## 4.1 Extract first product details save into csv file. e.g# Asus VivoBook X4 (product_name, product_link, product_img, product_price, product_details, product_reviews_number, product_reviews_star_number )

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops')

In [6]:
soup=BeautifulSoup(driver.page_source,'html')
first_pro=soup.find('div',class_='col-md-4 col-xl-4 col-lg-4')
list=[]
dic={
    'product_name':'',
    'product_link':'',
    'product_img':'',
    'product_price':'',
    'product_details':'',
    'product_reviews_number':'',
    'product_reviews_star_number':'',
}
dic['product_name']=first_pro.find('a').text.strip()
dic['product_link']=first_pro.find('a')['href']
dic['product_img']=first_pro.find('img')['src']
dic['product_price']=first_pro.find('h4',class_='price float-end pull-right').text.strip()
dic['product_details']=first_pro.find('p',class_='card-text description').text.strip()
dic['product_reviews_number']=first_pro.find('p',class_='review-count float-end pull-right').text.strip()
list.append(dic)
df=pd.DataFrame(list)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Asus VivoBook X4,/test-sites/e-commerce/ajax/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",1 reviews,

In [7]:
df.to_csv('wesraper q1.csv',index=False)

## 4.2 Extract product details from first row & save into csv file. e.g# Packard 255 G2, Aspire E1-510, ThinkPad T540p

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops')
soup=BeautifulSoup(driver.page_source,'html')
first_products=soup.find_all('div',class_='col-md-4 col-xl-4 col-lg-4')
list=[]
for first_pro in first_products[0:3:1]:
    dic={
        'product_name':'',
        'product_link':'',
        'product_img':'',
        'product_price':'',
        'product_details':'',
        'product_reviews_number':'',
        'product_reviews_star_number':'',
    }
    dic['product_name']=first_pro.find('a').text.strip()
    dic['product_link']=first_pro.find('a')['href']
    dic['product_img']=first_pro.find('img')['src']
    dic['product_price']=first_pro.find('h4',class_='price float-end pull-right').text.strip()
    dic['product_details']=first_pro.find('p',class_='card-text description').text.strip()
    dic['product_reviews_number']=first_pro.find('p',class_='review-count float-end pull-right').text.strip()
    list.append(dic)
df=pd.DataFrame(list)
df

In [11]:
df.to_csv('wesraper q2.csv',index=False)

## 4.3 Extract all product details from first page & save into csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops')
soup=BeautifulSoup(driver.page_source,'html')
first_products=soup.find_all('div',class_='col-md-4 col-xl-4 col-lg-4')
list=[]
for first_pro in first_products:
    dic={
        'product_name':'',
        'product_link':'',
        'product_img':'',
        'product_price':'',
        'product_details':'',
        'product_reviews_number':'',
        'product_reviews_star_number':'',
    }
    dic['product_name']=first_pro.find('a').text.strip()
    dic['product_link']=first_pro.find('a')['href']
    dic['product_img']=first_pro.find('img')['src']
    dic['product_price']=first_pro.find('h4',class_='price float-end pull-right').text.strip()
    dic['product_details']=first_pro.find('p',class_='card-text description').text.strip()
    dic['product_reviews_number']=first_pro.find('p',class_='review-count float-end pull-right').text.strip()
    list.append(dic)
df=pd.DataFrame(list)
df

In [13]:
df.to_csv('wesraper q3.csv',index=False)

## 4.4 Extract all product details from second page & save into another csv file.

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops')
soup=BeautifulSoup(driver.page_source,'html')
products=soup.find_all('div',class_='col-md-4 col-xl-4 col-lg-4')
list1=[]
for i in products:
    dic={
        'product_name':'',
        'product_link':'',
        'product_img':'',
        'product_price':'',
        'product_details':'',
        'product_reviews_number':'',
        'product_reviews_star_number':'',
    }
    dic['product_name']=i.find('a').text.strip()
    dic['product_link']=i.find('a')['href']
    dic['product_img']=i.find('img')['src']
    dic['product_price']=i.find('h4',class_='price float-end pull-right').text.strip()
    dic['product_details']=i.find('p',class_='card-text description').text.strip()
    dic['product_reviews_number']=i.find('p',class_='review-count float-end pull-right').text.strip()
    list1.append(dic)
driver.quit()
df=pd.DataFrame(list1)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Asus VivoBook X4,/test-sites/e-commerce/ajax/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",1 reviews,
1,Prestigio SmartB,/test-sites/e-commerce/ajax/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",9 reviews,
2,Prestigio SmartB,/test-sites/e-commerce/ajax/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",9 reviews,
3,Aspire E1-510,/test-sites/e-commerce/ajax/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews,
4,Lenovo V110-15IA,/test-sites/e-commerce/ajax/product/63,/images/test-sites/e-commerce/items/cart2.png,$321.94,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",12 reviews,
5,Lenovo V110-15IA,/test-sites/e-commerce/ajax/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,12 reviews,

In [41]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops')
soup=BeautifulSoup(driver.page_source,'html')

In [38]:
driver.find_element("xpath","//button[@class='acceptCookies']").click()

In [ ]:
soup.prettify()

In [27]:
btns = driver.find_elements("xpath","//button[@class='btn btn-default page-link page']")
len(btns)

19

In [40]:
btns = driver.find_element("xpath","//a[contains(text(),'More')]")
btns.click()

In [44]:
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [28]:
btns[0].text

'2'

In [30]:
btns[0].click()

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops')
soup=BeautifulSoup(driver.page_source,'html')

## 5.1 Extract first product details save into csv file. e.g# Asus VivoBook X4

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/more/computers/laptops')

In [2]:
soup=BeautifulSoup(driver.page_source,'html')
first_pro=soup.find('div',class_='col-md-4 col-xl-4 col-lg-4')
list=[]
dic={
    'product_name':'',
    'product_link':'',
    'product_img':'',
    'product_price':'',
    'product_details':'',
    'product_reviews_number':'',
    'product_reviews_star_number':'',
}
dic['product_name']=first_pro.find('a').text.strip()
dic['product_link']=first_pro.find('a')['href']
dic['product_img']=first_pro.find('img')['src']
dic['product_price']=first_pro.find('h4',class_='price float-end pull-right').text.strip()
dic['product_details']=first_pro.find('p',class_='card-text description').text.strip()
dic['product_reviews_number']=first_pro.find('p',class_='review-count float-end pull-right').text.strip()
list.append(dic)
df=pd.DataFrame(list)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Asus VivoBook X4,/test-sites/e-commerce/more/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",1 reviews,

## 5.2 Extract product details from first row & save into csv file. e.g# Asus VivoBook X4, Prestigio SmartB , Asus VivoBook X4

In [3]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/more/computers/laptops')
soup=BeautifulSoup(driver.page_source,'html')
first_products=soup.find_all('div',class_='col-md-4 col-xl-4 col-lg-4')
list=[]
for first_pro in first_products[0:3:1]:
    dic={
        'product_name':'',
        'product_link':'',
        'product_img':'',
        'product_price':'',
        'product_details':'',
        'product_reviews_number':'',
        'product_reviews_star_number':'',
    }
    dic['product_name']=first_pro.find('a').text.strip()
    dic['product_link']=first_pro.find('a')['href']
    dic['product_img']=first_pro.find('img')['src']
    dic['product_price']=first_pro.find('h4',class_='price float-end pull-right').text.strip()
    dic['product_details']=first_pro.find('p',class_='card-text description').text.strip()
    dic['product_reviews_number']=first_pro.find('p',class_='review-count float-end pull-right').text.strip()
    list.append(dic)
df=pd.DataFrame(list)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Asus VivoBook X4,/test-sites/e-commerce/more/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",1 reviews,
1,Prestigio SmartB,/test-sites/e-commerce/more/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",9 reviews,
2,Prestigio SmartB,/test-sites/e-commerce/more/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",9 reviews,

## 5.3 Extract all product details from first page & save into csv file.

In [3]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/more/computers/laptops')
time.sleep(3)
driver.find_element("xpath","//button[@class='acceptCookies']").click()
driver.find_element("xpath","//a[@class = 'btn btn-lg btn-block btn-primary ecomerce-items-scroll-more']").click()
time.sleep(3)
list=[]
soup=BeautifulSoup(driver.page_source,'html')
first_products=soup.find_all('div',class_='col-md-4 col-xl-4 col-lg-4')
for first_pro in first_products:
    dic={
        'product_name':'',
        'product_link':'',
        'product_img':'',
        'product_price':'',
        'product_details':'',
        'product_reviews_number':'',
        'product_reviews_star_number':'',
    }
    dic['product_name']=first_pro.find('a').text.strip()
    dic['product_link']=first_pro.find('a')['href']
    dic['product_img']=first_pro.find('img')['src']
    dic['product_price']=first_pro.find('h4',class_='price float-end pull-right').text.strip()
    dic['product_details']=first_pro.find('p',class_='card-text description').text.strip()
    dic['product_reviews_number']=first_pro.find('p',class_='review-count float-end pull-right').text.strip()
    list.append(dic)
df=pd.DataFrame(list)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Asus VivoBook X4,/test-sites/e-commerce/more/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",1 reviews,
1,Prestigio SmartB,/test-sites/e-commerce/more/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",9 reviews,
2,Prestigio SmartB,/test-sites/e-commerce/more/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",9 reviews,
3,Aspire E1-510,/test-sites/e-commerce/more/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews,
4,Lenovo V110-15IA,/test-sites/e-commerce/more/product/63,/images/test-sites/e-commerce/items/cart2.png,$321.94,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",12 reviews,
5,Lenovo V110-15IA,/test-sites/e-commerce/more/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,12 reviews,
6,Hewlett Packard,/test-sites/e-commerce/more/product/65,/images/test-sites/e-commerce/items/cart2.png,$364.46,"Hewlett Packard 250 G6 Dark Ash Silver, 15.6"" ...",11 reviews,
7,Acer Aspire 3 A3,/test-sites/e-commerce/more/product/66,/images/test-sites/e-commerce/items/cart2.png,$372.7,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Celeron...",3 reviews,
8,Acer Aspire A315,/test-sites/e-commerce/more/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",3 reviews,
9,Acer Aspire ES1-,/test-sites/e-commerce/more/product/68,/images/test-sites/e-commerce/items/cart2.png,$379.95,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",3 reviews,
10,Acer Aspire 3 A3,/test-sites/e-commerce/more/product/69,/images/test-sites/e-commerce/items/cart2.png,$391.48,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",3 reviews,
11,Acer Aspire 3 A3,/test-sites/e-commerce/more/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",3 reviews,

In [ ]:
##