# 7. https://webscraper.io/test-sites/e-commerce/static/computers/laptops (product_name, product_link, product_img, product_price, product_details, product_reviews_number, product_reviews_star_number )

#	7.1 Extract first product details save into csv file. e.g# Packard 255 G2

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url="https://webscraper.io/test-sites/e-commerce/static/computers/laptops"
r=requests.get(url)
r.status_code

200

In [3]:
soup=BeautifulSoup(r.text,"html")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="8g3Q6YhS39wAyy090BwgbZDy1Jng7oiT">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Static | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" rel="canonical"/>
<meta content="Static | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$416.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
						Packard 255 G2
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$306.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$1178.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">
						ThinkPad T540p
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$739.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">
						ProBook
					</a>
</h4>
<p class="description card-text" itemprop="description">14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">8</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$1311.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">
						ThinkPad X240
					</a>
</h4>
<p class="description card-text" itemprop="description">12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$581.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">
						Aspire E1-572G
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
</div>
<div id="static-pagination">
<nav>
<ul class="pagination">
<li aria-disabled="true" aria-label="« Previous" class="page-item disabled">
<span aria-hidden="true" class="page-link">‹</span>
</li>
<li aria-current="page" class="page-item active"><span class="page-link">1</span></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=2">2</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">3</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">4</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">5</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">6</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=7">7</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=8">8</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=9">9</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=10">10</a></li>
<li aria-disabled="true" class="page-item disabled"><span class="page-link">...</span></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=19">19</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=20">20</a></li>
<li class="page-item">
<a aria-label="Next »" class="page-link next" href="/test-sites/e-commerce/static/computers/laptops?page=2" rel="next">›</a>
</li>
</ul>
</nav>
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
<div class="push"></div>
</div>
<div class="container-fluid footer" id="layout-footer">
<div class="container">
<div class="row">
<div class="col-lg-3">
<ul>
<li><p>Products</p></li>
<li>
<a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
							Web Scraper browser extension
						</a>
</li>
<li>
<a href="/cloud-scraper">Web Scraper Cloud</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Company</p></li>
<li>
<a href="/about-us">About us</a>
</li>
<li>
<a href="/contact">Contact</a>
</li>
<li>
<a href="/privacy-policy">Website Privacy Policy</a>
</li>
<li>
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a>
</li>
<li>
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a>
</li>
<li><a href="/jobs">Jobs</a></li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Resources</p></li>
<li><a href="/blog">Blog</a></li>
<li>
<a href="/documentation">Documentation</a>
</li>
<li>
<a href="/tutorials">Video Tutorials</a>
</li>
<li>
<a href="/screenshots">Screenshots</a>
</li>
<li>
<a href="/test-sites">Test Sites</a>
</li>
<li>
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
<li>
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>CONTACT US</p></li>
<li>
<a href="mailto:info@webscraper.io">info@webscraper.io</a>
</li>
<li>Ubelu 5-71,<br/> Adazi, Latvia, LV-2164</li>
</ul>
<ul class="smedia">
<li>
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a>
</li>
<li>
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="browser-icon ws-icon ws-icon-chrome-dark"></i>
</a>
</li>
</ul>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<p class="copyright">Copyright © 2025
					<b>Web Scraper</b> | All rights reserved</p>
</div>
</div>
</div>
</div>
</body>
</html>

In [4]:
First_product=soup.find("div",class_="col-md-4 col-xl-4 col-lg-4")
First_product

<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$416.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
						Packard 255 G2
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>

In [5]:
First_product.text

'\n\n\n\n\n\n$416.99\n\n\n\n\n\t\t\t\t\t\tPackard 255 G2\n\t\t\t\t\t\n\n15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1\n\n\n\n2 reviews\n\t\t\t\t\n\n\n\n\n\n\n\n'

In [6]:
product_name=First_product.find("a",class_="title").text.strip()
product_name

'Packard 255 G2'

In [7]:
product_link=First_product.find("a",class_="title")["href"]
product_link

'/test-sites/e-commerce/static/product/31'

In [8]:
product_reviews_number=First_product.find("p",class_="review-count float-end").text.strip()
product_reviews_number

'2 reviews'

In [9]:
product_price=First_product.find("h4",class_="price float-end card-title pull-right").text.strip()
product_price

'$416.99'

In [11]:
product_details=First_product.find('p').text

product_details

'15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1'

In [13]:
product_img=First_product.find('img')['src']
product_img

'/images/test-sites/e-commerce/items/cart2.png'

In [14]:
list=[]
dict={
    "Product Name":'',
    "Product Link":"",
    "Product Reviews Number":"",
    "Product Price":"",
    "product_details":"",
    "product_img":"",
}
dict["Product Name"]=First_product.find("a",class_="title").text.strip()
dict["Product Link"]=First_product.find("a",class_="title")["href"]
dict["Product Reviews Number"]=First_product.find("p",class_="review-count float-end").text.strip()
dict["Product Price"]=First_product.find("h4",class_="price float-end card-title pull-right").text.strip()
dict["product_details"]=First_product.find('p').text.strip()
dict["product_img"]=First_product.find('img')['src']
list.append(dict)   
list

[{'Product Name': 'Packard 255 G2',
  'Product Link': '/test-sites/e-commerce/static/product/31',
  'Product Reviews Number': '2 reviews',
  'Product Price': '$416.99',
  'product_details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'}]

In [15]:
df=pd.DataFrame(list)
df

,Product Name,Product Link,Product Reviews Number,Product Price,product_details,product_img
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,2 reviews,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",/images/test-sites/e-commerce/items/cart2.png

In [16]:
df.to_csv("web_scraper2_q_7_1.csv",index=False)

# 7.2 Extract product details from first row & save into csv file. e.g# Packard 255 G2, Aspire E1-510, ThinkPad T540p

In [18]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url="https://webscraper.io/test-sites/e-commerce/static/computers/laptops"
r=requests.get(url)
r.status_code
soup=BeautifulSoup(r.text,"html")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="3ckZz4IlRXOeyaRavWCqjweWmTVwohJd">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Static | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" rel="canonical"/>
<meta content="Static | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$416.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
						Packard 255 G2
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$306.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$1178.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">
						ThinkPad T540p
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$739.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">
						ProBook
					</a>
</h4>
<p class="description card-text" itemprop="description">14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">8</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$1311.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">
						ThinkPad X240
					</a>
</h4>
<p class="description card-text" itemprop="description">12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$581.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">
						Aspire E1-572G
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
</div>
<div id="static-pagination">
<nav>
<ul class="pagination">
<li aria-disabled="true" aria-label="« Previous" class="page-item disabled">
<span aria-hidden="true" class="page-link">‹</span>
</li>
<li aria-current="page" class="page-item active"><span class="page-link">1</span></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=2">2</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">3</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">4</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">5</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">6</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=7">7</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=8">8</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=9">9</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=10">10</a></li>
<li aria-disabled="true" class="page-item disabled"><span class="page-link">...</span></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=19">19</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=20">20</a></li>
<li class="page-item">
<a aria-label="Next »" class="page-link next" href="/test-sites/e-commerce/static/computers/laptops?page=2" rel="next">›</a>
</li>
</ul>
</nav>
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
<div class="push"></div>
</div>
<div class="container-fluid footer" id="layout-footer">
<div class="container">
<div class="row">
<div class="col-lg-3">
<ul>
<li><p>Products</p></li>
<li>
<a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
							Web Scraper browser extension
						</a>
</li>
<li>
<a href="/cloud-scraper">Web Scraper Cloud</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Company</p></li>
<li>
<a href="/about-us">About us</a>
</li>
<li>
<a href="/contact">Contact</a>
</li>
<li>
<a href="/privacy-policy">Website Privacy Policy</a>
</li>
<li>
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a>
</li>
<li>
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a>
</li>
<li><a href="/jobs">Jobs</a></li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Resources</p></li>
<li><a href="/blog">Blog</a></li>
<li>
<a href="/documentation">Documentation</a>
</li>
<li>
<a href="/tutorials">Video Tutorials</a>
</li>
<li>
<a href="/screenshots">Screenshots</a>
</li>
<li>
<a href="/test-sites">Test Sites</a>
</li>
<li>
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
<li>
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>CONTACT US</p></li>
<li>
<a href="mailto:info@webscraper.io">info@webscraper.io</a>
</li>
<li>Ubelu 5-71,<br/> Adazi, Latvia, LV-2164</li>
</ul>
<ul class="smedia">
<li>
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a>
</li>
<li>
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="browser-icon ws-icon ws-icon-chrome-dark"></i>
</a>
</li>
</ul>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<p class="copyright">Copyright © 2025
					<b>Web Scraper</b> | All rights reserved</p>
</div>
</div>
</div>
</div>
</body>
</html>

In [19]:
first_row=soup.find_all("div",class_="row")
len(first_row)

5

In [21]:
all_products = first_row[1].find_all("div",class_="col-md-4 col-xl-4 col-lg-4")[:3]
len(all_products)

3

In [22]:
list=[]
for i in all_products:
    dict={
        "Product Name":'',
        "Product Link":"",
        "Product Reviews Number":"",
        "Product Price":"",
        "product_details":"",
        "product_img":"",
    }
    dict["Product Name"]=i.find("a",class_="title").text.strip()
    dict["Product Link"]=i.find("a",class_="title")["href"]
    dict["Product Reviews Number"]=i.find("p",class_="review-count float-end").text.strip()
    dict["Product Price"]=i.find("h4",class_="price float-end card-title pull-right").text.strip()
    dict["product_details"]=i.find('p').text.strip()
    dict["product_img"]=i.find('img')['src']
    list.append(dict)   
list

[{'Product Name': 'Packard 255 G2',
  'Product Link': '/test-sites/e-commerce/static/product/31',
  'Product Reviews Number': '2 reviews',
  'Product Price': '$416.99',
  'product_details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'Aspire E1-510',
  'Product Link': '/test-sites/e-commerce/static/product/32',
  'Product Reviews Number': '2 reviews',
  'Product Price': '$306.99',
  'product_details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'ThinkPad T540p',
  'Product Link': '/test-sites/e-commerce/static/product/33',
  'Product Reviews Number': '2 reviews',
  'Product Price': '$1178.99',
  'product_details': '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'}]

In [ ]:
#import pandas as pd
df=pd.DataFrame(list)
df

,Product Name,Product Link,Product Reviews Number,Product Price,product_details,product_img
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,2 reviews,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",/images/test-sites/e-commerce/items/cart2.png
1,Aspire E1-510,/test-sites/e-commerce/static/product/32,2 reviews,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",/images/test-sites/e-commerce/items/cart2.png
2,ThinkPad T540p,/test-sites/e-commerce/static/product/33,2 reviews,$1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",/images/test-sites/e-commerce/items/cart2.png

In [26]:
df.to_csv("web_scraper2_q_7_2.csv",index=False)

# 7.3 Extract all product details from first page & save into csv file.

In [27]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url="https://webscraper.io/test-sites/e-commerce/static/computers/laptops"
r=requests.get(url)
r.status_code
soup=BeautifulSoup(r.text,"html")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="3i6teo5JlnC4XfCIuNSUo6zFLlXa00Ds">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Static | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" rel="canonical"/>
<meta content="Static | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$416.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
						Packard 255 G2
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$306.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$1178.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">
						ThinkPad T540p
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$739.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">
						ProBook
					</a>
</h4>
<p class="description card-text" itemprop="description">14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">8</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$1311.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">
						ThinkPad X240
					</a>
</h4>
<p class="description card-text" itemprop="description">12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$581.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">
						Aspire E1-572G
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
</div>
<div id="static-pagination">
<nav>
<ul class="pagination">
<li aria-disabled="true" aria-label="« Previous" class="page-item disabled">
<span aria-hidden="true" class="page-link">‹</span>
</li>
<li aria-current="page" class="page-item active"><span class="page-link">1</span></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=2">2</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">3</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">4</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">5</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">6</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=7">7</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=8">8</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=9">9</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=10">10</a></li>
<li aria-disabled="true" class="page-item disabled"><span class="page-link">...</span></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=19">19</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=20">20</a></li>
<li class="page-item">
<a aria-label="Next »" class="page-link next" href="/test-sites/e-commerce/static/computers/laptops?page=2" rel="next">›</a>
</li>
</ul>
</nav>
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
<div class="push"></div>
</div>
<div class="container-fluid footer" id="layout-footer">
<div class="container">
<div class="row">
<div class="col-lg-3">
<ul>
<li><p>Products</p></li>
<li>
<a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
							Web Scraper browser extension
						</a>
</li>
<li>
<a href="/cloud-scraper">Web Scraper Cloud</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Company</p></li>
<li>
<a href="/about-us">About us</a>
</li>
<li>
<a href="/contact">Contact</a>
</li>
<li>
<a href="/privacy-policy">Website Privacy Policy</a>
</li>
<li>
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a>
</li>
<li>
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a>
</li>
<li><a href="/jobs">Jobs</a></li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Resources</p></li>
<li><a href="/blog">Blog</a></li>
<li>
<a href="/documentation">Documentation</a>
</li>
<li>
<a href="/tutorials">Video Tutorials</a>
</li>
<li>
<a href="/screenshots">Screenshots</a>
</li>
<li>
<a href="/test-sites">Test Sites</a>
</li>
<li>
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
<li>
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>CONTACT US</p></li>
<li>
<a href="mailto:info@webscraper.io">info@webscraper.io</a>
</li>
<li>Ubelu 5-71,<br/> Adazi, Latvia, LV-2164</li>
</ul>
<ul class="smedia">
<li>
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a>
</li>
<li>
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="browser-icon ws-icon ws-icon-chrome-dark"></i>
</a>
</li>
</ul>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<p class="copyright">Copyright © 2025
					<b>Web Scraper</b> | All rights reserved</p>
</div>
</div>
</div>
</div>
</body>
</html>

In [28]:
first_row=soup.find_all("div",class_="row")
len(first_row)

5

In [29]:
all_products = first_row[1].find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
len(all_products)

6

In [30]:
list=[]
for i in all_products:
    dict={
        "Product Name":'',
        "Product Link":"",
        "Product Reviews Number":"",
        "Product Price":"",
        "product_details":"",
        "product_img":"",
    }
    dict["Product Name"]=i.find("a",class_="title").text.strip()
    dict["Product Link"]=i.find("a",class_="title")["href"]
    dict["Product Reviews Number"]=i.find("p",class_="review-count float-end").text.strip()
    dict["Product Price"]=i.find("h4",class_="price float-end card-title pull-right").text.strip()
    dict["product_details"]=i.find('p').text.strip()
    dict["product_img"]=i.find('img')['src']
    list.append(dict)   
list

[{'Product Name': 'Packard 255 G2',
  'Product Link': '/test-sites/e-commerce/static/product/31',
  'Product Reviews Number': '2 reviews',
  'Product Price': '$416.99',
  'product_details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'Aspire E1-510',
  'Product Link': '/test-sites/e-commerce/static/product/32',
  'Product Reviews Number': '2 reviews',
  'Product Price': '$306.99',
  'product_details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'ThinkPad T540p',
  'Product Link': '/test-sites/e-commerce/static/product/33',
  'Product Reviews Number': '2 reviews',
  'Product Price': '$1178.99',
  'product_details': '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'ProBook',
  'Product Link': '/test-sites/e-commerce/static/product/34',
  'Product Reviews Number': '8 reviews',
  'Product Price': '$739.99',
  'product_details': '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'ThinkPad X240',
  'Product Link': '/test-sites/e-commerce/static/product/35',
  'Product Reviews Number': '12 reviews',
  'Product Price': '$1311.99',
  'product_details': '12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'Aspire E1-572G',
  'Product Link': '/test-sites/e-commerce/static/product/36',
  'Product Reviews Number': '2 reviews',
  'Product Price': '$581.99',
  'product_details': '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'}]

In [31]:
df=pd.DataFrame(list)
df

,Product Name,Product Link,Product Reviews Number,Product Price,product_details,product_img
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,2 reviews,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",/images/test-sites/e-commerce/items/cart2.png
1,Aspire E1-510,/test-sites/e-commerce/static/product/32,2 reviews,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",/images/test-sites/e-commerce/items/cart2.png
2,ThinkPad T540p,/test-sites/e-commerce/static/product/33,2 reviews,$1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",/images/test-sites/e-commerce/items/cart2.png
3,ProBook,/test-sites/e-commerce/static/product/34,8 reviews,$739.99,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",/images/test-sites/e-commerce/items/cart2.png
4,ThinkPad X240,/test-sites/e-commerce/static/product/35,12 reviews,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",/images/test-sites/e-commerce/items/cart2.png
5,Aspire E1-572G,/test-sites/e-commerce/static/product/36,2 reviews,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",/images/test-sites/e-commerce/items/cart2.png

In [32]:
df.to_csv("web_scraper2_q_7_3.csv",index=False)

# 7.4 Extract all product details from second page & save into another csv file.

In [33]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url="https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page=2"
r=requests.get(url)
r.status_code
soup=BeautifulSoup(r.text,"html")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="XuiuwQmmDRRdTqWV6cOyM8WoiXncDD2V">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Static | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page=2" rel="canonical"/>
<meta content="Static | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page=2" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$1033.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/37" itemprop="name" title="ThinkPad Yoga">
						ThinkPad Yoga
					</a>
</h4>
<p class="description card-text" itemprop="description">12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">13</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$609.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/38" itemprop="name" title="Pavilion">
						Pavilion
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">4</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$745.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/39" itemprop="name" title="Inspiron 15">
						Inspiron 15
					</a>
</h4>
<p class="description card-text" itemprop="description">Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$1281.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/40" itemprop="name" title="Dell XPS 13">
						Dell XPS 13
					</a>
</h4>
<p class="description card-text" itemprop="description">13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">4</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$1244.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/41" itemprop="name" title="ThinkPad X230">
						ThinkPad X230
					</a>
</h4>
<p class="description card-text" itemprop="description">12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">10</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$520.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/42" itemprop="name" title="HP 250 G3">
						HP 250 G3
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">13</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
</div>
<div id="static-pagination">
<nav>
<ul class="pagination">
<li class="page-item">
<a aria-label="« Previous" class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=1" rel="prev">‹</a>
</li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=1">1</a></li>
<li aria-current="page" class="page-item active"><span class="page-link">2</span></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">3</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">4</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">5</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">6</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=7">7</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=8">8</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=9">9</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=10">10</a></li>
<li aria-disabled="true" class="page-item disabled"><span class="page-link">...</span></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=19">19</a></li>
<li class="page-item"><a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=20">20</a></li>
<li class="page-item">
<a aria-label="Next »" class="page-link next" href="/test-sites/e-commerce/static/computers/laptops?page=3" rel="next">›</a>
</li>
</ul>
</nav>
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
<div class="push"></div>
</div>
<div class="container-fluid footer" id="layout-footer">
<div class="container">
<div class="row">
<div class="col-lg-3">
<ul>
<li><p>Products</p></li>
<li>
<a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
							Web Scraper browser extension
						</a>
</li>
<li>
<a href="/cloud-scraper">Web Scraper Cloud</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Company</p></li>
<li>
<a href="/about-us">About us</a>
</li>
<li>
<a href="/contact">Contact</a>
</li>
<li>
<a href="/privacy-policy">Website Privacy Policy</a>
</li>
<li>
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a>
</li>
<li>
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a>
</li>
<li><a href="/jobs">Jobs</a></li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Resources</p></li>
<li><a href="/blog">Blog</a></li>
<li>
<a href="/documentation">Documentation</a>
</li>
<li>
<a href="/tutorials">Video Tutorials</a>
</li>
<li>
<a href="/screenshots">Screenshots</a>
</li>
<li>
<a href="/test-sites">Test Sites</a>
</li>
<li>
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
<li>
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>CONTACT US</p></li>
<li>
<a href="mailto:info@webscraper.io">info@webscraper.io</a>
</li>
<li>Ubelu 5-71,<br/> Adazi, Latvia, LV-2164</li>
</ul>
<ul class="smedia">
<li>
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a>
</li>
<li>
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="browser-icon ws-icon ws-icon-chrome-dark"></i>
</a>
</li>
</ul>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<p class="copyright">Copyright © 2025
					<b>Web Scraper</b> | All rights reserved</p>
</div>
</div>
</div>
</div>
</body>
</html>

In [34]:
first_row=soup.find_all("div",class_="row")
len(first_row)

5

In [36]:
all_products = first_row[1].find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
len(all_products)

6

In [37]:
list=[]
for i in all_products:
    dict={
        "Product Name":'',
        "Product Link":"",
        "Product Reviews Number":"",
        "Product Price":"",
        "product_details":"",
        "product_img":"",
    }
    dict["Product Name"]=i.find("a",class_="title").text.strip()
    dict["Product Link"]=i.find("a",class_="title")["href"]
    dict["Product Reviews Number"]=i.find("p",class_="review-count float-end").text.strip()
    dict["Product Price"]=i.find("h4",class_="price float-end card-title pull-right").text.strip()
    dict["product_details"]=i.find('p').text.strip()
    dict["product_img"]=i.find('img')['src']
    list.append(dict)   
list

[{'Product Name': 'ThinkPad Yoga',
  'Product Link': '/test-sites/e-commerce/static/product/37',
  'Product Reviews Number': '13 reviews',
  'Product Price': '$1033.99',
  'product_details': '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'Pavilion',
  'Product Link': '/test-sites/e-commerce/static/product/38',
  'Product Reviews Number': '4 reviews',
  'Product Price': '$609.99',
  'product_details': '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'Inspiron 15',
  'Product Link': '/test-sites/e-commerce/static/product/39',
  'Product Reviews Number': '12 reviews',
  'Product Price': '$745.99',
  'product_details': 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'Dell XPS 13',
  'Product Link': '/test-sites/e-commerce/static/product/40',
  'Product Reviews Number': '4 reviews',
  'Product Price': '$1281.99',
  'product_details': '13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'ThinkPad X230',
  'Product Link': '/test-sites/e-commerce/static/product/41',
  'Product Reviews Number': '10 reviews',
  'Product Price': '$1244.99',
  'product_details': '12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'},
 {'Product Name': 'HP 250 G3',
  'Product Link': '/test-sites/e-commerce/static/product/42',
  'Product Reviews Number': '13 reviews',
  'Product Price': '$520.99',
  'product_details': '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png'}]

In [38]:
df=pd.DataFrame(list)
df

,Product Name,Product Link,Product Reviews Number,Product Price,product_details,product_img
0,ThinkPad Yoga,/test-sites/e-commerce/static/product/37,13 reviews,$1033.99,"12.5"" Touch, Core i3-4010U, 4GB, 500GB + 16GB ...",/images/test-sites/e-commerce/items/cart2.png
1,Pavilion,/test-sites/e-commerce/static/product/38,4 reviews,$609.99,"15.6"", Core i5-4200U, 6GB, 750GB, Windows 8.1",/images/test-sites/e-commerce/items/cart2.png
2,Inspiron 15,/test-sites/e-commerce/static/product/39,12 reviews,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",/images/test-sites/e-commerce/items/cart2.png
3,Dell XPS 13,/test-sites/e-commerce/static/product/40,4 reviews,$1281.99,"13.3"" Touch, Core i5-4210U, 8GB, 128GB SSD, Wi...",/images/test-sites/e-commerce/items/cart2.png
4,ThinkPad X230,/test-sites/e-commerce/static/product/41,10 reviews,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",/images/test-sites/e-commerce/items/cart2.png
5,HP 250 G3,/test-sites/e-commerce/static/product/42,13 reviews,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",/images/test-sites/e-commerce/items/cart2.png

In [39]:
df.to_csv("web_scraper2_q_7_4.csv",index=False)

# 7.5 Extract all product details from first page to fifth page & save into single csv file.