
# 6. https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops (product_name, product_link, product_img, product_price, product_details, product_reviews_number, product_reviews_star_number )


# 6.1 Extract first product details save into csv file. e.g# Asus VivoBook X4

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r=requests.get(url)
r.status_code

200

In [7]:
soup=BeautifulSoup(r.text)
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="ugplmmCzts1MpAtgXKWn2hZsbIF5xlzh">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Allinone | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>
<meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">8</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$306.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$321.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">5</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$356.49</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">6</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$364.46</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
						Hewlett Packar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$372.7</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
						Acer Aspire 3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
						Acer Aspire A3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">0</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.95</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
						Acer Aspire ES...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">9</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$391.48</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>

In [8]:
first1=soup.find("div",class_="col-md-4 col-xl-4 col-lg-4")
first1

<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>

In [9]:
product_name=first1.find("a",class_="title").text.strip()
product_name

'Asus VivoBook...'

In [10]:
product_img=first1.find("img",class_="img-responsive").get("src")
product_img

'/images/test-sites/e-commerce/items/cart2.png'

In [11]:
product_details=first1.find("div",class_="caption").find("p",class_="description").text.strip()
product_details

'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd'

In [12]:
product_price=first1.find("h4",class_="price float-end card-title pull-right").text.strip()
product_price

'$295.99'

In [13]:
product_rating=first1.find("div",class_="ratings").text.strip()
product_rating

'14 reviews'

In [14]:
dl = []
dict={
    "Product Name":"",
    "Product Image":"",
    "Product Details":"",
    "Product Price":"",
    "Product Rating":""
}
dict["Product Name"]=first1.find("a",class_="title").text.strip()
dict["Product Image"]= first1.find("img",class_="img-responsive").get("src")
dict["Product Details"]=first1.find("div",class_="caption").find("p",class_="description").text.strip()
dict["Product Price"]=first1.find("h4",class_="price float-end card-title pull-right").text.strip()
dict["Product Rating"]=first1.find("div",class_="ratings").text.strip()
dl.append(dict)
dl

[{'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'Product Price': '$295.99',
  'Product Rating': '14 reviews'}]

In [15]:
import pandas as pd
df=pd.DataFrame(dl)
df

,Product Name,Product Image,Product Details,Product Price,Product Rating
0,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",$295.99,14 reviews

In [16]:
df.to_csv("web_scraper_q_6_1.csv",index=False)

# 6.2 Extract product details from first row & save into csv file. e.g# Asus VivoBook X4, Prestigio SmartB , prestigio SmartB

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
# url="https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops"
url="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r=requests.get(url)
r.status_code
soup=BeautifulSoup(r.text,"html")
soup
first_row=soup.find_all("div",class_="row")
len(first_row)
# all_products = first_row[2].find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
# len(all_products)

5

In [73]:
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="pywMOgvLhgnlZtw3xSRgYnUgUrCOVd8l">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Scroll | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops" rel="canonical"/>
<meta content="Scroll | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/scroll" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/scroll/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/scroll/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/scroll/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/scroll/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

In [5]:
all_products = first_row[2].find_all("div",class_="col-md-4 col-xl-4 col-lg-4")[:3]
len(all_products)

3

In [6]:
dl=[]
for i in all_products:
    dict={
        "Product Name":"",
        "Product Image":"",
        "Product Details":"",
        "Product Price":"",
        "Product Rating":"",
    }
    dict["Product Name"]=i.find("a",class_="title").text.strip()
    dict["Product Image"]= i.find("img",class_="img-responsive").get("src")
    dict["Product Details"]=i.find("div",class_="caption").find("p",class_="description").text.strip()
    dict["Product Price"]=i.find("h4",class_="price float-end card-title pull-right").text.strip()
    dict["Product Rating"]=i.find("div",class_="ratings").text.strip()
    dl.append(dict)
    
dl

[{'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'Product Price': '$295.99',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Prestigio Smar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Price': '$299',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Prestigio Smar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Price': '$299',
  'Product Rating': '12 reviews'}]

In [7]:
df=pd.DataFrame(dl)
df

,Product Name,Product Image,Product Details,Product Price,Product Rating
0,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",$295.99,14 reviews
1,Prestigio Smar...,/images/test-sites/e-commerce/items/cart2.png,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",$299,8 reviews
2,Prestigio Smar...,/images/test-sites/e-commerce/items/cart2.png,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",$299,12 reviews

In [8]:
df.to_csv("web_scraper_q_6_2.csv",index=False)

In [9]:
df.to_csv("web_scraper_q_6_21.csv")

# 6.3 Extract all product details from first page & save into csv file.

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r=requests.get(url)
r.status_code

200

In [11]:
soup=BeautifulSoup(r.text,"html")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="LvjOu0qsPgHvfmDxXWq5gkBW1uWmBIpg">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Allinone | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>
<meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">8</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$306.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$321.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">5</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$356.49</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">6</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$364.46</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
						Hewlett Packar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$372.7</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
						Acer Aspire 3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
						Acer Aspire A3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">0</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.95</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
						Acer Aspire ES...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">9</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$391.48</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>

In [14]:
all_products=soup.find_all("div",class_="row")
len(all_products)

5

In [16]:
all_products = first_row[2].find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$321.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$356.49</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$364.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
 						Hewlett Packar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$372.7</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$391.48</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$393.88</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/70" itemprop="name" title="Acer Aspire 3 A315-21">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/45" itemprop="name" title="Asus VivoBook Max">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/71" itemprop="name" title="Asus VivoBook E502NA-GO022T Dark Blue">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">3</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$404.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/72" itemprop="name" title="Lenovo ThinkPad E31-80">
 						Lenovo ThinkPa...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$408.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/73" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,

In [18]:
list=[]
for i in all_products:
    dict={
        "Product Name":"",
        "Product Image":"",
        "Product Details":"",
        "Product Price":"",
        "Product Rating":"",
    }
    dict["Product Name"]=i.find("a",class_="title").text.strip()
    dict["Product Image"]= i.find("img",class_="img-responsive").get("src")
    dict["Product Details"]=i.find("div",class_="caption").find("p",class_="description").text.strip()
    dict["Product Price"]=i.find("h4",class_="price float-end card-title pull-right").text.strip()
    dict["Product Rating"]=i.find("div",class_="ratings").text.strip()
    list.append(dict)
list

[{'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'Product Price': '$295.99',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Prestigio Smar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Price': '$299',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Prestigio Smar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Price': '$299',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Aspire E1-510',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'Product Price': '$306.99',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$321.94',
  'Product Rating': '5 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd',
  'Product Price': '$356.49',
  'Product Rating': '6 reviews'},
 {'Product Name': 'Hewlett Packar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS',
  'Product Price': '$364.46',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$372.7',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Acer Aspire A3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG',
  'Product Price': '$379.94',
  'Product Rating': '0 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux',
  'Product Price': '$379.95',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$391.48',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux',
  'Product Price': '$393.88',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home',
  'Product Price': '$399',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'Product Price': '$399.99',
  'Product Rating': '3 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$404.23',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$408.98',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$409.63',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home',
  'Product Price': '$410.46',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'Product Price': '$410.66',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Packard 255 G2',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'Product Price': '$416.99',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Asus EeeBook R...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd',
  'Product Price': '$433.3',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home',
  'Product Price': '$436.29',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home',
  'Product Price': '$436.29',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Acer Extensa 1...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'Product Price': '$439.73',
  'Product Rating': '6 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'Product Price': '$454.62',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro',
  'Product Price': '$454.73',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Acer Aspire A3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG',
  'Product Price': '$457.38',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS',
  'Product Price': '$465.95',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd',
  'Product Price': '$468.56',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$469.1',
  'Product Rating': '5 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$484.23',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux',
  'Product Price': '$485.9',
  'Product Rating': '6 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$487.8',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Acer Swift 1 S...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$488.64',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Dell Vostro 15',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux',
  'Product Price': '$488.78',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home',
  'Product Price': '$494.71',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Dell Vostro 15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux',
  'Product Price': '$497.17',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro',
  'Product Price': '$498.23',
  'Product Rating': '5 reviews'},
 {'Product Name': 'HP 250 G3',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
  'Product Price': '$520.99',
  'Product Rating': '13 reviews'},
 {'Product Name': 'Acer Spin 5',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$564.98',
  'Product Rating': '0 reviews'},
 {'Product Name': 'HP 350 G1',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows',
  'Product Price': '$577.99',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Aspire E1-572G',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
  'Product Price': '$581.99',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Pavilion',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
  'Product Price': '$609.99',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Acer Aspire A5...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG',
  'Product Price': '$679',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux',
  'Product Price': '$679',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd',
  'Product Price': '$729',
  'Product Rating': '2 reviews'},
 {'Product Name': 'ProBook',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
  'Product Price': '$739.99',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Inspiron 15',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
  'Product Price': '$745.99',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS',
  'Product Price': '$799',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Acer Nitro 5 A...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Price': '$809',
  'Product Rating': '0 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS + Windows 10 Home',
  'Product Price': '$899',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo ThinkPad L570, 15.6" FHD, Core i7-7500U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$999',
  'Product Rating': '11 reviews'},
 {'Product Name': 'ThinkPad Yoga',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
  'Product Price': '$1033.99',
  'Product Rating': '13 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo ThinkPad L460, 14" FHD IPS, Core i7-6600U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1096.02',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 4GB, Windows 10 Home',
  'Product Price': '$1098.42',
  'Product Rating': '7 reviews'},
 {'Product Name': 'MSI GL72M 7RDX',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'MSI GL72M 7RDX, 17.3" FHD, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Price': '$1099',
  'Product Rating': '1 reviews'},
 {'Product Name': 'MSI GL72M 7RDX',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG Strix GL553VD-DM535T, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home, Eng kbd',
  'Product Price': '$1099',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Apple MacBook Air 13.3", Core i5 1.8GHz, 8GB, 128GB SSD, Intel HD 4000, RUS',
  'Product Price': '$1101.83',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5280, 12.5" HD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1102.66',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Linux + Windows 10 Home',
  'Product Price': '$1110.14',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo Legion Y520-15IKBM, Black, 15.6" FHD IPS, Core i5-7300HQ, 8 GB, 128GB SSD + 2 TB HDD, NVIDIA GeForce GTX 1060 6 GB, FreeDOS + Windows 10 Home',
  'Product Price': '$1112.91',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Toshiba Portege Z30-C-16J Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1114.55',
  'Product Rating': '0 reviews'},
 {'Product Name': 'Acer Predator...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050Ti 4GB, Windows 10 Home',
  'Product Price': '$1123.87',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Acer Aspire 7...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 7 A715-71G, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB HDD, GTX 1050 Ti 4GB, Windows 10 Home',
  'Product Price': '$1123.87',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Inspiron 17 2in1 (7779) Silver, 17.3" FHD Touch, Core i5-7200U, 12GB, 1TB, GeForce GT940MX 2GB, Windows 10 Home',
  'Product Price': '$1124.2',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Windows 10 Pro',
  'Product Price': '$1133.82',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo Legion Y520, 15.6" FHD, Core i7-7700HQ, 8GB, 128 GB SSD + 1TB HDD, GTX 1050 4GB, Windows 10 Home',
  'Product Price': '$1133.91',
  'Product Rating': '13 reviews'},
 {'Product Name': 'Asus AsusPro A...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus AsusPro Advanced BU401LA-FA271G Dark Grey, 14", Core i5-4210U, 4GB, 128GB SSD, Win7 Pro 64bit, ENG',
  'Product Price': '$1139.54',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Acer Nitro 5 A...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD +1TB, GeForce GTX 1050 Ti 4GB, Windows 10 Home + Windows 10 Home',
  'Product Price': '$1140.62',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7440HQ, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1143.4',
  'Product Rating': '5 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',

In [19]:
df=pd.DataFrame(list)
df

,Product Name,Product Image,Product Details,Product Price,Product Rating
0,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",$295.99,14 reviews
1,Prestigio Smar...,/images/test-sites/e-commerce/items/cart2.png,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",$299,8 reviews
2,Prestigio Smar...,/images/test-sites/e-commerce/items/cart2.png,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",$299,12 reviews
3,Aspire E1-510,/images/test-sites/e-commerce/items/cart2.png,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",$306.99,2 reviews
4,Lenovo V110-15...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",$321.94,5 reviews
...,...,...,...,...,...
112,Lenovo Legion...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo Legion Y720, 15.6"" FHD IPS, Core i7-770...",$1399,8 reviews
113,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",$1399,10 reviews
114,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix GL702ZC-GC154T, 17.3"" FHD, Ryze...",$1769,7 reviews
115,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix GL702ZC-GC209T, 17.3"" FHD IPS, ...",$1769,8 reviews
116,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",$1799,8 reviews

In [20]:
df.to_csv("web_scraper_q_6_3.csv",index=False)

In [21]:
df.to_csv("web_scraper_q_6_31.csv")

# 6.4 Extract all product details of first column save into csv file.

In [22]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r=requests.get(url)
r.status_code
soup=BeautifulSoup(r.text,"html")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="jOODF4gFSZrljohhiBkTY4uM6HGgEhhL">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Allinone | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>
<meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">8</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$306.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$321.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">5</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$356.49</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">6</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$364.46</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
						Hewlett Packar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$372.7</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
						Acer Aspire 3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
						Acer Aspire A3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">0</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.95</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
						Acer Aspire ES...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">9</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$391.48</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>

In [ ]:
all_products=soup.find_all("div",class_="row")
len(all_products)

5

In [25]:
all_products = first_row[2].find_all("div",class_="col-md-4 col-xl-4 col-lg-4")[0:117:3]
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$364.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
 						Hewlett Packar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/45" itemprop="name" title="Asus VivoBook Max">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$408.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/73" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$410.66</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/76" itemprop="name" title="Asus VivoBook 15 X540NA-GQ026T">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$436.29</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/78" itemprop="name" title="Acer Aspire 3 A315-51">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">1</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$454.62</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/81" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$465.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/84" itemprop="name" title="Lenovo V110-15IKB">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">7</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$484.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/87" itemprop="name" title="Lenovo V510 Black">
 						Lenovo V510 Bl...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$488.64</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/90" itemprop="name" title="Acer Swift 1 SF113-31 Silver">
 						Acer Swift 1 S...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$497.17</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/92" itemprop="name" title="Dell Vostro 15 (3568) Red">
 						Dell Vostro 15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$564.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/47" itemprop="name" title="Acer Spin 5">
 						Acer Spin 5
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$609.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/38" itemprop="name" title="Pavilion">
 						Pavilion
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$729</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/50" itemprop="name" title="Asus VivoBook S14">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$799</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>

In [26]:
list=[]
for C1 in all_products:
    dict={
        "Product Name":"",
        "Product Image":"",
        "Product Details":"",
        "Product Price":"",
        "Product Rating":"",
    }
    dict["Product Name"]=C1.find("a",class_="title").text.strip()
    dict["Product Image"]= C1.find("img",class_="img-responsive").get("src")
    dict["Product Details"]=C1.find("div",class_="caption").find("p",class_="description").text.strip()
    dict["Product Price"]=C1.find("h4",class_="price float-end card-title pull-right").text.strip()
    dict["Product Rating"]=C1.find("div",class_="ratings").text.strip()
    list.append(dict)
list

[{'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'Product Price': '$295.99',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Aspire E1-510',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'Product Price': '$306.99',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Hewlett Packar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS',
  'Product Price': '$364.46',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux',
  'Product Price': '$379.95',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home',
  'Product Price': '$399',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$408.98',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'Product Price': '$410.66',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home',
  'Product Price': '$436.29',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'Product Price': '$454.62',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS',
  'Product Price': '$465.95',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$484.23',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Acer Swift 1 S...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$488.64',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Dell Vostro 15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux',
  'Product Price': '$497.17',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Acer Spin 5',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$564.98',
  'Product Rating': '0 reviews'},
 {'Product Name': 'Pavilion',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
  'Product Price': '$609.99',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd',
  'Product Price': '$729',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS',
  'Product Price': '$799',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo ThinkPad L570, 15.6" FHD, Core i7-7500U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$999',
  'Product Rating': '11 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 4GB, Windows 10 Home',
  'Product Price': '$1098.42',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Apple MacBook Air 13.3", Core i5 1.8GHz, 8GB, 128GB SSD, Intel HD 4000, RUS',
  'Product Price': '$1101.83',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo Legion Y520-15IKBM, Black, 15.6" FHD IPS, Core i5-7300HQ, 8 GB, 128GB SSD + 2 TB HDD, NVIDIA GeForce GTX 1060 6 GB, FreeDOS + Windows 10 Home',
  'Product Price': '$1112.91',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Acer Aspire 7...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 7 A715-71G, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB HDD, GTX 1050 Ti 4GB, Windows 10 Home',
  'Product Price': '$1123.87',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo Legion Y520, 15.6" FHD, Core i7-7700HQ, 8GB, 128 GB SSD + 1TB HDD, GTX 1050 4GB, Windows 10 Home',
  'Product Price': '$1133.91',
  'Product Rating': '13 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7440HQ, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1143.4',
  'Product Rating': '5 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo Legion Y520-15IKBM, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB, GeForce GTX 1060 Max-Q 6GB, DOS',
  'Product Price': '$1149',
  'Product Rating': '11 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Toshiba Portege Z30-C-16L Grey, 13.3" FHD, Core i7-6500U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1154.04',
  'Product Rating': '7 reviews'},
 {'Product Name': 'ThinkPad T540p',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit',
  'Product Price': '$1178.99',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Acer Predator...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ. 8GB, 128GB SSD +1TB, GeForce GTX 1050Ti 4GB, Linux + Windows 10 Home',
  'Product Price': '$1187.98',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Lenovo Yoga 91...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo Yoga 910 Grey, 13.9" FHD Touch, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home',
  'Product Price': '$1199.73',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Acer Predator...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home',
  'Product Price': '$1221.58',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux',
  'Product Price': '$1238.37',
  'Product Rating': '0 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG Strix GL753VE-GC096T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home, Eng kbd',
  'Product Price': '$1259',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Hewlett Packar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Hewlett Packard Spectre 13-v106na Dark Ash Silver, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home',
  'Product Price': '$1273.11',
  'Product Rating': '8 reviews'},
 {'Product Name': 'MSI GL62VR 7RF...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'MSI GL62VR 7RFX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 256GB SSD, GeForce GTX 1060 3GB, Windows 10 Home',
  'Product Price': '$1299',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Hewlett Packar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Hewlett Packard ProBook 640 G3, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1326.83',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux + Windows 10 Home',
  'Product Price': '$1338.37',
  'Product Rating': '11 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo ThinkPad T470, 14" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1349.23',
  'Product Rating': '5 reviews'},
 {'Product Name': 'Asus ASUSPRO B...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ASUSPRO B9440UA-GV0279R Gray, 14" FHD, Core i7-7500U, 16GB, 512GB SSD, Windows 10 Pro, Eng kbd',
  'Product Price': '$1381.13',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG Strix GL702ZC-GC154T, 17.3" FHD, Ryzen 7 1700, 16GB, 256GB + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
  'Product Price': '$1769',
  'Product Rating': '7 reviews'}]

In [27]:
df=pd.DataFrame(list)
df

,Product Name,Product Image,Product Details,Product Price,Product Rating
0,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",$295.99,14 reviews
1,Aspire E1-510,/images/test-sites/e-commerce/items/cart2.png,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",$306.99,2 reviews
2,Hewlett Packar...,/images/test-sites/e-commerce/items/cart2.png,"Hewlett Packard 250 G6 Dark Ash Silver, 15.6"" ...",$364.46,12 reviews
3,Acer Aspire ES...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",$379.95,9 reviews
4,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,Asus VivoBook Max X541NA-GQ041 Black Chocolate...,$399,4 reviews
5,Acer Aspire 3...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",$408.98,10 reviews
6,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,Asus VivoBook 15 X540NA-GQ026T Chocolate Black...,$410.66,4 reviews
7,Acer Aspire 3...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire 3 A315-51, 15.6"" HD, Core i3-6006U...",$436.29,1 reviews
8,Acer Aspire ES...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i5-7...",$454.62,9 reviews
9,Lenovo V110-15...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo V110-15IKB, 15.6"" HD, Core i5-7200U, 4G...",$465.95,7 reviews
10,Lenovo V510 Bl...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo V510 Black, 14"" HD, Core i3-6006U, 4GB,...",$484.23,8 reviews
11,Acer Swift 1 S...,/images/test-sites/e-commerce/items/cart2.png,"Acer Swift 1 SF113-31 Silver, 13.3"" FHD, Penti...",$488.64,4 reviews
12,Dell Vostro 15...,/images/test-sites/e-commerce/items/cart2.png,"Dell Vostro 15 (3568) Red, 15.6"" HD, Core i5-7...",$497.17,9 reviews
13,Acer Spin 5,/images/test-sites/e-commerce/items/cart2.png,"Acer Spin 5 SP513-51 Black, 13.3"" FHD Touch, C...",$564.98,0 reviews
14,Pavilion,/images/test-sites/e-commerce/items/cart2.png,"15.6"", Core i5-4200U, 6GB, 750GB, Windows 8.1",$609.99,4 reviews
15,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,"Asus VivoBook S14 (S406UA-BV041T) Starry Grey,...",$729,2 reviews
16,Asus ROG STRIX...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",$799,7 reviews
17,Lenovo ThinkPa...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo ThinkPad L570, 15.6"" FHD, Core i7-7500U...",$999,11 reviews
18,Dell Inspiron...,/images/test-sites/e-commerce/items/cart2.png,"Dell Inspiron 15 (7567) Black, 15.6"" FHD, Core...",$1098.42,7 reviews
19,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Apple MacBook Air 13.3"", Core i5 1.8GHz, 8GB, ...",$1101.83,4 reviews
20,Lenovo Legion...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo Legion Y520-15IKBM, Black, 15.6"" FHD IP...",$1112.91,1 reviews
21,Acer Aspire 7...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire 7 A715-71G, 15.6"" FHD IPS, Core i7...",$1123.87,4 reviews
22,Lenovo Legion...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo Legion Y520, 15.6"" FHD, Core i7-7700HQ,...",$1133.91,13 reviews
23,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5480, 14"" FHD, Core i5-7440HQ, 8...",$1143.4,5 reviews
24,Lenovo Legion...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo Legion Y520-15IKBM, 15.6"" FHD IPS, Core...",$1149,11 reviews
25,Toshiba Porteg...,/images/test-sites/e-commerce/items/cart2.png,"Toshiba Portege Z30-C-16L Grey, 13.3"" FHD, Cor...",$1154.04,7 reviews
26,ThinkPad T540p,/images/test-sites/e-commerce/items/cart2.png,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",$1178.99,2 reviews
27,Acer Predator...,/images/test-sites/e-commerce/items/cart2.png,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",$1187.98,14 reviews
28,Lenovo Yoga 91...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo Yoga 910 Grey, 13.9"" FHD Touch, Core i5...",$1199.73,7 reviews
29,Acer Predator...,/images/test-sites/e-commerce/items/cart2.png,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",$1221.58,9 reviews
30,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",$1238.37,0 reviews
31,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix GL753VE-GC096T, 17.3"" FHD, Core...",$1259,7 reviews
32,Hewlett Packar...,/images/test-sites/e-commerce/items/cart2.png,Hewlett Packard Spectre 13-v106na Dark Ash Sil...,$1273.11,8 reviews
33,MSI GL62VR 7RF...,/images/test-sites/e-commerce/items/cart2.png,"MSI GL62VR 7RFX, 15.6"" FHD, Core i7-7700HQ, 8G...",$1299,1 reviews
34,Hewlett Packar...,/images/test-sites/e-commerce/items/cart2.png,"Hewlett Packard ProBook 640 G3, 14"" FHD, Core ...",$1326.83,2 reviews
35,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",$1338.37,11 reviews
36,Lenovo ThinkPa...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo ThinkPad T470, 14"" FHD IPS, Core i5-720...",$1349.23,5 reviews
37,Asus ASUSPRO B...,/images/test-sites/e-commerce/items/cart2.png,"Asus ASUSPRO B9440UA-GV0279R Gray, 14"" FHD, Co...",$1381.13,4 reviews
38,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix GL702ZC-GC154T, 17.3"" FHD, Ryze...",$1769,7 reviews

In [28]:
df.to_csv("web_scraper_q_6__4.csv",index=False)

In [29]:
len(list)

39

# 6.5 Extract all product details of Second column save into csv file.

In [30]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
url="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r=requests.get(url)
r.status_code
soup=BeautifulSoup(r.text,"html")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="sQn1begDTknZYgEkRQ0Yb7a2LDehA96C">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Allinone | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>
<meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">8</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$306.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$321.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">5</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$356.49</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">6</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$364.46</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
						Hewlett Packar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$372.7</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
						Acer Aspire 3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
						Acer Aspire A3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">0</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.95</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
						Acer Aspire ES...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">9</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$391.48</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>

In [31]:
all_products=soup.find_all("div",class_="row")
len(all_products)

5

In [32]:
all_products = first_row[2].find_all("div",class_="col-md-4 col-xl-4 col-lg-4")[1:117:3]
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$321.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$372.7</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$391.48</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/71" itemprop="name" title="Asus VivoBook E502NA-GO022T Dark Blue">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">3</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$409.63</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/74" itemprop="name" title="Lenovo V110-15ISK">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$416.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/31" itemprop="name" title="Packard 255 G2">
 						Packard 255 G2
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$436.29</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/79" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$454.73</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/82" itemprop="name" title="Lenovo V110-15ISK">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$468.56</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/85" itemprop="name" title="Asus VivoBook 15 X540UA-DM260 Chocolate Black">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">1</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$485.9</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/88" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$488.78</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/46" itemprop="name" title="Dell Vostro 15">
 						Dell Vostro 15
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$498.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/93" itemprop="name" title="Lenovo V510 Black">
 						Lenovo V510 Bl...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$577.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/44" itemprop="name" title="HP 350 G1">
 						HP 350 G1
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$679</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/48" itemprop="name" title="Acer Aspire A515-51-5654">
 						Acer Aspire A5...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$739.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/34" itemprop="name" title="ProBook">
 						ProBook
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">

In [33]:
list=[]
for C2 in all_products:
    dict={
        "Product Name":"",
        "Product Image":"",
        "Product Details":"",
        "Product Price":"",
        "Product Rating":"",
    }
    dict["Product Name"]=C2.find("a",class_="title").text.strip()
    dict["Product Image"]= C2.find("img",class_="img-responsive").get("src")
    dict["Product Details"]=C2.find("div",class_="caption").find("p",class_="description").text.strip()
    dict["Product Price"]=C2.find("h4",class_="price float-end card-title pull-right").text.strip()
    dict["Product Rating"]=C2.find("div",class_="ratings").text.strip()
    list.append(dict)   
list

[{'Product Name': 'Prestigio Smar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Price': '$299',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$321.94',
  'Product Rating': '5 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$372.7',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$391.48',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'Product Price': '$399.99',
  'Product Rating': '3 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$409.63',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Packard 255 G2',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'Product Price': '$416.99',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home',
  'Product Price': '$436.29',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro',
  'Product Price': '$454.73',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd',
  'Product Price': '$468.56',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux',
  'Product Price': '$485.9',
  'Product Rating': '6 reviews'},
 {'Product Name': 'Dell Vostro 15',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux',
  'Product Price': '$488.78',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro',
  'Product Price': '$498.23',
  'Product Rating': '5 reviews'},
 {'Product Name': 'HP 350 G1',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows',
  'Product Price': '$577.99',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Acer Aspire A5...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG',
  'Product Price': '$679',
  'Product Rating': '9 reviews'},
 {'Product Name': 'ProBook',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
  'Product Price': '$739.99',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Acer Nitro 5 A...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Price': '$809',
  'Product Rating': '0 reviews'},
 {'Product Name': 'ThinkPad Yoga',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
  'Product Price': '$1033.99',
  'Product Rating': '13 reviews'},
 {'Product Name': 'MSI GL72M 7RDX',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'MSI GL72M 7RDX, 17.3" FHD, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Price': '$1099',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5280, 12.5" HD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1102.66',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Toshiba Portege Z30-C-16J Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1114.55',
  'Product Rating': '0 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Inspiron 17 2in1 (7779) Silver, 17.3" FHD Touch, Core i5-7200U, 12GB, 1TB, GeForce GT940MX 2GB, Windows 10 Home',
  'Product Price': '$1124.2',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Asus AsusPro A...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus AsusPro Advanced BU401LA-FA271G Dark Grey, 14", Core i5-4210U, 4GB, 128GB SSD, Win7 Pro 64bit, ENG',
  'Product Price': '$1139.54',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB, GeForce GTX 1050 Ti 4GB, Linux + Windows 10 Home',
  'Product Price': '$1144.2',
  'Product Rating': '2 reviews'},
 {'Product Name': 'MSI GP62M 7RDX...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'MSI GP62M 7RDX Leopard, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Price': '$1149',
  'Product Rating': '11 reviews'},
 {'Product Name': 'Acer TravelMat...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer TravelMate P645-S-511A Black, 14" FHD IPS, Core i5-5200U, 8GB, 256GB SSD, 3G, Windows 10 Pro',
  'Product Price': '$1170.1',
  'Product Rating': '0 reviews'},
 {'Product Name': 'MSI GS63 7RD S...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'MSI GS63 7RD Stealth, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, DOS + Windows 10 Home',
  'Product Price': '$1179',
  'Product Rating': '2 reviews'},
 {'Product Name': 'MSI GL62M 7REX',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'MSI GL62M 7REX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home',
  'Product Price': '$1199',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Toshiba Portege X30-D-10J Black/Blue, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1203.41',
  'Product Rating': '13 reviews'},
 {'Product Name': 'ThinkPad Yoga',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '12.5" Touch, Core i5 4200U, 8GB, 500GB + 16GB SSD Cache, Windows',
  'Product Price': '$1223.99',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Asus ZenBook U...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ZenBook UX530UX-FY040T Blue, 15.6" FHD, Core i7-7500U, 8GB, 512GB SSD, GeForce GTX950M 2GB, Windows 10 Home, Eng kbd',
  'Product Price': '$1239.2',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Apple MacBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Apple MacBook Air 13", i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, ENG',
  'Product Price': '$1260.13',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Dell XPS 13',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1',
  'Product Price': '$1281.99',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1310.39',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Apple MacBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Apple MacBook Pro 13" Space Gray, Core i5 2.3GHz, 8GB, 128GB SSD, Iris Plus 640, ENG',
  'Product Price': '$1333',
  'Product Rating': '0 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 16GB, 256GB SSD, GeForce GT930MX, Linux',
  'Product Price': '$1341.22',
  'Product Rating': '3 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo ThinkPad Yoga 370 Black, 13.3" FHD IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
  'Product Price': '$1362.24',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo Legion Y720, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 2TB HDD, GeForce GTX 1060 6GB, DOS, RGB backlit keyboard',
  'Product Price': '$1399',
  'Product Rating': '8 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG Strix GL702ZC-GC209T, 17.3" FHD IPS, Ryzen 7 1700, 16GB, 256GB SSD + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
  'Product Price': '$1769',
  'Product Rating': '8 reviews'}]

In [34]:
df=pd.DataFrame(list)
df

,Product Name,Product Image,Product Details,Product Price,Product Rating
0,Prestigio Smar...,/images/test-sites/e-commerce/items/cart2.png,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",$299,8 reviews
1,Lenovo V110-15...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",$321.94,5 reviews
2,Acer Aspire 3...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Celeron...",$372.7,2 reviews
3,Acer Aspire 3...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",$391.48,10 reviews
4,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,"Asus VivoBook E502NA-GO022T Dark Blue, 15.6"" H...",$399.99,3 reviews
5,Lenovo V110-15...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo V110-15ISK, 15.6"" HD, Core i3-6006U, 8G...",$409.63,9 reviews
6,Packard 255 G2,/images/test-sites/e-commerce/items/cart2.png,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",$416.99,2 reviews
7,Acer Aspire ES...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",$436.29,2 reviews
8,Lenovo V110-15...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo V110-15ISK, 15.6"" HD, Core i3-6006U, 4G...",$454.73,2 reviews
9,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,"Asus VivoBook 15 X540UA-DM260 Chocolate Black,...",$468.56,1 reviews
10,Acer Aspire ES...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i5-7...",$485.9,6 reviews
11,Dell Vostro 15,/images/test-sites/e-commerce/items/cart2.png,"Dell Vostro 15 (3568) Black, 15.6"" FHD, Core i...",$488.78,14 reviews
12,Lenovo V510 Bl...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo V510 Black, 15.6"" FHD, Core i3-7100U, 4...",$498.23,5 reviews
13,HP 350 G1,/images/test-sites/e-commerce/items/cart2.png,"15.6"", Core i5-4200U, 4GB, 750GB, Radeon HD867...",$577.99,10 reviews
14,Acer Aspire A5...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire A515-51-5654, Black, 15.6"", FHD, C...",$679,9 reviews
15,ProBook,/images/test-sites/e-commerce/items/cart2.png,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",$739.99,8 reviews
16,Acer Nitro 5 A...,/images/test-sites/e-commerce/items/cart2.png,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i5-...",$809,0 reviews
17,ThinkPad Yoga,/images/test-sites/e-commerce/items/cart2.png,"12.5"" Touch, Core i3-4010U, 4GB, 500GB + 16GB ...",$1033.99,13 reviews
18,MSI GL72M 7RDX,/images/test-sites/e-commerce/items/cart2.png,"MSI GL72M 7RDX, 17.3"" FHD, Core i5-7300HQ, 8GB...",$1099,1 reviews
19,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5280, 12.5"" HD, Core i5-7300U, 8...",$1102.66,8 reviews
20,Toshiba Porteg...,/images/test-sites/e-commerce/items/cart2.png,"Toshiba Portege Z30-C-16J Grey, 13.3"" FHD, Cor...",$1114.55,0 reviews
21,Dell Inspiron...,/images/test-sites/e-commerce/items/cart2.png,"Dell Inspiron 17 2in1 (7779) Silver, 17.3"" FHD...",$1124.2,10 reviews
22,Asus AsusPro A...,/images/test-sites/e-commerce/items/cart2.png,Asus AsusPro Advanced BU401LA-FA271G Dark Grey...,$1139.54,7 reviews
23,Dell Inspiron...,/images/test-sites/e-commerce/items/cart2.png,"Dell Inspiron 15 (7567) Black, 15.6"" FHD, Core...",$1144.2,2 reviews
24,MSI GP62M 7RDX...,/images/test-sites/e-commerce/items/cart2.png,"MSI GP62M 7RDX Leopard, 15.6"" FHD, Core i7-770...",$1149,11 reviews
25,Acer TravelMat...,/images/test-sites/e-commerce/items/cart2.png,"Acer TravelMate P645-S-511A Black, 14"" FHD IPS...",$1170.1,0 reviews
26,MSI GS63 7RD S...,/images/test-sites/e-commerce/items/cart2.png,"MSI GS63 7RD Stealth, 15.6"" FHD IPS, Core i7-7...",$1179,2 reviews
27,MSI GL62M 7REX,/images/test-sites/e-commerce/items/cart2.png,"MSI GL62M 7REX, 15.6"" FHD, Core i7-7700HQ, 8GB...",$1199,7 reviews
28,Toshiba Porteg...,/images/test-sites/e-commerce/items/cart2.png,"Toshiba Portege X30-D-10J Black/Blue, 13.3"" FH...",$1203.41,13 reviews
29,ThinkPad Yoga,/images/test-sites/e-commerce/items/cart2.png,"12.5"" Touch, Core i5 4200U, 8GB, 500GB + 16GB ...",$1223.99,2 reviews
30,Asus ZenBook U...,/images/test-sites/e-commerce/items/cart2.png,"Asus ZenBook UX530UX-FY040T Blue, 15.6"" FHD, C...",$1239.2,14 reviews
31,Apple MacBook...,/images/test-sites/e-commerce/items/cart2.png,"Apple MacBook Air 13"", i5 1.8GHz, 8GB, 256GB S...",$1260.13,8 reviews
32,Dell XPS 13,/images/test-sites/e-commerce/items/cart2.png,"13.3"" Touch, Core i5-4210U, 8GB, 128GB SSD, Wi...",$1281.99,4 reviews
33,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",$1310.39,8 reviews
34,Apple MacBook...,/images/test-sites/e-commerce/items/cart2.png,"Apple MacBook Pro 13"" Space Gray, Core i5 2.3G...",$1333,0 reviews
35,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",$1341.22,3 reviews
36,Lenovo ThinkPa...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo ThinkPad Yoga 370 Black, 13.3"" FHD IPS ...",$1362.24,12 reviews
37,Lenovo Legion...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo Legion Y720, 15.6"" FHD IPS, Core i7-770...",$1399,8 reviews
38,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix GL702ZC-GC209T, 17.3"" FHD IPS, ...",$1769,8 reviews

In [35]:
df.to_csv("web_scraper_q_6_5.csv",index=False)

In [36]:
len(list)

39

# 6.6 Extract all product details of thirst column save into csv file.

In [37]:
import requests
from bs4 import BeautifulSoup
import pandas as pd 
url="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
response=requests.get(url)
soup=BeautifulSoup(response.text,"html.parser")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="bYNCdWmjb1kCEKNkTBIqpIlYy5MSovQ1">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Allinone | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>
<meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>
<div class="row">
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">8</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$299</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
						Prestigio Smar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$306.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$321.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">5</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$356.49</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
						Lenovo V110-15...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">6</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$364.46</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
						Hewlett Packar...
					</a>
</h4>
<p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">12</span> reviews
				</p>
<p data-rating="1">
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$372.7</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
						Acer Aspire 3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.94</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
						Acer Aspire A3...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">0</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$379.95</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
						Acer Aspire ES...
					</a>
</h4>
<p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">9</span> reviews
				</p>
<p data-rating="4">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$391.48</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>

In [38]:
all_products=soup.find_all("div",class_="row")
len(all_products)

5

In [39]:
all_products = first_row[2].find_all("div",class_="col-md-4 col-xl-4 col-lg-4")[2:117:3]
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$356.49</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$393.88</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/70" itemprop="name" title="Acer Aspire 3 A315-21">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$404.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/72" itemprop="name" title="Lenovo ThinkPad E31-80">
 						Lenovo ThinkPa...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$410.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/75" itemprop="name" title="Acer Aspire ES1-732 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$433.3</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/77" itemprop="name" title="Asus EeeBook R416NA-FA014T">
 						Asus EeeBook R...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">1</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$439.73</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/80" itemprop="name" title="Acer Extensa 15 (2540) Black">
 						Acer Extensa 1...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$457.38</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/83" itemprop="name" title="Acer Aspire A315-51-33TG">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$469.1</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/86" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$487.8</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/89" itemprop="name" title="Lenovo V510 Black">
 						Lenovo V510 Bl...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$494.71</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/91" itemprop="name" title="Acer Aspire 3 A315-51 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$520.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/42" itemprop="name" title="HP 250 G3">
 						HP 250 G3
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">13</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$581.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/36" itemprop="name" title="Aspire E1-572G">
 						Aspire E1-572G
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$679</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/49" itemprop="name" title="Dell Inspiron 15">
 						Dell Inspiron...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">7</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$745.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/39" itemprop="name" title="Inspiron 15">
 						Inspiron 15
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>

In [40]:
list=[]
for C3 in all_products:
    dict={
        "Product Name":"",
        "Product Image":"",
        "Product Details":"",
        "Product Price":"",
        "Product Rating":"",
    }
    dict["Product Name"]=C3.find("a",class_="title").text.strip()
    dict["Product Image"]= C3.find("img",class_="img-responsive").get("src")
    dict["Product Details"]=C3.find("div",class_="caption").find("p",class_="description").text.strip()
    dict["Product Price"]=C3.find("h4",class_="price float-end card-title pull-right").text.strip()
    dict["Product Rating"]=C3.find("div",class_="ratings").text.strip()
    list.append(dict)
list

[{'Product Name': 'Prestigio Smar...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Price': '$299',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd',
  'Product Price': '$356.49',
  'Product Rating': '6 reviews'},
 {'Product Name': 'Acer Aspire A3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG',
  'Product Price': '$379.94',
  'Product Rating': '0 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux',
  'Product Price': '$393.88',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$404.23',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home',
  'Product Price': '$410.46',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Asus EeeBook R...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd',
  'Product Price': '$433.3',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Acer Extensa 1...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'Product Price': '$439.73',
  'Product Rating': '6 reviews'},
 {'Product Name': 'Acer Aspire A3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG',
  'Product Price': '$457.38',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$469.1',
  'Product Rating': '5 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Price': '$487.8',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home',
  'Product Price': '$494.71',
  'Product Rating': '2 reviews'},
 {'Product Name': 'HP 250 G3',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
  'Product Price': '$520.99',
  'Product Rating': '13 reviews'},
 {'Product Name': 'Aspire E1-572G',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
  'Product Price': '$581.99',
  'Product Rating': '2 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux',
  'Product Price': '$679',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Inspiron 15',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
  'Product Price': '$745.99',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS + Windows 10 Home',
  'Product Price': '$899',
  'Product Rating': '7 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo ThinkPad L460, 14" FHD IPS, Core i7-6600U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1096.02',
  'Product Rating': '14 reviews'},
 {'Product Name': 'MSI GL72M 7RDX',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG Strix GL553VD-DM535T, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home, Eng kbd',
  'Product Price': '$1099',
  'Product Rating': '9 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Linux + Windows 10 Home',
  'Product Price': '$1110.14',
  'Product Rating': '4 reviews'},
 {'Product Name': 'Acer Predator...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050Ti 4GB, Windows 10 Home',
  'Product Price': '$1123.87',
  'Product Rating': '1 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Windows 10 Pro',
  'Product Price': '$1133.82',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Acer Nitro 5 A...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD +1TB, GeForce GTX 1050 Ti 4GB, Windows 10 Home + Windows 10 Home',
  'Product Price': '$1140.62',
  'Product Rating': '14 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1144.4',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Lenovo Yoga 72...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo Yoga 720 Grey, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Price': '$1149.73',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 16GB, 256GB SSD, Linux + Windows 10 Home',
  'Product Price': '$1178.19',
  'Product Rating': '6 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Price': '$1187.88',
  'Product Rating': '5 reviews'},
 {'Product Name': 'MSI GL62M 7REX...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'MSI GL62M 7REX2, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home',
  'Product Price': '$1199',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Lenovo IdeaPad...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Lenovo IdeaPad Miix 510 Platinum Silver, 12.2" IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
  'Product Price': '$1212.16',
  'Product Rating': '0 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus VivoBook Pro 15 N580VN-FI006T Gold Metal, 15.6" UHD, Core i7-7700HQ, 16GB, 1TB + 256GB SSD, GeForce MX150 2GB, Windows 10 Home, Eng kbd',
  'Product Price': '$1235.49',
  'Product Rating': '10 reviews'},
 {'Product Name': 'ThinkPad X230',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit',
  'Product Price': '$1244.99',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 1TB, GeForce GT930MX, Windows 10 Pro',
  'Product Price': '$1271.06',
  'Product Rating': '13 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Toshiba Portege Z30-C-16K Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
  'Product Price': '$1294.74',
  'Product Rating': '6 reviews'},
 {'Product Name': 'ThinkPad X240',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': '12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit',
  'Product Price': '$1311.99',
  'Product Rating': '12 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 8GB, 256GB SSD, GeForce GT930MX, Windows 10 Pro',
  'Product Price': '$1337.28',
  'Product Rating': '6 reviews'},
 {'Product Name': 'Apple MacBook...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Apple MacBook Air 13", Intel Core i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, RUS',
  'Product Price': '$1347.78',
  'Product Rating': '11 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Toshiba Portege X20W-D-10V Black/Blue, 12.5" FHD Touch, Core i7-7500U, 8GB, 512GB SSD, Windows 10 Pro',
  'Product Price': '$1366.32',
  'Product Rating': '11 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG Strix GL702VM-GC146T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1060 3GB, Windows 10 Home, Eng kbd',
  'Product Price': '$1399',
  'Product Rating': '10 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Details': 'Asus ROG Strix SCAR Edition GL503VM-ED115T, 15.6" FHD 120Hz, Core i7-7700HQ, 16GB, 256GB SSD + 1TB SSHD, GeForce GTX 1060 6GB, Windows 10 Home',
  'Product Price': '$1799',
  'Product Rating': '8 reviews'}]

In [41]:
df=pd.DataFrame(list)
df

,Product Name,Product Image,Product Details,Product Price,Product Rating
0,Prestigio Smar...,/images/test-sites/e-commerce/items/cart2.png,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",$299,12 reviews
1,Lenovo V110-15...,/images/test-sites/e-commerce/items/cart2.png,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,$356.49,6 reviews
2,Acer Aspire A3...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",$379.94,0 reviews
3,Acer Aspire 3...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",$393.88,9 reviews
4,Lenovo ThinkPa...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo ThinkPad E31-80, 13.3"" HD, Celeron 3855...",$404.23,12 reviews
5,Acer Aspire ES...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire ES1-732 Black, 17.3"" HD+, Celeron,...",$410.46,14 reviews
6,Asus EeeBook R...,/images/test-sites/e-commerce/items/cart2.png,"Asus EeeBook R416NA-FA014T, 14"" FHD, Pentium N...",$433.3,1 reviews
7,Acer Extensa 1...,/images/test-sites/e-commerce/items/cart2.png,"Acer Extensa 15 (2540) Black, 15.6"" HD, Core i...",$439.73,6 reviews
8,Acer Aspire A3...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire A315-51-33TG, Black 15.6"" HD, Core...",$457.38,9 reviews
9,Acer Aspire ES...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",$469.1,5 reviews
10,Lenovo V510 Bl...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo V510 Black, 15.6"" HD, Core i3-6006U, 4G...",$487.8,9 reviews
11,Acer Aspire 3...,/images/test-sites/e-commerce/items/cart2.png,"Acer Aspire 3 A315-51 Black, 15.6"" FHD, Core i...",$494.71,2 reviews
12,HP 250 G3,/images/test-sites/e-commerce/items/cart2.png,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",$520.99,13 reviews
13,Aspire E1-572G,/images/test-sites/e-commerce/items/cart2.png,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",$581.99,2 reviews
14,Dell Inspiron...,/images/test-sites/e-commerce/items/cart2.png,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",$679,7 reviews
15,Inspiron 15,/images/test-sites/e-commerce/items/cart2.png,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",$745.99,12 reviews
16,Asus ROG STRIX...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",$899,7 reviews
17,Lenovo ThinkPa...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo ThinkPad L460, 14"" FHD IPS, Core i7-660...",$1096.02,14 reviews
18,MSI GL72M 7RDX,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix GL553VD-DM535T, 15.6"" FHD, Core...",$1099,9 reviews
19,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",$1110.14,4 reviews
20,Acer Predator...,/images/test-sites/e-commerce/items/cart2.png,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",$1123.87,1 reviews
21,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",$1133.82,14 reviews
22,Acer Nitro 5 A...,/images/test-sites/e-commerce/items/cart2.png,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i7-...",$1140.62,14 reviews
23,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",$1144.4,10 reviews
24,Lenovo Yoga 72...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo Yoga 720 Grey, 15.6"" FHD IPS, Core i5-7...",$1149.73,12 reviews
25,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",$1178.19,6 reviews
26,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",$1187.88,5 reviews
27,MSI GL62M 7REX...,/images/test-sites/e-commerce/items/cart2.png,"MSI GL62M 7REX2, 15.6"" FHD, Core i7-7700HQ, 8G...",$1199,12 reviews
28,Lenovo IdeaPad...,/images/test-sites/e-commerce/items/cart2.png,"Lenovo IdeaPad Miix 510 Platinum Silver, 12.2""...",$1212.16,0 reviews
29,Asus VivoBook...,/images/test-sites/e-commerce/items/cart2.png,"Asus VivoBook Pro 15 N580VN-FI006T Gold Metal,...",$1235.49,10 reviews
30,ThinkPad X230,/images/test-sites/e-commerce/items/cart2.png,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",$1244.99,10 reviews
31,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",$1271.06,13 reviews
32,Toshiba Porteg...,/images/test-sites/e-commerce/items/cart2.png,"Toshiba Portege Z30-C-16K Grey, 13.3"" FHD, Cor...",$1294.74,6 reviews
33,ThinkPad X240,/images/test-sites/e-commerce/items/cart2.png,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",$1311.99,12 reviews
34,Dell Latitude...,/images/test-sites/e-commerce/items/cart2.png,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",$1337.28,6 reviews
35,Apple MacBook...,/images/test-sites/e-commerce/items/cart2.png,"Apple MacBook Air 13"", Intel Core i5 1.8GHz, 8...",$1347.78,11 reviews
36,Toshiba Porteg...,/images/test-sites/e-commerce/items/cart2.png,"Toshiba Portege X20W-D-10V Black/Blue, 12.5"" F...",$1366.32,11 reviews
37,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",$1399,10 reviews
38,Asus ROG Strix...,/images/test-sites/e-commerce/items/cart2.png,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",$1799,8 reviews

In [42]:
df.to_csv("web_scraper_q_6_6.csv",index=False)

In [43]:
len(list)

39