## 1.1 Extract Table of year 2015 & save into csv file.

In [77]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://www.scrapethissite.com/pages/ajax-javascript/#2015")

In [2]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<meta charset="utf-8"/>
<title>Oscar Winning Films: AJAX and Javascript | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li class="" id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-09N5RQCFG4&amp;cx=c&amp;_slc=1" type="text/javascript"></script><script async="" src="https://connect.facebook.net/signals/config/764287443701341?v=2.9.243&amp;r=stable&amp;domain=www.scrapethissite.com&amp;hme=fdfab1132115f4ac7aabc9fd7eee63947594f6e6f1735b47a225dd71217525d3&amp;ex_m=89%2C147%2C127%2C18%2C65%2C66%2C120%2C61%2C41%2C121%2C70%2C60%2C134%2C78%2C13%2C88%2C26%2C115%2C108%2C68%2C71%2C114%2C131%2C97%2C136%2C7%2C3%2C4%2C6%2C5%2C2%2C79%2C87%2C137%2C214%2C158%2C55%2C216%2C217%2C48%2C173%2C25%2C67%2C222%2C221%2C161%2C28%2C54%2C8%2C57%2C83%2C84%2C85%2C90%2C111%2C27%2C24%2C113%2C110%2C109%2C128%2C69%2C130%2C129%2C43%2C53%2C105%2C12%2C133%2C38%2C203%2C205%2C168%2C21%2C22%2C23%2C15%2C16%2C37%2C33%2C35%2C34%2C74%2C80%2C82%2C95%2C119%2C122%2C39%2C96%2C19%2C17%2C101%2C62%2C31%2C124%2C123%2C125%2C116%2C20%2C30%2C52%2C94%2C132%2C63%2C14%2C126%2C29%2C183%2C154%2C275%2C201%2C145%2C186%2C179%2C155%2C92%2C112%2C73%2C103%2C47%2C40%2C102%2C107%2C51%2C58%2C42%2C98%2C46%2C49%2C45%2C86%2C135%2C0%2C106%2C11%2C104%2C9%2C1%2C50%2C81%2C56%2C59%2C100%2C77%2C76%2C44%2C117%2C75%2C72%2C64%2C99%2C91%2C36%2C118%2C32%2C93%2C10%2C138"></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script async="" src="https://www.google-analytics.com/analytics.js"></script><script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="oscars">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Oscar Winning Films: AJAX and Javascript
                            <small>87 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it.
                            Look for ways that you can tell visually when a site is loading content with AJAX. Then, browse through your network tab to see those AJAX requests and scrape them.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">3 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="https://en.wikipedia.org/wiki/List_of_Academy_Award-winning_films" target="_blank">https://en.wikipedia.org/wiki/List_of_Academy_Award-winning_films</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12 text-center">
<h3>
                            Choose a Year to View Films
                        </h3>
<a class="year-link active" href="#" id="2015">2015</a>
<a class="year-link" href="#" id="2014">2014</a>
<a class="year-link" href="#" id="2013">2013</a>
<a class="year-link" href="#" id="2012">2012</a>
<a class="year-link" href="#" id="2011">2011</a>
<a class="year-link" href="#" id="2010">2010</a>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-12">
<div id="loading" style="display: none;">
<img class="center-block" src="/static/images/ajax-loader.gif"/>
</div>
<table class="table" style="">
<thead>
<tr>
<th>Title</th>
<th>Nominations</th>
<th>Awards</th>
<th>Best Picture</th>
</tr>
</thead>
<tbody id="table-body"><tr class="film"><td class="film-title">Spotlight  </td><td class="film-nominations">6</td><td class="film-awards">2</td><td class="film-best-picture"><i class="glyphicon glyphicon-flag"></i></td></tr><tr class="film"><td class="film-title">Mad Max: Fury Road </td><td class="film-nominations">10</td><td class="film-awards">6</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Revenant   </td><td class="film-nominations">12</td><td class="film-awards">3</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Bridge of Spies</td><td class="film-nominations">6</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Big Short  </td><td class="film-nominations">5</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Danish Girl</td><td class="film-nominations">4</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Room   </td><td class="film-nominations">4</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Ex Machina </td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Hateful Eight  </td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Inside Out </td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Amy</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Bear Story </td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">A Girl in the River: The Price of Forgiveness  </td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Son of Saul</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Spectre</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Stutterer  </td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr></tbody>
</table>
</div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
</div><!--#page-->
<section id="footer">
<div class="container">
<div class="row">
<div class="col-md-12 text-center text-muted">
                    Lessons and Videos © Hartley Brody 2023
                </div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
<script crossorigin="anonymous" data-cf-beacon='{"version":"2024.11.0","token":"876766d8a2734c408f9198f80ced491f","r":1,"server_timing":{"name":{"cfCacheStatus":true,"cfEdge":true,"cfExtPri":true,"cfL4":true,"cfOrigin":true,"cfSpeedBrain":true},"location_startswith":null}}' defer="" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script crossorigin="anonymous" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script type="text/javascript">
    $(document).ready( function(){
        $(".year-link").click( function(e){
            var target = $(e.target);
            var year = target.attr("id");

            document.location.hash = year;
            fetchFilms(year);
            return false;
        });

        if (document.location.hash){
            var year = document.location.hash.substr(1)
            fetchFilms(year);
        }

        function fetchFilms(year){
            showLoadingAnimation();
            $.ajax({
                method: "GET",
                url: document.location.pathname,
                data: {
                    ajax: true,
                    year: year
                },
                success: function(data){
                    setTimeout( function(){
                        showFilms(data);
                    }, 1500);  // add intentional delay to emphasize async UI
                },
                error: function(){
                    alert("Error loading films :(");
                }
            });
            $(".active").removeClass("active");
            $("#"+year).addClass("active");
        }

        function showLoadingAnimation(){
            $(".table").hide();
            $("#loading").show();
        }
        function showFilms(films){
            // console.log(films);
            var films_html = "";
            $.each(films, function(_, film){
                var film_html = "";
                film_html += "<tr class='film'>"
                    film_html += "<td class='film-title'>" + film["title"] + "</td>"
                    film_html += "<td class='film-nominations'>" + film["nominations"] + "</td>"
                    film_html += "<td class='film-awards'>" + film["awards"] + "</td>"
                    if (film["best_picture"]) {
                        film_html += "<td class='film-best-picture'><i class='glyphicon glyphicon-flag'></i></td>"
                    } else {
                        film_html += "<td class='film-best-picture'></td>"
                    }
                film_html += "</tr>"
                films_html += film_html;
            })
            $("#table-body").html(films_html);
            $(".table").show();
            $("#loading").hide();
        }
    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css"/>
<!-- pnotify messages -->
<script type="text/javascript">

    PNotify.prototype.options.styling = "bootstrap3";
    $(function(){

    });


    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
<!-- golbal video controls -->
<script type="text/javascript">
    $("video").hover(function() {
        $(this).prop("controls", true);
    }, function() {
        $(this).prop("controls", false);
    });

    $("video").click(function() {
        if( this.paused){
            this.play();
        }
        else {
            this.pause();
        }
    });
    </script>
<!-- insert google analytics here -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41551755-8', 'auto');
    ga('send', 'pageview');
  </script>
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '764287443701341');
  fbq('track', "PageView");</script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=764287443701341&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
<!-- End Facebook Pixel Code -->
<!-- Google Code for Remarketing Tag -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 950945448;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
<script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript">
</script><script async="" src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?random=1763744435728&amp;cv=9&amp;fst=1763744435728&amp;num=1&amp;guid=ON&amp;resp=GooglemKTybQhCsO&amp;eid=375603260%2C466465926%2C512247839%2C658953496&amp;u_h=768&amp;u_w=1366&amp;ig=1&amp;frm=0&amp;url=https%3A%2F%2Fwww.scrapethissite.com%2Fpages%2Fajax-javascript%2F&amp;tiba=Oscar%20Winning%20Films%3A%20AJAX%20and%20Javascript%20%7C%20Scrape%20This%20Site%20%7C%20A%20public%20sandbox%20for%20learning%20web%20scraping&amp;hn=www.googleadservices.com&amp;rfmt=3&amp;fmt=4" type="text/javascript"></script>
<noscript>
<div style="display:inline;">
<img alt="" height="1" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0" style="border-style:none;" width="1">
</img></div>
</noscript>
<!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>
<script>
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'AW-950945448');
  </script>
<iframe height="0" style="display: none; visibility: hidden;" width="0"></iframe><script async="" src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?random=1763744435886&amp;cv=11&amp;fst=1763744435886&amp;bg=ffffff&amp;guid=ON&amp;async=1&amp;en=gtag.config&amp;gtm=45be5bj0h2za200xec&amp;gcd=13l3l3l3l1l1&amp;dma=0&amp;tag_exp=102015666~103116026~103200004~104527907~104528501~104684208~104684211~105446120~115583767~115938466~115938469~116184927~116184929~116217636~116217638&amp;u_w=1366&amp;u_h=768&amp;url=https%3A%2F%2Fwww.scrapethissite.com%2Fpages%2Fajax-javascript%2F&amp;frm=0&amp;tiba=Oscar%20Winning%20Films%3A%20AJAX%20and%20Javascript%20%7C%20Scrape%20This%20Site%20%7C%20A%20public%20sandbox%20for%20learning%20web%20scraping&amp;hn=www.googleadservices.com&amp;npa=0&amp;pscdl=noapi&amp;auid=1854846395.1763744436&amp;uaa=x86&amp;uab=64&amp;uafvl=Chromium%3B142.0.7444.60%7CGoogle%2520Chrome%3B142.0.7444.60%7CNot_A%2520Brand%3B99.0.0.0&amp;uamb=0&amp;uam=&amp;uap=Windows&amp;uapv=10.0.0&amp;uaw=0&amp;data=event%3Dgtag.config&amp;rfmt=3&amp;fmt=4" type="text/javascript"></script></body></html>

In [25]:
dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

}

In [26]:
# soup.find_all('div',class_="col-md-12")[0].find_all('table")[0]
table= soup.find_all('div',class_="col-md-12")[4]
table

<div class="col-md-12">
<div id="loading" style="display: none;">
<img class="center-block" src="/static/images/ajax-loader.gif"/>
</div>
<table class="table" style="">
<thead>
<tr>
<th>Title</th>
<th>Nominations</th>
<th>Awards</th>
<th>Best Picture</th>
</tr>
</thead>
<tbody id="table-body"><tr class="film"><td class="film-title">Spotlight  </td><td class="film-nominations">6</td><td class="film-awards">2</td><td class="film-best-picture"><i class="glyphicon glyphicon-flag"></i></td></tr><tr class="film"><td class="film-title">Mad Max: Fury Road </td><td class="film-nominations">10</td><td class="film-awards">6</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Revenant   </td><td class="film-nominations">12</td><td class="film-awards">3</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Bridge of Spies</td><td class="film-nominations">6</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Big Short  </td><td class="film-nominations">5</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Danish Girl</td><td class="film-nominations">4</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Room   </td><td class="film-nominations">4</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Ex Machina </td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Hateful Eight  </td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Inside Out </td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Amy</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Bear Story </td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">A Girl in the River: The Price of Forgiveness  </td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Son of Saul</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Spectre</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Stutterer  </td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr></tbody>
</table>
</div>

In [35]:
rows= table.find_all('tr')[1]
rows

In [51]:
rows= table.find_all('tr',class_='film')
rows

[<tr class="film"><td class="film-title">Spotlight  </td><td class="film-nominations">6</td><td class="film-awards">2</td><td class="film-best-picture"><i class="glyphicon glyphicon-flag"></i></td></tr>,
 <tr class="film"><td class="film-title">Mad Max: Fury Road </td><td class="film-nominations">10</td><td class="film-awards">6</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">The Revenant   </td><td class="film-nominations">12</td><td class="film-awards">3</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Bridge of Spies</td><td class="film-nominations">6</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">The Big Short  </td><td class="film-nominations">5</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">The Danish Girl</td><td class="film-nominations">4</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Room   </td><td class="film-nominations">4</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Ex Machina </td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">The Hateful Eight  </td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Inside Out </td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Amy</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Bear Story </td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">A Girl in the River: The Price of Forgiveness  </td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Son of Saul</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Spectre</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Stutterer  </td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>]

In [52]:
list = []
for i in rows:
    dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

    }
    dict_data['Title']=i.find('td').text

    dict_data['Nominations']=i.find('td',class_='film-nominations').text
    dict_data['Awards']=i.find('td',class_='film-awards').text
    list.append(dict_data)

In [53]:
list

[{'Title': 'Spotlight  ',
  'Nominations': '6',
  'Best Picture': '',
  'Awards': '2'},
 {'Title': 'Mad Max: Fury Road ',
  'Nominations': '10',
  'Best Picture': '',
  'Awards': '6'},
 {'Title': 'The Revenant   ',
  'Nominations': '12',
  'Best Picture': '',
  'Awards': '3'},
 {'Title': 'Bridge of Spies',
  'Nominations': '6',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'The Big Short  ',
  'Nominations': '5',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'The Danish Girl',
  'Nominations': '4',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Room   ', 'Nominations': '4', 'Best Picture': '', 'Awards': '1'},
 {'Title': 'Ex Machina ',
  'Nominations': '2',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'The Hateful Eight  ',
  'Nominations': '2',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Inside Out ',
  'Nominations': '2',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Amy', 'Nominations': '1', 'Best Picture': '', 'Awards': '1'},
 {'Title': 'Bear Story ',
  'Nominations': '1',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'A Girl in the River: The Price of Forgiveness  ',
  'Nominations': '1',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Son of Saul',
  'Nominations': '1',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Spectre', 'Nominations': '1', 'Best Picture': '', 'Awards': '1'},
 {'Title': 'Stutterer  ',
  'Nominations': '1',
  'Best Picture': '',
  'Awards': '1'}]

In [55]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('scrapthisside q1_1.csv',index=False)
df

,Title,Nominations,Best Picture,Awards
0,Spotlight,6,,2
1,Mad Max: Fury Road,10,,6
2,The Revenant,12,,3
3,Bridge of Spies,6,,1
4,The Big Short,5,,1
5,The Danish Girl,4,,1
6,Room,4,,1
7,Ex Machina,2,,1
8,The Hateful Eight,2,,1
9,Inside Out,2,,1
10,Amy,1,,1
11,Bear Story,1,,1
12,A Girl in the River: The Price of Forgiveness,1,,1
13,Son of Saul,1,,1
14,Spectre,1,,1
15,Stutterer,1,,1

## 1.2 Extract Table of year 2014 & save into another csv file.

In [60]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://www.scrapethissite.com/pages/ajax-javascript/#2014")

In [58]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<meta charset="utf-8"/>
<title>Oscar Winning Films: AJAX and Javascript | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li class="" id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-09N5RQCFG4&amp;cx=c&amp;_slc=1" type="text/javascript"></script><script async="" src="https://connect.facebook.net/signals/config/764287443701341?v=2.9.243&amp;r=stable&amp;domain=www.scrapethissite.com&amp;hme=fdfab1132115f4ac7aabc9fd7eee63947594f6e6f1735b47a225dd71217525d3&amp;ex_m=89%2C147%2C127%2C18%2C65%2C66%2C120%2C61%2C41%2C121%2C70%2C60%2C134%2C78%2C13%2C88%2C26%2C115%2C108%2C68%2C71%2C114%2C131%2C97%2C136%2C7%2C3%2C4%2C6%2C5%2C2%2C79%2C87%2C137%2C214%2C158%2C55%2C216%2C217%2C48%2C173%2C25%2C67%2C222%2C221%2C161%2C28%2C54%2C8%2C57%2C83%2C84%2C85%2C90%2C111%2C27%2C24%2C113%2C110%2C109%2C128%2C69%2C130%2C129%2C43%2C53%2C105%2C12%2C133%2C38%2C203%2C205%2C168%2C21%2C22%2C23%2C15%2C16%2C37%2C33%2C35%2C34%2C74%2C80%2C82%2C95%2C119%2C122%2C39%2C96%2C19%2C17%2C101%2C62%2C31%2C124%2C123%2C125%2C116%2C20%2C30%2C52%2C94%2C132%2C63%2C14%2C126%2C29%2C183%2C154%2C275%2C201%2C145%2C186%2C179%2C155%2C92%2C112%2C73%2C103%2C47%2C40%2C102%2C107%2C51%2C58%2C42%2C98%2C46%2C49%2C45%2C86%2C135%2C0%2C106%2C11%2C104%2C9%2C1%2C50%2C81%2C56%2C59%2C100%2C77%2C76%2C44%2C117%2C75%2C72%2C64%2C99%2C91%2C36%2C118%2C32%2C93%2C10%2C138"></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script async="" src="https://www.google-analytics.com/analytics.js"></script><script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="oscars">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Oscar Winning Films: AJAX and Javascript
                            <small>87 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it.
                            Look for ways that you can tell visually when a site is loading content with AJAX. Then, browse through your network tab to see those AJAX requests and scrape them.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">3 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="https://en.wikipedia.org/wiki/List_of_Academy_Award-winning_films" target="_blank">https://en.wikipedia.org/wiki/List_of_Academy_Award-winning_films</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12 text-center">
<h3>
                            Choose a Year to View Films
                        </h3>
<a class="year-link" href="#" id="2015">2015</a>
<a class="year-link active" href="#" id="2014">2014</a>
<a class="year-link" href="#" id="2013">2013</a>
<a class="year-link" href="#" id="2012">2012</a>
<a class="year-link" href="#" id="2011">2011</a>
<a class="year-link" href="#" id="2010">2010</a>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-12">
<div id="loading" style="display: none;">
<img class="center-block" src="/static/images/ajax-loader.gif"/>
</div>
<table class="table" style="">
<thead>
<tr>
<th>Title</th>
<th>Nominations</th>
<th>Awards</th>
<th>Best Picture</th>
</tr>
</thead>
<tbody id="table-body"><tr class="film"><td class="film-title">Birdman</td><td class="film-nominations">9</td><td class="film-awards">4</td><td class="film-best-picture"><i class="glyphicon glyphicon-flag"></i></td></tr><tr class="film"><td class="film-title">The Grand Budapest Hotel</td><td class="film-nominations">9</td><td class="film-awards">4</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Whiplash</td><td class="film-nominations">5</td><td class="film-awards">3</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Imitation Game</td><td class="film-nominations">8</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">American Sniper</td><td class="film-nominations">6</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Boyhood</td><td class="film-nominations">6</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Interstellar</td><td class="film-nominations">5</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Theory of Everything</td><td class="film-nominations">5</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Ida</td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Selma</td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Citizenfour</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Big Hero 6</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Crisis Hotline: Veterans Press 1</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">The Phone Call</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Still Alice</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr><tr class="film"><td class="film-title">Feast</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr></tbody>
</table>
</div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
</div><!--#page-->
<section id="footer">
<div class="container">
<div class="row">
<div class="col-md-12 text-center text-muted">
                    Lessons and Videos © Hartley Brody 2023
                </div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
<script crossorigin="anonymous" data-cf-beacon='{"version":"2024.11.0","token":"876766d8a2734c408f9198f80ced491f","r":1,"server_timing":{"name":{"cfCacheStatus":true,"cfEdge":true,"cfExtPri":true,"cfL4":true,"cfOrigin":true,"cfSpeedBrain":true},"location_startswith":null}}' defer="" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script crossorigin="anonymous" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script type="text/javascript">
    $(document).ready( function(){
        $(".year-link").click( function(e){
            var target = $(e.target);
            var year = target.attr("id");

            document.location.hash = year;
            fetchFilms(year);
            return false;
        });

        if (document.location.hash){
            var year = document.location.hash.substr(1)
            fetchFilms(year);
        }

        function fetchFilms(year){
            showLoadingAnimation();
            $.ajax({
                method: "GET",
                url: document.location.pathname,
                data: {
                    ajax: true,
                    year: year
                },
                success: function(data){
                    setTimeout( function(){
                        showFilms(data);
                    }, 1500);  // add intentional delay to emphasize async UI
                },
                error: function(){
                    alert("Error loading films :(");
                }
            });
            $(".active").removeClass("active");
            $("#"+year).addClass("active");
        }

        function showLoadingAnimation(){
            $(".table").hide();
            $("#loading").show();
        }
        function showFilms(films){
            // console.log(films);
            var films_html = "";
            $.each(films, function(_, film){
                var film_html = "";
                film_html += "<tr class='film'>"
                    film_html += "<td class='film-title'>" + film["title"] + "</td>"
                    film_html += "<td class='film-nominations'>" + film["nominations"] + "</td>"
                    film_html += "<td class='film-awards'>" + film["awards"] + "</td>"
                    if (film["best_picture"]) {
                        film_html += "<td class='film-best-picture'><i class='glyphicon glyphicon-flag'></i></td>"
                    } else {
                        film_html += "<td class='film-best-picture'></td>"
                    }
                film_html += "</tr>"
                films_html += film_html;
            })
            $("#table-body").html(films_html);
            $(".table").show();
            $("#loading").hide();
        }
    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css"/>
<!-- pnotify messages -->
<script type="text/javascript">

    PNotify.prototype.options.styling = "bootstrap3";
    $(function(){

    });


    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
<!-- golbal video controls -->
<script type="text/javascript">
    $("video").hover(function() {
        $(this).prop("controls", true);
    }, function() {
        $(this).prop("controls", false);
    });

    $("video").click(function() {
        if( this.paused){
            this.play();
        }
        else {
            this.pause();
        }
    });
    </script>
<!-- insert google analytics here -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41551755-8', 'auto');
    ga('send', 'pageview');
  </script>
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '764287443701341');
  fbq('track', "PageView");</script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=764287443701341&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
<!-- End Facebook Pixel Code -->
<!-- Google Code for Remarketing Tag -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 950945448;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
<script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript">
</script><script async="" src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?random=1763747254636&amp;cv=9&amp;fst=1763747254636&amp;num=1&amp;guid=ON&amp;resp=GooglemKTybQhCsO&amp;eid=375603261%2C466465925%2C512247838%2C658953495&amp;u_h=768&amp;u_w=1366&amp;ig=1&amp;frm=0&amp;url=https%3A%2F%2Fwww.scrapethissite.com%2Fpages%2Fajax-javascript%2F&amp;tiba=Oscar%20Winning%20Films%3A%20AJAX%20and%20Javascript%20%7C%20Scrape%20This%20Site%20%7C%20A%20public%20sandbox%20for%20learning%20web%20scraping&amp;hn=www.googleadservices.com&amp;rfmt=3&amp;fmt=4" type="text/javascript"></script>
<noscript>
<div style="display:inline;">
<img alt="" height="1" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0" style="border-style:none;" width="1">
</img></div>
</noscript>
<!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>
<script>
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'AW-950945448');
  </script>
<iframe height="0" style="display: none; visibility: hidden;" width="0"></iframe><script async="" src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?random=1763747254788&amp;cv=11&amp;fst=1763747254788&amp;bg=ffffff&amp;guid=ON&amp;async=1&amp;en=gtag.config&amp;gtm=45be5bi1za200xec&amp;gcd=13l3l3l3l1l1&amp;dma=0&amp;tag_exp=103116026~103200004~104527906~104528500~104684208~104684211~105322303~115583767~115867898~115867900~115938465~115938469~116184927~116184929~116217636~116217638~116474636&amp;u_w=1366&amp;u_h=768&amp;url=https%3A%2F%2Fwww.scrapethissite.com%2Fpages%2Fajax-javascript%2F&amp;frm=0&amp;tiba=Oscar%20Winning%20Films%3A%20AJAX%20and%20Javascript%20%7C%20Scrape%20This%20Site%20%7C%20A%20public%20sandbox%20for%20learning%20web%20scraping&amp;hn=www.googleadservices.com&amp;npa=0&amp;pscdl=noapi&amp;auid=2146064170.1763747255&amp;uaa=x86&amp;uab=64&amp;uafvl=Chromium%3B142.0.7444.60%7CGoogle%2520Chrome%3B142.0.7444.60%7CNot_A%2520Brand%3B99.0.0.0&amp;uamb=0&amp;uam=&amp;uap=Windows&amp;uapv=10.0.0&amp;uaw=0&amp;data=event%3Dgtag.config&amp;rfmt=3&amp;fmt=4" type="text/javascript"></script></body></html>

In [67]:
table= soup.find_all('tr',class_='film')
table

[<tr class="film"><td class="film-title">Birdman</td><td class="film-nominations">9</td><td class="film-awards">4</td><td class="film-best-picture"><i class="glyphicon glyphicon-flag"></i></td></tr>,
 <tr class="film"><td class="film-title">The Grand Budapest Hotel</td><td class="film-nominations">9</td><td class="film-awards">4</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Whiplash</td><td class="film-nominations">5</td><td class="film-awards">3</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">The Imitation Game</td><td class="film-nominations">8</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">American Sniper</td><td class="film-nominations">6</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Boyhood</td><td class="film-nominations">6</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Interstellar</td><td class="film-nominations">5</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">The Theory of Everything</td><td class="film-nominations">5</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Ida</td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Selma</td><td class="film-nominations">2</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Citizenfour</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Big Hero 6</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Crisis Hotline: Veterans Press 1</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">The Phone Call</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Still Alice</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>,
 <tr class="film"><td class="film-title">Feast</td><td class="film-nominations">1</td><td class="film-awards">1</td><td class="film-best-picture"></td></tr>]

In [68]:
list = []
for i in table:
    dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

    }
    dict_data['Title']=i.find('td').text

    dict_data['Nominations']=i.find('td',class_='film-nominations').text
    dict_data['Awards']=i.find('td',class_='film-awards').text
    list.append(dict_data)

In [69]:
list

[{'Title': 'Birdman', 'Nominations': '9', 'Best Picture': '', 'Awards': '4'},
 {'Title': 'The Grand Budapest Hotel',
  'Nominations': '9',
  'Best Picture': '',
  'Awards': '4'},
 {'Title': 'Whiplash', 'Nominations': '5', 'Best Picture': '', 'Awards': '3'},
 {'Title': 'The Imitation Game',
  'Nominations': '8',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'American Sniper',
  'Nominations': '6',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Boyhood', 'Nominations': '6', 'Best Picture': '', 'Awards': '1'},
 {'Title': 'Interstellar',
  'Nominations': '5',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'The Theory of Everything',
  'Nominations': '5',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Ida', 'Nominations': '2', 'Best Picture': '', 'Awards': '1'},
 {'Title': 'Selma', 'Nominations': '2', 'Best Picture': '', 'Awards': '1'},
 {'Title': 'Citizenfour',
  'Nominations': '1',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Big Hero 6',
  'Nominations': '1',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Crisis Hotline: Veterans Press 1',
  'Nominations': '1',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'The Phone Call',
  'Nominations': '1',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Still Alice',
  'Nominations': '1',
  'Best Picture': '',
  'Awards': '1'},
 {'Title': 'Feast', 'Nominations': '1', 'Best Picture': '', 'Awards': '1'}]

In [ ]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('scrapthisside q1_2.csv',index=False)
df

ValueError: DataFrame constructor not properly called!

## 1.7 Extract Tables from year 2015 to 2010 & save into single csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/ajax-javascript/") # to get the url 
driver.get(url)
for j in range(2015,2009,-1): # for inner loop is 15 to 9 datas
    driver.find_element("xpath",f'//a[@id={j}]').click() # difrent file are element to chcek and click to  secand wibsite
    print(j) # print j this is all wibsite data
    time.sleep(3) # this a timer 
    soup = BeautifulSoup(driver.page_source, 'html.parser') # to website html code 
    tbs = soup.find_all('table',class_='table')[0] # to all table find 
    trs = tbs.find_all('tr') # to all find tr
    list=[]
    for i in trs[1:]: # for outer loop dict to control all data 
        dict_data = {
        'Title':'',
        'Nominations':'',
        'Best Picture':'',
        'Awards':'',

        }
        dict_data['Title']=i.find('td').text

        dict_data['Nominations']=i.find('td',class_='film-nominations').text
        dict_data['Awards']=i.find('td',class_='film-awards').text
        list.append(dict_data.copy()) # all data are append to list

        df = pd.DataFrame(list) # to convert to data frame 
        df
        df.to_csv(f'scrapthisside q7_1{j}.csv',index=False)# to save into csv file 
        df

2015
2014
2013
2012
2011
2010

## 1.8 Extract Tables from year 2015 to 2010 & save into single csv file with year column. (year, Title, Nominations, Awards, Best Picture)

In [7]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/ajax-javascript/") # to get the url 
driver.get(url)
list=[]
for j in range(2015,2009,-1): # for inner loop is 15 to 9 datas
    driver.find_element("xpath",f'//a[@id={j}]').click() # difrent file are element to chcek and click to  secand wibsite
    print(j) # print j this is all wibsite data
    time.sleep(3) # this a timer 
    soup = BeautifulSoup(driver.page_source, 'html.parser') # to website html code 
    tbs = soup.find_all('table',class_='table')[0] # to all table find 
    trs = tbs.find_all('tr') # to all find tr
    
    for i in trs[1:]: # for outer loop dict to control all data 
        dict_data = {
        'Title':'',
        'Nominations':'',
        'Best Picture':'',
        'Awards':'',

        }
        dict_data['Title']=i.find('td').text

        dict_data['Nominations']=i.find('td',class_='film-nominations').text
        dict_data['Awards']=i.find('td',class_='film-awards').text
        list.append(dict_data.copy()) # all data are append to list

df = pd.DataFrame(list) # to convert to data frame 
df
df.to_csv('scrapthisside q8_1.csv',index=False)# to save into csv file 
df

2015
2014
2013
2012
2011
2010

                  Title Nominations Best Picture Awards
0           Spotlight             6                   2
1   Mad Max: Fury Road           10                   6
2       The Revenant             12                   3
3       Bridge of Spies           6                   1
4       The Big Short             5                   1
..                  ...         ...          ...    ...
82       The Lost Thing           1                   1
83          God of Love           1                   1
84          The Wolfman           1                   1
85    Strangers No More           1                   1
86           Inside Job           1                   1

[87 rows x 4 columns]

## 2.1 Extract first Testudines details save into csv file. e.g# Carettochelyidae

In [33]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)

In [34]:
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find('div',class_='col-md-4 turtle-family-card')
frm

<div class="col-md-4 turtle-family-card">
<img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg"/>
<h3 class="family-name">Carettochelyidae</h3>
<a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Carettochelyidae">Learn more →</a>
</div>

In [13]:
len(frm)

14

In [35]:
list =[]
base_url = 'https://www.scrapethissite.com/'
dict = {
    'name':'',
    'url':'',
    'img_url':'',
}
dict ['url']=frm.find('img')['src']
dict ['img_url']=base_url + frm.find('a')['href']
dict ['name']=frm.find('h3').text
list.append(dict)

In [36]:
list

[{'name': 'Carettochelyidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Carettochelyidae'}]

In [24]:
df = pd.DataFrame(list)
df.to_csv('scrapthisside q2_1.csv',index=False)# to save into csv file 
df

,name,url,img_url
0,Carettochelyidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...

## 2.2 Extract Testudines family details save into csv file. e.g# Carettochelyidae, Cheloniidae, Chelydridae

In [40]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)

In [41]:
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='row')
frm

[<div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg"/>
 <h3 class="family-name">Carettochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Carettochelyidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GreenSeaTurtle-2.jpg/200px-GreenSeaTurtle-2.jpg"/>
 <h3 class="family-name">Cheloniidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Cheloniidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Alligator_snapping_turtle.jpg/200px-Alligator_snapping_turtle.jpg"/>
 <h3 class="family-name">Chelydridae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelydridae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Dermatemydidae.JPG/200px-Dermatemydidae.JPG"/>
 <h3 class="family-name">Dermatemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermatemydidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/LeatherbackTurtle.jpg/200px-LeatherbackTurtle.jpg"/>
 <h3 class="family-name">Dermochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermochelyidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Tortoise1_cepolina.jpg/200px-Tortoise1_cepolina.jpg"/>
 <h3 class="family-name">Emydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Emydidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cuora_amboinensis_kamaroma_j.jpg/200px-Cuora_amboinensis_kamaroma_j.jpg"/>
 <h3 class="family-name">Geoemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Geoemydidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sternotherus_odoratus.jpg/200px-Sternotherus_odoratus.jpg"/>
 <h3 class="family-name">Kinosternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Kinosternidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Zolw_wielkoglowy.jpg/200px-Zolw_wielkoglowy.jpg"/>
 <h3 class="family-name">Platysternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Platysternidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Tortoise.aldabra.750pix.jpg/200px-Tortoise.aldabra.750pix.jpg"/>
 <h3 class="family-name">Testudinidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Testudinidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Apalone_spinifera.jpg/200px-Apalone_spinifera.jpg"/>
 <h3 class="family-name">Trionychidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Trionychidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg/200px-Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg"/>
 <h3 class="family-name">Chelidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Pelomedusa_subrufa.JPG/200px-Pelomedusa_subrufa.JPG"/>
 <h3 class="family-name">Pelomedusidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Pelomedusidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Erymnochelys_madagascariensis.jpg/200px-Erymnochelys_madagascariensis.jpg"/>
 <h3 class="family-name">Podocnemididae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Podocnemididae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-12 text-center text-muted">
                     Lessons and Videos © Hartley Brody 2023
                 </div><!--.col-->
 </div>]

In [42]:
list =[]
for i in frm[0:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
    }
    dict ['url']=i.find('img')['src']
    dict ['img_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    list.append(dict)

In [43]:
list

[{'name': 'Carettochelyidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Carettochelyidae'},
 {'name': 'Dermatemydidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Dermatemydidae.JPG/200px-Dermatemydidae.JPG',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Dermatemydidae'},
 {'name': 'Geoemydidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cuora_amboinensis_kamaroma_j.jpg/200px-Cuora_amboinensis_kamaroma_j.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Geoemydidae'}]

In [44]:
df = pd.DataFrame(list)
df.to_csv('scrapthisside q2_2.csv',index=False)# to save into csv file 
df

,name,url,img_url
0,Carettochelyidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
1,Dermatemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
2,Geoemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...

## 2.3 Extract all Testudines family details save into csv file.

In [45]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)

In [46]:
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')
frm

[<div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg"/>
 <h3 class="family-name">Carettochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Carettochelyidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GreenSeaTurtle-2.jpg/200px-GreenSeaTurtle-2.jpg"/>
 <h3 class="family-name">Cheloniidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Cheloniidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Alligator_snapping_turtle.jpg/200px-Alligator_snapping_turtle.jpg"/>
 <h3 class="family-name">Chelydridae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelydridae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Dermatemydidae.JPG/200px-Dermatemydidae.JPG"/>
 <h3 class="family-name">Dermatemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermatemydidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/LeatherbackTurtle.jpg/200px-LeatherbackTurtle.jpg"/>
 <h3 class="family-name">Dermochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermochelyidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Tortoise1_cepolina.jpg/200px-Tortoise1_cepolina.jpg"/>
 <h3 class="family-name">Emydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Emydidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cuora_amboinensis_kamaroma_j.jpg/200px-Cuora_amboinensis_kamaroma_j.jpg"/>
 <h3 class="family-name">Geoemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Geoemydidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sternotherus_odoratus.jpg/200px-Sternotherus_odoratus.jpg"/>
 <h3 class="family-name">Kinosternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Kinosternidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Zolw_wielkoglowy.jpg/200px-Zolw_wielkoglowy.jpg"/>
 <h3 class="family-name">Platysternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Platysternidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Tortoise.aldabra.750pix.jpg/200px-Tortoise.aldabra.750pix.jpg"/>
 <h3 class="family-name">Testudinidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Testudinidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Apalone_spinifera.jpg/200px-Apalone_spinifera.jpg"/>
 <h3 class="family-name">Trionychidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Trionychidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg/200px-Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg"/>
 <h3 class="family-name">Chelidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Pelomedusa_subrufa.JPG/200px-Pelomedusa_subrufa.JPG"/>
 <h3 class="family-name">Pelomedusidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Pelomedusidae">Learn more →</a>
 </div>,
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Erymnochelys_madagascariensis.jpg/200px-Erymnochelys_madagascariensis.jpg"/>
 <h3 class="family-name">Podocnemididae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Podocnemididae">Learn more →</a>
 </div>]

In [47]:
list =[]
for i in frm[0:14]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
    }
    dict ['url']=i.find('img')['src']
    dict ['img_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    list.append(dict)

In [48]:
list

[{'name': 'Carettochelyidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Carettochelyidae'},
 {'name': 'Cheloniidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GreenSeaTurtle-2.jpg/200px-GreenSeaTurtle-2.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Cheloniidae'},
 {'name': 'Chelydridae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Alligator_snapping_turtle.jpg/200px-Alligator_snapping_turtle.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Chelydridae'},
 {'name': 'Dermatemydidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Dermatemydidae.JPG/200px-Dermatemydidae.JPG',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Dermatemydidae'},
 {'name': 'Dermochelyidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/LeatherbackTurtle.jpg/200px-LeatherbackTurtle.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Dermochelyidae'},
 {'name': 'Emydidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Tortoise1_cepolina.jpg/200px-Tortoise1_cepolina.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Emydidae'},
 {'name': 'Geoemydidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cuora_amboinensis_kamaroma_j.jpg/200px-Cuora_amboinensis_kamaroma_j.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Geoemydidae'},
 {'name': 'Kinosternidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sternotherus_odoratus.jpg/200px-Sternotherus_odoratus.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Kinosternidae'},
 {'name': 'Platysternidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Zolw_wielkoglowy.jpg/200px-Zolw_wielkoglowy.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Platysternidae'},
 {'name': 'Testudinidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Tortoise.aldabra.750pix.jpg/200px-Tortoise.aldabra.750pix.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Testudinidae'},
 {'name': 'Trionychidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Apalone_spinifera.jpg/200px-Apalone_spinifera.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Trionychidae'},
 {'name': 'Chelidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg/200px-Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Chelidae'},
 {'name': 'Pelomedusidae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Pelomedusa_subrufa.JPG/200px-Pelomedusa_subrufa.JPG',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Pelomedusidae'},
 {'name': 'Podocnemididae',
  'url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Erymnochelys_madagascariensis.jpg/200px-Erymnochelys_madagascariensis.jpg',
  'img_url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Podocnemididae'}]

In [49]:
df = pd.DataFrame(list)
df.to_csv('scrapthisside q2_3.csv',index=False)# to save into csv file 
df

,name,url,img_url
0,Carettochelyidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
1,Cheloniidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
2,Chelydridae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
3,Dermatemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
4,Dermochelyidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
5,Emydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
6,Geoemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
7,Kinosternidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
8,Platysternidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
9,Testudinidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
10,Trionychidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
11,Chelidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
12,Pelomedusidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
13,Podocnemididae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...

## 3.1 Extract first Testudines details save into csv file. e.g# Carettochelyidae

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 
from urllib.parse import urljoin
import requests
driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)

In [2]:
driver.switch_to.frame(0)

driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find('div',class_='col-md-4 turtle-family-card')
frm

<div class="col-md-4 turtle-family-card">
<img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg"/>
<h3 class="family-name">Carettochelyidae</h3>
<a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Carettochelyidae">Learn more →</a>
</div>

In [6]:
list = []
base_url = 'https://www.scrapethissite.com/'
dict = {
    'name':'',
    'url':'',
    'img_url':'',
   "detail":'',
}
dict ['img_url']=frm.find('img')['src']
dict ['url']=base_url + frm.find('a')['href']
dict ['name']=frm.find('h3').text
dict
        

act_url = urljoin(base_url,dict["url"])
resp = requests.get(act_url)
soup_nw = BeautifulSoup(resp.text, "html.parser")
soup_nw

dict["detail"]=soup_nw.find('p').text.strip()
list.append(dict)

In [7]:
dict

{'name': 'Carettochelyidae',
 'url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Carettochelyidae',
 'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg',
 'detail': 'The Carettochelyidae family of turtles — more commonly known as "Pig-nosed turtle" — were first discovered in 1887 by Boulenger.'}

In [8]:
df = pd.DataFrame(list)
df.to_csv('scrapthisside q3_1.csv',index=False)# to save into csv file 
df

,name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...

## 3.2 Extract Testudines family details from first row & save into csv file. e.g# Carettochelyidae, Cheloniidae, Chelydridae

In [10]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd
from urllib.parse import urljoin
import requests 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)

In [11]:
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='row')
frm

[<div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg"/>
 <h3 class="family-name">Carettochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Carettochelyidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GreenSeaTurtle-2.jpg/200px-GreenSeaTurtle-2.jpg"/>
 <h3 class="family-name">Cheloniidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Cheloniidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Alligator_snapping_turtle.jpg/200px-Alligator_snapping_turtle.jpg"/>
 <h3 class="family-name">Chelydridae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelydridae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Dermatemydidae.JPG/200px-Dermatemydidae.JPG"/>
 <h3 class="family-name">Dermatemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermatemydidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/LeatherbackTurtle.jpg/200px-LeatherbackTurtle.jpg"/>
 <h3 class="family-name">Dermochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermochelyidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Tortoise1_cepolina.jpg/200px-Tortoise1_cepolina.jpg"/>
 <h3 class="family-name">Emydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Emydidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cuora_amboinensis_kamaroma_j.jpg/200px-Cuora_amboinensis_kamaroma_j.jpg"/>
 <h3 class="family-name">Geoemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Geoemydidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sternotherus_odoratus.jpg/200px-Sternotherus_odoratus.jpg"/>
 <h3 class="family-name">Kinosternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Kinosternidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Zolw_wielkoglowy.jpg/200px-Zolw_wielkoglowy.jpg"/>
 <h3 class="family-name">Platysternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Platysternidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Tortoise.aldabra.750pix.jpg/200px-Tortoise.aldabra.750pix.jpg"/>
 <h3 class="family-name">Testudinidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Testudinidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Apalone_spinifera.jpg/200px-Apalone_spinifera.jpg"/>
 <h3 class="family-name">Trionychidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Trionychidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg/200px-Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg"/>
 <h3 class="family-name">Chelidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Pelomedusa_subrufa.JPG/200px-Pelomedusa_subrufa.JPG"/>
 <h3 class="family-name">Pelomedusidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Pelomedusidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Erymnochelys_madagascariensis.jpg/200px-Erymnochelys_madagascariensis.jpg"/>
 <h3 class="family-name">Podocnemididae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Podocnemididae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-12 text-center text-muted">
                     Lessons and Videos © Hartley Brody 2023
                 </div><!--.col-->
 </div>]

In [29]:
list =[]



for i in frm[0:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['url']=i.find('img')['src']
    dict ['img_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    list.append(dict)
    act_url = urljoin(base_url,dict["url"])
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(url, headers=headers)
    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()

In [27]:
df = pd.DataFrame(list)
df.to_csv('scrapthisside q3_2.csv',index=False)# to save into csv file 
df

,name,url,img_url,detail
0,Carettochelyidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...,Some older sites might still use frames to bre...
1,Dermatemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...,Some older sites might still use frames to bre...
2,Geoemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...,Some older sites might still use frames to bre...

## 2.1 Extract first Testudines details save into csv file. e.g# Carettochelyidae

In [71]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://www.scrapethissite.com/pages/frames/")

In [72]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<meta charset="utf-8"/>
<title>Turtles All the Way Down: Frames &amp; iFrames | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li class="active" id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-09N5RQCFG4&amp;cx=c&amp;_slc=1" type="text/javascript"></script><script async="" src="https://connect.facebook.net/signals/config/764287443701341?v=2.9.243&amp;r=stable&amp;domain=www.scrapethissite.com&amp;hme=fdfab1132115f4ac7aabc9fd7eee63947594f6e6f1735b47a225dd71217525d3&amp;ex_m=89%2C147%2C127%2C18%2C65%2C66%2C120%2C61%2C41%2C121%2C70%2C60%2C134%2C78%2C13%2C88%2C26%2C115%2C108%2C68%2C71%2C114%2C131%2C97%2C136%2C7%2C3%2C4%2C6%2C5%2C2%2C79%2C87%2C137%2C214%2C158%2C55%2C216%2C217%2C48%2C173%2C25%2C67%2C222%2C221%2C161%2C28%2C54%2C8%2C57%2C83%2C84%2C85%2C90%2C111%2C27%2C24%2C113%2C110%2C109%2C128%2C69%2C130%2C129%2C43%2C53%2C105%2C12%2C133%2C38%2C203%2C205%2C168%2C21%2C22%2C23%2C15%2C16%2C37%2C33%2C35%2C34%2C74%2C80%2C82%2C95%2C119%2C122%2C39%2C96%2C19%2C17%2C101%2C62%2C31%2C124%2C123%2C125%2C116%2C20%2C30%2C52%2C94%2C132%2C63%2C14%2C126%2C29%2C183%2C154%2C275%2C201%2C145%2C186%2C179%2C155%2C92%2C112%2C73%2C103%2C47%2C40%2C102%2C107%2C51%2C58%2C42%2C98%2C46%2C49%2C45%2C86%2C135%2C0%2C106%2C11%2C104%2C9%2C1%2C50%2C81%2C56%2C59%2C100%2C77%2C76%2C44%2C117%2C75%2C72%2C64%2C99%2C91%2C36%2C118%2C32%2C93%2C10%2C138"></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script async="" src="https://www.google-analytics.com/analytics.js"></script><script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="frames">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Turtles All the Way Down: Frames &amp; iFrames
                            <small>14 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.
                            See if you can find the 'real' URL that our content is being loaded from, and scrape that page. Also practice interating over a list of items and loading their detail pages to get more information about each one.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">3 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="https://en.wikipedia.org/wiki/List_of_Testudines_families" target="_blank">https://en.wikipedia.org/wiki/List_of_Testudines_families</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<noframes>
                                        Your browser does not support frames.
                                </noframes>
<iframe id="iframe" src="/pages/frames/?frame=i">
                                Your browser does not support iframes
                            </iframe>
</div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
</div><!--#page-->
<section id="footer">
<div class="container">
<div class="row">
<div class="col-md-12 text-center text-muted">
                    Lessons and Videos © Hartley Brody 2023
                </div><!--.col-->
</div><!--.row-->
</div><!--.container-->
</section>
<script crossorigin="anonymous" data-cf-beacon='{"version":"2024.11.0","token":"876766d8a2734c408f9198f80ced491f","r":1,"server_timing":{"name":{"cfCacheStatus":true,"cfEdge":true,"cfExtPri":true,"cfL4":true,"cfOrigin":true,"cfSpeedBrain":true},"location_startswith":null}}' defer="" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script crossorigin="anonymous" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css"/>
<!-- pnotify messages -->
<script type="text/javascript">

    PNotify.prototype.options.styling = "bootstrap3";
    $(function(){

    });


    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
<!-- golbal video controls -->
<script type="text/javascript">
    $("video").hover(function() {
        $(this).prop("controls", true);
    }, function() {
        $(this).prop("controls", false);
    });

    $("video").click(function() {
        if( this.paused){
            this.play();
        }
        else {
            this.pause();
        }
    });
    </script>
<!-- insert google analytics here -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41551755-8', 'auto');
    ga('send', 'pageview');
  </script>
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '764287443701341');
  fbq('track', "PageView");</script>
<noscript><img height="1" src="https://www.facebook.com/tr?id=764287443701341&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript>
<!-- End Facebook Pixel Code -->
<!-- Google Code for Remarketing Tag -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 950945448;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
<script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript">
</script><script async="" src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?random=1763747927929&amp;cv=9&amp;fst=1763747927929&amp;num=1&amp;guid=ON&amp;resp=GooglemKTybQhCsO&amp;eid=375603260%2C466465925%2C512247838%2C658953496&amp;u_h=768&amp;u_w=1366&amp;ig=1&amp;frm=0&amp;url=https%3A%2F%2Fwww.scrapethissite.com%2Fpages%2Fframes%2F&amp;tiba=Turtles%20All%20the%20Way%20Down%3A%20Frames%20%26%20iFrames%20%7C%20Scrape%20This%20Site%20%7C%20A%20public%20sandbox%20for%20learning%20web%20scraping&amp;hn=www.googleadservices.com&amp;rfmt=3&amp;fmt=4" type="text/javascript"></script>
<noscript>
<div style="display:inline;">
<img alt="" height="1" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0" style="border-style:none;" width="1"/>
</div>
</noscript>
<!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-950945448"></script>
<script>
   window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'AW-950945448');
  </script>
<iframe height="0" style="display: none; visibility: hidden;" width="0"></iframe><script async="" src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?random=1763747928073&amp;cv=11&amp;fst=1763747928073&amp;bg=ffffff&amp;guid=ON&amp;async=1&amp;en=gtag.config&amp;gtm=45be5bi1za200xec&amp;gcd=13l3l3l3l1l1&amp;dma=0&amp;tag_exp=103116026~103200004~104527906~104528500~104684208~104684211~105322303~115583767~115938465~115938469~116184927~116184929~116217636~116217638~116251935~116251937~116474637&amp;u_w=1366&amp;u_h=768&amp;url=https%3A%2F%2Fwww.scrapethissite.com%2Fpages%2Fframes%2F&amp;frm=0&amp;tiba=Turtles%20All%20the%20Way%20Down%3A%20Frames%20%26%20iFrames%20%7C%20Scrape%20This%20Site%20%7C%20A%20public%20sandbox%20for%20learning%20web%20scraping&amp;hn=www.googleadservices.com&amp;npa=0&amp;pscdl=noapi&amp;auid=1485856305.1763747928&amp;uaa=x86&amp;uab=64&amp;uafvl=Chromium%3B142.0.7444.60%7CGoogle%2520Chrome%3B142.0.7444.60%7CNot_A%2520Brand%3B99.0.0.0&amp;uamb=0&amp;uam=&amp;uap=Windows&amp;uapv=10.0.0&amp;uaw=0&amp;data=event%3Dgtag.config&amp;rfmt=3&amp;fmt=4" type="text/javascript"></script></body></html>

In [78]:
rows = soup.find('div',class_='col-md-4 turtle-family-card')
rows