## 4.1 Extract first product details save into csv file. e.g# Packard 255 G2

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops")

In [54]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<!-- Google Tag Manager -->
<script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bj0h2" type="text/javascript"></script><script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB"></script><script nonce="">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Ajax | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops?page=" rel="canonical"/>
<meta content="Ajax | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops?page=" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/ajax" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/ajax/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/ajax/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

In [55]:
product = soup.find('div',class_='product-wrapper card-body')
product

<div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$295.99</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">Asus VivoBook X4</a></h4><p class="card-text description" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">1</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div>

In [56]:
list = []
prod_dictionary = {
    'product_name': '',
    'product_link': '',
    'product_img': '',
    'product_price': '',
    'product_details': '',
    'product_reviews_number': '',
    'product_reviews_star_number': '',
}

In [57]:
prod_dictionary['product_name']= product.find('a').text.strip()
prod_dictionary['product_details']=product.find('p').text
prod_dictionary['product_img']=product.find('img')['src']
prod_dictionary['product_link']=product.find('a')['href']
prod_dictionary['product_reviews_number']=product.find('div',class_='ratings').text.strip()
prod_dictionary['product_reviews_star_number']
prod_dictionary['product_price']=product.find('h4').text.strip()
list.append(prod_dictionary)

In [58]:
prod_dictionary

{'product_name': 'Asus VivoBook X4',
 'product_link': '/test-sites/e-commerce/ajax/product/60',
 'product_img': '/images/test-sites/e-commerce/items/cart2.png',
 'product_price': '$295.99',
 'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
 'product_reviews_number': '1 reviews',
 'product_reviews_star_number': ''}

In [11]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q4_1.csv',index=False)

## 4.2 Extract product details from first row & save into csv file. e.g# Packard 255 G2, Aspire E1-510, ThinkPad T540p

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops")

In [16]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<!-- Google Tag Manager -->
<script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bj0h2" type="text/javascript"></script><script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB"></script><script nonce="">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Ajax | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops" rel="canonical"/>
<meta content="Ajax | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/ajax" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/ajax/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/ajax/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

In [17]:
products = soup.find_all('div',class_='row')
products

[<div class="row">
 <div class="col-lg-12">
 <h1>Test Sites</h1>
 </div>
 </div>,
 <div class="row">
 <div class="col-lg-3 sidebar">
 <div class="navbar-light sidebar" role="navigation">
 <div class="sidebar-nav navbar-collapse">
 <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
 <li class="nav-item">
 <a class="nav-link" href="/test-sites/e-commerce/ajax" itemprop="url"><span itemprop="name">Home</span></a>
 </li>
 <li class="nav-item active">
 <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/computers" itemprop="url">
 <span itemprop="name">Computers</span>
 <i aria-hidden="true" class="ws-icon ws-icon-right"></i>
 </a>
 <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
 <li class="nav-item">
 <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/ajax/computers/laptops" itemprop="url">
 <span itemprop="name">Laptops</span>
 </a>
 </li>
 <li class="nav-item">
 <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/ajax/computers/tablets" itemprop="url">
 <span itemprop="name">Tablets</span>
 </a>
 </li>
 </ul>
 </li>
 <li class="nav-item">
 <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/phones" itemprop="url">
 <span itemprop="name">Phones</span>
 <i aria-hidden="true" class="ws-icon ws-icon-right"></i>
 </a>
 </li>
 </ul>
 </div>
 </div>
 </div>
 <div class="col-lg-9">
 <h1 class="page-header">Computers / Laptops</h1>

In [39]:
main_div = products[2]

all_products = main_div.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
len(all_products)
# all_products

6

In [40]:
len(products)

5

In [29]:
list = []
for i in all_products[0:3]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
 } 
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [30]:
list

[{'product_name': 'Asus VivoBook X4',
  'product_link': '/test-sites/e-commerce/ajax/product/60',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$295.99',
  'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_reviews_number': '1 reviews',
  'product_reviews_star_number': ''},
 {'product_name': 'Prestigio SmartB',
  'product_link': '/test-sites/e-commerce/ajax/product/61',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '9 reviews',
  'product_reviews_star_number': ''},
 {'product_name': 'Prestigio SmartB',
  'product_link': '/test-sites/e-commerce/ajax/product/62',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '9 reviews',
  'product_reviews_star_number': ''}]

In [31]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q4_2.csv',index=False)

## 4.3 Extract all product details from first page & save into csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops")

In [32]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<!-- Google Tag Manager -->
<script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bj0h2" type="text/javascript"></script><script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB"></script><script nonce="">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Ajax | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops" rel="canonical"/>
<meta content="Ajax | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/ajax" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/ajax/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/ajax/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

In [34]:
all_products = main_div.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products
len(all_products)

6

In [41]:
list = []
for i in all_products[0:6]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [42]:
list

[{'product_name': 'Asus VivoBook X4',
  'product_link': '/test-sites/e-commerce/ajax/product/60',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$295.99',
  'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_reviews_number': '1 reviews',
  'product_reviews_star_number': ''},
 {'product_name': 'Prestigio SmartB',
  'product_link': '/test-sites/e-commerce/ajax/product/61',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '9 reviews',
  'product_reviews_star_number': ''},
 {'product_name': 'Prestigio SmartB',
  'product_link': '/test-sites/e-commerce/ajax/product/62',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '9 reviews',
  'product_reviews_star_number': ''},
 {'product_name': 'Aspire E1-510',
  'product_link': '/test-sites/e-commerce/ajax/product/32',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$306.99',
  'product_details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'product_reviews_number': '2 reviews',
  'product_reviews_star_number': ''},
 {'product_name': 'Lenovo V110-15IA',
  'product_link': '/test-sites/e-commerce/ajax/product/63',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$321.94',
  'product_details': 'Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '12 reviews',
  'product_reviews_star_number': ''},
 {'product_name': 'Lenovo V110-15IA',
  'product_link': '/test-sites/e-commerce/ajax/product/64',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$356.49',
  'product_details': 'Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd',
  'product_reviews_number': '12 reviews',
  'product_reviews_star_number': ''}]

In [43]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q4_3.csv',index=False)

## 4.4 Extract all product details from second page & save into another csv file.

In [3]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Edge()
driver.get("https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops?page=")

In [60]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<!-- Google Tag Manager -->
<script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bi1" type="text/javascript"></script><script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB"></script><script nonce="">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Ajax | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops?page=" rel="canonical"/>
<meta content="Ajax | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops?page=" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/ajax" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/ajax/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/ajax/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops") # to get the url 
driver.get(url)
for j in range(2): 
    driver.find_element("xpath",f'//div[@class={j}]').click() # difrent file are element to chcek and click to  secand wibsite
    print(j) # print j this is all wibsite data
    time.sleep(3) # this a timer 
    soup = BeautifulSoup(driver.page_source, 'html.parser') # to website html code 
    
    for i in all_products:
            prod_dictionary = {
                'product_name': '',
                'product_link': '',
                'product_img': '',
                'product_price': '',
                'product_details': '',
                'product_reviews_number': '',
                'product_reviews_star_number': '',
            }
            prod_dictionary['product_name']= i.find('a').text.strip()
            prod_dictionary['product_details']=i.find('p').text
            prod_dictionary['product_img']=i.find('img')['src']
            prod_dictionary['product_link']=i.find('a')['href']
            prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
            prod_dictionary['product_reviews_star_number']
            prod_dictionary['product_price']=i.find('h4').text.strip()
            list.append(prod_dictionary)
            df = pd.DataFrame(list) # to convert to data frame 
            df
            df.to_csv(f'scrapthisside q4_4{j}.csv',index=False)# to save into csv file 
            df

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@class=0]"}
  (Session info: MicrosoftEdge=142.0.3595.94); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff603afa715
	0x7ff603afa774
	0x7ff603cac558
	0x7ff6038b40ce
	0x7ff6038b431b
	0x7ff6038f0777
	0x7ff6038ab3d5
	0x7ff6038ee6f2
	0x7ff6038aa8aa
	0x7ff6038a9bd1
	0x7ff6038aa6d3
	0x7ff6039681f4
	0x7ff603964717
	0x7ff603b27375
	0x7ff603b157d1
	0x7ff603b1dc79
	0x7ff603b01c64
	0x7ff603b01db3
	0x7ff603aefae6
	0x7ff89f457374
	0x7ff89fb9cc91

In [14]:
driver.find_elements("xpath",f'//div[@class="btn-group pagination justify-content-center"]')[0]
driver

## 5.1 Extract first product details save into csv file. e.g# Asus VivoBook X4

In [69]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Edge()

driver.get("https://webscraper.io/test-sites/e-commerce/more/computers/laptops")

In [70]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<!-- Google Tag Manager -->
<script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bi1h1" type="text/javascript"></script><script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB"></script><script nonce="">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>More | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/more/computers/laptops" rel="canonical"/>
<meta content="More | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/more/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://microsoftedge.microsoft.com/addons/detail/web-scraper-free-web-sc/jfmdjnnfminejadhegajcjbpgjofnkaj" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-edge-500 ws-icon-edge-dark"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/more" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/more/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/more/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/more/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/more/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

In [71]:
product = soup.find('div',class_='product-wrapper card-body')
product

<div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$295.99</h4><h4><a class="title" href="/test-sites/e-commerce/more/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">Asus VivoBook X4</a></h4><p class="card-text description" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">1</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div>

In [72]:
list = []
prod_dictionary = {
    'product_name': '',
    'product_link': '',
    'product_img': '',
    'product_price': '',
    'product_details': '',
    'product_reviews_number': '',
    'product_reviews_star_number': '',
}

In [73]:
prod_dictionary['product_name']= product.find('a').text.strip()
prod_dictionary['product_details']=product.find('p').text
prod_dictionary['product_img']=product.find('img')['src']
prod_dictionary['product_link']=product.find('a')['href']
prod_dictionary['product_reviews_number']=product.find('div',class_='ratings').text.strip()
prod_dictionary['product_reviews_star_number']
prod_dictionary['product_price']=product.find('h4').text.strip()
list.append(prod_dictionary)

In [74]:
list

[{'product_name': 'Asus VivoBook X4',
  'product_link': '/test-sites/e-commerce/more/product/60',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$295.99',
  'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_reviews_number': '1 reviews',
  'product_reviews_star_number': ''}]

In [75]:
import pandas as pd
df = pd.DataFrame(list)
df
df.to_csv('webscraper io 5_1.csv',index=False)

## 5.2 Extract product details from first row & save into csv file. e.g# Asus VivoBook X4, Prestigio SmartB , Asus VivoBook X4

In [77]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Edge()
driver.get("https://webscraper.io/test-sites/e-commerce/more/computers/laptops")


soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<!-- Google Tag Manager -->
<script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bj0h2" type="text/javascript"></script><script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB"></script><script nonce="">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>More | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/more/computers/laptops" rel="canonical"/>
<meta content="More | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/more/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://microsoftedge.microsoft.com/addons/detail/web-scraper-free-web-sc/jfmdjnnfminejadhegajcjbpgjofnkaj" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-edge-500 ws-icon-edge-dark"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/more" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/more/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/more/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/more/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/more/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

In [78]:
products = soup.find_all('div',class_='row')
products

[<div class="row">
 <div class="col-lg-12">
 <h1>Test Sites</h1>
 </div>
 </div>,
 <div class="row">
 <div class="col-lg-3 sidebar">
 <div class="navbar-light sidebar" role="navigation">
 <div class="sidebar-nav navbar-collapse">
 <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
 <li class="nav-item">
 <a class="nav-link" href="/test-sites/e-commerce/more" itemprop="url"><span itemprop="name">Home</span></a>
 </li>
 <li class="nav-item active">
 <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/more/computers" itemprop="url">
 <span itemprop="name">Computers</span>
 <i aria-hidden="true" class="ws-icon ws-icon-right"></i>
 </a>
 <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
 <li class="nav-item">
 <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/more/computers/laptops" itemprop="url">
 <span itemprop="name">Laptops</span>
 </a>
 </li>
 <li class="nav-item">
 <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/more/computers/tablets" itemprop="url">
 <span itemprop="name">Tablets</span>
 </a>
 </li>
 </ul>
 </li>
 <li class="nav-item">
 <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/more/phones" itemprop="url">
 <span itemprop="name">Phones</span>
 <i aria-hidden="true" class="ws-icon ws-icon-right"></i>
 </a>
 </li>
 </ul>
 </div>
 </div>
 </div>
 <div class="col-lg-9">
 <h1 class="page-header">Computers / Laptops</h1>

In [80]:
all_products = main_div.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products
# len(all_products)

[<div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$295.99</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">Asus VivoBook X4</a></h4><p class="card-text description" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">1</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$299</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">Prestigio SmartB</a></h4><p class="card-text description" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">9</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$299</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">Prestigio SmartB</a></h4><p class="card-text description" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">9</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$306.99</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/32" itemprop="name" title="Aspire E1-510">Aspire E1-510</a></h4><p class="card-text description" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">2</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$321.94</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/63" itemprop="name" title="Lenovo V110-15IAP">Lenovo V110-15IA</a></h4><p class="card-text description" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">12</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$356.49</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/64" itemprop="name" title="Lenovo V110-15IAP">Lenovo V110-15IA</a></h4><p class="card-text description" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">12</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>]

In [81]:
list = []
for i in all_products[0:3]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [82]:
list

[{'product_name': 'Asus VivoBook X4',
  'product_link': '/test-sites/e-commerce/ajax/product/60',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$295.99',
  'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_reviews_number': '1 reviews',
  'product_reviews_star_number': ''},
 {'product_name': 'Prestigio SmartB',
  'product_link': '/test-sites/e-commerce/ajax/product/61',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '9 reviews',
  'product_reviews_star_number': ''},
 {'product_name': 'Prestigio SmartB',
  'product_link': '/test-sites/e-commerce/ajax/product/62',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '9 reviews',
  'product_reviews_star_number': ''}]

In [83]:
import pandas as pd
df = pd.DataFrame(list)
df
df.to_csv('webscraper io 5_2.csv',index=False)

## 5.3 Extract all product details from first page & save into csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Edge()
driver.get("https://webscraper.io/test-sites/e-commerce/more/computers/laptops")


soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

In [84]:
all_products = main_div.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products
# len(all_products)

[<div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$295.99</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">Asus VivoBook X4</a></h4><p class="card-text description" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">1</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$299</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">Prestigio SmartB</a></h4><p class="card-text description" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">9</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$299</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">Prestigio SmartB</a></h4><p class="card-text description" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">9</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$306.99</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/32" itemprop="name" title="Aspire E1-510">Aspire E1-510</a></h4><p class="card-text description" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">2</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$321.94</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/63" itemprop="name" title="Lenovo V110-15IAP">Lenovo V110-15IA</a></h4><p class="card-text description" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">12</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$356.49</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/64" itemprop="name" title="Lenovo V110-15IAP">Lenovo V110-15IA</a></h4><p class="card-text description" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">12</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>]

In [85]:
list = []
for i in all_products[0:6]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [86]:
import pandas as pd
df = pd.DataFrame(list)
df
df.to_csv('webscraper io 5_3.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Asus VivoBook X4,/test-sites/e-commerce/ajax/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",1 reviews,
1,Prestigio SmartB,/test-sites/e-commerce/ajax/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",9 reviews,
2,Prestigio SmartB,/test-sites/e-commerce/ajax/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",9 reviews,
3,Aspire E1-510,/test-sites/e-commerce/ajax/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews,
4,Lenovo V110-15IA,/test-sites/e-commerce/ajax/product/63,/images/test-sites/e-commerce/items/cart2.png,$321.94,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",12 reviews,
5,Lenovo V110-15IA,/test-sites/e-commerce/ajax/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,12 reviews,

## 5.3 Extract all product details from first page & save into csv file.

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Edge()
driver.get("https://webscraper.io/test-sites/e-commerce/more/computers/laptops")


soup = BeautifulSoup(driver.page_source, 'html.parser')

soup

<html lang="en"><head>
<!-- Google Tag Manager -->
<script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bi1" type="text/javascript"></script><script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB"></script><script nonce="">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>More | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/more/computers/laptops" rel="canonical"/>
<meta content="More | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/more/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://microsoftedge.microsoft.com/addons/detail/web-scraper-free-web-sc/jfmdjnnfminejadhegajcjbpgjofnkaj" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-edge-500 ws-icon-edge-dark"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/more" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/more/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/more/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/more/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/more/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

## 6.1 Extract first product details save into csv file. e.g# Asus VivoBook X4

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Edge()

driver.get("https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops")

In [2]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<!-- Google Tag Manager -->
<script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bi1" type="text/javascript"></script><script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB"></script><script nonce="">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Scroll | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops" rel="canonical"/>
<meta content="Scroll | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://microsoftedge.microsoft.com/addons/detail/web-scraper-free-web-sc/jfmdjnnfminejadhegajcjbpgjofnkaj" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-edge-500 ws-icon-edge-dark"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/scroll" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/scroll/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/scroll/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/scroll/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/scroll/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

In [3]:
product = soup.find('div',class_='product-wrapper card-body')
product

<div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$295.99</h4><h4><a class="title" href="/test-sites/e-commerce/scroll/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">Asus VivoBook X4</a></h4><p class="card-text description" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">1</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div>

In [4]:
list = []
prod_dictionary = {
    'product_name': '',
    'product_link': '',
    'product_img': '',
    'product_price': '',
    'product_details': '',
    'product_reviews_number': '',
    'product_reviews_star_number': '',
}

In [5]:
prod_dictionary['product_name']= product.find('a').text.strip()
prod_dictionary['product_details']=product.find('p').text
prod_dictionary['product_img']=product.find('img')['src']
prod_dictionary['product_link']=product.find('a')['href']
prod_dictionary['product_reviews_number']=product.find('div',class_='ratings').text.strip()
prod_dictionary['product_reviews_star_number']
prod_dictionary['product_price']=product.find('h4').text.strip()
list.append(prod_dictionary)

In [6]:
import pandas as pd
df = pd.DataFrame(list)
df
df.to_csv('webscraper io 6_1.csv',index=False)

## 6.2 Extract product details from first row & save into csv file. e.g# Asus VivoBook X4, Prestigio SmartB , prestigio SmartB

In [21]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Edge()

driver.get("https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops")

In [22]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
soup

<html lang="en"><head>
<!-- Google Tag Manager -->
<script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bi1" type="text/javascript"></script><script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB"></script><script nonce="">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Scroll | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops" rel="canonical"/>
<meta content="Scroll | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://microsoftedge.microsoft.com/addons/detail/web-scraper-free-web-sc/jfmdjnnfminejadhegajcjbpgjofnkaj" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-edge-500 ws-icon-edge-dark"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a class="nav-link" href="/test-sites/e-commerce/scroll" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item active">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/scroll/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
<ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/scroll/computers/laptops" itemprop="url">
<span itemprop="name">Laptops</span>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/scroll/computers/tablets" itemprop="url">
<span itemprop="name">Tablets</span>
</a>
</li>
</ul>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/scroll/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<h1 class="page-header">Computers / Laptops</h1>

In [ ]:
all_products = soup.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")

all_products
# len(all_products)

3

In [24]:
list = []
for i in all_products[0:3]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [25]:
import pandas as pd
df = pd.DataFrame(list)
df
df.to_csv('webscraper io 6_2.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Asus VivoBook X4,/test-sites/e-commerce/scroll/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",1 reviews,
1,Prestigio SmartB,/test-sites/e-commerce/scroll/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",9 reviews,
2,Prestigio SmartB,/test-sites/e-commerce/scroll/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",9 reviews,

## 6.3 Extract all product details from first page & save into csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Edge()

driver.get("https://webscraper.io/test-sites/e-commerce/scroll/computers/laptops")