##  2. https://www.scrapethissite.com/pages/ (header, paragraph, header_link)
	## 2.1 Extract first paragraph details of a page & save into csv file.
	## 2.2 Extract all paragraphs details of a page & save into csv file.

In [ ]:
import requests # requests Library
from bs4 import BeautifulSoup
import pandas as pd
url = "https://www.scrapethissite.com/pages/" # store Web page url in variable
r = requests.get(url)
r.status_code

In [ ]:
soup = BeautifulSoup(r.text, "html.parser") # parsing Webpage
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <meta charset="utf-8"/>\n  <title>\n   Learn Web Scraping | Scrape This Site | A public sandbox for learning web scraping\n  </title>\n  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>\n  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n  <meta content="Here are some practice pages you can scrape." name="description"/>\n  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>\n  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>\n  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>\n </head>\n <body>\n  <nav id="site-nav">\n   <div class="container">\n    <div class="col-md-12">\n     <ul class="nav nav-tabs">\n      <li id="nav-homepage">\n       <a class="nav-link hidden-sm hidden-xs" href="/">\n        <img id="nav-logo" src="/static/images/scraper-icon.png"/>\n        Scrape This Site\n       </a>\n      </li>\n      <li id="nav-sandbox">\n       <a class="nav-link" href="/pages/">\n        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">\n        </i>\n        Sandbox\n       </a>\n      </li>\n      <li id="nav-lessons">\n       <a class="nav-link" href="/lessons/">\n        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">\n        </i>\n        Lessons\n       </a>\n      </li>\n      <li id="nav-faq">\n       <a class="nav-link" href="/faq/">\n        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">\n        </i>\n        FAQ\n       </a>\n      </li>\n      <li class="pull-right" id="nav-login">\n       <a class="nav-link" href="/login/">\n        Login\n       </a>\n      </li>\n     </ul>\n    </div>\n   </div>\n  </nav>\n  <script type="text/javascript">\n   var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n  </script>\n  <div id="pages">\n   <section>\n    <div class="container">\n     <div class="row">\n      <div class="col-md-6 col-md-offset-3">\n       <h1>\n        Web Scraping Sandbox\n       </h1>\n       <hr/>\n       <div class="page">\n        <h3 class="page-title">\n         <a href="/pages/simple/">\n          Countries of the World: A Simple Example\n         </a>\n        </h3>\n        <p class="lead session-desc">\n         A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n        </p>\n        <hr/>\n       </div>\n       <!--.page-->\n       <div class="page">\n        <h3 class="page-title">\n         <a href="/pages/forms/">\n          Hockey Teams: Forms, Searching and Pagination\n         </a>\n        </h3>\n        <p class="lead session-desc">\n         Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.\n        </p>\n        <hr/>\n       </div>\n       <!--.page-->\n       <div class="page">\n        <h3 class="page-title">\n         <a href="/pages/ajax-javascript/">\n          Oscar Winning Films: AJAX and Javascript\n         </a>\n        </h3>\n        <p class="lead session-desc">\n         Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it.\n        </p>\n        <hr/>\n       </div>\n       <!--.page-->\n       <div class="page">\n        <h3 class="page-title">\n         <a href="/pages/frames/">\n          Turtles All the Way Down: Frames &amp; iFrames\n         </a>\n        </h3>\n        <p class="lead session-desc">\n         Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.\n        </p>\n        <hr/>\n       </div>\n       <!--.page-->\n       <div class="page">\n        <h3 class="page-title">\n         <a href="/pages/advanced/">\n          Advanced Topics: Real World Challenges You\'ll Encounter\n         </a>\n        </h3>\n        <p class="lead session-desc">\n         Scraping real websites, you\'re likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.\n        </p>\n        <hr/>\n       </div>\n       <!--.page-->\n      </div>\n      <!--.col-->\n     </div>\n     <!--.row-->\n    </div>\n    <!--.container-->\n   </section>\n  </div>\n  <section id="footer">\n   <div class="container">\n    <div class="row">\n     <div class="col-md-12 text-center text-muted">\n      Lessons and Videos © Hartley Brody 2023\n     </div>\n     <!--.col-->\n    </div>\n    <!--.row-->\n   </div>\n   <!--.container-->\n  </section>\n </body>\n <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">\n </script>\n <script crossorigin="anonymous" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js">\n </script>\n <script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js">\n </script>\n <link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css"/>\n <!-- pnotify messages -->\n <script type="text/javascript">\n  PNotify.prototype.options.styling = "bootstrap3";\n    $(function(){\n      \n    });\n    \n\n    $(function () {\n      $(\'[data-toggle="tooltip"]\').tooltip()\n    })\n </script>\n <!-- golbal video controls -->\n <script type="text/javascript">\n  $("video").hover(function() {\n        $(this).prop("controls", true);\n    }, function() {\n        $(this).prop("controls", false);\n    });\n\n    $("video").click(function() {\n        if( this.paused){\n            this.play();\n        }\n        else {\n            this.pause();\n        }\n    });\n </script>\n <!-- insert google analytics here -->\n <script>\n  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){\n    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n    })(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');\n\n    ga(\'create\', \'UA-41551755-8\', \'auto\');\n    ga(\'send\', \'pageview\');\n </script>\n <!-- Facebook Pixel Code -->\n <script>\n  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?\n  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;\n  n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;\n  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,\n  document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');\n\n  fbq(\'init\', \'764287443701341\');\n  fbq(\'track\', "PageView");\n </script>\n <noscript>\n  <img height="1" src="https://www.facebook.com/tr?id=764287443701341&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/>\n </noscript>\n <!-- End Facebook Pixel Code -->\n <!-- Google Code for Remarketing Tag -->\n <script type="text/javascript">\n  /* <![CDATA[ */\n    var google_conversion_id = 950945448;\n    var google_custom_params = window.google_tag_params;\n    var google_remarketing_only = true;\n    /* ]]> */\n </script>\n <script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript">\n </script>\n <noscript>\n  <div style="display:inline;">\n   <img alt="" height="1" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0" style="border-style:none;" width="1"/>\n  </div>\n </noscript>\n <!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->\n <script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-950945448">\n </script>\n <script>\n  window.dataLayer = window.dataLayer || [];\n   function gtag(){dataLayer.push(arguments);}\n   gtag(\'js\', new Date());\n\n   gtag(\'config\', \'AW-950945448\');\n </script>\n</html>\n'

In [ ]:
body = soup.find("div" , class_= "col-md-6 col-md-offset-3") # storing div
body.prettify()

'<div class="col-md-6 col-md-offset-3">\n <h1>\n  Web Scraping Sandbox\n </h1>\n <hr/>\n <div class="page">\n  <h3 class="page-title">\n   <a href="/pages/simple/">\n    Countries of the World: A Simple Example\n   </a>\n  </h3>\n  <p class="lead session-desc">\n   A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n  </p>\n  <hr/>\n </div>\n <!--.page-->\n <div class="page">\n  <h3 class="page-title">\n   <a href="/pages/forms/">\n    Hockey Teams: Forms, Searching and Pagination\n   </a>\n  </h3>\n  <p class="lead session-desc">\n   Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.\n  </p>\n  <hr/>\n </div>\n <!--.page-->\n <div class="page">\n  <h3 class="page-title">\n   <a href="/pages/ajax-javascript/">\n    Oscar Winning Films: AJAX and Javascript\n   </a>\n  </h3>\n  <p class="lead session-desc">\n   Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it.\n  </p>\n  <hr/>\n </div>\n <!--.page-->\n <div class="page">\n  <h3 class="page-title">\n   <a href="/pages/frames/">\n    Turtles All the Way Down: Frames &amp; iFrames\n   </a>\n  </h3>\n  <p class="lead session-desc">\n   Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.\n  </p>\n  <hr/>\n </div>\n <!--.page-->\n <div class="page">\n  <h3 class="page-title">\n   <a href="/pages/advanced/">\n    Advanced Topics: Real World Challenges You\'ll Encounter\n   </a>\n  </h3>\n  <p class="lead session-desc">\n   Scraping real websites, you\'re likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.\n  </p>\n  <hr/>\n </div>\n <!--.page-->\n</div>\n'

In [ ]:
body.find_all("h3") # finding H3

[<h3 class="page-title">
 <a href="/pages/simple/">Countries of the World: A Simple Example</a>
 </h3>,
 <h3 class="page-title">
 <a href="/pages/forms/">Hockey Teams: Forms, Searching and Pagination</a>
 </h3>,
 <h3 class="page-title">
 <a href="/pages/ajax-javascript/">Oscar Winning Films: AJAX and Javascript</a>
 </h3>,
 <h3 class="page-title">
 <a href="/pages/frames/">Turtles All the Way Down: Frames &amp; iFrames</a>
 </h3>,
 <h3 class="page-title">
 <a href="/pages/advanced/">Advanced Topics: Real World Challenges You'll Encounter</a>
 </h3>]

In [ ]:
body.find_all("p") # finding paragraphs

[<p class="lead session-desc">
                                 A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                             </p>,
 <p class="lead session-desc">
                                 Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                             </p>,
 <p class="lead session-desc">
                                 Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it.
                             </p>,
 <p class="lead session-desc">
                                 Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.
                             </p>,
 <p class="lead session-desc">
                                 Scraping real websites, you're likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.
                             </p>]

In [ ]:
body.find_all("a" , href = True) # finding Links

[<a href="/pages/simple/">Countries of the World: A Simple Example</a>,
 <a href="/pages/forms/">Hockey Teams: Forms, Searching and Pagination</a>,
 <a href="/pages/ajax-javascript/">Oscar Winning Films: AJAX and Javascript</a>,
 <a href="/pages/frames/">Turtles All the Way Down: Frames &amp; iFrames</a>,
 <a href="/pages/advanced/">Advanced Topics: Real World Challenges You'll Encounter</a>]

In [ ]:
dis=body.find_all("div",class_="page") 
dis

[<div class="page">
 <h3 class="page-title">
 <a href="/pages/simple/">Countries of the World: A Simple Example</a>
 </h3>
 <p class="lead session-desc">
                                 A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                             </p>
 <hr/>
 </div>,
 <div class="page">
 <h3 class="page-title">
 <a href="/pages/forms/">Hockey Teams: Forms, Searching and Pagination</a>
 </h3>
 <p class="lead session-desc">
                                 Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                             </p>
 <hr/>
 </div>,
 <div class="page">
 <h3 class="page-title">
 <a href="/pages/ajax-javascript/">Oscar Winning Films: AJAX and Javascript</a>
 </h3>
 <p class="lead session-desc">
                                 Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it.
                             </p>
 <hr/>
 </div>,
 <div class="page">
 <h3 class="page-title">
 <a href="/pages/frames/">Turtles All the Way Down: Frames &amp; iFrames</a>
 </h3>
 <p class="lead session-desc">
                                 Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.
                             </p>
 <hr/>
 </div>,
 <div class="page">
 <h3 class="page-title">
 <a href="/pages/advanced/">Advanced Topics: Real World Challenges You'll Encounter</a>
 </h3>
 <p class="lead session-desc">
                                 Scraping real websites, you're likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.
                             </p>
 <hr/>
 </div>]

In [ ]:
dis[0] # indexing

<div class="page">
<h3 class="page-title">
<a href="/pages/simple/">Countries of the World: A Simple Example</a>
</h3>
<p class="lead session-desc">
                                A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            </p>
<hr/>
</div>

In [ ]:
data = []
for div in dis:  # for loop
    ul = {
        "header" : "" ,
        "para" : "" ,
        "link" : "" 
    }
    ul["header"] = div.find("h3").text.strip()
    ul["para"] = div.find ("p").text.strip()
    ul["link"] = div.find ("a")["href"]
    data.append(ul)
df = pd.DataFrame(data)
df

,header,para,link
0,Countries of the World: A Simple Example,A single page that lists information about all...,/pages/simple/
1,"Hockey Teams: Forms, Searching and Pagination",Browse through a database of NHL team stats si...,/pages/forms/
2,Oscar Winning Films: AJAX and Javascript,Click through a bunch of great films. Learn ho...,/pages/ajax-javascript/
3,Turtles All the Way Down: Frames & iFrames,Some older sites might still use frames to bre...,/pages/frames/
4,Advanced Topics: Real World Challenges You'll ...,"Scraping real websites, you're likely run into...",/pages/advanced/

In [ ]:
print(dis[0].find("h3").text.strip())
print(dis[0].find("p").text.strip())
dis[0].find("a")["href"]

Countries of the World: A Simple Example
A single page that lists information about all the countries in the world. Good for those just get started with web scraping.

'/pages/simple/'

## 3. https://www.scrapethissite.com/pages/forms/ (Team Name, Year, Wins, Losses, OT Losses, Win %, Goals For (GF), Goals Against (GA), + / -)

## 3.1 Extract Table of first page & save into csv file.

In [5]:

import requests
from bs4 import BeautifulSoup
r = requests.get("https://www.scrapethissite.com/pages/forms/")
r.status_code

200

In [6]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>

In [7]:
data = {
    "Team_name" : "",
    "Year" : "",
    "Wins" : "" ,
    "Losses" : "",
    "Win_%" : "" , 
    "Goal_for" : "",
    "Goal_Against" : "",
    "+/-" : ""
}

In [8]:
tr = soup.find("table" , class_ = "table")

In [9]:
td = tr.find_all("tr" , class_ = "team")

In [10]:
tr.find("td" , class_ = "name").text.strip() # Name

'Boston Bruins'

In [44]:
tr.find("td" , class_ = "year").text.strip()

'1990'

In [ ]:
dl = []
for i in td:
    data = {
    "Team_name" : "",
    "Year" : "",
    "Wins" : "" ,
    "Losses" : "",
    "Ot_losses" : "",
    "Win_%" : "" , 
    "Goal_for" : "",
    "Goal_Against" : "",
    "+/-" : ""
}   
    data["Team_name"] = i.find("td" , class_ = "name").text.strip()
    data["Year"] = i.find("td" , class_ = "year").text.strip()
    data["Wins"] = i.find("td" , class_ = "wins").text.strip()
    data["Losses"] = i.find("td" , class_ = "losses").text.strip()
    data["Ot_losses"] = i.find("td" , class_ = "ot-losses").text.strip()
    try: 
          data["win%"] = i.find("td" , class_ = "pct text-danger").text.strip()
    except:
          data["win%"] = i.find("td" , class_ = "pct text-success").text.strip()
    data["Goal_for"] = i.find("td" , class_ = "gf").text.strip()
    data["Goal_Against"] = i.find("td" , class_ = "ga").text.strip()
    
    data["+/-"] = i.find("td" , class_ = "diff").text.strip()
    dl.append(data)
dl

[{'Team_name': 'Boston Bruins',
  'Year': '1990',
  'Wins': '44',
  'Losses': '24',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '299',
  'Goal_Against': '264',
  '+/-': '35',
  'win%': '0.55'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1990',
  'Wins': '31',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '292',
  'Goal_Against': '278',
  '+/-': '14',
  'win%': '0.388'},
 {'Team_name': 'Calgary Flames',
  'Year': '1990',
  'Wins': '46',
  'Losses': '26',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '344',
  'Goal_Against': '263',
  '+/-': '81',
  'win%': '0.575'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1990',
  'Wins': '49',
  'Losses': '23',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '284',
  'Goal_Against': '211',
  '+/-': '73',
  'win%': '0.613'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1990',
  'Wins': '34',
  'Losses': '38',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '273',
  'Goal_Against': '298',
  '+/-': '-25',
  'win%': '0.425'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1990',
  'Wins': '37',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '272',
  'Goal_Against': '272',
  '+/-': '0',
  'win%': '0.463'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1990',
  'Wins': '31',
  'Losses': '38',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '238',
  'Goal_Against': '276',
  '+/-': '-38',
  'win%': '0.388'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1990',
  'Wins': '46',
  'Losses': '24',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '340',
  'Goal_Against': '254',
  '+/-': '86',
  'win%': '0.575'},
 {'Team_name': 'Minnesota North Stars',
  'Year': '1990',
  'Wins': '27',
  'Losses': '39',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '256',
  'Goal_Against': '266',
  '+/-': '-10',
  'win%': '0.338'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1990',
  'Wins': '39',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '273',
  'Goal_Against': '249',
  '+/-': '24',
  'win%': '0.487'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1990',
  'Wins': '32',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '272',
  'Goal_Against': '264',
  '+/-': '8',
  'win%': '0.4'},
 {'Team_name': 'New York Islanders',
  'Year': '1990',
  'Wins': '25',
  'Losses': '45',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '223',
  'Goal_Against': '290',
  '+/-': '-67',
  'win%': '0.312'},
 {'Team_name': 'New York Rangers',
  'Year': '1990',
  'Wins': '36',
  'Losses': '31',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '297',
  'Goal_Against': '265',
  '+/-': '32',
  'win%': '0.45'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1990',
  'Wins': '33',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '252',
  'Goal_Against': '267',
  '+/-': '-15',
  'win%': '0.412'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1990',
  'Wins': '41',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '342',
  'Goal_Against': '305',
  '+/-': '37',
  'win%': '0.512'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1990',
  'Wins': '16',
  'Losses': '50',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '236',
  'Goal_Against': '354',
  '+/-': '-118',
  'win%': '0.2'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1990',
  'Wins': '47',
  'Losses': '22',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '310',
  'Goal_Against': '250',
  '+/-': '60',
  'win%': '0.588'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1990',
  'Wins': '23',
  'Losses': '46',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '241',
  'Goal_Against': '318',
  '+/-': '-77',
  'win%': '0.287'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1990',
  'Wins': '28',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '243',
  'Goal_Against': '315',
  '+/-': '-72',
  'win%': '0.35'},
 {'Team_name': 'Washington Capitals',
  'Year': '1990',
  'Wins': '37',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '258',
  'Goal_Against': '258',
  '+/-': '0',
  'win%': '0.463'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1990',
  'Wins': '26',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '260',
  'Goal_Against': '288',
  '+/-': '-28',
  'win%': '0.325'},
 {'Team_name': 'Boston Bruins',
  'Year': '1991',
  'Wins': '36',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '270',
  'Goal_Against': '275',
  '+/-': '-5',
  'win%': '0.45'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1991',
  'Wins': '31',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '289',
  'Goal_Against': '299',
  '+/-': '-10',
  'win%': '0.388'},
 {'Team_name': 'Calgary Flames',
  'Year': '1991',
  'Wins': '31',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '296',
  'Goal_Against': '305',
  '+/-': '-9',
  'win%': '0.388'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '257',
  'Goal_Against': '236',
  '+/-': '21',
  'win%': '0.45'}]

In [15]:
import pandas as pd
df = pd.DataFrame(dl)
df

,Team_name,Year,Wins,Losses,Ot_losses,Win_%,Goal_for,Goal_Against,+/-,win%
0,Buffalo Sabres,1990,31,30,,,292,278,14,0.388
1,Calgary Flames,1990,46,26,,,344,263,81,0.575
2,Chicago Blackhawks,1990,49,23,,,284,211,73,0.613
3,Detroit Red Wings,1990,34,38,,,273,298,-25,0.425
4,Edmonton Oilers,1990,37,37,,,272,272,0,0.463
5,Hartford Whalers,1990,31,38,,,238,276,-38,0.388
6,Los Angeles Kings,1990,46,24,,,340,254,86,0.575
7,Minnesota North Stars,1990,27,39,,,256,266,-10,0.338
8,Montreal Canadiens,1990,39,30,,,273,249,24,0.487
9,New Jersey Devils,1990,32,33,,,272,264,8,0.4
10,New York Islanders,1990,25,45,,,223,290,-67,0.312
11,New York Rangers,1990,36,31,,,297,265,32,0.45
12,Philadelphia Flyers,1990,33,37,,,252,267,-15,0.412
13,Pittsburgh Penguins,1990,41,33,,,342,305,37,0.512
14,Quebec Nordiques,1990,16,50,,,236,354,-118,0.2
15,St. Louis Blues,1990,47,22,,,310,250,60,0.588
16,Toronto Maple Leafs,1990,23,46,,,241,318,-77,0.287
17,Vancouver Canucks,1990,28,43,,,243,315,-72,0.35
18,Washington Capitals,1990,37,36,,,258,258,0,0.463
19,Winnipeg Jets,1990,26,43,,,260,288,-28,0.325
20,Boston Bruins,1991,36,32,,,270,275,-5,0.45
21,Buffalo Sabres,1991,31,37,,,289,299,-10,0.388
22,Calgary Flames,1991,31,37,,,296,305,-9,0.388
23,Chicago Blackhawks,1991,36,29,,,257,236,21,0.45

In [7]:
df.to_csv("Scrapthissite_q3.1.csv" , index = False)

## 3.2 Extract Table of second page & save into another csv file.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r = requests.get("https://www.scrapethissite.com/pages/forms/?page_num=2")
r.status_code

200

In [2]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>25 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            43
                        </td>
<td class="losses">
                            25
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.537
                        </td>
<td class="gf">
                            320
                        </td>
<td class="ga">
                            256
                        </td>
<td class="diff text-success">
                            64
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            34
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            295
                        </td>
<td class="ga">
                            297
                        </td>
<td class="diff text-danger">
                            -2
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            26
                        </td>
<td class="losses">
                            41
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.325
                        </td>
<td class="gf">
                            247
                        </td>
<td class="ga">
                            283
                        </td>
<td class="diff text-danger">
                            -36
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            35
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.438
                        </td>
<td class="gf">
                            287
                        </td>
<td class="ga">
                            296
                        </td>
<td class="diff text-danger">
                            -9
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            42
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            246
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-danger">
                            -32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            28
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            267
                        </td>
<td class="ga">
                            207
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            38
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.475
                        </td>
<td class="gf">
                            289
                        </td>
<td class="ga">
                            259
                        </td>
<td class="diff text-success">
                            30
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            35
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            291
                        </td>
<td class="ga">
                            299
                        </td>
<td class="diff text-danger">
                            -8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            50
                        </td>
<td class="losses">
                            25
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.625
                        </td>
<td class="gf">
                            321
                        </td>
<td class="ga">
                            246
                        </td>
<td class="diff text-success">
                            75
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            273
                        </td>
<td class="diff text-danger">
                            -21
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            32
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            343
                        </td>
<td class="ga">
                            308
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            20
                        </td>
<td class="losses">
                            48
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.25
                        </td>
<td class="gf">
                            255
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -63
                        </td>
</tr>
<tr class="team">
<td class="name">
                            San Jose Sharks
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            17
                        </td>
<td class="losses">
                            58
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.212
                        </td>
<td class="gf">
                            219
                        </td>
<td class="ga">
                            359
                        </td>
<td class="diff text-danger">
                            -140
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            279
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-success">
                            13
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            30
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.375
                        </td>
<td class="gf">
                            234
                        </td>
<td class="ga">
                            294
                        </td>
<td class="diff text-danger">
                            -60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            42
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.525
                        </td>
<td class="gf">
                            285
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            45
                        </td>
<td class="losses">
                            27
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.562
                        </td>
<td class="gf">
                            330
                        </td>
<td class="ga">
                            275
                        </td>
<td class="diff text-success">
                            55
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            32
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            251
                        </td>
<td class="ga">
                            244
                        </td>
<td class="diff text-success">
                            7
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1992
                        </td>
<td class="wins">
                            51
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.607
                        </td>
<td class="gf">
                            332
                        </td>
<td class="ga">
                            268
                        </td>
<td class="diff text-success">
                            64
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1992
                        </td>
<td class="wins">
                            38
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.452
                        </td>
<td class="gf">
                            335
                        </td>
<td class="ga">
                            297
                        </td>
<td class="diff text-success">
                            38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1992
                        </td>
<td class="wins">

In [4]:
tr = soup.find_all("tr" , class_ = "team")
tr

[<tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             43
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.537
                         </td>
 <td class="gf">
                             320
                         </td>
 <td class="ga">
                             256
                         </td>
 <td class="diff text-success">
                             64
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             34
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             295
                         </td>
 <td class="ga">
                             297
                         </td>
 <td class="diff text-danger">
                             -2
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             41
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.325
                         </td>
 <td class="gf">
                             247
                         </td>
 <td class="ga">
                             283
                         </td>
 <td class="diff text-danger">
                             -36
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             35
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.438
                         </td>
 <td class="gf">
                             287
                         </td>
 <td class="ga">
                             296
                         </td>
 <td class="diff text-danger">
                             -9
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             42
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             246
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-danger">
                             -32
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             28
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             267
                         </td>
 <td class="ga">
                             207
                         </td>
 <td class="diff text-success">
                             60
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             38
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.475
                         </td>
 <td class="gf">
                             289
                         </td>
 <td class="ga">
                             259
                         </td>
 <td class="diff text-success">
                             30
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             35
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.425
                         </td>
 <td class="gf">
                             291
                         </td>
 <td class="ga">
                             299
                         </td>
 <td class="diff text-danger">
                             -8
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             50
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.625
                         </td>
 <td class="gf">
                             321
                         </td>
 <td class="ga">
                             246
                         </td>
 <td class="diff text-success">
                             75
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             273
                         </td>
 <td class="diff text-danger">
                             -21
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.487
                         </td>
 <td class="gf">
                             343
                         </td>
 <td class="ga">
                             308
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             20
                         </td>
 <td class="losses">
                             48
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.25
                         </td>
 <td class="gf">
                             255
                         </td>
 <td class="ga">
                             318
                         </td>
 <td class="diff text-danger">
                             -63
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             San Jose Sharks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             17
                         </td>
 <td class="losses">
                             58
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.212
                         </td>
 <td class="gf">
                             219
                         </td>
 <td class="ga">
                             359
                         </td>
 <td class="diff text-danger">
                             -140
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             279
                         </td>
 <td class="ga">
                             266
                         </td>
 <td class="diff text-success">
                             13
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             30
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.375
                         </td>
 <td class="gf">
                             234
                         </td>
 <td class="ga">
                             294
                         </td>
 <td class="diff text-danger">
                             -60
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             42
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.525
                         </td>
 <td class="gf">
                             285
                         </td>
 <td class="ga">
                             250
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             45
                         </td>
 <td class="losses">
                             27
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.562
                         </td>
 <td class="gf">
                             330
                         </td>
 <td class="ga">
                             275
                         </td>
 <td class="diff text-success">
                             55
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.412
                         </td>
 <td class="gf">
                             251
                         </td>
 <td class="ga">
                             244
                         </td>
 <td class="diff text-success">
                             7
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             51
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.607
                         </td>
 <td class="gf">
                             332
                         </td>
 <td class="ga">
                             268
                         </td>
 <td class="diff text-success">
                             64
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             38
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.452
                         </td>
 <td class="gf">
                             335
                         </td>
 <td class="ga">
                             297
                         </td>
 <td class="diff text-success">
                             38
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             43
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             322
                         </td>
 <td class="ga">
                             282
                         </td>
 <td class="diff text-success">
                             40
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.56
                         </td>
 <td class="gf">
                             279
                         </td>
 <td class="ga">
                             230
                         </td>
 <td class="diff text-success">
                             49
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             28
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.56
                         </td>
 <td class="gf">
                             369
                         </td>
 <td class="ga">
                             280
                         </td>
 <td class="diff text-success">
                             89
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             50
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.31
                         </td>
 <td class="gf">
                             242
                         </td>
 <td class="ga">
                             337
                         </td>
 <td class="diff text-danger">
                             -95
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             52
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.31
                         </td>
 <td class="gf">
                             284
                         </td>
 <td class="ga">
                             369
                         </td>
 <td class="diff text-danger">
                             -85
                         </td>
 </tr>]

In [5]:
dl = []
for i in tr:
    data = {
    "Team_name" : "",
    "Year" : "",
    "Wins" : "" ,
    "Losses" : "",
    "Ot_losses" : "",
    "Win_%" : "" , 
    "Goal_for" : "",
    "Goal_Against" : "",
    "+/-" : ""
}   
    data["Team_name"] = i.find("td" , class_ = "name").text.strip()
    data["Year"] = i.find("td" , class_ = "year").text.strip()
    data["Wins"] = i.find("td" , class_ = "wins").text.strip()
    data["Losses"] = i.find("td" , class_ = "losses").text.strip()
    data["Ot_losses"] = i.find("td" , class_ = "ot-losses").text.strip()
    try: 
         data["win%"] = i.find("td" , class_ = "pct text-danger").text.strip()
    except:
          data["win%"] = i.find("td" , class_ = "pct text-success").text.strip()
    data["Goal_for"] = i.find("td" , class_ = "gf").text.strip()
    data["Goal_Against"] = i.find("td" , class_ = "ga").text.strip()
    
    data["+/-"] = i.find("td" , class_ = "diff").text.strip()
    dl.append(data)
dl

[{'Team_name': 'Detroit Red Wings',
  'Year': '1991',
  'Wins': '43',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '320',
  'Goal_Against': '256',
  '+/-': '64',
  'win%': '0.537'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1991',
  'Wins': '36',
  'Losses': '34',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '295',
  'Goal_Against': '297',
  '+/-': '-2',
  'win%': '0.45'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1991',
  'Wins': '26',
  'Losses': '41',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '247',
  'Goal_Against': '283',
  '+/-': '-36',
  'win%': '0.325'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1991',
  'Wins': '35',
  'Losses': '31',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '287',
  'Goal_Against': '296',
  '+/-': '-9',
  'win%': '0.438'},
 {'Team_name': 'Minnesota North Stars',
  'Year': '1991',
  'Wins': '32',
  'Losses': '42',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '246',
  'Goal_Against': '278',
  '+/-': '-32',
  'win%': '0.4'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1991',
  'Wins': '41',
  'Losses': '28',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '267',
  'Goal_Against': '207',
  '+/-': '60',
  'win%': '0.512'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1991',
  'Wins': '38',
  'Losses': '31',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '289',
  'Goal_Against': '259',
  '+/-': '30',
  'win%': '0.475'},
 {'Team_name': 'New York Islanders',
  'Year': '1991',
  'Wins': '34',
  'Losses': '35',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '291',
  'Goal_Against': '299',
  '+/-': '-8',
  'win%': '0.425'},
 {'Team_name': 'New York Rangers',
  'Year': '1991',
  'Wins': '50',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '321',
  'Goal_Against': '246',
  '+/-': '75',
  'win%': '0.625'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1991',
  'Wins': '32',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '252',
  'Goal_Against': '273',
  '+/-': '-21',
  'win%': '0.4'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1991',
  'Wins': '39',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '343',
  'Goal_Against': '308',
  '+/-': '35',
  'win%': '0.487'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1991',
  'Wins': '20',
  'Losses': '48',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '255',
  'Goal_Against': '318',
  '+/-': '-63',
  'win%': '0.25'},
 {'Team_name': 'San Jose Sharks',
  'Year': '1991',
  'Wins': '17',
  'Losses': '58',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '219',
  'Goal_Against': '359',
  '+/-': '-140',
  'win%': '0.212'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1991',
  'Wins': '36',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '279',
  'Goal_Against': '266',
  '+/-': '13',
  'win%': '0.45'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1991',
  'Wins': '30',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '234',
  'Goal_Against': '294',
  '+/-': '-60',
  'win%': '0.375'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1991',
  'Wins': '42',
  'Losses': '26',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '285',
  'Goal_Against': '250',
  '+/-': '35',
  'win%': '0.525'},
 {'Team_name': 'Washington Capitals',
  'Year': '1991',
  'Wins': '45',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '330',
  'Goal_Against': '275',
  '+/-': '55',
  'win%': '0.562'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1991',
  'Wins': '33',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '251',
  'Goal_Against': '244',
  '+/-': '7',
  'win%': '0.412'},
 {'Team_name': 'Boston Bruins',
  'Year': '1992',
  'Wins': '51',
  'Losses': '26',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '332',
  'Goal_Against': '268',
  '+/-': '64',
  'win%': '0.607'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1992',
  'Wins': '38',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '335',
  'Goal_Against': '297',
  '+/-': '38',
  'win%': '0.452'},
 {'Team_name': 'Calgary Flames',
  'Year': '1992',
  'Wins': '43',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '322',
  'Goal_Against': '282',
  '+/-': '40',
  'win%': '0.512'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1992',
  'Wins': '47',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '279',
  'Goal_Against': '230',
  '+/-': '49',
  'win%': '0.56'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1992',
  'Wins': '47',
  'Losses': '28',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '369',
  'Goal_Against': '280',
  '+/-': '89',
  'win%': '0.56'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1992',
  'Wins': '26',
  'Losses': '50',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '242',
  'Goal_Against': '337',
  '+/-': '-95',
  'win%': '0.31'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1992',
  'Wins': '26',
  'Losses': '52',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '284',
  'Goal_Against': '369',
  '+/-': '-85',
  'win%': '0.31'}]

In [8]:
df = pd.DataFrame(dl)
df.to_csv("scrapthissite_q3.2.csv")

##  3.3 Extract Table of fist five pages & save into single csv file.

In [5]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
b_url = "https://www.scrapethissite.com/pages/forms/?page_num="

In [6]:
dl = []
for page in range(1,6):
    url = b_url + str(page)
    r = requests.get(url)
    soup = BeautifulSoup(r.text , "html.parser")
    tr = soup.find_all("tr" , class_ = "team")

    for i in tr:
        data = {
                "Team_name" : "",
                "Year" : "",
                "Wins" : "" ,
                "Losses" : "",
                "Ot_losses" : "",
                "Win_%" : "" , 
                "Goal_for" : "",
                "Goal_Against" : "",
                "+/-" : ""
            }   

        data["Team_name"] = i.find("td" , class_ = "name").text.strip()
        data["Year"] = i.find("td" , class_ = "year").text.strip()
        data["Wins"] = i.find("td" , class_ = "wins").text.strip()
        data["Losses"] = i.find("td" , class_ = "losses").text.strip()
        data["Ot_losses"] = i.find("td" , class_ = "ot-losses").text.strip()
        data["Win_%"] = i.find("td" , class_ = "pct").text.strip()
        data["Goal_for"] = i.find("td" , class_ = "gf").text.strip()
        data["Goal_Against"] = i.find("td" , class_ = "ga").text.strip()
    
        data["+/-"] = i.find("td" , class_ = "diff").text.strip()
        dl.append(data)
dl

[{'Team_name': 'Boston Bruins',
  'Year': '1990',
  'Wins': '44',
  'Losses': '24',
  'Ot_losses': '',
  'Win_%': '0.55',
  'Goal_for': '299',
  'Goal_Against': '264',
  '+/-': '35'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1990',
  'Wins': '31',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '0.388',
  'Goal_for': '292',
  'Goal_Against': '278',
  '+/-': '14'},
 {'Team_name': 'Calgary Flames',
  'Year': '1990',
  'Wins': '46',
  'Losses': '26',
  'Ot_losses': '',
  'Win_%': '0.575',
  'Goal_for': '344',
  'Goal_Against': '263',
  '+/-': '81'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1990',
  'Wins': '49',
  'Losses': '23',
  'Ot_losses': '',
  'Win_%': '0.613',
  'Goal_for': '284',
  'Goal_Against': '211',
  '+/-': '73'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1990',
  'Wins': '34',
  'Losses': '38',
  'Ot_losses': '',
  'Win_%': '0.425',
  'Goal_for': '273',
  'Goal_Against': '298',
  '+/-': '-25'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1990',
  'Wins': '37',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '0.463',
  'Goal_for': '272',
  'Goal_Against': '272',
  '+/-': '0'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1990',
  'Wins': '31',
  'Losses': '38',
  'Ot_losses': '',
  'Win_%': '0.388',
  'Goal_for': '238',
  'Goal_Against': '276',
  '+/-': '-38'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1990',
  'Wins': '46',
  'Losses': '24',
  'Ot_losses': '',
  'Win_%': '0.575',
  'Goal_for': '340',
  'Goal_Against': '254',
  '+/-': '86'},
 {'Team_name': 'Minnesota North Stars',
  'Year': '1990',
  'Wins': '27',
  'Losses': '39',
  'Ot_losses': '',
  'Win_%': '0.338',
  'Goal_for': '256',
  'Goal_Against': '266',
  '+/-': '-10'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1990',
  'Wins': '39',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '0.487',
  'Goal_for': '273',
  'Goal_Against': '249',
  '+/-': '24'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1990',
  'Wins': '32',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '0.4',
  'Goal_for': '272',
  'Goal_Against': '264',
  '+/-': '8'},
 {'Team_name': 'New York Islanders',
  'Year': '1990',
  'Wins': '25',
  'Losses': '45',
  'Ot_losses': '',
  'Win_%': '0.312',
  'Goal_for': '223',
  'Goal_Against': '290',
  '+/-': '-67'},
 {'Team_name': 'New York Rangers',
  'Year': '1990',
  'Wins': '36',
  'Losses': '31',
  'Ot_losses': '',
  'Win_%': '0.45',
  'Goal_for': '297',
  'Goal_Against': '265',
  '+/-': '32'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1990',
  'Wins': '33',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '0.412',
  'Goal_for': '252',
  'Goal_Against': '267',
  '+/-': '-15'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1990',
  'Wins': '41',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '0.512',
  'Goal_for': '342',
  'Goal_Against': '305',
  '+/-': '37'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1990',
  'Wins': '16',
  'Losses': '50',
  'Ot_losses': '',
  'Win_%': '0.2',
  'Goal_for': '236',
  'Goal_Against': '354',
  '+/-': '-118'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1990',
  'Wins': '47',
  'Losses': '22',
  'Ot_losses': '',
  'Win_%': '0.588',
  'Goal_for': '310',
  'Goal_Against': '250',
  '+/-': '60'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1990',
  'Wins': '23',
  'Losses': '46',
  'Ot_losses': '',
  'Win_%': '0.287',
  'Goal_for': '241',
  'Goal_Against': '318',
  '+/-': '-77'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1990',
  'Wins': '28',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '0.35',
  'Goal_for': '243',
  'Goal_Against': '315',
  '+/-': '-72'},
 {'Team_name': 'Washington Capitals',
  'Year': '1990',
  'Wins': '37',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '0.463',
  'Goal_for': '258',
  'Goal_Against': '258',
  '+/-': '0'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1990',
  'Wins': '26',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '0.325',
  'Goal_for': '260',
  'Goal_Against': '288',
  '+/-': '-28'},
 {'Team_name': 'Boston Bruins',
  'Year': '1991',
  'Wins': '36',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '0.45',
  'Goal_for': '270',
  'Goal_Against': '275',
  '+/-': '-5'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1991',
  'Wins': '31',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '0.388',
  'Goal_for': '289',
  'Goal_Against': '299',
  '+/-': '-10'},
 {'Team_name': 'Calgary Flames',
  'Year': '1991',
  'Wins': '31',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '0.388',
  'Goal_for': '296',
  'Goal_Against': '305',
  '+/-': '-9'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '0.45',
  'Goal_for': '257',
  'Goal_Against': '236',
  '+/-': '21'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1991',
  'Wins': '43',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '0.537',
  'Goal_for': '320',
  'Goal_Against': '256',
  '+/-': '64'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1991',
  'Wins': '36',
  'Losses': '34',
  'Ot_losses': '',
  'Win_%': '0.45',
  'Goal_for': '295',
  'Goal_Against': '297',
  '+/-': '-2'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1991',
  'Wins': '26',
  'Losses': '41',
  'Ot_losses': '',
  'Win_%': '0.325',
  'Goal_for': '247',
  'Goal_Against': '283',
  '+/-': '-36'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1991',
  'Wins': '35',
  'Losses': '31',
  'Ot_losses': '',
  'Win_%': '0.438',
  'Goal_for': '287',
  'Goal_Against': '296',
  '+/-': '-9'},
 {'Team_name': 'Minnesota North Stars',
  'Year': '1991',
  'Wins': '32',
  'Losses': '42',
  'Ot_losses': '',
  'Win_%': '0.4',
  'Goal_for': '246',
  'Goal_Against': '278',
  '+/-': '-32'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1991',
  'Wins': '41',
  'Losses': '28',
  'Ot_losses': '',
  'Win_%': '0.512',
  'Goal_for': '267',
  'Goal_Against': '207',
  '+/-': '60'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1991',
  'Wins': '38',
  'Losses': '31',
  'Ot_losses': '',
  'Win_%': '0.475',
  'Goal_for': '289',
  'Goal_Against': '259',
  '+/-': '30'},
 {'Team_name': 'New York Islanders',
  'Year': '1991',
  'Wins': '34',
  'Losses': '35',
  'Ot_losses': '',
  'Win_%': '0.425',
  'Goal_for': '291',
  'Goal_Against': '299',
  '+/-': '-8'},
 {'Team_name': 'New York Rangers',
  'Year': '1991',
  'Wins': '50',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '0.625',
  'Goal_for': '321',
  'Goal_Against': '246',
  '+/-': '75'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1991',
  'Wins': '32',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '0.4',
  'Goal_for': '252',
  'Goal_Against': '273',
  '+/-': '-21'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1991',
  'Wins': '39',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '0.487',
  'Goal_for': '343',
  'Goal_Against': '308',
  '+/-': '35'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1991',
  'Wins': '20',
  'Losses': '48',
  'Ot_losses': '',
  'Win_%': '0.25',
  'Goal_for': '255',
  'Goal_Against': '318',
  '+/-': '-63'},
 {'Team_name': 'San Jose Sharks',
  'Year': '1991',
  'Wins': '17',
  'Losses': '58',
  'Ot_losses': '',
  'Win_%': '0.212',
  'Goal_for': '219',
  'Goal_Against': '359',
  '+/-': '-140'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1991',
  'Wins': '36',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '0.45',
  'Goal_for': '279',
  'Goal_Against': '266',
  '+/-': '13'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1991',
  'Wins': '30',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '0.375',
  'Goal_for': '234',
  'Goal_Against': '294',
  '+/-': '-60'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1991',
  'Wins': '42',
  'Losses': '26',
  'Ot_losses': '',
  'Win_%': '0.525',
  'Goal_for': '285',
  'Goal_Against': '250',
  '+/-': '35'},
 {'Team_name': 'Washington Capitals',
  'Year': '1991',
  'Wins': '45',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '0.562',
  'Goal_for': '330',
  'Goal_Against': '275',
  '+/-': '55'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1991',
  'Wins': '33',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '0.412',
  'Goal_for': '251',
  'Goal_Against': '244',
  '+/-': '7'},
 {'Team_name': 'Boston Bruins',
  'Year': '1992',
  'Wins': '51',
  'Losses': '26',
  'Ot_losses': '',
  'Win_%': '0.607',
  'Goal_for': '332',
  'Goal_Against': '268',
  '+/-': '64'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1992',
  'Wins': '38',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '0.452',
  'Goal_for': '335',
  'Goal_Against': '297',
  '+/-': '38'},
 {'Team_name': 'Calgary Flames',
  'Year': '1992',
  'Wins': '43',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '0.512',
  'Goal_for': '322',
  'Goal_Against': '282',
  '+/-': '40'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1992',
  'Wins': '47',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '0.56',
  'Goal_for': '279',
  'Goal_Against': '230',
  '+/-': '49'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1992',
  'Wins': '47',
  'Losses': '28',
  'Ot_losses': '',
  'Win_%': '0.56',
  'Goal_for': '369',
  'Goal_Against': '280',
  '+/-': '89'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1992',
  'Wins': '26',
  'Losses': '50',
  'Ot_losses': '',
  'Win_%': '0.31',
  'Goal_for': '242',
  'Goal_Against': '337',
  '+/-': '-95'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1992',
  'Wins': '26',
  'Losses': '52',
  'Ot_losses': '',
  'Win_%': '0.31',
  'Goal_for': '284',
  'Goal_Against': '369',
  '+/-': '-85'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1992',
  'Wins': '39',
  'Losses': '35',
  'Ot_losses': '',
  'Win_%': '0.464',
  'Goal_for': '338',
  'Goal_Against': '340',
  '+/-': '-2'},
 {'Team_name': 'Minnesota North Stars',
  'Year': '1992',
  'Wins': '36',
  'Losses': '38',
  'Ot_losses': '',
  'Win_%': '0.429',
  'Goal_for': '272',
  'Goal_Against': '293',
  '+/-': '-21'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1992',
  'Wins': '48',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '0.571',
  'Goal_for': '326',
  'Goal_Against': '280',
  '+/-': '46'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1992',
  'Wins': '40',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '0.476',
  'Goal_for': '308',
  'Goal_Against': '299',
  '+/-': '9'},
 {'Team_name': 'New York Islanders',
  'Year': '1992',
  'Wins': '40',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '0.476',
  'Goal_for': '335',
  'Goal_Against': '297',
  '+/-': '38'},
 {'Team_name': 'New York Rangers',
  'Year': '1992',
  'Wins': '34',
  'Losses': '39',
  'Ot_losses': '',
  'Win_%': '0.405',
  'Goal_for': '304',
  'Goal_Against': '308',
  '+/-': '-4'},
 {'Team_name': 'Ottawa Senators',
  'Year': '1992',
  'Wins': '10',
  'Losses': '70',
  'Ot_losses': '',
  'Win_%': '0.119',
  'Goal_for': '202',
  'Goal_Against': '395',
  '+/-': '-193'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1992',
  'Wins': '36',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '0.429',
  'Goal_for': '319',
  'Goal_Against': '319',
  '+/-': '0'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1992',
  'Wins': '56',
  'Losses': '21',
  'Ot_losses': '',
  'Win_%': '0.667',
  'Goal_for': '367',
  'Goal_Against': '268',
  '+/-': '99'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1992',
  'Wins': '47',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '0.56',
  'Goal_for': '351',
  'Goal_Against': '300',
  '+/-': '51'},
 {'Team_name': 'San Jose Sharks',
  'Year': '1992',
  'Wins': '11',
  'Losses': '71',
  'Ot_losses': '',
  'Win_%': '0.131',
  'Goal_for': '218',
  'Goal_Against': '414',
  '+/-': '-196'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1992',
  'Wins': '37',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '0.44',
  'Goal_for': '282',
  'Goal_Against': '278',
  '+/-': '4'},
 {'Team_name': 'Tampa Bay Lightning',
  'Year': '1992',
  'Wins': '23',
  'Losses': '54',
  'Ot_losses': '',
  'Win_%': '0.274',
  'Goal_for': '245',
  'Goal_Against': '332',
  '+/-': '-87'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1992',
  'Wins': '44',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '0.524',
  'Goal_for': '288',
  'Goal_Against': '241',
  '+/-': '47'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1992',
  'Wins': '46',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '0.548',
  'Goal_for': '346',
  'Goal_Against': '278',
  '+/-': '68'},
 {'Team_name': 'Washington Capitals',
  'Year': '1992',
  'Wins': '43',
  'Losses': '34',
  'Ot_losses': '',
  'Win_%': '0.512',
  'Goal_for': '325',
  'Goal_Against': '286',
  '+/-': '39'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1992',
  'Wins': '40',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '0.476',
  'Goal_for': '322',
  'Goal_Against': '320',
  '+/-': '2'},
 {'Team_name': 'Mighty Ducks of Anaheim',
  'Year': '1993',
  'Wins': '33',
  'Losses': '46',
  'Ot_losses': '',
  'Win_%': '0.393',
  'Goal_for': '229',
  'Goal_Against': '251',
  '+/-': '-22'},
 {'Team_name': 'Boston Bruins',
  'Year': '1993',
  'Wins': '42',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '0.5',
  'Goal_for': '289',
  'Goal_Against': '252',
  '+/-': '37'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1993',
  'Wins': '43',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '0.512',
  'Goal_for': '282',
  'Goal_Against': '218',
  '+/-': '64'},
 {'Team_name': 'Calgary Flames',
  'Year': '1993',
  'Wins': '42',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '0.5',
  'Goal_for': '302',
  'Goal_Against': '256',
  '+/-': '46'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1993',
  'Wins': '39',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '0.464',
  'Goal_for': '254',
  'Goal_Against': '240',
  '+/-': '14'},
 {'Team_name': 'Dallas Stars',
  'Year': '1993',
  'Wins': '42',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '0.5',
  'Goal_for': '286',
  'Goal_Against': '265',
  '+/-': '21'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1993',
  'Wins': '46',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '0.548',
  'Goal_for': '356',
  'Goal_Against': '275',
  '+/-': '81'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1993',
  'Wins': '25',
  'Losses': '45',
  'Ot_losses': '',
  'Win_%': '0.298',
  'Goal_for': '261',
  'Goal_Against': '305',
  '+/-': '-44'},
 {'Team_name': 'Florida Panthers',
  'Year': '1993',
  'Wins': '33',
  'Losses': '34',
  'Ot_losses': '',
  'Win_%': '0.393',
  'Goal_for': '233',
  'Goal_Against': '233',
  '+/-': '0'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1993',
  'Wins': '27',
  'Losses': '48',
  'Ot_losses': '',
  'Win_%': '0.321',
  'Goal_for': '227',
  'Goal_Against': '288',
  '+/-': '-61'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1993',
  'Wins': '27',
  'Losses': '45',
  'Ot_losses': '',
  'Win_%': '0.321',
  'Goal_for': '294',
  'Goal_Against': '322',
  '+/-': '-28'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1993',
  'Wins': '41',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '0.488',
  'Goal_for': '283',
  'Goal_Against': '248',
  '+/-': '35'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1993',
  'Wins': '47',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '0.56',
  'Goal_for': '306',
  'Goal_Against': '220',
  '+/-': '86'},
 {'Team_name': 'New York Islanders',
  'Year': '1993',
  'Wins': '36',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '0.429',
  'Goal_for': '282',
  'Goal_Against': '264',
  '+/-': '18'},
 {'Team_name': 'New York Rangers',
  'Year': '1993',
  'Wins': '52',
  'Losses': '24',
  'Ot_losses': '',
  'Win_%': '0.619',
  'Goal_for': '299',
  'Goal_Against': '231',
  '+/-': '68'},
 {'Team_name': 'Ottawa Senators',
  'Year': '1993',
  'Wins': '14',
  'Losses': '61',
  'Ot_losses': '',
  'Win_%': '0.167',
  'Goal_for': '201',
  'Goal_Against': '397',
  '+/-': '-196'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1993',
  'Wins': '35',
  'Losses': '39',
  'Ot_losses': '',
  'Win_%': '0.417',
  'Goal_for': '294',
  'Goal_Against': '314',
  '+/-': '-20'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1993',
  'Wins': '44',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '0.524',
  'Goal_for': '299',
  'Goal_Against': '285',
  '+/-': '14'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1993',
  'Wins': '34',
  'Losses': '42',
  'Ot_losses': '',
  'Win_%': '0.405',
  'Goal_for': '277',
  'Goal_Against': '292',
  '+/-': '-15'},
 {'Team_name': 'San Jose Sharks',
  'Year': '1993',
  'Wins': '33',
  'Losses': '35',
  'Ot_losses': '',
  'Win_%': '0.393',
  'Goal_for': '252',
  'Goal_Against': '265',
  '+/-': '-13'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1993',
  'Wins': '40',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '0.476',
  'Goal_for': '270',
  'Goal_Against': '283',
  '+/-': '-13'},
 {'Team_name': 'Tampa Bay Lightning',
  'Year': '1993',
  'Wins': '30',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '0.357',
  'Goal_for': '224',
  'Goal_Against': '251',
  '+/-': '-27'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1993',
  'Wins': '43',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '0.512',
  'Goal_for': '280',
  'Goal_Against': '243',
  '+/-': '37'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1993',
  'Wins': '41',
  'Losses': '40',
  'Ot_losses': '',
  'Win_%': '0.488',
  'Goal_for': '279',
  'Goal_Against': '276',
  '+/-': '3'},
 {'Team_name': 'Washington Capitals',
  'Year': '1993',
  'Wins': '39',
  'Losses': '35',
  'Ot_losses': '',
  'Win_%': '0.464',
  'Goal_for': '277',
  'Goal_Against': '263',
  '+/-': '14'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1993',
  'Wins': '24',
  'Losses': '51',
  'Ot_losses': '',
  'Win_%': '0.286',
  'Goal_for': '245',
  'Goal_Against': '344',
  '+/-': '-99'},
 {'Team_name': 'Mighty Ducks of Anaheim',
  'Year': '1994',
  'Wins': '16',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '0.333',
  'Goal_for': '125',
  'Goal_Against': '164',
  '+/-': '-39'},
 {'Team_name': 'Boston Bruins',
  'Year': '1994',
  'Wins': '27',
  'Losses': '18',
  'Ot_losses': '',
  'Win_%': '0.562',
  'Goal_for': '150',
  'Goal_Against': '127',
  '+/-': '23'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1994',
  'Wins': '22',
  'Losses': '19',
  'Ot_losses': '',
  'Win_%': '0.458',
  'Goal_for': '130',
  'Goal_Against': '119',
  '+/-': '11'},
 {'Team_name': 'Calgary Flames',
  'Year': '1994',
  'Wins': '24',
  'Losses': '17',
  'Ot_losses': '',
  'Win_%': '0.5',
  'Goal_for': '163',
  'Goal_Against': '135',
  '+/-': '28'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1994',
  'Wins': '24',
  'Losses': '19',
  'Ot_losses': '',
  'Win_%': '0.5',
  'Goal_for': '156',
  'Goal_Against': '115',
  '+/-': '41'},
 {'Team_name': 'Dallas Stars',
  'Year': '1994',
  'Wins': '17',
  'Losses': '23',
  'Ot_losses': '',
  'Win_%': '0.354',
  'Goal_for': '136',
  'Goal_Against': '135',
  '+/-': '1'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1994',
  'Wins': '33',
  'Losses': '11',
  'Ot_losses': '',
  'Win_%': '0.688',
  'Goal_for': '180',
  'Goal_Against': '117',
  '+/-': '63'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1994',
  'Wins': '17',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '0.354',
  'Goal_for': '136',
  'Goal_Against': '183',
  '+/-': '-47'},
 {'Team_name': 'Florida Panthers',
  'Year': '1994',
  'Wins': '20',
  'Losses': '22',
  'Ot_losses': '',
  'Win_%': '0.417',
  'Goal_for': '115',
  'Goal_Against': '127',
  '+/-': '-12'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1994',
  'Wins': '19',
  'Losses': '24',
  'Ot_losses': '',
  'Win_%': '0.396',
  'Goal_for': '127',
  'Goal_Against': '141',
  '+/-': '-14'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1994',
  'Wins': '16',
  'Losses': '23',
  'Ot_losses': '',
  'Win_%': '0.333',
  'Goal_for': '142',
  'Goal_Against': '174',
  '+/-': '-32'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1994',
  'Wins': '18',
  'Losses': '23',
  'Ot_losses': '',
  'Win_%': '0.375',
  'Goal_for': '125',
  'Goal_Against': '148',
  '+/-': '-23'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1994',
  'Wins': '22',
  'Losses': '18',
  'Ot_losses': '',
  'Win_%': '0.458',
  'Goal_for': '136',
  'Goal_Against': '121',
  '+/-': '15'},

In [27]:
import pandas as pd
df = pd.DataFrame(dl)
df.to_csv("scrapthissite_q3.3.csv" , index = False)

## 3.4 Extract Table of first page of 100 records/rows & save into another csv file.

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r = requests.get("https://www.scrapethissite.com/pages/forms/?per_page=100")
r.status_code

200

In [11]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="hockey">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>100 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">http://www.opensourcesports.com/hockey/</a>
</p>
<hr/>
</div>
</div>
<div class="row search-area">
<div class="col-md-12 text-center">
<form action="/pages/forms/" class="form form-inline" method="GET">
<label for="q">
                                Search for Teams:
                            </label>
<input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
<input name="per_page" type="hidden" value="100"/>
<input class="btn btn-primary" type="submit" value="Search"/>
</form>
<hr/>
</div>
</div><!--.row.search-area-->
<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">

In [12]:
tr = soup.find_all("tr" , class_ = "team")

In [13]:
dl = []
for i in tr:
    data = {
    "Team_name" : "",
    "Year" : "",
    "Wins" : "" ,
    "Losses" : "",
    "Ot_losses" : "",
    "Win_%" : "" , 
    "Goal_for" : "",
    "Goal_Against" : "",
    "+/-" : ""
}   
    data["Team_name"] = i.find("td" , class_ = "name").text.strip()
    data["Year"] = i.find("td" , class_ = "year").text.strip()
    data["Wins"] = i.find("td" , class_ = "wins").text.strip()
    data["Losses"] = i.find("td" , class_ = "losses").text.strip()
    data["Ot_losses"] = i.find("td" , class_ = "ot-losses").text.strip()
    try: 
         data["win%"] = i.find("td" , class_ = "pct text-danger").text.strip()
    except:
          data["win%"] = i.find("td" , class_ = "pct text-success").text.strip()
    data["Goal_for"] = i.find("td" , class_ = "gf").text.strip()
    data["Goal_Against"] = i.find("td" , class_ = "ga").text.strip()
    
    data["+/-"] = i.find("td" , class_ = "diff").text.strip()
    dl.append(data)
dl

[{'Team_name': 'Boston Bruins',
  'Year': '1990',
  'Wins': '44',
  'Losses': '24',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '299',
  'Goal_Against': '264',
  '+/-': '35',
  'win%': '0.55'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1990',
  'Wins': '31',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '292',
  'Goal_Against': '278',
  '+/-': '14',
  'win%': '0.388'},
 {'Team_name': 'Calgary Flames',
  'Year': '1990',
  'Wins': '46',
  'Losses': '26',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '344',
  'Goal_Against': '263',
  '+/-': '81',
  'win%': '0.575'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1990',
  'Wins': '49',
  'Losses': '23',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '284',
  'Goal_Against': '211',
  '+/-': '73',
  'win%': '0.613'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1990',
  'Wins': '34',
  'Losses': '38',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '273',
  'Goal_Against': '298',
  '+/-': '-25',
  'win%': '0.425'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1990',
  'Wins': '37',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '272',
  'Goal_Against': '272',
  '+/-': '0',
  'win%': '0.463'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1990',
  'Wins': '31',
  'Losses': '38',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '238',
  'Goal_Against': '276',
  '+/-': '-38',
  'win%': '0.388'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1990',
  'Wins': '46',
  'Losses': '24',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '340',
  'Goal_Against': '254',
  '+/-': '86',
  'win%': '0.575'},
 {'Team_name': 'Minnesota North Stars',
  'Year': '1990',
  'Wins': '27',
  'Losses': '39',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '256',
  'Goal_Against': '266',
  '+/-': '-10',
  'win%': '0.338'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1990',
  'Wins': '39',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '273',
  'Goal_Against': '249',
  '+/-': '24',
  'win%': '0.487'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1990',
  'Wins': '32',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '272',
  'Goal_Against': '264',
  '+/-': '8',
  'win%': '0.4'},
 {'Team_name': 'New York Islanders',
  'Year': '1990',
  'Wins': '25',
  'Losses': '45',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '223',
  'Goal_Against': '290',
  '+/-': '-67',
  'win%': '0.312'},
 {'Team_name': 'New York Rangers',
  'Year': '1990',
  'Wins': '36',
  'Losses': '31',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '297',
  'Goal_Against': '265',
  '+/-': '32',
  'win%': '0.45'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1990',
  'Wins': '33',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '252',
  'Goal_Against': '267',
  '+/-': '-15',
  'win%': '0.412'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1990',
  'Wins': '41',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '342',
  'Goal_Against': '305',
  '+/-': '37',
  'win%': '0.512'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1990',
  'Wins': '16',
  'Losses': '50',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '236',
  'Goal_Against': '354',
  '+/-': '-118',
  'win%': '0.2'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1990',
  'Wins': '47',
  'Losses': '22',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '310',
  'Goal_Against': '250',
  '+/-': '60',
  'win%': '0.588'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1990',
  'Wins': '23',
  'Losses': '46',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '241',
  'Goal_Against': '318',
  '+/-': '-77',
  'win%': '0.287'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1990',
  'Wins': '28',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '243',
  'Goal_Against': '315',
  '+/-': '-72',
  'win%': '0.35'},
 {'Team_name': 'Washington Capitals',
  'Year': '1990',
  'Wins': '37',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '258',
  'Goal_Against': '258',
  '+/-': '0',
  'win%': '0.463'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1990',
  'Wins': '26',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '260',
  'Goal_Against': '288',
  '+/-': '-28',
  'win%': '0.325'},
 {'Team_name': 'Boston Bruins',
  'Year': '1991',
  'Wins': '36',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '270',
  'Goal_Against': '275',
  '+/-': '-5',
  'win%': '0.45'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1991',
  'Wins': '31',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '289',
  'Goal_Against': '299',
  '+/-': '-10',
  'win%': '0.388'},
 {'Team_name': 'Calgary Flames',
  'Year': '1991',
  'Wins': '31',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '296',
  'Goal_Against': '305',
  '+/-': '-9',
  'win%': '0.388'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '257',
  'Goal_Against': '236',
  '+/-': '21',
  'win%': '0.45'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1991',
  'Wins': '43',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '320',
  'Goal_Against': '256',
  '+/-': '64',
  'win%': '0.537'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1991',
  'Wins': '36',
  'Losses': '34',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '295',
  'Goal_Against': '297',
  '+/-': '-2',
  'win%': '0.45'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1991',
  'Wins': '26',
  'Losses': '41',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '247',
  'Goal_Against': '283',
  '+/-': '-36',
  'win%': '0.325'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1991',
  'Wins': '35',
  'Losses': '31',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '287',
  'Goal_Against': '296',
  '+/-': '-9',
  'win%': '0.438'},
 {'Team_name': 'Minnesota North Stars',
  'Year': '1991',
  'Wins': '32',
  'Losses': '42',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '246',
  'Goal_Against': '278',
  '+/-': '-32',
  'win%': '0.4'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1991',
  'Wins': '41',
  'Losses': '28',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '267',
  'Goal_Against': '207',
  '+/-': '60',
  'win%': '0.512'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1991',
  'Wins': '38',
  'Losses': '31',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '289',
  'Goal_Against': '259',
  '+/-': '30',
  'win%': '0.475'},
 {'Team_name': 'New York Islanders',
  'Year': '1991',
  'Wins': '34',
  'Losses': '35',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '291',
  'Goal_Against': '299',
  '+/-': '-8',
  'win%': '0.425'},
 {'Team_name': 'New York Rangers',
  'Year': '1991',
  'Wins': '50',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '321',
  'Goal_Against': '246',
  '+/-': '75',
  'win%': '0.625'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1991',
  'Wins': '32',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '252',
  'Goal_Against': '273',
  '+/-': '-21',
  'win%': '0.4'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1991',
  'Wins': '39',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '343',
  'Goal_Against': '308',
  '+/-': '35',
  'win%': '0.487'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1991',
  'Wins': '20',
  'Losses': '48',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '255',
  'Goal_Against': '318',
  '+/-': '-63',
  'win%': '0.25'},
 {'Team_name': 'San Jose Sharks',
  'Year': '1991',
  'Wins': '17',
  'Losses': '58',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '219',
  'Goal_Against': '359',
  '+/-': '-140',
  'win%': '0.212'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1991',
  'Wins': '36',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '279',
  'Goal_Against': '266',
  '+/-': '13',
  'win%': '0.45'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1991',
  'Wins': '30',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '234',
  'Goal_Against': '294',
  '+/-': '-60',
  'win%': '0.375'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1991',
  'Wins': '42',
  'Losses': '26',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '285',
  'Goal_Against': '250',
  '+/-': '35',
  'win%': '0.525'},
 {'Team_name': 'Washington Capitals',
  'Year': '1991',
  'Wins': '45',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '330',
  'Goal_Against': '275',
  '+/-': '55',
  'win%': '0.562'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1991',
  'Wins': '33',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '251',
  'Goal_Against': '244',
  '+/-': '7',
  'win%': '0.412'},
 {'Team_name': 'Boston Bruins',
  'Year': '1992',
  'Wins': '51',
  'Losses': '26',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '332',
  'Goal_Against': '268',
  '+/-': '64',
  'win%': '0.607'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1992',
  'Wins': '38',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '335',
  'Goal_Against': '297',
  '+/-': '38',
  'win%': '0.452'},
 {'Team_name': 'Calgary Flames',
  'Year': '1992',
  'Wins': '43',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '322',
  'Goal_Against': '282',
  '+/-': '40',
  'win%': '0.512'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1992',
  'Wins': '47',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '279',
  'Goal_Against': '230',
  '+/-': '49',
  'win%': '0.56'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1992',
  'Wins': '47',
  'Losses': '28',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '369',
  'Goal_Against': '280',
  '+/-': '89',
  'win%': '0.56'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1992',
  'Wins': '26',
  'Losses': '50',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '242',
  'Goal_Against': '337',
  '+/-': '-95',
  'win%': '0.31'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1992',
  'Wins': '26',
  'Losses': '52',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '284',
  'Goal_Against': '369',
  '+/-': '-85',
  'win%': '0.31'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1992',
  'Wins': '39',
  'Losses': '35',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '338',
  'Goal_Against': '340',
  '+/-': '-2',
  'win%': '0.464'},
 {'Team_name': 'Minnesota North Stars',
  'Year': '1992',
  'Wins': '36',
  'Losses': '38',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '272',
  'Goal_Against': '293',
  '+/-': '-21',
  'win%': '0.429'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1992',
  'Wins': '48',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '326',
  'Goal_Against': '280',
  '+/-': '46',
  'win%': '0.571'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1992',
  'Wins': '40',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '308',
  'Goal_Against': '299',
  '+/-': '9',
  'win%': '0.476'},
 {'Team_name': 'New York Islanders',
  'Year': '1992',
  'Wins': '40',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '335',
  'Goal_Against': '297',
  '+/-': '38',
  'win%': '0.476'},
 {'Team_name': 'New York Rangers',
  'Year': '1992',
  'Wins': '34',
  'Losses': '39',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '304',
  'Goal_Against': '308',
  '+/-': '-4',
  'win%': '0.405'},
 {'Team_name': 'Ottawa Senators',
  'Year': '1992',
  'Wins': '10',
  'Losses': '70',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '202',
  'Goal_Against': '395',
  '+/-': '-193',
  'win%': '0.119'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1992',
  'Wins': '36',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '319',
  'Goal_Against': '319',
  '+/-': '0',
  'win%': '0.429'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1992',
  'Wins': '56',
  'Losses': '21',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '367',
  'Goal_Against': '268',
  '+/-': '99',
  'win%': '0.667'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1992',
  'Wins': '47',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '351',
  'Goal_Against': '300',
  '+/-': '51',
  'win%': '0.56'},
 {'Team_name': 'San Jose Sharks',
  'Year': '1992',
  'Wins': '11',
  'Losses': '71',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '218',
  'Goal_Against': '414',
  '+/-': '-196',
  'win%': '0.131'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1992',
  'Wins': '37',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '282',
  'Goal_Against': '278',
  '+/-': '4',
  'win%': '0.44'},
 {'Team_name': 'Tampa Bay Lightning',
  'Year': '1992',
  'Wins': '23',
  'Losses': '54',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '245',
  'Goal_Against': '332',
  '+/-': '-87',
  'win%': '0.274'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1992',
  'Wins': '44',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '288',
  'Goal_Against': '241',
  '+/-': '47',
  'win%': '0.524'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1992',
  'Wins': '46',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '346',
  'Goal_Against': '278',
  '+/-': '68',
  'win%': '0.548'},
 {'Team_name': 'Washington Capitals',
  'Year': '1992',
  'Wins': '43',
  'Losses': '34',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '325',
  'Goal_Against': '286',
  '+/-': '39',
  'win%': '0.512'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1992',
  'Wins': '40',
  'Losses': '37',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '322',
  'Goal_Against': '320',
  '+/-': '2',
  'win%': '0.476'},
 {'Team_name': 'Mighty Ducks of Anaheim',
  'Year': '1993',
  'Wins': '33',
  'Losses': '46',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '229',
  'Goal_Against': '251',
  '+/-': '-22',
  'win%': '0.393'},
 {'Team_name': 'Boston Bruins',
  'Year': '1993',
  'Wins': '42',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '289',
  'Goal_Against': '252',
  '+/-': '37',
  'win%': '0.5'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1993',
  'Wins': '43',
  'Losses': '32',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '282',
  'Goal_Against': '218',
  '+/-': '64',
  'win%': '0.512'},
 {'Team_name': 'Calgary Flames',
  'Year': '1993',
  'Wins': '42',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '302',
  'Goal_Against': '256',
  '+/-': '46',
  'win%': '0.5'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1993',
  'Wins': '39',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '254',
  'Goal_Against': '240',
  '+/-': '14',
  'win%': '0.464'},
 {'Team_name': 'Dallas Stars',
  'Year': '1993',
  'Wins': '42',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '286',
  'Goal_Against': '265',
  '+/-': '21',
  'win%': '0.5'},
 {'Team_name': 'Detroit Red Wings',
  'Year': '1993',
  'Wins': '46',
  'Losses': '30',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '356',
  'Goal_Against': '275',
  '+/-': '81',
  'win%': '0.548'},
 {'Team_name': 'Edmonton Oilers',
  'Year': '1993',
  'Wins': '25',
  'Losses': '45',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '261',
  'Goal_Against': '305',
  '+/-': '-44',
  'win%': '0.298'},
 {'Team_name': 'Florida Panthers',
  'Year': '1993',
  'Wins': '33',
  'Losses': '34',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '233',
  'Goal_Against': '233',
  '+/-': '0',
  'win%': '0.393'},
 {'Team_name': 'Hartford Whalers',
  'Year': '1993',
  'Wins': '27',
  'Losses': '48',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '227',
  'Goal_Against': '288',
  '+/-': '-61',
  'win%': '0.321'},
 {'Team_name': 'Los Angeles Kings',
  'Year': '1993',
  'Wins': '27',
  'Losses': '45',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '294',
  'Goal_Against': '322',
  '+/-': '-28',
  'win%': '0.321'},
 {'Team_name': 'Montreal Canadiens',
  'Year': '1993',
  'Wins': '41',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '283',
  'Goal_Against': '248',
  '+/-': '35',
  'win%': '0.488'},
 {'Team_name': 'New Jersey Devils',
  'Year': '1993',
  'Wins': '47',
  'Losses': '25',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '306',
  'Goal_Against': '220',
  '+/-': '86',
  'win%': '0.56'},
 {'Team_name': 'New York Islanders',
  'Year': '1993',
  'Wins': '36',
  'Losses': '36',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '282',
  'Goal_Against': '264',
  '+/-': '18',
  'win%': '0.429'},
 {'Team_name': 'New York Rangers',
  'Year': '1993',
  'Wins': '52',
  'Losses': '24',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '299',
  'Goal_Against': '231',
  '+/-': '68',
  'win%': '0.619'},
 {'Team_name': 'Ottawa Senators',
  'Year': '1993',
  'Wins': '14',
  'Losses': '61',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '201',
  'Goal_Against': '397',
  '+/-': '-196',
  'win%': '0.167'},
 {'Team_name': 'Philadelphia Flyers',
  'Year': '1993',
  'Wins': '35',
  'Losses': '39',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '294',
  'Goal_Against': '314',
  '+/-': '-20',
  'win%': '0.417'},
 {'Team_name': 'Pittsburgh Penguins',
  'Year': '1993',
  'Wins': '44',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '299',
  'Goal_Against': '285',
  '+/-': '14',
  'win%': '0.524'},
 {'Team_name': 'Quebec Nordiques',
  'Year': '1993',
  'Wins': '34',
  'Losses': '42',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '277',
  'Goal_Against': '292',
  '+/-': '-15',
  'win%': '0.405'},
 {'Team_name': 'San Jose Sharks',
  'Year': '1993',
  'Wins': '33',
  'Losses': '35',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '252',
  'Goal_Against': '265',
  '+/-': '-13',
  'win%': '0.393'},
 {'Team_name': 'St. Louis Blues',
  'Year': '1993',
  'Wins': '40',
  'Losses': '33',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '270',
  'Goal_Against': '283',
  '+/-': '-13',
  'win%': '0.476'},
 {'Team_name': 'Tampa Bay Lightning',
  'Year': '1993',
  'Wins': '30',
  'Losses': '43',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '224',
  'Goal_Against': '251',
  '+/-': '-27',
  'win%': '0.357'},
 {'Team_name': 'Toronto Maple Leafs',
  'Year': '1993',
  'Wins': '43',
  'Losses': '29',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '280',
  'Goal_Against': '243',
  '+/-': '37',
  'win%': '0.512'},
 {'Team_name': 'Vancouver Canucks',
  'Year': '1993',
  'Wins': '41',
  'Losses': '40',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '279',
  'Goal_Against': '276',
  '+/-': '3',
  'win%': '0.488'},
 {'Team_name': 'Washington Capitals',
  'Year': '1993',
  'Wins': '39',
  'Losses': '35',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '277',
  'Goal_Against': '263',
  '+/-': '14',
  'win%': '0.464'},
 {'Team_name': 'Winnipeg Jets',
  'Year': '1993',
  'Wins': '24',
  'Losses': '51',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '245',
  'Goal_Against': '344',
  '+/-': '-99',
  'win%': '0.286'},
 {'Team_name': 'Mighty Ducks of Anaheim',
  'Year': '1994',
  'Wins': '16',
  'Losses': '27',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '125',
  'Goal_Against': '164',
  '+/-': '-39',
  'win%': '0.333'},
 {'Team_name': 'Boston Bruins',
  'Year': '1994',
  'Wins': '27',
  'Losses': '18',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '150',
  'Goal_Against': '127',
  '+/-': '23',
  'win%': '0.562'},
 {'Team_name': 'Buffalo Sabres',
  'Year': '1994',
  'Wins': '22',
  'Losses': '19',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '130',
  'Goal_Against': '119',
  '+/-': '11',
  'win%': '0.458'},
 {'Team_name': 'Calgary Flames',
  'Year': '1994',
  'Wins': '24',
  'Losses': '17',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '163',
  'Goal_Against': '135',
  '+/-': '28',
  'win%': '0.5'},
 {'Team_name': 'Chicago Blackhawks',
  'Year': '1994',
  'Wins': '24',
  'Losses': '19',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '156',
  'Goal_Against': '115',
  '+/-': '41',
  'win%': '0.5'},
 {'Team_name': 'Dallas Stars',
  'Year': '1994',
  'Wins': '17',
  'Losses': '23',
  'Ot_losses': '',
  'Win_%': '',
  'Goal_for': '136',

In [15]:
df = pd.DataFrame(dl)
df.to_csv("scrapthissite_q3.4.csv" , index = False)

# 5. https://www.scrapethissite.com/pages/simple/ (coutry_name, Capital, Population, Area)

## 5.1 Extract first country details of a page & save into csv file. e.g# Andorra

In [26]:

import requests
from bs4 import BeautifulSoup
import pandas as pd
r = requests.get("https://www.scrapethissite.com/pages/simple/")
r.status_code

200

In [27]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>

In [28]:
divs = soup.find("div" , class_ = "col-md-4 country")

In [36]:
divs.find("h3" , class_ = "country-name").text.strip()

'Andorra'

In [20]:
divs.span.text.strip()

'Andorra la Vella'

In [22]:
divs.find("span" , class_ = "country-population").text

'84000'

In [24]:
divs.find("span" , class_ = "country-area").text.strip()

'468.0'

In [43]:
dl = []

data = {
"Country Name" : "" ,
"Capital" : "" ,
"Population" : "" ,
"Area" : ""
}
data["Country Name"] = divs.find("h3" , class_ = "country-name").text.strip()
data["Capital"] = divs.find("span" , class_ = "country-capital").text.strip()
data["Population"] = divs.find("span" , class_ = "country-population").text
data["Area"] = divs.find("span" , class_ = "country-area").text.strip()
dl.append(data)
dl

[{'Country Name': 'Andorra',
  'Capital': 'Andorra la Vella',
  'Population': '84000',
  'Area': '468.0'}]

In [44]:
df = pd.DataFrame(dl)
df.to_csv("scrapthissite_q5.1.csv" , index = False)

### 5.2 Extract country details of a first row of a page & save into csv file. e.g# Andorra, United Arab Emirates, Afghanistan

In [45]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r = requests.get("https://www.scrapethissite.com/pages/simple/")
r.status_code

200

In [46]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>

In [73]:
row = soup.find_all("div" , class_ = "row")[3]
row

<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div>

In [78]:
dl = []
for divs in row.find_all("div" , class_ = "col-md-4 country"):
    
    data = {
    "Country Name" : "" ,
    "Capital" : "" ,
    "Population" : "" ,
    "Area" : ""
    }
    data["Country Name"] = divs.find("h3" , class_="country-name").text.strip()
    data["Capital"] = divs.find("span" , class_ = "country-capital").text.strip()
    data["Population"] = divs.find("span" , class_ = "country-population").text
    data["Area"] = divs.find("span" , class_ = "country-area").text.strip()
    dl.append(data)
dl

[{'Country Name': 'Andorra',
  'Capital': 'Andorra la Vella',
  'Population': '84000',
  'Area': '468.0'},
 {'Country Name': 'United Arab Emirates',
  'Capital': 'Abu Dhabi',
  'Population': '4975593',
  'Area': '82880.0'},
 {'Country Name': 'Afghanistan',
  'Capital': 'Kabul',
  'Population': '29121286',
  'Area': '647500.0'}]

In [79]:
df = pd.DataFrame(dl)
df.to_csv("scrapthissite_q5.2.csv")

### 5.3 Extract all country details of a page & save into csv file.

In [80]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r = requests.get("https://www.scrapethissite.com/pages/simple/")
r.status_code

200

In [81]:
soup = BeautifulSoup(r.text , "html.parser")
soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [85]:
full_data = soup.find_all("div" , class_ = "col-md-4 country")

In [86]:
dl = []
for divs in full_data:
    
    data = {
    "Country Name" : "" ,
    "Capital" : "" ,
    "Population" : "" ,
    "Area" : ""
    }
    data["Country Name"] = divs.find("h3" , class_="country-name").text.strip()
    data["Capital"] = divs.find("span" , class_ = "country-capital").text.strip()
    data["Population"] = divs.find("span" , class_ = "country-population").text
    data["Area"] = divs.find("span" , class_ = "country-area").text.strip()
    dl.append(data)
dl

[{'Country Name': 'Andorra',
  'Capital': 'Andorra la Vella',
  'Population': '84000',
  'Area': '468.0'},
 {'Country Name': 'United Arab Emirates',
  'Capital': 'Abu Dhabi',
  'Population': '4975593',
  'Area': '82880.0'},
 {'Country Name': 'Afghanistan',
  'Capital': 'Kabul',
  'Population': '29121286',
  'Area': '647500.0'},
 {'Country Name': 'Antigua and Barbuda',
  'Capital': "St. John's",
  'Population': '86754',
  'Area': '443.0'},
 {'Country Name': 'Anguilla',
  'Capital': 'The Valley',
  'Population': '13254',
  'Area': '102.0'},
 {'Country Name': 'Albania',
  'Capital': 'Tirana',
  'Population': '2986952',
  'Area': '28748.0'},
 {'Country Name': 'Armenia',
  'Capital': 'Yerevan',
  'Population': '2968000',
  'Area': '29800.0'},
 {'Country Name': 'Angola',
  'Capital': 'Luanda',
  'Population': '13068161',
  'Area': '1246700.0'},
 {'Country Name': 'Antarctica',
  'Capital': 'None',
  'Population': '0',
  'Area': '1.4E7'},
 {'Country Name': 'Argentina',
  'Capital': 'Buenos Aires',
  'Population': '41343201',
  'Area': '2766890.0'},
 {'Country Name': 'American Samoa',
  'Capital': 'Pago Pago',
  'Population': '57881',
  'Area': '199.0'},
 {'Country Name': 'Austria',
  'Capital': 'Vienna',
  'Population': '8205000',
  'Area': '83858.0'},
 {'Country Name': 'Australia',
  'Capital': 'Canberra',
  'Population': '21515754',
  'Area': '7686850.0'},
 {'Country Name': 'Aruba',
  'Capital': 'Oranjestad',
  'Population': '71566',
  'Area': '193.0'},
 {'Country Name': 'Åland',
  'Capital': 'Mariehamn',
  'Population': '26711',
  'Area': '1580.0'},
 {'Country Name': 'Azerbaijan',
  'Capital': 'Baku',
  'Population': '8303512',
  'Area': '86600.0'},
 {'Country Name': 'Bosnia and Herzegovina',
  'Capital': 'Sarajevo',
  'Population': '4590000',
  'Area': '51129.0'},
 {'Country Name': 'Barbados',
  'Capital': 'Bridgetown',
  'Population': '285653',
  'Area': '431.0'},
 {'Country Name': 'Bangladesh',
  'Capital': 'Dhaka',
  'Population': '156118464',
  'Area': '144000.0'},
 {'Country Name': 'Belgium',
  'Capital': 'Brussels',
  'Population': '10403000',
  'Area': '30510.0'},
 {'Country Name': 'Burkina Faso',
  'Capital': 'Ouagadougou',
  'Population': '16241811',
  'Area': '274200.0'},
 {'Country Name': 'Bulgaria',
  'Capital': 'Sofia',
  'Population': '7148785',
  'Area': '110910.0'},
 {'Country Name': 'Bahrain',
  'Capital': 'Manama',
  'Population': '738004',
  'Area': '665.0'},
 {'Country Name': 'Burundi',
  'Capital': 'Bujumbura',
  'Population': '9863117',
  'Area': '27830.0'},
 {'Country Name': 'Benin',
  'Capital': 'Porto-Novo',
  'Population': '9056010',
  'Area': '112620.0'},
 {'Country Name': 'Saint Barthélemy',
  'Capital': 'Gustavia',
  'Population': '8450',
  'Area': '21.0'},
 {'Country Name': 'Bermuda',
  'Capital': 'Hamilton',
  'Population': '65365',
  'Area': '53.0'},
 {'Country Name': 'Brunei',
  'Capital': 'Bandar Seri Begawan',
  'Population': '395027',
  'Area': '5770.0'},
 {'Country Name': 'Bolivia',
  'Capital': 'Sucre',
  'Population': '9947418',
  'Area': '1098580.0'},
 {'Country Name': 'Bonaire',
  'Capital': 'Kralendijk',
  'Population': '18012',
  'Area': '328.0'},
 {'Country Name': 'Brazil',
  'Capital': 'Brasília',
  'Population': '201103330',
  'Area': '8511965.0'},
 {'Country Name': 'Bahamas',
  'Capital': 'Nassau',
  'Population': '301790',
  'Area': '13940.0'},
 {'Country Name': 'Bhutan',
  'Capital': 'Thimphu',
  'Population': '699847',
  'Area': '47000.0'},
 {'Country Name': 'Bouvet Island',
  'Capital': 'None',
  'Population': '0',
  'Area': '49.0'},
 {'Country Name': 'Botswana',
  'Capital': 'Gaborone',
  'Population': '2029307',
  'Area': '600370.0'},
 {'Country Name': 'Belarus',
  'Capital': 'Minsk',
  'Population': '9685000',
  'Area': '207600.0'},
 {'Country Name': 'Belize',
  'Capital': 'Belmopan',
  'Population': '314522',
  'Area': '22966.0'},
 {'Country Name': 'Canada',
  'Capital': 'Ottawa',
  'Population': '33679000',
  'Area': '9984670.0'},
 {'Country Name': 'Cocos [Keeling] Islands',
  'Capital': 'West Island',
  'Population': '628',
  'Area': '14.0'},
 {'Country Name': 'Democratic Republic of the Congo',
  'Capital': 'Kinshasa',
  'Population': '70916439',
  'Area': '2345410.0'},
 {'Country Name': 'Central African Republic',
  'Capital': 'Bangui',
  'Population': '4844927',
  'Area': '622984.0'},
 {'Country Name': 'Republic of the Congo',
  'Capital': 'Brazzaville',
  'Population': '3039126',
  'Area': '342000.0'},
 {'Country Name': 'Switzerland',
  'Capital': 'Bern',
  'Population': '7581000',
  'Area': '41290.0'},
 {'Country Name': 'Ivory Coast',
  'Capital': 'Yamoussoukro',
  'Population': '21058798',
  'Area': '322460.0'},
 {'Country Name': 'Cook Islands',
  'Capital': 'Avarua',
  'Population': '21388',
  'Area': '240.0'},
 {'Country Name': 'Chile',
  'Capital': 'Santiago',
  'Population': '16746491',
  'Area': '756950.0'},
 {'Country Name': 'Cameroon',
  'Capital': 'Yaoundé',
  'Population': '19294149',
  'Area': '475440.0'},
 {'Country Name': 'China',
  'Capital': 'Beijing',
  'Population': '1330044000',
  'Area': '9596960.0'},
 {'Country Name': 'Colombia',
  'Capital': 'Bogotá',
  'Population': '47790000',
  'Area': '1138910.0'},
 {'Country Name': 'Costa Rica',
  'Capital': 'San José',
  'Population': '4516220',
  'Area': '51100.0'},
 {'Country Name': 'Cuba',
  'Capital': 'Havana',
  'Population': '11423000',
  'Area': '110860.0'},
 {'Country Name': 'Cape Verde',
  'Capital': 'Praia',
  'Population': '508659',
  'Area': '4033.0'},
 {'Country Name': 'Curacao',
  'Capital': 'Willemstad',
  'Population': '141766',
  'Area': '444.0'},
 {'Country Name': 'Christmas Island',
  'Capital': 'Flying Fish Cove',
  'Population': '1500',
  'Area': '135.0'},
 {'Country Name': 'Cyprus',
  'Capital': 'Nicosia',
  'Population': '1102677',
  'Area': '9250.0'},
 {'Country Name': 'Czech Republic',
  'Capital': 'Prague',
  'Population': '10476000',
  'Area': '78866.0'},
 {'Country Name': 'Germany',
  'Capital': 'Berlin',
  'Population': '81802257',
  'Area': '357021.0'},
 {'Country Name': 'Djibouti',
  'Capital': 'Djibouti',
  'Population': '740528',
  'Area': '23000.0'},
 {'Country Name': 'Denmark',
  'Capital': 'Copenhagen',
  'Population': '5484000',
  'Area': '43094.0'},
 {'Country Name': 'Dominica',
  'Capital': 'Roseau',
  'Population': '72813',
  'Area': '754.0'},
 {'Country Name': 'Dominican Republic',
  'Capital': 'Santo Domingo',
  'Population': '9823821',
  'Area': '48730.0'},
 {'Country Name': 'Algeria',
  'Capital': 'Algiers',
  'Population': '34586184',
  'Area': '2381740.0'},
 {'Country Name': 'Ecuador',
  'Capital': 'Quito',
  'Population': '14790608',
  'Area': '283560.0'},
 {'Country Name': 'Estonia',
  'Capital': 'Tallinn',
  'Population': '1291170',
  'Area': '45226.0'},
 {'Country Name': 'Egypt',
  'Capital': 'Cairo',
  'Population': '80471869',
  'Area': '1001450.0'},
 {'Country Name': 'Western Sahara',
  'Capital': 'Laâyoune / El Aaiún',
  'Population': '273008',
  'Area': '266000.0'},
 {'Country Name': 'Eritrea',
  'Capital': 'Asmara',
  'Population': '5792984',
  'Area': '121320.0'},
 {'Country Name': 'Spain',
  'Capital': 'Madrid',
  'Population': '46505963',
  'Area': '504782.0'},
 {'Country Name': 'Ethiopia',
  'Capital': 'Addis Ababa',
  'Population': '88013491',
  'Area': '1127127.0'},
 {'Country Name': 'Finland',
  'Capital': 'Helsinki',
  'Population': '5244000',
  'Area': '337030.0'},
 {'Country Name': 'Fiji',
  'Capital': 'Suva',
  'Population': '875983',
  'Area': '18270.0'},
 {'Country Name': 'Falkland Islands',
  'Capital': 'Stanley',
  'Population': '2638',
  'Area': '12173.0'},
 {'Country Name': 'Micronesia',
  'Capital': 'Palikir',
  'Population': '107708',
  'Area': '702.0'},
 {'Country Name': 'Faroe Islands',
  'Capital': 'Tórshavn',
  'Population': '48228',
  'Area': '1399.0'},
 {'Country Name': 'France',
  'Capital': 'Paris',
  'Population': '64768389',
  'Area': '547030.0'},
 {'Country Name': 'Gabon',
  'Capital': 'Libreville',
  'Population': '1545255',
  'Area': '267667.0'},
 {'Country Name': 'United Kingdom',
  'Capital': 'London',
  'Population': '62348447',
  'Area': '244820.0'},
 {'Country Name': 'Grenada',
  'Capital': "St. George's",
  'Population': '107818',
  'Area': '344.0'},
 {'Country Name': 'Georgia',
  'Capital': 'Tbilisi',
  'Population': '4630000',
  'Area': '69700.0'},
 {'Country Name': 'French Guiana',
  'Capital': 'Cayenne',
  'Population': '195506',
  'Area': '91000.0'},
 {'Country Name': 'Guernsey',
  'Capital': 'St Peter Port',
  'Population': '65228',
  'Area': '78.0'},
 {'Country Name': 'Ghana',
  'Capital': 'Accra',
  'Population': '24339838',
  'Area': '239460.0'},
 {'Country Name': 'Gibraltar',
  'Capital': 'Gibraltar',
  'Population': '27884',
  'Area': '6.5'},
 {'Country Name': 'Greenland',
  'Capital': 'Nuuk',
  'Population': '56375',
  'Area': '2166086.0'},
 {'Country Name': 'Gambia',
  'Capital': 'Bathurst',
  'Population': '1593256',
  'Area': '11300.0'},
 {'Country Name': 'Guinea',
  'Capital': 'Conakry',
  'Population': '10324025',
  'Area': '245857.0'},
 {'Country Name': 'Guadeloupe',
  'Capital': 'Basse-Terre',
  'Population': '443000',
  'Area': '1780.0'},
 {'Country Name': 'Equatorial Guinea',
  'Capital': 'Malabo',
  'Population': '1014999',
  'Area': '28051.0'},
 {'Country Name': 'Greece',
  'Capital': 'Athens',
  'Population': '11000000',
  'Area': '131940.0'},
 {'Country Name': 'South Georgia and the South Sandwich Islands',
  'Capital': 'Grytviken',
  'Population': '30',
  'Area': '3903.0'},
 {'Country Name': 'Guatemala',
  'Capital': 'Guatemala City',
  'Population': '13550440',
  'Area': '108890.0'},
 {'Country Name': 'Guam',
  'Capital': 'Hagåtña',
  'Population': '159358',
  'Area': '549.0'},
 {'Country Name': 'Guinea-Bissau',
  'Capital': 'Bissau',
  'Population': '1565126',
  'Area': '36120.0'},
 {'Country Name': 'Guyana',
  'Capital': 'Georgetown',
  'Population': '748486',
  'Area': '214970.0'},
 {'Country Name': 'Hong Kong',
  'Capital': 'Hong Kong',
  'Population': '6898686',
  'Area': '1092.0'},
 {'Country Name': 'Heard Island and McDonald Islands',
  'Capital': 'None',
  'Population': '0',
  'Area': '412.0'},
 {'Country Name': 'Honduras',
  'Capital': 'Tegucigalpa',
  'Population': '7989415',
  'Area': '112090.0'},
 {'Country Name': 'Croatia',
  'Capital': 'Zagreb',
  'Population': '4491000',
  'Area': '56542.0'},
 {'Country Name': 'Haiti',
  'Capital': 'Port-au-Prince',
  'Population': '9648924',
  'Area': '27750.0'},
 {'Country Name': 'Hungary',
  'Capital': 'Budapest',
  'Population': '9982000',
  'Area': '93030.0'},
 {'Country Name': 'Indonesia',
  'Capital': 'Jakarta',
  'Population': '242968342',
  'Area': '1919440.0'},
 {'Country Name': 'Ireland',
  'Capital': 'Dublin',
  'Population': '4622917',
  'Area': '70280.0'},
 {'Country Name': 'Israel',
  'Capital': 'None',
  'Population': '7353985',
  'Area': '20770.0'},
 {'Country Name': 'Isle of Man',
  'Capital': 'Douglas',
  'Population': '75049',
  'Area': '572.0'},
 {'Country Name': 'India',
  'Capital': 'New Delhi',
  'Population': '1173108018',
  'Area': '3287590.0'},
 {'Country Name': 'British Indian Ocean Territory',
  'Capital': 'None',
  'Population': '4000',
  'Area': '60.0'},
 {'Country Name': 'Iraq',
  'Capital': 'Baghdad',
  'Population': '29671605',
  'Area': '437072.0'},
 {'Country Name': 'Iran',
  'Capital': 'Tehran',
  'Population': '76923300',
  'Area': '1648000.0'},
 {'Country Name': 'Iceland',
  'Capital': 'Reykjavik',
  'Population': '308910',
  'Area': '103000.0'},
 {'Country Name': 'Italy',
  'Capital': 'Rome',
  'Population': '60340328',
  'Area': '301230.0'},
 {'Country Name': 'Jersey',
  'Capital': 'Saint Helier',
  'Population': '90812',
  'Area': '116.0'},
 {'Country Name': 'Jamaica',
  'Capital': 'Kingston',
  'Population': '2847232',
  'Area': '10991.0'},
 {'Country Name': 'Jordan',
  'Capital': 'Amman',
  'Population': '6407085',
  'Area': '92300.0'},
 {'Country Name': 'Japan',
  'Capital': 'Tokyo',
  'Population': '127288000',
  'Area': '377835.0'},
 {'Country Name': 'Kenya',
  'Capital': 'Nairobi',
  'Population': '40046566',
  'Area': '582650.0'},
 {'Country Name': 'Kyrgyzstan',
  'Capital': 'Bishkek',
  'Population': '5776500',
  'Area': '198500.0'},
 {'Country Name': 'Cambodia',
  'Capital': 'Phnom Penh',
  'Population': '14453680',
  'Area': '181040.0'},
 {'Country Name': 'Kiribati',
  'Capital': 'Tarawa',
  'Population': '92533',
  'Area': '811.0'},
 {'Country Name': 'Comoros',
  'Capital': 'Moroni',
  'Population': '773407',
  'Area': '2170.0'},
 {'Country Name': 'Saint Kitts and Nevis',
  'Capital': 'Basseterre',
  'Population': '51134',
  'Area': '261.0'},
 {'Country Name': 'North Korea',
  'Capital': 'Pyongyang',
  'Population': '22912177',
  'Area': '120540.0'},
 {'Country Name': 'South Korea',
  'Capital': 'Seoul',
  'Population': '48422644',
  'Area': '98480.0'},
 {'Country Name': 'Kuwait',
  'Capital': 'Kuwait City',
  'Population': '2789132',
  'Area': '17820.0'},
 {'Country Name': 'Cayman Islands',
  'Capital': 'George Town',
  'Population': '44270',
  'Area': '262.0'},
 {'Country Name': 'Kazakhstan',
  'Capital': 'Astana',
  'Population': '15340000',
  'Area': '2717300.0'},
 {'Country Name': 'Laos',
  'Capital': 'Vientiane',
  'Population': '6368162',
  'Area': '236800.0'},
 {'Country Name': 'Lebanon',
  'Capital': 'Beirut',
  'Population': '4125247',
  'Area': '10400.0'},
 {'Country Name': 'Saint Lucia',
  'Capital': 'Castries',
  'Population': '160922',
  'Area': '616.0'},
 {'Country Name': 'Liechtenstein',
  'Capital': 'Vaduz',
  'Population': '35000',
  'Area': '160.0'},
 {'Country Name': 'Sri Lanka',
  'Capital': 'Colombo',
  'Population': '21513990',
  'Area': '65610.0'},
 {'Country Name': 'Liberia',
  'Capital': 'Monrovia',
  'Population': '3685076',
  'Area': '111370.0'},
 {'Country Name': 'Lesotho',
  'Capital': 'Maseru',
  'Population': '1919552',
  'Area': '30355.0'},
 {'Country Name': 'Lithuania',
  'Capital': 'Vilnius',
  'Population': '2944459',
  'Area': '65200.0'},
 {'Country Name': 'Luxembourg',
  'Capital': 'Luxembourg',
  'Population': '497538',
  'Area': '2586.0'},
 {'Country Name': 'Latvia',
  'Capital': 'Riga',
  'Population': '2217969',
  'Area': '64589.0'},
 {'Country Name': 'Libya',
  'Capital': 'Tripoli',
  'Population': '6461454',
  'Area': '1759540.0'},
 {'Country Name': 'Morocco',
  'Capital': 'Rabat',
  'Population': '31627428',
  'Area': '446550.0'},
 {'Country Name': 'Monaco',
  'Capital': 'Monaco',
  'Population': '32965',
  'Area': '1.95'},
 {'Country Name': 'Moldova',
  'Capital': 'Chişinău',
  'Population': '4324000',
  'Area': '33843.0'},
 {'Country Name': 'Montenegro',
  'Capital': 'Podgorica',
  'Population': '666730',
  'Area': '14026.0'},
 {'Country Name': 'Saint Martin',
  'Capital': 'Marigot',
  'Population': '35925',
  'Area': '53.0'},
 {'Country Name': 'Madagascar',
  'Capital': 'Antananarivo',
  'Population': '21281844',
  'Area': '587040.0'},
 {'Country Name': 'Marshall Islands',
  'Capital': 'Majuro',
  'Population': '65859',
  'Area': '181.3'},
 {'Country Name': 'Macedonia',
  'Capital': 'Skopje',
  'Population': '2062294',
  'Area': '25333.0'},
 {'Country Name': 'Mali',
  'Capital': 'Bamako',
  'Population': '13796354',
  'Area': '1240000.0'},
 {'Country Name': 'Myanmar [Burma]',
  'Capital': 'Naypyitaw',
  'Population': '53414374',
  'Area': '678500.0'},
 {'Country Name': 'Mongolia',
  'Capital': 'Ulan Bator',
  'Population': '3086918',
  'Area': '1565000.0'},
 {'Country Name': 'Macao',
  'Capital': 'Macao',
  'Population': '449198',
  'Area': '254.0'},
 {'Country Name': 'Northern Mariana Islands',
  'Capital': 'Saipan',
  'Population': '53883',
  'Area': '477.0'},
 {'Country Name': 'Martinique',
  'Capital': 'Fort-de-France',
  'Population': '432900',
  'Area': '1100.0'},
 {'Country Name': 'Mauritania',
  'Capital': 'Nouakchott',
  'Population': '3205060',
  'Area': '1030700.0'},
 {'Country Name': 'Montserrat',
  'Capital': 'Plymouth',
  'Population': '9341',
  'Area': '102.0'},
 {'Country Name': 'Malta',
  'Capital': 'Valletta',
  'Population': '403000',
  'Area': '316.0'},
 {'Country Name': 'Mauritius',
  'Capital': 'Port Louis',
  'Population': '1294104',
  'Area': '2040.0'},
 {'Country Name': 'Maldives',
  'Capital': 'Malé',
  'Population': '395650',
  'Area': '300.0'},
 {'Country Name': 'Malawi',
  'Capital': 'Lilongwe',
  'Population': '15447500',
  'Area': '118480.0'},
 {'Country Name': 'Mexico',
  'Capital': 'Mexico City',
  'Population': '112468855',
  'Area': '1972550.0'},
 {'Country Name': 'Malaysia',
  'Capital': 'Kuala Lumpur',
  'Population': '28274729',
  'Area': '329750.0'},
 {'Country Name': 'Mozambique',
  'Capital': 'Maputo',
  'Population': '22061451',
  'Area': '801590.0'},
 {'Country Name': 'Namibia',
  'Capital': 'Windhoek',
  'Population': '2128471',
  'Area': '825418.0'},
 {'Country Name': 'New Caledonia',
  'Capital': 'Noumea',
  'Population': '216494',
  'Area': '19060.0'},
 {'Country Name': 'Niger',
  'Capital': 'Niamey',
  'Population': '15878271',
  'Area': '1267000.0'},
 {'Country Name': 'Norfolk Island',
  'Capital': 'Kingston',
  'Population': '1828',
  'Area': '34.6'},
 {'Country Name': 'Nigeria',
  'Capital': 'Abuja',
  'Population': '154000000',
  'Area': '923768.0'},
 {'Country Name': 'Nicaragua',
  'Capital': 'Managua',
  'Population': '5995928',
  'Area': '129494.0'},
 {'Country Name': 'Netherlands',
  'Capital': 'Amsterdam',
  'Population': '16645000',
  'Area': '41526.0'},
 {'Country Name': 'Norway',
  'Capital': 'Oslo',
  'Population': '5009150',
  'Area': '324220.0'},
 {'Country Name': 'Nepal',
  'Capital': 'Kathmandu',
  'Population': '28951852',
  'Area': '140800.0'},
 {'Country Name': 'Nauru',
  'Capital': 'Yaren',
  'Population': '10065',
  'Area': '21.0'},
 {'Country Name': 'Niue',
  'Capital': 'Alofi',
  'Population': '2166',
  'Area': '260.0'},
 {'Country Name': 'New Zealand',
  'Capital': 'Wellington',
  'Population': '4252277',
  'Area': '268680.0'},
 {'Country Name': 'Oman',
  'Capital': 'Muscat',
  'Population': '2967717',
  'Area': '212460.0'},
 {'Country Name': 'Panama',
  'Capital': 'Panama City',
  'Population': '3410676',
  'Area': '78200.0'},
 {'Country Name': 'Peru',
  'Capital': 'Lima',
  'Population': '29907003',
  'Area': '1285220.0'},
 {'Country Name': 'French Polynesia',
  'Capital': 'Papeete',
  'Population': '270485',
  'Area': '4167.0'},
 {'Country Name': 'Papua New Guinea',
  'Capital': 'Port Moresby',
  'Population': '6064515',
  'Area': '462840.0'},
 {'Country Name': 'Philippines',
  'Capital': 'Manila',
  'Population': '99900177',
  'Area': '300000.0'},
 {'Country Name': 'Pakistan',
  'Capital': 'Islamabad',
  'Population': '184404791',
  'Area': '803940.0'},
 {'Country Name': 'Poland',
  'Capital': 'Warsaw',
  'Population': '38500000',
  'Area': '312685.0'},
 {'Country Name': 'Saint Pierre and Miquelon',
  'Capital': 'Saint-Pierre',
  'Population': '7012',
  'Area': '242.0'},
 {'Country Name': 'Pitcairn Islands',
  'Capital': 'Adamstown',
  'Population': '46',
  'Area': '47.0'},
 {'Country Name': 'Puerto Rico',
  'Capital': 'San Juan',
  'Population': '3916632',
  'Area': '9104.0'},
 {'Country Name': 'Palestine',
  'Capital': 'None',
  'Population': '3800000',
  'Area': '5970.0'},
 {'Country Name': 'Portugal',
  'Capital': 'Lisbon',
  'Population': '10676000',
  'Area': '92391.0'},
 {'Country Name': 'Palau',
  'Capital': 'Melekeok',
  'Population': '19907',
  'Area': '458.0'},
 {'Country Name': 'Paraguay',
  'Capital': 'Asunción',
  'Population': '6375830',
  'Area': '406750.0'},
 {'Country Name': 'Qatar',
  'Capital': 'Doha',
  'Population': '840926',
  'Area': '11437.0'},
 {'Country Name': 'Réunion',
  'Capital': 'Saint-Denis',
  'Population': '776948',
  'Area': '2517.0'},
 {'Country Name': 'Romania',
  'Capital': 'Bucharest',
  'Population': '21959278',
  'Area': '237500.0'},
 {'Country Name': 'Serbia',
  'Capital': 'Belgrade',
  'Population': '7344847',
  'Area': '88361.0'},
 {'Country Name': 'Russia',
  'Capital': 'Moscow',
  'Population': '140702000',

In [ ]:
df = pd.DataFrame(dl)
df.to_csv("scrapthissite_q5.3.csv" , index = False)
df

             Country Name           Capital Population       Area
0                 Andorra  Andorra la Vella      84000      468.0
1    United Arab Emirates         Abu Dhabi    4975593    82880.0
2             Afghanistan             Kabul   29121286   647500.0
3     Antigua and Barbuda        St. John's      86754      443.0
4                Anguilla        The Valley      13254      102.0
..                    ...               ...        ...        ...
245                 Yemen             Sanaa   23495361   527970.0
246               Mayotte         Mamoudzou     159042      374.0
247          South Africa          Pretoria   49000000  1219912.0
248                Zambia            Lusaka   13460305   752614.0
249              Zimbabwe            Harare   11651858   390580.0

[250 rows x 4 columns]

### 5.4 Extract country details of a first column of a page & save into csv file.

In [90]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r = requests.get("https://www.scrapethissite.com/pages/simple/")
r.status_code

200

In [91]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>

In [107]:
sec = soup.find_all("div" , class_ = "col-md-4 country")
sec

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">

In [110]:
col_data = sec[0::3]
col_data

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cl"></i>
                             Chile
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Santiago</span><br/>
 <strong>Population:</strong> <span class="country-population">16746491</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">756950.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-co"></i>
                             Colombia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bogotá</span><br/>
 <strong>Population:</strong> <span class="country-population">47790000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1138910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cv"></i>
                             Cape Verde
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Praia</span><br/>
 <strong>Population:</strong> <span class="country-population">508659</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">4033.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cy"></i>
                             Cyprus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nicosia</span><br/>
 <strong>Population:</strong> <span class="country-population">1102677</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9250.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dj"></i>
                             Djibouti
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Djibouti</span><br/>
 <strong>Population:</strong> <span class="country-population">740528</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">23000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-do"></i>
                             Dominican Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Santo Domingo</span><br/>
 <strong>Population:</strong> <span class="country-population">9823821</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">48730.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ee"></i>
                             Estonia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tallinn</span><br/>
 <strong>Population:</strong> <span class="country-population">1291170</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">45226.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-er"></i>
                             Eritrea
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Asmara</span><br/>
 <strong>Population:</strong> <span class="country-population">5792984</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">121320.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fi"></i>
                             Finland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Helsinki</span><br/>
 <strong>Population:</strong> <span class="country-population">5244000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">337030.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fm"></i>
                             Micronesia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Palikir</span><br/>
 <strong>Population:</strong> <span class="country-population">107708</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">702.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ga"></i>
                             Gabon
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Libreville</span><br/>
 <strong>Population:</strong> <span class="country-population">1545255</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">267667.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ge"></i>
                             Georgia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tbilisi</span><br/>
 <strong>Population:</strong> <span class="country-population">4630000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">69700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gh"></i>
                             Ghana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Accra</span><br/>
 <strong>Population:</strong> <span class="country-population">24339838</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">239460.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gm"></i>
                             Gambia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bathurst</span><br/>
 <strong>Population:</strong> <span class="country-population">1593256</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">11300.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gq"></i>
                             Equatorial Guinea
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Malabo</span><br/>
 <strong>Population:</strong> <span class="country-population">1014999</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28051.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gt"></i>
                             Guatemala
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Guatemala City</span><br/>
 <strong>Population:</strong> <span class="country-population">13550440</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">108890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gy"></i>
                             Guyana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Georgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">748486</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">214970.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hn"></i>
                             Honduras
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tegucigalpa</span><br/>
 <strong>Population:</strong> <span class="country-population">7989415</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112090.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hu"></i>
                             Hungary
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Budapest</span><br/>
 <strong>Population:</strong> <span class="country-population">9982000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">93030.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-il"></i>
                             Israel
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">7353985</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">20770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-io"></i>
                             British Indian Ocean Territory
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">4000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">60.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-is"></i>
                             Iceland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Reykjavik</span><br/>
 <strong>Population:</strong> <span class="country-population">308910</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">103000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jm"></i>
                             Jamaica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kingston</span><br/>
 <strong>Population:</strong> <span class="country-population">2847232</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">10991.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ke"></i>
                             Kenya
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nairobi</span><br/>
 <strong>Population:</strong> <span class="country-population">40046566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">582650.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ki"></i>
                             Kiribati
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tarawa</span><br/>
 <strong>Population:</strong> <span class="country-population">92533</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">811.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kp"></i>
                             North Korea
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pyongyang</span><br/>
 <strong>Population:</strong> <span class="country-population">22912177</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">120540.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ky"></i>
                             Cayman Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">George Town</span><br/>
 <strong>Population:</strong> <span class="country-population">44270</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">262.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lb"></i>
                             Lebanon
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Beirut</span><br/>
 <strong>Population:</strong> <span class="country-population">4125247</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">10400.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">

In [111]:
dl = []
for divs in col_data:
    
    data = {
    "Country Name" : "" ,
    "Capital" : "" ,
    "Population" : "" ,
    "Area" : ""
    }
    data["Country Name"] = divs.find("h3" , class_="country-name").text.strip()
    data["Capital"] = divs.find("span" , class_ = "country-capital").text.strip()
    data["Population"] = divs.find("span" , class_ = "country-population").text
    data["Area"] = divs.find("span" , class_ = "country-area").text.strip()
    dl.append(data)
dl

[{'Country Name': 'Andorra',
  'Capital': 'Andorra la Vella',
  'Population': '84000',
  'Area': '468.0'},
 {'Country Name': 'Antigua and Barbuda',
  'Capital': "St. John's",
  'Population': '86754',
  'Area': '443.0'},
 {'Country Name': 'Armenia',
  'Capital': 'Yerevan',
  'Population': '2968000',
  'Area': '29800.0'},
 {'Country Name': 'Argentina',
  'Capital': 'Buenos Aires',
  'Population': '41343201',
  'Area': '2766890.0'},
 {'Country Name': 'Australia',
  'Capital': 'Canberra',
  'Population': '21515754',
  'Area': '7686850.0'},
 {'Country Name': 'Azerbaijan',
  'Capital': 'Baku',
  'Population': '8303512',
  'Area': '86600.0'},
 {'Country Name': 'Bangladesh',
  'Capital': 'Dhaka',
  'Population': '156118464',
  'Area': '144000.0'},
 {'Country Name': 'Bulgaria',
  'Capital': 'Sofia',
  'Population': '7148785',
  'Area': '110910.0'},
 {'Country Name': 'Benin',
  'Capital': 'Porto-Novo',
  'Population': '9056010',
  'Area': '112620.0'},
 {'Country Name': 'Brunei',
  'Capital': 'Bandar Seri Begawan',
  'Population': '395027',
  'Area': '5770.0'},
 {'Country Name': 'Brazil',
  'Capital': 'Brasília',
  'Population': '201103330',
  'Area': '8511965.0'},
 {'Country Name': 'Bouvet Island',
  'Capital': 'None',
  'Population': '0',
  'Area': '49.0'},
 {'Country Name': 'Belize',
  'Capital': 'Belmopan',
  'Population': '314522',
  'Area': '22966.0'},
 {'Country Name': 'Democratic Republic of the Congo',
  'Capital': 'Kinshasa',
  'Population': '70916439',
  'Area': '2345410.0'},
 {'Country Name': 'Switzerland',
  'Capital': 'Bern',
  'Population': '7581000',
  'Area': '41290.0'},
 {'Country Name': 'Chile',
  'Capital': 'Santiago',
  'Population': '16746491',
  'Area': '756950.0'},
 {'Country Name': 'Colombia',
  'Capital': 'Bogotá',
  'Population': '47790000',
  'Area': '1138910.0'},
 {'Country Name': 'Cape Verde',
  'Capital': 'Praia',
  'Population': '508659',
  'Area': '4033.0'},
 {'Country Name': 'Cyprus',
  'Capital': 'Nicosia',
  'Population': '1102677',
  'Area': '9250.0'},
 {'Country Name': 'Djibouti',
  'Capital': 'Djibouti',
  'Population': '740528',
  'Area': '23000.0'},
 {'Country Name': 'Dominican Republic',
  'Capital': 'Santo Domingo',
  'Population': '9823821',
  'Area': '48730.0'},
 {'Country Name': 'Estonia',
  'Capital': 'Tallinn',
  'Population': '1291170',
  'Area': '45226.0'},
 {'Country Name': 'Eritrea',
  'Capital': 'Asmara',
  'Population': '5792984',
  'Area': '121320.0'},
 {'Country Name': 'Finland',
  'Capital': 'Helsinki',
  'Population': '5244000',
  'Area': '337030.0'},
 {'Country Name': 'Micronesia',
  'Capital': 'Palikir',
  'Population': '107708',
  'Area': '702.0'},
 {'Country Name': 'Gabon',
  'Capital': 'Libreville',
  'Population': '1545255',
  'Area': '267667.0'},
 {'Country Name': 'Georgia',
  'Capital': 'Tbilisi',
  'Population': '4630000',
  'Area': '69700.0'},
 {'Country Name': 'Ghana',
  'Capital': 'Accra',
  'Population': '24339838',
  'Area': '239460.0'},
 {'Country Name': 'Gambia',
  'Capital': 'Bathurst',
  'Population': '1593256',
  'Area': '11300.0'},
 {'Country Name': 'Equatorial Guinea',
  'Capital': 'Malabo',
  'Population': '1014999',
  'Area': '28051.0'},
 {'Country Name': 'Guatemala',
  'Capital': 'Guatemala City',
  'Population': '13550440',
  'Area': '108890.0'},
 {'Country Name': 'Guyana',
  'Capital': 'Georgetown',
  'Population': '748486',
  'Area': '214970.0'},
 {'Country Name': 'Honduras',
  'Capital': 'Tegucigalpa',
  'Population': '7989415',
  'Area': '112090.0'},
 {'Country Name': 'Hungary',
  'Capital': 'Budapest',
  'Population': '9982000',
  'Area': '93030.0'},
 {'Country Name': 'Israel',
  'Capital': 'None',
  'Population': '7353985',
  'Area': '20770.0'},
 {'Country Name': 'British Indian Ocean Territory',
  'Capital': 'None',
  'Population': '4000',
  'Area': '60.0'},
 {'Country Name': 'Iceland',
  'Capital': 'Reykjavik',
  'Population': '308910',
  'Area': '103000.0'},
 {'Country Name': 'Jamaica',
  'Capital': 'Kingston',
  'Population': '2847232',
  'Area': '10991.0'},
 {'Country Name': 'Kenya',
  'Capital': 'Nairobi',
  'Population': '40046566',
  'Area': '582650.0'},
 {'Country Name': 'Kiribati',
  'Capital': 'Tarawa',
  'Population': '92533',
  'Area': '811.0'},
 {'Country Name': 'North Korea',
  'Capital': 'Pyongyang',
  'Population': '22912177',
  'Area': '120540.0'},
 {'Country Name': 'Cayman Islands',
  'Capital': 'George Town',
  'Population': '44270',
  'Area': '262.0'},
 {'Country Name': 'Lebanon',
  'Capital': 'Beirut',
  'Population': '4125247',
  'Area': '10400.0'},
 {'Country Name': 'Sri Lanka',
  'Capital': 'Colombo',
  'Population': '21513990',
  'Area': '65610.0'},
 {'Country Name': 'Lithuania',
  'Capital': 'Vilnius',
  'Population': '2944459',
  'Area': '65200.0'},
 {'Country Name': 'Libya',
  'Capital': 'Tripoli',
  'Population': '6461454',
  'Area': '1759540.0'},
 {'Country Name': 'Moldova',
  'Capital': 'Chişinău',
  'Population': '4324000',
  'Area': '33843.0'},
 {'Country Name': 'Madagascar',
  'Capital': 'Antananarivo',
  'Population': '21281844',
  'Area': '587040.0'},
 {'Country Name': 'Mali',
  'Capital': 'Bamako',
  'Population': '13796354',
  'Area': '1240000.0'},
 {'Country Name': 'Macao',
  'Capital': 'Macao',
  'Population': '449198',
  'Area': '254.0'},
 {'Country Name': 'Mauritania',
  'Capital': 'Nouakchott',
  'Population': '3205060',
  'Area': '1030700.0'},
 {'Country Name': 'Mauritius',
  'Capital': 'Port Louis',
  'Population': '1294104',
  'Area': '2040.0'},
 {'Country Name': 'Mexico',
  'Capital': 'Mexico City',
  'Population': '112468855',
  'Area': '1972550.0'},
 {'Country Name': 'Namibia',
  'Capital': 'Windhoek',
  'Population': '2128471',
  'Area': '825418.0'},
 {'Country Name': 'Norfolk Island',
  'Capital': 'Kingston',
  'Population': '1828',
  'Area': '34.6'},
 {'Country Name': 'Netherlands',
  'Capital': 'Amsterdam',
  'Population': '16645000',
  'Area': '41526.0'},
 {'Country Name': 'Nauru',
  'Capital': 'Yaren',
  'Population': '10065',
  'Area': '21.0'},
 {'Country Name': 'Oman',
  'Capital': 'Muscat',
  'Population': '2967717',
  'Area': '212460.0'},
 {'Country Name': 'French Polynesia',
  'Capital': 'Papeete',
  'Population': '270485',
  'Area': '4167.0'},
 {'Country Name': 'Pakistan',
  'Capital': 'Islamabad',
  'Population': '184404791',
  'Area': '803940.0'},
 {'Country Name': 'Pitcairn Islands',
  'Capital': 'Adamstown',
  'Population': '46',
  'Area': '47.0'},
 {'Country Name': 'Portugal',
  'Capital': 'Lisbon',
  'Population': '10676000',
  'Area': '92391.0'},
 {'Country Name': 'Qatar',
  'Capital': 'Doha',
  'Population': '840926',
  'Area': '11437.0'},
 {'Country Name': 'Serbia',
  'Capital': 'Belgrade',
  'Population': '7344847',
  'Area': '88361.0'},
 {'Country Name': 'Saudi Arabia',
  'Capital': 'Riyadh',
  'Population': '25731776',
  'Area': '1960582.0'},
 {'Country Name': 'Sudan',
  'Capital': 'Khartoum',
  'Population': '35000000',
  'Area': '1861484.0'},
 {'Country Name': 'Saint Helena',
  'Capital': 'Jamestown',
  'Population': '7460',
  'Area': '410.0'},
 {'Country Name': 'Slovakia',
  'Capital': 'Bratislava',
  'Population': '5455000',
  'Area': '48845.0'},
 {'Country Name': 'Senegal',
  'Capital': 'Dakar',
  'Population': '12323252',
  'Area': '196190.0'},
 {'Country Name': 'South Sudan',
  'Capital': 'Juba',
  'Population': '8260490',
  'Area': '644329.0'},
 {'Country Name': 'Sint Maarten',
  'Capital': 'Philipsburg',
  'Population': '37429',
  'Area': '21.0'},
 {'Country Name': 'Turks and Caicos Islands',
  'Capital': 'Cockburn Town',
  'Population': '20556',
  'Area': '430.0'},
 {'Country Name': 'Togo',
  'Capital': 'Lomé',
  'Population': '6587239',
  'Area': '56785.0'},
 {'Country Name': 'Tokelau',
  'Capital': 'None',
  'Population': '1466',
  'Area': '10.0'},
 {'Country Name': 'Tunisia',
  'Capital': 'Tunis',
  'Population': '10589025',
  'Area': '163610.0'},
 {'Country Name': 'Trinidad and Tobago',
  'Capital': 'Port of Spain',
  'Population': '1228691',
  'Area': '5128.0'},
 {'Country Name': 'Tanzania',
  'Capital': 'Dodoma',
  'Population': '41892895',
  'Area': '945087.0'},
 {'Country Name': 'U.S. Minor Outlying Islands',
  'Capital': 'None',
  'Population': '0',
  'Area': '0.0'},
 {'Country Name': 'Uzbekistan',
  'Capital': 'Tashkent',
  'Population': '27865738',
  'Area': '447400.0'},
 {'Country Name': 'Venezuela',
  'Capital': 'Caracas',
  'Population': '27223228',
  'Area': '912050.0'},
 {'Country Name': 'Vietnam',
  'Capital': 'Hanoi',
  'Population': '89571130',
  'Area': '329560.0'},
 {'Country Name': 'Samoa',
  'Capital': 'Apia',
  'Population': '192001',
  'Area': '2944.0'},
 {'Country Name': 'Mayotte',
  'Capital': 'Mamoudzou',
  'Population': '159042',
  'Area': '374.0'},
 {'Country Name': 'Zimbabwe',
  'Capital': 'Harare',
  'Population': '11651858',
  'Area': '390580.0'}]

In [112]:
df = pd.DataFrame(dl)
df

           Country Name           Capital Population       Area
0               Andorra  Andorra la Vella      84000      468.0
1   Antigua and Barbuda        St. John's      86754      443.0
2               Armenia           Yerevan    2968000    29800.0
3             Argentina      Buenos Aires   41343201  2766890.0
4             Australia          Canberra   21515754  7686850.0
..                  ...               ...        ...        ...
79            Venezuela           Caracas   27223228   912050.0
80              Vietnam             Hanoi   89571130   329560.0
81                Samoa              Apia     192001     2944.0
82              Mayotte         Mamoudzou     159042      374.0
83             Zimbabwe            Harare   11651858   390580.0

[84 rows x 4 columns]

In [113]:
df.to_csv("scrapthissite_q5.4.csv" , index = False)

### 5.5 Extract country details of a Second column of a page & save into csv file.

In [100]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r = requests.get("https://www.scrapethissite.com/pages/simple/")
r.status_code

200

In [101]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>

In [ ]:
sec = soup.find_all("div" , class_ = "col-md-4 country")

In [114]:
col2_data = sec[1::3]
col2_data

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ci"></i>
                             Ivory Coast
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yamoussoukro</span><br/>
 <strong>Population:</strong> <span class="country-population">21058798</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">322460.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cm"></i>
                             Cameroon
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yaoundé</span><br/>
 <strong>Population:</strong> <span class="country-population">19294149</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">475440.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cr"></i>
                             Costa Rica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">San José</span><br/>
 <strong>Population:</strong> <span class="country-population">4516220</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51100.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cw"></i>
                             Curacao
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Willemstad</span><br/>
 <strong>Population:</strong> <span class="country-population">141766</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">444.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cz"></i>
                             Czech Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Prague</span><br/>
 <strong>Population:</strong> <span class="country-population">10476000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">78866.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dk"></i>
                             Denmark
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Copenhagen</span><br/>
 <strong>Population:</strong> <span class="country-population">5484000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">43094.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dz"></i>
                             Algeria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Algiers</span><br/>
 <strong>Population:</strong> <span class="country-population">34586184</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2381740.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eg"></i>
                             Egypt
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Cairo</span><br/>
 <strong>Population:</strong> <span class="country-population">80471869</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1001450.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-es"></i>
                             Spain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Madrid</span><br/>
 <strong>Population:</strong> <span class="country-population">46505963</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">504782.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fj"></i>
                             Fiji
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Suva</span><br/>
 <strong>Population:</strong> <span class="country-population">875983</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">18270.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fo"></i>
                             Faroe Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tórshavn</span><br/>
 <strong>Population:</strong> <span class="country-population">48228</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1399.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gb"></i>
                             United Kingdom
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">London</span><br/>
 <strong>Population:</strong> <span class="country-population">62348447</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">244820.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gf"></i>
                             French Guiana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Cayenne</span><br/>
 <strong>Population:</strong> <span class="country-population">195506</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">91000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gi"></i>
                             Gibraltar
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gibraltar</span><br/>
 <strong>Population:</strong> <span class="country-population">27884</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">6.5</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gn"></i>
                             Guinea
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Conakry</span><br/>
 <strong>Population:</strong> <span class="country-population">10324025</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">245857.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gr"></i>
                             Greece
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Athens</span><br/>
 <strong>Population:</strong> <span class="country-population">11000000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">131940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gu"></i>
                             Guam
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hagåtña</span><br/>
 <strong>Population:</strong> <span class="country-population">159358</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">549.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hk"></i>
                             Hong Kong
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hong Kong</span><br/>
 <strong>Population:</strong> <span class="country-population">6898686</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1092.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hr"></i>
                             Croatia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Zagreb</span><br/>
 <strong>Population:</strong> <span class="country-population">4491000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">56542.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-id"></i>
                             Indonesia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Jakarta</span><br/>
 <strong>Population:</strong> <span class="country-population">242968342</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1919440.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-im"></i>
                             Isle of Man
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Douglas</span><br/>
 <strong>Population:</strong> <span class="country-population">75049</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">572.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-iq"></i>
                             Iraq
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baghdad</span><br/>
 <strong>Population:</strong> <span class="country-population">29671605</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">437072.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-it"></i>
                             Italy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Rome</span><br/>
 <strong>Population:</strong> <span class="country-population">60340328</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">301230.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jo"></i>
                             Jordan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Amman</span><br/>
 <strong>Population:</strong> <span class="country-population">6407085</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">92300.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kg"></i>
                             Kyrgyzstan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bishkek</span><br/>
 <strong>Population:</strong> <span class="country-population">5776500</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">198500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-km"></i>
                             Comoros
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Moroni</span><br/>
 <strong>Population:</strong> <span class="country-population">773407</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2170.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kr"></i>
                             South Korea
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Seoul</span><br/>
 <strong>Population:</strong> <span class="country-population">48422644</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">98480.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kz"></i>
                             Kazakhstan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Astana</span><br/>
 <strong>Population:</strong> <span class="country-population">15340000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2717300.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lc"></i>
                             Saint Lucia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Castries</span><br/>
 <strong>Population:</strong> <span class="country-population">160922</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">616.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lr"></i>

In [115]:
dl = []
for divs in col2_data:
    
    data = {
    "Country Name" : "" ,
    "Capital" : "" ,
    "Population" : "" ,
    "Area" : ""
    }
    data["Country Name"] = divs.find("h3" , class_="country-name").text.strip()
    data["Capital"] = divs.find("span" , class_ = "country-capital").text.strip()
    data["Population"] = divs.find("span" , class_ = "country-population").text
    data["Area"] = divs.find("span" , class_ = "country-area").text.strip()
    dl.append(data)
dl

[{'Country Name': 'United Arab Emirates',
  'Capital': 'Abu Dhabi',
  'Population': '4975593',
  'Area': '82880.0'},
 {'Country Name': 'Anguilla',
  'Capital': 'The Valley',
  'Population': '13254',
  'Area': '102.0'},
 {'Country Name': 'Angola',
  'Capital': 'Luanda',
  'Population': '13068161',
  'Area': '1246700.0'},
 {'Country Name': 'American Samoa',
  'Capital': 'Pago Pago',
  'Population': '57881',
  'Area': '199.0'},
 {'Country Name': 'Aruba',
  'Capital': 'Oranjestad',
  'Population': '71566',
  'Area': '193.0'},
 {'Country Name': 'Bosnia and Herzegovina',
  'Capital': 'Sarajevo',
  'Population': '4590000',
  'Area': '51129.0'},
 {'Country Name': 'Belgium',
  'Capital': 'Brussels',
  'Population': '10403000',
  'Area': '30510.0'},
 {'Country Name': 'Bahrain',
  'Capital': 'Manama',
  'Population': '738004',
  'Area': '665.0'},
 {'Country Name': 'Saint Barthélemy',
  'Capital': 'Gustavia',
  'Population': '8450',
  'Area': '21.0'},
 {'Country Name': 'Bolivia',
  'Capital': 'Sucre',
  'Population': '9947418',
  'Area': '1098580.0'},
 {'Country Name': 'Bahamas',
  'Capital': 'Nassau',
  'Population': '301790',
  'Area': '13940.0'},
 {'Country Name': 'Botswana',
  'Capital': 'Gaborone',
  'Population': '2029307',
  'Area': '600370.0'},
 {'Country Name': 'Canada',
  'Capital': 'Ottawa',
  'Population': '33679000',
  'Area': '9984670.0'},
 {'Country Name': 'Central African Republic',
  'Capital': 'Bangui',
  'Population': '4844927',
  'Area': '622984.0'},
 {'Country Name': 'Ivory Coast',
  'Capital': 'Yamoussoukro',
  'Population': '21058798',
  'Area': '322460.0'},
 {'Country Name': 'Cameroon',
  'Capital': 'Yaoundé',
  'Population': '19294149',
  'Area': '475440.0'},
 {'Country Name': 'Costa Rica',
  'Capital': 'San José',
  'Population': '4516220',
  'Area': '51100.0'},
 {'Country Name': 'Curacao',
  'Capital': 'Willemstad',
  'Population': '141766',
  'Area': '444.0'},
 {'Country Name': 'Czech Republic',
  'Capital': 'Prague',
  'Population': '10476000',
  'Area': '78866.0'},
 {'Country Name': 'Denmark',
  'Capital': 'Copenhagen',
  'Population': '5484000',
  'Area': '43094.0'},
 {'Country Name': 'Algeria',
  'Capital': 'Algiers',
  'Population': '34586184',
  'Area': '2381740.0'},
 {'Country Name': 'Egypt',
  'Capital': 'Cairo',
  'Population': '80471869',
  'Area': '1001450.0'},
 {'Country Name': 'Spain',
  'Capital': 'Madrid',
  'Population': '46505963',
  'Area': '504782.0'},
 {'Country Name': 'Fiji',
  'Capital': 'Suva',
  'Population': '875983',
  'Area': '18270.0'},
 {'Country Name': 'Faroe Islands',
  'Capital': 'Tórshavn',
  'Population': '48228',
  'Area': '1399.0'},
 {'Country Name': 'United Kingdom',
  'Capital': 'London',
  'Population': '62348447',
  'Area': '244820.0'},
 {'Country Name': 'French Guiana',
  'Capital': 'Cayenne',
  'Population': '195506',
  'Area': '91000.0'},
 {'Country Name': 'Gibraltar',
  'Capital': 'Gibraltar',
  'Population': '27884',
  'Area': '6.5'},
 {'Country Name': 'Guinea',
  'Capital': 'Conakry',
  'Population': '10324025',
  'Area': '245857.0'},
 {'Country Name': 'Greece',
  'Capital': 'Athens',
  'Population': '11000000',
  'Area': '131940.0'},
 {'Country Name': 'Guam',
  'Capital': 'Hagåtña',
  'Population': '159358',
  'Area': '549.0'},
 {'Country Name': 'Hong Kong',
  'Capital': 'Hong Kong',
  'Population': '6898686',
  'Area': '1092.0'},
 {'Country Name': 'Croatia',
  'Capital': 'Zagreb',
  'Population': '4491000',
  'Area': '56542.0'},
 {'Country Name': 'Indonesia',
  'Capital': 'Jakarta',
  'Population': '242968342',
  'Area': '1919440.0'},
 {'Country Name': 'Isle of Man',
  'Capital': 'Douglas',
  'Population': '75049',
  'Area': '572.0'},
 {'Country Name': 'Iraq',
  'Capital': 'Baghdad',
  'Population': '29671605',
  'Area': '437072.0'},
 {'Country Name': 'Italy',
  'Capital': 'Rome',
  'Population': '60340328',
  'Area': '301230.0'},
 {'Country Name': 'Jordan',
  'Capital': 'Amman',
  'Population': '6407085',
  'Area': '92300.0'},
 {'Country Name': 'Kyrgyzstan',
  'Capital': 'Bishkek',
  'Population': '5776500',
  'Area': '198500.0'},
 {'Country Name': 'Comoros',
  'Capital': 'Moroni',
  'Population': '773407',
  'Area': '2170.0'},
 {'Country Name': 'South Korea',
  'Capital': 'Seoul',
  'Population': '48422644',
  'Area': '98480.0'},
 {'Country Name': 'Kazakhstan',
  'Capital': 'Astana',
  'Population': '15340000',
  'Area': '2717300.0'},
 {'Country Name': 'Saint Lucia',
  'Capital': 'Castries',
  'Population': '160922',
  'Area': '616.0'},
 {'Country Name': 'Liberia',
  'Capital': 'Monrovia',
  'Population': '3685076',
  'Area': '111370.0'},
 {'Country Name': 'Luxembourg',
  'Capital': 'Luxembourg',
  'Population': '497538',
  'Area': '2586.0'},
 {'Country Name': 'Morocco',
  'Capital': 'Rabat',
  'Population': '31627428',
  'Area': '446550.0'},
 {'Country Name': 'Montenegro',
  'Capital': 'Podgorica',
  'Population': '666730',
  'Area': '14026.0'},
 {'Country Name': 'Marshall Islands',
  'Capital': 'Majuro',
  'Population': '65859',
  'Area': '181.3'},
 {'Country Name': 'Myanmar [Burma]',
  'Capital': 'Naypyitaw',
  'Population': '53414374',
  'Area': '678500.0'},
 {'Country Name': 'Northern Mariana Islands',
  'Capital': 'Saipan',
  'Population': '53883',
  'Area': '477.0'},
 {'Country Name': 'Montserrat',
  'Capital': 'Plymouth',
  'Population': '9341',
  'Area': '102.0'},
 {'Country Name': 'Maldives',
  'Capital': 'Malé',
  'Population': '395650',
  'Area': '300.0'},
 {'Country Name': 'Malaysia',
  'Capital': 'Kuala Lumpur',
  'Population': '28274729',
  'Area': '329750.0'},
 {'Country Name': 'New Caledonia',
  'Capital': 'Noumea',
  'Population': '216494',
  'Area': '19060.0'},
 {'Country Name': 'Nigeria',
  'Capital': 'Abuja',
  'Population': '154000000',
  'Area': '923768.0'},
 {'Country Name': 'Norway',
  'Capital': 'Oslo',
  'Population': '5009150',
  'Area': '324220.0'},
 {'Country Name': 'Niue',
  'Capital': 'Alofi',
  'Population': '2166',
  'Area': '260.0'},
 {'Country Name': 'Panama',
  'Capital': 'Panama City',
  'Population': '3410676',
  'Area': '78200.0'},
 {'Country Name': 'Papua New Guinea',
  'Capital': 'Port Moresby',
  'Population': '6064515',
  'Area': '462840.0'},
 {'Country Name': 'Poland',
  'Capital': 'Warsaw',
  'Population': '38500000',
  'Area': '312685.0'},
 {'Country Name': 'Puerto Rico',
  'Capital': 'San Juan',
  'Population': '3916632',
  'Area': '9104.0'},
 {'Country Name': 'Palau',
  'Capital': 'Melekeok',
  'Population': '19907',
  'Area': '458.0'},
 {'Country Name': 'Réunion',
  'Capital': 'Saint-Denis',
  'Population': '776948',
  'Area': '2517.0'},
 {'Country Name': 'Russia',
  'Capital': 'Moscow',
  'Population': '140702000',
  'Area': '1.71E7'},
 {'Country Name': 'Solomon Islands',
  'Capital': 'Honiara',
  'Population': '559198',
  'Area': '28450.0'},
 {'Country Name': 'Sweden',
  'Capital': 'Stockholm',
  'Population': '9828655',
  'Area': '449964.0'},
 {'Country Name': 'Slovenia',
  'Capital': 'Ljubljana',
  'Population': '2007000',
  'Area': '20273.0'},
 {'Country Name': 'Sierra Leone',
  'Capital': 'Freetown',
  'Population': '5245695',
  'Area': '71740.0'},
 {'Country Name': 'Somalia',
  'Capital': 'Mogadishu',
  'Population': '10112453',
  'Area': '637657.0'},
 {'Country Name': 'São Tomé and Príncipe',
  'Capital': 'São Tomé',
  'Population': '175808',
  'Area': '1001.0'},
 {'Country Name': 'Syria',
  'Capital': 'Damascus',
  'Population': '22198110',
  'Area': '185180.0'},
 {'Country Name': 'Chad',
  'Capital': "N'Djamena",
  'Population': '10543464',
  'Area': '1284000.0'},
 {'Country Name': 'Thailand',
  'Capital': 'Bangkok',
  'Population': '67089500',
  'Area': '514000.0'},
 {'Country Name': 'East Timor',
  'Capital': 'Dili',
  'Population': '1154625',
  'Area': '15007.0'},
 {'Country Name': 'Tonga',
  'Capital': "Nuku'alofa",
  'Population': '122580',
  'Area': '748.0'},
 {'Country Name': 'Tuvalu',
  'Capital': 'Funafuti',
  'Population': '10472',
  'Area': '26.0'},
 {'Country Name': 'Ukraine',
  'Capital': 'Kiev',
  'Population': '45415596',
  'Area': '603700.0'},
 {'Country Name': 'United States',
  'Capital': 'Washington',
  'Population': '310232863',
  'Area': '9629091.0'},
 {'Country Name': 'Vatican City',
  'Capital': 'Vatican City',
  'Population': '921',
  'Area': '0.44'},
 {'Country Name': 'British Virgin Islands',
  'Capital': 'Road Town',
  'Population': '21730',
  'Area': '153.0'},
 {'Country Name': 'Vanuatu',
  'Capital': 'Port Vila',
  'Population': '221552',
  'Area': '12200.0'},
 {'Country Name': 'Kosovo',
  'Capital': 'Pristina',
  'Population': '1800000',
  'Area': '10908.0'},
 {'Country Name': 'South Africa',
  'Capital': 'Pretoria',
  'Population': '49000000',
  'Area': '1219912.0'}]

In [116]:
df = pd.DataFrame(dl)
df.to_csv("scrapthssite_q5.5.csv" , index = False)

### 5.6 Extract country details of a Third column of a page & save into csv file.

In [117]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r = requests.get("https://www.scrapethissite.com/pages/simple/")
r.status_code

200

In [118]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>

In [119]:
sec = soup.find_all("div" , class_ = "col-md-4 country")

In [121]:
col3_data = sec[2::3]
col3_data

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ck"></i>
                             Cook Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Avarua</span><br/>
 <strong>Population:</strong> <span class="country-population">21388</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">240.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cn"></i>
                             China
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Beijing</span><br/>
 <strong>Population:</strong> <span class="country-population">1330044000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9596960.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cu"></i>
                             Cuba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Havana</span><br/>
 <strong>Population:</strong> <span class="country-population">11423000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110860.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cx"></i>
                             Christmas Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Flying Fish Cove</span><br/>
 <strong>Population:</strong> <span class="country-population">1500</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">135.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-de"></i>
                             Germany
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Berlin</span><br/>
 <strong>Population:</strong> <span class="country-population">81802257</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">357021.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dm"></i>
                             Dominica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Roseau</span><br/>
 <strong>Population:</strong> <span class="country-population">72813</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">754.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ec"></i>
                             Ecuador
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Quito</span><br/>
 <strong>Population:</strong> <span class="country-population">14790608</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">283560.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eh"></i>
                             Western Sahara
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Laâyoune / El Aaiún</span><br/>
 <strong>Population:</strong> <span class="country-population">273008</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">266000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-et"></i>
                             Ethiopia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Addis Ababa</span><br/>
 <strong>Population:</strong> <span class="country-population">88013491</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1127127.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fk"></i>
                             Falkland Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Stanley</span><br/>
 <strong>Population:</strong> <span class="country-population">2638</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">12173.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fr"></i>
                             France
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Paris</span><br/>
 <strong>Population:</strong> <span class="country-population">64768389</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">547030.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gd"></i>
                             Grenada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. George's</span><br/>
 <strong>Population:</strong> <span class="country-population">107818</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">344.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gg"></i>
                             Guernsey
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St Peter Port</span><br/>
 <strong>Population:</strong> <span class="country-population">65228</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">78.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gl"></i>
                             Greenland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nuuk</span><br/>
 <strong>Population:</strong> <span class="country-population">56375</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2166086.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gp"></i>
                             Guadeloupe
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Basse-Terre</span><br/>
 <strong>Population:</strong> <span class="country-population">443000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1780.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gs"></i>
                             South Georgia and the South Sandwich Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Grytviken</span><br/>
 <strong>Population:</strong> <span class="country-population">30</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">3903.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gw"></i>
                             Guinea-Bissau
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bissau</span><br/>
 <strong>Population:</strong> <span class="country-population">1565126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">36120.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hm"></i>
                             Heard Island and McDonald Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">412.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ht"></i>
                             Haiti
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Port-au-Prince</span><br/>
 <strong>Population:</strong> <span class="country-population">9648924</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27750.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ie"></i>
                             Ireland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dublin</span><br/>
 <strong>Population:</strong> <span class="country-population">4622917</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">70280.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-in"></i>
                             India
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">New Delhi</span><br/>
 <strong>Population:</strong> <span class="country-population">1173108018</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">3287590.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ir"></i>
                             Iran
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tehran</span><br/>
 <strong>Population:</strong> <span class="country-population">76923300</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1648000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-je"></i>
                             Jersey
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Saint Helier</span><br/>
 <strong>Population:</strong> <span class="country-population">90812</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">116.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jp"></i>
                             Japan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tokyo</span><br/>
 <strong>Population:</strong> <span class="country-population">127288000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">377835.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kh"></i>
                             Cambodia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Phnom Penh</span><br/>
 <strong>Population:</strong> <span class="country-population">14453680</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">181040.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kn"></i>
                             Saint Kitts and Nevis
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Basseterre</span><br/>
 <strong>Population:</strong> <span class="country-population">51134</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">261.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kw"></i>
                             Kuwait
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kuwait City</span><br/>
 <strong>Population:</strong> <span class="country-population">2789132</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">17820.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-la"></i>
                             Laos
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vientiane</span><br/>
 <strong>Population:</strong> <span class="country-population">6368162</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">236800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-li"></i>
                             Liechtenstein
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vaduz</span><br/>
 <strong>Population:</strong> <span class="country-population">35000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">160.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">

In [122]:
dl = []
for divs in col3_data:
    
    data = {
    "Country Name" : "" ,
    "Capital" : "" ,
    "Population" : "" ,
    "Area" : ""
    }
    data["Country Name"] = divs.find("h3" , class_="country-name").text.strip()
    data["Capital"] = divs.find("span" , class_ = "country-capital").text.strip()
    data["Population"] = divs.find("span" , class_ = "country-population").text
    data["Area"] = divs.find("span" , class_ = "country-area").text.strip()
    dl.append(data)
dl

[{'Country Name': 'Afghanistan',
  'Capital': 'Kabul',
  'Population': '29121286',
  'Area': '647500.0'},
 {'Country Name': 'Albania',
  'Capital': 'Tirana',
  'Population': '2986952',
  'Area': '28748.0'},
 {'Country Name': 'Antarctica',
  'Capital': 'None',
  'Population': '0',
  'Area': '1.4E7'},
 {'Country Name': 'Austria',
  'Capital': 'Vienna',
  'Population': '8205000',
  'Area': '83858.0'},
 {'Country Name': 'Åland',
  'Capital': 'Mariehamn',
  'Population': '26711',
  'Area': '1580.0'},
 {'Country Name': 'Barbados',
  'Capital': 'Bridgetown',
  'Population': '285653',
  'Area': '431.0'},
 {'Country Name': 'Burkina Faso',
  'Capital': 'Ouagadougou',
  'Population': '16241811',
  'Area': '274200.0'},
 {'Country Name': 'Burundi',
  'Capital': 'Bujumbura',
  'Population': '9863117',
  'Area': '27830.0'},
 {'Country Name': 'Bermuda',
  'Capital': 'Hamilton',
  'Population': '65365',
  'Area': '53.0'},
 {'Country Name': 'Bonaire',
  'Capital': 'Kralendijk',
  'Population': '18012',
  'Area': '328.0'},
 {'Country Name': 'Bhutan',
  'Capital': 'Thimphu',
  'Population': '699847',
  'Area': '47000.0'},
 {'Country Name': 'Belarus',
  'Capital': 'Minsk',
  'Population': '9685000',
  'Area': '207600.0'},
 {'Country Name': 'Cocos [Keeling] Islands',
  'Capital': 'West Island',
  'Population': '628',
  'Area': '14.0'},
 {'Country Name': 'Republic of the Congo',
  'Capital': 'Brazzaville',
  'Population': '3039126',
  'Area': '342000.0'},
 {'Country Name': 'Cook Islands',
  'Capital': 'Avarua',
  'Population': '21388',
  'Area': '240.0'},
 {'Country Name': 'China',
  'Capital': 'Beijing',
  'Population': '1330044000',
  'Area': '9596960.0'},
 {'Country Name': 'Cuba',
  'Capital': 'Havana',
  'Population': '11423000',
  'Area': '110860.0'},
 {'Country Name': 'Christmas Island',
  'Capital': 'Flying Fish Cove',
  'Population': '1500',
  'Area': '135.0'},
 {'Country Name': 'Germany',
  'Capital': 'Berlin',
  'Population': '81802257',
  'Area': '357021.0'},
 {'Country Name': 'Dominica',
  'Capital': 'Roseau',
  'Population': '72813',
  'Area': '754.0'},
 {'Country Name': 'Ecuador',
  'Capital': 'Quito',
  'Population': '14790608',
  'Area': '283560.0'},
 {'Country Name': 'Western Sahara',
  'Capital': 'Laâyoune / El Aaiún',
  'Population': '273008',
  'Area': '266000.0'},
 {'Country Name': 'Ethiopia',
  'Capital': 'Addis Ababa',
  'Population': '88013491',
  'Area': '1127127.0'},
 {'Country Name': 'Falkland Islands',
  'Capital': 'Stanley',
  'Population': '2638',
  'Area': '12173.0'},
 {'Country Name': 'France',
  'Capital': 'Paris',
  'Population': '64768389',
  'Area': '547030.0'},
 {'Country Name': 'Grenada',
  'Capital': "St. George's",
  'Population': '107818',
  'Area': '344.0'},
 {'Country Name': 'Guernsey',
  'Capital': 'St Peter Port',
  'Population': '65228',
  'Area': '78.0'},
 {'Country Name': 'Greenland',
  'Capital': 'Nuuk',
  'Population': '56375',
  'Area': '2166086.0'},
 {'Country Name': 'Guadeloupe',
  'Capital': 'Basse-Terre',
  'Population': '443000',
  'Area': '1780.0'},
 {'Country Name': 'South Georgia and the South Sandwich Islands',
  'Capital': 'Grytviken',
  'Population': '30',
  'Area': '3903.0'},
 {'Country Name': 'Guinea-Bissau',
  'Capital': 'Bissau',
  'Population': '1565126',
  'Area': '36120.0'},
 {'Country Name': 'Heard Island and McDonald Islands',
  'Capital': 'None',
  'Population': '0',
  'Area': '412.0'},
 {'Country Name': 'Haiti',
  'Capital': 'Port-au-Prince',
  'Population': '9648924',
  'Area': '27750.0'},
 {'Country Name': 'Ireland',
  'Capital': 'Dublin',
  'Population': '4622917',
  'Area': '70280.0'},
 {'Country Name': 'India',
  'Capital': 'New Delhi',
  'Population': '1173108018',
  'Area': '3287590.0'},
 {'Country Name': 'Iran',
  'Capital': 'Tehran',
  'Population': '76923300',
  'Area': '1648000.0'},
 {'Country Name': 'Jersey',
  'Capital': 'Saint Helier',
  'Population': '90812',
  'Area': '116.0'},
 {'Country Name': 'Japan',
  'Capital': 'Tokyo',
  'Population': '127288000',
  'Area': '377835.0'},
 {'Country Name': 'Cambodia',
  'Capital': 'Phnom Penh',
  'Population': '14453680',
  'Area': '181040.0'},
 {'Country Name': 'Saint Kitts and Nevis',
  'Capital': 'Basseterre',
  'Population': '51134',
  'Area': '261.0'},
 {'Country Name': 'Kuwait',
  'Capital': 'Kuwait City',
  'Population': '2789132',
  'Area': '17820.0'},
 {'Country Name': 'Laos',
  'Capital': 'Vientiane',
  'Population': '6368162',
  'Area': '236800.0'},
 {'Country Name': 'Liechtenstein',
  'Capital': 'Vaduz',
  'Population': '35000',
  'Area': '160.0'},
 {'Country Name': 'Lesotho',
  'Capital': 'Maseru',
  'Population': '1919552',
  'Area': '30355.0'},
 {'Country Name': 'Latvia',
  'Capital': 'Riga',
  'Population': '2217969',
  'Area': '64589.0'},
 {'Country Name': 'Monaco',
  'Capital': 'Monaco',
  'Population': '32965',
  'Area': '1.95'},
 {'Country Name': 'Saint Martin',
  'Capital': 'Marigot',
  'Population': '35925',
  'Area': '53.0'},
 {'Country Name': 'Macedonia',
  'Capital': 'Skopje',
  'Population': '2062294',
  'Area': '25333.0'},
 {'Country Name': 'Mongolia',
  'Capital': 'Ulan Bator',
  'Population': '3086918',
  'Area': '1565000.0'},
 {'Country Name': 'Martinique',
  'Capital': 'Fort-de-France',
  'Population': '432900',
  'Area': '1100.0'},
 {'Country Name': 'Malta',
  'Capital': 'Valletta',
  'Population': '403000',
  'Area': '316.0'},
 {'Country Name': 'Malawi',
  'Capital': 'Lilongwe',
  'Population': '15447500',
  'Area': '118480.0'},
 {'Country Name': 'Mozambique',
  'Capital': 'Maputo',
  'Population': '22061451',
  'Area': '801590.0'},
 {'Country Name': 'Niger',
  'Capital': 'Niamey',
  'Population': '15878271',
  'Area': '1267000.0'},
 {'Country Name': 'Nicaragua',
  'Capital': 'Managua',
  'Population': '5995928',
  'Area': '129494.0'},
 {'Country Name': 'Nepal',
  'Capital': 'Kathmandu',
  'Population': '28951852',
  'Area': '140800.0'},
 {'Country Name': 'New Zealand',
  'Capital': 'Wellington',
  'Population': '4252277',
  'Area': '268680.0'},
 {'Country Name': 'Peru',
  'Capital': 'Lima',
  'Population': '29907003',
  'Area': '1285220.0'},
 {'Country Name': 'Philippines',
  'Capital': 'Manila',
  'Population': '99900177',
  'Area': '300000.0'},
 {'Country Name': 'Saint Pierre and Miquelon',
  'Capital': 'Saint-Pierre',
  'Population': '7012',
  'Area': '242.0'},
 {'Country Name': 'Palestine',
  'Capital': 'None',
  'Population': '3800000',
  'Area': '5970.0'},
 {'Country Name': 'Paraguay',
  'Capital': 'Asunción',
  'Population': '6375830',
  'Area': '406750.0'},
 {'Country Name': 'Romania',
  'Capital': 'Bucharest',
  'Population': '21959278',
  'Area': '237500.0'},
 {'Country Name': 'Rwanda',
  'Capital': 'Kigali',
  'Population': '11055976',
  'Area': '26338.0'},
 {'Country Name': 'Seychelles',
  'Capital': 'Victoria',
  'Population': '88340',
  'Area': '455.0'},
 {'Country Name': 'Singapore',
  'Capital': 'Singapore',
  'Population': '4701069',
  'Area': '692.7'},
 {'Country Name': 'Svalbard and Jan Mayen',
  'Capital': 'Longyearbyen',
  'Population': '2550',
  'Area': '62049.0'},
 {'Country Name': 'San Marino',
  'Capital': 'San Marino',
  'Population': '31477',
  'Area': '61.2'},
 {'Country Name': 'Suriname',
  'Capital': 'Paramaribo',
  'Population': '492829',
  'Area': '163270.0'},
 {'Country Name': 'El Salvador',
  'Capital': 'San Salvador',
  'Population': '6052064',
  'Area': '21040.0'},
 {'Country Name': 'Swaziland',
  'Capital': 'Mbabane',
  'Population': '1354051',
  'Area': '17363.0'},
 {'Country Name': 'French Southern Territories',
  'Capital': 'Port-aux-Français',
  'Population': '140',
  'Area': '7829.0'},
 {'Country Name': 'Tajikistan',
  'Capital': 'Dushanbe',
  'Population': '7487489',
  'Area': '143100.0'},
 {'Country Name': 'Turkmenistan',
  'Capital': 'Ashgabat',
  'Population': '4940916',
  'Area': '488100.0'},
 {'Country Name': 'Turkey',
  'Capital': 'Ankara',
  'Population': '77804122',
  'Area': '780580.0'},
 {'Country Name': 'Taiwan',
  'Capital': 'Taipei',
  'Population': '22894384',
  'Area': '35980.0'},
 {'Country Name': 'Uganda',
  'Capital': 'Kampala',
  'Population': '33398682',
  'Area': '236040.0'},
 {'Country Name': 'Uruguay',
  'Capital': 'Montevideo',
  'Population': '3477000',
  'Area': '176220.0'},
 {'Country Name': 'Saint Vincent and the Grenadines',
  'Capital': 'Kingstown',
  'Population': '104217',
  'Area': '389.0'},
 {'Country Name': 'U.S. Virgin Islands',
  'Capital': 'Charlotte Amalie',
  'Population': '108708',
  'Area': '352.0'},
 {'Country Name': 'Wallis and Futuna',
  'Capital': 'Mata-Utu',
  'Population': '16025',
  'Area': '274.0'},
 {'Country Name': 'Yemen',
  'Capital': 'Sanaa',
  'Population': '23495361',
  'Area': '527970.0'},
 {'Country Name': 'Zambia',
  'Capital': 'Lusaka',
  'Population': '13460305',
  'Area': '752614.0'}]

In [123]:
df = pd.DataFrame(dl)
df

                        Country Name           Capital Population      Area
0                        Afghanistan             Kabul   29121286  647500.0
1                            Albania            Tirana    2986952   28748.0
2                         Antarctica              None          0     1.4E7
3                            Austria            Vienna    8205000   83858.0
4                              Åland         Mariehamn      26711    1580.0
..                               ...               ...        ...       ...
78  Saint Vincent and the Grenadines         Kingstown     104217     389.0
79               U.S. Virgin Islands  Charlotte Amalie     108708     352.0
80                 Wallis and Futuna          Mata-Utu      16025     274.0
81                             Yemen             Sanaa   23495361  527970.0
82                            Zambia            Lusaka   13460305  752614.0

[83 rows x 4 columns]

In [125]:
df.to_csv("scrapthissite_q5.6" , index = False)