# .4 Extract all product details from second page & save into another csv file.

	# 4.1 Extract first product details save into csv file. e.g# Packard 255 G2

In [3]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops")



soup = BeautifulSoup(driver.page_source, 'html.parser')
soup
product = soup.find('div',class_='product-wrapper card-body')
product
list = []
prod_dictionary = {
    'product_name': '',
    'product_link': '',
    'product_img': '',
    'product_price': '',
    'product_details': '',
    'product_reviews_number': '',
    'product_reviews_star_number': '',
}
prod_dictionary['product_name']= product.find('a').text.strip()
prod_dictionary['product_details']=product.find('p').text
prod_dictionary['product_img']=product.find('img')['src']
prod_dictionary['product_link']=product.find('a')['href']
prod_dictionary['product_reviews_number']=product.find('div',class_='ratings').text.strip()
prod_dictionary['product_reviews_star_number']
prod_dictionary['product_price']=product.find('h4').text.strip()
list.append(prod_dictionary)
prod_dictionary

{'product_name': 'Asus VivoBook X4',
 'product_link': '/test-sites/e-commerce/ajax/product/60',
 'product_img': '/images/test-sites/e-commerce/items/cart2.png',
 'product_price': '$295.99',
 'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
 'product_reviews_number': '1 reviews',
 'product_reviews_star_number': ''}

	# 4.2 Extract product details from first row & save into csv file. e.g# Packard 255 G2, Aspire E1-510, ThinkPad T540p

In [2]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops')
time.sleep(3)
driver.find_element("xpath","//button[@class='acceptCookies']").click()
list=[]
for i in range(2,3):
    for btn in driver.find_elements("xpath","//button[@class = 'btn btn-default page-link page']"):
        if btn.text == str(i):
            print("clicking on page:",btn.text)
            btn.click()
            time.sleep(3)
    soup=BeautifulSoup(driver.page_source,'html')
    first_products=soup.find_all('div',class_='col-md-4 col-xl-4 col-lg-4')
    for first_pro in first_products:
        dic={
            'product_name':'',
            'product_link':'',
            'product_img':'',
            'product_price':'',
            'product_details':'',
            'product_reviews_number':'',
            'product_reviews_star_number':'',
        }
        dic['product_name']=first_pro.find('a').text.strip()
        dic['product_link']=first_pro.find('a')['href']
        dic['product_img']=first_pro.find('img')['src']
        dic['product_price']=first_pro.find('h4',class_='price float-end pull-right').text.strip()
        dic['product_details']=first_pro.find('p',class_='card-text description').text.strip()
        dic['product_reviews_number']=first_pro.find('p',class_='review-count float-end pull-right').text.strip()
        list.append(dic)
df=pd.DataFrame(list)
df

clicking on page: 2

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Hewlett Packard,/test-sites/e-commerce/ajax/product/65,/images/test-sites/e-commerce/items/cart2.png,$364.46,"Hewlett Packard 250 G6 Dark Ash Silver, 15.6"" ...",11 reviews,
1,Acer Aspire 3 A3,/test-sites/e-commerce/ajax/product/66,/images/test-sites/e-commerce/items/cart2.png,$372.7,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Celeron...",3 reviews,
2,Acer Aspire A315,/test-sites/e-commerce/ajax/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",3 reviews,
3,Acer Aspire ES1-,/test-sites/e-commerce/ajax/product/68,/images/test-sites/e-commerce/items/cart2.png,$379.95,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",3 reviews,
4,Acer Aspire 3 A3,/test-sites/e-commerce/ajax/product/69,/images/test-sites/e-commerce/items/cart2.png,$391.48,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",3 reviews,
5,Acer Aspire 3 A3,/test-sites/e-commerce/ajax/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",3 reviews,

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
driver = webdriver.Chrome()
driver.get("https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops")
time.sleep(3)
driver.find_element("xpath" , "//button [@ class='acceptCookies']").click()


for btn in driver.find_elements("xpath" , "//button [@ class = 'btn btn-default page-link page']"):
    if btn.text == '2':
        btn.click()
        break

time.sleep(6)

soup = BeautifulSoup(driver.page_source , "html")
print(soup.prettify())

<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script async="" nonce="" src="https://www.googletagmanager.com/gtag/js?id=G-Q9KY1T6XJQ&amp;cx=c&amp;gtm=4e5bj0h2" type="text/javascript">
  </script>
  <script async="" nonce="" src="https://www.google-analytics.com/analytics.js" type="text/javascript">
  </script>
  <script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-NVFPDWB">
  </script>
  <script nonce="">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Ajax | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
  <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
  <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
  <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
  <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
  <link href="/css/app.css?id=f90c5791d7eb09506961d9ee889840b2" rel="stylesheet"/>
  <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
  <link href="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops" rel="canonical"/>
  <meta content="Ajax | Web Scraper Test Sites" property="og:title"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
  <meta content="website" property="og:type"/>
  <meta content="https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops" property="og:url"/>
  <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
  <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
  </script>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-site">
    <div class="row">
     <div class="col-lg-3 sidebar">
      <div class="navbar-light sidebar" role="navigation">
       <div class="sidebar-nav navbar-collapse">
        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
         <li class="nav-item">
          <a class="nav-link" href="/test-sites/e-commerce/ajax" itemprop="url">
           <span itemprop="name">
            Home
           </span>
          </a>
         </li>
         <li class="nav-item active">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/computers" itemprop="url">
           <span itemprop="name">
            Computers
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/ajax/computers/laptops" itemprop="url">
             <span itemprop="name">
              Laptops
             </span>
            </a>
           </li>
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/ajax/computers/tablets" itemprop="url">
             <span itemprop="name">
              Tablets
             </span>
            </a>
           </li>
          </ul>
         </li>
         <li class="nav-item">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/ajax/phones" itemprop="url">
           <span itemprop="name">
            Phones
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
         </li>
        </ul>
       </div>
      </div>
     </div>
     <div class="col-lg-9">
      <h1 class="page-header">
       Computers / Laptops
      </h1>

In [2]:
row = soup.find_all("div" , class_ = "col-md-4 col-xl-4 col-lg-4")
row

[<div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$364.46</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">Hewlett Packard </a></h4><p class="card-text description" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">11</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$372.7</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">Acer Aspire 3 A3</a></h4><p class="card-text description" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">3</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$379.94</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">Acer Aspire A315</a></h4><p class="card-text description" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">3</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$379.95</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">Acer Aspire ES1-</a></h4><p class="card-text description" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">3</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$391.48</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">Acer Aspire 3 A3</a></h4><p class="card-text description" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">3</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>,
 <div class="col-md-4 col-xl-4 col-lg-4"><div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product"><div class="product-wrapper card-body"><img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/><div class="caption"><h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">$393.88</h4><h4><a class="title" href="/test-sites/e-commerce/ajax/product/70" itemprop="name" title="Acer Aspire 3 A315-21">Acer Aspire 3 A3</a></h4><p class="card-text description" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p></div><div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating"><p class="review-count float-end pull-right"><span itemprop="reviewCount">3</span> reviews</p><p><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span><span class="ws-icon ws-icon-star"></span></p></div></div></div></div>]

In [ ]:
import requests
dl = []

for i in range(6):
    p_url = row[i].find("a")["href"]
    b_url = "https://webscraper.io"
    act_url = b_url + p_url

    r1 = requests.get(act_url)
    soup1 = BeautifulSoup (r1.text , "html.parser")

    data = {} 
    data["Product_Name"] = soup1.find("h4" ,class_ = "title card-title").text
    data["Product_Link"] = act_url
    data["Product_Image"] = soup1.find("img" ,class_ = "image img-fluid img-responsive")["src"]
    data["Product_Price"] = soup1.find("h4" , class_ = "price float-end pull-right").text.strip()
    data["Product_Details"] = soup1.find("p" , class_ = "description card-text").text 
    data["Product_Review_No"] = soup1.find("p" , class_ = "review-count").text.strip()
    
    dl.append(data)
dl

[{'Product_Name': 'Hewlett Packard 250 G6 Dark Ash Silver',
  'Product_Link': 'https://webscraper.io/test-sites/e-commerce/ajax/product/65',
  'Product_Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product_Price': '$364.46',
  'Product_Details': 'Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS',
  'Product_Review_No': '12 reviews'},
 {'Product_Name': 'Acer Aspire 3 A315-31 Black',
  'Product_Link': 'https://webscraper.io/test-sites/e-commerce/ajax/product/66',
  'Product_Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product_Price': '$372.7',
  'Product_Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product_Review_No': '2 reviews'},
 {'Product_Name': 'Acer Aspire A315-31-C33J',
  'Product_Link': 'https://webscraper.io/test-sites/e-commerce/ajax/product/67',
  'Product_Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product_Price': '$379.94',
  'Product_Details': 'Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG',
  'Product_Review_No': '0 reviews'},
 {'Product_Name': 'Acer Aspire ES1-572 Black',
  'Product_Link': 'https://webscraper.io/test-sites/e-commerce/ajax/product/68',
  'Product_Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product_Price': '$379.95',
  'Product_Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux',
  'Product_Review_No': '9 reviews'},
 {'Product_Name': 'Acer Aspire 3 A315-31 Black',
  'Product_Link': 'https://webscraper.io/test-sites/e-commerce/ajax/product/69',
  'Product_Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product_Price': '$391.48',
  'Product_Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product_Review_No': '10 reviews'},
 {'Product_Name': 'Acer Aspire 3 A315-21',
  'Product_Link': 'https://webscraper.io/test-sites/e-commerce/ajax/product/70',
  'Product_Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product_Price': '$393.88',
  'Product_Details': 'Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux',
  'Product_Review_No': '9 reviews'}]

In [4]:
df=pd.DataFrame(dl)
df

,Product_Name,Product_Link,Product_Image,Product_Price,Product_Details,Product_Review_No
0,Hewlett Packard 250 G6 Dark Ash Silver,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$364.46,"Hewlett Packard 250 G6 Dark Ash Silver, 15.6"" ...",12 reviews
1,Acer Aspire 3 A315-31 Black,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$372.7,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Celeron...",2 reviews
2,Acer Aspire A315-31-C33J,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",0 reviews
3,Acer Aspire ES1-572 Black,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$379.95,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",9 reviews
4,Acer Aspire 3 A315-31 Black,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$391.48,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",10 reviews
5,Acer Aspire 3 A315-21,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",9 reviews

In [5]:
df.to_csv("question_no_4.csv", index=False)    
df

,Product_Name,Product_Link,Product_Image,Product_Price,Product_Details,Product_Review_No
0,Hewlett Packard 250 G6 Dark Ash Silver,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$364.46,"Hewlett Packard 250 G6 Dark Ash Silver, 15.6"" ...",12 reviews
1,Acer Aspire 3 A315-31 Black,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$372.7,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Celeron...",2 reviews
2,Acer Aspire A315-31-C33J,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",0 reviews
3,Acer Aspire ES1-572 Black,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$379.95,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",9 reviews
4,Acer Aspire 3 A315-31 Black,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$391.48,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",10 reviews
5,Acer Aspire 3 A315-21,https://webscraper.io/test-sites/e-commerce/aj...,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",9 reviews