#  https://www.scrapethissite.com/pages/ajax-javascript/ (Title, Nominations, Awards, Best Picture)
	# 1.1 Extract Table of year 2015 & save into csv file.

In [7]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://www.scrapethissite.com/pages/ajax-javascript/#2015")



soup = BeautifulSoup(driver.page_source, 'html.parser')
soup
dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

}
# soup.find_all('div',class_="col-md-12")[0].find_all('table")[0]
table= soup.find_all('div',class_="col-md-12")[4]
table

rows= table.find_all('tr')[0]
rows
rows= table.find_all('tr',class_='film')
rows
list = []
for i in rows:
    dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

    }
    dict_data['Title']=i.find('td').text

    dict_data['Nominations']=i.find('td',class_='film-nominations').text
    dict_data['Awards']=i.find('td',class_='film-awards').text
    list.append(dict_data)

list
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('scrapthisside_Q_1_1.csv',index=False)
df

,Title,Nominations,Best Picture,Awards
0,Spotlight,6,,2
1,Mad Max: Fury Road,10,,6
2,The Revenant,12,,3
3,Bridge of Spies,6,,1
4,The Big Short,5,,1
5,The Danish Girl,4,,1
6,Room,4,,1
7,Ex Machina,2,,1
8,The Hateful Eight,2,,1
9,Inside Out,2,,1
10,Amy,1,,1
11,Bear Story,1,,1
12,A Girl in the River: The Price of Forgiveness,1,,1
13,Son of Saul,1,,1
14,Spectre,1,,1
15,Stutterer,1,,1

	# 1.2 Extract Table of year 2014 & save into another csv file.

In [10]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://www.scrapethissite.com/pages/ajax-javascript/#2014")



soup = BeautifulSoup(driver.page_source, 'html.parser')
soup
table= soup.find_all('tr',class_='film')
table
list = []
for i in table:
    dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

    }
    dict_data['Title']=i.find('td').text

    dict_data['Nominations']=i.find('td',class_='film-nominations').text
    dict_data['Awards']=i.find('td',class_='film-awards').text
    list.append(dict_data)

list
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('scrapthisside Q1_2.csv',index=False)
df

                               Title Nominations Best Picture Awards
0                            Birdman           9                   4
1           The Grand Budapest Hotel           9                   4
2                           Whiplash           5                   3
3                 The Imitation Game           8                   1
4                    American Sniper           6                   1
5                            Boyhood           6                   1
6                       Interstellar           5                   1
7           The Theory of Everything           5                   1
8                                Ida           2                   1
9                              Selma           2                   1
10                       Citizenfour           1                   1
11                        Big Hero 6           1                   1
12  Crisis Hotline: Veterans Press 1           1                   1
13                    The Phone Call           1                   1
14                       Still Alice           1                   1
15                             Feast           1                   1

	# 1.3 Extract Table of year 2013 & save into another csv file.

In [13]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://www.scrapethissite.com/pages/ajax-javascript/#2013")



soup = BeautifulSoup(driver.page_source, 'html.parser')
soup
dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

}
# soup.find_all('div',class_="col-md-12")[0].find_all('table")[0]
table= soup.find_all('div',class_="col-md-12")[4]
table

rows= table.find_all('tr')[3]
rows
rows= table.find_all('tr',class_='film')
rows
list = []
for i in rows:
    dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

    }
    dict_data['Title']=i.find('td').text

    dict_data['Nominations']=i.find('td',class_='film-nominations').text
    dict_data['Awards']=i.find('td',class_='film-awards').text
    list.append(dict_data)

list
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('scrapthisside_Q_1_1.csv',index=False)
df

                                        Title Nominations Best Picture Awards
0                            12 Years a Slave           9                   3
1                                     Gravity          10                   7
2                          Dallas Buyers Club           6                   3
3                                      Frozen           2                   2
4                            The Great Gatsby           2                   2
5                                         Her           5                   1
6                                Blue Jasmine           3                   1
7                                   Mr Hublot           1                   1
8   The Lady in Number 6: Music Saved My Life           1                   1
9                                      Helium           1                   1
10                           The Great Beauty           1                   1
11                       20 Feet from Stardom           1                   1

	# 1.4 Extract Table of year 2012 & save into another csv file.

In [14]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://www.scrapethissite.com/pages/ajax-javascript/#2012  ")



soup = BeautifulSoup(driver.page_source, 'html.parser')
soup
dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

}
# soup.find_all('div',class_="col-md-12")[0].find_all('table")[0]
table= soup.find_all('div',class_="col-md-12")[4]
table

rows= table.find_all('tr')[3]
rows
rows= table.find_all('tr',class_='film')
rows
list = []
for i in rows:
    dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

    }
    dict_data['Title']=i.find('td').text

    dict_data['Nominations']=i.find('td',class_='film-nominations').text
    dict_data['Awards']=i.find('td',class_='film-awards').text
    list.append(dict_data)

list
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('scrapthisside_Q_1_4.csv',index=False)
df

                      Title Nominations Best Picture Awards
0                      Argo           7                   3
1                Life of Pi          11                   4
2            Les Misérables           8                   3
3                   Lincoln          12                   2
4          Django Unchained           5                   2
5                   Skyfall           5                   2
6   Silver Linings Playbook           8                   1
7          Zero Dark Thirty           5                   1
8                     Amour           5                   1
9             Anna Karenina           4                   1
10                 Paperman           1                   1
11                    Brave           1                   1
12  Searching for Sugar Man           1                   1
13                 Inocente           1                   1
14                   Curfew           1                   1

	# 1.5 Extract Table of year 2011 & save into another csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://www.scrapethissite.com/pages/ajax-javascript/#2011")



soup = BeautifulSoup(driver.page_source, 'html.parser')
soup
dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

}
# soup.find_all('div',class_="col-md-12")[0].find_all('table")[0]
table= soup.find_all('div',class_="col-md-12")[4]
table

rows= table.find_all('tr')[0]
rows
rows= table.find_all('tr',class_='film')
rows
list = []
for i in rows:
    dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

    }
    dict_data['Title']=i.find('td').text

    dict_data['Nominations']=i.find('td',class_='film-nominations').text
    dict_data['Awards']=i.find('td',class_='film-awards').text
    list.append(dict_data)

list
import pandas as pd 
df = pd.DataFrame(list)
df
# df.to_csv('scrapthisside_Q_1_1.csv',index=False)
# df

,Title,Nominations,Best Picture,Awards
0,The Artist,10,,5
1,Hugo,11,,5
2,The Iron Lady,2,,2
3,The Descendants,5,,1
4,The Girl with the Dragon Tattoo,5,,1
5,Midnight in Paris,4,,1
6,The Help,4,,1
7,A Separation,2,,1
8,The Fantastic Flying Books of Mr. Morris Lessmore,1,,1
9,The Shore,1,,1
10,Undefeated,1,,1
11,The Muppets,1,,1
12,Saving Face,1,,1
13,Beginners,1,,1
14,Rango,1,,1

	# 1.6 Extract Table of year 2010 & save into another csv file.

In [17]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://www.scrapethissite.com/pages/ajax-javascript/#2010")



soup = BeautifulSoup(driver.page_source, 'html.parser')
soup
dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

}
# soup.find_all('div',class_="col-md-12")[0].find_all('table")[0]
table= soup.find_all('div',class_="col-md-12")[4]
table

rows= table.find_all('tr')[0]
rows
rows= table.find_all('tr',class_='film')
rows
list = []
for i in rows:
    dict_data = {
    'Title':'',
    'Nominations':'',
    'Best Picture':'',
    'Awards':'',

    }
    dict_data['Title']=i.find('td').text

    dict_data['Nominations']=i.find('td',class_='film-nominations').text
    dict_data['Awards']=i.find('td',class_='film-awards').text
    list.append(dict_data)

list
import pandas as pd 
df = pd.DataFrame(list)
df
# df.to_csv('scrapthisside_Q_1_1.csv',index=False)
# df

                  Title Nominations Best Picture Awards
0     The King's Speech          12                   4
1             Inception           8                   4
2    The Social Network           8                   3
3           The Fighter           7                   2
4           Toy Story 3           5                   2
5   Alice in Wonderland           3                   2
6            Black Swan           5                   1
7     In a Better World           1                   1
8        The Lost Thing           1                   1
9           God of Love           1                   1
10          The Wolfman           1                   1
11    Strangers No More           1                   1
12           Inside Job           1                   1

	# 1.7 Extract Tables from year 2015 to 2010 & save into single csv file.

In [18]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/ajax-javascript/") # to get the url 
driver.get(url)
for j in range(2015,2009,-1): # for inner loop is 15 to 9 datas
    driver.find_element("xpath",f'//a[@id={j}]').click() # difrent file are element to chcek and click to  secand wibsite
    print(j) # print j this is all wibsite data
    time.sleep(3) # this a timer 
    soup = BeautifulSoup(driver.page_source, 'html.parser') # to website html code 
    tbs = soup.find_all('table',class_='table')[0] # to all table find 
    trs = tbs.find_all('tr') # to all find tr
    list=[]
    for i in trs[1:]: # for outer loop dict to control all data 
        dict_data = {
        'Title':'',
        'Nominations':'',
        'Best Picture':'',
        'Awards':'',

        }
        dict_data['Title']=i.find('td').text

        dict_data['Nominations']=i.find('td',class_='film-nominations').text
        dict_data['Awards']=i.find('td',class_='film-awards').text
        list.append(dict_data.copy()) # all data are append to list

        df = pd.DataFrame(list) # to convert to data frame 
        df
        # df.to_csv(f'scrapthisside q7_1{j}.csv',index=False)# to save into csv file 
        # df

2015
2014
2013
2012
2011
2010

	# 1.8 Extract Tables from year 2015 to 2010 & save into single csv file with year column. (year, Title, Nominations, Awards, Best Picture)

In [19]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/ajax-javascript/") # to get the url 
driver.get(url)
list=[]
for j in range(2015,2009,-1): # for inner loop is 15 to 9 datas
    driver.find_element("xpath",f'//a[@id={j}]').click() # difrent file are element to chcek and click to  secand wibsite
    print(j) # print j this is all wibsite data
    time.sleep(3) # this a timer 
    soup = BeautifulSoup(driver.page_source, 'html.parser') # to website html code 
    tbs = soup.find_all('table',class_='table')[0] # to all table find 
    trs = tbs.find_all('tr') # to all find tr
    
    for i in trs[1:]: # for outer loop dict to control all data 
        dict_data = {
        'Title':'',
        'Nominations':'',
        'Best Picture':'',
        'Awards':'',

        }
        dict_data['Title']=i.find('td').text

        dict_data['Nominations']=i.find('td',class_='film-nominations').text
        dict_data['Awards']=i.find('td',class_='film-awards').text
        list.append(dict_data.copy()) # all data are append to list

df = pd.DataFrame(list) # to convert to data frame 
df
# df.to_csv('scrapthisside q8_1.csv',index=False)# to save into csv file 
# df

2015
2014
2013
2012
2011
2010

                  Title Nominations Best Picture Awards
0           Spotlight             6                   2
1   Mad Max: Fury Road           10                   6
2       The Revenant             12                   3
3       Bridge of Spies           6                   1
4       The Big Short             5                   1
..                  ...         ...          ...    ...
86       The Lost Thing           1                   1
87          God of Love           1                   1
88          The Wolfman           1                   1
89    Strangers No More           1                   1
90           Inside Job           1                   1

[91 rows x 4 columns]

# https://www.scrapethissite.com/pages/frames/ (Testudines_name, url,img_url)
	# 2.1 Extract first Testudines details save into csv file. e.g# Carettochelyidae

In [22]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find('div',class_='col-md-4 turtle-family-card')
frm
len(frm)
list =[]
base_url = 'https://www.scrapethissite.com/'
dict = {
    'name':'',
    'url':'',
    'img_url':'',
}
dict ['url']=frm.find('img')['src']
dict ['img_url']=base_url + frm.find('a')['href']
dict ['name']=frm.find('h3').text
list.append(dict)
list
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q2_1.csv',index=False)# to save into csv file 
df

,name,url,img_url
0,Carettochelyidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...

	# 2.2 Extract Testudines family details save into csv file. e.g# Carettochelyidae, Cheloniidae, Chelydridae

In [24]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='row')
frm
list =[]
for i in frm[0:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
    }
    dict ['url']=i.find('img')['src']
    dict ['img_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    list.append(dict)
list
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q2_2.csv',index=False)# to save into csv file 
df

,name,url,img_url
0,Carettochelyidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
1,Dermatemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
2,Geoemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...

# 2.3 Extract all Testudines family details save into csv file.

In [25]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')
frm
list =[]
for i in frm[0:14]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
    }
    dict ['url']=i.find('img')['src']
    dict ['img_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    list.append(dict)
list
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q2_3.csv',index=False)# to save into csv file 
df

,name,url,img_url
0,Carettochelyidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
1,Cheloniidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
2,Chelydridae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
3,Dermatemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
4,Dermochelyidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
5,Emydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
6,Geoemydidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
7,Kinosternidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
8,Platysternidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
9,Testudinidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
10,Trionychidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
11,Chelidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
12,Pelomedusidae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...
13,Podocnemididae,https://upload.wikimedia.org/wikipedia/commons...,https://www.scrapethissite.com//pages/frames/?...

	# 2.4 Extract all Testudines family details of first column save into csv file.

In [26]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')
frm
list =[]
for i in frm[0:14:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    list.append(dict)
list
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q2_4.csv',index=False)# to save into csv file 
df

,name,url,img_url
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
1,Dermatemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
2,Geoemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
3,Testudinidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
4,Pelomedusidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

	# 2.5 Extract all Testudines family details of Second column save into csv file.
m

In [27]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')
frm
list =[]
for i in frm[1:14:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    list.append(dict)
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q2_5.csv',index=False)# to save into csv file 
df

,name,url,img_url
0,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
1,Dermochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
2,Kinosternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
3,Trionychidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
4,Podocnemididae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

	# 2.6 Extract all Testudines family details of thirst column save into csv file.

In [28]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')
frm
list =[]
for i in frm[0:14]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    list.append(dict)
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q2_6.csv',index=False)# to save into csv file 
df

,name,url,img_url
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
3,Dermatemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
4,Dermochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
5,Emydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
6,Geoemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
7,Kinosternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
8,Platysternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
9,Testudinidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
10,Trionychidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
11,Chelidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
12,Pelomedusidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
13,Podocnemididae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

#  https://www.scrapethissite.com/pages/frames/ (Testudines_name, url,img_url,Testudines_deails via clicking on `Lean more` button)

# 	3.1 Extract first Testudines details save into csv file. e.g# Carettochelyidae

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd 
from urllib.parse import urljoin
import requests
driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
list = []
base_url = 'https://www.scrapethissite.com/'
dict = {
    'name':'',
    'url':'',
    'img_url':'',
   "detail":'',
}
dict ['img_url']=frm.find('img')['src']
dict ['url']=base_url + frm.find('a')['href']
dict ['name']=frm.find('h3').text
dict
        

act_url = urljoin(base_url,dict["url"])
resp = requests.get(act_url)
soup_nw = BeautifulSoup(resp.text, "html.parser")
soup_nw

dict["detail"]=soup_nw.find('p').text.strip()
list.append(dict)
dict
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q3_1.csv',index=False)# to save into csv file 
df

AttributeError: ResultSet object has no attribute "find". You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

	# 3.2 Extract Testudines family details from first row & save into csv file. e.g# Carettochelyidae, Cheloniidae, Chelydridae

In [31]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd
from urllib.parse import urljoin
import requests 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='row')
frm
list =[]



for i in frm[0:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(inner_url, headers=headers)
    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q3_2.csv',index=False)# to save into csv file 
df

,name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...
1,Dermatemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Dermatemydidae family of turtles — more co...
2,Geoemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Geoemydidae family of turtles — more commo...

	# 3.3 Extract all Testudines family details save into csv file.

In [32]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd
from urllib.parse import urljoin
import requests 

driver = webdriver.Edge() # to get webdriver to edge
url= "https://www.scrapethissite.com/pages/frames/" # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')
frm
list =[]



for i in frm[0:14]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(inner_url, headers=headers)
    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)
dict['url']
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q3_3.csv',index=False)# to save into csv file 
df

,name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Cheloniidae family of turtles — more commo...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Chelydridae family of turtles — more commo...
3,Dermatemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Dermatemydidae family of turtles — more co...
4,Dermochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Dermochelyidae family of turtles — more co...
5,Emydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Emydidae family of turtles — more commonly...
6,Geoemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Geoemydidae family of turtles — more commo...
7,Kinosternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Kinosternidae family of turtles — more com...
8,Platysternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Platysternidae family of turtles — more co...
9,Testudinidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Testudinidae family of turtles — more comm...
10,Trionychidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Trionychidae family of turtles — more comm...
11,Chelidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Chelidae family of turtles — more commonly...
12,Pelomedusidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Pelomedusidae family of turtles — more com...
13,Podocnemididae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Podocnemididae family of turtles — more co...

	# 3.4 Extract all Testudines family details of first column save into csv file.

In [33]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd
from urllib.parse import urljoin
import requests 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')
frm
list =[]



for i in frm[0:14:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(inner_url, headers=headers)
    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q3_4.csv',index=False)# to save into csv file 
df

,name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...
1,Dermatemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Dermatemydidae family of turtles — more co...
2,Geoemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Geoemydidae family of turtles — more commo...
3,Testudinidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Testudinidae family of turtles — more comm...
4,Pelomedusidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Pelomedusidae family of turtles — more com...

	# 3.5 Extract all Testudines family details of Second column save into csv file.

In [34]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd
from urllib.parse import urljoin
import requests 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')
frm
list =[]



for i in frm[1:14:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(inner_url, headers=headers)
    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)
df = pd.DataFrame(list)
# df.to_csv('scrapthisside q3_5.csv',index=False)# to save into csv file 
df

,name,url,img_url,detail
0,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Cheloniidae family of turtles — more commo...
1,Dermochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Dermochelyidae family of turtles — more co...
2,Kinosternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Kinosternidae family of turtles — more com...
3,Trionychidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Trionychidae family of turtles — more comm...
4,Podocnemididae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Podocnemididae family of turtles — more co...

	# 3.6 Extract all Testudines family details of thirst column save into csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd
from urllib.parse import urljoin
import requests 

driver = webdriver.Edge() # to get webdriver to edge
url= ("https://www.scrapethissite.com/pages/frames/") # to get the url 
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='col-md-4 turtle-family-card')
frm
list =[]



for i in frm[2:14:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(inner_url, headers=headers)
    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)
df = pd.DataFrame(list)
df.to_csv('scrapthisside q3_6.csv',index=False)# to save into csv file 
df

# 4. https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops (product_name, product_link, product_img, product_price, product_details, product_reviews_number, product_reviews_star_number )

# 	4.1 Extract first product details save into csv file. e.g# Packard 255 G2

In [35]:
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome()
driver.get("https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops")



soup = BeautifulSoup(driver.page_source, 'html.parser')
soup
product = soup.find('div',class_='product-wrapper card-body')
product
list = []
prod_dictionary = {
    'product_name': '',
    'product_link': '',
    'product_img': '',
    'product_price': '',
    'product_details': '',
    'product_reviews_number': '',
    'product_reviews_star_number': '',
}
prod_dictionary['product_name']= product.find('a').text.strip()
prod_dictionary['product_details']=product.find('p').text
prod_dictionary['product_img']=product.find('img')['src']
prod_dictionary['product_link']=product.find('a')['href']
prod_dictionary['product_reviews_number']=product.find('div',class_='ratings').text.strip()
prod_dictionary['product_reviews_star_number']
prod_dictionary['product_price']=product.find('h4').text.strip()
list.append(prod_dictionary)
prod_dictionary

{'product_name': 'Asus VivoBook X4',
 'product_link': '/test-sites/e-commerce/ajax/product/60',
 'product_img': '/images/test-sites/e-commerce/items/cart2.png',
 'product_price': '$295.99',
 'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
 'product_reviews_number': '1 reviews',
 'product_reviews_star_number': ''}

	# 4.2 Extract product details from first row & save into csv file. e.g# Packard 255 G2, Aspire E1-510, ThinkPad T540p

In [36]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops')
time.sleep(3)
driver.find_element("xpath","//button[@class='acceptCookies']").click()
list=[]
for i in range(2,3):
    for btn in driver.find_elements("xpath","//button[@class = 'btn btn-default page-link page']"):
        if btn.text == str(i):
            print("clicking on page:",btn.text)
            btn.click()
            time.sleep(3)
    soup=BeautifulSoup(driver.page_source,'html')
    first_products=soup.find_all('div',class_='col-md-4 col-xl-4 col-lg-4')
    for first_pro in first_products:
        dic={
            'product_name':'',
            'product_link':'',
            'product_img':'',
            'product_price':'',
            'product_details':'',
            'product_reviews_number':'',
            'product_reviews_star_number':'',
        }
        dic['product_name']=first_pro.find('a').text.strip()
        dic['product_link']=first_pro.find('a')['href']
        dic['product_img']=first_pro.find('img')['src']
        dic['product_price']=first_pro.find('h4',class_='price float-end pull-right').text.strip()
        dic['product_details']=first_pro.find('p',class_='card-text description').text.strip()
        dic['product_reviews_number']=first_pro.find('p',class_='review-count float-end pull-right').text.strip()
        list.append(dic)
df=pd.DataFrame(list)
df

clicking on page: 2

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Hewlett Packard,/test-sites/e-commerce/ajax/product/65,/images/test-sites/e-commerce/items/cart2.png,$364.46,"Hewlett Packard 250 G6 Dark Ash Silver, 15.6"" ...",11 reviews,
1,Acer Aspire 3 A3,/test-sites/e-commerce/ajax/product/66,/images/test-sites/e-commerce/items/cart2.png,$372.7,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Celeron...",3 reviews,
2,Acer Aspire A315,/test-sites/e-commerce/ajax/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",3 reviews,
3,Acer Aspire ES1-,/test-sites/e-commerce/ajax/product/68,/images/test-sites/e-commerce/items/cart2.png,$379.95,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",3 reviews,
4,Acer Aspire 3 A3,/test-sites/e-commerce/ajax/product/69,/images/test-sites/e-commerce/items/cart2.png,$391.48,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",3 reviews,
5,Acer Aspire 3 A3,/test-sites/e-commerce/ajax/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",3 reviews,

	# 4.3 Extract all product details from first page & save into csv file.

In [4]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
driver=webdriver.Chrome()
driver.get('https://webscraper.io/test-sites/e-commerce/ajax/computers/laptops')
time.sleep(3)
driver.find_element("xpath","//button[@class='acceptCookies']").click()
list=[]
for i in range(2,3):
    for btn in driver.find_elements("xpath","//button[@class = 'btn btn-default page-link page']"):
        if btn.text == str(i):
            print("clicking on page:",btn.text)
            btn.click()
            time.sleep(3)
    soup=BeautifulSoup(driver.page_source,'html')
    first_products=soup.find_all('div',class_='col-md-4 col-xl-4 col-lg-4')
    for first_pro in first_products:
        dic={
            'product_name':'',
            'product_link':'',
            'product_img':'',
            'product_price':'',
            'product_details':'',
            'product_reviews_number':'',
            'product_reviews_star_number':'',
        }
        dic['product_name']=first_pro.find('a').text.strip()
        dic['product_link']=first_pro.find('a')['href']
        dic['product_img']=first_pro.find('img')['src']
        dic['product_price']=first_pro.find('h4',class_='price float-end pull-right').text.strip()
        dic['product_details']=first_pro.find('p',class_='card-text description').text.strip()
        dic['product_reviews_number']=first_pro.find('p',class_='review-count float-end pull-right').text.strip()
        list.append(dic)
df=pd.DataFrame(list)
df

clicking on page: 2

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Hewlett Packard,/test-sites/e-commerce/ajax/product/65,/images/test-sites/e-commerce/items/cart2.png,$364.46,"Hewlett Packard 250 G6 Dark Ash Silver, 15.6"" ...",11 reviews,
1,Acer Aspire 3 A3,/test-sites/e-commerce/ajax/product/66,/images/test-sites/e-commerce/items/cart2.png,$372.7,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Celeron...",3 reviews,
2,Acer Aspire A315,/test-sites/e-commerce/ajax/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",3 reviews,
3,Acer Aspire ES1-,/test-sites/e-commerce/ajax/product/68,/images/test-sites/e-commerce/items/cart2.png,$379.95,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",3 reviews,
4,Acer Aspire 3 A3,/test-sites/e-commerce/ajax/product/69,/images/test-sites/e-commerce/items/cart2.png,$391.48,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",3 reviews,
5,Acer Aspire 3 A3,/test-sites/e-commerce/ajax/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",3 reviews,