In [13]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r=requests.get('https://www.cisa.gov/news-events/cybersecurity-advisories')
r.status_code

200

In [14]:
soup=BeautifulSoup(r.text,'html.parser')
web=soup.find_all('div',class_='c-view__row')
data=[]
for div in web:
    dic={
        "date":"",
        "name":"",
        "url":"",
    }
    dic['date']=div.find('time').text
    dic['name']=div.find('span').text
    dic['url']=div.find('a')['href']
    data.append(dic)
    #print(dic)

In [15]:
df=pd.DataFrame(data)
df

,date,name,url
0,"Oct 30, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/10/30/cisa-adds-two-k...
1,"Oct 30, 2025",CISA Releases Two Industrial Control Systems A...,/news-events/alerts/2025/10/30/cisa-releases-t...
2,"Oct 30, 2025",New Guidance Released on Microsoft Exchange Se...,/news-events/alerts/2025/10/30/new-guidance-re...
3,"Oct 28, 2025",CISA Releases Three Industrial Control Systems...,/news-events/alerts/2025/10/28/cisa-releases-t...
4,"Oct 28, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/10/28/cisa-adds-two-k...
5,"Oct 24, 2025",Microsoft Releases Out-of-Band Security Update...,/news-events/alerts/2025/10/24/microsoft-relea...
6,"Oct 24, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/10/24/cisa-adds-two-k...
7,"Oct 23, 2025",CISA Releases Eight Industrial Control Systems...,/news-events/alerts/2025/10/23/cisa-releases-e...
8,"Oct 22, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/10/22/cisa-adds-one-k...
9,"Oct 21, 2025",CISA Releases 10 Industrial Control Systems Ad...,/news-events/alerts/2025/10/21/cisa-releases-1...

In [16]:
df.to_csv('cybersecurity.csv',index=False)

In [11]:
d=requests.get('https://www.cisa.gov/news-events/cybersecurity-advisories?page=1')
soup=BeautifulSoup(d.text,'html.parser')
page1=soup.find_all('div',class_='c-view__row')
data1=[]
for div in page1:
    dic1={
        "date":"",
        "name":"",
        "url":"",
    }
    dic1['date']=div.find('time').text
    dic1['name']=div.find('span').text
    dic1['url']=div.find('a')['href']
    data1.append(dic1)
    print(data1)

[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}]
[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 16, 2025', 'name': 'CISA Releases Thirteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/16/cisa-releases-thirteen-industrial-control-systems-advisories'}]
[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 16, 2025', 'name': 'CISA Releases Thirteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/16/cisa-releases-thirteen-industrial-control-systems-advisories'}, {'date': 'Oct 15, 2025', 'name': 'CISA Directs Federal Agencies to Mitigate Vulnerabilities in F5 Devices', 'url': '/news-events/alerts/2025/10/15/cisa-directs-federal-agencies-mitigate-vulnerabilities-f5-devices'}]
[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 16, 2025', 'name': 'CISA Releases Thirteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/16/cisa-releases-thirteen-industrial-control-systems-advisories'}, {'date': 'Oct 15, 2025', 'name': 'CISA Directs Federal Agencies to Mitigate Vulnerabilities in F5 Devices', 'url': '/news-events/alerts/2025/10/15/cisa-directs-federal-agencies-mitigate-vulnerabilities-f5-devices'}, {'date': 'Oct 15, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/15/cisa-adds-one-known-exploited-vulnerability-catalog'}]
[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 16, 2025', 'name': 'CISA Releases Thirteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/16/cisa-releases-thirteen-industrial-control-systems-advisories'}, {'date': 'Oct 15, 2025', 'name': 'CISA Directs Federal Agencies to Mitigate Vulnerabilities in F5 Devices', 'url': '/news-events/alerts/2025/10/15/cisa-directs-federal-agencies-mitigate-vulnerabilities-f5-devices'}, {'date': 'Oct 15, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/15/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/14/cisa-adds-five-known-exploited-vulnerabilities-catalog'}]
[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 16, 2025', 'name': 'CISA Releases Thirteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/16/cisa-releases-thirteen-industrial-control-systems-advisories'}, {'date': 'Oct 15, 2025', 'name': 'CISA Directs Federal Agencies to Mitigate Vulnerabilities in F5 Devices', 'url': '/news-events/alerts/2025/10/15/cisa-directs-federal-agencies-mitigate-vulnerabilities-f5-devices'}, {'date': 'Oct 15, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/15/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/14/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Releases One Industrial Control Systems Advisory', 'url': '/news-events/alerts/2025/10/14/cisa-releases-one-industrial-control-systems-advisory'}]
[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 16, 2025', 'name': 'CISA Releases Thirteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/16/cisa-releases-thirteen-industrial-control-systems-advisories'}, {'date': 'Oct 15, 2025', 'name': 'CISA Directs Federal Agencies to Mitigate Vulnerabilities in F5 Devices', 'url': '/news-events/alerts/2025/10/15/cisa-directs-federal-agencies-mitigate-vulnerabilities-f5-devices'}, {'date': 'Oct 15, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/15/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/14/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Releases One Industrial Control Systems Advisory', 'url': '/news-events/alerts/2025/10/14/cisa-releases-one-industrial-control-systems-advisory'}, {'date': 'Oct 09, 2025', 'name': 'CISA Releases Four Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/09/cisa-releases-four-industrial-control-systems-advisories'}]
[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 16, 2025', 'name': 'CISA Releases Thirteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/16/cisa-releases-thirteen-industrial-control-systems-advisories'}, {'date': 'Oct 15, 2025', 'name': 'CISA Directs Federal Agencies to Mitigate Vulnerabilities in F5 Devices', 'url': '/news-events/alerts/2025/10/15/cisa-directs-federal-agencies-mitigate-vulnerabilities-f5-devices'}, {'date': 'Oct 15, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/15/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/14/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Releases One Industrial Control Systems Advisory', 'url': '/news-events/alerts/2025/10/14/cisa-releases-one-industrial-control-systems-advisory'}, {'date': 'Oct 09, 2025', 'name': 'CISA Releases Four Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/09/cisa-releases-four-industrial-control-systems-advisories'}, {'date': 'Oct 09, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/09/cisa-adds-one-known-exploited-vulnerability-catalog'}]
[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 16, 2025', 'name': 'CISA Releases Thirteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/16/cisa-releases-thirteen-industrial-control-systems-advisories'}, {'date': 'Oct 15, 2025', 'name': 'CISA Directs Federal Agencies to Mitigate Vulnerabilities in F5 Devices', 'url': '/news-events/alerts/2025/10/15/cisa-directs-federal-agencies-mitigate-vulnerabilities-f5-devices'}, {'date': 'Oct 15, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/15/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/14/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Releases One Industrial Control Systems Advisory', 'url': '/news-events/alerts/2025/10/14/cisa-releases-one-industrial-control-systems-advisory'}, {'date': 'Oct 09, 2025', 'name': 'CISA Releases Four Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/09/cisa-releases-four-industrial-control-systems-advisories'}, {'date': 'Oct 09, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/09/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Oct 07, 2025', 'name': 'CISA Releases Two Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/07/cisa-releases-two-industrial-control-systems-advisories'}]
[{'date': 'Oct 20, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/20/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 16, 2025', 'name': 'CISA Releases Thirteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/16/cisa-releases-thirteen-industrial-control-systems-advisories'}, {'date': 'Oct 15, 2025', 'name': 'CISA Directs Federal Agencies to Mitigate Vulnerabilities in F5 Devices', 'url': '/news-events/alerts/2025/10/15/cisa-directs-federal-agencies-mitigate-vulnerabilities-f5-devices'}, {'date': 'Oct 15, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/15/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/14/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 14, 2025', 'name': 'CISA Releases One Industrial Control Systems Advisory', 'url': '/news-events/alerts/2025/10/14/cisa-releases-one-industrial-control-systems-advisory'}, {'date': 'Oct 09, 2025', 'name': 'CISA Releases Four Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/09/cisa-releases-four-industrial-control-systems-advisories'}, {'date': 'Oct 09, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/09/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Oct 07, 2025', 'name': 'CISA Releases Two Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/07/cisa-releases-two-industrial-control-systems-advisories'}, {'date': 'Oct 07, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/10/07/cisa-adds-one-known-exploited-vulnerability-catalog'}]

In [ ]:
final_dat=data+data1 #merging two list into one
df1=pd.DataFrame(final_dat)
df1

,date,name,url
0,"Oct 30, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/10/30/cisa-adds-two-k...
1,"Oct 30, 2025",CISA Releases Two Industrial Control Systems A...,/news-events/alerts/2025/10/30/cisa-releases-t...
2,"Oct 30, 2025",New Guidance Released on Microsoft Exchange Se...,/news-events/alerts/2025/10/30/new-guidance-re...
3,"Oct 28, 2025",CISA Releases Three Industrial Control Systems...,/news-events/alerts/2025/10/28/cisa-releases-t...
4,"Oct 28, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/10/28/cisa-adds-two-k...
5,"Oct 24, 2025",Microsoft Releases Out-of-Band Security Update...,/news-events/alerts/2025/10/24/microsoft-relea...
6,"Oct 24, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/10/24/cisa-adds-two-k...
7,"Oct 23, 2025",CISA Releases Eight Industrial Control Systems...,/news-events/alerts/2025/10/23/cisa-releases-e...
8,"Oct 22, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/10/22/cisa-adds-one-k...
9,"Oct 21, 2025",CISA Releases 10 Industrial Control Systems Ad...,/news-events/alerts/2025/10/21/cisa-releases-1...
10,"Oct 20, 2025",CISA Adds Five Known Exploited Vulnerabilities...,/news-events/alerts/2025/10/20/cisa-adds-five-...
11,"Oct 16, 2025",CISA Releases Thirteen Industrial Control Syst...,/news-events/alerts/2025/10/16/cisa-releases-t...
12,"Oct 15, 2025",CISA Directs Federal Agencies to Mitigate Vuln...,/news-events/alerts/2025/10/15/cisa-directs-fe...
13,"Oct 15, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/10/15/cisa-adds-one-k...
14,"Oct 14, 2025",CISA Adds Five Known Exploited Vulnerabilities...,/news-events/alerts/2025/10/14/cisa-adds-five-...
15,"Oct 14, 2025",CISA Releases One Industrial Control Systems A...,/news-events/alerts/2025/10/14/cisa-releases-o...
16,"Oct 09, 2025",CISA Releases Four Industrial Control Systems ...,/news-events/alerts/2025/10/09/cisa-releases-f...
17,"Oct 09, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/10/09/cisa-adds-one-k...
18,"Oct 07, 2025",CISA Releases Two Industrial Control Systems A...,/news-events/alerts/2025/10/07/cisa-releases-t...
19,"Oct 07, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/10/07/cisa-adds-one-k...

In [18]:
df1.to_csv('cybersecurity.csv',index=False)

In [20]:
f=requests.get('https://www.cisa.gov/news-events/cybersecurity-advisories?page=2')
soup=BeautifulSoup(f.text,'html.parser')
page2=soup.find_all('div',class_='c-view__row')
data2=[]
for div in page2:
    dic2={
        "date":"",
        "name":"",
        "url":"",
    }
    dic2['date']=div.find('time').text
    dic2['name']=div.find('span').text
    dic2['url']=div.find('a')['href']
    data2.append(dic2)
print(data2)

[{'date': 'Oct 06, 2025', 'name': 'CISA Adds Seven Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/06/cisa-adds-seven-known-exploited-vulnerabilities-catalog'}, {'date': 'Oct 02, 2025', 'name': 'CISA Releases Two Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/10/02/cisa-releases-two-industrial-control-systems-advisories'}, {'date': 'Oct 02, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/10/02/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Sep 30, 2025', 'name': 'CISA Releases Ten Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/09/30/cisa-releases-ten-industrial-control-systems-advisories'}, {'date': 'Sep 29, 2025', 'name': 'CISA and UK NCSC Release Joint Guidance for Securing OT Systems', 'url': '/news-events/alerts/2025/09/29/cisa-and-uk-ncsc-release-joint-guidance-securing-ot-systems'}, {'date': 'Sep 29, 2025', 'name': 'CISA Strengthens Commitment to SLTT Governments', 'url': '/news-events/alerts/2025/09/29/cisa-strengthens-commitment-sltt-governments'}, {'date': 'Sep 29, 2025', 'name': 'CISA Adds Five Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/09/29/cisa-adds-five-known-exploited-vulnerabilities-catalog'}, {'date': 'Sep 25, 2025', 'name': 'CISA Directs Federal Agencies to Identify and Mitigate Potential Compromise of Cisco Devices', 'url': '/news-events/alerts/2025/09/25/cisa-directs-federal-agencies-identify-and-mitigate-potential-compromise-cisco-devices'}, {'date': 'Sep 25, 2025', 'name': 'CISA Releases One Industrial Control Systems Advisory', 'url': '/news-events/alerts/2025/09/25/cisa-releases-one-industrial-control-systems-advisory'}, {'date': 'Sep 23, 2025', 'name': 'Widespread Supply Chain Compromise Impacting npm Ecosystem', 'url': '/news-events/alerts/2025/09/23/widespread-supply-chain-compromise-impacting-npm-ecosystem'}]

In [21]:
g=requests.get('https://www.cisa.gov/news-events/cybersecurity-advisories?page=3')
soup=BeautifulSoup(g.text,'html.parser')
page3=soup.find_all('div',class_='c-view__row')
data3=[]
for div in page3:
    dic3={
        "date":"",
        "name":"",
        "url":"",
    }
    dic3['date']=div.find('time').text
    dic3['name']=div.find('span').text
    dic3['url']=div.find('a')['href']
    data3.append(dic3)
print(data3)

[{'date': 'Sep 23, 2025', 'name': 'CISA Releases Advisory on Lessons Learned from an Incident Response Engagement', 'url': '/news-events/alerts/2025/09/23/cisa-releases-advisory-lessons-learned-incident-response-engagement'}, {'date': 'Sep 23, 2025', 'name': 'CISA Releases Six Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/09/23/cisa-releases-six-industrial-control-systems-advisories'}, {'date': 'Sep 23, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/09/23/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Sep 23, 2025', 'name': 'CISA Shares Lessons Learned from an Incident Response Engagement', 'url': '/news-events/cybersecurity-advisories/aa25-266a'}, {'date': 'Sep 22, 2025', 'name': 'SonicWall Releases Advisory for Customers after Security Incident', 'url': '/news-events/alerts/2025/09/22/sonicwall-releases-advisory-customers-after-security-incident'}, {'date': 'Sep 18, 2025', 'name': 'CISA Releases Malware Analysis Report on Malicious Listener Targeting Ivanti Endpoint Manager Mobile Systems', 'url': '/news-events/alerts/2025/09/18/cisa-releases-malware-analysis-report-malicious-listener-targeting-ivanti-endpoint-manager-mobile'}, {'date': 'Sep 18, 2025', 'name': 'CISA Releases Nine Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/09/18/cisa-releases-nine-industrial-control-systems-advisories'}, {'date': 'Sep 18, 2025', 'name': 'Malicious Listener for Ivanti Endpoint Mobile Management Systems', 'url': '/news-events/analysis-reports/ar25-261a'}, {'date': 'Sep 16, 2025', 'name': 'CISA Releases Eight Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/09/16/cisa-releases-eight-industrial-control-systems-advisories'}, {'date': 'Sep 11, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/09/11/cisa-adds-one-known-exploited-vulnerability-catalog'}]

In [22]:
h=requests.get('https://www.cisa.gov/news-events/cybersecurity-advisories?page=4')
soup=BeautifulSoup(h.text,'html.parser')
page4=soup.find_all('div',class_='c-view__row')
data4=[]
for div in page4:
    dic4={
        "date":"",
        "name":"",
        "url":"",
    }
    dic4['date']=div.find('time').text
    dic4['name']=div.find('span').text
    dic4['url']=div.find('a')['href']
    data4.append(dic4)
print(data4)

[{'date': 'Sep 11, 2025', 'name': 'CISA Releases Eleven Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/09/11/cisa-releases-eleven-industrial-control-systems-advisories'}, {'date': 'Sep 09, 2025', 'name': 'CISA Releases Fourteen Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/09/09/cisa-releases-fourteen-industrial-control-systems-advisories'}, {'date': 'Sep 04, 2025', 'name': 'CISA Adds Three Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/09/04/cisa-adds-three-known-exploited-vulnerabilities-catalog'}, {'date': 'Sep 04, 2025', 'name': 'CISA Releases Five Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/09/04/cisa-releases-five-industrial-control-systems-advisories'}, {'date': 'Sep 03, 2025', 'name': 'CISA Adds Two Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/09/03/cisa-adds-two-known-exploited-vulnerabilities-catalog'}, {'date': 'Sep 03, 2025', 'name': 'CISA, NSA, and Global Partners Release a Shared Vision of Software Bill of Materials (SBOM) Guidance ', 'url': '/news-events/alerts/2025/09/03/cisa-nsa-and-global-partners-release-shared-vision-software-bill-materials-sbom-guidance'}, {'date': 'Sep 02, 2025', 'name': 'CISA Adds Two Known Exploited Vulnerabilities to Catalog', 'url': '/news-events/alerts/2025/09/02/cisa-adds-two-known-exploited-vulnerabilities-catalog'}, {'date': 'Sep 02, 2025', 'name': 'CISA Releases Four Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/09/02/cisa-releases-four-industrial-control-systems-advisories'}, {'date': 'Aug 29, 2025', 'name': 'CISA Adds One Known Exploited Vulnerability to Catalog', 'url': '/news-events/alerts/2025/08/29/cisa-adds-one-known-exploited-vulnerability-catalog'}, {'date': 'Aug 28, 2025', 'name': 'CISA Releases Nine Industrial Control Systems Advisories', 'url': '/news-events/alerts/2025/08/28/cisa-releases-nine-industrial-control-systems-advisories'}]

In [23]:
final1_data=final_dat+data2+data3+data4
df2=pd.DataFrame(final1_data)
df2

,date,name,url
0,"Oct 30, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/10/30/cisa-adds-two-k...
1,"Oct 30, 2025",CISA Releases Two Industrial Control Systems A...,/news-events/alerts/2025/10/30/cisa-releases-t...
2,"Oct 30, 2025",New Guidance Released on Microsoft Exchange Se...,/news-events/alerts/2025/10/30/new-guidance-re...
3,"Oct 28, 2025",CISA Releases Three Industrial Control Systems...,/news-events/alerts/2025/10/28/cisa-releases-t...
4,"Oct 28, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/10/28/cisa-adds-two-k...
5,"Oct 24, 2025",Microsoft Releases Out-of-Band Security Update...,/news-events/alerts/2025/10/24/microsoft-relea...
6,"Oct 24, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/10/24/cisa-adds-two-k...
7,"Oct 23, 2025",CISA Releases Eight Industrial Control Systems...,/news-events/alerts/2025/10/23/cisa-releases-e...
8,"Oct 22, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/10/22/cisa-adds-one-k...
9,"Oct 21, 2025",CISA Releases 10 Industrial Control Systems Ad...,/news-events/alerts/2025/10/21/cisa-releases-1...
10,"Oct 20, 2025",CISA Adds Five Known Exploited Vulnerabilities...,/news-events/alerts/2025/10/20/cisa-adds-five-...
11,"Oct 16, 2025",CISA Releases Thirteen Industrial Control Syst...,/news-events/alerts/2025/10/16/cisa-releases-t...
12,"Oct 15, 2025",CISA Directs Federal Agencies to Mitigate Vuln...,/news-events/alerts/2025/10/15/cisa-directs-fe...
13,"Oct 15, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/10/15/cisa-adds-one-k...
14,"Oct 14, 2025",CISA Adds Five Known Exploited Vulnerabilities...,/news-events/alerts/2025/10/14/cisa-adds-five-...
15,"Oct 14, 2025",CISA Releases One Industrial Control Systems A...,/news-events/alerts/2025/10/14/cisa-releases-o...
16,"Oct 09, 2025",CISA Releases Four Industrial Control Systems ...,/news-events/alerts/2025/10/09/cisa-releases-f...
17,"Oct 09, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/10/09/cisa-adds-one-k...
18,"Oct 07, 2025",CISA Releases Two Industrial Control Systems A...,/news-events/alerts/2025/10/07/cisa-releases-t...
19,"Oct 07, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/10/07/cisa-adds-one-k...
20,"Oct 06, 2025",CISA Adds Seven Known Exploited Vulnerabilitie...,/news-events/alerts/2025/10/06/cisa-adds-seven...
21,"Oct 02, 2025",CISA Releases Two Industrial Control Systems A...,/news-events/alerts/2025/10/02/cisa-releases-t...
22,"Oct 02, 2025",CISA Adds Five Known Exploited Vulnerabilities...,/news-events/alerts/2025/10/02/cisa-adds-five-...
23,"Sep 30, 2025",CISA Releases Ten Industrial Control Systems A...,/news-events/alerts/2025/09/30/cisa-releases-t...
24,"Sep 29, 2025",CISA and UK NCSC Release Joint Guidance for Se...,/news-events/alerts/2025/09/29/cisa-and-uk-ncs...
25,"Sep 29, 2025",CISA Strengthens Commitment to SLTT Governments,/news-events/alerts/2025/09/29/cisa-strengthen...
26,"Sep 29, 2025",CISA Adds Five Known Exploited Vulnerabilities...,/news-events/alerts/2025/09/29/cisa-adds-five-...
27,"Sep 25, 2025",CISA Directs Federal Agencies to Identify and ...,/news-events/alerts/2025/09/25/cisa-directs-fe...
28,"Sep 25, 2025",CISA Releases One Industrial Control Systems A...,/news-events/alerts/2025/09/25/cisa-releases-o...
29,"Sep 23, 2025",Widespread Supply Chain Compromise Impacting n...,/news-events/alerts/2025/09/23/widespread-supp...
30,"Sep 23, 2025",CISA Releases Advisory on Lessons Learned from...,/news-events/alerts/2025/09/23/cisa-releases-a...
31,"Sep 23, 2025",CISA Releases Six Industrial Control Systems A...,/news-events/alerts/2025/09/23/cisa-releases-s...
32,"Sep 23, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/09/23/cisa-adds-one-k...
33,"Sep 23, 2025",CISA Shares Lessons Learned from an Incident R...,/news-events/cybersecurity-advisories/aa25-266a
34,"Sep 22, 2025",SonicWall Releases Advisory for Customers afte...,/news-events/alerts/2025/09/22/sonicwall-relea...
35,"Sep 18, 2025",CISA Releases Malware Analysis Report on Malic...,/news-events/alerts/2025/09/18/cisa-releases-m...
36,"Sep 18, 2025",CISA Releases Nine Industrial Control Systems ...,/news-events/alerts/2025/09/18/cisa-releases-n...
37,"Sep 18, 2025",Malicious Listener for Ivanti Endpoint Mobile ...,/news-events/analysis-reports/ar25-261a
38,"Sep 16, 2025",CISA Releases Eight Industrial Control Systems...,/news-events/alerts/2025/09/16/cisa-releases-e...
39,"Sep 11, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/09/11/cisa-adds-one-k...
40,"Sep 11, 2025",CISA Releases Eleven Industrial Control System...,/news-events/alerts/2025/09/11/cisa-releases-e...
41,"Sep 09, 2025",CISA Releases Fourteen Industrial Control Syst...,/news-events/alerts/2025/09/09/cisa-releases-f...
42,"Sep 04, 2025",CISA Adds Three Known Exploited Vulnerabilitie...,/news-events/alerts/2025/09/04/cisa-adds-three...
43,"Sep 04, 2025",CISA Releases Five Industrial Control Systems ...,/news-events/alerts/2025/09/04/cisa-releases-f...
44,"Sep 03, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/09/03/cisa-adds-two-k...
45,"Sep 03, 2025","CISA, NSA, and Global Partners Release a Share...",/news-events/alerts/2025/09/03/cisa-nsa-and-gl...
46,"Sep 02, 2025",CISA Adds Two Known Exploited Vulnerabilities ...,/news-events/alerts/2025/09/02/cisa-adds-two-k...
47,"Sep 02, 2025",CISA Releases Four Industrial Control Systems ...,/news-events/alerts/2025/09/02/cisa-releases-f...
48,"Aug 29, 2025",CISA Adds One Known Exploited Vulnerability to...,/news-events/alerts/2025/08/29/cisa-adds-one-k...
49,"Aug 28, 2025",CISA Releases Nine Industrial Control Systems ...,/news-events/alerts/2025/08/28/cisa-releases-n...

In [24]:
df2.to_csv('cybersecurity.csv',index=False)