# All div find

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r=requests.get('https://www.scrapethissite.com/pages/')
r.status_code

200

In [3]:
soup=BeautifulSoup(r.text,'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Learn Web Scraping | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Here are some practice pages you can scrape." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="pages">
   <section>
    <div class="container">
     <div class="row">
      <div class="col-md-6 col-md-offset-3">
       <h1>
        Web Scraping Sandbox
       </h1>
       <hr/>
       <div class="page">
        <h3 class="page-title">
         <a href="/pages/simple/">
          Countries of the World: A Simple Example
         </a>
        </h3>
        <p class="lead session-desc">
         A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
        </p>
        <hr/>
       </div>
       <!--.page-->
       <div class="page">
        <h3 class="page-title">
         <a href="/pages/forms/">
          Hockey Teams: Forms, Searching and Pagination
         </a>
        </h3>
        <p class="lead session-desc">
         Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
        </p>
        <hr/>
       </div>
       <!--.page-->
       <div class="page">
        <h3 class="page-title">
         <a href="/pages/ajax-javascript/">
          Oscar Winning Films: AJAX and Javascript
         </a>
        </h3>
        <p class="lead session-desc">
         Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it.
        </p>
        <hr/>
       </div>
       <!--.page-->
       <div class="page">
        <h3 class="page-title">
         <a href="/pages/frames/">
          Turtles All the Way Down: Frames &amp; iFrames
         </a>
        </h3>
        <p class="lead session-desc">
         Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.
        </p>
        <hr/>
       </div>
       <!--.page-->
       <div class="page">
        <h3 class="page-title">
         <a href="/pages/advanced/">
          Advanced Topics: Real World Challenges You'll Encounter
         </a>
        </h3>
        <p class="lead session-desc">
         Scraping real websites, you're likely run into a number of common gotchas. Get practice with spoofing headers, handling logins &amp; session cookies, finding CSRF tokens, and other common network errors.
        </p>
        <hr/>
       </div>
       <!--.page-->
      </div>
      <!--.col-->
     </div>
     <!--.row-->
    </div>
    <!--.container-->
   </section>
  </div>
  <section id="footer">
   <div class="container">
    <div class="row">
     <div class="col-md-12 text-center text-muted">
      Lessons and Videos © Hartley Brody 2023
     </div>
     <!--.col-->
    </div>
    <!--.row-->
   </div>
   <!--.container-->
  </section>
 </body>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
 </script>
 <script crossorigin="anonymous" integrity="sha256-Sk3nkD6mLTMOF0EOpNtsIry+s1CsaqQC1rVLTAy+0yc= sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js">
 </script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.js">
 </script>
 <link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/2.1.0/pnotify.core.min.css" rel="stylesheet" type="text/css"/>
 <!-- pnotify messages -->
 <script type="text/javascript">
  PNotify.prototype.options.styling = "bootstrap3";
    $(function(){

    });


    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
 </script>
 <!-- golbal video controls -->
 <script type="text/javascript">
  $("video").hover(function() {
        $(this).prop("controls", true);
    }, function() {
        $(this).prop("controls", false);
    });

    $("video").click(function() {
        if( this.paused){
            this.play();
        }
        else {
            this.pause();
        }
    });
 </script>
 <!-- insert google analytics here -->
 <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41551755-8', 'auto');
    ga('send', 'pageview');
 </script>
 <!-- Facebook Pixel Code -->
 <script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');

  fbq('init', '764287443701341');
  fbq('track', "PageView");
 </script>
 <noscript>
  <img height="1" src="https://www.facebook.com/tr?id=764287443701341&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/>
 </noscript>
 <!-- End Facebook Pixel Code -->
 <!-- Google Code for Remarketing Tag -->
 <script type="text/javascript">
  /* <![CDATA[ */
    var google_conversion_id = 950945448;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
 </script>
 <script src="//www.googleadservices.com/pagead/conversion.js" type="text/javascript">
 </script>
 <noscript>
  <div style="display:inline;">
   <img alt="" height="1" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950945448/?guid=ON&amp;script=0" style="border-style:none;" width="1"/>
  </div>
 </noscript>
 <!-- Global site tag (gtag.js) - Google AdWords: 950945448 -->
 <script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-950945448">
 </script>
 <script>
  window.dataLayer = window.dataLayer || [];
   function gtag(){dataLayer.push(arguments);}
   gtag('js', new Date());

   gtag('config', 'AW-950945448');
 </script>
</html>

In [9]:
website=soup.find_all('div',class_='page')
list=[]
for div in website:
    products_dtl={
        'products_name':"",
        'products_para':"",
        'product_url':"",
    }
    products_dtl['products_name']=div.find('a').text
    products_dtl['products_para']=div.find('p').text.strip()
    products_dtl['product_url']=div.find('a')['href']
    print(products_dtl)
    list.append(products_dtl)

{'products_name': 'Countries of the World: A Simple Example', 'products_para': 'A single page that lists information about all the countries in the world. Good for those just get started with web scraping.', 'product_url': '/pages/simple/'}
{'products_name': 'Hockey Teams: Forms, Searching and Pagination', 'products_para': 'Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.', 'product_url': '/pages/forms/'}
{'products_name': 'Oscar Winning Films: AJAX and Javascript', 'products_para': 'Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it.', 'product_url': '/pages/ajax-javascript/'}
{'products_name': 'Turtles All the Way Down: Frames & iFrames', 'products_para': 'Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.', 'product_url': '/pages/frames/'}
{'products_name': "Advanced Topics: Real World Challenges You'll Encounter", 'products_para': "Scraping real websites, you're likely run into a number of common gotchas. Get practice with spoofing headers, handling logins & session cookies, finding CSRF tokens, and other common network errors.", 'product_url': '/pages/advanced/'}

In [10]:
csv=pd.DataFrame(list)
csv

,products_name,products_para,product_url
0,Countries of the World: A Simple Example,A single page that lists information about all...,/pages/simple/
1,"Hockey Teams: Forms, Searching and Pagination",Browse through a database of NHL team stats si...,/pages/forms/
2,Oscar Winning Films: AJAX and Javascript,Click through a bunch of great films. Learn ho...,/pages/ajax-javascript/
3,Turtles All the Way Down: Frames & iFrames,Some older sites might still use frames to bre...,/pages/frames/
4,Advanced Topics: Real World Challenges You'll ...,"Scraping real websites, you're likely run into...",/pages/advanced/

In [11]:
csv.to_csv('list of product.csv',index=False)

## 3.1 Extract Table of first page & save into csv file. (Team Name, Year, Wins, Losses, OT Losses, Win %, Goals For (GF), Goals Against (GA), + / -)

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r=requests.get('https://www.scrapethissite.com/pages/forms/')
r.status_code

200

In [5]:
soup=BeautifulSoup(r.text,'html.parser')
web=soup.find_all('tr',class_='team')
list=[]
for table in web:
    dic={
        'Team Name':'',
        'Year':'',
        'Wins':'',
        'Losses':'',
        'OT Losses':'Nill',
        'Win %':'',
        'Goals For (GF)':'',
        'Goals Against (GA)':'',
        '+ / -':'',
    }
    dic['Team Name']=table.find('td',class_='name').text.strip()
    dic['Year']=table.find('td',class_='year').text.strip()
    dic['Wins']=table.find('td',class_='wins').text.strip()
    dic['Losses']=table.find('td',class_='losses').text.strip()
    dic['Win %']=table.find('td',class_='pct').text.strip()
    dic['Goals For (GF)']=table.find('td',class_='gf').text.strip()
    dic['Goals Against (GA)']=table.find('td',class_='ga').text.strip()
    dic['+ / -']=table.find('td',class_='diff').text.strip()
    #print(dic)
    list.append(dic)
print(list)

[{'Team Name': 'Boston Bruins', 'Year': '1990', 'Wins': '44', 'Losses': '24', 'OT Losses': 'Nill', 'Win %': '0.55', 'Goals For (GF)': '299', 'Goals Against (GA)': '264', '+ / -': '35'}, {'Team Name': 'Buffalo Sabres', 'Year': '1990', 'Wins': '31', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '292', 'Goals Against (GA)': '278', '+ / -': '14'}, {'Team Name': 'Calgary Flames', 'Year': '1990', 'Wins': '46', 'Losses': '26', 'OT Losses': 'Nill', 'Win %': '0.575', 'Goals For (GF)': '344', 'Goals Against (GA)': '263', '+ / -': '81'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1990', 'Wins': '49', 'Losses': '23', 'OT Losses': 'Nill', 'Win %': '0.613', 'Goals For (GF)': '284', 'Goals Against (GA)': '211', '+ / -': '73'}, {'Team Name': 'Detroit Red Wings', 'Year': '1990', 'Wins': '34', 'Losses': '38', 'OT Losses': 'Nill', 'Win %': '0.425', 'Goals For (GF)': '273', 'Goals Against (GA)': '298', '+ / -': '-25'}, {'Team Name': 'Edmonton Oilers', 'Year': '1990', 'Wins': '37', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.463', 'Goals For (GF)': '272', 'Goals Against (GA)': '272', '+ / -': '0'}, {'Team Name': 'Hartford Whalers', 'Year': '1990', 'Wins': '31', 'Losses': '38', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '238', 'Goals Against (GA)': '276', '+ / -': '-38'}, {'Team Name': 'Los Angeles Kings', 'Year': '1990', 'Wins': '46', 'Losses': '24', 'OT Losses': 'Nill', 'Win %': '0.575', 'Goals For (GF)': '340', 'Goals Against (GA)': '254', '+ / -': '86'}, {'Team Name': 'Minnesota North Stars', 'Year': '1990', 'Wins': '27', 'Losses': '39', 'OT Losses': 'Nill', 'Win %': '0.338', 'Goals For (GF)': '256', 'Goals Against (GA)': '266', '+ / -': '-10'}, {'Team Name': 'Montreal Canadiens', 'Year': '1990', 'Wins': '39', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.487', 'Goals For (GF)': '273', 'Goals Against (GA)': '249', '+ / -': '24'}, {'Team Name': 'New Jersey Devils', 'Year': '1990', 'Wins': '32', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.4', 'Goals For (GF)': '272', 'Goals Against (GA)': '264', '+ / -': '8'}, {'Team Name': 'New York Islanders', 'Year': '1990', 'Wins': '25', 'Losses': '45', 'OT Losses': 'Nill', 'Win %': '0.312', 'Goals For (GF)': '223', 'Goals Against (GA)': '290', '+ / -': '-67'}, {'Team Name': 'New York Rangers', 'Year': '1990', 'Wins': '36', 'Losses': '31', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '297', 'Goals Against (GA)': '265', '+ / -': '32'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1990', 'Wins': '33', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.412', 'Goals For (GF)': '252', 'Goals Against (GA)': '267', '+ / -': '-15'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1990', 'Wins': '41', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '342', 'Goals Against (GA)': '305', '+ / -': '37'}, {'Team Name': 'Quebec Nordiques', 'Year': '1990', 'Wins': '16', 'Losses': '50', 'OT Losses': 'Nill', 'Win %': '0.2', 'Goals For (GF)': '236', 'Goals Against (GA)': '354', '+ / -': '-118'}, {'Team Name': 'St. Louis Blues', 'Year': '1990', 'Wins': '47', 'Losses': '22', 'OT Losses': 'Nill', 'Win %': '0.588', 'Goals For (GF)': '310', 'Goals Against (GA)': '250', '+ / -': '60'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1990', 'Wins': '23', 'Losses': '46', 'OT Losses': 'Nill', 'Win %': '0.287', 'Goals For (GF)': '241', 'Goals Against (GA)': '318', '+ / -': '-77'}, {'Team Name': 'Vancouver Canucks', 'Year': '1990', 'Wins': '28', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.35', 'Goals For (GF)': '243', 'Goals Against (GA)': '315', '+ / -': '-72'}, {'Team Name': 'Washington Capitals', 'Year': '1990', 'Wins': '37', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.463', 'Goals For (GF)': '258', 'Goals Against (GA)': '258', '+ / -': '0'}, {'Team Name': 'Winnipeg Jets', 'Year': '1990', 'Wins': '26', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.325', 'Goals For (GF)': '260', 'Goals Against (GA)': '288', '+ / -': '-28'}, {'Team Name': 'Boston Bruins', 'Year': '1991', 'Wins': '36', 'Losses': '32', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '270', 'Goals Against (GA)': '275', '+ / -': '-5'}, {'Team Name': 'Buffalo Sabres', 'Year': '1991', 'Wins': '31', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '289', 'Goals Against (GA)': '299', '+ / -': '-10'}, {'Team Name': 'Calgary Flames', 'Year': '1991', 'Wins': '31', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '296', 'Goals Against (GA)': '305', '+ / -': '-9'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1991', 'Wins': '36', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '257', 'Goals Against (GA)': '236', '+ / -': '21'}]

In [12]:
df=pd.DataFrame(list)
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,Nill,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,Nill,0.388,292,278,14
2,Calgary Flames,1990,46,26,Nill,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,Nill,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,Nill,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,Nill,0.463,272,272,0
6,Hartford Whalers,1990,31,38,Nill,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,Nill,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,Nill,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,Nill,0.487,273,249,24
10,New Jersey Devils,1990,32,33,Nill,0.4,272,264,8
11,New York Islanders,1990,25,45,Nill,0.312,223,290,-67
12,New York Rangers,1990,36,31,Nill,0.45,297,265,32
13,Philadelphia Flyers,1990,33,37,Nill,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,Nill,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,Nill,0.2,236,354,-118
16,St. Louis Blues,1990,47,22,Nill,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,Nill,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,Nill,0.35,243,315,-72
19,Washington Capitals,1990,37,36,Nill,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,Nill,0.325,260,288,-28
21,Boston Bruins,1991,36,32,Nill,0.45,270,275,-5
22,Buffalo Sabres,1991,31,37,Nill,0.388,289,299,-10
23,Calgary Flames,1991,31,37,Nill,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,Nill,0.45,257,236,21

In [13]:
df.to_csv('scrapethissite_q1.csv',index=False)

## 3.2 Extract Table of second page & save into another csv file.

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r2=requests.get('https://www.scrapethissite.com/pages/forms/?page_num=2')
r2.status_code

200

In [7]:
soup=BeautifulSoup(r2.text,'html.parser')
web2=soup.find_all('tr',class_='team')
list2=[]
for table2 in web2:
    dic2={
        'Team Name':'',
        'Year':'',
        'Wins':'',
        'Losses':'',
        'OT Losses':'Nill',
        'Win %':'',
        'Goals For (GF)':'',
        'Goals Against (GA)':'',
        '+ / -':'',
    }
    dic2['Team Name']=table2.find('td',class_='name').text.strip()
    dic2['Year']=table2.find('td',class_='year').text.strip()
    dic2['Wins']=table2.find('td',class_='wins').text.strip()
    dic2['Losses']=table2.find('td',class_='losses').text.strip()
    dic2['Win %']=table2.find('td',class_='pct').text.strip()
    dic2['Goals For (GF)']=table2.find('td',class_='gf').text.strip()
    dic2['Goals Against (GA)']=table2.find('td',class_='ga').text.strip()
    dic2['+ / -']=table2.find('td',class_='diff').text.strip()
    #print(dic)
    list2.append(dic2)
print(list2)

[{'Team Name': 'Detroit Red Wings', 'Year': '1991', 'Wins': '43', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.537', 'Goals For (GF)': '320', 'Goals Against (GA)': '256', '+ / -': '64'}, {'Team Name': 'Edmonton Oilers', 'Year': '1991', 'Wins': '36', 'Losses': '34', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '295', 'Goals Against (GA)': '297', '+ / -': '-2'}, {'Team Name': 'Hartford Whalers', 'Year': '1991', 'Wins': '26', 'Losses': '41', 'OT Losses': 'Nill', 'Win %': '0.325', 'Goals For (GF)': '247', 'Goals Against (GA)': '283', '+ / -': '-36'}, {'Team Name': 'Los Angeles Kings', 'Year': '1991', 'Wins': '35', 'Losses': '31', 'OT Losses': 'Nill', 'Win %': '0.438', 'Goals For (GF)': '287', 'Goals Against (GA)': '296', '+ / -': '-9'}, {'Team Name': 'Minnesota North Stars', 'Year': '1991', 'Wins': '32', 'Losses': '42', 'OT Losses': 'Nill', 'Win %': '0.4', 'Goals For (GF)': '246', 'Goals Against (GA)': '278', '+ / -': '-32'}, {'Team Name': 'Montreal Canadiens', 'Year': '1991', 'Wins': '41', 'Losses': '28', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '267', 'Goals Against (GA)': '207', '+ / -': '60'}, {'Team Name': 'New Jersey Devils', 'Year': '1991', 'Wins': '38', 'Losses': '31', 'OT Losses': 'Nill', 'Win %': '0.475', 'Goals For (GF)': '289', 'Goals Against (GA)': '259', '+ / -': '30'}, {'Team Name': 'New York Islanders', 'Year': '1991', 'Wins': '34', 'Losses': '35', 'OT Losses': 'Nill', 'Win %': '0.425', 'Goals For (GF)': '291', 'Goals Against (GA)': '299', '+ / -': '-8'}, {'Team Name': 'New York Rangers', 'Year': '1991', 'Wins': '50', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.625', 'Goals For (GF)': '321', 'Goals Against (GA)': '246', '+ / -': '75'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1991', 'Wins': '32', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.4', 'Goals For (GF)': '252', 'Goals Against (GA)': '273', '+ / -': '-21'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1991', 'Wins': '39', 'Losses': '32', 'OT Losses': 'Nill', 'Win %': '0.487', 'Goals For (GF)': '343', 'Goals Against (GA)': '308', '+ / -': '35'}, {'Team Name': 'Quebec Nordiques', 'Year': '1991', 'Wins': '20', 'Losses': '48', 'OT Losses': 'Nill', 'Win %': '0.25', 'Goals For (GF)': '255', 'Goals Against (GA)': '318', '+ / -': '-63'}, {'Team Name': 'San Jose Sharks', 'Year': '1991', 'Wins': '17', 'Losses': '58', 'OT Losses': 'Nill', 'Win %': '0.212', 'Goals For (GF)': '219', 'Goals Against (GA)': '359', '+ / -': '-140'}, {'Team Name': 'St. Louis Blues', 'Year': '1991', 'Wins': '36', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '279', 'Goals Against (GA)': '266', '+ / -': '13'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1991', 'Wins': '30', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.375', 'Goals For (GF)': '234', 'Goals Against (GA)': '294', '+ / -': '-60'}, {'Team Name': 'Vancouver Canucks', 'Year': '1991', 'Wins': '42', 'Losses': '26', 'OT Losses': 'Nill', 'Win %': '0.525', 'Goals For (GF)': '285', 'Goals Against (GA)': '250', '+ / -': '35'}, {'Team Name': 'Washington Capitals', 'Year': '1991', 'Wins': '45', 'Losses': '27', 'OT Losses': 'Nill', 'Win %': '0.562', 'Goals For (GF)': '330', 'Goals Against (GA)': '275', '+ / -': '55'}, {'Team Name': 'Winnipeg Jets', 'Year': '1991', 'Wins': '33', 'Losses': '32', 'OT Losses': 'Nill', 'Win %': '0.412', 'Goals For (GF)': '251', 'Goals Against (GA)': '244', '+ / -': '7'}, {'Team Name': 'Boston Bruins', 'Year': '1992', 'Wins': '51', 'Losses': '26', 'OT Losses': 'Nill', 'Win %': '0.607', 'Goals For (GF)': '332', 'Goals Against (GA)': '268', '+ / -': '64'}, {'Team Name': 'Buffalo Sabres', 'Year': '1992', 'Wins': '38', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.452', 'Goals For (GF)': '335', 'Goals Against (GA)': '297', '+ / -': '38'}, {'Team Name': 'Calgary Flames', 'Year': '1992', 'Wins': '43', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '322', 'Goals Against (GA)': '282', '+ / -': '40'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1992', 'Wins': '47', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.56', 'Goals For (GF)': '279', 'Goals Against (GA)': '230', '+ / -': '49'}, {'Team Name': 'Detroit Red Wings', 'Year': '1992', 'Wins': '47', 'Losses': '28', 'OT Losses': 'Nill', 'Win %': '0.56', 'Goals For (GF)': '369', 'Goals Against (GA)': '280', '+ / -': '89'}, {'Team Name': 'Edmonton Oilers', 'Year': '1992', 'Wins': '26', 'Losses': '50', 'OT Losses': 'Nill', 'Win %': '0.31', 'Goals For (GF)': '242', 'Goals Against (GA)': '337', '+ / -': '-95'}, {'Team Name': 'Hartford Whalers', 'Year': '1992', 'Wins': '26', 'Losses': '52', 'OT Losses': 'Nill', 'Win %': '0.31', 'Goals For (GF)': '284', 'Goals Against (GA)': '369', '+ / -': '-85'}]

In [17]:
df2=pd.DataFrame(list2)
df2

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Detroit Red Wings,1991,43,25,Nill,0.537,320,256,64
1,Edmonton Oilers,1991,36,34,Nill,0.45,295,297,-2
2,Hartford Whalers,1991,26,41,Nill,0.325,247,283,-36
3,Los Angeles Kings,1991,35,31,Nill,0.438,287,296,-9
4,Minnesota North Stars,1991,32,42,Nill,0.4,246,278,-32
5,Montreal Canadiens,1991,41,28,Nill,0.512,267,207,60
6,New Jersey Devils,1991,38,31,Nill,0.475,289,259,30
7,New York Islanders,1991,34,35,Nill,0.425,291,299,-8
8,New York Rangers,1991,50,25,Nill,0.625,321,246,75
9,Philadelphia Flyers,1991,32,37,Nill,0.4,252,273,-21
10,Pittsburgh Penguins,1991,39,32,Nill,0.487,343,308,35
11,Quebec Nordiques,1991,20,48,Nill,0.25,255,318,-63
12,San Jose Sharks,1991,17,58,Nill,0.212,219,359,-140
13,St. Louis Blues,1991,36,33,Nill,0.45,279,266,13
14,Toronto Maple Leafs,1991,30,43,Nill,0.375,234,294,-60
15,Vancouver Canucks,1991,42,26,Nill,0.525,285,250,35
16,Washington Capitals,1991,45,27,Nill,0.562,330,275,55
17,Winnipeg Jets,1991,33,32,Nill,0.412,251,244,7
18,Boston Bruins,1992,51,26,Nill,0.607,332,268,64
19,Buffalo Sabres,1992,38,36,Nill,0.452,335,297,38
20,Calgary Flames,1992,43,30,Nill,0.512,322,282,40
21,Chicago Blackhawks,1992,47,25,Nill,0.56,279,230,49
22,Detroit Red Wings,1992,47,28,Nill,0.56,369,280,89
23,Edmonton Oilers,1992,26,50,Nill,0.31,242,337,-95
24,Hartford Whalers,1992,26,52,Nill,0.31,284,369,-85

In [18]:
df2.to_csv('scrapethissite_q2.csv',index=False)

## 3.3 Extract Table of fist five pages & save into single csv file.

In [9]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r3=requests.get('https://www.scrapethissite.com/pages/forms/?page_num=3')
r3.status_code

200

In [10]:
soup=BeautifulSoup(r3.text,'html.parser')
web3=soup.find_all('tr',class_='team')
list3=[]
for table3 in web3:
    dic3={
        'Team Name':'',
        'Year':'',
        'Wins':'',
        'Losses':'',
        'OT Losses':'Nill',
        'Win %':'',
        'Goals For (GF)':'',
        'Goals Against (GA)':'',
        '+ / -':'',
    }
    dic3['Team Name']=table3.find('td',class_='name').text.strip()
    dic3['Year']=table3.find('td',class_='year').text.strip()
    dic3['Wins']=table3.find('td',class_='wins').text.strip()
    dic3['Losses']=table3.find('td',class_='losses').text.strip()
    dic3['Win %']=table3.find('td',class_='pct').text.strip()
    dic3['Goals For (GF)']=table3.find('td',class_='gf').text.strip()
    dic3['Goals Against (GA)']=table3.find('td',class_='ga').text.strip()
    dic3['+ / -']=table3.find('td',class_='diff').text.strip()
    #print(dic)
    list3.append(dic3)
print(list3)

[{'Team Name': 'Los Angeles Kings', 'Year': '1992', 'Wins': '39', 'Losses': '35', 'OT Losses': 'Nill', 'Win %': '0.464', 'Goals For (GF)': '338', 'Goals Against (GA)': '340', '+ / -': '-2'}, {'Team Name': 'Minnesota North Stars', 'Year': '1992', 'Wins': '36', 'Losses': '38', 'OT Losses': 'Nill', 'Win %': '0.429', 'Goals For (GF)': '272', 'Goals Against (GA)': '293', '+ / -': '-21'}, {'Team Name': 'Montreal Canadiens', 'Year': '1992', 'Wins': '48', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.571', 'Goals For (GF)': '326', 'Goals Against (GA)': '280', '+ / -': '46'}, {'Team Name': 'New Jersey Devils', 'Year': '1992', 'Wins': '40', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.476', 'Goals For (GF)': '308', 'Goals Against (GA)': '299', '+ / -': '9'}, {'Team Name': 'New York Islanders', 'Year': '1992', 'Wins': '40', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.476', 'Goals For (GF)': '335', 'Goals Against (GA)': '297', '+ / -': '38'}, {'Team Name': 'New York Rangers', 'Year': '1992', 'Wins': '34', 'Losses': '39', 'OT Losses': 'Nill', 'Win %': '0.405', 'Goals For (GF)': '304', 'Goals Against (GA)': '308', '+ / -': '-4'}, {'Team Name': 'Ottawa Senators', 'Year': '1992', 'Wins': '10', 'Losses': '70', 'OT Losses': 'Nill', 'Win %': '0.119', 'Goals For (GF)': '202', 'Goals Against (GA)': '395', '+ / -': '-193'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1992', 'Wins': '36', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.429', 'Goals For (GF)': '319', 'Goals Against (GA)': '319', '+ / -': '0'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1992', 'Wins': '56', 'Losses': '21', 'OT Losses': 'Nill', 'Win %': '0.667', 'Goals For (GF)': '367', 'Goals Against (GA)': '268', '+ / -': '99'}, {'Team Name': 'Quebec Nordiques', 'Year': '1992', 'Wins': '47', 'Losses': '27', 'OT Losses': 'Nill', 'Win %': '0.56', 'Goals For (GF)': '351', 'Goals Against (GA)': '300', '+ / -': '51'}, {'Team Name': 'San Jose Sharks', 'Year': '1992', 'Wins': '11', 'Losses': '71', 'OT Losses': 'Nill', 'Win %': '0.131', 'Goals For (GF)': '218', 'Goals Against (GA)': '414', '+ / -': '-196'}, {'Team Name': 'St. Louis Blues', 'Year': '1992', 'Wins': '37', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.44', 'Goals For (GF)': '282', 'Goals Against (GA)': '278', '+ / -': '4'}, {'Team Name': 'Tampa Bay Lightning', 'Year': '1992', 'Wins': '23', 'Losses': '54', 'OT Losses': 'Nill', 'Win %': '0.274', 'Goals For (GF)': '245', 'Goals Against (GA)': '332', '+ / -': '-87'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1992', 'Wins': '44', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.524', 'Goals For (GF)': '288', 'Goals Against (GA)': '241', '+ / -': '47'}, {'Team Name': 'Vancouver Canucks', 'Year': '1992', 'Wins': '46', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.548', 'Goals For (GF)': '346', 'Goals Against (GA)': '278', '+ / -': '68'}, {'Team Name': 'Washington Capitals', 'Year': '1992', 'Wins': '43', 'Losses': '34', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '325', 'Goals Against (GA)': '286', '+ / -': '39'}, {'Team Name': 'Winnipeg Jets', 'Year': '1992', 'Wins': '40', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.476', 'Goals For (GF)': '322', 'Goals Against (GA)': '320', '+ / -': '2'}, {'Team Name': 'Mighty Ducks of Anaheim', 'Year': '1993', 'Wins': '33', 'Losses': '46', 'OT Losses': 'Nill', 'Win %': '0.393', 'Goals For (GF)': '229', 'Goals Against (GA)': '251', '+ / -': '-22'}, {'Team Name': 'Boston Bruins', 'Year': '1993', 'Wins': '42', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '289', 'Goals Against (GA)': '252', '+ / -': '37'}, {'Team Name': 'Buffalo Sabres', 'Year': '1993', 'Wins': '43', 'Losses': '32', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '282', 'Goals Against (GA)': '218', '+ / -': '64'}, {'Team Name': 'Calgary Flames', 'Year': '1993', 'Wins': '42', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '302', 'Goals Against (GA)': '256', '+ / -': '46'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1993', 'Wins': '39', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.464', 'Goals For (GF)': '254', 'Goals Against (GA)': '240', '+ / -': '14'}, {'Team Name': 'Dallas Stars', 'Year': '1993', 'Wins': '42', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '286', 'Goals Against (GA)': '265', '+ / -': '21'}, {'Team Name': 'Detroit Red Wings', 'Year': '1993', 'Wins': '46', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.548', 'Goals For (GF)': '356', 'Goals Against (GA)': '275', '+ / -': '81'}, {'Team Name': 'Edmonton Oilers', 'Year': '1993', 'Wins': '25', 'Losses': '45', 'OT Losses': 'Nill', 'Win %': '0.298', 'Goals For (GF)': '261', 'Goals Against (GA)': '305', '+ / -': '-44'}]

In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r4=requests.get('https://www.scrapethissite.com/pages/forms/?page_num=4')
r4.status_code

200

In [12]:
soup=BeautifulSoup(r4.text,'html.parser')
web4=soup.find_all('tr',class_='team')
list4=[]
for table4 in web4:
    dic4={
        'Team Name':'',
        'Year':'',
        'Wins':'',
        'Losses':'',
        'OT Losses':'Nill',
        'Win %':'',
        'Goals For (GF)':'',
        'Goals Against (GA)':'',
        '+ / -':'',
    }
    dic4['Team Name']=table4.find('td',class_='name').text.strip()
    dic4['Year']=table4.find('td',class_='year').text.strip()
    dic4['Wins']=table4.find('td',class_='wins').text.strip()
    dic4['Losses']=table4.find('td',class_='losses').text.strip()
    dic4['Win %']=table4.find('td',class_='pct').text.strip()
    dic4['Goals For (GF)']=table4.find('td',class_='gf').text.strip()
    dic4['Goals Against (GA)']=table4.find('td',class_='ga').text.strip()
    dic4['+ / -']=table4.find('td',class_='diff').text.strip()
    #print(dic)
    list4.append(dic4)
print(list4)

[{'Team Name': 'Florida Panthers', 'Year': '1993', 'Wins': '33', 'Losses': '34', 'OT Losses': 'Nill', 'Win %': '0.393', 'Goals For (GF)': '233', 'Goals Against (GA)': '233', '+ / -': '0'}, {'Team Name': 'Hartford Whalers', 'Year': '1993', 'Wins': '27', 'Losses': '48', 'OT Losses': 'Nill', 'Win %': '0.321', 'Goals For (GF)': '227', 'Goals Against (GA)': '288', '+ / -': '-61'}, {'Team Name': 'Los Angeles Kings', 'Year': '1993', 'Wins': '27', 'Losses': '45', 'OT Losses': 'Nill', 'Win %': '0.321', 'Goals For (GF)': '294', 'Goals Against (GA)': '322', '+ / -': '-28'}, {'Team Name': 'Montreal Canadiens', 'Year': '1993', 'Wins': '41', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.488', 'Goals For (GF)': '283', 'Goals Against (GA)': '248', '+ / -': '35'}, {'Team Name': 'New Jersey Devils', 'Year': '1993', 'Wins': '47', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.56', 'Goals For (GF)': '306', 'Goals Against (GA)': '220', '+ / -': '86'}, {'Team Name': 'New York Islanders', 'Year': '1993', 'Wins': '36', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.429', 'Goals For (GF)': '282', 'Goals Against (GA)': '264', '+ / -': '18'}, {'Team Name': 'New York Rangers', 'Year': '1993', 'Wins': '52', 'Losses': '24', 'OT Losses': 'Nill', 'Win %': '0.619', 'Goals For (GF)': '299', 'Goals Against (GA)': '231', '+ / -': '68'}, {'Team Name': 'Ottawa Senators', 'Year': '1993', 'Wins': '14', 'Losses': '61', 'OT Losses': 'Nill', 'Win %': '0.167', 'Goals For (GF)': '201', 'Goals Against (GA)': '397', '+ / -': '-196'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1993', 'Wins': '35', 'Losses': '39', 'OT Losses': 'Nill', 'Win %': '0.417', 'Goals For (GF)': '294', 'Goals Against (GA)': '314', '+ / -': '-20'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1993', 'Wins': '44', 'Losses': '27', 'OT Losses': 'Nill', 'Win %': '0.524', 'Goals For (GF)': '299', 'Goals Against (GA)': '285', '+ / -': '14'}, {'Team Name': 'Quebec Nordiques', 'Year': '1993', 'Wins': '34', 'Losses': '42', 'OT Losses': 'Nill', 'Win %': '0.405', 'Goals For (GF)': '277', 'Goals Against (GA)': '292', '+ / -': '-15'}, {'Team Name': 'San Jose Sharks', 'Year': '1993', 'Wins': '33', 'Losses': '35', 'OT Losses': 'Nill', 'Win %': '0.393', 'Goals For (GF)': '252', 'Goals Against (GA)': '265', '+ / -': '-13'}, {'Team Name': 'St. Louis Blues', 'Year': '1993', 'Wins': '40', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.476', 'Goals For (GF)': '270', 'Goals Against (GA)': '283', '+ / -': '-13'}, {'Team Name': 'Tampa Bay Lightning', 'Year': '1993', 'Wins': '30', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.357', 'Goals For (GF)': '224', 'Goals Against (GA)': '251', '+ / -': '-27'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1993', 'Wins': '43', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '280', 'Goals Against (GA)': '243', '+ / -': '37'}, {'Team Name': 'Vancouver Canucks', 'Year': '1993', 'Wins': '41', 'Losses': '40', 'OT Losses': 'Nill', 'Win %': '0.488', 'Goals For (GF)': '279', 'Goals Against (GA)': '276', '+ / -': '3'}, {'Team Name': 'Washington Capitals', 'Year': '1993', 'Wins': '39', 'Losses': '35', 'OT Losses': 'Nill', 'Win %': '0.464', 'Goals For (GF)': '277', 'Goals Against (GA)': '263', '+ / -': '14'}, {'Team Name': 'Winnipeg Jets', 'Year': '1993', 'Wins': '24', 'Losses': '51', 'OT Losses': 'Nill', 'Win %': '0.286', 'Goals For (GF)': '245', 'Goals Against (GA)': '344', '+ / -': '-99'}, {'Team Name': 'Mighty Ducks of Anaheim', 'Year': '1994', 'Wins': '16', 'Losses': '27', 'OT Losses': 'Nill', 'Win %': '0.333', 'Goals For (GF)': '125', 'Goals Against (GA)': '164', '+ / -': '-39'}, {'Team Name': 'Boston Bruins', 'Year': '1994', 'Wins': '27', 'Losses': '18', 'OT Losses': 'Nill', 'Win %': '0.562', 'Goals For (GF)': '150', 'Goals Against (GA)': '127', '+ / -': '23'}, {'Team Name': 'Buffalo Sabres', 'Year': '1994', 'Wins': '22', 'Losses': '19', 'OT Losses': 'Nill', 'Win %': '0.458', 'Goals For (GF)': '130', 'Goals Against (GA)': '119', '+ / -': '11'}, {'Team Name': 'Calgary Flames', 'Year': '1994', 'Wins': '24', 'Losses': '17', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '163', 'Goals Against (GA)': '135', '+ / -': '28'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1994', 'Wins': '24', 'Losses': '19', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '156', 'Goals Against (GA)': '115', '+ / -': '41'}, {'Team Name': 'Dallas Stars', 'Year': '1994', 'Wins': '17', 'Losses': '23', 'OT Losses': 'Nill', 'Win %': '0.354', 'Goals For (GF)': '136', 'Goals Against (GA)': '135', '+ / -': '1'}, {'Team Name': 'Detroit Red Wings', 'Year': '1994', 'Wins': '33', 'Losses': '11', 'OT Losses': 'Nill', 'Win %': '0.688', 'Goals For (GF)': '180', 'Goals Against (GA)': '117', '+ / -': '63'}]

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r5=requests.get('https://www.scrapethissite.com/pages/forms/?page_num')
r5.status_code

400

In [ ]:
soup=BeautifulSoup(r5.text,'html.parser')
web5=soup.find_all('tr',class_='team')
list5=[]
for i in range(1,6):
    url=r5+i
    r=requests.get(url)
    for table5 in web5:
        dic5={
            'Team Name':'',
            'Year':'',
            'Wins':'',
            'Losses':'',
            'OT Losses':'Nill',
            'Win %':'',
            'Goals For (GF)':'',
            'Goals Against (GA)':'',
            '+ / -':'',
        }
        dic5['Team Name']=table5.find('td',class_='name').text.strip()
        dic5['Year']=table5.find('td',class_='year').text.strip()
        dic5['Wins']=table5.find('td',class_='wins').text.strip()
        dic5['Losses']=table5.find('td',class_='losses').text.strip()
        dic5['Win %']=table5.find('td',class_='pct').text.strip()
        dic5['Goals For (GF)']=table5.find('td',class_='gf').text.strip()
        dic5['Goals Against (GA)']=table5.find('td',class_='ga').text.strip()
        dic5['+ / -']=table5.find('td',class_='diff').text.strip()
    #print(dic)
        list5.append(dic5)
print(list5)

[{'Team Name': 'Edmonton Oilers', 'Year': '1994', 'Wins': '17', 'Losses': '27', 'OT Losses': 'Nill', 'Win %': '0.354', 'Goals For (GF)': '136', 'Goals Against (GA)': '183', '+ / -': '-47'}, {'Team Name': 'Florida Panthers', 'Year': '1994', 'Wins': '20', 'Losses': '22', 'OT Losses': 'Nill', 'Win %': '0.417', 'Goals For (GF)': '115', 'Goals Against (GA)': '127', '+ / -': '-12'}, {'Team Name': 'Hartford Whalers', 'Year': '1994', 'Wins': '19', 'Losses': '24', 'OT Losses': 'Nill', 'Win %': '0.396', 'Goals For (GF)': '127', 'Goals Against (GA)': '141', '+ / -': '-14'}, {'Team Name': 'Los Angeles Kings', 'Year': '1994', 'Wins': '16', 'Losses': '23', 'OT Losses': 'Nill', 'Win %': '0.333', 'Goals For (GF)': '142', 'Goals Against (GA)': '174', '+ / -': '-32'}, {'Team Name': 'Montreal Canadiens', 'Year': '1994', 'Wins': '18', 'Losses': '23', 'OT Losses': 'Nill', 'Win %': '0.375', 'Goals For (GF)': '125', 'Goals Against (GA)': '148', '+ / -': '-23'}, {'Team Name': 'New Jersey Devils', 'Year': '1994', 'Wins': '22', 'Losses': '18', 'OT Losses': 'Nill', 'Win %': '0.458', 'Goals For (GF)': '136', 'Goals Against (GA)': '121', '+ / -': '15'}, {'Team Name': 'New York Islanders', 'Year': '1994', 'Wins': '15', 'Losses': '28', 'OT Losses': 'Nill', 'Win %': '0.312', 'Goals For (GF)': '126', 'Goals Against (GA)': '158', '+ / -': '-32'}, {'Team Name': 'New York Rangers', 'Year': '1994', 'Wins': '22', 'Losses': '23', 'OT Losses': 'Nill', 'Win %': '0.458', 'Goals For (GF)': '139', 'Goals Against (GA)': '134', '+ / -': '5'}, {'Team Name': 'Ottawa Senators', 'Year': '1994', 'Wins': '9', 'Losses': '34', 'OT Losses': 'Nill', 'Win %': '0.188', 'Goals For (GF)': '117', 'Goals Against (GA)': '174', '+ / -': '-57'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1994', 'Wins': '28', 'Losses': '16', 'OT Losses': 'Nill', 'Win %': '0.583', 'Goals For (GF)': '150', 'Goals Against (GA)': '132', '+ / -': '18'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1994', 'Wins': '29', 'Losses': '16', 'OT Losses': 'Nill', 'Win %': '0.604', 'Goals For (GF)': '181', 'Goals Against (GA)': '158', '+ / -': '23'}, {'Team Name': 'Quebec Nordiques', 'Year': '1994', 'Wins': '30', 'Losses': '13', 'OT Losses': 'Nill', 'Win %': '0.625', 'Goals For (GF)': '185', 'Goals Against (GA)': '134', '+ / -': '51'}, {'Team Name': 'San Jose Sharks', 'Year': '1994', 'Wins': '19', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.396', 'Goals For (GF)': '129', 'Goals Against (GA)': '161', '+ / -': '-32'}, {'Team Name': 'St. Louis Blues', 'Year': '1994', 'Wins': '28', 'Losses': '15', 'OT Losses': 'Nill', 'Win %': '0.583', 'Goals For (GF)': '178', 'Goals Against (GA)': '135', '+ / -': '43'}, {'Team Name': 'Tampa Bay Lightning', 'Year': '1994', 'Wins': '17', 'Losses': '28', 'OT Losses': 'Nill', 'Win %': '0.354', 'Goals For (GF)': '120', 'Goals Against (GA)': '144', '+ / -': '-24'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1994', 'Wins': '21', 'Losses': '19', 'OT Losses': 'Nill', 'Win %': '0.438', 'Goals For (GF)': '135', 'Goals Against (GA)': '146', '+ / -': '-11'}, {'Team Name': 'Vancouver Canucks', 'Year': '1994', 'Wins': '18', 'Losses': '18', 'OT Losses': 'Nill', 'Win %': '0.375', 'Goals For (GF)': '153', 'Goals Against (GA)': '148', '+ / -': '5'}, {'Team Name': 'Washington Capitals', 'Year': '1994', 'Wins': '22', 'Losses': '18', 'OT Losses': 'Nill', 'Win %': '0.458', 'Goals For (GF)': '136', 'Goals Against (GA)': '120', '+ / -': '16'}, {'Team Name': 'Winnipeg Jets', 'Year': '1994', 'Wins': '16', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.333', 'Goals For (GF)': '157', 'Goals Against (GA)': '177', '+ / -': '-20'}, {'Team Name': 'Mighty Ducks of Anaheim', 'Year': '1995', 'Wins': '35', 'Losses': '39', 'OT Losses': 'Nill', 'Win %': '0.427', 'Goals For (GF)': '234', 'Goals Against (GA)': '247', '+ / -': '-13'}, {'Team Name': 'Boston Bruins', 'Year': '1995', 'Wins': '40', 'Losses': '31', 'OT Losses': 'Nill', 'Win %': '0.488', 'Goals For (GF)': '282', 'Goals Against (GA)': '269', '+ / -': '13'}, {'Team Name': 'Buffalo Sabres', 'Year': '1995', 'Wins': '33', 'Losses': '42', 'OT Losses': 'Nill', 'Win %': '0.402', 'Goals For (GF)': '247', 'Goals Against (GA)': '262', '+ / -': '-15'}, {'Team Name': 'Calgary Flames', 'Year': '1995', 'Wins': '34', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.415', 'Goals For (GF)': '241', 'Goals Against (GA)': '240', '+ / -': '1'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1995', 'Wins': '40', 'Losses': '28', 'OT Losses': 'Nill', 'Win %': '0.488', 'Goals For (GF)': '273', 'Goals Against (GA)': '220', '+ / -': '53'}, {'Team Name': 'Colorado Avalanche', 'Year': '1995', 'Wins': '47', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.573', 'Goals For (GF)': '326', 'Goals Against (GA)': '240', '+ / -': '86'}]

In [15]:
final_list=list+list2+list3+list4+list5
dg=pd.DataFrame(final_list)
dg

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,Nill,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,Nill,0.388,292,278,14
2,Calgary Flames,1990,46,26,Nill,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,Nill,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,Nill,0.425,273,298,-25
...,...,...,...,...,...,...,...,...,...
120,Boston Bruins,1995,40,31,Nill,0.488,282,269,13
121,Buffalo Sabres,1995,33,42,Nill,0.402,247,262,-15
122,Calgary Flames,1995,34,37,Nill,0.415,241,240,1
123,Chicago Blackhawks,1995,40,28,Nill,0.488,273,220,53
124,Colorado Avalanche,1995,47,25,Nill,0.573,326,240,86

In [16]:
dg.to_csv('scrapethissite_q3.csv',index=False)

## 3.4 Extract Table of first page of 100 records/rows & save into another csv file.

In [17]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r6=requests.get('https://www.scrapethissite.com/pages/forms/?per_page=100')
r6.status_code

200

In [18]:
soup=BeautifulSoup(r6.text,'html.parser')
web6=soup.find_all('tr',class_='team')
list6=[]
for table6 in web6:
    dic6={
        'Team Name':'',
        'Year':'',
        'Wins':'',
        'Losses':'',
        'OT Losses':'Nill',
        'Win %':'',
        'Goals For (GF)':'',
        'Goals Against (GA)':'',
        '+ / -':'',
    }
    dic6['Team Name']=table6.find('td',class_='name').text.strip()
    dic6['Year']=table6.find('td',class_='year').text.strip()
    dic6['Wins']=table6.find('td',class_='wins').text.strip()
    dic6['Losses']=table6.find('td',class_='losses').text.strip()
    dic6['Win %']=table6.find('td',class_='pct').text.strip()
    dic6['Goals For (GF)']=table6.find('td',class_='gf').text.strip()
    dic6['Goals Against (GA)']=table6.find('td',class_='ga').text.strip()
    dic6['+ / -']=table6.find('td',class_='diff').text.strip()
    #print(dic)
    list6.append(dic6)
print(list6)

[{'Team Name': 'Boston Bruins', 'Year': '1990', 'Wins': '44', 'Losses': '24', 'OT Losses': 'Nill', 'Win %': '0.55', 'Goals For (GF)': '299', 'Goals Against (GA)': '264', '+ / -': '35'}, {'Team Name': 'Buffalo Sabres', 'Year': '1990', 'Wins': '31', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '292', 'Goals Against (GA)': '278', '+ / -': '14'}, {'Team Name': 'Calgary Flames', 'Year': '1990', 'Wins': '46', 'Losses': '26', 'OT Losses': 'Nill', 'Win %': '0.575', 'Goals For (GF)': '344', 'Goals Against (GA)': '263', '+ / -': '81'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1990', 'Wins': '49', 'Losses': '23', 'OT Losses': 'Nill', 'Win %': '0.613', 'Goals For (GF)': '284', 'Goals Against (GA)': '211', '+ / -': '73'}, {'Team Name': 'Detroit Red Wings', 'Year': '1990', 'Wins': '34', 'Losses': '38', 'OT Losses': 'Nill', 'Win %': '0.425', 'Goals For (GF)': '273', 'Goals Against (GA)': '298', '+ / -': '-25'}, {'Team Name': 'Edmonton Oilers', 'Year': '1990', 'Wins': '37', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.463', 'Goals For (GF)': '272', 'Goals Against (GA)': '272', '+ / -': '0'}, {'Team Name': 'Hartford Whalers', 'Year': '1990', 'Wins': '31', 'Losses': '38', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '238', 'Goals Against (GA)': '276', '+ / -': '-38'}, {'Team Name': 'Los Angeles Kings', 'Year': '1990', 'Wins': '46', 'Losses': '24', 'OT Losses': 'Nill', 'Win %': '0.575', 'Goals For (GF)': '340', 'Goals Against (GA)': '254', '+ / -': '86'}, {'Team Name': 'Minnesota North Stars', 'Year': '1990', 'Wins': '27', 'Losses': '39', 'OT Losses': 'Nill', 'Win %': '0.338', 'Goals For (GF)': '256', 'Goals Against (GA)': '266', '+ / -': '-10'}, {'Team Name': 'Montreal Canadiens', 'Year': '1990', 'Wins': '39', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.487', 'Goals For (GF)': '273', 'Goals Against (GA)': '249', '+ / -': '24'}, {'Team Name': 'New Jersey Devils', 'Year': '1990', 'Wins': '32', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.4', 'Goals For (GF)': '272', 'Goals Against (GA)': '264', '+ / -': '8'}, {'Team Name': 'New York Islanders', 'Year': '1990', 'Wins': '25', 'Losses': '45', 'OT Losses': 'Nill', 'Win %': '0.312', 'Goals For (GF)': '223', 'Goals Against (GA)': '290', '+ / -': '-67'}, {'Team Name': 'New York Rangers', 'Year': '1990', 'Wins': '36', 'Losses': '31', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '297', 'Goals Against (GA)': '265', '+ / -': '32'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1990', 'Wins': '33', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.412', 'Goals For (GF)': '252', 'Goals Against (GA)': '267', '+ / -': '-15'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1990', 'Wins': '41', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '342', 'Goals Against (GA)': '305', '+ / -': '37'}, {'Team Name': 'Quebec Nordiques', 'Year': '1990', 'Wins': '16', 'Losses': '50', 'OT Losses': 'Nill', 'Win %': '0.2', 'Goals For (GF)': '236', 'Goals Against (GA)': '354', '+ / -': '-118'}, {'Team Name': 'St. Louis Blues', 'Year': '1990', 'Wins': '47', 'Losses': '22', 'OT Losses': 'Nill', 'Win %': '0.588', 'Goals For (GF)': '310', 'Goals Against (GA)': '250', '+ / -': '60'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1990', 'Wins': '23', 'Losses': '46', 'OT Losses': 'Nill', 'Win %': '0.287', 'Goals For (GF)': '241', 'Goals Against (GA)': '318', '+ / -': '-77'}, {'Team Name': 'Vancouver Canucks', 'Year': '1990', 'Wins': '28', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.35', 'Goals For (GF)': '243', 'Goals Against (GA)': '315', '+ / -': '-72'}, {'Team Name': 'Washington Capitals', 'Year': '1990', 'Wins': '37', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.463', 'Goals For (GF)': '258', 'Goals Against (GA)': '258', '+ / -': '0'}, {'Team Name': 'Winnipeg Jets', 'Year': '1990', 'Wins': '26', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.325', 'Goals For (GF)': '260', 'Goals Against (GA)': '288', '+ / -': '-28'}, {'Team Name': 'Boston Bruins', 'Year': '1991', 'Wins': '36', 'Losses': '32', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '270', 'Goals Against (GA)': '275', '+ / -': '-5'}, {'Team Name': 'Buffalo Sabres', 'Year': '1991', 'Wins': '31', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '289', 'Goals Against (GA)': '299', '+ / -': '-10'}, {'Team Name': 'Calgary Flames', 'Year': '1991', 'Wins': '31', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '296', 'Goals Against (GA)': '305', '+ / -': '-9'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1991', 'Wins': '36', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '257', 'Goals Against (GA)': '236', '+ / -': '21'}, {'Team Name': 'Detroit Red Wings', 'Year': '1991', 'Wins': '43', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.537', 'Goals For (GF)': '320', 'Goals Against (GA)': '256', '+ / -': '64'}, {'Team Name': 'Edmonton Oilers', 'Year': '1991', 'Wins': '36', 'Losses': '34', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '295', 'Goals Against (GA)': '297', '+ / -': '-2'}, {'Team Name': 'Hartford Whalers', 'Year': '1991', 'Wins': '26', 'Losses': '41', 'OT Losses': 'Nill', 'Win %': '0.325', 'Goals For (GF)': '247', 'Goals Against (GA)': '283', '+ / -': '-36'}, {'Team Name': 'Los Angeles Kings', 'Year': '1991', 'Wins': '35', 'Losses': '31', 'OT Losses': 'Nill', 'Win %': '0.438', 'Goals For (GF)': '287', 'Goals Against (GA)': '296', '+ / -': '-9'}, {'Team Name': 'Minnesota North Stars', 'Year': '1991', 'Wins': '32', 'Losses': '42', 'OT Losses': 'Nill', 'Win %': '0.4', 'Goals For (GF)': '246', 'Goals Against (GA)': '278', '+ / -': '-32'}, {'Team Name': 'Montreal Canadiens', 'Year': '1991', 'Wins': '41', 'Losses': '28', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '267', 'Goals Against (GA)': '207', '+ / -': '60'}, {'Team Name': 'New Jersey Devils', 'Year': '1991', 'Wins': '38', 'Losses': '31', 'OT Losses': 'Nill', 'Win %': '0.475', 'Goals For (GF)': '289', 'Goals Against (GA)': '259', '+ / -': '30'}, {'Team Name': 'New York Islanders', 'Year': '1991', 'Wins': '34', 'Losses': '35', 'OT Losses': 'Nill', 'Win %': '0.425', 'Goals For (GF)': '291', 'Goals Against (GA)': '299', '+ / -': '-8'}, {'Team Name': 'New York Rangers', 'Year': '1991', 'Wins': '50', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.625', 'Goals For (GF)': '321', 'Goals Against (GA)': '246', '+ / -': '75'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1991', 'Wins': '32', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.4', 'Goals For (GF)': '252', 'Goals Against (GA)': '273', '+ / -': '-21'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1991', 'Wins': '39', 'Losses': '32', 'OT Losses': 'Nill', 'Win %': '0.487', 'Goals For (GF)': '343', 'Goals Against (GA)': '308', '+ / -': '35'}, {'Team Name': 'Quebec Nordiques', 'Year': '1991', 'Wins': '20', 'Losses': '48', 'OT Losses': 'Nill', 'Win %': '0.25', 'Goals For (GF)': '255', 'Goals Against (GA)': '318', '+ / -': '-63'}, {'Team Name': 'San Jose Sharks', 'Year': '1991', 'Wins': '17', 'Losses': '58', 'OT Losses': 'Nill', 'Win %': '0.212', 'Goals For (GF)': '219', 'Goals Against (GA)': '359', '+ / -': '-140'}, {'Team Name': 'St. Louis Blues', 'Year': '1991', 'Wins': '36', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '279', 'Goals Against (GA)': '266', '+ / -': '13'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1991', 'Wins': '30', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.375', 'Goals For (GF)': '234', 'Goals Against (GA)': '294', '+ / -': '-60'}, {'Team Name': 'Vancouver Canucks', 'Year': '1991', 'Wins': '42', 'Losses': '26', 'OT Losses': 'Nill', 'Win %': '0.525', 'Goals For (GF)': '285', 'Goals Against (GA)': '250', '+ / -': '35'}, {'Team Name': 'Washington Capitals', 'Year': '1991', 'Wins': '45', 'Losses': '27', 'OT Losses': 'Nill', 'Win %': '0.562', 'Goals For (GF)': '330', 'Goals Against (GA)': '275', '+ / -': '55'}, {'Team Name': 'Winnipeg Jets', 'Year': '1991', 'Wins': '33', 'Losses': '32', 'OT Losses': 'Nill', 'Win %': '0.412', 'Goals For (GF)': '251', 'Goals Against (GA)': '244', '+ / -': '7'}, {'Team Name': 'Boston Bruins', 'Year': '1992', 'Wins': '51', 'Losses': '26', 'OT Losses': 'Nill', 'Win %': '0.607', 'Goals For (GF)': '332', 'Goals Against (GA)': '268', '+ / -': '64'}, {'Team Name': 'Buffalo Sabres', 'Year': '1992', 'Wins': '38', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.452', 'Goals For (GF)': '335', 'Goals Against (GA)': '297', '+ / -': '38'}, {'Team Name': 'Calgary Flames', 'Year': '1992', 'Wins': '43', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '322', 'Goals Against (GA)': '282', '+ / -': '40'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1992', 'Wins': '47', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.56', 'Goals For (GF)': '279', 'Goals Against (GA)': '230', '+ / -': '49'}, {'Team Name': 'Detroit Red Wings', 'Year': '1992', 'Wins': '47', 'Losses': '28', 'OT Losses': 'Nill', 'Win %': '0.56', 'Goals For (GF)': '369', 'Goals Against (GA)': '280', '+ / -': '89'}, {'Team Name': 'Edmonton Oilers', 'Year': '1992', 'Wins': '26', 'Losses': '50', 'OT Losses': 'Nill', 'Win %': '0.31', 'Goals For (GF)': '242', 'Goals Against (GA)': '337', '+ / -': '-95'}, {'Team Name': 'Hartford Whalers', 'Year': '1992', 'Wins': '26', 'Losses': '52', 'OT Losses': 'Nill', 'Win %': '0.31', 'Goals For (GF)': '284', 'Goals Against (GA)': '369', '+ / -': '-85'}, {'Team Name': 'Los Angeles Kings', 'Year': '1992', 'Wins': '39', 'Losses': '35', 'OT Losses': 'Nill', 'Win %': '0.464', 'Goals For (GF)': '338', 'Goals Against (GA)': '340', '+ / -': '-2'}, {'Team Name': 'Minnesota North Stars', 'Year': '1992', 'Wins': '36', 'Losses': '38', 'OT Losses': 'Nill', 'Win %': '0.429', 'Goals For (GF)': '272', 'Goals Against (GA)': '293', '+ / -': '-21'}, {'Team Name': 'Montreal Canadiens', 'Year': '1992', 'Wins': '48', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.571', 'Goals For (GF)': '326', 'Goals Against (GA)': '280', '+ / -': '46'}, {'Team Name': 'New Jersey Devils', 'Year': '1992', 'Wins': '40', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.476', 'Goals For (GF)': '308', 'Goals Against (GA)': '299', '+ / -': '9'}, {'Team Name': 'New York Islanders', 'Year': '1992', 'Wins': '40', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.476', 'Goals For (GF)': '335', 'Goals Against (GA)': '297', '+ / -': '38'}, {'Team Name': 'New York Rangers', 'Year': '1992', 'Wins': '34', 'Losses': '39', 'OT Losses': 'Nill', 'Win %': '0.405', 'Goals For (GF)': '304', 'Goals Against (GA)': '308', '+ / -': '-4'}, {'Team Name': 'Ottawa Senators', 'Year': '1992', 'Wins': '10', 'Losses': '70', 'OT Losses': 'Nill', 'Win %': '0.119', 'Goals For (GF)': '202', 'Goals Against (GA)': '395', '+ / -': '-193'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1992', 'Wins': '36', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.429', 'Goals For (GF)': '319', 'Goals Against (GA)': '319', '+ / -': '0'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1992', 'Wins': '56', 'Losses': '21', 'OT Losses': 'Nill', 'Win %': '0.667', 'Goals For (GF)': '367', 'Goals Against (GA)': '268', '+ / -': '99'}, {'Team Name': 'Quebec Nordiques', 'Year': '1992', 'Wins': '47', 'Losses': '27', 'OT Losses': 'Nill', 'Win %': '0.56', 'Goals For (GF)': '351', 'Goals Against (GA)': '300', '+ / -': '51'}, {'Team Name': 'San Jose Sharks', 'Year': '1992', 'Wins': '11', 'Losses': '71', 'OT Losses': 'Nill', 'Win %': '0.131', 'Goals For (GF)': '218', 'Goals Against (GA)': '414', '+ / -': '-196'}, {'Team Name': 'St. Louis Blues', 'Year': '1992', 'Wins': '37', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.44', 'Goals For (GF)': '282', 'Goals Against (GA)': '278', '+ / -': '4'}, {'Team Name': 'Tampa Bay Lightning', 'Year': '1992', 'Wins': '23', 'Losses': '54', 'OT Losses': 'Nill', 'Win %': '0.274', 'Goals For (GF)': '245', 'Goals Against (GA)': '332', '+ / -': '-87'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1992', 'Wins': '44', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.524', 'Goals For (GF)': '288', 'Goals Against (GA)': '241', '+ / -': '47'}, {'Team Name': 'Vancouver Canucks', 'Year': '1992', 'Wins': '46', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.548', 'Goals For (GF)': '346', 'Goals Against (GA)': '278', '+ / -': '68'}, {'Team Name': 'Washington Capitals', 'Year': '1992', 'Wins': '43', 'Losses': '34', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '325', 'Goals Against (GA)': '286', '+ / -': '39'}, {'Team Name': 'Winnipeg Jets', 'Year': '1992', 'Wins': '40', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.476', 'Goals For (GF)': '322', 'Goals Against (GA)': '320', '+ / -': '2'}, {'Team Name': 'Mighty Ducks of Anaheim', 'Year': '1993', 'Wins': '33', 'Losses': '46', 'OT Losses': 'Nill', 'Win %': '0.393', 'Goals For (GF)': '229', 'Goals Against (GA)': '251', '+ / -': '-22'}, {'Team Name': 'Boston Bruins', 'Year': '1993', 'Wins': '42', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '289', 'Goals Against (GA)': '252', '+ / -': '37'}, {'Team Name': 'Buffalo Sabres', 'Year': '1993', 'Wins': '43', 'Losses': '32', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '282', 'Goals Against (GA)': '218', '+ / -': '64'}, {'Team Name': 'Calgary Flames', 'Year': '1993', 'Wins': '42', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '302', 'Goals Against (GA)': '256', '+ / -': '46'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1993', 'Wins': '39', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.464', 'Goals For (GF)': '254', 'Goals Against (GA)': '240', '+ / -': '14'}, {'Team Name': 'Dallas Stars', 'Year': '1993', 'Wins': '42', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '286', 'Goals Against (GA)': '265', '+ / -': '21'}, {'Team Name': 'Detroit Red Wings', 'Year': '1993', 'Wins': '46', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.548', 'Goals For (GF)': '356', 'Goals Against (GA)': '275', '+ / -': '81'}, {'Team Name': 'Edmonton Oilers', 'Year': '1993', 'Wins': '25', 'Losses': '45', 'OT Losses': 'Nill', 'Win %': '0.298', 'Goals For (GF)': '261', 'Goals Against (GA)': '305', '+ / -': '-44'}, {'Team Name': 'Florida Panthers', 'Year': '1993', 'Wins': '33', 'Losses': '34', 'OT Losses': 'Nill', 'Win %': '0.393', 'Goals For (GF)': '233', 'Goals Against (GA)': '233', '+ / -': '0'}, {'Team Name': 'Hartford Whalers', 'Year': '1993', 'Wins': '27', 'Losses': '48', 'OT Losses': 'Nill', 'Win %': '0.321', 'Goals For (GF)': '227', 'Goals Against (GA)': '288', '+ / -': '-61'}, {'Team Name': 'Los Angeles Kings', 'Year': '1993', 'Wins': '27', 'Losses': '45', 'OT Losses': 'Nill', 'Win %': '0.321', 'Goals For (GF)': '294', 'Goals Against (GA)': '322', '+ / -': '-28'}, {'Team Name': 'Montreal Canadiens', 'Year': '1993', 'Wins': '41', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.488', 'Goals For (GF)': '283', 'Goals Against (GA)': '248', '+ / -': '35'}, {'Team Name': 'New Jersey Devils', 'Year': '1993', 'Wins': '47', 'Losses': '25', 'OT Losses': 'Nill', 'Win %': '0.56', 'Goals For (GF)': '306', 'Goals Against (GA)': '220', '+ / -': '86'}, {'Team Name': 'New York Islanders', 'Year': '1993', 'Wins': '36', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.429', 'Goals For (GF)': '282', 'Goals Against (GA)': '264', '+ / -': '18'}, {'Team Name': 'New York Rangers', 'Year': '1993', 'Wins': '52', 'Losses': '24', 'OT Losses': 'Nill', 'Win %': '0.619', 'Goals For (GF)': '299', 'Goals Against (GA)': '231', '+ / -': '68'}, {'Team Name': 'Ottawa Senators', 'Year': '1993', 'Wins': '14', 'Losses': '61', 'OT Losses': 'Nill', 'Win %': '0.167', 'Goals For (GF)': '201', 'Goals Against (GA)': '397', '+ / -': '-196'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1993', 'Wins': '35', 'Losses': '39', 'OT Losses': 'Nill', 'Win %': '0.417', 'Goals For (GF)': '294', 'Goals Against (GA)': '314', '+ / -': '-20'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1993', 'Wins': '44', 'Losses': '27', 'OT Losses': 'Nill', 'Win %': '0.524', 'Goals For (GF)': '299', 'Goals Against (GA)': '285', '+ / -': '14'}, {'Team Name': 'Quebec Nordiques', 'Year': '1993', 'Wins': '34', 'Losses': '42', 'OT Losses': 'Nill', 'Win %': '0.405', 'Goals For (GF)': '277', 'Goals Against (GA)': '292', '+ / -': '-15'}, {'Team Name': 'San Jose Sharks', 'Year': '1993', 'Wins': '33', 'Losses': '35', 'OT Losses': 'Nill', 'Win %': '0.393', 'Goals For (GF)': '252', 'Goals Against (GA)': '265', '+ / -': '-13'}, {'Team Name': 'St. Louis Blues', 'Year': '1993', 'Wins': '40', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.476', 'Goals For (GF)': '270', 'Goals Against (GA)': '283', '+ / -': '-13'}, {'Team Name': 'Tampa Bay Lightning', 'Year': '1993', 'Wins': '30', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.357', 'Goals For (GF)': '224', 'Goals Against (GA)': '251', '+ / -': '-27'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1993', 'Wins': '43', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '280', 'Goals Against (GA)': '243', '+ / -': '37'}, {'Team Name': 'Vancouver Canucks', 'Year': '1993', 'Wins': '41', 'Losses': '40', 'OT Losses': 'Nill', 'Win %': '0.488', 'Goals For (GF)': '279', 'Goals Against (GA)': '276', '+ / -': '3'}, {'Team Name': 'Washington Capitals', 'Year': '1993', 'Wins': '39', 'Losses': '35', 'OT Losses': 'Nill', 'Win %': '0.464', 'Goals For (GF)': '277', 'Goals Against (GA)': '263', '+ / -': '14'}, {'Team Name': 'Winnipeg Jets', 'Year': '1993', 'Wins': '24', 'Losses': '51', 'OT Losses': 'Nill', 'Win %': '0.286', 'Goals For (GF)': '245', 'Goals Against (GA)': '344', '+ / -': '-99'}, {'Team Name': 'Mighty Ducks of Anaheim', 'Year': '1994', 'Wins': '16', 'Losses': '27', 'OT Losses': 'Nill', 'Win %': '0.333', 'Goals For (GF)': '125', 'Goals Against (GA)': '164', '+ / -': '-39'}, {'Team Name': 'Boston Bruins', 'Year': '1994', 'Wins': '27', 'Losses': '18', 'OT Losses': 'Nill', 'Win %': '0.562', 'Goals For (GF)': '150', 'Goals Against (GA)': '127', '+ / -': '23'}, {'Team Name': 'Buffalo Sabres', 'Year': '1994', 'Wins': '22', 'Losses': '19', 'OT Losses': 'Nill', 'Win %': '0.458', 'Goals For (GF)': '130', 'Goals Against (GA)': '119', '+ / -': '11'}, {'Team Name': 'Calgary Flames', 'Year': '1994', 'Wins': '24', 'Losses': '17', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '163', 'Goals Against (GA)': '135', '+ / -': '28'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1994', 'Wins': '24', 'Losses': '19', 'OT Losses': 'Nill', 'Win %': '0.5', 'Goals For (GF)': '156', 'Goals Against (GA)': '115', '+ / -': '41'}, {'Team Name': 'Dallas Stars', 'Year': '1994', 'Wins': '17', 'Losses': '23', 'OT Losses': 'Nill', 'Win %': '0.354', 'Goals For (GF)': '136', 'Goals Against (GA)': '135', '+ / -': '1'}, {'Team Name': 'Detroit Red Wings', 'Year': '1994', 'Wins': '33', 'Losses': '11', 'OT Losses': 'Nill', 'Win %': '0.688', 'Goals For (GF)': '180', 'Goals Against (GA)': '117', '+ / -': '63'}]

In [19]:
dj=pd.DataFrame(list6)
dj

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,Nill,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,Nill,0.388,292,278,14
2,Calgary Flames,1990,46,26,Nill,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,Nill,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,Nill,0.425,273,298,-25
...,...,...,...,...,...,...,...,...,...
95,Buffalo Sabres,1994,22,19,Nill,0.458,130,119,11
96,Calgary Flames,1994,24,17,Nill,0.5,163,135,28
97,Chicago Blackhawks,1994,24,19,Nill,0.5,156,115,41
98,Dallas Stars,1994,17,23,Nill,0.354,136,135,1
99,Detroit Red Wings,1994,33,11,Nill,0.688,180,117,63

In [20]:
dj.to_csv('scrapethissite_q4.csv',index=False)