# Practice

In [1]:
import requests
from bs4 import BeautifulSoup
web=requests.get('https://webscraper.io/test-sites')
web.status_code

200

In [81]:
var_dic={
    "product_name":"",
    "product_para":"",
    "product_index":"1",
    "product_url":"",
    "product_img":"",
}
var_dic

{'product_name': '',
 'product_para': '',
 'product_index': '1',
 'product_url': '',
 'product_img': ''}

In [29]:
soup=BeautifulSoup(web.text,'html.parser')
var=soup.find('div',class_='row test-site')
print(var.prettify())

<div class="row test-site">
 <div class="col-lg-7 order-lg-2">
  <h2 class="site-heading">
   <a href="/test-sites/e-commerce/allinone">
    E-commerce site
   </a>
  </h2>
  <p class="lead">
   E-commerce site with multiple categories, subcategories.
					All items are loaded in one page.
  </p>
 </div>
 <div class="col-lg-5 order-lg-1">
  <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
 </div>
</div>

In [82]:
var_dic['product_name']=var.find('h2').text.strip()
var_dic

{'product_name': 'E-commerce site',
 'product_para': '',
 'product_index': '1',
 'product_url': '',
 'product_img': ''}

In [83]:
var_dic['product_url']=var.find('a')['href']
var_dic

{'product_name': 'E-commerce site',
 'product_para': '',
 'product_index': '1',
 'product_url': '/test-sites/e-commerce/allinone',
 'product_img': ''}

In [84]:
var_dic['product_para']=var.find('p').text.replace('\n',' ').replace('\t','')
var_dic

{'product_name': 'E-commerce site',
 'product_para': ' E-commerce site with multiple categories, subcategories. All items are loaded in one page. ',
 'product_index': '1',
 'product_url': '/test-sites/e-commerce/allinone',
 'product_img': ''}

In [97]:
var_dic['product_img']=var.find('img')['src']
var_dic

{'product_name': 'E-commerce site',
 'product_para': ' E-commerce site with multiple categories, subcategories. All items are loaded in one page. ',
 'product_index': '1',
 'product_url': '/test-sites/e-commerce/allinone',
 'product_img': '/images/test-sites/screens/test-sites-ecommerce-allinone.png'}

In [ ]:
import pandas as pd
list=[var_dic]
df=pd.DataFrame(list)
df

,product_name,product_para,product_index,product_url,product_img
0,E-commerce site,"E-commerce site with multiple categories, sub...",1,/test-sites/e-commerce/allinone,/images/test-sites/screens/test-sites-ecommerc...

In [100]:
df.to_csv('data_product.csv',index=False)

# Second Product

In [128]:
var1=soup.find_all('div',class_='row test-site')
second_product=var1[1]
second_product

<div class="row test-site">
<div class="col-lg-7 order-lg-2">
<h2 class="site-heading">
<a href="/test-sites/e-commerce/static">
						E-commerce site with pagination links
					</a>
</h2>
<p class="lead">
					E-commerce site with multiple categories, subcategories.
					Standard links are used for pagination.
				</p>
</div>
<div class="col-lg-5 order-lg-1">
<img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-static.png"/>
</div>
</div>

In [108]:
var_dic2={
    "product_name":"",
    "product_para":"",
    "product_url":"",
    "product_img":"",
    "product_index":"2",
}
var_dic2

{'product_name': '',
 'product_para': '',
 'product_url': '',
 'product_img': '',
 'product_index': '2'}

In [130]:
var_dic2['product_name']=second_product.find('h2').text.strip()
var_dic2

{'product_name': 'E-commerce site with pagination links',
 'product_para': '',
 'product_url': '',
 'product_img': '',
 'product_index': '2'}

In [132]:
var_dic2['product_para']=second_product.find('p').text.replace('\n',' ').replace('\t',"")
var_dic2

{'product_name': 'E-commerce site with pagination links',
 'product_para': ' E-commerce site with multiple categories, subcategories. Standard links are used for pagination. ',
 'product_url': '',
 'product_img': '',
 'product_index': '2'}

In [133]:
var_dic2['product_url']=second_product.find('a')['href']
var_dic2

{'product_name': 'E-commerce site with pagination links',
 'product_para': ' E-commerce site with multiple categories, subcategories. Standard links are used for pagination. ',
 'product_url': '/test-sites/e-commerce/static',
 'product_img': '',
 'product_index': '2'}

In [137]:
var_dic2['product_img']=second_product.find('img')['src']
var_dic2

{'product_name': 'E-commerce site with pagination links',
 'product_para': ' E-commerce site with multiple categories, subcategories. Standard links are used for pagination. ',
 'product_url': '/test-sites/e-commerce/static',
 'product_img': '/images/test-sites/screens/test-sites-ecommerce-static.png',
 'product_index': '2'}

# All products list

In [4]:
import requests
from bs4 import BeautifulSoup
r=requests.get('https://webscraper.io/test-sites')
r.status_code

200

In [14]:
soup=BeautifulSoup(r.text,'html.parser')
website=soup.find_all('div',class_='row test-site')
list3=[]
for div in website:
    detail={
        'product_name':'',
        'product_para':'',
        'product_url':'',
        'product_iamge':'',
    }
    detail['product_name']=div.find('h2').text.strip()
    detail['product_para']=div.find('p').text.replace('\n'," ").replace("\t","")
    detail['product_url']=div.find('a')['href']
    detail['product_iamge']=div.find('img')['src']
    print(detail)
    list3.append(detail)

{'product_name': 'E-commerce site', 'product_para': ' E-commerce site with multiple categories, subcategories. All items are loaded in one page. ', 'product_url': '/test-sites/e-commerce/allinone', 'product_iamge': '/images/test-sites/screens/test-sites-ecommerce-allinone.png'}
{'product_name': 'E-commerce site with pagination links', 'product_para': ' E-commerce site with multiple categories, subcategories. Standard links are used for pagination. ', 'product_url': '/test-sites/e-commerce/static', 'product_iamge': '/images/test-sites/screens/test-sites-ecommerce-static.png'}
{'product_name': 'E-commerce site with AJAX pagination links', 'product_para': ' E-commerce site with multiple categories, subcategories. Dynamic links that use data without reloading the page for pagination. ', 'product_url': '/test-sites/e-commerce/ajax', 'product_iamge': '/images/test-sites/screens/test-sites-ecommerce-ajax.png'}
{'product_name': 'E-commerce site with "Load more" buttons', 'product_para': ' E-commerce site with multiple categories, subcategories. Instead of using pagination this site uses a "Load more" button to load more items. ', 'product_url': '/test-sites/e-commerce/more', 'product_iamge': '/images/test-sites/screens/test-sites-ecommerce-more.png'}
{'product_name': 'E-commerce site that loads items while scrolling', 'product_para': ' E-commerce site with multiple categories, subcategories. Instead of using pagination this site loads items when user scrolls the page down. ', 'product_url': '/test-sites/e-commerce/scroll', 'product_iamge': '/images/test-sites/screens/test-sites-ecommerce-allinone.png'}
{'product_name': 'Table playground', 'product_para': ' This page contains multiple tables. You can train using Table selector here. ', 'product_url': '/test-sites/tables', 'product_iamge': '/images/test-sites/screens/test-sites-tables.png'}

In [15]:
import pandas as pd
dg=pd.DataFrame(list3)
dg

,product_name,product_para,product_url,product_iamge
0,E-commerce site,"E-commerce site with multiple categories, sub...",/test-sites/e-commerce/allinone,/images/test-sites/screens/test-sites-ecommerc...
1,E-commerce site with pagination links,"E-commerce site with multiple categories, sub...",/test-sites/e-commerce/static,/images/test-sites/screens/test-sites-ecommerc...
2,E-commerce site with AJAX pagination links,"E-commerce site with multiple categories, sub...",/test-sites/e-commerce/ajax,/images/test-sites/screens/test-sites-ecommerc...
3,"E-commerce site with ""Load more"" buttons","E-commerce site with multiple categories, sub...",/test-sites/e-commerce/more,/images/test-sites/screens/test-sites-ecommerc...
4,E-commerce site that loads items while scrolling,"E-commerce site with multiple categories, sub...",/test-sites/e-commerce/scroll,/images/test-sites/screens/test-sites-ecommerc...
5,Table playground,This page contains multiple tables. You can t...,/test-sites/tables,/images/test-sites/screens/test-sites-tables.png

In [17]:
dg.to_csv('products.csv',index=False)

## 4.1 Extract first Table of a page & save into csv file.

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r=requests.get('https://webscraper.io/test-sites/tables')
r.status_code

200

In [7]:
soup=BeautifulSoup(r.text,'html.parser')
web=soup.find('table',class_='table table-bordered')
rows=web.find('tbody').find_all('tr')
list=[]
for tr in rows:
    col=tr.find_all('td')
    dic={
        '#':col[0].text.strip(),
        'Firsname':col[1].text.strip(),
        'Lastname':col[2].text.strip(),
        'Username':col[3].text.strip(),
    }
    list.append(dic)
print(list)

[{'#': '1', 'Firsname': 'Mark', 'Lastname': 'Otto', 'Username': '@mdo'}, {'#': '2', 'Firsname': 'Jacob', 'Lastname': 'Thornton', 'Username': '@fat'}, {'#': '3', 'Firsname': 'Larry', 'Lastname': 'the Bird', 'Username': '@twitter'}]

In [14]:
df=pd.DataFrame(list)
df

   # Firsname  Lastname  Username
0  1     Mark      Otto      @mdo
1  2    Jacob  Thornton      @fat
2  3    Larry  the Bird  @twitter

In [16]:
df.to_csv('webscraperd_q1.csv',index=False)

## 4.2 Extract second Table of a page & save into another csv file.

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r2=requests.get('https://webscraper.io/test-sites/tables')
r2.status_code

200

In [9]:
soup=BeautifulSoup(r2.text,'html.parser')
web2=soup.find('table',class_='table table-bordered table-bordered2')
rows2=web2.find('tbody').find_all('tr')
list2=[]
for tr2 in rows2:
    col2=tr2.find_all('td')
    dic2={
        '#':col2[0].text.strip(),
        'Firsname':col2[1].text.strip(),
        'Lastname':col2[2].text.strip(),
        'Username':col2[3].text.strip(),
    }
    list2.append(dic2)
print(list2)

[{'#': '4', 'Firsname': 'Harry', 'Lastname': 'Potter', 'Username': '@hp'}, {'#': '5', 'Firsname': 'John', 'Lastname': 'Snow', 'Username': '@dunno'}, {'#': '6', 'Firsname': 'Tim', 'Lastname': 'Bean', 'Username': '@timbean'}]

In [10]:
df=pd.DataFrame(list2)
df

   # Firsname Lastname  Username
0  4    Harry   Potter       @hp
1  5     John     Snow    @dunno
2  6      Tim     Bean  @timbean

In [12]:
df.to_csv('webscraper_q2.csv',index=False)

## 4.3 Extract both Tables of a page & save into single csv file.

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r2=requests.get('https://webscraper.io/test-sites/tables')
r2.status_code

200

In [4]:
soup=BeautifulSoup(r2.text,'html.parser')
page=soup.find('div',class_='tables-semantically-correct')
web2=page.find('table',class_='table table-bordered table-bordered2')
rows2=web2.find('tbody').find_all('tr')
list2=[]
for tr2 in rows2:
    col2=tr2.find_all('td')
    dic2={
        '#':col2[0].text.strip(),
        'Firsname':col2[1].text.strip(),
        'Lastname':col2[2].text.strip(),
        'Username':col2[3].text.strip(),
    }
    list2.append(dic2)
print(list2)

[{'#': '4', 'Firsname': 'Harry', 'Lastname': 'Potter', 'Username': '@hp'}, {'#': '5', 'Firsname': 'John', 'Lastname': 'Snow', 'Username': '@dunno'}, {'#': '6', 'Firsname': 'Tim', 'Lastname': 'Bean', 'Username': '@timbean'}]

In [10]:
final_list=list+list2
df=pd.DataFrame(final_list)
df

   # Firsname  Lastname  Username
0  1     Mark      Otto      @mdo
1  2    Jacob  Thornton      @fat
2  3    Larry  the Bird  @twitter
3  4    Harry    Potter       @hp
4  5     John      Snow    @dunno
5  6      Tim      Bean  @timbean

In [18]:
df.to_csv('webscraper_q3.csv',index=False)

## 5.1 Extract first country details of a page & save into csv file. e.g# Andorra (coutry_name, Capital, Population, Area)

In [27]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r=requests.get('https://www.scrapethissite.com/pages/simple/')
r.status_code

200

In [50]:
soup=BeautifulSoup(r.text,'html.parser')
#country=soup.find('div',class_='row')
div=soup.find('div',class_='col-md-4 country')
d=[]
dictionary={
        'country_name':'',
        'Capital:':'',
        'Population:':'',
        'Area (km2):':'',

    }
dictionary['country_name']=div.find('h3',class_='country-name').text.strip()
dictionary['Capital:']=div.find('span',class_='country-capital').text.strip()
dictionary['Population:']=div.find('span',class_='country-population').text.strip()
dictionary['Area (km2):']=div.find('span',class_='country-area').text.strip()
#print(dictionary)
d.append(dictionary)
d

[{'country_name': 'Andorra',
  'Capital:': 'Andorra la Vella',
  'Population:': '84000',
  'Area (km2):': '468.0'}]

## 5.2 Extract country details of a first row of a page & save into csv file. e.g# Andorra, United Arab Emirates, Afghanistan``

In [76]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r1=requests.get('https://www.scrapethissite.com/pages/simple/')
soup=BeautifulSoup(r1.text,'html.parser')
row=soup.find_all('div',class_='row')
var=row[3]
var
d2=[]
for i in var.find_all('div',class_='col-md-4 country'):
    dictionary2={
        'country_name':'',
        'Capital:':'',
        'Population:':'',
        'Area (km2):':'',

    }
    dictionary2['country_name']=i.find('h3',class_='country-name').text.strip()
    dictionary2['Capital:']=i.find('span',class_='country-capital').text.strip()
    dictionary2['Population:']=i.find('span',class_='country-population').text.strip()
    dictionary2['Area (km2):']=i.find('span',class_='country-area').text.strip()
    #print(dictionary2)
    d2.append(dictionary2)
print(d2)

[{'country_name': 'Andorra', 'Capital:': 'Andorra la Vella', 'Population:': '84000', 'Area (km2):': '468.0'}, {'country_name': 'United Arab Emirates', 'Capital:': 'Abu Dhabi', 'Population:': '4975593', 'Area (km2):': '82880.0'}, {'country_name': 'Afghanistan', 'Capital:': 'Kabul', 'Population:': '29121286', 'Area (km2):': '647500.0'}]

## 5.3 Extract all country details of a page & save into csv file.

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r1=requests.get('https://www.scrapethissite.com/pages/simple/')
soup=BeautifulSoup(r1.text,'html.parser')
row=soup.find_all('div',class_='col-md-4 country')
row
d3=[]
for i in row:
    dictionary3={
        'country_name':'',
        'Capital:':'',
        'Population:':'',
        'Area (km2):':'',

    }
    dictionary3['country_name']=i.find('h3',class_='country-name').text.strip()
    dictionary3['Capital:']=i.find('span',class_='country-capital').text.strip()
    dictionary3['Population:']=i.find('span',class_='country-population').text.strip()
    dictionary3['Area (km2):']=i.find('span',class_='country-area').text.strip()
    #print(dictionary2)
    d3.append(dictionary3)
print(d3)

[{'country_name': 'Andorra', 'Capital:': 'Andorra la Vella', 'Population:': '84000', 'Area (km2):': '468.0'}, {'country_name': 'United Arab Emirates', 'Capital:': 'Abu Dhabi', 'Population:': '4975593', 'Area (km2):': '82880.0'}, {'country_name': 'Afghanistan', 'Capital:': 'Kabul', 'Population:': '29121286', 'Area (km2):': '647500.0'}, {'country_name': 'Antigua and Barbuda', 'Capital:': "St. John's", 'Population:': '86754', 'Area (km2):': '443.0'}, {'country_name': 'Anguilla', 'Capital:': 'The Valley', 'Population:': '13254', 'Area (km2):': '102.0'}, {'country_name': 'Albania', 'Capital:': 'Tirana', 'Population:': '2986952', 'Area (km2):': '28748.0'}, {'country_name': 'Armenia', 'Capital:': 'Yerevan', 'Population:': '2968000', 'Area (km2):': '29800.0'}, {'country_name': 'Angola', 'Capital:': 'Luanda', 'Population:': '13068161', 'Area (km2):': '1246700.0'}, {'country_name': 'Antarctica', 'Capital:': 'None', 'Population:': '0', 'Area (km2):': '1.4E7'}, {'country_name': 'Argentina', 'Capital:': 'Buenos Aires', 'Population:': '41343201', 'Area (km2):': '2766890.0'}, {'country_name': 'American Samoa', 'Capital:': 'Pago Pago', 'Population:': '57881', 'Area (km2):': '199.0'}, {'country_name': 'Austria', 'Capital:': 'Vienna', 'Population:': '8205000', 'Area (km2):': '83858.0'}, {'country_name': 'Australia', 'Capital:': 'Canberra', 'Population:': '21515754', 'Area (km2):': '7686850.0'}, {'country_name': 'Aruba', 'Capital:': 'Oranjestad', 'Population:': '71566', 'Area (km2):': '193.0'}, {'country_name': 'Åland', 'Capital:': 'Mariehamn', 'Population:': '26711', 'Area (km2):': '1580.0'}, {'country_name': 'Azerbaijan', 'Capital:': 'Baku', 'Population:': '8303512', 'Area (km2):': '86600.0'}, {'country_name': 'Bosnia and Herzegovina', 'Capital:': 'Sarajevo', 'Population:': '4590000', 'Area (km2):': '51129.0'}, {'country_name': 'Barbados', 'Capital:': 'Bridgetown', 'Population:': '285653', 'Area (km2):': '431.0'}, {'country_name': 'Bangladesh', 'Capital:': 'Dhaka', 'Population:': '156118464', 'Area (km2):': '144000.0'}, {'country_name': 'Belgium', 'Capital:': 'Brussels', 'Population:': '10403000', 'Area (km2):': '30510.0'}, {'country_name': 'Burkina Faso', 'Capital:': 'Ouagadougou', 'Population:': '16241811', 'Area (km2):': '274200.0'}, {'country_name': 'Bulgaria', 'Capital:': 'Sofia', 'Population:': '7148785', 'Area (km2):': '110910.0'}, {'country_name': 'Bahrain', 'Capital:': 'Manama', 'Population:': '738004', 'Area (km2):': '665.0'}, {'country_name': 'Burundi', 'Capital:': 'Bujumbura', 'Population:': '9863117', 'Area (km2):': '27830.0'}, {'country_name': 'Benin', 'Capital:': 'Porto-Novo', 'Population:': '9056010', 'Area (km2):': '112620.0'}, {'country_name': 'Saint Barthélemy', 'Capital:': 'Gustavia', 'Population:': '8450', 'Area (km2):': '21.0'}, {'country_name': 'Bermuda', 'Capital:': 'Hamilton', 'Population:': '65365', 'Area (km2):': '53.0'}, {'country_name': 'Brunei', 'Capital:': 'Bandar Seri Begawan', 'Population:': '395027', 'Area (km2):': '5770.0'}, {'country_name': 'Bolivia', 'Capital:': 'Sucre', 'Population:': '9947418', 'Area (km2):': '1098580.0'}, {'country_name': 'Bonaire', 'Capital:': 'Kralendijk', 'Population:': '18012', 'Area (km2):': '328.0'}, {'country_name': 'Brazil', 'Capital:': 'Brasília', 'Population:': '201103330', 'Area (km2):': '8511965.0'}, {'country_name': 'Bahamas', 'Capital:': 'Nassau', 'Population:': '301790', 'Area (km2):': '13940.0'}, {'country_name': 'Bhutan', 'Capital:': 'Thimphu', 'Population:': '699847', 'Area (km2):': '47000.0'}, {'country_name': 'Bouvet Island', 'Capital:': 'None', 'Population:': '0', 'Area (km2):': '49.0'}, {'country_name': 'Botswana', 'Capital:': 'Gaborone', 'Population:': '2029307', 'Area (km2):': '600370.0'}, {'country_name': 'Belarus', 'Capital:': 'Minsk', 'Population:': '9685000', 'Area (km2):': '207600.0'}, {'country_name': 'Belize', 'Capital:': 'Belmopan', 'Population:': '314522', 'Area (km2):': '22966.0'}, {'country_name': 'Canada', 'Capital:': 'Ottawa', 'Population:': '33679000', 'Area (km2):': '9984670.0'}, {'country_name': 'Cocos [Keeling] Islands', 'Capital:': 'West Island', 'Population:': '628', 'Area (km2):': '14.0'}, {'country_name': 'Democratic Republic of the Congo', 'Capital:': 'Kinshasa', 'Population:': '70916439', 'Area (km2):': '2345410.0'}, {'country_name': 'Central African Republic', 'Capital:': 'Bangui', 'Population:': '4844927', 'Area (km2):': '622984.0'}, {'country_name': 'Republic of the Congo', 'Capital:': 'Brazzaville', 'Population:': '3039126', 'Area (km2):': '342000.0'}, {'country_name': 'Switzerland', 'Capital:': 'Bern', 'Population:': '7581000', 'Area (km2):': '41290.0'}, {'country_name': 'Ivory Coast', 'Capital:': 'Yamoussoukro', 'Population:': '21058798', 'Area (km2):': '322460.0'}, {'country_name': 'Cook Islands', 'Capital:': 'Avarua', 'Population:': '21388', 'Area (km2):': '240.0'}, {'country_name': 'Chile', 'Capital:': 'Santiago', 'Population:': '16746491', 'Area (km2):': '756950.0'}, {'country_name': 'Cameroon', 'Capital:': 'Yaoundé', 'Population:': '19294149', 'Area (km2):': '475440.0'}, {'country_name': 'China', 'Capital:': 'Beijing', 'Population:': '1330044000', 'Area (km2):': '9596960.0'}, {'country_name': 'Colombia', 'Capital:': 'Bogotá', 'Population:': '47790000', 'Area (km2):': '1138910.0'}, {'country_name': 'Costa Rica', 'Capital:': 'San José', 'Population:': '4516220', 'Area (km2):': '51100.0'}, {'country_name': 'Cuba', 'Capital:': 'Havana', 'Population:': '11423000', 'Area (km2):': '110860.0'}, {'country_name': 'Cape Verde', 'Capital:': 'Praia', 'Population:': '508659', 'Area (km2):': '4033.0'}, {'country_name': 'Curacao', 'Capital:': 'Willemstad', 'Population:': '141766', 'Area (km2):': '444.0'}, {'country_name': 'Christmas Island', 'Capital:': 'Flying Fish Cove', 'Population:': '1500', 'Area (km2):': '135.0'}, {'country_name': 'Cyprus', 'Capital:': 'Nicosia', 'Population:': '1102677', 'Area (km2):': '9250.0'}, {'country_name': 'Czech Republic', 'Capital:': 'Prague', 'Population:': '10476000', 'Area (km2):': '78866.0'}, {'country_name': 'Germany', 'Capital:': 'Berlin', 'Population:': '81802257', 'Area (km2):': '357021.0'}, {'country_name': 'Djibouti', 'Capital:': 'Djibouti', 'Population:': '740528', 'Area (km2):': '23000.0'}, {'country_name': 'Denmark', 'Capital:': 'Copenhagen', 'Population:': '5484000', 'Area (km2):': '43094.0'}, {'country_name': 'Dominica', 'Capital:': 'Roseau', 'Population:': '72813', 'Area (km2):': '754.0'}, {'country_name': 'Dominican Republic', 'Capital:': 'Santo Domingo', 'Population:': '9823821', 'Area (km2):': '48730.0'}, {'country_name': 'Algeria', 'Capital:': 'Algiers', 'Population:': '34586184', 'Area (km2):': '2381740.0'}, {'country_name': 'Ecuador', 'Capital:': 'Quito', 'Population:': '14790608', 'Area (km2):': '283560.0'}, {'country_name': 'Estonia', 'Capital:': 'Tallinn', 'Population:': '1291170', 'Area (km2):': '45226.0'}, {'country_name': 'Egypt', 'Capital:': 'Cairo', 'Population:': '80471869', 'Area (km2):': '1001450.0'}, {'country_name': 'Western Sahara', 'Capital:': 'Laâyoune / El Aaiún', 'Population:': '273008', 'Area (km2):': '266000.0'}, {'country_name': 'Eritrea', 'Capital:': 'Asmara', 'Population:': '5792984', 'Area (km2):': '121320.0'}, {'country_name': 'Spain', 'Capital:': 'Madrid', 'Population:': '46505963', 'Area (km2):': '504782.0'}, {'country_name': 'Ethiopia', 'Capital:': 'Addis Ababa', 'Population:': '88013491', 'Area (km2):': '1127127.0'}, {'country_name': 'Finland', 'Capital:': 'Helsinki', 'Population:': '5244000', 'Area (km2):': '337030.0'}, {'country_name': 'Fiji', 'Capital:': 'Suva', 'Population:': '875983', 'Area (km2):': '18270.0'}, {'country_name': 'Falkland Islands', 'Capital:': 'Stanley', 'Population:': '2638', 'Area (km2):': '12173.0'}, {'country_name': 'Micronesia', 'Capital:': 'Palikir', 'Population:': '107708', 'Area (km2):': '702.0'}, {'country_name': 'Faroe Islands', 'Capital:': 'Tórshavn', 'Population:': '48228', 'Area (km2):': '1399.0'}, {'country_name': 'France', 'Capital:': 'Paris', 'Population:': '64768389', 'Area (km2):': '547030.0'}, {'country_name': 'Gabon', 'Capital:': 'Libreville', 'Population:': '1545255', 'Area (km2):': '267667.0'}, {'country_name': 'United Kingdom', 'Capital:': 'London', 'Population:': '62348447', 'Area (km2):': '244820.0'}, {'country_name': 'Grenada', 'Capital:': "St. George's", 'Population:': '107818', 'Area (km2):': '344.0'}, {'country_name': 'Georgia', 'Capital:': 'Tbilisi', 'Population:': '4630000', 'Area (km2):': '69700.0'}, {'country_name': 'French Guiana', 'Capital:': 'Cayenne', 'Population:': '195506', 'Area (km2):': '91000.0'}, {'country_name': 'Guernsey', 'Capital:': 'St Peter Port', 'Population:': '65228', 'Area (km2):': '78.0'}, {'country_name': 'Ghana', 'Capital:': 'Accra', 'Population:': '24339838', 'Area (km2):': '239460.0'}, {'country_name': 'Gibraltar', 'Capital:': 'Gibraltar', 'Population:': '27884', 'Area (km2):': '6.5'}, {'country_name': 'Greenland', 'Capital:': 'Nuuk', 'Population:': '56375', 'Area (km2):': '2166086.0'}, {'country_name': 'Gambia', 'Capital:': 'Bathurst', 'Population:': '1593256', 'Area (km2):': '11300.0'}, {'country_name': 'Guinea', 'Capital:': 'Conakry', 'Population:': '10324025', 'Area (km2):': '245857.0'}, {'country_name': 'Guadeloupe', 'Capital:': 'Basse-Terre', 'Population:': '443000', 'Area (km2):': '1780.0'}, {'country_name': 'Equatorial Guinea', 'Capital:': 'Malabo', 'Population:': '1014999', 'Area (km2):': '28051.0'}, {'country_name': 'Greece', 'Capital:': 'Athens', 'Population:': '11000000', 'Area (km2):': '131940.0'}, {'country_name': 'South Georgia and the South Sandwich Islands', 'Capital:': 'Grytviken', 'Population:': '30', 'Area (km2):': '3903.0'}, {'country_name': 'Guatemala', 'Capital:': 'Guatemala City', 'Population:': '13550440', 'Area (km2):': '108890.0'}, {'country_name': 'Guam', 'Capital:': 'Hagåtña', 'Population:': '159358', 'Area (km2):': '549.0'}, {'country_name': 'Guinea-Bissau', 'Capital:': 'Bissau', 'Population:': '1565126', 'Area (km2):': '36120.0'}, {'country_name': 'Guyana', 'Capital:': 'Georgetown', 'Population:': '748486', 'Area (km2):': '214970.0'}, {'country_name': 'Hong Kong', 'Capital:': 'Hong Kong', 'Population:': '6898686', 'Area (km2):': '1092.0'}, {'country_name': 'Heard Island and McDonald Islands', 'Capital:': 'None', 'Population:': '0', 'Area (km2):': '412.0'}, {'country_name': 'Honduras', 'Capital:': 'Tegucigalpa', 'Population:': '7989415', 'Area (km2):': '112090.0'}, {'country_name': 'Croatia', 'Capital:': 'Zagreb', 'Population:': '4491000', 'Area (km2):': '56542.0'}, {'country_name': 'Haiti', 'Capital:': 'Port-au-Prince', 'Population:': '9648924', 'Area (km2):': '27750.0'}, {'country_name': 'Hungary', 'Capital:': 'Budapest', 'Population:': '9982000', 'Area (km2):': '93030.0'}, {'country_name': 'Indonesia', 'Capital:': 'Jakarta', 'Population:': '242968342', 'Area (km2):': '1919440.0'}, {'country_name': 'Ireland', 'Capital:': 'Dublin', 'Population:': '4622917', 'Area (km2):': '70280.0'}, {'country_name': 'Israel', 'Capital:': 'None', 'Population:': '7353985', 'Area (km2):': '20770.0'}, {'country_name': 'Isle of Man', 'Capital:': 'Douglas', 'Population:': '75049', 'Area (km2):': '572.0'}, {'country_name': 'India', 'Capital:': 'New Delhi', 'Population:': '1173108018', 'Area (km2):': '3287590.0'}, {'country_name': 'British Indian Ocean Territory', 'Capital:': 'None', 'Population:': '4000', 'Area (km2):': '60.0'}, {'country_name': 'Iraq', 'Capital:': 'Baghdad', 'Population:': '29671605', 'Area (km2):': '437072.0'}, {'country_name': 'Iran', 'Capital:': 'Tehran', 'Population:': '76923300', 'Area (km2):': '1648000.0'}, {'country_name': 'Iceland', 'Capital:': 'Reykjavik', 'Population:': '308910', 'Area (km2):': '103000.0'}, {'country_name': 'Italy', 'Capital:': 'Rome', 'Population:': '60340328', 'Area (km2):': '301230.0'}, {'country_name': 'Jersey', 'Capital:': 'Saint Helier', 'Population:': '90812', 'Area (km2):': '116.0'}, {'country_name': 'Jamaica', 'Capital:': 'Kingston', 'Population:': '2847232', 'Area (km2):': '10991.0'}, {'country_name': 'Jordan', 'Capital:': 'Amman', 'Population:': '6407085', 'Area (km2):': '92300.0'}, {'country_name': 'Japan', 'Capital:': 'Tokyo', 'Population:': '127288000', 'Area (km2):': '377835.0'}, {'country_name': 'Kenya', 'Capital:': 'Nairobi', 'Population:': '40046566', 'Area (km2):': '582650.0'}, {'country_name': 'Kyrgyzstan', 'Capital:': 'Bishkek', 'Population:': '5776500', 'Area (km2):': '198500.0'}, {'country_name': 'Cambodia', 'Capital:': 'Phnom Penh', 'Population:': '14453680', 'Area (km2):': '181040.0'}, {'country_name': 'Kiribati', 'Capital:': 'Tarawa', 'Population:': '92533', 'Area (km2):': '811.0'}, {'country_name': 'Comoros', 'Capital:': 'Moroni', 'Population:': '773407', 'Area (km2):': '2170.0'}, {'country_name': 'Saint Kitts and Nevis', 'Capital:': 'Basseterre', 'Population:': '51134', 'Area (km2):': '261.0'}, {'country_name': 'North Korea', 'Capital:': 'Pyongyang', 'Population:': '22912177', 'Area (km2):': '120540.0'}, {'country_name': 'South Korea', 'Capital:': 'Seoul', 'Population:': '48422644', 'Area (km2):': '98480.0'}, {'country_name': 'Kuwait', 'Capital:': 'Kuwait City', 'Population:': '2789132', 'Area (km2):': '17820.0'}, {'country_name': 'Cayman Islands', 'Capital:': 'George Town', 'Population:': '44270', 'Area (km2):': '262.0'}, {'country_name': 'Kazakhstan', 'Capital:': 'Astana', 'Population:': '15340000', 'Area (km2):': '2717300.0'}, {'country_name': 'Laos', 'Capital:': 'Vientiane', 'Population:': '6368162', 'Area (km2):': '236800.0'}, {'country_name': 'Lebanon', 'Capital:': 'Beirut', 'Population:': '4125247', 'Area (km2):': '10400.0'}, {'country_name': 'Saint Lucia', 'Capital:': 'Castries', 'Population:': '160922', 'Area (km2):': '616.0'}, {'country_name': 'Liechtenstein', 'Capital:': 'Vaduz', 'Population:': '35000', 'Area (km2):': '160.0'}, {'country_name': 'Sri Lanka', 'Capital:': 'Colombo', 'Population:': '21513990', 'Area (km2):': '65610.0'}, {'country_name': 'Liberia', 'Capital:': 'Monrovia', 'Population:': '3685076', 'Area (km2):': '111370.0'}, {'country_name': 'Lesotho', 'Capital:': 'Maseru', 'Population:': '1919552', 'Area (km2):': '30355.0'}, {'country_name': 'Lithuania', 'Capital:': 'Vilnius', 'Population:': '2944459', 'Area (km2):': '65200.0'}, {'country_name': 'Luxembourg', 'Capital:': 'Luxembourg', 'Population:': '497538', 'Area (km2):': '2586.0'}, {'country_name': 'Latvia', 'Capital:': 'Riga', 'Population:': '2217969', 'Area (km2):': '64589.0'}, {'country_name': 'Libya', 'Capital:': 'Tripoli', 'Population:': '6461454', 'Area (km2):': '1759540.0'}, {'country_name': 'Morocco', 'Capital:': 'Rabat', 'Population:': '31627428', 'Area (km2):': '446550.0'}, {'country_name': 'Monaco', 'Capital:': 'Monaco', 'Population:': '32965', 'Area (km2):': '1.95'}, {'country_name': 'Moldova', 'Capital:': 'Chişinău', 'Population:': '4324000', 'Area (km2):': '33843.0'}, {'country_name': 'Montenegro', 'Capital:': 'Podgorica', 'Population:': '666730', 'Area (km2):': '14026.0'}, {'country_name': 'Saint Martin', 'Capital:': 'Marigot', 'Population:': '35925', 'Area (km2):': '53.0'}, {'country_name': 'Madagascar', 'Capital:': 'Antananarivo', 'Population:': '21281844', 'Area (km2):': '587040.0'}, {'country_name': 'Marshall Islands', 'Capital:': 'Majuro', 'Population:': '65859', 'Area (km2):': '181.3'}, {'country_name': 'Macedonia', 'Capital:': 'Skopje', 'Population:': '2062294', 'Area (km2):': '25333.0'}, {'country_name': 'Mali', 'Capital:': 'Bamako', 'Population:': '13796354', 'Area (km2):': '1240000.0'}, {'country_name': 'Myanmar [Burma]', 'Capital:': 'Naypyitaw', 'Population:': '53414374', 'Area (km2):': '678500.0'}, {'country_name': 'Mongolia', 'Capital:': 'Ulan Bator', 'Population:': '3086918', 'Area (km2):': '1565000.0'}, {'country_name': 'Macao', 'Capital:': 'Macao', 'Population:': '449198', 'Area (km2):': '254.0'}, {'country_name': 'Northern Mariana Islands', 'Capital:': 'Saipan', 'Population:': '53883', 'Area (km2):': '477.0'}, {'country_name': 'Martinique', 'Capital:': 'Fort-de-France', 'Population:': '432900', 'Area (km2):': '1100.0'}, {'country_name': 'Mauritania', 'Capital:': 'Nouakchott', 'Population:': '3205060', 'Area (km2):': '1030700.0'}, {'country_name': 'Montserrat', 'Capital:': 'Plymouth', 'Population:': '9341', 'Area (km2):': '102.0'}, {'country_name': 'Malta', 'Capital:': 'Valletta', 'Population:': '403000', 'Area (km2):': '316.0'}, {'country_name': 'Mauritius', 'Capital:': 'Port Louis', 'Population:': '1294104', 'Area (km2):': '2040.0'}, {'country_name': 'Maldives', 'Capital:': 'Malé', 'Population:': '395650', 'Area (km2):': '300.0'}, {'country_name': 'Malawi', 'Capital:': 'Lilongwe', 'Population:': '15447500', 'Area (km2):': '118480.0'}, {'country_name': 'Mexico', 'Capital:': 'Mexico City', 'Population:': '112468855', 'Area (km2):': '1972550.0'}, {'country_name': 'Malaysia', 'Capital:': 'Kuala Lumpur', 'Population:': '28274729', 'Area (km2):': '329750.0'}, {'country_name': 'Mozambique', 'Capital:': 'Maputo', 'Population:': '22061451', 'Area (km2):': '801590.0'}, {'country_name': 'Namibia', 'Capital:': 'Windhoek', 'Population:': '2128471', 'Area (km2):': '825418.0'}, {'country_name': 'New Caledonia', 'Capital:': 'Noumea', 'Population:': '216494', 'Area (km2):': '19060.0'}, {'country_name': 'Niger', 'Capital:': 'Niamey', 'Population:': '15878271', 'Area (km2):': '1267000.0'}, {'country_name': 'Norfolk Island', 'Capital:': 'Kingston', 'Population:': '1828', 'Area (km2):': '34.6'}, {'country_name': 'Nigeria', 'Capital:': 'Abuja', 'Population:': '154000000', 'Area (km2):': '923768.0'}, {'country_name': 'Nicaragua', 'Capital:': 'Managua', 'Population:': '5995928', 'Area (km2):': '129494.0'}, {'country_name': 'Netherlands', 'Capital:': 'Amsterdam', 'Population:': '16645000', 'Area (km2):': '41526.0'}, {'country_name': 'Norway', 'Capital:': 'Oslo', 'Population:': '5009150', 'Area (km2):': '324220.0'}, {'country_name': 'Nepal', 'Capital:': 'Kathmandu', 'Population:': '28951852', 'Area (km2):': '140800.0'}, {'country_name': 'Nauru', 'Capital:': 'Yaren', 'Population:': '10065', 'Area (km2):': '21.0'}, {'country_name': 'Niue', 'Capital:': 'Alofi', 'Population:': '2166', 'Area (km2):': '260.0'}, {'country_name': 'New Zealand', 'Capital:': 'Wellington', 'Population:': '4252277', 'Area (km2):': '268680.0'}, {'country_name': 'Oman', 'Capital:': 'Muscat', 'Population:': '2967717', 'Area (km2):': '212460.0'}, {'country_name': 'Panama', 'Capital:': 'Panama City', 'Population:': '3410676', 'Area (km2):': '78200.0'}, {'country_name': 'Peru', 'Capital:': 'Lima', 'Population:': '29907003', 'Area (km2):': '1285220.0'}, {'country_name': 'French Polynesia', 'Capital:': 'Papeete', 'Population:': '270485', 'Area (km2):': '4167.0'}, {'country_name': 'Papua New Guinea', 'Capital:': 'Port Moresby', 'Population:': '6064515', 'Area (km2):': '462840.0'}, {'country_name': 'Philippines', 'Capital:': 'Manila', 'Population:': '99900177', 'Area (km2):': '300000.0'}, {'country_name': 'Pakistan', 'Capital:': 'Islamabad', 'Population:': '184404791', 'Area (km2):': '803940.0'}, {'country_name': 'Poland', 'Capital:': 'Warsaw', 'Population:': '38500000', 'Area (km2):': '312685.0'}, {'country_name': 'Saint Pierre and Miquelon', 'Capital:': 'Saint-Pierre', 'Population:': '7012', 'Area (km2):': '242.0'}, {'country_name': 'Pitcairn Islands', 'Capital:': 'Adamstown', 'Population:': '46', 'Area (km2):': '47.0'}, {'country_name': 'Puerto Rico', 'Capital:': 'San Juan', 'Population:': '3916632', 'Area (km2):': '9104.0'}, {'country_name': 'Palestine', 'Capital:': 'None', 'Population:': '3800000', 'Area (km2):': '5970.0'}, {'country_name': 'Portugal', 'Capital:': 'Lisbon', 'Population:': '10676000', 'Area (km2):': '92391.0'}, {'country_name': 'Palau', 'Capital:': 'Melekeok', 'Population:': '19907', 'Area (km2):': '458.0'}, {'country_name': 'Paraguay', 'Capital:': 'Asunción', 'Population:': '6375830', 'Area (km2):': '406750.0'}, {'country_name': 'Qatar', 'Capital:': 'Doha', 'Population:': '840926', 'Area (km2):': '11437.0'}, {'country_name': '

In [82]:
len(d3)

250

## 5.4 Extract country details of a first column of a page & save into csv file.

In [85]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
var=requests.get('https://www.scrapethissite.com/pages/simple/')
soup=BeautifulSoup(var.text,'html.parser')
web=soup.find_all('div',class_='col-md-4 country')
d4=[]
for i in web[0:250:3]:
    dictionary4={
        'country_name':'',
        'Capital:':'',
        'Population:':'',
        'Area (km2):':'',

    }
    dictionary4['country_name']=i.find('h3',class_='country-name').text.strip()
    dictionary4['Capital:']=i.find('span',class_='country-capital').text.strip()
    dictionary4['Population:']=i.find('span',class_='country-population').text.strip()
    dictionary4['Area (km2):']=i.find('span',class_='country-area').text.strip()
    #print(dictionary2)
    d4.append(dictionary4)
print(d4)

[{'country_name': 'Andorra', 'Capital:': 'Andorra la Vella', 'Population:': '84000', 'Area (km2):': '468.0'}, {'country_name': 'Antigua and Barbuda', 'Capital:': "St. John's", 'Population:': '86754', 'Area (km2):': '443.0'}, {'country_name': 'Armenia', 'Capital:': 'Yerevan', 'Population:': '2968000', 'Area (km2):': '29800.0'}, {'country_name': 'Argentina', 'Capital:': 'Buenos Aires', 'Population:': '41343201', 'Area (km2):': '2766890.0'}, {'country_name': 'Australia', 'Capital:': 'Canberra', 'Population:': '21515754', 'Area (km2):': '7686850.0'}, {'country_name': 'Azerbaijan', 'Capital:': 'Baku', 'Population:': '8303512', 'Area (km2):': '86600.0'}, {'country_name': 'Bangladesh', 'Capital:': 'Dhaka', 'Population:': '156118464', 'Area (km2):': '144000.0'}, {'country_name': 'Bulgaria', 'Capital:': 'Sofia', 'Population:': '7148785', 'Area (km2):': '110910.0'}, {'country_name': 'Benin', 'Capital:': 'Porto-Novo', 'Population:': '9056010', 'Area (km2):': '112620.0'}, {'country_name': 'Brunei', 'Capital:': 'Bandar Seri Begawan', 'Population:': '395027', 'Area (km2):': '5770.0'}, {'country_name': 'Brazil', 'Capital:': 'Brasília', 'Population:': '201103330', 'Area (km2):': '8511965.0'}, {'country_name': 'Bouvet Island', 'Capital:': 'None', 'Population:': '0', 'Area (km2):': '49.0'}, {'country_name': 'Belize', 'Capital:': 'Belmopan', 'Population:': '314522', 'Area (km2):': '22966.0'}, {'country_name': 'Democratic Republic of the Congo', 'Capital:': 'Kinshasa', 'Population:': '70916439', 'Area (km2):': '2345410.0'}, {'country_name': 'Switzerland', 'Capital:': 'Bern', 'Population:': '7581000', 'Area (km2):': '41290.0'}, {'country_name': 'Chile', 'Capital:': 'Santiago', 'Population:': '16746491', 'Area (km2):': '756950.0'}, {'country_name': 'Colombia', 'Capital:': 'Bogotá', 'Population:': '47790000', 'Area (km2):': '1138910.0'}, {'country_name': 'Cape Verde', 'Capital:': 'Praia', 'Population:': '508659', 'Area (km2):': '4033.0'}, {'country_name': 'Cyprus', 'Capital:': 'Nicosia', 'Population:': '1102677', 'Area (km2):': '9250.0'}, {'country_name': 'Djibouti', 'Capital:': 'Djibouti', 'Population:': '740528', 'Area (km2):': '23000.0'}, {'country_name': 'Dominican Republic', 'Capital:': 'Santo Domingo', 'Population:': '9823821', 'Area (km2):': '48730.0'}, {'country_name': 'Estonia', 'Capital:': 'Tallinn', 'Population:': '1291170', 'Area (km2):': '45226.0'}, {'country_name': 'Eritrea', 'Capital:': 'Asmara', 'Population:': '5792984', 'Area (km2):': '121320.0'}, {'country_name': 'Finland', 'Capital:': 'Helsinki', 'Population:': '5244000', 'Area (km2):': '337030.0'}, {'country_name': 'Micronesia', 'Capital:': 'Palikir', 'Population:': '107708', 'Area (km2):': '702.0'}, {'country_name': 'Gabon', 'Capital:': 'Libreville', 'Population:': '1545255', 'Area (km2):': '267667.0'}, {'country_name': 'Georgia', 'Capital:': 'Tbilisi', 'Population:': '4630000', 'Area (km2):': '69700.0'}, {'country_name': 'Ghana', 'Capital:': 'Accra', 'Population:': '24339838', 'Area (km2):': '239460.0'}, {'country_name': 'Gambia', 'Capital:': 'Bathurst', 'Population:': '1593256', 'Area (km2):': '11300.0'}, {'country_name': 'Equatorial Guinea', 'Capital:': 'Malabo', 'Population:': '1014999', 'Area (km2):': '28051.0'}, {'country_name': 'Guatemala', 'Capital:': 'Guatemala City', 'Population:': '13550440', 'Area (km2):': '108890.0'}, {'country_name': 'Guyana', 'Capital:': 'Georgetown', 'Population:': '748486', 'Area (km2):': '214970.0'}, {'country_name': 'Honduras', 'Capital:': 'Tegucigalpa', 'Population:': '7989415', 'Area (km2):': '112090.0'}, {'country_name': 'Hungary', 'Capital:': 'Budapest', 'Population:': '9982000', 'Area (km2):': '93030.0'}, {'country_name': 'Israel', 'Capital:': 'None', 'Population:': '7353985', 'Area (km2):': '20770.0'}, {'country_name': 'British Indian Ocean Territory', 'Capital:': 'None', 'Population:': '4000', 'Area (km2):': '60.0'}, {'country_name': 'Iceland', 'Capital:': 'Reykjavik', 'Population:': '308910', 'Area (km2):': '103000.0'}, {'country_name': 'Jamaica', 'Capital:': 'Kingston', 'Population:': '2847232', 'Area (km2):': '10991.0'}, {'country_name': 'Kenya', 'Capital:': 'Nairobi', 'Population:': '40046566', 'Area (km2):': '582650.0'}, {'country_name': 'Kiribati', 'Capital:': 'Tarawa', 'Population:': '92533', 'Area (km2):': '811.0'}, {'country_name': 'North Korea', 'Capital:': 'Pyongyang', 'Population:': '22912177', 'Area (km2):': '120540.0'}, {'country_name': 'Cayman Islands', 'Capital:': 'George Town', 'Population:': '44270', 'Area (km2):': '262.0'}, {'country_name': 'Lebanon', 'Capital:': 'Beirut', 'Population:': '4125247', 'Area (km2):': '10400.0'}, {'country_name': 'Sri Lanka', 'Capital:': 'Colombo', 'Population:': '21513990', 'Area (km2):': '65610.0'}, {'country_name': 'Lithuania', 'Capital:': 'Vilnius', 'Population:': '2944459', 'Area (km2):': '65200.0'}, {'country_name': 'Libya', 'Capital:': 'Tripoli', 'Population:': '6461454', 'Area (km2):': '1759540.0'}, {'country_name': 'Moldova', 'Capital:': 'Chişinău', 'Population:': '4324000', 'Area (km2):': '33843.0'}, {'country_name': 'Madagascar', 'Capital:': 'Antananarivo', 'Population:': '21281844', 'Area (km2):': '587040.0'}, {'country_name': 'Mali', 'Capital:': 'Bamako', 'Population:': '13796354', 'Area (km2):': '1240000.0'}, {'country_name': 'Macao', 'Capital:': 'Macao', 'Population:': '449198', 'Area (km2):': '254.0'}, {'country_name': 'Mauritania', 'Capital:': 'Nouakchott', 'Population:': '3205060', 'Area (km2):': '1030700.0'}, {'country_name': 'Mauritius', 'Capital:': 'Port Louis', 'Population:': '1294104', 'Area (km2):': '2040.0'}, {'country_name': 'Mexico', 'Capital:': 'Mexico City', 'Population:': '112468855', 'Area (km2):': '1972550.0'}, {'country_name': 'Namibia', 'Capital:': 'Windhoek', 'Population:': '2128471', 'Area (km2):': '825418.0'}, {'country_name': 'Norfolk Island', 'Capital:': 'Kingston', 'Population:': '1828', 'Area (km2):': '34.6'}, {'country_name': 'Netherlands', 'Capital:': 'Amsterdam', 'Population:': '16645000', 'Area (km2):': '41526.0'}, {'country_name': 'Nauru', 'Capital:': 'Yaren', 'Population:': '10065', 'Area (km2):': '21.0'}, {'country_name': 'Oman', 'Capital:': 'Muscat', 'Population:': '2967717', 'Area (km2):': '212460.0'}, {'country_name': 'French Polynesia', 'Capital:': 'Papeete', 'Population:': '270485', 'Area (km2):': '4167.0'}, {'country_name': 'Pakistan', 'Capital:': 'Islamabad', 'Population:': '184404791', 'Area (km2):': '803940.0'}, {'country_name': 'Pitcairn Islands', 'Capital:': 'Adamstown', 'Population:': '46', 'Area (km2):': '47.0'}, {'country_name': 'Portugal', 'Capital:': 'Lisbon', 'Population:': '10676000', 'Area (km2):': '92391.0'}, {'country_name': 'Qatar', 'Capital:': 'Doha', 'Population:': '840926', 'Area (km2):': '11437.0'}, {'country_name': 'Serbia', 'Capital:': 'Belgrade', 'Population:': '7344847', 'Area (km2):': '88361.0'}, {'country_name': 'Saudi Arabia', 'Capital:': 'Riyadh', 'Population:': '25731776', 'Area (km2):': '1960582.0'}, {'country_name': 'Sudan', 'Capital:': 'Khartoum', 'Population:': '35000000', 'Area (km2):': '1861484.0'}, {'country_name': 'Saint Helena', 'Capital:': 'Jamestown', 'Population:': '7460', 'Area (km2):': '410.0'}, {'country_name': 'Slovakia', 'Capital:': 'Bratislava', 'Population:': '5455000', 'Area (km2):': '48845.0'}, {'country_name': 'Senegal', 'Capital:': 'Dakar', 'Population:': '12323252', 'Area (km2):': '196190.0'}, {'country_name': 'South Sudan', 'Capital:': 'Juba', 'Population:': '8260490', 'Area (km2):': '644329.0'}, {'country_name': 'Sint Maarten', 'Capital:': 'Philipsburg', 'Population:': '37429', 'Area (km2):': '21.0'}, {'country_name': 'Turks and Caicos Islands', 'Capital:': 'Cockburn Town', 'Population:': '20556', 'Area (km2):': '430.0'}, {'country_name': 'Togo', 'Capital:': 'Lomé', 'Population:': '6587239', 'Area (km2):': '56785.0'}, {'country_name': 'Tokelau', 'Capital:': 'None', 'Population:': '1466', 'Area (km2):': '10.0'}, {'country_name': 'Tunisia', 'Capital:': 'Tunis', 'Population:': '10589025', 'Area (km2):': '163610.0'}, {'country_name': 'Trinidad and Tobago', 'Capital:': 'Port of Spain', 'Population:': '1228691', 'Area (km2):': '5128.0'}, {'country_name': 'Tanzania', 'Capital:': 'Dodoma', 'Population:': '41892895', 'Area (km2):': '945087.0'}, {'country_name': 'U.S. Minor Outlying Islands', 'Capital:': 'None', 'Population:': '0', 'Area (km2):': '0.0'}, {'country_name': 'Uzbekistan', 'Capital:': 'Tashkent', 'Population:': '27865738', 'Area (km2):': '447400.0'}, {'country_name': 'Venezuela', 'Capital:': 'Caracas', 'Population:': '27223228', 'Area (km2):': '912050.0'}, {'country_name': 'Vietnam', 'Capital:': 'Hanoi', 'Population:': '89571130', 'Area (km2):': '329560.0'}, {'country_name': 'Samoa', 'Capital:': 'Apia', 'Population:': '192001', 'Area (km2):': '2944.0'}, {'country_name': 'Mayotte', 'Capital:': 'Mamoudzou', 'Population:': '159042', 'Area (km2):': '374.0'}, {'country_name': 'Zimbabwe', 'Capital:': 'Harare', 'Population:': '11651858', 'Area (km2):': '390580.0'}]

In [86]:
len(d4)

84

## 5.5 Extract country details of a Second column of a page & save into csv file.

In [87]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
var=requests.get('https://www.scrapethissite.com/pages/simple/')
soup=BeautifulSoup(var.text,'html.parser')
web=soup.find_all('div',class_='col-md-4 country')
d4=[]
for i in web[1:250:3]:
    dictionary4={
        'country_name':'',
        'Capital:':'',
        'Population:':'',
        'Area (km2):':'',

    }
    dictionary4['country_name']=i.find('h3',class_='country-name').text.strip()
    dictionary4['Capital:']=i.find('span',class_='country-capital').text.strip()
    dictionary4['Population:']=i.find('span',class_='country-population').text.strip()
    dictionary4['Area (km2):']=i.find('span',class_='country-area').text.strip()
    #print(dictionary2)
    d4.append(dictionary4)
print(d4)

[{'country_name': 'United Arab Emirates', 'Capital:': 'Abu Dhabi', 'Population:': '4975593', 'Area (km2):': '82880.0'}, {'country_name': 'Anguilla', 'Capital:': 'The Valley', 'Population:': '13254', 'Area (km2):': '102.0'}, {'country_name': 'Angola', 'Capital:': 'Luanda', 'Population:': '13068161', 'Area (km2):': '1246700.0'}, {'country_name': 'American Samoa', 'Capital:': 'Pago Pago', 'Population:': '57881', 'Area (km2):': '199.0'}, {'country_name': 'Aruba', 'Capital:': 'Oranjestad', 'Population:': '71566', 'Area (km2):': '193.0'}, {'country_name': 'Bosnia and Herzegovina', 'Capital:': 'Sarajevo', 'Population:': '4590000', 'Area (km2):': '51129.0'}, {'country_name': 'Belgium', 'Capital:': 'Brussels', 'Population:': '10403000', 'Area (km2):': '30510.0'}, {'country_name': 'Bahrain', 'Capital:': 'Manama', 'Population:': '738004', 'Area (km2):': '665.0'}, {'country_name': 'Saint Barthélemy', 'Capital:': 'Gustavia', 'Population:': '8450', 'Area (km2):': '21.0'}, {'country_name': 'Bolivia', 'Capital:': 'Sucre', 'Population:': '9947418', 'Area (km2):': '1098580.0'}, {'country_name': 'Bahamas', 'Capital:': 'Nassau', 'Population:': '301790', 'Area (km2):': '13940.0'}, {'country_name': 'Botswana', 'Capital:': 'Gaborone', 'Population:': '2029307', 'Area (km2):': '600370.0'}, {'country_name': 'Canada', 'Capital:': 'Ottawa', 'Population:': '33679000', 'Area (km2):': '9984670.0'}, {'country_name': 'Central African Republic', 'Capital:': 'Bangui', 'Population:': '4844927', 'Area (km2):': '622984.0'}, {'country_name': 'Ivory Coast', 'Capital:': 'Yamoussoukro', 'Population:': '21058798', 'Area (km2):': '322460.0'}, {'country_name': 'Cameroon', 'Capital:': 'Yaoundé', 'Population:': '19294149', 'Area (km2):': '475440.0'}, {'country_name': 'Costa Rica', 'Capital:': 'San José', 'Population:': '4516220', 'Area (km2):': '51100.0'}, {'country_name': 'Curacao', 'Capital:': 'Willemstad', 'Population:': '141766', 'Area (km2):': '444.0'}, {'country_name': 'Czech Republic', 'Capital:': 'Prague', 'Population:': '10476000', 'Area (km2):': '78866.0'}, {'country_name': 'Denmark', 'Capital:': 'Copenhagen', 'Population:': '5484000', 'Area (km2):': '43094.0'}, {'country_name': 'Algeria', 'Capital:': 'Algiers', 'Population:': '34586184', 'Area (km2):': '2381740.0'}, {'country_name': 'Egypt', 'Capital:': 'Cairo', 'Population:': '80471869', 'Area (km2):': '1001450.0'}, {'country_name': 'Spain', 'Capital:': 'Madrid', 'Population:': '46505963', 'Area (km2):': '504782.0'}, {'country_name': 'Fiji', 'Capital:': 'Suva', 'Population:': '875983', 'Area (km2):': '18270.0'}, {'country_name': 'Faroe Islands', 'Capital:': 'Tórshavn', 'Population:': '48228', 'Area (km2):': '1399.0'}, {'country_name': 'United Kingdom', 'Capital:': 'London', 'Population:': '62348447', 'Area (km2):': '244820.0'}, {'country_name': 'French Guiana', 'Capital:': 'Cayenne', 'Population:': '195506', 'Area (km2):': '91000.0'}, {'country_name': 'Gibraltar', 'Capital:': 'Gibraltar', 'Population:': '27884', 'Area (km2):': '6.5'}, {'country_name': 'Guinea', 'Capital:': 'Conakry', 'Population:': '10324025', 'Area (km2):': '245857.0'}, {'country_name': 'Greece', 'Capital:': 'Athens', 'Population:': '11000000', 'Area (km2):': '131940.0'}, {'country_name': 'Guam', 'Capital:': 'Hagåtña', 'Population:': '159358', 'Area (km2):': '549.0'}, {'country_name': 'Hong Kong', 'Capital:': 'Hong Kong', 'Population:': '6898686', 'Area (km2):': '1092.0'}, {'country_name': 'Croatia', 'Capital:': 'Zagreb', 'Population:': '4491000', 'Area (km2):': '56542.0'}, {'country_name': 'Indonesia', 'Capital:': 'Jakarta', 'Population:': '242968342', 'Area (km2):': '1919440.0'}, {'country_name': 'Isle of Man', 'Capital:': 'Douglas', 'Population:': '75049', 'Area (km2):': '572.0'}, {'country_name': 'Iraq', 'Capital:': 'Baghdad', 'Population:': '29671605', 'Area (km2):': '437072.0'}, {'country_name': 'Italy', 'Capital:': 'Rome', 'Population:': '60340328', 'Area (km2):': '301230.0'}, {'country_name': 'Jordan', 'Capital:': 'Amman', 'Population:': '6407085', 'Area (km2):': '92300.0'}, {'country_name': 'Kyrgyzstan', 'Capital:': 'Bishkek', 'Population:': '5776500', 'Area (km2):': '198500.0'}, {'country_name': 'Comoros', 'Capital:': 'Moroni', 'Population:': '773407', 'Area (km2):': '2170.0'}, {'country_name': 'South Korea', 'Capital:': 'Seoul', 'Population:': '48422644', 'Area (km2):': '98480.0'}, {'country_name': 'Kazakhstan', 'Capital:': 'Astana', 'Population:': '15340000', 'Area (km2):': '2717300.0'}, {'country_name': 'Saint Lucia', 'Capital:': 'Castries', 'Population:': '160922', 'Area (km2):': '616.0'}, {'country_name': 'Liberia', 'Capital:': 'Monrovia', 'Population:': '3685076', 'Area (km2):': '111370.0'}, {'country_name': 'Luxembourg', 'Capital:': 'Luxembourg', 'Population:': '497538', 'Area (km2):': '2586.0'}, {'country_name': 'Morocco', 'Capital:': 'Rabat', 'Population:': '31627428', 'Area (km2):': '446550.0'}, {'country_name': 'Montenegro', 'Capital:': 'Podgorica', 'Population:': '666730', 'Area (km2):': '14026.0'}, {'country_name': 'Marshall Islands', 'Capital:': 'Majuro', 'Population:': '65859', 'Area (km2):': '181.3'}, {'country_name': 'Myanmar [Burma]', 'Capital:': 'Naypyitaw', 'Population:': '53414374', 'Area (km2):': '678500.0'}, {'country_name': 'Northern Mariana Islands', 'Capital:': 'Saipan', 'Population:': '53883', 'Area (km2):': '477.0'}, {'country_name': 'Montserrat', 'Capital:': 'Plymouth', 'Population:': '9341', 'Area (km2):': '102.0'}, {'country_name': 'Maldives', 'Capital:': 'Malé', 'Population:': '395650', 'Area (km2):': '300.0'}, {'country_name': 'Malaysia', 'Capital:': 'Kuala Lumpur', 'Population:': '28274729', 'Area (km2):': '329750.0'}, {'country_name': 'New Caledonia', 'Capital:': 'Noumea', 'Population:': '216494', 'Area (km2):': '19060.0'}, {'country_name': 'Nigeria', 'Capital:': 'Abuja', 'Population:': '154000000', 'Area (km2):': '923768.0'}, {'country_name': 'Norway', 'Capital:': 'Oslo', 'Population:': '5009150', 'Area (km2):': '324220.0'}, {'country_name': 'Niue', 'Capital:': 'Alofi', 'Population:': '2166', 'Area (km2):': '260.0'}, {'country_name': 'Panama', 'Capital:': 'Panama City', 'Population:': '3410676', 'Area (km2):': '78200.0'}, {'country_name': 'Papua New Guinea', 'Capital:': 'Port Moresby', 'Population:': '6064515', 'Area (km2):': '462840.0'}, {'country_name': 'Poland', 'Capital:': 'Warsaw', 'Population:': '38500000', 'Area (km2):': '312685.0'}, {'country_name': 'Puerto Rico', 'Capital:': 'San Juan', 'Population:': '3916632', 'Area (km2):': '9104.0'}, {'country_name': 'Palau', 'Capital:': 'Melekeok', 'Population:': '19907', 'Area (km2):': '458.0'}, {'country_name': 'Réunion', 'Capital:': 'Saint-Denis', 'Population:': '776948', 'Area (km2):': '2517.0'}, {'country_name': 'Russia', 'Capital:': 'Moscow', 'Population:': '140702000', 'Area (km2):': '1.71E7'}, {'country_name': 'Solomon Islands', 'Capital:': 'Honiara', 'Population:': '559198', 'Area (km2):': '28450.0'}, {'country_name': 'Sweden', 'Capital:': 'Stockholm', 'Population:': '9828655', 'Area (km2):': '449964.0'}, {'country_name': 'Slovenia', 'Capital:': 'Ljubljana', 'Population:': '2007000', 'Area (km2):': '20273.0'}, {'country_name': 'Sierra Leone', 'Capital:': 'Freetown', 'Population:': '5245695', 'Area (km2):': '71740.0'}, {'country_name': 'Somalia', 'Capital:': 'Mogadishu', 'Population:': '10112453', 'Area (km2):': '637657.0'}, {'country_name': 'São Tomé and Príncipe', 'Capital:': 'São Tomé', 'Population:': '175808', 'Area (km2):': '1001.0'}, {'country_name': 'Syria', 'Capital:': 'Damascus', 'Population:': '22198110', 'Area (km2):': '185180.0'}, {'country_name': 'Chad', 'Capital:': "N'Djamena", 'Population:': '10543464', 'Area (km2):': '1284000.0'}, {'country_name': 'Thailand', 'Capital:': 'Bangkok', 'Population:': '67089500', 'Area (km2):': '514000.0'}, {'country_name': 'East Timor', 'Capital:': 'Dili', 'Population:': '1154625', 'Area (km2):': '15007.0'}, {'country_name': 'Tonga', 'Capital:': "Nuku'alofa", 'Population:': '122580', 'Area (km2):': '748.0'}, {'country_name': 'Tuvalu', 'Capital:': 'Funafuti', 'Population:': '10472', 'Area (km2):': '26.0'}, {'country_name': 'Ukraine', 'Capital:': 'Kiev', 'Population:': '45415596', 'Area (km2):': '603700.0'}, {'country_name': 'United States', 'Capital:': 'Washington', 'Population:': '310232863', 'Area (km2):': '9629091.0'}, {'country_name': 'Vatican City', 'Capital:': 'Vatican City', 'Population:': '921', 'Area (km2):': '0.44'}, {'country_name': 'British Virgin Islands', 'Capital:': 'Road Town', 'Population:': '21730', 'Area (km2):': '153.0'}, {'country_name': 'Vanuatu', 'Capital:': 'Port Vila', 'Population:': '221552', 'Area (km2):': '12200.0'}, {'country_name': 'Kosovo', 'Capital:': 'Pristina', 'Population:': '1800000', 'Area (km2):': '10908.0'}, {'country_name': 'South Africa', 'Capital:': 'Pretoria', 'Population:': '49000000', 'Area (km2):': '1219912.0'}]

## 5.6 Extract country details of a Third column of a page & save into csv file.

In [88]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
var=requests.get('https://www.scrapethissite.com/pages/simple/')
soup=BeautifulSoup(var.text,'html.parser')
web=soup.find_all('div',class_='col-md-4 country')
d4=[]
for i in web[2:250:3]:
    dictionary4={
        'country_name':'',
        'Capital:':'',
        'Population:':'',
        'Area (km2):':'',

    }
    dictionary4['country_name']=i.find('h3',class_='country-name').text.strip()
    dictionary4['Capital:']=i.find('span',class_='country-capital').text.strip()
    dictionary4['Population:']=i.find('span',class_='country-population').text.strip()
    dictionary4['Area (km2):']=i.find('span',class_='country-area').text.strip()
    #print(dictionary2)
    d4.append(dictionary4)
print(d4)

[{'country_name': 'Afghanistan', 'Capital:': 'Kabul', 'Population:': '29121286', 'Area (km2):': '647500.0'}, {'country_name': 'Albania', 'Capital:': 'Tirana', 'Population:': '2986952', 'Area (km2):': '28748.0'}, {'country_name': 'Antarctica', 'Capital:': 'None', 'Population:': '0', 'Area (km2):': '1.4E7'}, {'country_name': 'Austria', 'Capital:': 'Vienna', 'Population:': '8205000', 'Area (km2):': '83858.0'}, {'country_name': 'Åland', 'Capital:': 'Mariehamn', 'Population:': '26711', 'Area (km2):': '1580.0'}, {'country_name': 'Barbados', 'Capital:': 'Bridgetown', 'Population:': '285653', 'Area (km2):': '431.0'}, {'country_name': 'Burkina Faso', 'Capital:': 'Ouagadougou', 'Population:': '16241811', 'Area (km2):': '274200.0'}, {'country_name': 'Burundi', 'Capital:': 'Bujumbura', 'Population:': '9863117', 'Area (km2):': '27830.0'}, {'country_name': 'Bermuda', 'Capital:': 'Hamilton', 'Population:': '65365', 'Area (km2):': '53.0'}, {'country_name': 'Bonaire', 'Capital:': 'Kralendijk', 'Population:': '18012', 'Area (km2):': '328.0'}, {'country_name': 'Bhutan', 'Capital:': 'Thimphu', 'Population:': '699847', 'Area (km2):': '47000.0'}, {'country_name': 'Belarus', 'Capital:': 'Minsk', 'Population:': '9685000', 'Area (km2):': '207600.0'}, {'country_name': 'Cocos [Keeling] Islands', 'Capital:': 'West Island', 'Population:': '628', 'Area (km2):': '14.0'}, {'country_name': 'Republic of the Congo', 'Capital:': 'Brazzaville', 'Population:': '3039126', 'Area (km2):': '342000.0'}, {'country_name': 'Cook Islands', 'Capital:': 'Avarua', 'Population:': '21388', 'Area (km2):': '240.0'}, {'country_name': 'China', 'Capital:': 'Beijing', 'Population:': '1330044000', 'Area (km2):': '9596960.0'}, {'country_name': 'Cuba', 'Capital:': 'Havana', 'Population:': '11423000', 'Area (km2):': '110860.0'}, {'country_name': 'Christmas Island', 'Capital:': 'Flying Fish Cove', 'Population:': '1500', 'Area (km2):': '135.0'}, {'country_name': 'Germany', 'Capital:': 'Berlin', 'Population:': '81802257', 'Area (km2):': '357021.0'}, {'country_name': 'Dominica', 'Capital:': 'Roseau', 'Population:': '72813', 'Area (km2):': '754.0'}, {'country_name': 'Ecuador', 'Capital:': 'Quito', 'Population:': '14790608', 'Area (km2):': '283560.0'}, {'country_name': 'Western Sahara', 'Capital:': 'Laâyoune / El Aaiún', 'Population:': '273008', 'Area (km2):': '266000.0'}, {'country_name': 'Ethiopia', 'Capital:': 'Addis Ababa', 'Population:': '88013491', 'Area (km2):': '1127127.0'}, {'country_name': 'Falkland Islands', 'Capital:': 'Stanley', 'Population:': '2638', 'Area (km2):': '12173.0'}, {'country_name': 'France', 'Capital:': 'Paris', 'Population:': '64768389', 'Area (km2):': '547030.0'}, {'country_name': 'Grenada', 'Capital:': "St. George's", 'Population:': '107818', 'Area (km2):': '344.0'}, {'country_name': 'Guernsey', 'Capital:': 'St Peter Port', 'Population:': '65228', 'Area (km2):': '78.0'}, {'country_name': 'Greenland', 'Capital:': 'Nuuk', 'Population:': '56375', 'Area (km2):': '2166086.0'}, {'country_name': 'Guadeloupe', 'Capital:': 'Basse-Terre', 'Population:': '443000', 'Area (km2):': '1780.0'}, {'country_name': 'South Georgia and the South Sandwich Islands', 'Capital:': 'Grytviken', 'Population:': '30', 'Area (km2):': '3903.0'}, {'country_name': 'Guinea-Bissau', 'Capital:': 'Bissau', 'Population:': '1565126', 'Area (km2):': '36120.0'}, {'country_name': 'Heard Island and McDonald Islands', 'Capital:': 'None', 'Population:': '0', 'Area (km2):': '412.0'}, {'country_name': 'Haiti', 'Capital:': 'Port-au-Prince', 'Population:': '9648924', 'Area (km2):': '27750.0'}, {'country_name': 'Ireland', 'Capital:': 'Dublin', 'Population:': '4622917', 'Area (km2):': '70280.0'}, {'country_name': 'India', 'Capital:': 'New Delhi', 'Population:': '1173108018', 'Area (km2):': '3287590.0'}, {'country_name': 'Iran', 'Capital:': 'Tehran', 'Population:': '76923300', 'Area (km2):': '1648000.0'}, {'country_name': 'Jersey', 'Capital:': 'Saint Helier', 'Population:': '90812', 'Area (km2):': '116.0'}, {'country_name': 'Japan', 'Capital:': 'Tokyo', 'Population:': '127288000', 'Area (km2):': '377835.0'}, {'country_name': 'Cambodia', 'Capital:': 'Phnom Penh', 'Population:': '14453680', 'Area (km2):': '181040.0'}, {'country_name': 'Saint Kitts and Nevis', 'Capital:': 'Basseterre', 'Population:': '51134', 'Area (km2):': '261.0'}, {'country_name': 'Kuwait', 'Capital:': 'Kuwait City', 'Population:': '2789132', 'Area (km2):': '17820.0'}, {'country_name': 'Laos', 'Capital:': 'Vientiane', 'Population:': '6368162', 'Area (km2):': '236800.0'}, {'country_name': 'Liechtenstein', 'Capital:': 'Vaduz', 'Population:': '35000', 'Area (km2):': '160.0'}, {'country_name': 'Lesotho', 'Capital:': 'Maseru', 'Population:': '1919552', 'Area (km2):': '30355.0'}, {'country_name': 'Latvia', 'Capital:': 'Riga', 'Population:': '2217969', 'Area (km2):': '64589.0'}, {'country_name': 'Monaco', 'Capital:': 'Monaco', 'Population:': '32965', 'Area (km2):': '1.95'}, {'country_name': 'Saint Martin', 'Capital:': 'Marigot', 'Population:': '35925', 'Area (km2):': '53.0'}, {'country_name': 'Macedonia', 'Capital:': 'Skopje', 'Population:': '2062294', 'Area (km2):': '25333.0'}, {'country_name': 'Mongolia', 'Capital:': 'Ulan Bator', 'Population:': '3086918', 'Area (km2):': '1565000.0'}, {'country_name': 'Martinique', 'Capital:': 'Fort-de-France', 'Population:': '432900', 'Area (km2):': '1100.0'}, {'country_name': 'Malta', 'Capital:': 'Valletta', 'Population:': '403000', 'Area (km2):': '316.0'}, {'country_name': 'Malawi', 'Capital:': 'Lilongwe', 'Population:': '15447500', 'Area (km2):': '118480.0'}, {'country_name': 'Mozambique', 'Capital:': 'Maputo', 'Population:': '22061451', 'Area (km2):': '801590.0'}, {'country_name': 'Niger', 'Capital:': 'Niamey', 'Population:': '15878271', 'Area (km2):': '1267000.0'}, {'country_name': 'Nicaragua', 'Capital:': 'Managua', 'Population:': '5995928', 'Area (km2):': '129494.0'}, {'country_name': 'Nepal', 'Capital:': 'Kathmandu', 'Population:': '28951852', 'Area (km2):': '140800.0'}, {'country_name': 'New Zealand', 'Capital:': 'Wellington', 'Population:': '4252277', 'Area (km2):': '268680.0'}, {'country_name': 'Peru', 'Capital:': 'Lima', 'Population:': '29907003', 'Area (km2):': '1285220.0'}, {'country_name': 'Philippines', 'Capital:': 'Manila', 'Population:': '99900177', 'Area (km2):': '300000.0'}, {'country_name': 'Saint Pierre and Miquelon', 'Capital:': 'Saint-Pierre', 'Population:': '7012', 'Area (km2):': '242.0'}, {'country_name': 'Palestine', 'Capital:': 'None', 'Population:': '3800000', 'Area (km2):': '5970.0'}, {'country_name': 'Paraguay', 'Capital:': 'Asunción', 'Population:': '6375830', 'Area (km2):': '406750.0'}, {'country_name': 'Romania', 'Capital:': 'Bucharest', 'Population:': '21959278', 'Area (km2):': '237500.0'}, {'country_name': 'Rwanda', 'Capital:': 'Kigali', 'Population:': '11055976', 'Area (km2):': '26338.0'}, {'country_name': 'Seychelles', 'Capital:': 'Victoria', 'Population:': '88340', 'Area (km2):': '455.0'}, {'country_name': 'Singapore', 'Capital:': 'Singapore', 'Population:': '4701069', 'Area (km2):': '692.7'}, {'country_name': 'Svalbard and Jan Mayen', 'Capital:': 'Longyearbyen', 'Population:': '2550', 'Area (km2):': '62049.0'}, {'country_name': 'San Marino', 'Capital:': 'San Marino', 'Population:': '31477', 'Area (km2):': '61.2'}, {'country_name': 'Suriname', 'Capital:': 'Paramaribo', 'Population:': '492829', 'Area (km2):': '163270.0'}, {'country_name': 'El Salvador', 'Capital:': 'San Salvador', 'Population:': '6052064', 'Area (km2):': '21040.0'}, {'country_name': 'Swaziland', 'Capital:': 'Mbabane', 'Population:': '1354051', 'Area (km2):': '17363.0'}, {'country_name': 'French Southern Territories', 'Capital:': 'Port-aux-Français', 'Population:': '140', 'Area (km2):': '7829.0'}, {'country_name': 'Tajikistan', 'Capital:': 'Dushanbe', 'Population:': '7487489', 'Area (km2):': '143100.0'}, {'country_name': 'Turkmenistan', 'Capital:': 'Ashgabat', 'Population:': '4940916', 'Area (km2):': '488100.0'}, {'country_name': 'Turkey', 'Capital:': 'Ankara', 'Population:': '77804122', 'Area (km2):': '780580.0'}, {'country_name': 'Taiwan', 'Capital:': 'Taipei', 'Population:': '22894384', 'Area (km2):': '35980.0'}, {'country_name': 'Uganda', 'Capital:': 'Kampala', 'Population:': '33398682', 'Area (km2):': '236040.0'}, {'country_name': 'Uruguay', 'Capital:': 'Montevideo', 'Population:': '3477000', 'Area (km2):': '176220.0'}, {'country_name': 'Saint Vincent and the Grenadines', 'Capital:': 'Kingstown', 'Population:': '104217', 'Area (km2):': '389.0'}, {'country_name': 'U.S. Virgin Islands', 'Capital:': 'Charlotte Amalie', 'Population:': '108708', 'Area (km2):': '352.0'}, {'country_name': 'Wallis and Futuna', 'Capital:': 'Mata-Utu', 'Population:': '16025', 'Area (km2):': '274.0'}, {'country_name': 'Yemen', 'Capital:': 'Sanaa', 'Population:': '23495361', 'Area (km2):': '527970.0'}, {'country_name': 'Zambia', 'Capital:': 'Lusaka', 'Population:': '13460305', 'Area (km2):': '752614.0'}]

## 6.1 Extract first product details save into csv file. e.g# Asus VivoBook...

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
web=requests.get('https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops')
web.status_code
soup=BeautifulSoup(web.text,'html.parser')
product=soup.find('div',class_='product-wrapper card-body')
list=[]
dic={
    'product_name':'',
    'product_link':'',
    'product_img':'',
    'product_price':'',
    'product_detail':'',
    'product_review_number':'',
}
dic['product_img']=product.find('img')['src']
dic['product_price']=product.find('span',itemprop='price').text
dic['product_name']=product.find('a').text.strip()
dic['product_link']=product.find('a')['href']
dic['product_detail']=product.find('p').text.strip()
dic['product_review_number']=product.find('span',itemprop='reviewCount').text
dic

200

## 6.2 Extract product details from first row & save into csv file.

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
web_row=requests.get('https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops')
soup=BeautifulSoup(web_row.text,'html.parser')
first_row=soup.find_all('div',class_='product-wrapper card-body')
list_first_row=[]
for i in first_row[0:3]:
    dic={
    'product_name':'',
    'product_link':'',
    'product_img':'',
    'product_price':'',
    'product_detail':'',
    'product_review_number':'',
    'product_review_star_number':'',
}
    dic['product_img']=i.find('img')['src']
    dic['product_price']=i.find('span',itemprop='price').text
    dic['product_name']=i.find('a').text.strip()
    dic['product_link']=i.find('a')['href']
    dic['product_detail']=i.find('p').text.strip()
    dic['product_review_number']=i.find('span',itemprop='reviewCount').text
    #dic['product_review_star_number']=i.find('p')['']
    print(dic)

{'product_name': 'Asus VivoBook...', 'product_link': '/test-sites/e-commerce/allinone/product/60', 'product_img': '/images/test-sites/e-commerce/items/cart2.png', 'product_price': '$295.99', 'product_detail': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd', 'product_review_number': '14', 'product_review_star_number': ''}
{'product_name': 'Prestigio Smar...', 'product_link': '/test-sites/e-commerce/allinone/product/61', 'product_img': '/images/test-sites/e-commerce/items/cart2.png', 'product_price': '$299', 'product_detail': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam', 'product_review_number': '8', 'product_review_star_number': ''}
{'product_name': 'Prestigio Smar...', 'product_link': '/test-sites/e-commerce/allinone/product/62', 'product_img': '/images/test-sites/e-commerce/items/cart2.png', 'product_price': '$299', 'product_detail': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam', 'product_review_number': '12', 'product_review_star_number': ''}

## 5.1 Extract first product details save into csv file. e.g# Asus VivoBook X441NA-GA190

In [8]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url='https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops'
web=requests.get(main_url)
web.status_code
soup=BeautifulSoup(web.text,'html.parser')
product=soup.find('div',class_='product-wrapper card-body')
list=[]
for first_pro in product:
    dic={
        'product_name':'',
        'product_link':'',
        'product_img':'',
        'product_price':'',
        'product_detail':'',
        'product_review_number':'',
    }
    dic['product_img']=product.find('img')['src']
    dic['product_price']=product.find('span',itemprop='price').text
    dic['product_name']=product.find('a').text.strip()
    dic['product_link']=product.find('a')['href']
    dic['product_detail']=product.find('p').text.strip()
    dic['product_review_number']=product.find('span',itemprop='reviewCount').text
    list.append(dic)
df=pd.DataFrame(list)
df

,product_name,product_link,product_img,product_price,product_detail,product_review_number
0,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14
1,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14
2,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14
3,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14
4,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14
5,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14
6,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14

## a5.1 Extract first product details save into csv file. e.g# Asus VivoBook X441NA-GA190

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url='https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops'
r=requests.get(main_url)
r.status_code

200

In [2]:
soup=BeautifulSoup(r.text,'html.parser')
product=soup.find('div',class_='col-md-4 col-xl-4 col-lg-4')
product

<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>

In [8]:
list=[]
var_dic={
    'product_name':'',
    'product_para':'',
    'product_img':'',
    'product_url':'',
    'product_price':'',
    'procut_review':'',
}
var_dic['product_name']=product.find('a').text.strip()
var_dic['product_para']=product.find('p',class_='description card-text').text.strip()
var_dic['product_img']=product.find('img')['src']
var_dic['product_url']=product.find('a')['href']
var_dic['product_price']=product.find('span').text.strip()
var_dic['procut_review']=product.find('p',class_='review-count float-end').text.strip()
var_dic

{'product_name': 'Asus VivoBook...',
 'product_para': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
 'product_img': '/images/test-sites/e-commerce/items/cart2.png',
 'product_url': '/test-sites/e-commerce/allinone/product/60',
 'product_price': '$295.99',
 'procut_review': '14 reviews'}

In [5]:
var_dic['product_url']

'/test-sites/e-commerce/allinone/product/60'

In [6]:
base_url='https://webscraper.io'
actrual=base_url+var_dic['product_url']
r1=requests.get(actrual)
r1.status_code

200

In [7]:
new_soup=BeautifulSoup(r1.text,'html.parser')
var_dic['product_name']=new_soup.find('h4',itemprop='name').text.strip()
list.append(var_dic)
list

[{'product_name': 'Asus VivoBook X441NA-GA190',
  'product_para': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_url': '/test-sites/e-commerce/allinone/product/60',
  'product_price': '$295.99',
  'procut_review': '14 reviews'}]

## a5.2 Extract product details from first row & save into csv file.

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url='https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops'
r=requests.get(main_url)
soup=BeautifulSoup(r.text,'html.parser')
products=soup.find_all('div',class_='col-md-4 col-xl-4 col-lg-4')
list=[]
for i in products[0:3]:
    var_dic={
        'product_name':'',
        'product_para':'',
        'product_img':'',
        'product_url':'',
        'product_price':'',
        'procut_review':'',
}
    var_dic['product_name']=i.find('a').text.strip()
    var_dic['product_para']=i.find('p',class_='description card-text').text.strip()
    var_dic['product_img']=i.find('img')['src']
    var_dic['product_url']=i.find('a')['href']
    url='https://webscraper.io'
    actual_url=url+var_dic['product_url']
    web=requests.get(actual_url)
    new_soup1=BeautifulSoup(web.text,'html.parser')
    var_dic['product_name']=new_soup1.find('h4',itemprop='name').text.strip()
    var_dic['product_para']=i.find('p',class_='description card-text').text.strip()
    var_dic['product_img']=i.find('img')['src']
    var_dic['product_price']=i.find('span').text.strip()
    var_dic['procut_review']=i.find('p',class_='review-count float-end').text.strip()
    list.append(var_dic)
list

[{'product_name': 'Asus VivoBook X441NA-GA190',
  'product_para': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_url': '/test-sites/e-commerce/allinone/product/60',
  'product_price': '$295.99',
  'procut_review': '14 reviews'},
 {'product_name': 'Prestigio SmartBook 133S Dark Grey',
  'product_para': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_url': '/test-sites/e-commerce/allinone/product/61',
  'product_price': '$299',
  'procut_review': '8 reviews'},
 {'product_name': 'Prestigio SmartBook 133S Gold',
  'product_para': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_url': '/test-sites/e-commerce/allinone/product/62',
  'product_price': '$299',
  'procut_review': '12 reviews'}]