In [ ]:
dict_pro = {
    "Product_name":"",
    "Product_url":"",

    "Product_Description":"",
    "UPC":"", 
    # "Product_Type":"",
    # "Price_excl_tax":"",
    # "Price_incl_tax":"",
    "Tax":"",
    # "Availability_numbers":"",
    # "Number_of_reviews":"",
    "product_img":"",
    "product_reviews_star_no":"",
    "product_price":"",
    "product_availabililty":""
}

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url = "https://books.toscrape.com/"
r = requests.get(main_url)
r.status_code

200

In [4]:
soup = BeautifulSoup(r.text,"html")
products = soup.find_all("li",class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3") # finding all products div
print("total products are ",len(products))

total products are  20

In [5]:
list = []
for fst_pro in products:
    dict_pro = {
    "Product_name":"",
    "Product_url":"",
    "product_img":"",
    "product_price":"",
    "product_availabililty":""
    }
    dict_pro["Product_name"]= fst_pro.find("h3").text
    dict_pro["product_price"]= fst_pro.find("p",class_ = "price_color").text
    dict_pro["product_availabililty"]= fst_pro.find("p",class_ = "instock availability").text.strip()
    dict_pro["product_img"]= fst_pro.find("img")["src"]
    dict_pro["Product_url"]= fst_pro.find("a")["href"]
    list.append(dict_pro)

df  = pd.DataFrame(list)
df

,Product_name,Product_url,product_img,product_price,product_availabililty
0,A Light in the ...,catalogue/a-light-in-the-attic_1000/index.html,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,Â£51.77,In stock
1,Tipping the Velvet,catalogue/tipping-the-velvet_999/index.html,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...,Â£53.74,In stock
2,Soumission,catalogue/soumission_998/index.html,media/cache/3e/ef/3eef99c9d9adef34639f51066202...,Â£50.10,In stock
3,Sharp Objects,catalogue/sharp-objects_997/index.html,media/cache/32/51/3251cf3a3412f53f339e42cac213...,Â£47.82,In stock
4,Sapiens: A Brief History ...,catalogue/sapiens-a-brief-history-of-humankind...,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...,Â£54.23,In stock
5,The Requiem Red,catalogue/the-requiem-red_995/index.html,media/cache/68/33/68339b4c9bc034267e1da611ab3b...,Â£22.65,In stock
6,The Dirty Little Secrets ...,catalogue/the-dirty-little-secrets-of-getting-...,media/cache/92/27/92274a95b7c251fea59a2b8a7827...,Â£33.34,In stock
7,The Coming Woman: A ...,catalogue/the-coming-woman-a-novel-based-on-th...,media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78...,Â£17.93,In stock
8,The Boys in the ...,catalogue/the-boys-in-the-boat-nine-americans-...,media/cache/66/88/66883b91f6804b2323c8369331cb...,Â£22.60,In stock
9,The Black Maria,catalogue/the-black-maria_991/index.html,media/cache/58/46/5846057e28022268153beff6d352...,Â£52.15,In stock
10,Starving Hearts (Triangular Trade ...,catalogue/starving-hearts-triangular-trade-tri...,media/cache/be/f4/bef44da28c98f905a3ebec0b87be...,Â£13.99,In stock
11,Shakespeare's Sonnets,catalogue/shakespeares-sonnets_989/index.html,media/cache/10/48/1048f63d3b5061cd2f424d20b3f9...,Â£20.66,In stock
12,Set Me Free,catalogue/set-me-free_988/index.html,media/cache/5b/88/5b88c52633f53cacf162c15f4f82...,Â£17.46,In stock
13,Scott Pilgrim's Precious Little ...,catalogue/scott-pilgrims-precious-little-life-...,media/cache/94/b1/94b1b8b244bce9677c2f29ccc890...,Â£52.29,In stock
14,Rip it Up and ...,catalogue/rip-it-up-and-start-again_986/index....,media/cache/81/c4/81c4a973364e17d01f217e118825...,Â£35.02,In stock
15,Our Band Could Be ...,catalogue/our-band-could-be-your-life-scenes-f...,media/cache/54/60/54607fe8945897cdcced0044103b...,Â£57.25,In stock
16,Olio,catalogue/olio_984/index.html,media/cache/55/33/553310a7162dfbc2c6d19a84da0d...,Â£23.88,In stock
17,Mesaerion: The Best Science ...,catalogue/mesaerion-the-best-science-fiction-s...,media/cache/09/a3/09a3aef48557576e1a85ba7efea8...,Â£37.59,In stock
18,Libertarianism for Beginners,catalogue/libertarianism-for-beginners_982/ind...,media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736...,Â£51.33,In stock
19,It's Only the Himalayas,catalogue/its-only-the-himalayas_981/index.html,media/cache/27/a5/27a53d0bb95bdd88288eaf66c923...,Â£45.17,In stock

In [ ]:
fst_pro = products[0]

dict_pro["Product_name"]= fst_pro.find("h3").text
dict_pro["product_price"]= fst_pro.find("p",class_ = "price_color").text
dict_pro["product_availabililty"]= fst_pro.find("p",class_ = "instock availability").text.strip()
dict_pro["product_img"]= fst_pro.find("img")["src"]
dict_pro["product_url"]= fst_pro.find("a")["href"]
dict_pro

In [8]:
act_url = main_url + dict_pro["Product_url"]

req = requests.get(act_url)

soup_nw = BeautifulSoup(req.text,"html")

# dict_pro["Product_Description"] =  soup_nw.find("article",class_ = "product_page").find_all("p")[-1].text
dict_pro["Product_Description"] =  soup_nw.find("div",id = "product_description").find_next_sibling().text.strip()


for i in soup_nw.find_all("tr"):
    dict_pro[i.find("th").text] = i.find("td").text

dict_pro["Product_name"] = soup_nw.find("h1").text
dict_pro["product_reviews_star_no"] =  soup_nw.find("p",class_ = "star-rating").attrs["class"][1]
dict_pro

{'Product_name': "It's Only the Himalayas",
 'Product_url': 'catalogue/its-only-the-himalayas_981/index.html',
 'product_img': 'media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg',
 'product_price': 'Â£45.17',
 'product_availabililty': 'In stock',
 'Product_Description': 'â\x80\x9cWherever you go, whatever you do, just . . . donâ\x80\x99t do anything stupid.â\x80\x9d â\x80\x94My MotherDuring her yearlong adventure backpacking from South Africa to Singapore, S. Bedford definitely did a few things her mother might classify as "stupid." She swam with great white sharks in South Africa, ran from lions in Zimbabwe, climbed a Himalayan mountain without training in Nepal, and wa â\x80\x9cWherever you go, whatever you do, just . . . donâ\x80\x99t do anything stupid.â\x80\x9d â\x80\x94My MotherDuring her yearlong adventure backpacking from South Africa to Singapore, S. Bedford definitely did a few things her mother might classify as "stupid." She swam with great white sharks in South Africa, ran from lions in Zimbabwe, climbed a Himalayan mountain without training in Nepal, and watched as her friend was attacked by a monkey in Indonesia.But interspersed in those slightly more crazy moments, Sue Bedfored and her friend "Sara the Stoic" experienced the sights, sounds, life, and culture of fifteen countries. Joined along the way by a few friends and their aging fathers here and there, Sue and Sara experience the trip of a lifetime. They fall in love with the world, cultivate an appreciation for home, and discover who, or what, they want to become.It\'s Only the Himalayas is the incredibly funny, sometimes outlandish, always entertaining confession of a young backpacker that will inspire you to take your own adventure. ...more',
 'UPC': 'a22124811bfa8350',
 'Product Type': 'Books',
 'Price (excl. tax)': 'Â£45.17',
 'Price (incl. tax)': 'Â£45.17',
 'Tax': 'Â£0.00',
 'Availability': 'In stock (19 available)',
 'Number of reviews': '0',
 'product_reviews_star_no': 'Two'}

In [ ]:
dict = {}
dict["std_name"] = "asif kasi"
dict["fname"] = "qasim kasi"
dict

In [9]:
df

,Product_name,Product_url,product_img,product_price,product_availabililty
0,A Light in the ...,catalogue/a-light-in-the-attic_1000/index.html,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,Â£51.77,In stock
1,Tipping the Velvet,catalogue/tipping-the-velvet_999/index.html,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...,Â£53.74,In stock
2,Soumission,catalogue/soumission_998/index.html,media/cache/3e/ef/3eef99c9d9adef34639f51066202...,Â£50.10,In stock
3,Sharp Objects,catalogue/sharp-objects_997/index.html,media/cache/32/51/3251cf3a3412f53f339e42cac213...,Â£47.82,In stock
4,Sapiens: A Brief History ...,catalogue/sapiens-a-brief-history-of-humankind...,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...,Â£54.23,In stock
5,The Requiem Red,catalogue/the-requiem-red_995/index.html,media/cache/68/33/68339b4c9bc034267e1da611ab3b...,Â£22.65,In stock
6,The Dirty Little Secrets ...,catalogue/the-dirty-little-secrets-of-getting-...,media/cache/92/27/92274a95b7c251fea59a2b8a7827...,Â£33.34,In stock
7,The Coming Woman: A ...,catalogue/the-coming-woman-a-novel-based-on-th...,media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78...,Â£17.93,In stock
8,The Boys in the ...,catalogue/the-boys-in-the-boat-nine-americans-...,media/cache/66/88/66883b91f6804b2323c8369331cb...,Â£22.60,In stock
9,The Black Maria,catalogue/the-black-maria_991/index.html,media/cache/58/46/5846057e28022268153beff6d352...,Â£52.15,In stock
10,Starving Hearts (Triangular Trade ...,catalogue/starving-hearts-triangular-trade-tri...,media/cache/be/f4/bef44da28c98f905a3ebec0b87be...,Â£13.99,In stock
11,Shakespeare's Sonnets,catalogue/shakespeares-sonnets_989/index.html,media/cache/10/48/1048f63d3b5061cd2f424d20b3f9...,Â£20.66,In stock
12,Set Me Free,catalogue/set-me-free_988/index.html,media/cache/5b/88/5b88c52633f53cacf162c15f4f82...,Â£17.46,In stock
13,Scott Pilgrim's Precious Little ...,catalogue/scott-pilgrims-precious-little-life-...,media/cache/94/b1/94b1b8b244bce9677c2f29ccc890...,Â£52.29,In stock
14,Rip it Up and ...,catalogue/rip-it-up-and-start-again_986/index....,media/cache/81/c4/81c4a973364e17d01f217e118825...,Â£35.02,In stock
15,Our Band Could Be ...,catalogue/our-band-could-be-your-life-scenes-f...,media/cache/54/60/54607fe8945897cdcced0044103b...,Â£57.25,In stock
16,Olio,catalogue/olio_984/index.html,media/cache/55/33/553310a7162dfbc2c6d19a84da0d...,Â£23.88,In stock
17,Mesaerion: The Best Science ...,catalogue/mesaerion-the-best-science-fiction-s...,media/cache/09/a3/09a3aef48557576e1a85ba7efea8...,Â£37.59,In stock
18,Libertarianism for Beginners,catalogue/libertarianism-for-beginners_982/ind...,media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736...,Â£51.33,In stock
19,It's Only the Himalayas,catalogue/its-only-the-himalayas_981/index.html,media/cache/27/a5/27a53d0bb95bdd88288eaf66c923...,Â£45.17,In stock

In [10]:
df["Product_url"]

0        catalogue/a-light-in-the-attic_1000/index.html
1           catalogue/tipping-the-velvet_999/index.html
2                   catalogue/soumission_998/index.html
3                catalogue/sharp-objects_997/index.html
4     catalogue/sapiens-a-brief-history-of-humankind...
5              catalogue/the-requiem-red_995/index.html
6     catalogue/the-dirty-little-secrets-of-getting-...
7     catalogue/the-coming-woman-a-novel-based-on-th...
8     catalogue/the-boys-in-the-boat-nine-americans-...
9              catalogue/the-black-maria_991/index.html
10    catalogue/starving-hearts-triangular-trade-tri...
11        catalogue/shakespeares-sonnets_989/index.html
12                 catalogue/set-me-free_988/index.html
13    catalogue/scott-pilgrims-precious-little-life-...
14    catalogue/rip-it-up-and-start-again_986/index....
15    catalogue/our-band-could-be-your-life-scenes-f...
16                        catalogue/olio_984/index.html
17    catalogue/mesaerion-the-best-science-fiction-s...
18    catalogue/libertarianism-for-beginners_982/ind...
19      catalogue/its-only-the-himalayas_981/index.html
Name: Product_url, dtype: object

In [1]:
list_nw = []
for i in df["Product_url"]:
    # print(main_url + i)
    dict_pro = {}

    act_url = main_url + i
    print(act_url)

    # dict_pro["Product_url"]

    req = requests.get(act_url)

    soup_nw = BeautifulSoup(req.text,"html")

    # dict_pro["Product_Description"] =  soup_nw.find("article",class_ = "product_page").find_all("p")[-1].text
    dict_pro["Product_Description"] =  soup_nw.find("div",id = "product_description").find_next_sibling().text.strip()
    
    for i in soup_nw.find_all("tr"):
        dict_pro[i.find("th").text] = i.find("td").text

    dict_pro["Product_name"] = soup_nw.find("h1").text
    dict_pro["product_reviews_star_no"] =  soup_nw.find("p",class_ = "star-rating").attrs["class"][1]
    list_nw.append(dict_pro)

df_nw = pd.DataFrame(list_nw)
df_nw

NameError: name 'df' is not defined