## https://webscraper.io/test-sites Scrap Productname, index, desc, url, img_url

In [87]:
import requests  # requests library
from bs4 import BeautifulSoup # BeautifulSoup
import pandas as pd
url = "https://webscraper.io/test-sites" # url of webpage
response = requests.get(url)
soup = BeautifulSoup(response.content, "html.parser")  # parsing html 
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="SpFia47qPMPpCblYTr93NKx1HlRZsM0C">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Test Sites | Web Scraper\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance with our dedicated test sites. Experiment with different configurations, extract data, and evaluate the tool\'s capabilities in real-world scenarios" name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites" rel="canonical"/>\n    <meta content="Test Sites | Web Scraper" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance with our dedicated test sites. Experiment with different configurations, extract data, and evaluate the tool\'s capabilities in real-world scenarios" property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-sites">\n    <p style="font-size:21px;">\n     Here are some sites that you can use for training while learning how to\n\t\t\tuse the Web Scraper.\n    </p>\n    <hr class="test-site-divider"/>\n    <div class="row test-site">\n     <div class="col-lg-7 order-lg-2">\n      <h2 class="site-heading">\n       <a href="/test-sites/e-commerce/allinone">\n        E-commerce site\n       </a>\n      </h2>\n      <p class="lead">\n       E-commerce site with multiple categories, subcategories.\n\t\t\t\t\tAll items are loaded in one page.\n      </p>\n     </div>\n     <div class="col-lg-5 order-lg-1">\n      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>\n     </div>\n    </div>\n    <hr class="test-site-divider"/>\n    <div class="row test-site">\n     <div class="col-lg-7 order-lg-2">\n      <h2 class="site-heading">\n       <a href="/test-sites/e-commerce/static">\n        E-commerce site with pagination links\n       </a>\n      </h2>\n      <p class="lead">\n       E-commerce site with multiple categories, subcategories.\n\t\t\t\t\tStandard links are used for pagination.\n      </p>\n     </div>\n     <div class="col-lg-5 order-lg-1">\n      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-static.png"/>\n     </div>\n    </div>\n    <hr class="test-site-divider"/>\n    <div class="row test-site">\n     <div class="col-lg-7 order-lg-2">\n      <h2 class="site-heading">\n       <a href="/test-sites/e-commerce/ajax">\n        E-commerce site with AJAX pagination links\n       </a>\n      </h2>\n      <p class="lead">\n       E-commerce site with multiple categories, subcategories.\n\t\t\t\t\tDynamic links that use data without reloading the page for\n\t\t\t\t\tpagination.\n      </p>\n     </div>\n     <div class="col-lg-5 order-lg-1">\n      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-ajax.png"/>\n     </div>\n    </div>\n    <hr class="test-site-divider"/>\n    <div class="row test-site">\n     <div class="col-lg-7 order-lg-2">\n      <h2 class="site-heading">\n       <a href="/test-sites/e-commerce/more">\n        E-commerce site with "Load more" buttons\n       </a>\n      </h2>\n      <p class="lead">\n       E-commerce site with multiple categories, subcategories.\n\t\t\t\t\tInstead of using pagination this site uses a "Load more"\n\t\t\t\t\tbutton to load more items.\n      </p>\n     </div>\n     <div class="col-lg-5 order-lg-1">\n      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-more.png"/>\n     </div>\n    </div>\n    <hr class="test-site-divider"/>\n    <div class="row test-site">\n     <div class="col-lg-7 order-lg-2">\n      <h2 class="site-heading">\n       <a href="/test-sites/e-commerce/scroll">\n        E-commerce site that loads items while scrolling\n       </a>\n      </h2>\n      <p class="lead">\n       E-commerce site with multiple categories, subcategories.\n\t\t\t\t\tInstead of using pagination this site loads items when user\n\t\t\t\t\tscrolls the page down.\n      </p>\n     </div>\n     <div class="col-lg-5 order-lg-1">\n      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>\n     </div>\n    </div>\n    <hr class="test-site-divider"/>\n    <div class="row test-site">\n     <div class="col-lg-7 order-lg-2">\n      <h2 class="site-heading">\n       <a href="/test-sites/tables">\n        Table playground\n       </a>\n      </h2>\n      <p class="lead">\n       This page contains multiple tables. You can train using Table\n\t\t\t\t\tselector here.\n      </p>\n     </div>\n     <div class="col-lg-5 order-lg-1">\n      <img alt="table playground" src="/images/test-sites/screens/test-sites-tables.png"/>\n     </div>\n    </div>\n   </div>\n   <div class="clearfix">\n   </div>\n   <div class="push">\n   </div>\n  </div>\n  <div class="container-fluid footer" id="layout-footer">\n   <div class="container">\n    <div class="row">\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         Products\n        </p>\n       </li>\n       <li>\n        <a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         Web Scraper browser extension\n        </a>\n       </li>\n       <li>\n        <a href="/cloud-scraper">\n         Web Scraper Cloud\n        </a>\n       </li>\n      </ul>\n     </div>\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         Company\n        </p>\n       </li>\n       <li>\n        <a href="/about-us">\n         About us\n        </a>\n       </li>\n       <li>\n        <a href="/contact">\n         Contact\n        </a>\n       </li>\n       <li>\n        <a href="/privacy-policy">\n         Website Privacy Policy\n        </a>\n       </li>\n       <li>\n        <a href="/extension-privacy-policy">\n         Browser Extension Privacy Policy\n        </a>\n       </li>\n       <li>\n        <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">\n         Media kit\n        </a>\n       </li>\n       <li>\n        <a href="/jobs">\n         Jobs\n        </a>\n       </li>\n      </ul>\n     </div>\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         Resources\n        </p>\n       </li>\n       <li>\n        <a href="/blog">\n         Blog\n        </a>\n       </li>\n       <li>\n        <a href="/documentation">\n         Documentation\n        </a>\n       </li>\n       <li>\n        <a href="/tutorials">\n         Video Tutorials\n        </a>\n       </li>\n       <li>\n        <a href="/screenshots">\n         Screenshots\n        </a>\n       </li>\n       <li>\n        <a href="/test-sites">\n         Test Sites\n        </a>\n       </li>\n       <li>\n        <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n         Forum\n        </a>\n       </li>\n       <li>\n        <a href="https://status.webscraper.io/" rel="noopener" target="_blank">\n         Status\n        </a>\n       </li>\n      </ul>\n     </div>\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         CONTACT US\n        </p>\n       </li>\n       <li>\n        <a href="mailto:info@webscraper.io">\n         info@webscraper.io\n        </a>\n       </li>\n       <li>\n        Ubelu 5-71,\n        <br/>\n        Adazi, Latvia, LV-2164\n       </li>\n      </ul>\n      <ul class="smedia">\n       <li>\n        <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">\n         <i class="ws-icon ws-icon-facebook-f">\n         </i>\n        </a>\n       </li>\n       <li>\n        <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">\n         <i class="ws-icon ws-icon-linkedin">\n         </i>\n        </a>\n       </li>\n       <li>\n        <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">\n         <i class="ws-icon ws-icon-youtube">\n         </i>\n        </a>\n       </li>\n       <li>\n        <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i class="browser-icon ws-icon ws-icon-chrome-dark">\n         </i>\n        </a>\n       </li>\n      </ul>\n     </div>\n    </div>\n    <div class="row">\n     <div class="col-lg-12">\n      <p class="copyright">\n       Copyright © 2025\n       <b>\n        Web Scraper\n       </b>\n       | All rights reserved\n      </p>\n     </div>\n    </div>\n   </div>\n  </div>\n </body>\n</html>\n'

In [88]:
var_dict = {
    "product_name":"",
    "product_index":"1",
    "product_desc":"",
    "product_url":"",
    "img_url":""

}

In [89]:
var_fst_div = soup.find("div",class_="row test-site")
print(var_fst_div.prettify())

<div class="row test-site">
 <div class="col-lg-7 order-lg-2">
  <h2 class="site-heading">
   <a href="/test-sites/e-commerce/allinone">
    E-commerce site
   </a>
  </h2>
  <p class="lead">
   E-commerce site with multiple categories, subcategories.
					All items are loaded in one page.
  </p>
 </div>
 <div class="col-lg-5 order-lg-1">
  <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
 </div>
</div>

In [90]:
var_dict["product_name"] = var_fst_div.find("h2").text.strip()
var_dict["product_desc"] = var_fst_div.find("p").text.strip().replace("\n"," ").replace("\t","")
var_dict["product_url"] = var_fst_div.find("a")["href"]
# var_dict
var_dict["img_url"] = var_fst_div.find("img")["src"]
var_dict

{'product_name': 'E-commerce site',
 'product_index': '1',
 'product_desc': 'E-commerce site with multiple categories, subcategories. All items are loaded in one page.',
 'product_url': '/test-sites/e-commerce/allinone',
 'img_url': '/images/test-sites/screens/test-sites-ecommerce-allinone.png'}

In [91]:
var_fst_div = soup.find("div",class_="row test-site")
var_lsit_of_div = soup.find_all("div",class_="row test-site")

In [92]:
list = []
for div in var_lsit_of_div:
    var_dict = {
    "product_name":"",
    # "product_index":"1",
    "product_desc":"",
    "product_url":"",
    "img_url":""

    }
    var_dict["product_name"] = div.find("h2").text.strip()
    var_dict["product_desc"] = div.find("p").text.strip().replace("\n"," ").replace("\t","")
    var_dict["product_url"] = div.find("a")["href"]
    # var_dict
    var_dict["img_url"] = div.find("img")["src"]
    print(var_dict)
    print()
    list.append(var_dict)

{'product_name': 'E-commerce site', 'product_desc': 'E-commerce site with multiple categories, subcategories. All items are loaded in one page.', 'product_url': '/test-sites/e-commerce/allinone', 'img_url': '/images/test-sites/screens/test-sites-ecommerce-allinone.png'}

{'product_name': 'E-commerce site with pagination links', 'product_desc': 'E-commerce site with multiple categories, subcategories. Standard links are used for pagination.', 'product_url': '/test-sites/e-commerce/static', 'img_url': '/images/test-sites/screens/test-sites-ecommerce-static.png'}

{'product_name': 'E-commerce site with AJAX pagination links', 'product_desc': 'E-commerce site with multiple categories, subcategories. Dynamic links that use data without reloading the page for pagination.', 'product_url': '/test-sites/e-commerce/ajax', 'img_url': '/images/test-sites/screens/test-sites-ecommerce-ajax.png'}

{'product_name': 'E-commerce site with "Load more" buttons', 'product_desc': 'E-commerce site with multiple categories, subcategories. Instead of using pagination this site uses a "Load more" button to load more items.', 'product_url': '/test-sites/e-commerce/more', 'img_url': '/images/test-sites/screens/test-sites-ecommerce-more.png'}

{'product_name': 'E-commerce site that loads items while scrolling', 'product_desc': 'E-commerce site with multiple categories, subcategories. Instead of using pagination this site loads items when user scrolls the page down.', 'product_url': '/test-sites/e-commerce/scroll', 'img_url': '/images/test-sites/screens/test-sites-ecommerce-allinone.png'}

{'product_name': 'Table playground', 'product_desc': 'This page contains multiple tables. You can train using Table selector here.', 'product_url': '/test-sites/tables', 'img_url': '/images/test-sites/screens/test-sites-tables.png'}

In [93]:
import pandas as pd

df = pd.DataFrame(list)
df

,product_name,product_desc,product_url,img_url
0,E-commerce site,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/allinone,/images/test-sites/screens/test-sites-ecommerc...
1,E-commerce site with pagination links,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/static,/images/test-sites/screens/test-sites-ecommerc...
2,E-commerce site with AJAX pagination links,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/ajax,/images/test-sites/screens/test-sites-ecommerc...
3,"E-commerce site with ""Load more"" buttons","E-commerce site with multiple categories, subc...",/test-sites/e-commerce/more,/images/test-sites/screens/test-sites-ecommerc...
4,E-commerce site that loads items while scrolling,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/scroll,/images/test-sites/screens/test-sites-ecommerc...
5,Table playground,This page contains multiple tables. You can tr...,/test-sites/tables,/images/test-sites/screens/test-sites-tables.png

## 4. https://webscraper.io/test-sites/tables

## 4.1 Extract first Table of a page & save into another csv file.

In [94]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/tables")
r.status_code

200

In [95]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="e5wxEpQJZ0YFfqu774aABTEhp0J67Jdj">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Table Playground | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features on basic table layouts. Practice extracting structured table data." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/tables" rel="canonical"/>\n    <meta content="Table Playground | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features on basic table layouts. Practice extracting structured table data." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/tables" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container">\n    <div class="test-site">\n     <div class="row">\n      <div class="col-lg-3 sidebar">\n       <div class="navbar-light sidebar" role="navigation">\n        <div class="sidebar-nav navbar-collapse">\n         <ul class="nav flex-column tables-nav" id="side-menu">\n          <li class="nav-item">\n           <a class="table-nav-button semantically-correct-button nav-link active" href="/test-sites/tables/tables-semantically-correct">\n            Semantically correct tables\n           </a>\n          </li>\n          <li class="nav-item">\n           <a class="table-nav-button button-without-thead nav-link" href="/test-sites/tables/tables-without-thead">\n            Tables without the thead tag\n           </a>\n          </li>\n          <li class="nav-item">\n           <a class="table-nav-button button-multiple-headers nav-link" href="/test-sites/tables/tables-multiple-header-rows">\n            Tables with multiple header rows\n           </a>\n          </li>\n         </ul>\n        </div>\n       </div>\n      </div>\n      <div class="col-lg-9">\n       <div class="tables-all">\n        <div class="jumbotron tables-initial-text">\n         <h2>\n          Table playground\n         </h2>\n         <p class="lead">\n          You can train using Table selector here.\n         </p>\n        </div>\n        <div class="tables-semantically-correct">\n         <h2>\n          Semantically correct table with thead and tbody\n         </h2>\n         <p>\n          Table selector automatically detects header and data rows.\n         </p>\n         <table class="table table-bordered">\n          <thead>\n           <tr>\n            <th>\n             #\n            </th>\n            <th>\n             First Name\n            </th>\n            <th>\n             Last Name\n            </th>\n            <th>\n             Username\n            </th>\n           </tr>\n          </thead>\n          <tbody>\n           <tr>\n            <td>\n             1\n            </td>\n            <td>\n             Mark\n            </td>\n            <td>\n             Otto\n            </td>\n            <td>\n             @mdo\n            </td>\n           </tr>\n           <tr>\n            <td>\n             2\n            </td>\n            <td>\n             Jacob\n            </td>\n            <td>\n             Thornton\n            </td>\n            <td>\n             @fat\n            </td>\n           </tr>\n           <tr>\n            <td>\n             3\n            </td>\n            <td>\n             Larry\n            </td>\n            <td>\n             the Bird\n            </td>\n            <td>\n             @twitter\n            </td>\n           </tr>\n          </tbody>\n         </table>\n         <table class="table table-bordered table-bordered2">\n          <thead>\n           <tr>\n            <th>\n             #\n            </th>\n            <th>\n             First Name\n            </th>\n            <th>\n             Last Name\n            </th>\n            <th>\n             Username\n            </th>\n           </tr>\n          </thead>\n          <tbody>\n           <tr>\n            <td>\n             4\n            </td>\n            <td>\n             Harry\n            </td>\n            <td>\n             Potter\n            </td>\n            <td>\n             @hp\n            </td>\n           </tr>\n           <tr>\n            <td>\n             5\n            </td>\n            <td>\n             John\n            </td>\n            <td>\n             Snow\n            </td>\n            <td>\n             @dunno\n            </td>\n           </tr>\n           <tr>\n            <td>\n             6\n            </td>\n            <td>\n             Tim\n            </td>\n            <td>\n             Bean\n            </td>\n            <td>\n             @timbean\n            </td>\n           </tr>\n          </tbody>\n         </table>\n        </div>\n       </div>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="clearfix">\n   </div>\n   <div class="push">\n   </div>\n  </div>\n  <div class="container-fluid footer" id="layout-footer">\n   <div class="container">\n    <div class="row">\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         Products\n        </p>\n       </li>\n       <li>\n        <a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         Web Scraper browser extension\n        </a>\n       </li>\n       <li>\n        <a href="/cloud-scraper">\n         Web Scraper Cloud\n        </a>\n       </li>\n      </ul>\n     </div>\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         Company\n        </p>\n       </li>\n       <li>\n        <a href="/about-us">\n         About us\n        </a>\n       </li>\n       <li>\n        <a href="/contact">\n         Contact\n        </a>\n       </li>\n       <li>\n        <a href="/privacy-policy">\n         Website Privacy Policy\n        </a>\n       </li>\n       <li>\n        <a href="/extension-privacy-policy">\n         Browser Extension Privacy Policy\n        </a>\n       </li>\n       <li>\n        <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">\n         Media kit\n        </a>\n       </li>\n       <li>\n        <a href="/jobs">\n         Jobs\n        </a>\n       </li>\n      </ul>\n     </div>\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         Resources\n        </p>\n       </li>\n       <li>\n        <a href="/blog">\n         Blog\n        </a>\n       </li>\n       <li>\n        <a href="/documentation">\n         Documentation\n        </a>\n       </li>\n       <li>\n        <a href="/tutorials">\n         Video Tutorials\n        </a>\n       </li>\n       <li>\n        <a href="/screenshots">\n         Screenshots\n        </a>\n       </li>\n       <li>\n        <a href="/test-sites">\n         Test Sites\n        </a>\n       </li>\n       <li>\n        <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n         Forum\n        </a>\n       </li>\n       <li>\n        <a href="https://status.webscraper.io/" rel="noopener" target="_blank">\n         Status\n        </a>\n       </li>\n      </ul>\n     </div>\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         CONTACT US\n        </p>\n       </li>\n       <li>\n        <a href="mailto:info@webscraper.io">\n         info@webscraper.io\n        </a>\n       </li>\n       <li>\n        Ubelu 5-71,\n        <br/>\n        Adazi, Latvia, LV-2164\n       </li>\n      </ul>\n      <ul class="smedia">\n       <li>\n        <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">\n         <i class="ws-icon ws-icon-facebook-f">\n         </i>\n        </a>\n       </li>\n       <li>\n        <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">\n         <i class="ws-icon ws-icon-linkedin">\n         </i>\n        </a>\n       </li>\n       <li>\n        <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">\n         <i class="ws-icon ws-icon-youtube">\n         </i>\n        </a>\n       </li>\n       <li>\n        <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i class="browser-icon ws-icon ws-icon-chrome-dark">\n         </i>\n        </a>\n       </li>\n      </ul>\n     </div>\n    </div>\n    <div class="row">\n     <div class="col-lg-12">\n      <p class="copyright">\n       Copyright © 2025\n       <b>\n        Web Scraper\n       </b>\n       | All rights reserved\n      </p>\n     </div>\n    </div>\n   </div>\n  </div>\n </body>\n</html>\n'

In [96]:
tb = soup.find("table" , class_ = "table table-bordered")
tb

<table class="table table-bordered">
<thead>
<tr>
<th>#</th>
<th>First Name</th>
<th>Last Name</th>
<th>Username</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>Mark</td>
<td>Otto</td>
<td>@mdo</td>
</tr>
<tr>
<td>2</td>
<td>Jacob</td>
<td>Thornton</td>
<td>@fat</td>
</tr>
<tr>
<td>3</td>
<td>Larry</td>
<td>the Bird</td>
<td>@twitter</td>
</tr>
</tbody>
</table>

In [97]:
trs = tb.find_all("tr")
trs

[<tr>
 <th>#</th>
 <th>First Name</th>
 <th>Last Name</th>
 <th>Username</th>
 </tr>,
 <tr>
 <td>1</td>
 <td>Mark</td>
 <td>Otto</td>
 <td>@mdo</td>
 </tr>,
 <tr>
 <td>2</td>
 <td>Jacob</td>
 <td>Thornton</td>
 <td>@fat</td>
 </tr>,
 <tr>
 <td>3</td>
 <td>Larry</td>
 <td>the Bird</td>
 <td>@twitter</td>
 </tr>]

In [98]:
dl = []
for td in trs:
    dr = {
    "First Name" : "" ,
    "Last Name" : "" ,
    "Username" : ""
}
    cols = td.find_all("td")
    if len(cols) >= 3:
         dr["First Name"] = cols[1].text.strip()
         dr["Last Name"] = cols[2].text.strip()
         dr["Username"] = cols[3].text.strip()
         dl.append(dr)
dl

[{'First Name': 'Mark', 'Last Name': 'Otto', 'Username': '@mdo'},
 {'First Name': 'Jacob', 'Last Name': 'Thornton', 'Username': '@fat'},
 {'First Name': 'Larry', 'Last Name': 'the Bird', 'Username': '@twitter'}]

In [99]:
df = pd.DataFrame(dl)
df.to_csv("webscraper_q4.1.csv" , index = False)

## 4.2 Extract second Table of a page & save into another csv file.

In [100]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/tables")
r.status_code

200

In [101]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="e5wxEpQJZ0YFfqu774aABTEhp0J67Jdj">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Table Playground | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features on basic table layouts. Practice extracting structured table data." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/tables" rel="canonical"/>\n    <meta content="Table Playground | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features on basic table layouts. Practice extracting structured table data." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/tables" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container">\n    <div class="test-site">\n     <div class="row">\n      <div class="col-lg-3 sidebar">\n       <div class="navbar-light sidebar" role="navigation">\n        <div class="sidebar-nav navbar-collapse">\n         <ul class="nav flex-column tables-nav" id="side-menu">\n          <li class="nav-item">\n           <a class="table-nav-button semantically-correct-button nav-link active" href="/test-sites/tables/tables-semantically-correct">\n            Semantically correct tables\n           </a>\n          </li>\n          <li class="nav-item">\n           <a class="table-nav-button button-without-thead nav-link" href="/test-sites/tables/tables-without-thead">\n            Tables without the thead tag\n           </a>\n          </li>\n          <li class="nav-item">\n           <a class="table-nav-button button-multiple-headers nav-link" href="/test-sites/tables/tables-multiple-header-rows">\n            Tables with multiple header rows\n           </a>\n          </li>\n         </ul>\n        </div>\n       </div>\n      </div>\n      <div class="col-lg-9">\n       <div class="tables-all">\n        <div class="jumbotron tables-initial-text">\n         <h2>\n          Table playground\n         </h2>\n         <p class="lead">\n          You can train using Table selector here.\n         </p>\n        </div>\n        <div class="tables-semantically-correct">\n         <h2>\n          Semantically correct table with thead and tbody\n         </h2>\n         <p>\n          Table selector automatically detects header and data rows.\n         </p>\n         <table class="table table-bordered">\n          <thead>\n           <tr>\n            <th>\n             #\n            </th>\n            <th>\n             First Name\n            </th>\n            <th>\n             Last Name\n            </th>\n            <th>\n             Username\n            </th>\n           </tr>\n          </thead>\n          <tbody>\n           <tr>\n            <td>\n             1\n            </td>\n            <td>\n             Mark\n            </td>\n            <td>\n             Otto\n            </td>\n            <td>\n             @mdo\n            </td>\n           </tr>\n           <tr>\n            <td>\n             2\n            </td>\n            <td>\n             Jacob\n            </td>\n            <td>\n             Thornton\n            </td>\n            <td>\n             @fat\n            </td>\n           </tr>\n           <tr>\n            <td>\n             3\n            </td>\n            <td>\n             Larry\n            </td>\n            <td>\n             the Bird\n            </td>\n            <td>\n             @twitter\n            </td>\n           </tr>\n          </tbody>\n         </table>\n         <table class="table table-bordered table-bordered2">\n          <thead>\n           <tr>\n            <th>\n             #\n            </th>\n            <th>\n             First Name\n            </th>\n            <th>\n             Last Name\n            </th>\n            <th>\n             Username\n            </th>\n           </tr>\n          </thead>\n          <tbody>\n           <tr>\n            <td>\n             4\n            </td>\n            <td>\n             Harry\n            </td>\n            <td>\n             Potter\n            </td>\n            <td>\n             @hp\n            </td>\n           </tr>\n           <tr>\n            <td>\n             5\n            </td>\n            <td>\n             John\n            </td>\n            <td>\n             Snow\n            </td>\n            <td>\n             @dunno\n            </td>\n           </tr>\n           <tr>\n            <td>\n             6\n            </td>\n            <td>\n             Tim\n            </td>\n            <td>\n             Bean\n            </td>\n            <td>\n             @timbean\n            </td>\n           </tr>\n          </tbody>\n         </table>\n        </div>\n       </div>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="clearfix">\n   </div>\n   <div class="push">\n   </div>\n  </div>\n  <div class="container-fluid footer" id="layout-footer">\n   <div class="container">\n    <div class="row">\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         Products\n        </p>\n       </li>\n       <li>\n        <a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         Web Scraper browser extension\n        </a>\n       </li>\n       <li>\n        <a href="/cloud-scraper">\n         Web Scraper Cloud\n        </a>\n       </li>\n      </ul>\n     </div>\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         Company\n        </p>\n       </li>\n       <li>\n        <a href="/about-us">\n         About us\n        </a>\n       </li>\n       <li>\n        <a href="/contact">\n         Contact\n        </a>\n       </li>\n       <li>\n        <a href="/privacy-policy">\n         Website Privacy Policy\n        </a>\n       </li>\n       <li>\n        <a href="/extension-privacy-policy">\n         Browser Extension Privacy Policy\n        </a>\n       </li>\n       <li>\n        <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">\n         Media kit\n        </a>\n       </li>\n       <li>\n        <a href="/jobs">\n         Jobs\n        </a>\n       </li>\n      </ul>\n     </div>\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         Resources\n        </p>\n       </li>\n       <li>\n        <a href="/blog">\n         Blog\n        </a>\n       </li>\n       <li>\n        <a href="/documentation">\n         Documentation\n        </a>\n       </li>\n       <li>\n        <a href="/tutorials">\n         Video Tutorials\n        </a>\n       </li>\n       <li>\n        <a href="/screenshots">\n         Screenshots\n        </a>\n       </li>\n       <li>\n        <a href="/test-sites">\n         Test Sites\n        </a>\n       </li>\n       <li>\n        <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n         Forum\n        </a>\n       </li>\n       <li>\n        <a href="https://status.webscraper.io/" rel="noopener" target="_blank">\n         Status\n        </a>\n       </li>\n      </ul>\n     </div>\n     <div class="col-lg-3">\n      <ul>\n       <li>\n        <p>\n         CONTACT US\n        </p>\n       </li>\n       <li>\n        <a href="mailto:info@webscraper.io">\n         info@webscraper.io\n        </a>\n       </li>\n       <li>\n        Ubelu 5-71,\n        <br/>\n        Adazi, Latvia, LV-2164\n       </li>\n      </ul>\n      <ul class="smedia">\n       <li>\n        <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">\n         <i class="ws-icon ws-icon-facebook-f">\n         </i>\n        </a>\n       </li>\n       <li>\n        <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">\n         <i class="ws-icon ws-icon-linkedin">\n         </i>\n        </a>\n       </li>\n       <li>\n        <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">\n         <i class="ws-icon ws-icon-youtube">\n         </i>\n        </a>\n       </li>\n       <li>\n        <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i class="browser-icon ws-icon ws-icon-chrome-dark">\n         </i>\n        </a>\n       </li>\n      </ul>\n     </div>\n    </div>\n    <div class="row">\n     <div class="col-lg-12">\n      <p class="copyright">\n       Copyright © 2025\n       <b>\n        Web Scraper\n       </b>\n       | All rights reserved\n      </p>\n     </div>\n    </div>\n   </div>\n  </div>\n </body>\n</html>\n'

In [102]:
tb = soup.find("table" , class_ = "table table-bordered table-bordered2")
tb

<table class="table table-bordered table-bordered2">
<thead>
<tr>
<th>#</th>
<th>First Name</th>
<th>Last Name</th>
<th>Username</th>
</tr>
</thead>
<tbody>
<tr>
<td>4</td>
<td>Harry</td>
<td>Potter</td>
<td>@hp</td>
</tr>
<tr>
<td>5</td>
<td>John</td>
<td>Snow</td>
<td>@dunno</td>
</tr>
<tr>
<td>6</td>
<td>Tim</td>
<td>Bean</td>
<td>@timbean</td>
</tr>
</tbody>
</table>

In [103]:
trs = tb.find_all("tr")
trs

[<tr>
 <th>#</th>
 <th>First Name</th>
 <th>Last Name</th>
 <th>Username</th>
 </tr>,
 <tr>
 <td>4</td>
 <td>Harry</td>
 <td>Potter</td>
 <td>@hp</td>
 </tr>,
 <tr>
 <td>5</td>
 <td>John</td>
 <td>Snow</td>
 <td>@dunno</td>
 </tr>,
 <tr>
 <td>6</td>
 <td>Tim</td>
 <td>Bean</td>
 <td>@timbean</td>
 </tr>]

In [104]:
dl = []
for td in trs:
    dr = {
    "First Name" : "" ,
    "Last Name" : "" ,
    "Username" : ""
}
    cols = td.find_all("td")
    if len(cols) >= 3:
         dr["First Name"] = cols[1].text.strip()
         dr["Last Name"] = cols[2].text.strip()
         dr["Username"] = cols[3].text.strip()
         dl.append(dr)
dl

[{'First Name': 'Harry', 'Last Name': 'Potter', 'Username': '@hp'},
 {'First Name': 'John', 'Last Name': 'Snow', 'Username': '@dunno'},
 {'First Name': 'Tim', 'Last Name': 'Bean', 'Username': '@timbean'}]

In [105]:
df = pd.DataFrame(dl)
df.to_csv("webscraper_q4.2.csv" , index = False)

## 4.3 Extract both Tables of a page & save into single csv file.

In [106]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/tables")
r.status_code

200

In [107]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="e5wxEpQJZ0YFfqu774aABTEhp0J67Jdj">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Table Playground | Web Scraper Test Sites</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="Test Web Scraper's features on basic table layouts. Practice extracting structured table data." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/tables" rel="canonical"/>
<meta content="Table Playground | Web Scraper Test Sites" property="og:title"/>
<meta content="Test Web Scraper's features on basic table layouts. Practice extracting structured table data." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/tables" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container">
<div class="test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column tables-nav" id="side-menu">
<li class="nav-item">
<a class="table-nav-button semantically-correct-button nav-link active" href="/test-sites/tables/tables-semantically-correct">Semantically correct tables</a>
</li>
<li class="nav-item">
<a class="table-nav-button button-without-thead nav-link" href="/test-sites/tables/tables-without-thead">Tables without the thead tag</a>
</li>
<li class="nav-item">
<a class="table-nav-button button-multiple-headers nav-link" href="/test-sites/tables/tables-multiple-header-rows">Tables with multiple header rows</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<div class="tables-all">
<div class="jumbotron tables-initial-text">
<h2>Table playground</h2>
<p class="lead">
								You can train using Table selector here.
							</p>
</div>
<div class="tables-semantically-correct">
<h2>Semantically correct table with thead and tbody</h2>
<p>
			Table selector automatically detects header and data rows.
		</p>
<table class="table table-bordered">
<thead>
<tr>
<th>#</th>
<th>First Name</th>
<th>Last Name</th>
<th>Username</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>Mark</td>
<td>Otto</td>
<td>@mdo</td>
</tr>
<tr>
<td>2</td>
<td>Jacob</td>
<td>Thornton</td>
<td>@fat</td>
</tr>
<tr>
<td>3</td>
<td>Larry</td>
<td>the Bird</td>
<td>@twitter</td>
</tr>
</tbody>
</table>
<table class="table table-bordered table-bordered2">
<thead>
<tr>
<th>#</th>
<th>First Name</th>
<th>Last Name</th>
<th>Username</th>
</tr>
</thead>
<tbody>
<tr>
<td>4</td>
<td>Harry</td>
<td>Potter</td>
<td>@hp</td>
</tr>
<tr>
<td>5</td>
<td>John</td>
<td>Snow</td>
<td>@dunno</td>
</tr>
<tr>
<td>6</td>
<td>Tim</td>
<td>Bean</td>
<td>@timbean</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
<div class="push"></div>
</div>
<div class="container-fluid footer" id="layout-footer">
<div class="container">
<div class="row">
<div class="col-lg-3">
<ul>
<li><p>Products</p></li>
<li>
<a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
							Web Scraper browser extension
						</a>
</li>
<li>
<a href="/cloud-scraper">Web Scraper Cloud</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Company</p></li>
<li>
<a href="/about-us">About us</a>
</li>
<li>
<a href="/contact">Contact</a>
</li>
<li>
<a href="/privacy-policy">Website Privacy Policy</a>
</li>
<li>
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a>
</li>
<li>
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a>
</li>
<li><a href="/jobs">Jobs</a></li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Resources</p></li>
<li><a href="/blog">Blog</a></li>
<li>
<a href="/documentation">Documentation</a>
</li>
<li>
<a href="/tutorials">Video Tutorials</a>
</li>
<li>
<a href="/screenshots">Screenshots</a>
</li>
<li>
<a href="/test-sites">Test Sites</a>
</li>
<li>
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
<li>
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>CONTACT US</p></li>
<li>
<a href="mailto:info@webscraper.io">info@webscraper.io</a>
</li>
<li>Ubelu 5-71,<br/> Adazi, Latvia, LV-2164</li>
</ul>
<ul class="smedia">
<li>
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a>
</li>
<li>
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="browser-icon ws-icon ws-icon-chrome-dark"></i>
</a>
</li>
</ul>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<p class="copyright">Copyright © 2025
					<b>Web Scraper</b> | All rights reserved</p>
</div>
</div>
</div>
</div>
</body>
</html>
>

In [108]:
table_div = soup.find("div" , class_ = "tables-semantically-correct")

In [109]:
t = table_div.find_all("tr")
t

[<tr>
 <th>#</th>
 <th>First Name</th>
 <th>Last Name</th>
 <th>Username</th>
 </tr>,
 <tr>
 <td>1</td>
 <td>Mark</td>
 <td>Otto</td>
 <td>@mdo</td>
 </tr>,
 <tr>
 <td>2</td>
 <td>Jacob</td>
 <td>Thornton</td>
 <td>@fat</td>
 </tr>,
 <tr>
 <td>3</td>
 <td>Larry</td>
 <td>the Bird</td>
 <td>@twitter</td>
 </tr>,
 <tr>
 <th>#</th>
 <th>First Name</th>
 <th>Last Name</th>
 <th>Username</th>
 </tr>,
 <tr>
 <td>4</td>
 <td>Harry</td>
 <td>Potter</td>
 <td>@hp</td>
 </tr>,
 <tr>
 <td>5</td>
 <td>John</td>
 <td>Snow</td>
 <td>@dunno</td>
 </tr>,
 <tr>
 <td>6</td>
 <td>Tim</td>
 <td>Bean</td>
 <td>@timbean</td>
 </tr>]

In [110]:
dl = []
for i in t [1:]:
    dr = {
    "First Name" : "" ,
    "Last Name" : "" ,
    "Username" : ""
}
    cols = i.find_all("td")
    if len(cols) >= 3:
        dr["First Name"] = cols[1].text.strip()
        dr["Last Name"] = cols[2].text.strip()
        dr["Username"] = cols[3].text.strip()
        dl.append(dr)
dl

[{'First Name': 'Mark', 'Last Name': 'Otto', 'Username': '@mdo'},
 {'First Name': 'Jacob', 'Last Name': 'Thornton', 'Username': '@fat'},
 {'First Name': 'Larry', 'Last Name': 'the Bird', 'Username': '@twitter'},
 {'First Name': 'Harry', 'Last Name': 'Potter', 'Username': '@hp'},
 {'First Name': 'John', 'Last Name': 'Snow', 'Username': '@dunno'},
 {'First Name': 'Tim', 'Last Name': 'Bean', 'Username': '@timbean'}]

In [111]:
df = pd.DataFrame(dl)
df.to_csv("webscraper_q4.3.csv" , index =False)

## https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops (product_name, product_link, product_img,product_price, product_details, product_reviews_number,product_reviews_star_number)

### 6.1 Extract first product details save into csv file. e.g# Asus VivoBook...

In [112]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops") 
r.status_code

200

In [113]:
soup = BeautifulSoup(r.text , "html.parser")
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="ugplmmCzts1MpAtgXKWn2hZsbIF5xlzh">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Allinone | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
   <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">
    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <link href="https://fonts.googleapis.com" rel="preconnect"/>
    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
    <link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>
    <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
    <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
    <meta content="website" property="og:type"/>
    <meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>
    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
    </script>
   </meta>
  </meta>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-site">
    <div class="row">
     <div class="col-lg-3 sidebar">
      <div class="navbar-light sidebar" role="navigation">
       <div class="sidebar-nav navbar-collapse">
        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
         <li class="nav-item">
          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">
           <span itemprop="name">
            Home
           </span>
          </a>
         </li>
         <li class="nav-item active">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
           <span itemprop="name">
            Computers
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
             <span itemprop="name">
              Laptops
             </span>
            </a>
           </li>
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
             <span itemprop="name">
              Tablets
             </span>
            </a>
           </li>
          </ul>
         </li>
         <li class="nav-item">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
           <span itemprop="name">
            Phones
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
         </li>
        </ul>
       </div>
      </div>
     </div>
     <div class="col-lg-9">
      <h1 class="page-header">
       Computers / Laptops
      </h1>
      <div class="row">
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $295.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
             Asus VivoBook...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             14
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $299
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
             Prestigio Smar...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             8
            </span>
            reviews
           </p>
           <p data-rating="2">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $299
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
             Prestigio Smar...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             12
            </span>
            reviews
           </p>
           <p data-rating="4">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $306.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
             Aspire E1-510
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             2
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $321.94
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
             Lenovo V110-15...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             5
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $356.49
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
             Lenovo V110-15...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             6
            </span>
            reviews
           </p>
           <p data-rating="2">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $364.46
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
             Hewlett Packar...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">

In [114]:
sec = soup.find("div" , class_ = "product-wrapper card-body")

In [115]:
sec.find("h4").text.strip() # price

'$295.99'

In [116]:
sec.find("a").text.strip() # Product Name

'Asus VivoBook...'

In [117]:
sec.find("a")["href"] # Product Link

'/test-sites/e-commerce/allinone/product/60'

In [118]:
sec.find("img")["src"] # Product image

'/images/test-sites/e-commerce/items/cart2.png'

In [119]:
sec.find("p").text # Product Description

'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd'

In [120]:
sec.find("p" , class_ = "review-count float-end").text.strip() # reviews

'14 reviews'

In [121]:
dl = []
data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
data["Product Name"] = sec.find("a").text.strip() # Product Name
data["Product Link"] = sec.find("a")["href"] # Product Link
data["Product Image"] = sec.find("img")["src"] # Product image
data["Product Price"] = sec.find("h4").text.strip() # price
data["Product Details"] = sec.find("p").text # Product Description
data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
dl.append(data)
dl

[{'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/60',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$295.99',
  'Product Details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'Product Reviews Number': '14 reviews'}]

In [122]:
df = pd.DataFrame(dl)
df.to_csv("webscraper_q6.1.csv" , index = False)

In [123]:
df

,Product Name,Product Link,Product Image,Product Price,Product Details,Product Reviews Number
0,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14 reviews

### 6.2 Extract product details from first row & save into csv file. e.g# Asus VivoBook..., Prestigio Smar...,Prestigio Smar...

In [124]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops") 
r.status_code

200

In [125]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="ugplmmCzts1MpAtgXKWn2hZsbIF5xlzh">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Allinone | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>\n    <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $295.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">\n             Asus VivoBook...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             14\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             8\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="4">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $306.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">\n             Aspire E1-510\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $321.94\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             5\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $356.49\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             6\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $364.46\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/65" 

In [126]:
row = soup.find_all("div" , class_ = "product-wrapper card-body")[0:3]

In [127]:
dl=[]
for sec in row:
    data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
    data["Product Name"] = sec.find("a").text.strip() # Product Name
    data["Product Link"] = sec.find("a")["href"] # Product Link
    data["Product Image"] = sec.find("img")["src"] # Product image
    data["Product Price"] = sec.find("h4").text.strip() # price
    data["Product Details"] = sec.find("p").text # Product Description
    data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
    dl.append(data)
dl

[{'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/60',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$295.99',
  'Product Details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Prestigio Smar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/61',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$299',
  'Product Details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Prestigio Smar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/62',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$299',
  'Product Details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Reviews Number': '12 reviews'}]

In [128]:
df = pd.DataFrame(dl)
df.to_csv("webscraper_q6.2.csv", index = False)

In [21]:
df

,Product Name,Product Link,Product Image,Product Price,Product Details,Product Reviews Number
0,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14 reviews
1,Prestigio Smar...,/test-sites/e-commerce/allinone/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",8 reviews
2,Prestigio Smar...,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews

### 6.3 Extract all product details from page & save into csv file.

In [22]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops") 
r.status_code

200

In [23]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="ugplmmCzts1MpAtgXKWn2hZsbIF5xlzh">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Allinone | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>\n    <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $295.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">\n             Asus VivoBook...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             14\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             8\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="4">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $306.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">\n             Aspire E1-510\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $321.94\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             5\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $356.49\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             6\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $364.46\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/65" 

In [24]:
row = soup.find_all("div" , class_ = "product-wrapper card-body")

In [25]:
dl=[]
for sec in row:
    data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
    data["Product Name"] = sec.find("a").text.strip() # Product Name
    data["Product Link"] = sec.find("a")["href"] # Product Link
    data["Product Image"] = sec.find("img")["src"] # Product image
    data["Product Price"] = sec.find("h4").text.strip() # price
    data["Product Details"] = sec.find("p").text # Product Description
    data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
    dl.append(data)
dl

[{'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/60',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$295.99',
  'Product Details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Prestigio Smar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/61',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$299',
  'Product Details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Prestigio Smar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/62',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$299',
  'Product Details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Aspire E1-510',
  'Product Link': '/test-sites/e-commerce/allinone/product/32',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$306.99',
  'Product Details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/63',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$321.94',
  'Product Details': 'Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '5 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/64',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$356.49',
  'Product Details': 'Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd',
  'Product Reviews Number': '6 reviews'},
 {'Product Name': 'Hewlett Packar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/65',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$364.46',
  'Product Details': 'Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/66',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$372.7',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Acer Aspire A3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/67',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$379.94',
  'Product Details': 'Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/68',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$379.95',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/69',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$391.48',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/70',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$393.88',
  'Product Details': 'Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/45',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$399',
  'Product Details': 'Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/71',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$399.99',
  'Product Details': 'Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'Product Reviews Number': '3 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Link': '/test-sites/e-commerce/allinone/product/72',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$404.23',
  'Product Details': 'Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/73',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$408.98',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/74',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$409.63',
  'Product Details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/75',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$410.46',
  'Product Details': 'Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/76',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$410.66',
  'Product Details': 'Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Packard 255 G2',
  'Product Link': '/test-sites/e-commerce/allinone/product/31',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$416.99',
  'Product Details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Asus EeeBook R...',
  'Product Link': '/test-sites/e-commerce/allinone/product/77',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$433.3',
  'Product Details': 'Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/78',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$436.29',
  'Product Details': 'Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/79',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$436.29',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Acer Extensa 1...',
  'Product Link': '/test-sites/e-commerce/allinone/product/80',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$439.73',
  'Product Details': 'Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'Product Reviews Number': '6 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/81',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$454.62',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/82',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$454.73',
  'Product Details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Acer Aspire A3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/83',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$457.38',
  'Product Details': 'Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/84',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$465.95',
  'Product Details': 'Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/85',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$468.56',
  'Product Details': 'Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/86',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$469.1',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '5 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Link': '/test-sites/e-commerce/allinone/product/87',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$484.23',
  'Product Details': 'Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/88',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$485.9',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux',
  'Product Reviews Number': '6 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Link': '/test-sites/e-commerce/allinone/product/89',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$487.8',
  'Product Details': 'Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Acer Swift 1 S...',
  'Product Link': '/test-sites/e-commerce/allinone/product/90',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$488.64',
  'Product Details': 'Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Dell Vostro 15',
  'Product Link': '/test-sites/e-commerce/allinone/product/46',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$488.78',
  'Product Details': 'Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/91',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$494.71',
  'Product Details': 'Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Dell Vostro 15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/92',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$497.17',
  'Product Details': 'Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Link': '/test-sites/e-commerce/allinone/product/93',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$498.23',
  'Product Details': 'Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro',
  'Product Reviews Number': '5 reviews'},
 {'Product Name': 'HP 250 G3',
  'Product Link': '/test-sites/e-commerce/allinone/product/42',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$520.99',
  'Product Details': '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'Acer Spin 5',
  'Product Link': '/test-sites/e-commerce/allinone/product/47',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$564.98',
  'Product Details': 'Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'HP 350 G1',
  'Product Link': '/test-sites/e-commerce/allinone/product/44',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$577.99',
  'Product Details': '15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Aspire E1-572G',
  'Product Link': '/test-sites/e-commerce/allinone/product/36',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$581.99',
  'Product Details': '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Pavilion',
  'Product Link': '/test-sites/e-commerce/allinone/product/38',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$609.99',
  'Product Details': '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Acer Aspire A5...',
  'Product Link': '/test-sites/e-commerce/allinone/product/48',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$679',
  'Product Details': 'Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Link': '/test-sites/e-commerce/allinone/product/49',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$679',
  'Product Details': 'Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/50',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$729',
  'Product Details': 'Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'ProBook',
  'Product Link': '/test-sites/e-commerce/allinone/product/34',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$739.99',
  'Product Details': '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Inspiron 15',
  'Product Link': '/test-sites/e-commerce/allinone/product/39',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$745.99',
  'Product Details': 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Link': '/test-sites/e-commerce/allinone/product/51',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$799',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Acer Nitro 5 A...',
  'Product Link': '/test-sites/e-commerce/allinone/product/52',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$809',
  'Product Details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Link': '/test-sites/e-commerce/allinone/product/53',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$899',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS + Windows 10 Home',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Link': '/test-sites/e-commerce/allinone/product/54',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$999',
  'Product Details': 'Lenovo ThinkPad L570, 15.6" FHD, Core i7-7500U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '11 reviews'},
 {'Product Name': 'ThinkPad Yoga',
  'Product Link': '/test-sites/e-commerce/allinone/product/37',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1033.99',
  'Product Details': '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Link': '/test-sites/e-commerce/allinone/product/94',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1096.02',
  'Product Details': 'Lenovo ThinkPad L460, 14" FHD IPS, Core i7-6600U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Link': '/test-sites/e-commerce/allinone/product/95',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1098.42',
  'Product Details': 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 4GB, Windows 10 Home',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'MSI GL72M 7RDX',
  'Product Link': '/test-sites/e-commerce/allinone/product/96',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1099',
  'Product Details': 'MSI GL72M 7RDX, 17.3" FHD, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'MSI GL72M 7RDX',
  'Product Link': '/test-sites/e-commerce/allinone/product/97',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1099',
  'Product Details': 'Asus ROG Strix GL553VD-DM535T, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home, Eng kbd',

In [26]:
df = pd.DataFrame(dl)
df.to_csv("webscraper_q6.3.csv",index = False)

In [27]:
df

,Product Name,Product Link,Product Image,Product Price,Product Details,Product Reviews Number
0,Asus VivoBook...,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14 reviews
1,Prestigio Smar...,/test-sites/e-commerce/allinone/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",8 reviews
2,Prestigio Smar...,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews
3,Aspire E1-510,/test-sites/e-commerce/allinone/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews
4,Lenovo V110-15...,/test-sites/e-commerce/allinone/product/63,/images/test-sites/e-commerce/items/cart2.png,$321.94,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",5 reviews
...,...,...,...,...,...,...
112,Lenovo Legion...,/test-sites/e-commerce/allinone/product/56,/images/test-sites/e-commerce/items/cart2.png,$1399,"Lenovo Legion Y720, 15.6"" FHD IPS, Core i7-770...",8 reviews
113,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/147,/images/test-sites/e-commerce/items/cart2.png,$1399,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",10 reviews
114,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/57,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC154T, 17.3"" FHD, Ryze...",7 reviews
115,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/58,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC209T, 17.3"" FHD IPS, ...",8 reviews
116,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews

### 6.4 Extract all product details of first column save into csv file.

In [28]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops") 
r.status_code

200

In [29]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="ugplmmCzts1MpAtgXKWn2hZsbIF5xlzh">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Allinone | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>\n    <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $295.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">\n             Asus VivoBook...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             14\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             8\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="4">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $306.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">\n             Aspire E1-510\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $321.94\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             5\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $356.49\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             6\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $364.46\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/65" 

In [30]:
row = soup.find_all("div" , class_ = "product-wrapper card-body")[0::3]

In [31]:
dl=[]
for sec in row:
    data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
    data["Product Name"] = sec.find("a").text.strip() # Product Name
    data["Product Link"] = sec.find("a")["href"] # Product Link
    data["Product Image"] = sec.find("img")["src"] # Product image
    data["Product Price"] = sec.find("h4").text.strip() # price
    data["Product Details"] = sec.find("p").text # Product Description
    data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
    dl.append(data)
dl

[{'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/60',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$295.99',
  'Product Details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Aspire E1-510',
  'Product Link': '/test-sites/e-commerce/allinone/product/32',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$306.99',
  'Product Details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Hewlett Packar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/65',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$364.46',
  'Product Details': 'Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/68',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$379.95',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/45',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$399',
  'Product Details': 'Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/73',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$408.98',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/76',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$410.66',
  'Product Details': 'Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/78',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$436.29',
  'Product Details': 'Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/81',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$454.62',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/84',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$465.95',
  'Product Details': 'Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Link': '/test-sites/e-commerce/allinone/product/87',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$484.23',
  'Product Details': 'Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Acer Swift 1 S...',
  'Product Link': '/test-sites/e-commerce/allinone/product/90',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$488.64',
  'Product Details': 'Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Dell Vostro 15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/92',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$497.17',
  'Product Details': 'Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Acer Spin 5',
  'Product Link': '/test-sites/e-commerce/allinone/product/47',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$564.98',
  'Product Details': 'Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Pavilion',
  'Product Link': '/test-sites/e-commerce/allinone/product/38',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$609.99',
  'Product Details': '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/50',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$729',
  'Product Details': 'Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Link': '/test-sites/e-commerce/allinone/product/51',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$799',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Link': '/test-sites/e-commerce/allinone/product/54',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$999',
  'Product Details': 'Lenovo ThinkPad L570, 15.6" FHD, Core i7-7500U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '11 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Link': '/test-sites/e-commerce/allinone/product/95',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1098.42',
  'Product Details': 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 4GB, Windows 10 Home',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Link': '/test-sites/e-commerce/allinone/product/98',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1101.83',
  'Product Details': 'Apple MacBook Air 13.3", Core i5 1.8GHz, 8GB, 128GB SSD, Intel HD 4000, RUS',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Link': '/test-sites/e-commerce/allinone/product/101',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1112.91',
  'Product Details': 'Lenovo Legion Y520-15IKBM, Black, 15.6" FHD IPS, Core i5-7300HQ, 8 GB, 128GB SSD + 2 TB HDD, NVIDIA GeForce GTX 1060 6 GB, FreeDOS + Windows 10 Home',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Acer Aspire 7...',
  'Product Link': '/test-sites/e-commerce/allinone/product/104',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1123.87',
  'Product Details': 'Acer Aspire 7 A715-71G, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB HDD, GTX 1050 Ti 4GB, Windows 10 Home',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Link': '/test-sites/e-commerce/allinone/product/107',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1133.91',
  'Product Details': 'Lenovo Legion Y520, 15.6" FHD, Core i7-7700HQ, 8GB, 128 GB SSD + 1TB HDD, GTX 1050 4GB, Windows 10 Home',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/110',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1143.4',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7440HQ, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '5 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Link': '/test-sites/e-commerce/allinone/product/55',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1149',
  'Product Details': 'Lenovo Legion Y520-15IKBM, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB, GeForce GTX 1060 Max-Q 6GB, DOS',
  'Product Reviews Number': '11 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Link': '/test-sites/e-commerce/allinone/product/115',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1154.04',
  'Product Details': 'Toshiba Portege Z30-C-16L Grey, 13.3" FHD, Core i7-6500U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'ThinkPad T540p',
  'Product Link': '/test-sites/e-commerce/allinone/product/33',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1178.99',
  'Product Details': '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Acer Predator...',
  'Product Link': '/test-sites/e-commerce/allinone/product/120',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1187.98',
  'Product Details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ. 8GB, 128GB SSD +1TB, GeForce GTX 1050Ti 4GB, Linux + Windows 10 Home',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Lenovo Yoga 91...',
  'Product Link': '/test-sites/e-commerce/allinone/product/123',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1199.73',
  'Product Details': 'Lenovo Yoga 910 Grey, 13.9" FHD Touch, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Acer Predator...',
  'Product Link': '/test-sites/e-commerce/allinone/product/126',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1221.58',
  'Product Details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/128',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1238.37',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Link': '/test-sites/e-commerce/allinone/product/130',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1259',
  'Product Details': 'Asus ROG Strix GL753VE-GC096T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Hewlett Packar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/133',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1273.11',
  'Product Details': 'Hewlett Packard Spectre 13-v106na Dark Ash Silver, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'MSI GL62VR 7RF...',
  'Product Link': '/test-sites/e-commerce/allinone/product/135',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1299',
  'Product Details': 'MSI GL62VR 7RFX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 256GB SSD, GeForce GTX 1060 3GB, Windows 10 Home',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Hewlett Packar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/137',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1326.83',
  'Product Details': 'Hewlett Packard ProBook 640 G3, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/140',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1338.37',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux + Windows 10 Home',
  'Product Reviews Number': '11 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Link': '/test-sites/e-commerce/allinone/product/143',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1349.23',
  'Product Details': 'Lenovo ThinkPad T470, 14" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '5 reviews'},
 {'Product Name': 'Asus ASUSPRO B...',
  'Product Link': '/test-sites/e-commerce/allinone/product/146',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1381.13',
  'Product Details': 'Asus ASUSPRO B9440UA-GV0279R Gray, 14" FHD, Core i7-7500U, 16GB, 512GB SSD, Windows 10 Pro, Eng kbd',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Link': '/test-sites/e-commerce/allinone/product/57',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1769',
  'Product Details': 'Asus ROG Strix GL702ZC-GC154T, 17.3" FHD, Ryzen 7 1700, 16GB, 256GB + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
  'Product Reviews Number': '7 reviews'}]

In [32]:
df = pd.DataFrame(dl)
df.to_csv("webscraper_q6.4.csv",index= False)

##  6.5 Extract all product details of Second column save into csv file.

In [33]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops") 
r.status_code

200

In [34]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="ugplmmCzts1MpAtgXKWn2hZsbIF5xlzh">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Allinone | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>\n    <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $295.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">\n             Asus VivoBook...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             14\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             8\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="4">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $306.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">\n             Aspire E1-510\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $321.94\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             5\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $356.49\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             6\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $364.46\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/65" 

In [35]:
row = soup.find_all("div" , class_ = "product-wrapper card-body")[1::3]

In [36]:
dl=[]
for sec in row:
    data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
    data["Product Name"] = sec.find("a").text.strip() # Product Name
    data["Product Link"] = sec.find("a")["href"] # Product Link
    data["Product Image"] = sec.find("img")["src"] # Product image
    data["Product Price"] = sec.find("h4").text.strip() # price
    data["Product Details"] = sec.find("p").text # Product Description
    data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
    dl.append(data)
dl

[{'Product Name': 'Prestigio Smar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/61',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$299',
  'Product Details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/63',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$321.94',
  'Product Details': 'Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '5 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/66',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$372.7',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/69',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$391.48',
  'Product Details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/71',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$399.99',
  'Product Details': 'Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'Product Reviews Number': '3 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/74',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$409.63',
  'Product Details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Packard 255 G2',
  'Product Link': '/test-sites/e-commerce/allinone/product/31',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$416.99',
  'Product Details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/79',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$436.29',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/82',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$454.73',
  'Product Details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/85',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$468.56',
  'Product Details': 'Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/88',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$485.9',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux',
  'Product Reviews Number': '6 reviews'},
 {'Product Name': 'Dell Vostro 15',
  'Product Link': '/test-sites/e-commerce/allinone/product/46',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$488.78',
  'Product Details': 'Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Link': '/test-sites/e-commerce/allinone/product/93',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$498.23',
  'Product Details': 'Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro',
  'Product Reviews Number': '5 reviews'},
 {'Product Name': 'HP 350 G1',
  'Product Link': '/test-sites/e-commerce/allinone/product/44',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$577.99',
  'Product Details': '15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Acer Aspire A5...',
  'Product Link': '/test-sites/e-commerce/allinone/product/48',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$679',
  'Product Details': 'Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'ProBook',
  'Product Link': '/test-sites/e-commerce/allinone/product/34',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$739.99',
  'Product Details': '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Acer Nitro 5 A...',
  'Product Link': '/test-sites/e-commerce/allinone/product/52',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$809',
  'Product Details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'ThinkPad Yoga',
  'Product Link': '/test-sites/e-commerce/allinone/product/37',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1033.99',
  'Product Details': '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'MSI GL72M 7RDX',
  'Product Link': '/test-sites/e-commerce/allinone/product/96',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1099',
  'Product Details': 'MSI GL72M 7RDX, 17.3" FHD, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/99',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1102.66',
  'Product Details': 'Dell Latitude 5280, 12.5" HD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Link': '/test-sites/e-commerce/allinone/product/102',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1114.55',
  'Product Details': 'Toshiba Portege Z30-C-16J Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Link': '/test-sites/e-commerce/allinone/product/105',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1124.2',
  'Product Details': 'Dell Inspiron 17 2in1 (7779) Silver, 17.3" FHD Touch, Core i5-7200U, 12GB, 1TB, GeForce GT940MX 2GB, Windows 10 Home',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Asus AsusPro A...',
  'Product Link': '/test-sites/e-commerce/allinone/product/108',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1139.54',
  'Product Details': 'Asus AsusPro Advanced BU401LA-FA271G Dark Grey, 14", Core i5-4210U, 4GB, 128GB SSD, Win7 Pro 64bit, ENG',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Link': '/test-sites/e-commerce/allinone/product/111',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1144.2',
  'Product Details': 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB, GeForce GTX 1050 Ti 4GB, Linux + Windows 10 Home',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'MSI GP62M 7RDX...',
  'Product Link': '/test-sites/e-commerce/allinone/product/113',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1149',
  'Product Details': 'MSI GP62M 7RDX Leopard, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Reviews Number': '11 reviews'},
 {'Product Name': 'Acer TravelMat...',
  'Product Link': '/test-sites/e-commerce/allinone/product/116',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1170.1',
  'Product Details': 'Acer TravelMate P645-S-511A Black, 14" FHD IPS, Core i5-5200U, 8GB, 256GB SSD, 3G, Windows 10 Pro',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'MSI GS63 7RD S...',
  'Product Link': '/test-sites/e-commerce/allinone/product/118',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1179',
  'Product Details': 'MSI GS63 7RD Stealth, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, DOS + Windows 10 Home',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'MSI GL62M 7REX',
  'Product Link': '/test-sites/e-commerce/allinone/product/121',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1199',
  'Product Details': 'MSI GL62M 7REX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Link': '/test-sites/e-commerce/allinone/product/124',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1203.41',
  'Product Details': 'Toshiba Portege X30-D-10J Black/Blue, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'ThinkPad Yoga',
  'Product Link': '/test-sites/e-commerce/allinone/product/43',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1223.99',
  'Product Details': '12.5" Touch, Core i5 4200U, 8GB, 500GB + 16GB SSD Cache, Windows',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Asus ZenBook U...',
  'Product Link': '/test-sites/e-commerce/allinone/product/129',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1239.2',
  'Product Details': 'Asus ZenBook UX530UX-FY040T Blue, 15.6" FHD, Core i7-7500U, 8GB, 512GB SSD, GeForce GTX950M 2GB, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Apple MacBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/131',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1260.13',
  'Product Details': 'Apple MacBook Air 13", i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, ENG',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Dell XPS 13',
  'Product Link': '/test-sites/e-commerce/allinone/product/40',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1281.99',
  'Product Details': '13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/136',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1310.39',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Apple MacBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/138',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1333',
  'Product Details': 'Apple MacBook Pro 13" Space Gray, Core i5 2.3GHz, 8GB, 128GB SSD, Iris Plus 640, ENG',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/141',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1341.22',
  'Product Details': 'Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 16GB, 256GB SSD, GeForce GT930MX, Linux',
  'Product Reviews Number': '3 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Link': '/test-sites/e-commerce/allinone/product/144',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1362.24',
  'Product Details': 'Lenovo ThinkPad Yoga 370 Black, 13.3" FHD IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Link': '/test-sites/e-commerce/allinone/product/56',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1399',
  'Product Details': 'Lenovo Legion Y720, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 2TB HDD, GeForce GTX 1060 6GB, DOS, RGB backlit keyboard',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Link': '/test-sites/e-commerce/allinone/product/58',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1769',
  'Product Details': 'Asus ROG Strix GL702ZC-GC209T, 17.3" FHD IPS, Ryzen 7 1700, 16GB, 256GB SSD + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
  'Product Reviews Number': '8 reviews'}]

In [37]:
df = pd.DataFrame(dl)
df.to_csv("webscraper_q6.5.csv",index = False)

### 6.6 Extract all product details of thirst column save into csv file.

In [38]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops") 
r.status_code

200

In [39]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="ugplmmCzts1MpAtgXKWn2hZsbIF5xlzh">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Allinone | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>\n    <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $295.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">\n             Asus VivoBook...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             14\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             8\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $299\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">\n             Prestigio Smar...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="4">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $306.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">\n             Aspire E1-510\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $321.94\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             5\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $356.49\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">\n             Lenovo V110-15...\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             6\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $364.46\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/allinone/product/65" 

In [40]:
row = soup.find_all("div" , class_ = "product-wrapper card-body")[2::3]

In [41]:
dl=[]
for sec in row:
    data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
    data["Product Name"] = sec.find("a").text.strip() # Product Name
    data["Product Link"] = sec.find("a")["href"] # Product Link
    data["Product Image"] = sec.find("img")["src"] # Product image
    data["Product Price"] = sec.find("h4").text.strip() # price
    data["Product Details"] = sec.find("p").text # Product Description
    data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
    dl.append(data)
dl

[{'Product Name': 'Prestigio Smar...',
  'Product Link': '/test-sites/e-commerce/allinone/product/62',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$299',
  'Product Details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Lenovo V110-15...',
  'Product Link': '/test-sites/e-commerce/allinone/product/64',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$356.49',
  'Product Details': 'Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd',
  'Product Reviews Number': '6 reviews'},
 {'Product Name': 'Acer Aspire A3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/67',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$379.94',
  'Product Details': 'Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/70',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$393.88',
  'Product Details': 'Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Link': '/test-sites/e-commerce/allinone/product/72',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$404.23',
  'Product Details': 'Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/75',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$410.46',
  'Product Details': 'Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Asus EeeBook R...',
  'Product Link': '/test-sites/e-commerce/allinone/product/77',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$433.3',
  'Product Details': 'Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Acer Extensa 1...',
  'Product Link': '/test-sites/e-commerce/allinone/product/80',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$439.73',
  'Product Details': 'Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'Product Reviews Number': '6 reviews'},
 {'Product Name': 'Acer Aspire A3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/83',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$457.38',
  'Product Details': 'Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Acer Aspire ES...',
  'Product Link': '/test-sites/e-commerce/allinone/product/86',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$469.1',
  'Product Details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '5 reviews'},
 {'Product Name': 'Lenovo V510 Bl...',
  'Product Link': '/test-sites/e-commerce/allinone/product/89',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$487.8',
  'Product Details': 'Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Acer Aspire 3...',
  'Product Link': '/test-sites/e-commerce/allinone/product/91',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$494.71',
  'Product Details': 'Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'HP 250 G3',
  'Product Link': '/test-sites/e-commerce/allinone/product/42',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$520.99',
  'Product Details': '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'Aspire E1-572G',
  'Product Link': '/test-sites/e-commerce/allinone/product/36',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$581.99',
  'Product Details': '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Link': '/test-sites/e-commerce/allinone/product/49',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$679',
  'Product Details': 'Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Inspiron 15',
  'Product Link': '/test-sites/e-commerce/allinone/product/39',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$745.99',
  'Product Details': 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Link': '/test-sites/e-commerce/allinone/product/53',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$899',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS + Windows 10 Home',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Link': '/test-sites/e-commerce/allinone/product/94',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1096.02',
  'Product Details': 'Lenovo ThinkPad L460, 14" FHD IPS, Core i7-6600U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'MSI GL72M 7RDX',
  'Product Link': '/test-sites/e-commerce/allinone/product/97',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1099',
  'Product Details': 'Asus ROG Strix GL553VD-DM535T, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/100',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1110.14',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Linux + Windows 10 Home',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Acer Predator...',
  'Product Link': '/test-sites/e-commerce/allinone/product/103',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1123.87',
  'Product Details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050Ti 4GB, Windows 10 Home',
  'Product Reviews Number': '1 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/106',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1133.82',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Windows 10 Pro',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Acer Nitro 5 A...',
  'Product Link': '/test-sites/e-commerce/allinone/product/109',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1140.62',
  'Product Details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD +1TB, GeForce GTX 1050 Ti 4GB, Windows 10 Home + Windows 10 Home',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/112',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1144.4',
  'Product Details': 'Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Lenovo Yoga 72...',
  'Product Link': '/test-sites/e-commerce/allinone/product/114',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1149.73',
  'Product Details': 'Lenovo Yoga 720 Grey, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/117',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1178.19',
  'Product Details': 'Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 16GB, 256GB SSD, Linux + Windows 10 Home',
  'Product Reviews Number': '6 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/119',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1187.88',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '5 reviews'},
 {'Product Name': 'MSI GL62M 7REX...',
  'Product Link': '/test-sites/e-commerce/allinone/product/122',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1199',
  'Product Details': 'MSI GL62M 7REX2, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Lenovo IdeaPad...',
  'Product Link': '/test-sites/e-commerce/allinone/product/125',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1212.16',
  'Product Details': 'Lenovo IdeaPad Miix 510 Platinum Silver, 12.2" IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/127',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1235.49',
  'Product Details': 'Asus VivoBook Pro 15 N580VN-FI006T Gold Metal, 15.6" UHD, Core i7-7700HQ, 16GB, 1TB + 256GB SSD, GeForce MX150 2GB, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'ThinkPad X230',
  'Product Link': '/test-sites/e-commerce/allinone/product/41',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1244.99',
  'Product Details': '12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/132',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1271.06',
  'Product Details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 1TB, GeForce GT930MX, Windows 10 Pro',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Link': '/test-sites/e-commerce/allinone/product/134',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1294.74',
  'Product Details': 'Toshiba Portege Z30-C-16K Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
  'Product Reviews Number': '6 reviews'},
 {'Product Name': 'ThinkPad X240',
  'Product Link': '/test-sites/e-commerce/allinone/product/35',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1311.99',
  'Product Details': '12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Dell Latitude...',
  'Product Link': '/test-sites/e-commerce/allinone/product/139',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1337.28',
  'Product Details': 'Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 8GB, 256GB SSD, GeForce GT930MX, Windows 10 Pro',
  'Product Reviews Number': '6 reviews'},
 {'Product Name': 'Apple MacBook...',
  'Product Link': '/test-sites/e-commerce/allinone/product/142',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1347.78',
  'Product Details': 'Apple MacBook Air 13", Intel Core i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, RUS',
  'Product Reviews Number': '11 reviews'},
 {'Product Name': 'Toshiba Porteg...',
  'Product Link': '/test-sites/e-commerce/allinone/product/145',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1366.32',
  'Product Details': 'Toshiba Portege X20W-D-10V Black/Blue, 12.5" FHD Touch, Core i7-7500U, 8GB, 512GB SSD, Windows 10 Pro',
  'Product Reviews Number': '11 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Link': '/test-sites/e-commerce/allinone/product/147',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1399',
  'Product Details': 'Asus ROG Strix GL702VM-GC146T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1060 3GB, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Link': '/test-sites/e-commerce/allinone/product/59',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1799',
  'Product Details': 'Asus ROG Strix SCAR Edition GL503VM-ED115T, 15.6" FHD 120Hz, Core i7-7700HQ, 16GB, 256GB SSD + 1TB SSHD, GeForce GTX 1060 6GB, Windows 10 Home',
  'Product Reviews Number': '8 reviews'}]

In [42]:
df = pd.DataFrame(dl)
df.to_csv("webscraper_q6.6.csv",index = False)

In [43]:
df

,Product Name,Product Link,Product Image,Product Price,Product Details,Product Reviews Number
0,Prestigio Smar...,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews
1,Lenovo V110-15...,/test-sites/e-commerce/allinone/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,6 reviews
2,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",0 reviews
3,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",9 reviews
4,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/72,/images/test-sites/e-commerce/items/cart2.png,$404.23,"Lenovo ThinkPad E31-80, 13.3"" HD, Celeron 3855...",12 reviews
5,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/75,/images/test-sites/e-commerce/items/cart2.png,$410.46,"Acer Aspire ES1-732 Black, 17.3"" HD+, Celeron,...",14 reviews
6,Asus EeeBook R...,/test-sites/e-commerce/allinone/product/77,/images/test-sites/e-commerce/items/cart2.png,$433.3,"Asus EeeBook R416NA-FA014T, 14"" FHD, Pentium N...",1 reviews
7,Acer Extensa 1...,/test-sites/e-commerce/allinone/product/80,/images/test-sites/e-commerce/items/cart2.png,$439.73,"Acer Extensa 15 (2540) Black, 15.6"" HD, Core i...",6 reviews
8,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/83,/images/test-sites/e-commerce/items/cart2.png,$457.38,"Acer Aspire A315-51-33TG, Black 15.6"" HD, Core...",9 reviews
9,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/86,/images/test-sites/e-commerce/items/cart2.png,$469.1,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",5 reviews
10,Lenovo V510 Bl...,/test-sites/e-commerce/allinone/product/89,/images/test-sites/e-commerce/items/cart2.png,$487.8,"Lenovo V510 Black, 15.6"" HD, Core i3-6006U, 4G...",9 reviews
11,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/91,/images/test-sites/e-commerce/items/cart2.png,$494.71,"Acer Aspire 3 A315-51 Black, 15.6"" FHD, Core i...",2 reviews
12,HP 250 G3,/test-sites/e-commerce/allinone/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews
13,Aspire E1-572G,/test-sites/e-commerce/allinone/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews
14,Dell Inspiron...,/test-sites/e-commerce/allinone/product/49,/images/test-sites/e-commerce/items/cart2.png,$679,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",7 reviews
15,Inspiron 15,/test-sites/e-commerce/allinone/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews
16,Asus ROG STRIX...,/test-sites/e-commerce/allinone/product/53,/images/test-sites/e-commerce/items/cart2.png,$899,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews
17,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/94,/images/test-sites/e-commerce/items/cart2.png,$1096.02,"Lenovo ThinkPad L460, 14"" FHD IPS, Core i7-660...",14 reviews
18,MSI GL72M 7RDX,/test-sites/e-commerce/allinone/product/97,/images/test-sites/e-commerce/items/cart2.png,$1099,"Asus ROG Strix GL553VD-DM535T, 15.6"" FHD, Core...",9 reviews
19,Dell Latitude...,/test-sites/e-commerce/allinone/product/100,/images/test-sites/e-commerce/items/cart2.png,$1110.14,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",4 reviews
20,Acer Predator...,/test-sites/e-commerce/allinone/product/103,/images/test-sites/e-commerce/items/cart2.png,$1123.87,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",1 reviews
21,Dell Latitude...,/test-sites/e-commerce/allinone/product/106,/images/test-sites/e-commerce/items/cart2.png,$1133.82,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",14 reviews
22,Acer Nitro 5 A...,/test-sites/e-commerce/allinone/product/109,/images/test-sites/e-commerce/items/cart2.png,$1140.62,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i7-...",14 reviews
23,Dell Latitude...,/test-sites/e-commerce/allinone/product/112,/images/test-sites/e-commerce/items/cart2.png,$1144.4,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",10 reviews
24,Lenovo Yoga 72...,/test-sites/e-commerce/allinone/product/114,/images/test-sites/e-commerce/items/cart2.png,$1149.73,"Lenovo Yoga 720 Grey, 15.6"" FHD IPS, Core i5-7...",12 reviews
25,Dell Latitude...,/test-sites/e-commerce/allinone/product/117,/images/test-sites/e-commerce/items/cart2.png,$1178.19,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",6 reviews
26,Dell Latitude...,/test-sites/e-commerce/allinone/product/119,/images/test-sites/e-commerce/items/cart2.png,$1187.88,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",5 reviews
27,MSI GL62M 7REX...,/test-sites/e-commerce/allinone/product/122,/images/test-sites/e-commerce/items/cart2.png,$1199,"MSI GL62M 7REX2, 15.6"" FHD, Core i7-7700HQ, 8G...",12 reviews
28,Lenovo IdeaPad...,/test-sites/e-commerce/allinone/product/125,/images/test-sites/e-commerce/items/cart2.png,$1212.16,"Lenovo IdeaPad Miix 510 Platinum Silver, 12.2""...",0 reviews
29,Asus VivoBook...,/test-sites/e-commerce/allinone/product/127,/images/test-sites/e-commerce/items/cart2.png,$1235.49,"Asus VivoBook Pro 15 N580VN-FI006T Gold Metal,...",10 reviews
30,ThinkPad X230,/test-sites/e-commerce/allinone/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews
31,Dell Latitude...,/test-sites/e-commerce/allinone/product/132,/images/test-sites/e-commerce/items/cart2.png,$1271.06,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",13 reviews
32,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/134,/images/test-sites/e-commerce/items/cart2.png,$1294.74,"Toshiba Portege Z30-C-16K Grey, 13.3"" FHD, Cor...",6 reviews
33,ThinkPad X240,/test-sites/e-commerce/allinone/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews
34,Dell Latitude...,/test-sites/e-commerce/allinone/product/139,/images/test-sites/e-commerce/items/cart2.png,$1337.28,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",6 reviews
35,Apple MacBook...,/test-sites/e-commerce/allinone/product/142,/images/test-sites/e-commerce/items/cart2.png,$1347.78,"Apple MacBook Air 13"", Intel Core i5 1.8GHz, 8...",11 reviews
36,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/145,/images/test-sites/e-commerce/items/cart2.png,$1366.32,"Toshiba Portege X20W-D-10V Black/Blue, 12.5"" F...",11 reviews
37,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/147,/images/test-sites/e-commerce/items/cart2.png,$1399,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",10 reviews
38,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews

### 7. https://webscraper.io/test-sites/e-commerce/static/computers/laptops (product_name, product_link, product_img, product_price, product_details, product_reviews_number, product_reviews_star_number )

###  7.1 Extract first product details save into csv file. e.g# Packard 255 G2

In [44]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/static/computers/laptops") 
r.status_code

200

In [45]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="gF9s6JOtatzK727F1j6eSurGHKZ46Kh0">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Static | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" rel="canonical"/>\n    <meta content="Static | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $416.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">\n             Packard 255 G2\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $306.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">\n             Aspire E1-510\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $1178.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">\n             ThinkPad T540p\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="1">\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $739.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">\n             ProBook\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             8\n            </span>\n            reviews\n           </p>\n           <p data-rating="4">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $1311.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">\n             ThinkPad X240\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $581.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">\n             Aspire E1-572G\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="1">\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n      </div>\n      <div id="static-pagination">\n       <nav>\n        <ul class="pagination">\n         <li aria-disabled="true" aria-label="« Previous" class="page-item disabled">\n          <span aria-hidden="true" class="page-link">\n           ‹\n          </span>\n         </li>\n         <li aria-current="page" class="page-item active">\n          <span class="page-link">\n           1\n          </span>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=2">\n           2\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">\n           3\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">\n           4\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">\n           5\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">\n           6\n          </a>\n         </li>\n         <li class="page-item">\n 

In [46]:
sec = soup.find("div" , class_ = "product-wrapper card-body")
sec

<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$416.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
						Packard 255 G2
					</a>
</h4>
<p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">2</span> reviews
				</p>
<p data-rating="2">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>

In [47]:
sec.find("a").text.strip()

'Packard 255 G2'

In [48]:
dl=[]

data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
data["Product Name"] = sec.find("a").text.strip() # Product Name
data["Product Link"] = sec.find("a")["href"] # Product Link
data["Product Image"] = sec.find("img")["src"] # Product image
data["Product Price"] = sec.find("h4").text.strip() # price
data["Product Details"] = sec.find("p").text # Product Description
data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
dl.append(data)
dl

[{'Product Name': 'Packard 255 G2',
  'Product Link': '/test-sites/e-commerce/static/product/31',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$416.99',
  'Product Details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '2 reviews'}]

In [49]:
df = pd.DataFrame(dl)
df

,Product Name,Product Link,Product Image,Product Price,Product Details,Product Reviews Number
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,/images/test-sites/e-commerce/items/cart2.png,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2 reviews

In [129]:
df.to_csv("webscraper_q7.1.csv" , index = False)

### 7.2 Extract product details from first row & save into csv file. e.g# Packard 255 G2, Aspire E1-510, ThinkPad T540p

In [130]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/static/computers/laptops") 
r.status_code

200

In [131]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="gpBA7dWbADpqLI5gtfudErNyasdl6hSO">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Static | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" rel="canonical"/>\n    <meta content="Static | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $416.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">\n             Packard 255 G2\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $306.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">\n             Aspire E1-510\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $1178.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">\n             ThinkPad T540p\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="1">\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $739.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">\n             ProBook\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             8\n            </span>\n            reviews\n           </p>\n           <p data-rating="4">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $1311.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">\n             ThinkPad X240\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $581.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">\n             Aspire E1-572G\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="1">\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n      </div>\n      <div id="static-pagination">\n       <nav>\n        <ul class="pagination">\n         <li aria-disabled="true" aria-label="« Previous" class="page-item disabled">\n          <span aria-hidden="true" class="page-link">\n           ‹\n          </span>\n         </li>\n         <li aria-current="page" class="page-item active">\n          <span class="page-link">\n           1\n          </span>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=2">\n           2\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">\n           3\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">\n           4\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">\n           5\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">\n           6\n          </a>\n         </li>\n         <li class="page-item">\n 

In [134]:
secrow = soup.find_all("div" , class_ = "product-wrapper card-body")[0:3]
secrow

[<div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$416.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
 						Packard 255 G2
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1178.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">
 						ThinkPad T540p
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>]

In [136]:
dl = []
for sec in secrow:
    data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
    data["Product Name"] = sec.find("a").text.strip() # Product Name
    data["Product Link"] = sec.find("a")["href"] # Product Link
    data["Product Image"] = sec.find("img")["src"] # Product image
    data["Product Price"] = sec.find("h4").text.strip() # price
    data["Product Details"] = sec.find("p").text # Product Description
    data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
    dl.append(data)
dl

[{'Product Name': 'Packard 255 G2',
  'Product Link': '/test-sites/e-commerce/static/product/31',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$416.99',
  'Product Details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Aspire E1-510',
  'Product Link': '/test-sites/e-commerce/static/product/32',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$306.99',
  'Product Details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'ThinkPad T540p',
  'Product Link': '/test-sites/e-commerce/static/product/33',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1178.99',
  'Product Details': '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit',
  'Product Reviews Number': '2 reviews'}]

In [137]:
df= pd.DataFrame(dl)
df

,Product Name,Product Link,Product Image,Product Price,Product Details,Product Reviews Number
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,/images/test-sites/e-commerce/items/cart2.png,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2 reviews
1,Aspire E1-510,/test-sites/e-commerce/static/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews
2,ThinkPad T540p,/test-sites/e-commerce/static/product/33,/images/test-sites/e-commerce/items/cart2.png,$1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",2 reviews

In [138]:
df.to_csv("webscraper_q7.2.csv")

### 7.3 Extract all product details from first page & save into csv file.

In [139]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/static/computers/laptops") 
r.status_code

200

In [140]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="NTec9Dcl4BHIk95ecH96eTVYflDD6oDL">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Static | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" rel="canonical"/>\n    <meta content="Static | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $416.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">\n             Packard 255 G2\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $306.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">\n             Aspire E1-510\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $1178.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">\n             ThinkPad T540p\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="1">\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $739.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">\n             ProBook\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             8\n            </span>\n            reviews\n           </p>\n           <p data-rating="4">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $1311.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">\n             ThinkPad X240\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $581.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">\n             Aspire E1-572G\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             2\n            </span>\n            reviews\n           </p>\n           <p data-rating="1">\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n      </div>\n      <div id="static-pagination">\n       <nav>\n        <ul class="pagination">\n         <li aria-disabled="true" aria-label="« Previous" class="page-item disabled">\n          <span aria-hidden="true" class="page-link">\n           ‹\n          </span>\n         </li>\n         <li aria-current="page" class="page-item active">\n          <span class="page-link">\n           1\n          </span>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=2">\n           2\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">\n           3\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">\n           4\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">\n           5\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">\n           6\n          </a>\n         </li>\n         <li class="page-item">\n 

In [141]:
secrow = soup.find_all("div" , class_ = "product-wrapper card-body")
secrow

[<div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$416.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
 						Packard 255 G2
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1178.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">
 						ThinkPad T540p
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$739.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">
 						ProBook
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1311.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">
 						ThinkPad X240
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$581.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">
 						Aspire E1-572G
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>]

In [144]:
dl = []
for sec in secrow:
    data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
    data["Product Name"] = sec.find("a").text.strip() # Product Name
    data["Product Link"] = sec.find("a")["href"] # Product Link
    data["Product Image"] = sec.find("img")["src"] # Product image
    data["Product Price"] = sec.find("h4").text.strip() # price
    data["Product Details"] = sec.find("p").text # Product Description
    data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
    dl.append(data)
dl

[{'Product Name': 'Packard 255 G2',
  'Product Link': '/test-sites/e-commerce/static/product/31',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$416.99',
  'Product Details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Aspire E1-510',
  'Product Link': '/test-sites/e-commerce/static/product/32',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$306.99',
  'Product Details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'ThinkPad T540p',
  'Product Link': '/test-sites/e-commerce/static/product/33',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1178.99',
  'Product Details': '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'ProBook',
  'Product Link': '/test-sites/e-commerce/static/product/34',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$739.99',
  'Product Details': '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'ThinkPad X240',
  'Product Link': '/test-sites/e-commerce/static/product/35',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1311.99',
  'Product Details': '12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Aspire E1-572G',
  'Product Link': '/test-sites/e-commerce/static/product/36',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$581.99',
  'Product Details': '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
  'Product Reviews Number': '2 reviews'}]

In [145]:
len(dl)

6

In [146]:
df= pd.DataFrame(dl)
df

,Product Name,Product Link,Product Image,Product Price,Product Details,Product Reviews Number
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,/images/test-sites/e-commerce/items/cart2.png,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2 reviews
1,Aspire E1-510,/test-sites/e-commerce/static/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews
2,ThinkPad T540p,/test-sites/e-commerce/static/product/33,/images/test-sites/e-commerce/items/cart2.png,$1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",2 reviews
3,ProBook,/test-sites/e-commerce/static/product/34,/images/test-sites/e-commerce/items/cart2.png,$739.99,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",8 reviews
4,ThinkPad X240,/test-sites/e-commerce/static/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews
5,Aspire E1-572G,/test-sites/e-commerce/static/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews

In [147]:
df.to_csv("webscraper_q7.3.csv")

### 7.4 Extract all product details from second page & save into another csv file.

In [151]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r= requests.get("https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page=2") 
r.status_code

200

In [152]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <!-- Google Tag Manager -->\n  <script nonce="kHIHruKdYVZp7KiFkzpsLoNeJqeiF2B9">\n   (function (w, d, s, l, i) {\n\t\tw[l] = w[l] || [];\n\t\tw[l].push({\n\t\t\t\'gtm.start\':\n\t\t\t\tnew Date().getTime(), event: \'gtm.js\'\n\t\t});\n\t\tvar f = d.getElementsByTagName(s)[0],\n\t\t\tj = d.createElement(s), dl = l != \'dataLayer\' ? \'&l=\' + l : \'\';\n\t\tj.async = true;\n\t\tj.src =\n\t\t\t\'https://www.googletagmanager.com/gtm.js?id=\' + i + dl;\n\t\tf.parentNode.insertBefore(j, f);\n\t})(window, document, \'script\', \'dataLayer\', \'GTM-NVFPDWB\');\n  </script>\n  <!-- End Google Tag Manager -->\n  <title>\n   Static | Web Scraper Test Sites\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>\n  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">\n   <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description">\n    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>\n    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>\n    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>\n    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>\n    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>\n    <link href="https://fonts.googleapis.com" rel="preconnect"/>\n    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>\n    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>\n    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>\n    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>\n    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>\n    <link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page=2" rel="canonical"/>\n    <meta content="Static | Web Scraper Test Sites" property="og:title"/>\n    <meta content="Test Web Scraper\'s features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>\n    <meta content="website" property="og:type"/>\n    <meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page=2" property="og:url"/>\n    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>\n    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">\n    </script>\n   </meta>\n  </meta>\n </head>\n <body>\n  <!-- Google Tag Manager (noscript) -->\n  <noscript>\n   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">\n   </iframe>\n  </noscript>\n  <!-- End Google Tag Manager (noscript) -->\n  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">\n   <div class="container">\n    <div class="navbar-header">\n     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">\n      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">\n       <span class="visually-hidden">\n        Toggle navigation\n       </span>\n       <span class="icon-bar top-bar">\n       </span>\n       <span class="icon-bar middle-bar">\n       </span>\n       <span class="icon-bar bottom-bar">\n       </span>\n       <span class="icon-bar extra-bottom-bar">\n       </span>\n      </button>\n     </a>\n     <div class="navbar-brand">\n      <a href="/">\n       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>\n      </a>\n     </div>\n    </div>\n    <div class="side-collapse in">\n     <nav class="navbar-collapse collapse" id="navbar" role="navigation">\n      <ul class="nav navbar-nav navbar-right">\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/">\n         <p>\n          Web Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">\n         <p>\n          Cloud Scraper\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">\n         <p>\n          Pricing\n         </p>\n         <div class="crta">\n         </div>\n        </a>\n       </li>\n       <li class="nav-item dropdown">\n        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">\n         <p>\n          Learn\n          <i class="ws-icon ws-icon-down">\n          </i>\n         </p>\n         <span class="crta">\n         </span>\n        </button>\n        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">\n         <li>\n          <a class="dropdown-item" href="/documentation">\n           Documentation\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/tutorials">\n           Video Tutorials\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="/test-sites">\n           Test Sites\n          </a>\n         </li>\n         <li>\n          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">\n           Forum\n          </a>\n         </li>\n        </ul>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">\n         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">\n         </i>\n         Install\n        </a>\n       </li>\n       <li class="nav-item">\n        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">\n         Cloud Login\n        </a>\n       </li>\n      </ul>\n     </nav>\n    </div>\n   </div>\n  </header>\n  <div class="wrapper">\n   <div class="formenu-here container-fluid">\n   </div>\n   <div class="container-fluid blog-hero">\n    <div class="container">\n     <div class="row">\n      <div class="col-lg-12">\n       <h1>\n        Test Sites\n       </h1>\n      </div>\n     </div>\n    </div>\n   </div>\n   <div class="container test-site">\n    <div class="row">\n     <div class="col-lg-3 sidebar">\n      <div class="navbar-light sidebar" role="navigation">\n       <div class="sidebar-nav navbar-collapse">\n        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n         <li class="nav-item">\n          <a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url">\n           <span itemprop="name">\n            Home\n           </span>\n          </a>\n         </li>\n         <li class="nav-item active">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">\n           <span itemprop="name">\n            Computers\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">\n             <span itemprop="name">\n              Laptops\n             </span>\n            </a>\n           </li>\n           <li class="nav-item">\n            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">\n             <span itemprop="name">\n              Tablets\n             </span>\n            </a>\n           </li>\n          </ul>\n         </li>\n         <li class="nav-item">\n          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">\n           <span itemprop="name">\n            Phones\n           </span>\n           <i aria-hidden="true" class="ws-icon ws-icon-right">\n           </i>\n          </a>\n         </li>\n        </ul>\n       </div>\n      </div>\n     </div>\n     <div class="col-lg-9">\n      <h1 class="page-header">\n       Computers / Laptops\n      </h1>\n      <div class="row">\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $1033.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/37" itemprop="name" title="ThinkPad Yoga">\n             ThinkPad Yoga\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             13\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $609.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/38" itemprop="name" title="Pavilion">\n             Pavilion\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             4\n            </span>\n            reviews\n           </p>\n           <p data-rating="1">\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $745.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/39" itemprop="name" title="Inspiron 15">\n             Inspiron 15\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             12\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $1281.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/40" itemprop="name" title="Dell XPS 13">\n             Dell XPS 13\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             4\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $1244.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/41" itemprop="name" title="ThinkPad X230">\n             ThinkPad X230\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             10\n            </span>\n            reviews\n           </p>\n           <p data-rating="3">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n       <div class="col-md-4 col-xl-4 col-lg-4">\n        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">\n         <div class="product-wrapper card-body">\n          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>\n          <div class="caption">\n           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">\n            <span itemprop="price">\n             $520.99\n            </span>\n            <meta content="USD" itemprop="priceCurrency"/>\n           </h4>\n           <h4>\n            <a class="title" href="/test-sites/e-commerce/static/product/42" itemprop="name" title="HP 250 G3">\n             HP 250 G3\n            </a>\n           </h4>\n           <p class="description card-text" itemprop="description">\n            15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1\n           </p>\n          </div>\n          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">\n           <p class="review-count float-end">\n            <span itemprop="reviewCount">\n             13\n            </span>\n            reviews\n           </p>\n           <p data-rating="2">\n            <span class="ws-icon ws-icon-star">\n            </span>\n            <span class="ws-icon ws-icon-star">\n            </span>\n           </p>\n          </div>\n         </div>\n        </div>\n       </div>\n      </div>\n      <div id="static-pagination">\n       <nav>\n        <ul class="pagination">\n         <li class="page-item">\n          <a aria-label="« Previous" class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=1" rel="prev">\n           ‹\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=1">\n           1\n          </a>\n         </li>\n         <li aria-current="page" class="page-item active">\n          <span class="page-link">\n           2\n          </span>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">\n           3\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">\n           4\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">\n           5\n          </a>\n         </li>\n         <li class="page-item">\n          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">\n           6\n          </a>\n         </li

In [153]:
secrow = soup.find_all("div" , class_ = "product-wrapper card-body")
secrow

[<div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1033.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/37" itemprop="name" title="ThinkPad Yoga">
 						ThinkPad Yoga
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">13</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$609.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/38" itemprop="name" title="Pavilion">
 						Pavilion
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$745.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/39" itemprop="name" title="Inspiron 15">
 						Inspiron 15
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1281.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/40" itemprop="name" title="Dell XPS 13">
 						Dell XPS 13
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1244.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/41" itemprop="name" title="ThinkPad X230">
 						ThinkPad X230
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>,
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$520.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/42" itemprop="name" title="HP 250 G3">
 						HP 250 G3
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">13</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>]

In [154]:
dl = []
for sec in secrow:
    data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
    data["Product Name"] = sec.find("a").text.strip() # Product Name
    data["Product Link"] = sec.find("a")["href"] # Product Link
    data["Product Image"] = sec.find("img")["src"] # Product image
    data["Product Price"] = sec.find("h4").text.strip() # price
    data["Product Details"] = sec.find("p").text # Product Description
    data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
    dl.append(data)
dl

[{'Product Name': 'ThinkPad Yoga',
  'Product Link': '/test-sites/e-commerce/static/product/37',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1033.99',
  'Product Details': '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'Pavilion',
  'Product Link': '/test-sites/e-commerce/static/product/38',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$609.99',
  'Product Details': '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Inspiron 15',
  'Product Link': '/test-sites/e-commerce/static/product/39',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$745.99',
  'Product Details': 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Dell XPS 13',
  'Product Link': '/test-sites/e-commerce/static/product/40',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1281.99',
  'Product Details': '13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'ThinkPad X230',
  'Product Link': '/test-sites/e-commerce/static/product/41',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1244.99',
  'Product Details': '12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'HP 250 G3',
  'Product Link': '/test-sites/e-commerce/static/product/42',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$520.99',
  'Product Details': '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '13 reviews'}]

In [155]:
len(dl)

6

In [156]:
df= pd.DataFrame(dl)
df

,Product Name,Product Link,Product Image,Product Price,Product Details,Product Reviews Number
0,ThinkPad Yoga,/test-sites/e-commerce/static/product/37,/images/test-sites/e-commerce/items/cart2.png,$1033.99,"12.5"" Touch, Core i3-4010U, 4GB, 500GB + 16GB ...",13 reviews
1,Pavilion,/test-sites/e-commerce/static/product/38,/images/test-sites/e-commerce/items/cart2.png,$609.99,"15.6"", Core i5-4200U, 6GB, 750GB, Windows 8.1",4 reviews
2,Inspiron 15,/test-sites/e-commerce/static/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews
3,Dell XPS 13,/test-sites/e-commerce/static/product/40,/images/test-sites/e-commerce/items/cart2.png,$1281.99,"13.3"" Touch, Core i5-4210U, 8GB, 128GB SSD, Wi...",4 reviews
4,ThinkPad X230,/test-sites/e-commerce/static/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews
5,HP 250 G3,/test-sites/e-commerce/static/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews

In [157]:
df.to_csv("webscraper_q7.4.csv")

### 7.5 Extract all product details from first page to fifth page & save into single csv file.

In [159]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
b_url = "https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page="

In [160]:
dl = []
for page in range (1,6):
    url = b_url + str(page)
    r= requests.get(url)
    soup = BeautifulSoup(r.text , "html.parser")
    secrow = soup.find_all("div" , class_ = "product-wrapper card-body")

    for sec in secrow:
        data = {
    "Product Name": "" ,
    "Product Link" : "" ,
    "Product Image" : "" ,
    "Product Price" : "" ,
    "Product Details" : "" ,
    "Product Reviews Number" : ""
    }
        data["Product Name"] = sec.find("a").text.strip() # Product Name
        data["Product Link"] = sec.find("a")["href"] # Product Link
        data["Product Image"] = sec.find("img")["src"] # Product image
        data["Product Price"] = sec.find("h4").text.strip() # price
        data["Product Details"] = sec.find("p").text # Product Description
        data["Product Reviews Number"] = sec.find("p" , class_ = "review-count float-end").text.strip() # reviews
        dl.append(data)
dl

[{'Product Name': 'Packard 255 G2',
  'Product Link': '/test-sites/e-commerce/static/product/31',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$416.99',
  'Product Details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Aspire E1-510',
  'Product Link': '/test-sites/e-commerce/static/product/32',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$306.99',
  'Product Details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'ThinkPad T540p',
  'Product Link': '/test-sites/e-commerce/static/product/33',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1178.99',
  'Product Details': '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'ProBook',
  'Product Link': '/test-sites/e-commerce/static/product/34',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$739.99',
  'Product Details': '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'ThinkPad X240',
  'Product Link': '/test-sites/e-commerce/static/product/35',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1311.99',
  'Product Details': '12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Aspire E1-572G',
  'Product Link': '/test-sites/e-commerce/static/product/36',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$581.99',
  'Product Details': '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'ThinkPad Yoga',
  'Product Link': '/test-sites/e-commerce/static/product/37',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1033.99',
  'Product Details': '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'Pavilion',
  'Product Link': '/test-sites/e-commerce/static/product/38',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$609.99',
  'Product Details': '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Inspiron 15',
  'Product Link': '/test-sites/e-commerce/static/product/39',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$745.99',
  'Product Details': 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
  'Product Reviews Number': '12 reviews'},
 {'Product Name': 'Dell XPS 13',
  'Product Link': '/test-sites/e-commerce/static/product/40',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1281.99',
  'Product Details': '13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'ThinkPad X230',
  'Product Link': '/test-sites/e-commerce/static/product/41',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1244.99',
  'Product Details': '12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'HP 250 G3',
  'Product Link': '/test-sites/e-commerce/static/product/42',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$520.99',
  'Product Details': '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
  'Product Reviews Number': '13 reviews'},
 {'Product Name': 'ThinkPad Yoga',
  'Product Link': '/test-sites/e-commerce/static/product/43',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1223.99',
  'Product Details': '12.5" Touch, Core i5 4200U, 8GB, 500GB + 16GB SSD Cache, Windows',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'HP 350 G1',
  'Product Link': '/test-sites/e-commerce/static/product/44',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$577.99',
  'Product Details': '15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows',
  'Product Reviews Number': '10 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/static/product/45',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$399',
  'Product Details': 'Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home',
  'Product Reviews Number': '4 reviews'},
 {'Product Name': 'Dell Vostro 15',
  'Product Link': '/test-sites/e-commerce/static/product/46',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$488.78',
  'Product Details': 'Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux',
  'Product Reviews Number': '14 reviews'},
 {'Product Name': 'Acer Spin 5',
  'Product Link': '/test-sites/e-commerce/static/product/47',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$564.98',
  'Product Details': 'Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Acer Aspire A5...',
  'Product Link': '/test-sites/e-commerce/static/product/48',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$679',
  'Product Details': 'Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG',
  'Product Reviews Number': '9 reviews'},
 {'Product Name': 'Dell Inspiron...',
  'Product Link': '/test-sites/e-commerce/static/product/49',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$679',
  'Product Details': 'Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/static/product/50',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$729',
  'Product Details': 'Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd',
  'Product Reviews Number': '2 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Link': '/test-sites/e-commerce/static/product/51',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$799',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Acer Nitro 5 A...',
  'Product Link': '/test-sites/e-commerce/static/product/52',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$809',
  'Product Details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, Windows 10 Home',
  'Product Reviews Number': '0 reviews'},
 {'Product Name': 'Asus ROG STRIX...',
  'Product Link': '/test-sites/e-commerce/static/product/53',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$899',
  'Product Details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS + Windows 10 Home',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Lenovo ThinkPa...',
  'Product Link': '/test-sites/e-commerce/static/product/54',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$999',
  'Product Details': 'Lenovo ThinkPad L570, 15.6" FHD, Core i7-7500U, 8GB, 256GB SSD, Windows 10 Pro',
  'Product Reviews Number': '11 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Link': '/test-sites/e-commerce/static/product/55',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1149',
  'Product Details': 'Lenovo Legion Y520-15IKBM, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB, GeForce GTX 1060 Max-Q 6GB, DOS',
  'Product Reviews Number': '11 reviews'},
 {'Product Name': 'Lenovo Legion...',
  'Product Link': '/test-sites/e-commerce/static/product/56',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1399',
  'Product Details': 'Lenovo Legion Y720, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 2TB HDD, GeForce GTX 1060 6GB, DOS, RGB backlit keyboard',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Link': '/test-sites/e-commerce/static/product/57',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1769',
  'Product Details': 'Asus ROG Strix GL702ZC-GC154T, 17.3" FHD, Ryzen 7 1700, 16GB, 256GB + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
  'Product Reviews Number': '7 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Link': '/test-sites/e-commerce/static/product/58',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1769',
  'Product Details': 'Asus ROG Strix GL702ZC-GC209T, 17.3" FHD IPS, Ryzen 7 1700, 16GB, 256GB SSD + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Asus ROG Strix...',
  'Product Link': '/test-sites/e-commerce/static/product/59',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$1799',
  'Product Details': 'Asus ROG Strix SCAR Edition GL503VM-ED115T, 15.6" FHD 120Hz, Core i7-7700HQ, 16GB, 256GB SSD + 1TB SSHD, GeForce GTX 1060 6GB, Windows 10 Home',
  'Product Reviews Number': '8 reviews'},
 {'Product Name': 'Asus VivoBook...',
  'Product Link': '/test-sites/e-commerce/static/product/60',
  'Product Image': '/images/test-sites/e-commerce/items/cart2.png',
  'Product Price': '$295.99',
  'Product Details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'Product Reviews Number': '14 reviews'}]

In [161]:
df = pd.DataFrame(dl)
df

,Product Name,Product Link,Product Image,Product Price,Product Details,Product Reviews Number
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,/images/test-sites/e-commerce/items/cart2.png,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2 reviews
1,Aspire E1-510,/test-sites/e-commerce/static/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews
2,ThinkPad T540p,/test-sites/e-commerce/static/product/33,/images/test-sites/e-commerce/items/cart2.png,$1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",2 reviews
3,ProBook,/test-sites/e-commerce/static/product/34,/images/test-sites/e-commerce/items/cart2.png,$739.99,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",8 reviews
4,ThinkPad X240,/test-sites/e-commerce/static/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews
5,Aspire E1-572G,/test-sites/e-commerce/static/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews
6,ThinkPad Yoga,/test-sites/e-commerce/static/product/37,/images/test-sites/e-commerce/items/cart2.png,$1033.99,"12.5"" Touch, Core i3-4010U, 4GB, 500GB + 16GB ...",13 reviews
7,Pavilion,/test-sites/e-commerce/static/product/38,/images/test-sites/e-commerce/items/cart2.png,$609.99,"15.6"", Core i5-4200U, 6GB, 750GB, Windows 8.1",4 reviews
8,Inspiron 15,/test-sites/e-commerce/static/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews
9,Dell XPS 13,/test-sites/e-commerce/static/product/40,/images/test-sites/e-commerce/items/cart2.png,$1281.99,"13.3"" Touch, Core i5-4210U, 8GB, 128GB SSD, Wi...",4 reviews
10,ThinkPad X230,/test-sites/e-commerce/static/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews
11,HP 250 G3,/test-sites/e-commerce/static/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews
12,ThinkPad Yoga,/test-sites/e-commerce/static/product/43,/images/test-sites/e-commerce/items/cart2.png,$1223.99,"12.5"" Touch, Core i5 4200U, 8GB, 500GB + 16GB ...",2 reviews
13,HP 350 G1,/test-sites/e-commerce/static/product/44,/images/test-sites/e-commerce/items/cart2.png,$577.99,"15.6"", Core i5-4200U, 4GB, 750GB, Radeon HD867...",10 reviews
14,Asus VivoBook...,/test-sites/e-commerce/static/product/45,/images/test-sites/e-commerce/items/cart2.png,$399,Asus VivoBook Max X541NA-GQ041 Black Chocolate...,4 reviews
15,Dell Vostro 15,/test-sites/e-commerce/static/product/46,/images/test-sites/e-commerce/items/cart2.png,$488.78,"Dell Vostro 15 (3568) Black, 15.6"" FHD, Core i...",14 reviews
16,Acer Spin 5,/test-sites/e-commerce/static/product/47,/images/test-sites/e-commerce/items/cart2.png,$564.98,"Acer Spin 5 SP513-51 Black, 13.3"" FHD Touch, C...",0 reviews
17,Acer Aspire A5...,/test-sites/e-commerce/static/product/48,/images/test-sites/e-commerce/items/cart2.png,$679,"Acer Aspire A515-51-5654, Black, 15.6"", FHD, C...",9 reviews
18,Dell Inspiron...,/test-sites/e-commerce/static/product/49,/images/test-sites/e-commerce/items/cart2.png,$679,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",7 reviews
19,Asus VivoBook...,/test-sites/e-commerce/static/product/50,/images/test-sites/e-commerce/items/cart2.png,$729,"Asus VivoBook S14 (S406UA-BV041T) Starry Grey,...",2 reviews
20,Asus ROG STRIX...,/test-sites/e-commerce/static/product/51,/images/test-sites/e-commerce/items/cart2.png,$799,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews
21,Acer Nitro 5 A...,/test-sites/e-commerce/static/product/52,/images/test-sites/e-commerce/items/cart2.png,$809,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i5-...",0 reviews
22,Asus ROG STRIX...,/test-sites/e-commerce/static/product/53,/images/test-sites/e-commerce/items/cart2.png,$899,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews
23,Lenovo ThinkPa...,/test-sites/e-commerce/static/product/54,/images/test-sites/e-commerce/items/cart2.png,$999,"Lenovo ThinkPad L570, 15.6"" FHD, Core i7-7500U...",11 reviews
24,Lenovo Legion...,/test-sites/e-commerce/static/product/55,/images/test-sites/e-commerce/items/cart2.png,$1149,"Lenovo Legion Y520-15IKBM, 15.6"" FHD IPS, Core...",11 reviews
25,Lenovo Legion...,/test-sites/e-commerce/static/product/56,/images/test-sites/e-commerce/items/cart2.png,$1399,"Lenovo Legion Y720, 15.6"" FHD IPS, Core i7-770...",8 reviews
26,Asus ROG Strix...,/test-sites/e-commerce/static/product/57,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC154T, 17.3"" FHD, Ryze...",7 reviews
27,Asus ROG Strix...,/test-sites/e-commerce/static/product/58,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC209T, 17.3"" FHD IPS, ...",8 reviews
28,Asus ROG Strix...,/test-sites/e-commerce/static/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews
29,Asus VivoBook...,/test-sites/e-commerce/static/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14 reviews

In [162]:
df.to_csv("webscraper_q7.5.csv")

## a5. https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops (product_name (full product name via clicking on link), product_link, product_img,product_price, product_details, product_reviews_number,product_reviews_star_number)

### a5.1 Extract first product details save into csv file. e.g# Asus VivoBook X441NA-GA190

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url = "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r = requests.get(main_url)
r.status_code

200

In [2]:
soup = BeautifulSoup(r.text,"html")
product = soup.find("div",class_ = "col-md-4 col-xl-4 col-lg-4") # finding all products div
product

<div class="col-md-4 col-xl-4 col-lg-4">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>

In [3]:
product.find("a").text.strip() # product name

'Asus VivoBook...'

In [21]:
product.find("a")["href"] # product url

'/test-sites/e-commerce/allinone/product/60'

In [24]:
product.find("img")["src"].strip() # img

'/images/test-sites/e-commerce/items/cart2.png'

In [ ]:
product.find("span").text # price

'$295.99'

In [9]:
product.find("p" , class_ = "description card-text").text

'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd'

In [12]:
product.find("p" , class_ = "review-count float-end").text.strip()

'14 reviews'

In [14]:
product.find("p" , class_ ="data")

In [26]:
dl = []
data = {
    "product_name" : "",
    "product_link" : "",
    "product_img" : "",
    "product_price" : "",
    "product_details" : "",
    "product_reviews_number" : "",
    # "product_reviews_star_number" : ""
}
data["product_name"] = product.find("a").text.strip() # product name
data["product_link"] = product.find("a")["href"] # product url
data["product_img"] = product.find("img")["src"].strip() # img 
data["product_price"] = product.find("span").text # price
data["product_details"] = product.find("p" , class_ = "description card-text").text
data["product_reviews_number"] = product.find("p" , class_ = "review-count float-end").text.strip()
# data["product_reviews_star_number"] =

In [27]:

data["product_link"]

'/test-sites/e-commerce/allinone/product/60'

In [28]:
base_url = "https://webscraper.io"
act_url = base_url + data["product_link"]
req = requests.get(act_url)
req.status_code

200

In [29]:
soup_nw = BeautifulSoup(req.text , "html.parser")
soup_nw

<!DOCTYPE html>

<html lang="en">
<head>
<!-- Google Tag Manager -->
<script nonce="n6fo4brFwbthfJrPrQ7nAXmuSvrSJ5ey">(function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');</script>
<!-- End Google Tag Manager -->
<title>Web Scraper - The #1 web scraping extension</title>
<meta charset="utf-8"/>
<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
<meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
<meta content="The most popular web scraping extension. Start scraping in minutes. Automate your tasks with our Cloud Scraper. No software to download, no coding needed." name="description">
<link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
<link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
<link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
<link href="/icon.svg" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
<link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
<link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
<link href="https://webscraper.io/test-sites/e-commerce/allinone/product/60" rel="canonical"/>
<meta content="Web Scraper - The #1 web scraping extension" property="og:title"/>
<meta content="The most popular web scraping extension. Start scraping in minutes. Automate your tasks with our Cloud Scraper. No software to download, no coding needed." property="og:description"/>
<meta content="website" property="og:type"/>
<meta content="https://webscraper.io/test-sites/e-commerce/allinone/product/60" property="og:url"/>
<meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
<script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b"></script>
</meta></meta></head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>
</header>
<div class="wrapper">
<div class="formenu-here container-fluid">
</div>
<div class="container-fluid blog-hero">
<div class="container">
<div class="row">
<div class="col-lg-12">
<h1>Test Sites</h1>
</div>
</div>
</div>
</div>
<div class="container test-site">
<div class="row">
<div class="col-lg-3 sidebar">
<div class="navbar-light sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
<ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
<li class="nav-item active">
<a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
<span itemprop="name">Computers</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
<li class="nav-item">
<a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
<span itemprop="name">Phones</span>
<i aria-hidden="true" class="ws-icon ws-icon-right"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-lg-9">
<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
<div class="product-wrapper card-body">
<div class="row">
<div class="col-xl-2">
<img alt="item" class="image img-fluid img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
</div>
<div class="col-xl-10">
<div class="caption">
<h4 class="price float-end pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4 class="title card-title" itemprop="name">Asus VivoBook X441NA-GA190</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<label class="memory">HDD:</label>
<div class="swatches">
<button class="btn swatch btn-primary active" type="button" value="128">128</button>
<button class="btn swatch" type="button" value="256">256</button>
<button class="btn swatch" type="button" value="512">512</button>
<button class="btn swatch disabled" type="button" value="1024">1024</button>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count">
<span itemprop="reviewCount">14</span> reviews
																				<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="clearfix"></div>
<div class="push"></div>
</div>
<div class="container-fluid footer" id="layout-footer">
<div class="container">
<div class="row">
<div class="col-lg-3">
<ul>
<li><p>Products</p></li>
<li>
<a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
							Web Scraper browser extension
						</a>
</li>
<li>
<a href="/cloud-scraper">Web Scraper Cloud</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Company</p></li>
<li>
<a href="/about-us">About us</a>
</li>
<li>
<a href="/contact">Contact</a>
</li>
<li>
<a href="/privacy-policy">Website Privacy Policy</a>
</li>
<li>
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a>
</li>
<li>
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a>
</li>
<li><a href="/jobs">Jobs</a></li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>Resources</p></li>
<li><a href="/blog">Blog</a></li>
<li>
<a href="/documentation">Documentation</a>
</li>
<li>
<a href="/tutorials">Video Tutorials</a>
</li>
<li>
<a href="/screenshots">Screenshots</a>
</li>
<li>
<a href="/test-sites">Test Sites</a>
</li>
<li>
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
<li>
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a>
</li>
</ul>
</div>
<div class="col-lg-3">
<ul>
<li><p>CONTACT US</p></li>
<li>
<a href="mailto:info@webscraper.io">info@webscraper.io</a>
</li>
<li>Ubelu 5-71,<br/> Adazi, Latvia, LV-2164</li>
</ul>
<ul class="smedia">
<li>
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a>
</li>
<li>
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a>
</li>
<li>
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="browser-icon ws-icon ws-icon-chrome-dark"></i>
</a>
</li>
</ul>
</div>
</div>
<div class="row">
<div class="col-lg-12">
<p class="copyright">Copyright © 2025
					<b>Web Scraper</b> | All rights reserved</p>
</div>
</div>
</div>
</div>
</body>
</html>

In [30]:
soup_nw.find("h4" , class_ = "title card-title" ).text

'Asus VivoBook X441NA-GA190'

In [31]:
data["product_name"] = soup_nw.find("h4" , class_ = "title card-title" ).text
dl.append(data)

In [32]:
dl

[{'product_name': 'Asus VivoBook X441NA-GA190',
  'product_link': '/test-sites/e-commerce/allinone/product/60',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$295.99',
  'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_reviews_number': '14 reviews'}]

In [33]:
df = pd.DataFrame(dl)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number
0,Asus VivoBook X441NA-GA190,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14 reviews

In [34]:
df.to_csv("web_scraper_qa5.1.csv")

### a5.2 Extract product details from first row & save into csv file. e.g# Asus VivoBook X441NA-GA190, Prestigio SmartBook 133S Dark Grey, Prestigio SmartBook 133S Gold

In [35]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url = "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r = requests.get(main_url)
r.status_code

200

In [39]:
soup = BeautifulSoup(r.text,"html")
products = soup.find_all("div",class_ = "col-md-4 col-xl-4 col-lg-4")[0:3] # finding 1 row products div
products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>]

In [52]:
dl = []
for product in products:
    
    data = {
        "product_name" : "",
        "product_link" : "",
        "product_img" : "",
        "product_price" : "",
        "product_details" : "",
        "product_reviews_number" : "",
    # "product_reviews_star_number" : ""
    }
    
    data["product_link"] = product.find("a")["href"] # product url

    base_url = "https://webscraper.io"
    act_url = base_url + data["product_link"]
    req = requests.get(act_url)
    soup_nw = BeautifulSoup(req.text , "html.parser")
    data["product_name"] = soup_nw.find("h4" , class_ = "title card-title" ).text

    data["product_img"] = product.find("img")["src"].strip() # img 
    data["product_price"] = product.find("span").text # price
    data["product_details"] = product.find("p" , class_ = "description card-text").text
    data["product_reviews_number"] = product.find("p" , class_ = "review-count float-end").text.strip()
    dl.append(data)

dl

[{'product_name': 'Asus VivoBook X441NA-GA190',
  'product_link': '/test-sites/e-commerce/allinone/product/60',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$295.99',
  'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Prestigio SmartBook 133S Dark Grey',
  'product_link': '/test-sites/e-commerce/allinone/product/61',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Prestigio SmartBook 133S Gold',
  'product_link': '/test-sites/e-commerce/allinone/product/62',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '12 reviews'}]

In [53]:
df = pd.DataFrame(dl)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number
0,Asus VivoBook X441NA-GA190,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14 reviews
1,Prestigio SmartBook 133S Dark Grey,/test-sites/e-commerce/allinone/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",8 reviews
2,Prestigio SmartBook 133S Gold,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews

In [54]:
df.to_csv("web_scraper_qa5.2.csv")

### a5.3 Extract all product details from page & save into csv file.

In [55]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url = "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r = requests.get(main_url)
r.status_code

200

In [56]:
soup = BeautifulSoup(r.text,"html")
products = soup.find_all("div",class_ = "col-md-4 col-xl-4 col-lg-4") # finding 1 row products div
products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$321.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$356.49</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$364.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
 						Hewlett Packar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$372.7</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$391.48</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$393.88</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/70" itemprop="name" title="Acer Aspire 3 A315-21">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/45" itemprop="name" title="Asus VivoBook Max">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/71" itemprop="name" title="Asus VivoBook E502NA-GO022T Dark Blue">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">3</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$404.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/72" itemprop="name" title="Lenovo ThinkPad E31-80">
 						Lenovo ThinkPa...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$408.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/73" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,

In [57]:
dl = []
for product in products:
    
    data = {
        "product_name" : "",
        "product_link" : "",
        "product_img" : "",
        "product_price" : "",
        "product_details" : "",
        "product_reviews_number" : "",
    # "product_reviews_star_number" : ""
    }
    
    data["product_link"] = product.find("a")["href"] # product url

    base_url = "https://webscraper.io"
    act_url = base_url + data["product_link"]
    req = requests.get(act_url)
    soup_nw = BeautifulSoup(req.text , "html.parser")
    data["product_name"] = soup_nw.find("h4" , class_ = "title card-title" ).text

    data["product_img"] = product.find("img")["src"].strip() # img 
    data["product_price"] = product.find("span").text # price
    data["product_details"] = product.find("p" , class_ = "description card-text").text
    data["product_reviews_number"] = product.find("p" , class_ = "review-count float-end").text.strip()
    dl.append(data)

dl

[{'product_name': 'Asus VivoBook X441NA-GA190',
  'product_link': '/test-sites/e-commerce/allinone/product/60',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$295.99',
  'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Prestigio SmartBook 133S Dark Grey',
  'product_link': '/test-sites/e-commerce/allinone/product/61',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Prestigio SmartBook 133S Gold',
  'product_link': '/test-sites/e-commerce/allinone/product/62',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Aspire E1-510',
  'product_link': '/test-sites/e-commerce/allinone/product/32',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$306.99',
  'product_details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Lenovo V110-15IAP',
  'product_link': '/test-sites/e-commerce/allinone/product/63',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$321.94',
  'product_details': 'Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '5 reviews'},
 {'product_name': 'Lenovo V110-15IAP',
  'product_link': '/test-sites/e-commerce/allinone/product/64',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$356.49',
  'product_details': 'Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd',
  'product_reviews_number': '6 reviews'},
 {'product_name': 'Hewlett Packard 250 G6 Dark Ash Silver',
  'product_link': '/test-sites/e-commerce/allinone/product/65',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$364.46',
  'product_details': 'Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Acer Aspire 3 A315-31 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/66',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$372.7',
  'product_details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Acer Aspire A315-31-C33J',
  'product_link': '/test-sites/e-commerce/allinone/product/67',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$379.94',
  'product_details': 'Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/68',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$379.95',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Acer Aspire 3 A315-31 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/69',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$391.48',
  'product_details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Acer Aspire 3 A315-21',
  'product_link': '/test-sites/e-commerce/allinone/product/70',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$393.88',
  'product_details': 'Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Asus VivoBook Max',
  'product_link': '/test-sites/e-commerce/allinone/product/45',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$399',
  'product_details': 'Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Asus VivoBook E502NA-GO022T Dark Blue',
  'product_link': '/test-sites/e-commerce/allinone/product/71',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$399.99',
  'product_details': 'Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'product_reviews_number': '3 reviews'},
 {'product_name': 'Lenovo ThinkPad E31-80',
  'product_link': '/test-sites/e-commerce/allinone/product/72',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$404.23',
  'product_details': 'Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Acer Aspire 3 A315-31 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/73',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$408.98',
  'product_details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Lenovo V110-15ISK',
  'product_link': '/test-sites/e-commerce/allinone/product/74',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$409.63',
  'product_details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Acer Aspire ES1-732 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/75',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$410.46',
  'product_details': 'Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Asus VivoBook 15 X540NA-GQ026T',
  'product_link': '/test-sites/e-commerce/allinone/product/76',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$410.66',
  'product_details': 'Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Packard 255 G2',
  'product_link': '/test-sites/e-commerce/allinone/product/31',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$416.99',
  'product_details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Asus EeeBook R416NA-FA014T',
  'product_link': '/test-sites/e-commerce/allinone/product/77',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$433.3',
  'product_details': 'Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Acer Aspire 3 A315-51',
  'product_link': '/test-sites/e-commerce/allinone/product/78',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$436.29',
  'product_details': 'Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/79',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$436.29',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Acer Extensa 15 (2540) Black',
  'product_link': '/test-sites/e-commerce/allinone/product/80',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$439.73',
  'product_details': 'Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'product_reviews_number': '6 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/81',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$454.62',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Lenovo V110-15ISK',
  'product_link': '/test-sites/e-commerce/allinone/product/82',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$454.73',
  'product_details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Acer Aspire A315-51-33TG',
  'product_link': '/test-sites/e-commerce/allinone/product/83',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$457.38',
  'product_details': 'Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Lenovo V110-15IKB',
  'product_link': '/test-sites/e-commerce/allinone/product/84',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$465.95',
  'product_details': 'Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Asus VivoBook 15 X540UA-DM260 Chocolate Black',
  'product_link': '/test-sites/e-commerce/allinone/product/85',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$468.56',
  'product_details': 'Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/86',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$469.1',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '5 reviews'},
 {'product_name': 'Lenovo V510 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/87',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$484.23',
  'product_details': 'Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/88',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$485.9',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux',
  'product_reviews_number': '6 reviews'},
 {'product_name': 'Lenovo V510 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/89',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$487.8',
  'product_details': 'Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Acer Swift 1 SF113-31 Silver',
  'product_link': '/test-sites/e-commerce/allinone/product/90',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$488.64',
  'product_details': 'Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Dell Vostro 15',
  'product_link': '/test-sites/e-commerce/allinone/product/46',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$488.78',
  'product_details': 'Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Acer Aspire 3 A315-51 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/91',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$494.71',
  'product_details': 'Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Dell Vostro 15 (3568) Red',
  'product_link': '/test-sites/e-commerce/allinone/product/92',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$497.17',
  'product_details': 'Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Lenovo V510 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/93',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$498.23',
  'product_details': 'Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro',
  'product_reviews_number': '5 reviews'},
 {'product_name': 'HP 250 G3',
  'product_link': '/test-sites/e-commerce/allinone/product/42',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$520.99',
  'product_details': '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
  'product_reviews_number': '13 reviews'},
 {'product_name': 'Acer Spin 5',
  'product_link': '/test-sites/e-commerce/allinone/product/47',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$564.98',
  'product_details': 'Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'HP 350 G1',
  'product_link': '/test-sites/e-commerce/allinone/product/44',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$577.99',
  'product_details': '15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Aspire E1-572G',
  'product_link': '/test-sites/e-commerce/allinone/product/36',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$581.99',
  'product_details': '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Pavilion',
  'product_link': '/test-sites/e-commerce/allinone/product/38',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$609.99',
  'product_details': '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Acer Aspire A515-51-5654',
  'product_link': '/test-sites/e-commerce/allinone/product/48',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$679',
  'product_details': 'Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Dell Inspiron 15',
  'product_link': '/test-sites/e-commerce/allinone/product/49',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$679',
  'product_details': 'Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Asus VivoBook S14',
  'product_link': '/test-sites/e-commerce/allinone/product/50',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$729',
  'product_details': 'Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'ProBook',
  'product_link': '/test-sites/e-commerce/allinone/product/34',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$739.99',
  'product_details': '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Inspiron 15',
  'product_link': '/test-sites/e-commerce/allinone/product/39',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$745.99',
  'product_details': 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Asus ROG STRIX GL553VD-DM256',
  'product_link': '/test-sites/e-commerce/allinone/product/51',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$799',
  'product_details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Acer Nitro 5 AN515-51',
  'product_link': '/test-sites/e-commerce/allinone/product/52',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$809',
  'product_details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, Windows 10 Home',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'Asus ROG STRIX GL553VD-DM256',
  'product_link': '/test-sites/e-commerce/allinone/product/53',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$899',
  'product_details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS + Windows 10 Home',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Lenovo ThinkPad L570',
  'product_link': '/test-sites/e-commerce/allinone/product/54',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$999',
  'product_details': 'Lenovo ThinkPad L570, 15.6" FHD, Core i7-7500U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '11 reviews'},
 {'product_name': 'ThinkPad Yoga',
  'product_link': '/test-sites/e-commerce/allinone/product/37',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1033.99',
  'product_details': '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
  'product_reviews_number': '13 reviews'},
 {'product_name': 'Lenovo ThinkPad L460',
  'product_link': '/test-sites/e-commerce/allinone/product/94',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1096.02',
  'product_details': 'Lenovo ThinkPad L460, 14" FHD IPS, Core i7-6600U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Dell Inspiron 15 (7567) Black',
  'product_link': '/test-sites/e-commerce/allinone/product/95',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1098.42',
  'product_details': 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 4GB, Windows 10 Home',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'MSI GL72M 7RDX',
  'product_link': '/test-sites/e-commerce/allinone/product/96',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1099',
  'product_details': 'MSI GL72M 7RDX, 17.3" FHD, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'MSI GL72M 7RDX',
  'product_link': '/test-sites/e-commerce/allinone/product/97',

In [58]:
df = pd.DataFrame(dl)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number
0,Asus VivoBook X441NA-GA190,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14 reviews
1,Prestigio SmartBook 133S Dark Grey,/test-sites/e-commerce/allinone/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",8 reviews
2,Prestigio SmartBook 133S Gold,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews
3,Aspire E1-510,/test-sites/e-commerce/allinone/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews
4,Lenovo V110-15IAP,/test-sites/e-commerce/allinone/product/63,/images/test-sites/e-commerce/items/cart2.png,$321.94,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",5 reviews
...,...,...,...,...,...,...
112,Lenovo Legion Y720,/test-sites/e-commerce/allinone/product/56,/images/test-sites/e-commerce/items/cart2.png,$1399,"Lenovo Legion Y720, 15.6"" FHD IPS, Core i7-770...",8 reviews
113,Asus ROG Strix GL702VM-GC146T,/test-sites/e-commerce/allinone/product/147,/images/test-sites/e-commerce/items/cart2.png,$1399,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",10 reviews
114,Asus ROG Strix GL702ZC-GC154T,/test-sites/e-commerce/allinone/product/57,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC154T, 17.3"" FHD, Ryze...",7 reviews
115,Asus ROG Strix GL702ZC-GC209T,/test-sites/e-commerce/allinone/product/58,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC209T, 17.3"" FHD IPS, ...",8 reviews
116,Asus ROG Strix SCAR Edition GL503VM-ED115T,/test-sites/e-commerce/allinone/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews

In [60]:
df.to_csv("web_scraper_qa5.3.csv")

### a5.4 Extract all product details of first column save into csv file.

In [61]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url = "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r = requests.get(main_url)
r.status_code

200

In [62]:
soup = BeautifulSoup(r.text,"html")
products = soup.find_all("div",class_ = "col-md-4 col-xl-4 col-lg-4")[0::3] # finding 1 row products div
products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$364.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
 						Hewlett Packar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/45" itemprop="name" title="Asus VivoBook Max">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$408.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/73" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$410.66</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/76" itemprop="name" title="Asus VivoBook 15 X540NA-GQ026T">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$436.29</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/78" itemprop="name" title="Acer Aspire 3 A315-51">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">1</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$454.62</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/81" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$465.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/84" itemprop="name" title="Lenovo V110-15IKB">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">7</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$484.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/87" itemprop="name" title="Lenovo V510 Black">
 						Lenovo V510 Bl...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$488.64</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/90" itemprop="name" title="Acer Swift 1 SF113-31 Silver">
 						Acer Swift 1 S...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$497.17</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/92" itemprop="name" title="Dell Vostro 15 (3568) Red">
 						Dell Vostro 15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$564.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/47" itemprop="name" title="Acer Spin 5">
 						Acer Spin 5
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$609.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/38" itemprop="name" title="Pavilion">
 						Pavilion
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$729</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/50" itemprop="name" title="Asus VivoBook S14">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$799</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>

In [63]:
dl = []
for product in products:
    
    data = {
        "product_name" : "",
        "product_link" : "",
        "product_img" : "",
        "product_price" : "",
        "product_details" : "",
        "product_reviews_number" : "",
    # "product_reviews_star_number" : ""
    }
    
    data["product_link"] = product.find("a")["href"] # product url

    base_url = "https://webscraper.io"
    act_url = base_url + data["product_link"]
    req = requests.get(act_url)
    soup_nw = BeautifulSoup(req.text , "html.parser")
    data["product_name"] = soup_nw.find("h4" , class_ = "title card-title" ).text

    data["product_img"] = product.find("img")["src"].strip() # img 
    data["product_price"] = product.find("span").text # price
    data["product_details"] = product.find("p" , class_ = "description card-text").text
    data["product_reviews_number"] = product.find("p" , class_ = "review-count float-end").text.strip()
    dl.append(data)

dl

[{'product_name': 'Asus VivoBook X441NA-GA190',
  'product_link': '/test-sites/e-commerce/allinone/product/60',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$295.99',
  'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Aspire E1-510',
  'product_link': '/test-sites/e-commerce/allinone/product/32',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$306.99',
  'product_details': '15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Hewlett Packard 250 G6 Dark Ash Silver',
  'product_link': '/test-sites/e-commerce/allinone/product/65',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$364.46',
  'product_details': 'Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/68',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$379.95',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Asus VivoBook Max',
  'product_link': '/test-sites/e-commerce/allinone/product/45',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$399',
  'product_details': 'Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Acer Aspire 3 A315-31 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/73',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$408.98',
  'product_details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Asus VivoBook 15 X540NA-GQ026T',
  'product_link': '/test-sites/e-commerce/allinone/product/76',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$410.66',
  'product_details': 'Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Acer Aspire 3 A315-51',
  'product_link': '/test-sites/e-commerce/allinone/product/78',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$436.29',
  'product_details': 'Acer Aspire 3 A315-51, 15.6" HD, Core i3-6006U, 4GB, 1TB, Windows 10 Home',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/81',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$454.62',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Lenovo V110-15IKB',
  'product_link': '/test-sites/e-commerce/allinone/product/84',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$465.95',
  'product_details': 'Lenovo V110-15IKB, 15.6" HD, Core i5-7200U, 4GB, 500GB, DOS',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Lenovo V510 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/87',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$484.23',
  'product_details': 'Lenovo V510 Black, 14" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Acer Swift 1 SF113-31 Silver',
  'product_link': '/test-sites/e-commerce/allinone/product/90',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$488.64',
  'product_details': 'Acer Swift 1 SF113-31 Silver, 13.3" FHD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Dell Vostro 15 (3568) Red',
  'product_link': '/test-sites/e-commerce/allinone/product/92',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$497.17',
  'product_details': 'Dell Vostro 15 (3568) Red, 15.6" HD, Core i5-7200U, 4GB, 1TB, Radeon R5 M420 2GB, Linux',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Acer Spin 5',
  'product_link': '/test-sites/e-commerce/allinone/product/47',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$564.98',
  'product_details': 'Acer Spin 5 SP513-51 Black, 13.3" FHD Touch, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'Pavilion',
  'product_link': '/test-sites/e-commerce/allinone/product/38',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$609.99',
  'product_details': '15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Asus VivoBook S14',
  'product_link': '/test-sites/e-commerce/allinone/product/50',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$729',
  'product_details': 'Asus VivoBook S14 (S406UA-BV041T) Starry Grey, 14", Core i5-8250U, 8GB, 256GB SSD, Windows 10 Home, Eng kbd',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Asus ROG STRIX GL553VD-DM256',
  'product_link': '/test-sites/e-commerce/allinone/product/51',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$799',
  'product_details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Lenovo ThinkPad L570',
  'product_link': '/test-sites/e-commerce/allinone/product/54',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$999',
  'product_details': 'Lenovo ThinkPad L570, 15.6" FHD, Core i7-7500U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '11 reviews'},
 {'product_name': 'Dell Inspiron 15 (7567) Black',
  'product_link': '/test-sites/e-commerce/allinone/product/95',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1098.42',
  'product_details': 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 4GB, Windows 10 Home',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Asus ROG Strix GL553VD-DM535T',
  'product_link': '/test-sites/e-commerce/allinone/product/98',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1101.83',
  'product_details': 'Apple MacBook Air 13.3", Core i5 1.8GHz, 8GB, 128GB SSD, Intel HD 4000, RUS',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Lenovo Legion Y520-15IKBM',
  'product_link': '/test-sites/e-commerce/allinone/product/101',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1112.91',
  'product_details': 'Lenovo Legion Y520-15IKBM, Black, 15.6" FHD IPS, Core i5-7300HQ, 8 GB, 128GB SSD + 2 TB HDD, NVIDIA GeForce GTX 1060 6 GB, FreeDOS + Windows 10 Home',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Acer Aspire 7 A715-71G',
  'product_link': '/test-sites/e-commerce/allinone/product/104',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1123.87',
  'product_details': 'Acer Aspire 7 A715-71G, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB HDD, GTX 1050 Ti 4GB, Windows 10 Home',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Lenovo Legion Y520',
  'product_link': '/test-sites/e-commerce/allinone/product/107',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1133.91',
  'product_details': 'Lenovo Legion Y520, 15.6" FHD, Core i7-7700HQ, 8GB, 128 GB SSD + 1TB HDD, GTX 1050 4GB, Windows 10 Home',
  'product_reviews_number': '13 reviews'},
 {'product_name': 'Dell Latitude 5480',
  'product_link': '/test-sites/e-commerce/allinone/product/110',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1143.4',
  'product_details': 'Dell Latitude 5480, 14" FHD, Core i5-7440HQ, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '5 reviews'},
 {'product_name': 'Lenovo Legion Y520-15IKBM',
  'product_link': '/test-sites/e-commerce/allinone/product/55',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1149',
  'product_details': 'Lenovo Legion Y520-15IKBM, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 1TB, GeForce GTX 1060 Max-Q 6GB, DOS',
  'product_reviews_number': '11 reviews'},
 {'product_name': 'Toshiba Portege Z30-C-16L Grey',
  'product_link': '/test-sites/e-commerce/allinone/product/115',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1154.04',
  'product_details': 'Toshiba Portege Z30-C-16L Grey, 13.3" FHD, Core i7-6500U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'ThinkPad T540p',
  'product_link': '/test-sites/e-commerce/allinone/product/33',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1178.99',
  'product_details': '15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Acer Predator Helios 300 (PH317-51)',
  'product_link': '/test-sites/e-commerce/allinone/product/120',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1187.98',
  'product_details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ. 8GB, 128GB SSD +1TB, GeForce GTX 1050Ti 4GB, Linux + Windows 10 Home',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Lenovo Yoga 910 Grey',
  'product_link': '/test-sites/e-commerce/allinone/product/123',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1199.73',
  'product_details': 'Lenovo Yoga 910 Grey, 13.9" FHD Touch, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Acer Predator Helios 300 (PH317-51)',
  'product_link': '/test-sites/e-commerce/allinone/product/126',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1221.58',
  'product_details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Dell Latitude 5480',
  'product_link': '/test-sites/e-commerce/allinone/product/128',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1238.37',
  'product_details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'Asus ROG Strix GL753VE-GC096T',
  'product_link': '/test-sites/e-commerce/allinone/product/130',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1259',
  'product_details': 'Asus ROG Strix GL753VE-GC096T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 4GB, Windows 10 Home, Eng kbd',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Hewlett Packard Spectre 13-v106na Dark Ash Silver',
  'product_link': '/test-sites/e-commerce/allinone/product/133',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1273.11',
  'product_details': 'Hewlett Packard Spectre 13-v106na Dark Ash Silver, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Home',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'MSI GL62VR 7RFX',
  'product_link': '/test-sites/e-commerce/allinone/product/135',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1299',
  'product_details': 'MSI GL62VR 7RFX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 256GB SSD, GeForce GTX 1060 3GB, Windows 10 Home',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Hewlett Packard ProBook 640 G3',
  'product_link': '/test-sites/e-commerce/allinone/product/137',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1326.83',
  'product_details': 'Hewlett Packard ProBook 640 G3, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Dell Latitude 5480',
  'product_link': '/test-sites/e-commerce/allinone/product/140',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1338.37',
  'product_details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Linux + Windows 10 Home',
  'product_reviews_number': '11 reviews'},
 {'product_name': 'Lenovo ThinkPad T470',
  'product_link': '/test-sites/e-commerce/allinone/product/143',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1349.23',
  'product_details': 'Lenovo ThinkPad T470, 14" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '5 reviews'},
 {'product_name': 'Asus ASUSPRO B9440UA-GV0279R Gray',
  'product_link': '/test-sites/e-commerce/allinone/product/146',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1381.13',
  'product_details': 'Asus ASUSPRO B9440UA-GV0279R Gray, 14" FHD, Core i7-7500U, 16GB, 512GB SSD, Windows 10 Pro, Eng kbd',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Asus ROG Strix GL702ZC-GC154T',
  'product_link': '/test-sites/e-commerce/allinone/product/57',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1769',
  'product_details': 'Asus ROG Strix GL702ZC-GC154T, 17.3" FHD, Ryzen 7 1700, 16GB, 256GB + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
  'product_reviews_number': '7 reviews'}]

In [66]:

df = pd.DataFrame(dl)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number
0,Asus VivoBook X441NA-GA190,/test-sites/e-commerce/allinone/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14 reviews
1,Aspire E1-510,/test-sites/e-commerce/allinone/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews
2,Hewlett Packard 250 G6 Dark Ash Silver,/test-sites/e-commerce/allinone/product/65,/images/test-sites/e-commerce/items/cart2.png,$364.46,"Hewlett Packard 250 G6 Dark Ash Silver, 15.6"" ...",12 reviews
3,Acer Aspire ES1-572 Black,/test-sites/e-commerce/allinone/product/68,/images/test-sites/e-commerce/items/cart2.png,$379.95,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",9 reviews
4,Asus VivoBook Max,/test-sites/e-commerce/allinone/product/45,/images/test-sites/e-commerce/items/cart2.png,$399,Asus VivoBook Max X541NA-GQ041 Black Chocolate...,4 reviews
5,Acer Aspire 3 A315-31 Black,/test-sites/e-commerce/allinone/product/73,/images/test-sites/e-commerce/items/cart2.png,$408.98,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",10 reviews
6,Asus VivoBook 15 X540NA-GQ026T,/test-sites/e-commerce/allinone/product/76,/images/test-sites/e-commerce/items/cart2.png,$410.66,Asus VivoBook 15 X540NA-GQ026T Chocolate Black...,4 reviews
7,Acer Aspire 3 A315-51,/test-sites/e-commerce/allinone/product/78,/images/test-sites/e-commerce/items/cart2.png,$436.29,"Acer Aspire 3 A315-51, 15.6"" HD, Core i3-6006U...",1 reviews
8,Acer Aspire ES1-572 Black,/test-sites/e-commerce/allinone/product/81,/images/test-sites/e-commerce/items/cart2.png,$454.62,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i5-7...",9 reviews
9,Lenovo V110-15IKB,/test-sites/e-commerce/allinone/product/84,/images/test-sites/e-commerce/items/cart2.png,$465.95,"Lenovo V110-15IKB, 15.6"" HD, Core i5-7200U, 4G...",7 reviews
10,Lenovo V510 Black,/test-sites/e-commerce/allinone/product/87,/images/test-sites/e-commerce/items/cart2.png,$484.23,"Lenovo V510 Black, 14"" HD, Core i3-6006U, 4GB,...",8 reviews
11,Acer Swift 1 SF113-31 Silver,/test-sites/e-commerce/allinone/product/90,/images/test-sites/e-commerce/items/cart2.png,$488.64,"Acer Swift 1 SF113-31 Silver, 13.3"" FHD, Penti...",4 reviews
12,Dell Vostro 15 (3568) Red,/test-sites/e-commerce/allinone/product/92,/images/test-sites/e-commerce/items/cart2.png,$497.17,"Dell Vostro 15 (3568) Red, 15.6"" HD, Core i5-7...",9 reviews
13,Acer Spin 5,/test-sites/e-commerce/allinone/product/47,/images/test-sites/e-commerce/items/cart2.png,$564.98,"Acer Spin 5 SP513-51 Black, 13.3"" FHD Touch, C...",0 reviews
14,Pavilion,/test-sites/e-commerce/allinone/product/38,/images/test-sites/e-commerce/items/cart2.png,$609.99,"15.6"", Core i5-4200U, 6GB, 750GB, Windows 8.1",4 reviews
15,Asus VivoBook S14,/test-sites/e-commerce/allinone/product/50,/images/test-sites/e-commerce/items/cart2.png,$729,"Asus VivoBook S14 (S406UA-BV041T) Starry Grey,...",2 reviews
16,Asus ROG STRIX GL553VD-DM256,/test-sites/e-commerce/allinone/product/51,/images/test-sites/e-commerce/items/cart2.png,$799,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews
17,Lenovo ThinkPad L570,/test-sites/e-commerce/allinone/product/54,/images/test-sites/e-commerce/items/cart2.png,$999,"Lenovo ThinkPad L570, 15.6"" FHD, Core i7-7500U...",11 reviews
18,Dell Inspiron 15 (7567) Black,/test-sites/e-commerce/allinone/product/95,/images/test-sites/e-commerce/items/cart2.png,$1098.42,"Dell Inspiron 15 (7567) Black, 15.6"" FHD, Core...",7 reviews
19,Asus ROG Strix GL553VD-DM535T,/test-sites/e-commerce/allinone/product/98,/images/test-sites/e-commerce/items/cart2.png,$1101.83,"Apple MacBook Air 13.3"", Core i5 1.8GHz, 8GB, ...",4 reviews
20,Lenovo Legion Y520-15IKBM,/test-sites/e-commerce/allinone/product/101,/images/test-sites/e-commerce/items/cart2.png,$1112.91,"Lenovo Legion Y520-15IKBM, Black, 15.6"" FHD IP...",1 reviews
21,Acer Aspire 7 A715-71G,/test-sites/e-commerce/allinone/product/104,/images/test-sites/e-commerce/items/cart2.png,$1123.87,"Acer Aspire 7 A715-71G, 15.6"" FHD IPS, Core i7...",4 reviews
22,Lenovo Legion Y520,/test-sites/e-commerce/allinone/product/107,/images/test-sites/e-commerce/items/cart2.png,$1133.91,"Lenovo Legion Y520, 15.6"" FHD, Core i7-7700HQ,...",13 reviews
23,Dell Latitude 5480,/test-sites/e-commerce/allinone/product/110,/images/test-sites/e-commerce/items/cart2.png,$1143.4,"Dell Latitude 5480, 14"" FHD, Core i5-7440HQ, 8...",5 reviews
24,Lenovo Legion Y520-15IKBM,/test-sites/e-commerce/allinone/product/55,/images/test-sites/e-commerce/items/cart2.png,$1149,"Lenovo Legion Y520-15IKBM, 15.6"" FHD IPS, Core...",11 reviews
25,Toshiba Portege Z30-C-16L Grey,/test-sites/e-commerce/allinone/product/115,/images/test-sites/e-commerce/items/cart2.png,$1154.04,"Toshiba Portege Z30-C-16L Grey, 13.3"" FHD, Cor...",7 reviews
26,ThinkPad T540p,/test-sites/e-commerce/allinone/product/33,/images/test-sites/e-commerce/items/cart2.png,$1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",2 reviews
27,Acer Predator Helios 300 (PH317-51),/test-sites/e-commerce/allinone/product/120,/images/test-sites/e-commerce/items/cart2.png,$1187.98,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",14 reviews
28,Lenovo Yoga 910 Grey,/test-sites/e-commerce/allinone/product/123,/images/test-sites/e-commerce/items/cart2.png,$1199.73,"Lenovo Yoga 910 Grey, 13.9"" FHD Touch, Core i5...",7 reviews
29,Acer Predator Helios 300 (PH317-51),/test-sites/e-commerce/allinone/product/126,/images/test-sites/e-commerce/items/cart2.png,$1221.58,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",9 reviews
30,Dell Latitude 5480,/test-sites/e-commerce/allinone/product/128,/images/test-sites/e-commerce/items/cart2.png,$1238.37,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",0 reviews
31,Asus ROG Strix GL753VE-GC096T,/test-sites/e-commerce/allinone/product/130,/images/test-sites/e-commerce/items/cart2.png,$1259,"Asus ROG Strix GL753VE-GC096T, 17.3"" FHD, Core...",7 reviews
32,Hewlett Packard Spectre 13-v106na Dark Ash Silver,/test-sites/e-commerce/allinone/product/133,/images/test-sites/e-commerce/items/cart2.png,$1273.11,Hewlett Packard Spectre 13-v106na Dark Ash Sil...,8 reviews
33,MSI GL62VR 7RFX,/test-sites/e-commerce/allinone/product/135,/images/test-sites/e-commerce/items/cart2.png,$1299,"MSI GL62VR 7RFX, 15.6"" FHD, Core i7-7700HQ, 8G...",1 reviews
34,Hewlett Packard ProBook 640 G3,/test-sites/e-commerce/allinone/product/137,/images/test-sites/e-commerce/items/cart2.png,$1326.83,"Hewlett Packard ProBook 640 G3, 14"" FHD, Core ...",2 reviews
35,Dell Latitude 5480,/test-sites/e-commerce/allinone/product/140,/images/test-sites/e-commerce/items/cart2.png,$1338.37,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",11 reviews
36,Lenovo ThinkPad T470,/test-sites/e-commerce/allinone/product/143,/images/test-sites/e-commerce/items/cart2.png,$1349.23,"Lenovo ThinkPad T470, 14"" FHD IPS, Core i5-720...",5 reviews
37,Asus ASUSPRO B9440UA-GV0279R Gray,/test-sites/e-commerce/allinone/product/146,/images/test-sites/e-commerce/items/cart2.png,$1381.13,"Asus ASUSPRO B9440UA-GV0279R Gray, 14"" FHD, Co...",4 reviews
38,Asus ROG Strix GL702ZC-GC154T,/test-sites/e-commerce/allinone/product/57,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC154T, 17.3"" FHD, Ryze...",7 reviews

In [68]:
df.to_csv("web_scraper_qa5.4.csv")

### a5.5 Extract all product details of Second column save into csv file.

In [69]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url = "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r = requests.get(main_url)
r.status_code

200

In [72]:
soup = BeautifulSoup(r.text,"html")
products = soup.find_all("div",class_ = "col-md-4 col-xl-4 col-lg-4")[1::3] # finding 1 row products div
products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$321.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$372.7</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$391.48</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/71" itemprop="name" title="Asus VivoBook E502NA-GO022T Dark Blue">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">3</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$409.63</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/74" itemprop="name" title="Lenovo V110-15ISK">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$416.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/31" itemprop="name" title="Packard 255 G2">
 						Packard 255 G2
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$436.29</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/79" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$454.73</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/82" itemprop="name" title="Lenovo V110-15ISK">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$468.56</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/85" itemprop="name" title="Asus VivoBook 15 X540UA-DM260 Chocolate Black">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">1</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$485.9</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/88" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$488.78</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/46" itemprop="name" title="Dell Vostro 15">
 						Dell Vostro 15
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$498.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/93" itemprop="name" title="Lenovo V510 Black">
 						Lenovo V510 Bl...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$577.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/44" itemprop="name" title="HP 350 G1">
 						HP 350 G1
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$679</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/48" itemprop="name" title="Acer Aspire A515-51-5654">
 						Acer Aspire A5...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$739.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/34" itemprop="name" title="ProBook">
 						ProBook
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">

In [73]:
dl = []
for product in products:
    
    data = {
        "product_name" : "",
        "product_link" : "",
        "product_img" : "",
        "product_price" : "",
        "product_details" : "",
        "product_reviews_number" : "",
    # "product_reviews_star_number" : ""
    }
    
    data["product_link"] = product.find("a")["href"] # product url

    base_url = "https://webscraper.io"
    act_url = base_url + data["product_link"]
    req = requests.get(act_url)
    soup_nw = BeautifulSoup(req.text , "html.parser")
    data["product_name"] = soup_nw.find("h4" , class_ = "title card-title" ).text

    data["product_img"] = product.find("img")["src"].strip() # img 
    data["product_price"] = product.find("span").text # price
    data["product_details"] = product.find("p" , class_ = "description card-text").text
    data["product_reviews_number"] = product.find("p" , class_ = "review-count float-end").text.strip()
    dl.append(data)

dl

[{'product_name': 'Prestigio SmartBook 133S Dark Grey',
  'product_link': '/test-sites/e-commerce/allinone/product/61',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Lenovo V110-15IAP',
  'product_link': '/test-sites/e-commerce/allinone/product/63',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$321.94',
  'product_details': 'Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '5 reviews'},
 {'product_name': 'Acer Aspire 3 A315-31 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/66',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$372.7',
  'product_details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Acer Aspire 3 A315-31 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/69',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$391.48',
  'product_details': 'Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Asus VivoBook E502NA-GO022T Dark Blue',
  'product_link': '/test-sites/e-commerce/allinone/product/71',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$399.99',
  'product_details': 'Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd',
  'product_reviews_number': '3 reviews'},
 {'product_name': 'Lenovo V110-15ISK',
  'product_link': '/test-sites/e-commerce/allinone/product/74',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$409.63',
  'product_details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 8GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Packard 255 G2',
  'product_link': '/test-sites/e-commerce/allinone/product/31',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$416.99',
  'product_details': '15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/79',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$436.29',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 500GB, Windows 10 Home',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Lenovo V110-15ISK',
  'product_link': '/test-sites/e-commerce/allinone/product/82',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$454.73',
  'product_details': 'Lenovo V110-15ISK, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Pro',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Asus VivoBook 15 X540UA-DM260 Chocolate Black',
  'product_link': '/test-sites/e-commerce/allinone/product/85',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$468.56',
  'product_details': 'Asus VivoBook 15 X540UA-DM260 Chocolate Black, 15.6" FHD, Core i3-6006U, 4GB, 256GB SSD, Endless OS, En kbd',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/88',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$485.9',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i5-7200U, 4GB, 128GB SSD, Linux',
  'product_reviews_number': '6 reviews'},
 {'product_name': 'Dell Vostro 15',
  'product_link': '/test-sites/e-commerce/allinone/product/46',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$488.78',
  'product_details': 'Dell Vostro 15 (3568) Black, 15.6" FHD, Core i5-7200U, 4GB, 128GB SSD, Radeon R5 M420 2GB, Linux',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Lenovo V510 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/93',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$498.23',
  'product_details': 'Lenovo V510 Black, 15.6" FHD, Core i3-7100U, 4GB, 128GB SSD, Windows 10 Pro',
  'product_reviews_number': '5 reviews'},
 {'product_name': 'HP 350 G1',
  'product_link': '/test-sites/e-commerce/allinone/product/44',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$577.99',
  'product_details': '15.6", Core i5-4200U, 4GB, 750GB, Radeon HD8670M 2GB, Windows',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Acer Aspire A515-51-5654',
  'product_link': '/test-sites/e-commerce/allinone/product/48',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$679',
  'product_details': 'Acer Aspire A515-51-5654, Black, 15.6", FHD, Core i5-8250U, 8GB DDR4, 256GB SSD, Windows 10 Home, ENG',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'ProBook',
  'product_link': '/test-sites/e-commerce/allinone/product/34',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$739.99',
  'product_details': '14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Acer Nitro 5 AN515-51',
  'product_link': '/test-sites/e-commerce/allinone/product/52',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$809',
  'product_details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, Windows 10 Home',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'ThinkPad Yoga',
  'product_link': '/test-sites/e-commerce/allinone/product/37',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1033.99',
  'product_details': '12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,',
  'product_reviews_number': '13 reviews'},
 {'product_name': 'MSI GL72M 7RDX',
  'product_link': '/test-sites/e-commerce/allinone/product/96',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1099',
  'product_details': 'MSI GL72M 7RDX, 17.3" FHD, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Dell Latitude 5280',
  'product_link': '/test-sites/e-commerce/allinone/product/99',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1102.66',
  'product_details': 'Dell Latitude 5280, 12.5" HD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Toshiba Portege Z30-C-16J Grey',
  'product_link': '/test-sites/e-commerce/allinone/product/102',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1114.55',
  'product_details': 'Toshiba Portege Z30-C-16J Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'Dell Inspiron 17 2in1 (7779) Silver',
  'product_link': '/test-sites/e-commerce/allinone/product/105',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1124.2',
  'product_details': 'Dell Inspiron 17 2in1 (7779) Silver, 17.3" FHD Touch, Core i5-7200U, 12GB, 1TB, GeForce GT940MX 2GB, Windows 10 Home',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Asus AsusPro Advanced BU401LA-FA271G Dark Grey',
  'product_link': '/test-sites/e-commerce/allinone/product/108',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1139.54',
  'product_details': 'Asus AsusPro Advanced BU401LA-FA271G Dark Grey, 14", Core i5-4210U, 4GB, 128GB SSD, Win7 Pro 64bit, ENG',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Dell Inspiron 15 (7567) Black',
  'product_link': '/test-sites/e-commerce/allinone/product/111',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1144.2',
  'product_details': 'Dell Inspiron 15 (7567) Black, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB, GeForce GTX 1050 Ti 4GB, Linux + Windows 10 Home',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'MSI GP62M 7RDX Leopard',
  'product_link': '/test-sites/e-commerce/allinone/product/113',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1149',
  'product_details': 'MSI GP62M 7RDX Leopard, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'product_reviews_number': '11 reviews'},
 {'product_name': 'Acer TravelMate P645-S-511A Black',
  'product_link': '/test-sites/e-commerce/allinone/product/116',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1170.1',
  'product_details': 'Acer TravelMate P645-S-511A Black, 14" FHD IPS, Core i5-5200U, 8GB, 256GB SSD, 3G, Windows 10 Pro',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'MSI GS63 7RD Stealth',
  'product_link': '/test-sites/e-commerce/allinone/product/118',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1179',
  'product_details': 'MSI GS63 7RD Stealth, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, DOS + Windows 10 Home',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'MSI GL62M 7REX',
  'product_link': '/test-sites/e-commerce/allinone/product/121',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1199',
  'product_details': 'MSI GL62M 7REX, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Toshiba Portege X30-D-10J Black/Blue',
  'product_link': '/test-sites/e-commerce/allinone/product/124',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1203.41',
  'product_details': 'Toshiba Portege X30-D-10J Black/Blue, 13.3" FHD IPS, Core i5-7200U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '13 reviews'},
 {'product_name': 'ThinkPad Yoga',
  'product_link': '/test-sites/e-commerce/allinone/product/43',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1223.99',
  'product_details': '12.5" Touch, Core i5 4200U, 8GB, 500GB + 16GB SSD Cache, Windows',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Asus ZenBook UX530UX-FY040T Blue',
  'product_link': '/test-sites/e-commerce/allinone/product/129',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1239.2',
  'product_details': 'Asus ZenBook UX530UX-FY040T Blue, 15.6" FHD, Core i7-7500U, 8GB, 512GB SSD, GeForce GTX950M 2GB, Windows 10 Home, Eng kbd',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Apple MacBook Air 13"',
  'product_link': '/test-sites/e-commerce/allinone/product/131',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1260.13',
  'product_details': 'Apple MacBook Air 13", i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, ENG',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Dell XPS 13',
  'product_link': '/test-sites/e-commerce/allinone/product/40',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1281.99',
  'product_details': '13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Dell Latitude 5480',
  'product_link': '/test-sites/e-commerce/allinone/product/136',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1310.39',
  'product_details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Apple MacBook Pro 13" Space Gray',
  'product_link': '/test-sites/e-commerce/allinone/product/138',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1333',
  'product_details': 'Apple MacBook Pro 13" Space Gray, Core i5 2.3GHz, 8GB, 128GB SSD, Iris Plus 640, ENG',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'Dell Latitude 5580',
  'product_link': '/test-sites/e-commerce/allinone/product/141',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1341.22',
  'product_details': 'Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 16GB, 256GB SSD, GeForce GT930MX, Linux',
  'product_reviews_number': '3 reviews'},
 {'product_name': 'Lenovo ThinkPad Yoga 370 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/144',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1362.24',
  'product_details': 'Lenovo ThinkPad Yoga 370 Black, 13.3" FHD IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Lenovo Legion Y720',
  'product_link': '/test-sites/e-commerce/allinone/product/56',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1399',
  'product_details': 'Lenovo Legion Y720, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 128GB SSD + 2TB HDD, GeForce GTX 1060 6GB, DOS, RGB backlit keyboard',
  'product_reviews_number': '8 reviews'},
 {'product_name': 'Asus ROG Strix GL702ZC-GC209T',
  'product_link': '/test-sites/e-commerce/allinone/product/58',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1769',
  'product_details': 'Asus ROG Strix GL702ZC-GC209T, 17.3" FHD IPS, Ryzen 7 1700, 16GB, 256GB SSD + 1TB HDD, Radeon RX 580 4GB, Windows 10 Home',
  'product_reviews_number': '8 reviews'}]

In [74]:
df = pd.DataFrame(dl)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number
0,Prestigio SmartBook 133S Dark Grey,/test-sites/e-commerce/allinone/product/61,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Dark Grey, 13.3"" FHD ...",8 reviews
1,Lenovo V110-15IAP,/test-sites/e-commerce/allinone/product/63,/images/test-sites/e-commerce/items/cart2.png,$321.94,"Lenovo V110-15IAP, 15.6"" HD, Celeron N3350 1.1...",5 reviews
2,Acer Aspire 3 A315-31 Black,/test-sites/e-commerce/allinone/product/66,/images/test-sites/e-commerce/items/cart2.png,$372.7,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Celeron...",2 reviews
3,Acer Aspire 3 A315-31 Black,/test-sites/e-commerce/allinone/product/69,/images/test-sites/e-commerce/items/cart2.png,$391.48,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",10 reviews
4,Asus VivoBook E502NA-GO022T Dark Blue,/test-sites/e-commerce/allinone/product/71,/images/test-sites/e-commerce/items/cart2.png,$399.99,"Asus VivoBook E502NA-GO022T Dark Blue, 15.6"" H...",3 reviews
5,Lenovo V110-15ISK,/test-sites/e-commerce/allinone/product/74,/images/test-sites/e-commerce/items/cart2.png,$409.63,"Lenovo V110-15ISK, 15.6"" HD, Core i3-6006U, 8G...",9 reviews
6,Packard 255 G2,/test-sites/e-commerce/allinone/product/31,/images/test-sites/e-commerce/items/cart2.png,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2 reviews
7,Acer Aspire ES1-572 Black,/test-sites/e-commerce/allinone/product/79,/images/test-sites/e-commerce/items/cart2.png,$436.29,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",2 reviews
8,Lenovo V110-15ISK,/test-sites/e-commerce/allinone/product/82,/images/test-sites/e-commerce/items/cart2.png,$454.73,"Lenovo V110-15ISK, 15.6"" HD, Core i3-6006U, 4G...",2 reviews
9,Asus VivoBook 15 X540UA-DM260 Chocolate Black,/test-sites/e-commerce/allinone/product/85,/images/test-sites/e-commerce/items/cart2.png,$468.56,"Asus VivoBook 15 X540UA-DM260 Chocolate Black,...",1 reviews
10,Acer Aspire ES1-572 Black,/test-sites/e-commerce/allinone/product/88,/images/test-sites/e-commerce/items/cart2.png,$485.9,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i5-7...",6 reviews
11,Dell Vostro 15,/test-sites/e-commerce/allinone/product/46,/images/test-sites/e-commerce/items/cart2.png,$488.78,"Dell Vostro 15 (3568) Black, 15.6"" FHD, Core i...",14 reviews
12,Lenovo V510 Black,/test-sites/e-commerce/allinone/product/93,/images/test-sites/e-commerce/items/cart2.png,$498.23,"Lenovo V510 Black, 15.6"" FHD, Core i3-7100U, 4...",5 reviews
13,HP 350 G1,/test-sites/e-commerce/allinone/product/44,/images/test-sites/e-commerce/items/cart2.png,$577.99,"15.6"", Core i5-4200U, 4GB, 750GB, Radeon HD867...",10 reviews
14,Acer Aspire A515-51-5654,/test-sites/e-commerce/allinone/product/48,/images/test-sites/e-commerce/items/cart2.png,$679,"Acer Aspire A515-51-5654, Black, 15.6"", FHD, C...",9 reviews
15,ProBook,/test-sites/e-commerce/allinone/product/34,/images/test-sites/e-commerce/items/cart2.png,$739.99,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",8 reviews
16,Acer Nitro 5 AN515-51,/test-sites/e-commerce/allinone/product/52,/images/test-sites/e-commerce/items/cart2.png,$809,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i5-...",0 reviews
17,ThinkPad Yoga,/test-sites/e-commerce/allinone/product/37,/images/test-sites/e-commerce/items/cart2.png,$1033.99,"12.5"" Touch, Core i3-4010U, 4GB, 500GB + 16GB ...",13 reviews
18,MSI GL72M 7RDX,/test-sites/e-commerce/allinone/product/96,/images/test-sites/e-commerce/items/cart2.png,$1099,"MSI GL72M 7RDX, 17.3"" FHD, Core i5-7300HQ, 8GB...",1 reviews
19,Dell Latitude 5280,/test-sites/e-commerce/allinone/product/99,/images/test-sites/e-commerce/items/cart2.png,$1102.66,"Dell Latitude 5280, 12.5"" HD, Core i5-7300U, 8...",8 reviews
20,Toshiba Portege Z30-C-16J Grey,/test-sites/e-commerce/allinone/product/102,/images/test-sites/e-commerce/items/cart2.png,$1114.55,"Toshiba Portege Z30-C-16J Grey, 13.3"" FHD, Cor...",0 reviews
21,Dell Inspiron 17 2in1 (7779) Silver,/test-sites/e-commerce/allinone/product/105,/images/test-sites/e-commerce/items/cart2.png,$1124.2,"Dell Inspiron 17 2in1 (7779) Silver, 17.3"" FHD...",10 reviews
22,Asus AsusPro Advanced BU401LA-FA271G Dark Grey,/test-sites/e-commerce/allinone/product/108,/images/test-sites/e-commerce/items/cart2.png,$1139.54,Asus AsusPro Advanced BU401LA-FA271G Dark Grey...,7 reviews
23,Dell Inspiron 15 (7567) Black,/test-sites/e-commerce/allinone/product/111,/images/test-sites/e-commerce/items/cart2.png,$1144.2,"Dell Inspiron 15 (7567) Black, 15.6"" FHD, Core...",2 reviews
24,MSI GP62M 7RDX Leopard,/test-sites/e-commerce/allinone/product/113,/images/test-sites/e-commerce/items/cart2.png,$1149,"MSI GP62M 7RDX Leopard, 15.6"" FHD, Core i7-770...",11 reviews
25,Acer TravelMate P645-S-511A Black,/test-sites/e-commerce/allinone/product/116,/images/test-sites/e-commerce/items/cart2.png,$1170.1,"Acer TravelMate P645-S-511A Black, 14"" FHD IPS...",0 reviews
26,MSI GS63 7RD Stealth,/test-sites/e-commerce/allinone/product/118,/images/test-sites/e-commerce/items/cart2.png,$1179,"MSI GS63 7RD Stealth, 15.6"" FHD IPS, Core i7-7...",2 reviews
27,MSI GL62M 7REX,/test-sites/e-commerce/allinone/product/121,/images/test-sites/e-commerce/items/cart2.png,$1199,"MSI GL62M 7REX, 15.6"" FHD, Core i7-7700HQ, 8GB...",7 reviews
28,Toshiba Portege X30-D-10J Black/Blue,/test-sites/e-commerce/allinone/product/124,/images/test-sites/e-commerce/items/cart2.png,$1203.41,"Toshiba Portege X30-D-10J Black/Blue, 13.3"" FH...",13 reviews
29,ThinkPad Yoga,/test-sites/e-commerce/allinone/product/43,/images/test-sites/e-commerce/items/cart2.png,$1223.99,"12.5"" Touch, Core i5 4200U, 8GB, 500GB + 16GB ...",2 reviews
30,Asus ZenBook UX530UX-FY040T Blue,/test-sites/e-commerce/allinone/product/129,/images/test-sites/e-commerce/items/cart2.png,$1239.2,"Asus ZenBook UX530UX-FY040T Blue, 15.6"" FHD, C...",14 reviews
31,"Apple MacBook Air 13""",/test-sites/e-commerce/allinone/product/131,/images/test-sites/e-commerce/items/cart2.png,$1260.13,"Apple MacBook Air 13"", i5 1.8GHz, 8GB, 256GB S...",8 reviews
32,Dell XPS 13,/test-sites/e-commerce/allinone/product/40,/images/test-sites/e-commerce/items/cart2.png,$1281.99,"13.3"" Touch, Core i5-4210U, 8GB, 128GB SSD, Wi...",4 reviews
33,Dell Latitude 5480,/test-sites/e-commerce/allinone/product/136,/images/test-sites/e-commerce/items/cart2.png,$1310.39,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",8 reviews
34,"Apple MacBook Pro 13"" Space Gray",/test-sites/e-commerce/allinone/product/138,/images/test-sites/e-commerce/items/cart2.png,$1333,"Apple MacBook Pro 13"" Space Gray, Core i5 2.3G...",0 reviews
35,Dell Latitude 5580,/test-sites/e-commerce/allinone/product/141,/images/test-sites/e-commerce/items/cart2.png,$1341.22,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",3 reviews
36,Lenovo ThinkPad Yoga 370 Black,/test-sites/e-commerce/allinone/product/144,/images/test-sites/e-commerce/items/cart2.png,$1362.24,"Lenovo ThinkPad Yoga 370 Black, 13.3"" FHD IPS ...",12 reviews
37,Lenovo Legion Y720,/test-sites/e-commerce/allinone/product/56,/images/test-sites/e-commerce/items/cart2.png,$1399,"Lenovo Legion Y720, 15.6"" FHD IPS, Core i7-770...",8 reviews
38,Asus ROG Strix GL702ZC-GC209T,/test-sites/e-commerce/allinone/product/58,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC209T, 17.3"" FHD IPS, ...",8 reviews

In [75]:
df.to_csv("web_scraper_qa5.5.csv")

### a5.6 Extract all product details of thirst column save into csv file.

In [76]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_url = "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"
r = requests.get(main_url)
r.status_code

200

In [77]:
soup = BeautifulSoup(r.text,"html")
products = soup.find_all("div",class_ = "col-md-4 col-xl-4 col-lg-4")[2::3] # finding 1 row products div
products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$356.49</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$393.88</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/70" itemprop="name" title="Acer Aspire 3 A315-21">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$404.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/72" itemprop="name" title="Lenovo ThinkPad E31-80">
 						Lenovo ThinkPa...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$410.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/75" itemprop="name" title="Acer Aspire ES1-732 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$433.3</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/77" itemprop="name" title="Asus EeeBook R416NA-FA014T">
 						Asus EeeBook R...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">1</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$439.73</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/80" itemprop="name" title="Acer Extensa 15 (2540) Black">
 						Acer Extensa 1...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$457.38</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/83" itemprop="name" title="Acer Aspire A315-51-33TG">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$469.1</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/86" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$487.8</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/89" itemprop="name" title="Lenovo V510 Black">
 						Lenovo V510 Bl...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$494.71</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/91" itemprop="name" title="Acer Aspire 3 A315-51 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$520.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/42" itemprop="name" title="HP 250 G3">
 						HP 250 G3
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">13</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$581.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/36" itemprop="name" title="Aspire E1-572G">
 						Aspire E1-572G
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$679</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/49" itemprop="name" title="Dell Inspiron 15">
 						Dell Inspiron...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">7</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$745.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/39" itemprop="name" title="Inspiron 15">
 						Inspiron 15
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>

In [78]:
dl = []
for product in products:
    
    data = {
        "product_name" : "",
        "product_link" : "",
        "product_img" : "",
        "product_price" : "",
        "product_details" : "",
        "product_reviews_number" : "",
    # "product_reviews_star_number" : ""
    }
    
    data["product_link"] = product.find("a")["href"] # product url

    base_url = "https://webscraper.io"
    act_url = base_url + data["product_link"]
    req = requests.get(act_url)
    soup_nw = BeautifulSoup(req.text , "html.parser")
    data["product_name"] = soup_nw.find("h4" , class_ = "title card-title" ).text

    data["product_img"] = product.find("img")["src"].strip() # img 
    data["product_price"] = product.find("span").text # price
    data["product_details"] = product.find("p" , class_ = "description card-text").text
    data["product_reviews_number"] = product.find("p" , class_ = "review-count float-end").text.strip()
    dl.append(data)

dl

[{'product_name': 'Prestigio SmartBook 133S Gold',
  'product_link': '/test-sites/e-commerce/allinone/product/62',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$299',
  'product_details': 'Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Lenovo V110-15IAP',
  'product_link': '/test-sites/e-commerce/allinone/product/64',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$356.49',
  'product_details': 'Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd',
  'product_reviews_number': '6 reviews'},
 {'product_name': 'Acer Aspire A315-31-C33J',
  'product_link': '/test-sites/e-commerce/allinone/product/67',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$379.94',
  'product_details': 'Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'Acer Aspire 3 A315-21',
  'product_link': '/test-sites/e-commerce/allinone/product/70',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$393.88',
  'product_details': 'Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Lenovo ThinkPad E31-80',
  'product_link': '/test-sites/e-commerce/allinone/product/72',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$404.23',
  'product_details': 'Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Acer Aspire ES1-732 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/75',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$410.46',
  'product_details': 'Acer Aspire ES1-732 Black, 17.3" HD+, Celeron, N3350, 4GB, 1TB, Windows 10 Home',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Asus EeeBook R416NA-FA014T',
  'product_link': '/test-sites/e-commerce/allinone/product/77',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$433.3',
  'product_details': 'Asus EeeBook R416NA-FA014T, 14" FHD, Pentium N4200, 4GB, 128GB eMMC, Windows 10 Home, Eng kbd',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Acer Extensa 15 (2540) Black',
  'product_link': '/test-sites/e-commerce/allinone/product/80',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$439.73',
  'product_details': 'Acer Extensa 15 (2540) Black, 15.6" HD, Core i5-7200U, 4GB, 500GB, Linux',
  'product_reviews_number': '6 reviews'},
 {'product_name': 'Acer Aspire A315-51-33TG',
  'product_link': '/test-sites/e-commerce/allinone/product/83',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$457.38',
  'product_details': 'Acer Aspire A315-51-33TG, Black 15.6" HD, Core i3-7100U, 4GB DDR4, 128GB SSD, Windows 10 Home, ENG',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Acer Aspire ES1-572 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/86',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$469.1',
  'product_details': 'Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '5 reviews'},
 {'product_name': 'Lenovo V510 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/89',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$487.8',
  'product_details': 'Lenovo V510 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Windows 10 Home',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Acer Aspire 3 A315-51 Black',
  'product_link': '/test-sites/e-commerce/allinone/product/91',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$494.71',
  'product_details': 'Acer Aspire 3 A315-51 Black, 15.6" FHD, Core i3-7100U, 4GB, 500GB + 128GB SSD, Windows 10 Home',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'HP 250 G3',
  'product_link': '/test-sites/e-commerce/allinone/product/42',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$520.99',
  'product_details': '15.6", Core\xa0i5-4210U, 4GB, 500GB, Windows 8.1',
  'product_reviews_number': '13 reviews'},
 {'product_name': 'Aspire E1-572G',
  'product_link': '/test-sites/e-commerce/allinone/product/36',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$581.99',
  'product_details': '15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1',
  'product_reviews_number': '2 reviews'},
 {'product_name': 'Dell Inspiron 15',
  'product_link': '/test-sites/e-commerce/allinone/product/49',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$679',
  'product_details': 'Dell Inspiron 15 (5567) Fog Gray, 15.6" FHD, Core i5-7200U, 8GB, 1TB, Radeon R7 M445 4GB, Linux',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Inspiron 15',
  'product_link': '/test-sites/e-commerce/allinone/product/39',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$745.99',
  'product_details': 'Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Asus ROG STRIX GL553VD-DM256',
  'product_link': '/test-sites/e-commerce/allinone/product/53',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$899',
  'product_details': 'Asus ROG STRIX GL553VD-DM256, 15.6" FHD, Core i5-7300HQ, 8GB, 1TB, GeForce GTX 1050 2GB, No OS + Windows 10 Home',
  'product_reviews_number': '7 reviews'},
 {'product_name': 'Lenovo ThinkPad L460',
  'product_link': '/test-sites/e-commerce/allinone/product/94',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1096.02',
  'product_details': 'Lenovo ThinkPad L460, 14" FHD IPS, Core i7-6600U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'MSI GL72M 7RDX',
  'product_link': '/test-sites/e-commerce/allinone/product/97',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1099',
  'product_details': 'Asus ROG Strix GL553VD-DM535T, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 2GB, Windows 10 Home, Eng kbd',
  'product_reviews_number': '9 reviews'},
 {'product_name': 'Dell Latitude 5480',
  'product_link': '/test-sites/e-commerce/allinone/product/100',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1110.14',
  'product_details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Linux + Windows 10 Home',
  'product_reviews_number': '4 reviews'},
 {'product_name': 'Acer Predator Helios 300 (PH317-51)',
  'product_link': '/test-sites/e-commerce/allinone/product/103',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1123.87',
  'product_details': 'Acer Predator Helios 300 (PH317-51), 17.3" FHD IPS, Core i5-7300HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050Ti 4GB, Windows 10 Home',
  'product_reviews_number': '1 reviews'},
 {'product_name': 'Dell Latitude 5480',
  'product_link': '/test-sites/e-commerce/allinone/product/106',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1133.82',
  'product_details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 500GB, Windows 10 Pro',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Acer Nitro 5 AN515-51',
  'product_link': '/test-sites/e-commerce/allinone/product/109',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1140.62',
  'product_details': 'Acer Nitro 5 AN515-51, 15.6" FHD IPS, Core i7-7700HQ, 8GB, 256GB SSD +1TB, GeForce GTX 1050 Ti 4GB, Windows 10 Home + Windows 10 Home',
  'product_reviews_number': '14 reviews'},
 {'product_name': 'Dell Latitude 5580',
  'product_link': '/test-sites/e-commerce/allinone/product/112',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1144.4',
  'product_details': 'Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Lenovo Yoga 720 Grey',
  'product_link': '/test-sites/e-commerce/allinone/product/114',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1149.73',
  'product_details': 'Lenovo Yoga 720 Grey, 15.6" FHD IPS, Core i5-7300HQ, 8GB, 256GB SSD, GeForce GTX 1050 2GB, Windows 10 Home',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Dell Latitude 5580',
  'product_link': '/test-sites/e-commerce/allinone/product/117',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1178.19',
  'product_details': 'Dell Latitude 5580, 15.6" FHD, Core i5-7300U, 16GB, 256GB SSD, Linux + Windows 10 Home',
  'product_reviews_number': '6 reviews'},
 {'product_name': 'Dell Latitude 5480',
  'product_link': '/test-sites/e-commerce/allinone/product/119',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1187.88',
  'product_details': 'Dell Latitude 5480, 14" FHD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro',
  'product_reviews_number': '5 reviews'},
 {'product_name': 'MSI GL62M 7REX2',
  'product_link': '/test-sites/e-commerce/allinone/product/122',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1199',
  'product_details': 'MSI GL62M 7REX2, 15.6" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1050 Ti 2GB, Windows 10 Home',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Lenovo IdeaPad Miix 510 Platinum Silver',
  'product_link': '/test-sites/e-commerce/allinone/product/125',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1212.16',
  'product_details': 'Lenovo IdeaPad Miix 510 Platinum Silver, 12.2" IPS Touch, Core i5-7200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
  'product_reviews_number': '0 reviews'},
 {'product_name': 'Asus VivoBook Pro 15 N580VN-FI006T Gold Metal',
  'product_link': '/test-sites/e-commerce/allinone/product/127',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1235.49',
  'product_details': 'Asus VivoBook Pro 15 N580VN-FI006T Gold Metal, 15.6" UHD, Core i7-7700HQ, 16GB, 1TB + 256GB SSD, GeForce MX150 2GB, Windows 10 Home, Eng kbd',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'ThinkPad X230',
  'product_link': '/test-sites/e-commerce/allinone/product/41',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1244.99',
  'product_details': '12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Dell Latitude 5480',
  'product_link': '/test-sites/e-commerce/allinone/product/132',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1271.06',
  'product_details': 'Dell Latitude 5480, 14" FHD, Core i7-7600U, 8GB, 1TB, GeForce GT930MX, Windows 10 Pro',
  'product_reviews_number': '13 reviews'},
 {'product_name': 'Toshiba Portege Z30-C-16K Grey',
  'product_link': '/test-sites/e-commerce/allinone/product/134',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1294.74',
  'product_details': 'Toshiba Portege Z30-C-16K Grey, 13.3" FHD, Core i5-6200U, 8GB, 256GB SSD, 4G, Windows 10 Pro',
  'product_reviews_number': '6 reviews'},
 {'product_name': 'ThinkPad X240',
  'product_link': '/test-sites/e-commerce/allinone/product/35',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1311.99',
  'product_details': '12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit',
  'product_reviews_number': '12 reviews'},
 {'product_name': 'Dell Latitude 5580',
  'product_link': '/test-sites/e-commerce/allinone/product/139',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1337.28',
  'product_details': 'Dell Latitude 5580, 15.6" FHD, Core i7-7600U, 8GB, 256GB SSD, GeForce GT930MX, Windows 10 Pro',
  'product_reviews_number': '6 reviews'},
 {'product_name': 'Apple MacBook Air 13"',
  'product_link': '/test-sites/e-commerce/allinone/product/142',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1347.78',
  'product_details': 'Apple MacBook Air 13", Intel Core i5 1.8GHz, 8GB, 256GB SSD, Intel HD 6000, RUS',
  'product_reviews_number': '11 reviews'},
 {'product_name': 'Toshiba Portege X20W-D-10V Black/Blue',
  'product_link': '/test-sites/e-commerce/allinone/product/145',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1366.32',
  'product_details': 'Toshiba Portege X20W-D-10V Black/Blue, 12.5" FHD Touch, Core i7-7500U, 8GB, 512GB SSD, Windows 10 Pro',
  'product_reviews_number': '11 reviews'},
 {'product_name': 'Asus ROG Strix GL702VM-GC146T',
  'product_link': '/test-sites/e-commerce/allinone/product/147',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1399',
  'product_details': 'Asus ROG Strix GL702VM-GC146T, 17.3" FHD, Core i7-7700HQ, 8GB, 1TB + 128GB SSD, GeForce GTX 1060 3GB, Windows 10 Home, Eng kbd',
  'product_reviews_number': '10 reviews'},
 {'product_name': 'Asus ROG Strix SCAR Edition GL503VM-ED115T',
  'product_link': '/test-sites/e-commerce/allinone/product/59',
  'product_img': '/images/test-sites/e-commerce/items/cart2.png',
  'product_price': '$1799',
  'product_details': 'Asus ROG Strix SCAR Edition GL503VM-ED115T, 15.6" FHD 120Hz, Core i7-7700HQ, 16GB, 256GB SSD + 1TB SSHD, GeForce GTX 1060 6GB, Windows 10 Home',
  'product_reviews_number': '8 reviews'}]

In [79]:
df = pd.DataFrame(dl)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number
0,Prestigio SmartBook 133S Gold,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews
1,Lenovo V110-15IAP,/test-sites/e-commerce/allinone/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,6 reviews
2,Acer Aspire A315-31-C33J,/test-sites/e-commerce/allinone/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",0 reviews
3,Acer Aspire 3 A315-21,/test-sites/e-commerce/allinone/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",9 reviews
4,Lenovo ThinkPad E31-80,/test-sites/e-commerce/allinone/product/72,/images/test-sites/e-commerce/items/cart2.png,$404.23,"Lenovo ThinkPad E31-80, 13.3"" HD, Celeron 3855...",12 reviews
5,Acer Aspire ES1-732 Black,/test-sites/e-commerce/allinone/product/75,/images/test-sites/e-commerce/items/cart2.png,$410.46,"Acer Aspire ES1-732 Black, 17.3"" HD+, Celeron,...",14 reviews
6,Asus EeeBook R416NA-FA014T,/test-sites/e-commerce/allinone/product/77,/images/test-sites/e-commerce/items/cart2.png,$433.3,"Asus EeeBook R416NA-FA014T, 14"" FHD, Pentium N...",1 reviews
7,Acer Extensa 15 (2540) Black,/test-sites/e-commerce/allinone/product/80,/images/test-sites/e-commerce/items/cart2.png,$439.73,"Acer Extensa 15 (2540) Black, 15.6"" HD, Core i...",6 reviews
8,Acer Aspire A315-51-33TG,/test-sites/e-commerce/allinone/product/83,/images/test-sites/e-commerce/items/cart2.png,$457.38,"Acer Aspire A315-51-33TG, Black 15.6"" HD, Core...",9 reviews
9,Acer Aspire ES1-572 Black,/test-sites/e-commerce/allinone/product/86,/images/test-sites/e-commerce/items/cart2.png,$469.1,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",5 reviews
10,Lenovo V510 Black,/test-sites/e-commerce/allinone/product/89,/images/test-sites/e-commerce/items/cart2.png,$487.8,"Lenovo V510 Black, 15.6"" HD, Core i3-6006U, 4G...",9 reviews
11,Acer Aspire 3 A315-51 Black,/test-sites/e-commerce/allinone/product/91,/images/test-sites/e-commerce/items/cart2.png,$494.71,"Acer Aspire 3 A315-51 Black, 15.6"" FHD, Core i...",2 reviews
12,HP 250 G3,/test-sites/e-commerce/allinone/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews
13,Aspire E1-572G,/test-sites/e-commerce/allinone/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews
14,Dell Inspiron 15,/test-sites/e-commerce/allinone/product/49,/images/test-sites/e-commerce/items/cart2.png,$679,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",7 reviews
15,Inspiron 15,/test-sites/e-commerce/allinone/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews
16,Asus ROG STRIX GL553VD-DM256,/test-sites/e-commerce/allinone/product/53,/images/test-sites/e-commerce/items/cart2.png,$899,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews
17,Lenovo ThinkPad L460,/test-sites/e-commerce/allinone/product/94,/images/test-sites/e-commerce/items/cart2.png,$1096.02,"Lenovo ThinkPad L460, 14"" FHD IPS, Core i7-660...",14 reviews
18,MSI GL72M 7RDX,/test-sites/e-commerce/allinone/product/97,/images/test-sites/e-commerce/items/cart2.png,$1099,"Asus ROG Strix GL553VD-DM535T, 15.6"" FHD, Core...",9 reviews
19,Dell Latitude 5480,/test-sites/e-commerce/allinone/product/100,/images/test-sites/e-commerce/items/cart2.png,$1110.14,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",4 reviews
20,Acer Predator Helios 300 (PH317-51),/test-sites/e-commerce/allinone/product/103,/images/test-sites/e-commerce/items/cart2.png,$1123.87,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",1 reviews
21,Dell Latitude 5480,/test-sites/e-commerce/allinone/product/106,/images/test-sites/e-commerce/items/cart2.png,$1133.82,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",14 reviews
22,Acer Nitro 5 AN515-51,/test-sites/e-commerce/allinone/product/109,/images/test-sites/e-commerce/items/cart2.png,$1140.62,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i7-...",14 reviews
23,Dell Latitude 5580,/test-sites/e-commerce/allinone/product/112,/images/test-sites/e-commerce/items/cart2.png,$1144.4,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",10 reviews
24,Lenovo Yoga 720 Grey,/test-sites/e-commerce/allinone/product/114,/images/test-sites/e-commerce/items/cart2.png,$1149.73,"Lenovo Yoga 720 Grey, 15.6"" FHD IPS, Core i5-7...",12 reviews
25,Dell Latitude 5580,/test-sites/e-commerce/allinone/product/117,/images/test-sites/e-commerce/items/cart2.png,$1178.19,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",6 reviews
26,Dell Latitude 5480,/test-sites/e-commerce/allinone/product/119,/images/test-sites/e-commerce/items/cart2.png,$1187.88,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",5 reviews
27,MSI GL62M 7REX2,/test-sites/e-commerce/allinone/product/122,/images/test-sites/e-commerce/items/cart2.png,$1199,"MSI GL62M 7REX2, 15.6"" FHD, Core i7-7700HQ, 8G...",12 reviews
28,Lenovo IdeaPad Miix 510 Platinum Silver,/test-sites/e-commerce/allinone/product/125,/images/test-sites/e-commerce/items/cart2.png,$1212.16,"Lenovo IdeaPad Miix 510 Platinum Silver, 12.2""...",0 reviews
29,Asus VivoBook Pro 15 N580VN-FI006T Gold Metal,/test-sites/e-commerce/allinone/product/127,/images/test-sites/e-commerce/items/cart2.png,$1235.49,"Asus VivoBook Pro 15 N580VN-FI006T Gold Metal,...",10 reviews
30,ThinkPad X230,/test-sites/e-commerce/allinone/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews
31,Dell Latitude 5480,/test-sites/e-commerce/allinone/product/132,/images/test-sites/e-commerce/items/cart2.png,$1271.06,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",13 reviews
32,Toshiba Portege Z30-C-16K Grey,/test-sites/e-commerce/allinone/product/134,/images/test-sites/e-commerce/items/cart2.png,$1294.74,"Toshiba Portege Z30-C-16K Grey, 13.3"" FHD, Cor...",6 reviews
33,ThinkPad X240,/test-sites/e-commerce/allinone/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews
34,Dell Latitude 5580,/test-sites/e-commerce/allinone/product/139,/images/test-sites/e-commerce/items/cart2.png,$1337.28,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",6 reviews
35,"Apple MacBook Air 13""",/test-sites/e-commerce/allinone/product/142,/images/test-sites/e-commerce/items/cart2.png,$1347.78,"Apple MacBook Air 13"", Intel Core i5 1.8GHz, 8...",11 reviews
36,Toshiba Portege X20W-D-10V Black/Blue,/test-sites/e-commerce/allinone/product/145,/images/test-sites/e-commerce/items/cart2.png,$1366.32,"Toshiba Portege X20W-D-10V Black/Blue, 12.5"" F...",11 reviews
37,Asus ROG Strix GL702VM-GC146T,/test-sites/e-commerce/allinone/product/147,/images/test-sites/e-commerce/items/cart2.png,$1399,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",10 reviews
38,Asus ROG Strix SCAR Edition GL503VM-ED115T,/test-sites/e-commerce/allinone/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews

In [80]:
df.to_csv("web_scraper_qqa5.6")