# 	3.2 Extract Testudines family details from first row & save into csv file. e.g# Carettochelyidae, Cheloniidae, Chelydridae

## Method 1 (Extractacting detail of inner page via Request library)

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import requests
import time

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/frames/"
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='row')
frm

[<div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg"/>
 <h3 class="family-name">Carettochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Carettochelyidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GreenSeaTurtle-2.jpg/200px-GreenSeaTurtle-2.jpg"/>
 <h3 class="family-name">Cheloniidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Cheloniidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Alligator_snapping_turtle.jpg/200px-Alligator_snapping_turtle.jpg"/>
 <h3 class="family-name">Chelydridae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelydridae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Dermatemydidae.JPG/200px-Dermatemydidae.JPG"/>
 <h3 class="family-name">Dermatemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermatemydidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/LeatherbackTurtle.jpg/200px-LeatherbackTurtle.jpg"/>
 <h3 class="family-name">Dermochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermochelyidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Tortoise1_cepolina.jpg/200px-Tortoise1_cepolina.jpg"/>
 <h3 class="family-name">Emydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Emydidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cuora_amboinensis_kamaroma_j.jpg/200px-Cuora_amboinensis_kamaroma_j.jpg"/>
 <h3 class="family-name">Geoemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Geoemydidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sternotherus_odoratus.jpg/200px-Sternotherus_odoratus.jpg"/>
 <h3 class="family-name">Kinosternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Kinosternidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Zolw_wielkoglowy.jpg/200px-Zolw_wielkoglowy.jpg"/>
 <h3 class="family-name">Platysternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Platysternidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Tortoise.aldabra.750pix.jpg/200px-Tortoise.aldabra.750pix.jpg"/>
 <h3 class="family-name">Testudinidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Testudinidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Apalone_spinifera.jpg/200px-Apalone_spinifera.jpg"/>
 <h3 class="family-name">Trionychidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Trionychidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg/200px-Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg"/>
 <h3 class="family-name">Chelidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Pelomedusa_subrufa.JPG/200px-Pelomedusa_subrufa.JPG"/>
 <h3 class="family-name">Pelomedusidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Pelomedusidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Erymnochelys_madagascariensis.jpg/200px-Erymnochelys_madagascariensis.jpg"/>
 <h3 class="family-name">Podocnemididae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Podocnemididae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-12 text-center text-muted">
                     Lessons and Videos © Hartley Brody 2023
                 </div><!--.col-->
 </div>]

In [2]:
list =[]
for i in frm[0:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['inner_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["inner_url"] # inner url
    headers = {"User-Agent": "Mozilla/5.0"}
    
    resp = requests.get(inner_url, headers=headers)

    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    
    list.append(dict)

In [3]:
df = pd.DataFrame(list)
df

,name,url,img_url,detail,inner_url
0,Carettochelyidae,,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...,https://www.scrapethissite.com//pages/frames/?...
1,Dermatemydidae,,https://upload.wikimedia.org/wikipedia/commons...,The Dermatemydidae family of turtles — more co...,https://www.scrapethissite.com//pages/frames/?...
2,Geoemydidae,,https://upload.wikimedia.org/wikipedia/commons...,The Geoemydidae family of turtles — more commo...,https://www.scrapethissite.com//pages/frames/?...

## Method 2
'''
1. clicking on `Learn More` button and extracting details.
2. Clicking on `Back to all turtles` button.
3. clicking on next div (family/product) `Learn More` button and extracting details.
4. repeat`


'''

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import requests
import time

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/frames/"
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text


# soup = BeautifulSoup(driver.page_source,('html'))
frm = driver.find_elements('xpath',"//div[@class='col-md-4 turtle-family-card']")
len(frm)

14

In [18]:
list =[]
for j in range(3):
    base_url = 'https://www.scrapethissite.com/'
    frm = driver.find_elements('xpath',"//div[@class='col-md-4 turtle-family-card']")
    i  = frm[j]
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url'] = i.find_element("xpath",'img').get_attribute("src")

    dict ['inner_url']=base_url + i.find_element("xpath",'a').get_attribute('href')
    dict ['name']=i.find_element("xpath",'h3').text

    # 1. clicking on `Learn More` button and extracting details.
    i.find_element("xpath","//a[@class='btn btn-default btn-xs']").click()
    time.sleep(2)

    dict["detail"]= driver.find_element("xpath","//p[@class= 'lead']").text
    list.append(dict)

    #2. Clicking on `Back to all turtles` button.
    driver.find_element("xpath","//a[@class='btn btn-default btn-xs']").click()
    time.sleep(8)
    # driver.switch_to.frame(0)

In [19]:
df = pd.DataFrame(list)
df

,name,url,img_url,detail,inner_url
0,Carettochelyidae,,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...,https://www.scrapethissite.com/https://www.scr...
1,Cheloniidae,,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...,https://www.scrapethissite.com/https://www.scr...
2,Chelydridae,,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...,https://www.scrapethissite.com/https://www.scr...

## method 3 (hitting inner url via selenium)

In [14]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import requests
import time

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/frames/"
driver.get(url)
driver.switch_to.frame(0)
driver.find_element("xpath",'//h3').text
soup = BeautifulSoup(driver.page_source,('html'))
frm = soup.find_all('div',class_='row')
frm

[<div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg"/>
 <h3 class="family-name">Carettochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Carettochelyidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/GreenSeaTurtle-2.jpg/200px-GreenSeaTurtle-2.jpg"/>
 <h3 class="family-name">Cheloniidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Cheloniidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Alligator_snapping_turtle.jpg/200px-Alligator_snapping_turtle.jpg"/>
 <h3 class="family-name">Chelydridae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelydridae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Dermatemydidae.JPG/200px-Dermatemydidae.JPG"/>
 <h3 class="family-name">Dermatemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermatemydidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/LeatherbackTurtle.jpg/200px-LeatherbackTurtle.jpg"/>
 <h3 class="family-name">Dermochelyidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Dermochelyidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Tortoise1_cepolina.jpg/200px-Tortoise1_cepolina.jpg"/>
 <h3 class="family-name">Emydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Emydidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cuora_amboinensis_kamaroma_j.jpg/200px-Cuora_amboinensis_kamaroma_j.jpg"/>
 <h3 class="family-name">Geoemydidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Geoemydidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sternotherus_odoratus.jpg/200px-Sternotherus_odoratus.jpg"/>
 <h3 class="family-name">Kinosternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Kinosternidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Zolw_wielkoglowy.jpg/200px-Zolw_wielkoglowy.jpg"/>
 <h3 class="family-name">Platysternidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Platysternidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Tortoise.aldabra.750pix.jpg/200px-Tortoise.aldabra.750pix.jpg"/>
 <h3 class="family-name">Testudinidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Testudinidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Apalone_spinifera.jpg/200px-Apalone_spinifera.jpg"/>
 <h3 class="family-name">Trionychidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Trionychidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg/200px-Eastern_long_neck_tortoise_-_chelodina_longicollis.jpg"/>
 <h3 class="family-name">Chelidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Chelidae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Pelomedusa_subrufa.JPG/200px-Pelomedusa_subrufa.JPG"/>
 <h3 class="family-name">Pelomedusidae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Pelomedusidae">Learn more →</a>
 </div>
 <div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Erymnochelys_madagascariensis.jpg/200px-Erymnochelys_madagascariensis.jpg"/>
 <h3 class="family-name">Podocnemididae</h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Podocnemididae">Learn more →</a>
 </div>
 </div>,
 <div class="row">
 <div class="col-md-12 text-center text-muted">
                     Lessons and Videos © Hartley Brody 2023
                 </div><!--.col-->
 </div>]

In [15]:
list =[]
for i in frm[0:3]:
    base_url = 'https://www.scrapethissite.com/'
    dict = {
        'name':'',
        'url':'',
        'img_url':'',
        "detail":'',
    }
    dict ['img_url']=i.find('img')['src']
    dict ['inner_url']=base_url + i.find('a')['href']
    dict ['name']=i.find('h3').text
    
    inner_url = dict["inner_url"] # inner url
    driver.get(inner_url)
    time.sleep(3)
    dict["detail"]=driver.find_element("xpath",'//p[@class="lead"]').text.strip()# all url details
    list.append(dict)

In [16]:
df = pd.DataFrame(list)
df

,name,url,img_url,detail,inner_url
0,Carettochelyidae,,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...,https://www.scrapethissite.com//pages/frames/?...
1,Dermatemydidae,,https://upload.wikimedia.org/wikipedia/commons...,The Dermatemydidae family of turtles — more co...,https://www.scrapethissite.com//pages/frames/?...
2,Geoemydidae,,https://upload.wikimedia.org/wikipedia/commons...,The Geoemydidae family of turtles — more commo...,https://www.scrapethissite.com//pages/frames/?...

In [11]:
    # dict["detail"]=
driver.find_element("xpath",'//p[@class="lead"]').text.strip()# all url details

'The Carettochelyidae family of turtles — more commonly known as "Pig-nosed turtle" — were first discovered in 1887 by Boulenger.'

In [ ]:
## method 4 (same question is also done in 2.1, so will read csv and clicking on each inner url and extract)

In [24]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
import requests

In [25]:
df = pd.read_csv("scrape_this_site_q_2.1.csv")
df

,name,url,img_url
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

In [26]:
df["url"]

0    https://www.scrapethissite.com//pages/frames/?...
1    https://www.scrapethissite.com//pages/frames/?...
2    https://www.scrapethissite.com//pages/frames/?...
Name: url, dtype: object

In [32]:
list = []
for i in range(3):
    inner_url = df["url"][i]
    dict = {
        'name':df["name"][i],
        'url':df["url"][i],
        'img_url':df["img_url"][i],
        "detail":'',
    }
    r = requests.get(inner_url)    
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(inner_url, headers=headers)

    soup_nw = BeautifulSoup(resp.text, "html.parser")
    # soup_nw
    dict["detail"]=soup_nw.find('p').text.strip()# all url details
    list.append(dict)

In [33]:
df_new = pd.DataFrame(list)
df_new

,name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Cheloniidae family of turtles — more commo...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Chelydridae family of turtles — more commo...

In [34]:
df.to_csv("scrape_this_site_q_3.2.csv",index=False)

# method 5 (same as method 4 but using selenium library) student Assignment

# 	2.1 Extract first Testudines details save into csv file. e.g# Carettochelyidae
    ## (Testudines_name, url,img_url)m

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
import requests

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/frames/"
driver.get(url)

In [2]:
driver.find_element("xpath", "//h3").text

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//h3"}
  (Session info: chrome=142.0.7444.176); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7fff02eafd0c
	0x7ff659b9a235
	0x7ff6598f2630
	0x7ff6596816dd
	0x7ff6596da27e
	0x7ff6596da58c
	0x7ff65972ed77
	0x7ff65972baba
	0x7ff6596cb0ed
	0x7ff6596cbf63
	0x7ff659bc5d60
	0x7ff659bbfe8a
	0x7ff659be1005
	0x7ff65990d71e
	0x7ff659914e1f
	0x7ff6598fb7c4
	0x7ff6598fb97f
	0x7ff6598e18e8
	0x7fff01f4170c
	0x7fff01ec15e8
	0x7fff02dec200

In [3]:
driver.switch_to.frame(0)

In [4]:
driver.find_element("xpath", "//h3").text

'Carettochelyidae'

In [8]:
soup = BeautifulSoup(driver.page_source,"html")

In [9]:
#  finding div of each content
divs = soup.find_all("div",class_ = "col-md-4 turtle-family-card")
len(divs)

14

In [10]:
print(divs[0].prettify())

<div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg"/>
 <h3 class="family-name">
  Carettochelyidae
 </h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Carettochelyidae">
  Learn more →
 </a>
</div>

In [15]:
div = divs[0]

dict = {
    "name":"",
    "url":"",
    "img_url":""
}
base_url = "https://www.scrapethissite.com/"
dict["img_url"] = div.find("img")["src"]
dict["url"] =base_url + div.find("a")["href"]
dict["name"] =div.find("h3").text
# ["src"]
dict

{'name': 'Carettochelyidae',
 'url': 'https://www.scrapethissite.com//pages/frames/?frame=i&family=Carettochelyidae',
 'img_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg'}

In [16]:
df = pd.DataFrame([dict])
df

,name,url,img_url
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

## 2.1 clear code

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/frames/"
driver.get(url)
time.sleep(5)
driver.switch_to.frame(0) # switch driver into iframe otherwise no data will show in BS4
soup = BeautifulSoup(driver.page_source,"html")

divs = soup.find_all("div",class_ = "col-md-4 turtle-family-card") #  finding div of each content
# len(divs)
print(divs[0].prettify())
div = divs[0] # indexing to first family

<div class="col-md-4 turtle-family-card">
 <img class="turtle-image" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Carettochelys_insculpta.jpg/200px-Carettochelys_insculpta.jpg"/>
 <h3 class="family-name">
  Carettochelyidae
 </h3>
 <a class="btn btn-default btn-xs" href="/pages/frames/?frame=i&amp;family=Carettochelyidae">
  Learn more →
 </a>
</div>

,name,url,img_url
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

In [22]:
list = []
for div in divs[:3]:
    dict = {
        "name":"",
        "url":"",
        "img_url":""
    }
    base_url = "https://www.scrapethissite.com/"
    dict["img_url"] = div.find("img")["src"]
    dict["url"] =base_url + div.find("a")["href"]
    dict["name"] =div.find("h3").text
    # dict
    list.append(dict)

df = pd.DataFrame(list)
df

,name,url,img_url
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

In [23]:
df.to_csv("scrape_this_site_q_2.1.csv",index=False)

## 	1.7 Extract Tables from year 2015 to 2010 & save into single csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/ajax-javascript/"
driver.get(url)

for yr in range(2015,2009,-1):
    # driver.find_element("xpath","//element_name[@class='']")
    # driver.find_element("xpath","//element_name[@id='']")
    # driver.find_element("xpath",'//element_name[@id=""]')
    driver.find_element("xpath",f"//a[@id='{yr}']").click() # click on each year to load table data
    print(yr)
    time.sleep(3) #time delay to oad the table

    soup=BeautifulSoup(driver.page_source,"html")
    tbs= soup.find_all("table",class_= "table")[0]
    # tbs= soup.find("table",class_= "table")

    trs = tbs.find_all("tr")
    list = []
    for i in trs[1:]:
        dict = {        
        "title":i.find("td",class_ ="film-title" ).text.strip(),
        "Nomination":i.find("td",class_ ="film-nominations" ).text.strip(),
        "awards":i.find("td",class_ ="film-awards" ).text.strip()
        }
        list.append(dict.copy())
    df = pd.DataFrame(list)
    # df.to_csv("scrape_this_site_yr_"+str(yr)+".csv",index=False)
    df.to_csv(f"scrape_this_site_yr_{yr}.csv",index=False)

2015
2014
2013
2012
2011
2010

In [ ]:

# driver.find_element("xpath","//a[@id='2015']")

In [21]:
df

Empty DataFrame
Columns: []
Index: []