In [83]:
import requests # import library to make HTTP requests
from bs4 import BeautifulSoup # import library for parsing HTML
r = requests.get("https://books.toscrape.com/") # make a GET request to the URL
r.status_code # check the status code of the response

200

In [84]:
soup = BeautifulSoup(r.text, 'html.parser') # parse the HTML content
soup.prettify() # prettify the parsed HTML for better readability

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:29" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="catalogue/category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="catalogue/category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        1\n       </strong>\n       to\n       <strong>\n        20\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/a-light-in-the-attic_1000/index.html">\n             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">\n             A Light in the ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£51.77\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/tipping-the-velvet_999/index.html">\n             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">\n             Tipping the Velvet\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£53.74\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/soumission_998/index.html">\n             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/soumission_998/index.html" title="Soumission">\n             Soumission\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£50.10\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sharp-objects_997/index.html">\n             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">\n             Sharp Objects\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£47.82\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">\n             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">\n             Sapiens: A Brief History ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.23\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-requiem-red_995/index.html">\n             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">\n             The Requiem Red\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.65\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">\n             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">\n             The Dirty Little Secrets ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£33.34\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loadi

In [85]:
Header = soup.find("ol" , class_= "row") # find the ordered list with class "row"
Header.text.strip().replace("\n", "") # extract and clean the text content

"A Light in the ...Â£51.77            In stock    Add to basketTipping the VelvetÂ£53.74            In stock    Add to basketSoumissionÂ£50.10            In stock    Add to basketSharp ObjectsÂ£47.82            In stock    Add to basketSapiens: A Brief History ...Â£54.23            In stock    Add to basketThe Requiem RedÂ£22.65            In stock    Add to basketThe Dirty Little Secrets ...Â£33.34            In stock    Add to basketThe Coming Woman: A ...Â£17.93            In stock    Add to basketThe Boys in the ...Â£22.60            In stock    Add to basketThe Black MariaÂ£52.15            In stock    Add to basketStarving Hearts (Triangular Trade ...Â£13.99            In stock    Add to basketShakespeare's SonnetsÂ£20.66            In stock    Add to basketSet Me FreeÂ£17.46            In stock    Add to basketScott Pilgrim's Precious Little ...Â£52.29            In stock    Add to basketRip it Up and ...Â£35.02            In stock    Add to basketOur Band Could Be ...Â£57.25            In stock    Add to basketOlioÂ£23.88            In stock    Add to basketMesaerion: The Best Science ...Â£37.59            In stock    Add to basketLibertarianism for BeginnersÂ£51.33            In stock    Add to basketIt's Only the HimalayasÂ£45.17            In stock    Add to basket"

In [86]:
header =Header.find_all("li") #  find all list items within the ordered list
print(header)

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
<div class="product_price">
<p class="price_color">Â£53.74</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
<div class="product_price">
<p class="price_color">Â£50.10</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
<div class="product_price">
<p class="price_color">Â£47.82</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
<div class="product_price">
<p class="price_color">Â£54.23</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
<div class="product_price">
<p class="price_color">Â£22.65</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
<div class="product_price">
<p class="price_color">Â£33.34</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
<div class="product_price">
<p class="price_color">Â£17.93</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£22.60</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
<div class="product_price">
<p class="price_color">Â£52.15</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
<div class="product_price">
<p class="price_color">Â£13.99</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
<div class="product_price">
<p class="price_color">Â£20.66</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
<div class="product_price">
<p class="price_color">Â£17.46</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
<div class="product_price">
<p class="price_color">Â£52.29</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
<div class="product_price">
<p class="price_color">Â£35.02</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html"><img alt="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991" class="thumbnail" src="media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
<div class="product_price">
<p class="price_color">Â£57.25</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/olio_984/index.html"><img alt="Olio" class="thumbnail" src="media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
<div class="product_price">
<p class="price_color">Â£23.88</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
<div class="product_price">
<p class="price_color">Â£37.59</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
<div class="product_price">
<p class="price_color">Â£51.33</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
<div class="product_price">
<p class="price_color">Â£45.17</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>]

In [87]:
for book in header:
    title = book.find("h3").text # extract the book title
    link = book.find("a")["href"] # extract the book link
    price = book.find("p", class_ = "price_color").text # extract the book price

    print(title)
    print(link)
    print(price)
    print()

A Light in the ...
catalogue/a-light-in-the-attic_1000/index.html
Â£51.77

Tipping the Velvet
catalogue/tipping-the-velvet_999/index.html
Â£53.74

Soumission
catalogue/soumission_998/index.html
Â£50.10

Sharp Objects
catalogue/sharp-objects_997/index.html
Â£47.82

Sapiens: A Brief History ...
catalogue/sapiens-a-brief-history-of-humankind_996/index.html
Â£54.23

The Requiem Red
catalogue/the-requiem-red_995/index.html
Â£22.65

The Dirty Little Secrets ...
catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
Â£33.34

The Coming Woman: A ...
catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
Â£17.93

The Boys in the ...
catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
Â£22.60

The Black Maria
catalogue/the-black-maria_991/index.html
Â£52.15

Starving Hearts (Triangular Trade ...
catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
Â£13.99

Shakespeare's Sonnets
catalogue/shakespeares-sonnets_989/index.html
Â£20.66

Set Me Free
catalogue/set-me-free_988/index.html
Â£17.46

Scott Pilgrim's Precious Little ...
catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
Â£52.29

Rip it Up and ...
catalogue/rip-it-up-and-start-again_986/index.html
Â£35.02

Our Band Could Be ...
catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
Â£57.25

Olio
catalogue/olio_984/index.html
Â£23.88

Mesaerion: The Best Science ...
catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
Â£37.59

Libertarianism for Beginners
catalogue/libertarianism-for-beginners_982/index.html
Â£51.33

It's Only the Himalayas
catalogue/its-only-the-himalayas_981/index.html
Â£45.17

In [88]:
import pandas as pd
data = [] # create an empty list to store book data

for book in header:
    title = book.find("h3").text # extract the book title
    link = book.find("a")["href"] # extract the book link
    price = book.find("p", class_ = "price_color").text # extract the book price

    book_data = { # create a dictionary to store book details
    "Title" : "",
    "Link" : "",
    "Price" : ""
}
    book_data["Title"] = title # assign title to the dictionary
    book_data["Link"] = link  # assign link to the dictionary
    book_data["Price"] = price # assign price to the dictionaryv
    data.append(book_data) # append the dictionary to the list
    df = pd.DataFrame(data) # create a DataFrame from the list of dictionaries
    df

In [89]:
df.to_csv("books.csv", index = False)

In [90]:
df

,Title,Link,Price
0,A Light in the ...,catalogue/a-light-in-the-attic_1000/index.html,Â£51.77
1,Tipping the Velvet,catalogue/tipping-the-velvet_999/index.html,Â£53.74
2,Soumission,catalogue/soumission_998/index.html,Â£50.10
3,Sharp Objects,catalogue/sharp-objects_997/index.html,Â£47.82
4,Sapiens: A Brief History ...,catalogue/sapiens-a-brief-history-of-humankind...,Â£54.23
5,The Requiem Red,catalogue/the-requiem-red_995/index.html,Â£22.65
6,The Dirty Little Secrets ...,catalogue/the-dirty-little-secrets-of-getting-...,Â£33.34
7,The Coming Woman: A ...,catalogue/the-coming-woman-a-novel-based-on-th...,Â£17.93
8,The Boys in the ...,catalogue/the-boys-in-the-boat-nine-americans-...,Â£22.60
9,The Black Maria,catalogue/the-black-maria_991/index.html,Â£52.15
10,Starving Hearts (Triangular Trade ...,catalogue/starving-hearts-triangular-trade-tri...,Â£13.99
11,Shakespeare's Sonnets,catalogue/shakespeares-sonnets_989/index.html,Â£20.66
12,Set Me Free,catalogue/set-me-free_988/index.html,Â£17.46
13,Scott Pilgrim's Precious Little ...,catalogue/scott-pilgrims-precious-little-life-...,Â£52.29
14,Rip it Up and ...,catalogue/rip-it-up-and-start-again_986/index....,Â£35.02
15,Our Band Could Be ...,catalogue/our-band-could-be-your-life-scenes-f...,Â£57.25
16,Olio,catalogue/olio_984/index.html,Â£23.88
17,Mesaerion: The Best Science ...,catalogue/mesaerion-the-best-science-fiction-s...,Â£37.59
18,Libertarianism for Beginners,catalogue/libertarianism-for-beginners_982/ind...,Â£51.33
19,It's Only the Himalayas,catalogue/its-only-the-himalayas_981/index.html,Â£45.17

### 3. https://books.toscrape.com/ (Product_name,product_img, product_reviews_star_no, product_price, product_availabililty)

### 3.1 Extract first product details save into csv file. e.g# A Light in the ...

In [91]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r = requests.get("https://books.toscrape.com/")
r.status_code

200

In [92]:
soup =  BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:29" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="catalogue/category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="catalogue/category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        1\n       </strong>\n       to\n       <strong>\n        20\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/a-light-in-the-attic_1000/index.html">\n             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">\n             A Light in the ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£51.77\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/tipping-the-velvet_999/index.html">\n             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">\n             Tipping the Velvet\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£53.74\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/soumission_998/index.html">\n             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/soumission_998/index.html" title="Soumission">\n             Soumission\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£50.10\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sharp-objects_997/index.html">\n             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">\n             Sharp Objects\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£47.82\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">\n             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">\n             Sapiens: A Brief History ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.23\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-requiem-red_995/index.html">\n             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">\n             The Requiem Red\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.65\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">\n             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">\n             The Dirty Little Secrets ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£33.34\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loadi

In [93]:
sec = soup.find("li" , class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")

In [94]:
sec.find("h3").text.strip()

'A Light in the ...'

In [95]:
sec.find("img")["src"]

'media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg'

In [96]:
sec.find("p" , class_ = "star-rating Three").text.strip()

''

In [97]:
sec.find("p" , class_ = "price_color").text.strip()

'Â£51.77'

In [98]:
sec.find("p" , class_ = "instock availability").text.strip()

'In stock'

In [10]:
dl = []
data = {
    "Product Name" : "",
    "Product Image" : "",
    "Product Price" : "",
    "Product Availability" : ""

}
data["Product Name"] = sec.find("h3").text.strip()
data["Product Image"] = sec.find("img")["src"]
data["Product Price"] = sec.find("p" , class_ = "price_color").text.strip()
data["Product Availability"] = sec.find("p" , class_ = "instock availability").text.strip()
dl.append(data)
dl

[{'Product Name': 'In the Country We ...',
  'Product Image': '../media/cache/fe/ea/feeafd2ad7b3077f8e74cbb1da9e3c7d.jpg',
  'Product Price': 'Â£22.00',
  'Product Availability': 'In stock'}]

In [11]:
df = pd.DataFrame(dl)
df

,Product Name,Product Image,Product Price,Product Availability
0,In the Country We ...,../media/cache/fe/ea/feeafd2ad7b3077f8e74cbb1d...,Â£22.00,In stock

In [101]:
df.to_csv("book_toscrape_q3.1.csv")

### 3.2 Extract product details from first row & save into csv file. e.g# A Light in the ..., Tipping the Velvet, Soumission

In [17]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r = requests.get("https://books.toscrape.com/")
r.status_code

200

In [18]:
soup =  BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:29" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="catalogue/category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="catalogue/category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        1\n       </strong>\n       to\n       <strong>\n        20\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/a-light-in-the-attic_1000/index.html">\n             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">\n             A Light in the ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£51.77\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/tipping-the-velvet_999/index.html">\n             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">\n             Tipping the Velvet\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£53.74\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/soumission_998/index.html">\n             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/soumission_998/index.html" title="Soumission">\n             Soumission\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£50.10\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sharp-objects_997/index.html">\n             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">\n             Sharp Objects\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£47.82\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">\n             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">\n             Sapiens: A Brief History ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.23\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-requiem-red_995/index.html">\n             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">\n             The Requiem Red\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.65\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">\n             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">\n             The Dirty Little Secrets ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£33.34\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loadi

In [19]:
row = soup.find_all("li" , class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")[0:4]
row

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.74</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
 <div class="product_price">
 <p class="price_color">Â£50.10</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
 <div class="product_price">
 <p class="price_color">Â£47.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>]

In [20]:
dl = []
for sec in row:
    data = {
    "Product Name" : "",
    "Product Image" : "",
    "Product Price" : "",
    "Product Avail" : ""

}
    data["Product Name"] = sec.find("h3").text.strip()
    data["Product Image"] = sec.find("img")["src"]
    data["Product Price"] = sec.find("p" , class_ = "price_color").text.strip()
    data["Product Avail"] = sec.find("p" , class_ = "instock availability").text.strip()
    dl.append(data)
dl

[{'Product Name': 'A Light in the ...',
  'Product Image': 'media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg',
  'Product Price': 'Â£51.77',
  'Product Avail': 'In stock'},
 {'Product Name': 'Tipping the Velvet',
  'Product Image': 'media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg',
  'Product Price': 'Â£53.74',
  'Product Avail': 'In stock'},
 {'Product Name': 'Soumission',
  'Product Image': 'media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg',
  'Product Price': 'Â£50.10',
  'Product Avail': 'In stock'},
 {'Product Name': 'Sharp Objects',
  'Product Image': 'media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg',
  'Product Price': 'Â£47.82',
  'Product Avail': 'In stock'}]

In [21]:
df = pd.DataFrame(dl)
df

,Product Name,Product Image,Product Price,Product Avail
0,A Light in the ...,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,Â£51.77,In stock
1,Tipping the Velvet,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...,Â£53.74,In stock
2,Soumission,media/cache/3e/ef/3eef99c9d9adef34639f51066202...,Â£50.10,In stock
3,Sharp Objects,media/cache/32/51/3251cf3a3412f53f339e42cac213...,Â£47.82,In stock

In [22]:
df.to_csv("book_toscrape_q3.2.csv")

### 3.3 Extract all product details from page & save into csv file.

In [23]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r = requests.get("https://books.toscrape.com/")
r.status_code

200

In [109]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:29" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="catalogue/category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="catalogue/category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        1\n       </strong>\n       to\n       <strong>\n        20\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/a-light-in-the-attic_1000/index.html">\n             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">\n             A Light in the ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£51.77\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/tipping-the-velvet_999/index.html">\n             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">\n             Tipping the Velvet\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£53.74\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/soumission_998/index.html">\n             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/soumission_998/index.html" title="Soumission">\n             Soumission\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£50.10\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sharp-objects_997/index.html">\n             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">\n             Sharp Objects\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£47.82\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">\n             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">\n             Sapiens: A Brief History ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.23\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-requiem-red_995/index.html">\n             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">\n             The Requiem Red\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.65\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">\n             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">\n             The Dirty Little Secrets ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£33.34\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loadi

In [110]:
books = soup.find_all("li" , class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")
books

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.74</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
 <div class="product_price">
 <p class="price_color">Â£50.10</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
 <div class="product_price">
 <p class="price_color">Â£47.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£54.23</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.65</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.34</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.93</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.60</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.15</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£13.99</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
 <div class="product_price">
 <p class="price_color">Â£20.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.46</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£35.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html"><img alt="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991" class="thumbnail" src="media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£57.25</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/olio_984/index.html"><img alt="Olio" class="thumbnail" src="media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
 <div class="product_price">
 <p class="price_color">Â£23.88</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£37.59</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.33</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
 <div class="product_price">
 <p class="price_color">Â£45.17</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>]

In [111]:
dl = []
for sec in books:
    data = {
    "Product Name" : "",
    "Product Image" : "",
    "Product Price" : "",
    "Product Avail" : ""

}
    data["Product Name"] = sec.find("h3").text.strip()
    data["Product Image"] = sec.find("img")["src"]
    data["Product Price"] = sec.find("p" , class_ = "price_color").text.strip()
    data["Product Avail"] = sec.find("p" , class_ = "instock availability").text.strip()
    dl.append(data)
dl

[{'Product Name': 'A Light in the ...',
  'Product Image': 'media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg',
  'Product Price': 'Â£51.77',
  'Product Avail': 'In stock'},
 {'Product Name': 'Tipping the Velvet',
  'Product Image': 'media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg',
  'Product Price': 'Â£53.74',
  'Product Avail': 'In stock'},
 {'Product Name': 'Soumission',
  'Product Image': 'media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg',
  'Product Price': 'Â£50.10',
  'Product Avail': 'In stock'},
 {'Product Name': 'Sharp Objects',
  'Product Image': 'media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg',
  'Product Price': 'Â£47.82',
  'Product Avail': 'In stock'},
 {'Product Name': 'Sapiens: A Brief History ...',
  'Product Image': 'media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg',
  'Product Price': 'Â£54.23',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Requiem Red',
  'Product Image': 'media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg',
  'Product Price': 'Â£22.65',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Dirty Little Secrets ...',
  'Product Image': 'media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg',
  'Product Price': 'Â£33.34',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Coming Woman: A ...',
  'Product Image': 'media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg',
  'Product Price': 'Â£17.93',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Boys in the ...',
  'Product Image': 'media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg',
  'Product Price': 'Â£22.60',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Black Maria',
  'Product Image': 'media/cache/58/46/5846057e28022268153beff6d352b06c.jpg',
  'Product Price': 'Â£52.15',
  'Product Avail': 'In stock'},
 {'Product Name': 'Starving Hearts (Triangular Trade ...',
  'Product Image': 'media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg',
  'Product Price': 'Â£13.99',
  'Product Avail': 'In stock'},
 {'Product Name': "Shakespeare's Sonnets",
  'Product Image': 'media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg',
  'Product Price': 'Â£20.66',
  'Product Avail': 'In stock'},
 {'Product Name': 'Set Me Free',
  'Product Image': 'media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg',
  'Product Price': 'Â£17.46',
  'Product Avail': 'In stock'},
 {'Product Name': "Scott Pilgrim's Precious Little ...",
  'Product Image': 'media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg',
  'Product Price': 'Â£52.29',
  'Product Avail': 'In stock'},
 {'Product Name': 'Rip it Up and ...',
  'Product Image': 'media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg',
  'Product Price': 'Â£35.02',
  'Product Avail': 'In stock'},
 {'Product Name': 'Our Band Could Be ...',
  'Product Image': 'media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg',
  'Product Price': 'Â£57.25',
  'Product Avail': 'In stock'},
 {'Product Name': 'Olio',
  'Product Image': 'media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg',
  'Product Price': 'Â£23.88',
  'Product Avail': 'In stock'},
 {'Product Name': 'Mesaerion: The Best Science ...',
  'Product Image': 'media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg',
  'Product Price': 'Â£37.59',
  'Product Avail': 'In stock'},
 {'Product Name': 'Libertarianism for Beginners',
  'Product Image': 'media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg',
  'Product Price': 'Â£51.33',
  'Product Avail': 'In stock'},
 {'Product Name': "It's Only the Himalayas",
  'Product Image': 'media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg',
  'Product Price': 'Â£45.17',
  'Product Avail': 'In stock'}]

In [112]:
len(dl)

20

In [113]:
df = pd.DataFrame(dl)
df

,Product Name,Product Image,Product Price,Product Avail
0,A Light in the ...,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,Â£51.77,In stock
1,Tipping the Velvet,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...,Â£53.74,In stock
2,Soumission,media/cache/3e/ef/3eef99c9d9adef34639f51066202...,Â£50.10,In stock
3,Sharp Objects,media/cache/32/51/3251cf3a3412f53f339e42cac213...,Â£47.82,In stock
4,Sapiens: A Brief History ...,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...,Â£54.23,In stock
5,The Requiem Red,media/cache/68/33/68339b4c9bc034267e1da611ab3b...,Â£22.65,In stock
6,The Dirty Little Secrets ...,media/cache/92/27/92274a95b7c251fea59a2b8a7827...,Â£33.34,In stock
7,The Coming Woman: A ...,media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78...,Â£17.93,In stock
8,The Boys in the ...,media/cache/66/88/66883b91f6804b2323c8369331cb...,Â£22.60,In stock
9,The Black Maria,media/cache/58/46/5846057e28022268153beff6d352...,Â£52.15,In stock
10,Starving Hearts (Triangular Trade ...,media/cache/be/f4/bef44da28c98f905a3ebec0b87be...,Â£13.99,In stock
11,Shakespeare's Sonnets,media/cache/10/48/1048f63d3b5061cd2f424d20b3f9...,Â£20.66,In stock
12,Set Me Free,media/cache/5b/88/5b88c52633f53cacf162c15f4f82...,Â£17.46,In stock
13,Scott Pilgrim's Precious Little ...,media/cache/94/b1/94b1b8b244bce9677c2f29ccc890...,Â£52.29,In stock
14,Rip it Up and ...,media/cache/81/c4/81c4a973364e17d01f217e118825...,Â£35.02,In stock
15,Our Band Could Be ...,media/cache/54/60/54607fe8945897cdcced0044103b...,Â£57.25,In stock
16,Olio,media/cache/55/33/553310a7162dfbc2c6d19a84da0d...,Â£23.88,In stock
17,Mesaerion: The Best Science ...,media/cache/09/a3/09a3aef48557576e1a85ba7efea8...,Â£37.59,In stock
18,Libertarianism for Beginners,media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736...,Â£51.33,In stock
19,It's Only the Himalayas,media/cache/27/a5/27a53d0bb95bdd88288eaf66c923...,Â£45.17,In stock

In [114]:
df.to_csv("book_toscrape_q3.3.csv")

### 3.4 Extract all product details of first column save into csv file.

In [115]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r = requests.get("https://books.toscrape.com/")
r.status_code

200

In [116]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:29" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="catalogue/category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="catalogue/category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        1\n       </strong>\n       to\n       <strong>\n        20\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/a-light-in-the-attic_1000/index.html">\n             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">\n             A Light in the ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£51.77\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/tipping-the-velvet_999/index.html">\n             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">\n             Tipping the Velvet\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£53.74\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/soumission_998/index.html">\n             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/soumission_998/index.html" title="Soumission">\n             Soumission\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£50.10\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sharp-objects_997/index.html">\n             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">\n             Sharp Objects\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£47.82\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">\n             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">\n             Sapiens: A Brief History ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.23\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-requiem-red_995/index.html">\n             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">\n             The Requiem Red\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.65\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">\n             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">\n             The Dirty Little Secrets ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£33.34\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loadi

In [117]:
first_col = soup.find_all("li" , class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")[0::4]
first_col

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£54.23</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.60</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.46</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/olio_984/index.html"><img alt="Olio" class="thumbnail" src="media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
 <div class="product_price">
 <p class="price_color">Â£23.88</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>]

In [118]:
dl = []
for sec in first_col:
    data = {
    "Product Name" : "",
    "Product Image" : "",
    "Product Price" : "",
    "Product Avail" : ""

}
    data["Product Name"] = sec.find("h3").text.strip()
    data["Product Image"] = sec.find("img")["src"]
    data["Product Price"] = sec.find("p" , class_ = "price_color").text.strip()
    data["Product Avail"] = sec.find("p" , class_ = "instock availability").text.strip()
    dl.append(data)
dl

[{'Product Name': 'A Light in the ...',
  'Product Image': 'media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg',
  'Product Price': 'Â£51.77',
  'Product Avail': 'In stock'},
 {'Product Name': 'Sapiens: A Brief History ...',
  'Product Image': 'media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg',
  'Product Price': 'Â£54.23',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Boys in the ...',
  'Product Image': 'media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg',
  'Product Price': 'Â£22.60',
  'Product Avail': 'In stock'},
 {'Product Name': 'Set Me Free',
  'Product Image': 'media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg',
  'Product Price': 'Â£17.46',
  'Product Avail': 'In stock'},
 {'Product Name': 'Olio',
  'Product Image': 'media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg',
  'Product Price': 'Â£23.88',
  'Product Avail': 'In stock'}]

In [119]:
df = pd.DataFrame(dl)
df

,Product Name,Product Image,Product Price,Product Avail
0,A Light in the ...,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,Â£51.77,In stock
1,Sapiens: A Brief History ...,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...,Â£54.23,In stock
2,The Boys in the ...,media/cache/66/88/66883b91f6804b2323c8369331cb...,Â£22.60,In stock
3,Set Me Free,media/cache/5b/88/5b88c52633f53cacf162c15f4f82...,Â£17.46,In stock
4,Olio,media/cache/55/33/553310a7162dfbc2c6d19a84da0d...,Â£23.88,In stock

In [120]:
df.to_csv("book_toscrape_q3.4.csv")

### 3.5 Extract all product details of Second column save into csv file.

In [121]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r = requests.get("https://books.toscrape.com/")
r.status_code

200

In [122]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:29" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="catalogue/category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="catalogue/category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        1\n       </strong>\n       to\n       <strong>\n        20\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/a-light-in-the-attic_1000/index.html">\n             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">\n             A Light in the ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£51.77\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/tipping-the-velvet_999/index.html">\n             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">\n             Tipping the Velvet\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£53.74\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/soumission_998/index.html">\n             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/soumission_998/index.html" title="Soumission">\n             Soumission\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£50.10\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sharp-objects_997/index.html">\n             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">\n             Sharp Objects\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£47.82\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">\n             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">\n             Sapiens: A Brief History ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.23\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-requiem-red_995/index.html">\n             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">\n             The Requiem Red\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.65\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">\n             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">\n             The Dirty Little Secrets ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£33.34\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loadi

In [123]:
second_col = soup.find_all("li" , class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")[1::4]
second_col

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.74</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.65</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.15</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£37.59</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>]

In [124]:
dl = []
for sec in second_col:
    data = {
    "Product Name" : "",
    "Product Image" : "",
    "Product Price" : "",
    "Product Avail" : ""

}
    data["Product Name"] = sec.find("h3").text.strip()
    data["Product Image"] = sec.find("img")["src"]
    data["Product Price"] = sec.find("p" , class_ = "price_color").text.strip()
    data["Product Avail"] = sec.find("p" , class_ = "instock availability").text.strip()
    dl.append(data)
dl

[{'Product Name': 'Tipping the Velvet',
  'Product Image': 'media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg',
  'Product Price': 'Â£53.74',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Requiem Red',
  'Product Image': 'media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg',
  'Product Price': 'Â£22.65',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Black Maria',
  'Product Image': 'media/cache/58/46/5846057e28022268153beff6d352b06c.jpg',
  'Product Price': 'Â£52.15',
  'Product Avail': 'In stock'},
 {'Product Name': "Scott Pilgrim's Precious Little ...",
  'Product Image': 'media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg',
  'Product Price': 'Â£52.29',
  'Product Avail': 'In stock'},
 {'Product Name': 'Mesaerion: The Best Science ...',
  'Product Image': 'media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg',
  'Product Price': 'Â£37.59',
  'Product Avail': 'In stock'}]

In [125]:
df = pd.DataFrame(dl)
df

,Product Name,Product Image,Product Price,Product Avail
0,Tipping the Velvet,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...,Â£53.74,In stock
1,The Requiem Red,media/cache/68/33/68339b4c9bc034267e1da611ab3b...,Â£22.65,In stock
2,The Black Maria,media/cache/58/46/5846057e28022268153beff6d352...,Â£52.15,In stock
3,Scott Pilgrim's Precious Little ...,media/cache/94/b1/94b1b8b244bce9677c2f29ccc890...,Â£52.29,In stock
4,Mesaerion: The Best Science ...,media/cache/09/a3/09a3aef48557576e1a85ba7efea8...,Â£37.59,In stock

In [126]:
df.to_csv("book_toscrape_q3.5.csv")

### 3.6 Extract all product details of thirst column save into csv file.

In [127]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r = requests.get("https://books.toscrape.com/")
r.status_code

200

In [128]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:29" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="catalogue/category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="catalogue/category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="catalogue/category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        1\n       </strong>\n       to\n       <strong>\n        20\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/a-light-in-the-attic_1000/index.html">\n             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">\n             A Light in the ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£51.77\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/tipping-the-velvet_999/index.html">\n             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">\n             Tipping the Velvet\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£53.74\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/soumission_998/index.html">\n             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/soumission_998/index.html" title="Soumission">\n             Soumission\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£50.10\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sharp-objects_997/index.html">\n             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">\n             Sharp Objects\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£47.82\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">\n             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">\n             Sapiens: A Brief History ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.23\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-requiem-red_995/index.html">\n             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">\n             The Requiem Red\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.65\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">\n             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">\n             The Dirty Little Secrets ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£33.34\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loadi

In [129]:
third_col = soup.find_all("li" , class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")[2::4]
third_col

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
 <div class="product_price">
 <p class="price_color">Â£50.10</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.34</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£13.99</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£35.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.33</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>]

In [130]:
dl = []
for sec in third_col:
    data = {
    "Product Name" : "",
    "Product Image" : "",
    "Product Price" : "",
    "Product Avail" : ""

}
    data["Product Name"] = sec.find("h3").text.strip()
    data["Product Image"] = sec.find("img")["src"]
    data["Product Price"] = sec.find("p" , class_ = "price_color").text.strip()
    data["Product Avail"] = sec.find("p" , class_ = "instock availability").text.strip()
    dl.append(data)
dl

[{'Product Name': 'Soumission',
  'Product Image': 'media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg',
  'Product Price': 'Â£50.10',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Dirty Little Secrets ...',
  'Product Image': 'media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg',
  'Product Price': 'Â£33.34',
  'Product Avail': 'In stock'},
 {'Product Name': 'Starving Hearts (Triangular Trade ...',
  'Product Image': 'media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg',
  'Product Price': 'Â£13.99',
  'Product Avail': 'In stock'},
 {'Product Name': 'Rip it Up and ...',
  'Product Image': 'media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg',
  'Product Price': 'Â£35.02',
  'Product Avail': 'In stock'},
 {'Product Name': 'Libertarianism for Beginners',
  'Product Image': 'media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg',
  'Product Price': 'Â£51.33',
  'Product Avail': 'In stock'}]

In [131]:
df = pd.DataFrame(dl)
df

,Product Name,Product Image,Product Price,Product Avail
0,Soumission,media/cache/3e/ef/3eef99c9d9adef34639f51066202...,Â£50.10,In stock
1,The Dirty Little Secrets ...,media/cache/92/27/92274a95b7c251fea59a2b8a7827...,Â£33.34,In stock
2,Starving Hearts (Triangular Trade ...,media/cache/be/f4/bef44da28c98f905a3ebec0b87be...,Â£13.99,In stock
3,Rip it Up and ...,media/cache/81/c4/81c4a973364e17d01f217e118825...,Â£35.02,In stock
4,Libertarianism for Beginners,media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736...,Â£51.33,In stock

In [132]:
df.to_csv("book_toscrape_q3.6.csv")

### 3.7 Extract all product details from first page & save into csv file.

In [133]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r = requests.get("https://books.toscrape.com/catalogue/page-1.html")
r.status_code

200

In [134]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:30" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="../static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="../index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="../index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        1\n       </strong>\n       to\n       <strong>\n        20\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="a-light-in-the-attic_1000/index.html">\n             <img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">\n             A Light in the ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£51.77\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="tipping-the-velvet_999/index.html">\n             <img alt="Tipping the Velvet" class="thumbnail" src="../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="tipping-the-velvet_999/index.html" title="Tipping the Velvet">\n             Tipping the Velvet\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£53.74\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="soumission_998/index.html">\n             <img alt="Soumission" class="thumbnail" src="../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="soumission_998/index.html" title="Soumission">\n             Soumission\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£50.10\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="sharp-objects_997/index.html">\n             <img alt="Sharp Objects" class="thumbnail" src="../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="sharp-objects_997/index.html" title="Sharp Objects">\n             Sharp Objects\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£47.82\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="sapiens-a-brief-history-of-humankind_996/index.html">\n             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">\n             Sapiens: A Brief History ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.23\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="the-requiem-red_995/index.html">\n             <img alt="The Requiem Red" class="thumbnail" src="../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="the-requiem-red_995/index.html" title="The Requiem Red">\n             The Requiem Red\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.65\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">\n             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Four">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">\n             The Dirty Little Secrets ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£33.34\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">\n             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="../media/cache/3d/54/3d54940e57e662c4dd1f3

In [135]:
all_book = soup.find_all("li" , class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")
all_book

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.74</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="soumission_998/index.html" title="Soumission">Soumission</a></h3>
 <div class="product_price">
 <p class="price_color">Â£50.10</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
 <div class="product_price">
 <p class="price_color">Â£47.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£54.23</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.65</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.34</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.93</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="../media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.60</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="../media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.15</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="../media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£13.99</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="../media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
 <div class="product_price">
 <p class="price_color">Â£20.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="../media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.46</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="../media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="../media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£35.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html"><img alt="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991" class="thumbnail" src="../media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£57.25</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="olio_984/index.html"><img alt="Olio" class="thumbnail" src="../media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="olio_984/index.html" title="Olio">Olio</a></h3>
 <div class="product_price">
 <p class="price_color">Â£23.88</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="../media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£37.59</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="../media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.33</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="../media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
 <div class="product_price">
 <p class="price_color">Â£45.17</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>]

In [136]:
dl = []
for sec in all_book:
    data = {
    "Product Name" : "",
    "Product Image" : "",
    "Product Price" : "",
    "Product Avail" : ""

}
    data["Product Name"] = sec.find("h3").text.strip()
    data["Product Image"] = sec.find("img")["src"]
    data["Product Price"] = sec.find("p" , class_ = "price_color").text.strip()
    data["Product Avail"] = sec.find("p" , class_ = "instock availability").text.strip()
    dl.append(data)
dl

[{'Product Name': 'A Light in the ...',
  'Product Image': '../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg',
  'Product Price': 'Â£51.77',
  'Product Avail': 'In stock'},
 {'Product Name': 'Tipping the Velvet',
  'Product Image': '../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg',
  'Product Price': 'Â£53.74',
  'Product Avail': 'In stock'},
 {'Product Name': 'Soumission',
  'Product Image': '../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg',
  'Product Price': 'Â£50.10',
  'Product Avail': 'In stock'},
 {'Product Name': 'Sharp Objects',
  'Product Image': '../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg',
  'Product Price': 'Â£47.82',
  'Product Avail': 'In stock'},
 {'Product Name': 'Sapiens: A Brief History ...',
  'Product Image': '../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg',
  'Product Price': 'Â£54.23',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Requiem Red',
  'Product Image': '../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg',
  'Product Price': 'Â£22.65',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Dirty Little Secrets ...',
  'Product Image': '../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg',
  'Product Price': 'Â£33.34',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Coming Woman: A ...',
  'Product Image': '../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg',
  'Product Price': 'Â£17.93',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Boys in the ...',
  'Product Image': '../media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg',
  'Product Price': 'Â£22.60',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Black Maria',
  'Product Image': '../media/cache/58/46/5846057e28022268153beff6d352b06c.jpg',
  'Product Price': 'Â£52.15',
  'Product Avail': 'In stock'},
 {'Product Name': 'Starving Hearts (Triangular Trade ...',
  'Product Image': '../media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg',
  'Product Price': 'Â£13.99',
  'Product Avail': 'In stock'},
 {'Product Name': "Shakespeare's Sonnets",
  'Product Image': '../media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg',
  'Product Price': 'Â£20.66',
  'Product Avail': 'In stock'},
 {'Product Name': 'Set Me Free',
  'Product Image': '../media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg',
  'Product Price': 'Â£17.46',
  'Product Avail': 'In stock'},
 {'Product Name': "Scott Pilgrim's Precious Little ...",
  'Product Image': '../media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg',
  'Product Price': 'Â£52.29',
  'Product Avail': 'In stock'},
 {'Product Name': 'Rip it Up and ...',
  'Product Image': '../media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg',
  'Product Price': 'Â£35.02',
  'Product Avail': 'In stock'},
 {'Product Name': 'Our Band Could Be ...',
  'Product Image': '../media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg',
  'Product Price': 'Â£57.25',
  'Product Avail': 'In stock'},
 {'Product Name': 'Olio',
  'Product Image': '../media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg',
  'Product Price': 'Â£23.88',
  'Product Avail': 'In stock'},
 {'Product Name': 'Mesaerion: The Best Science ...',
  'Product Image': '../media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg',
  'Product Price': 'Â£37.59',
  'Product Avail': 'In stock'},
 {'Product Name': 'Libertarianism for Beginners',
  'Product Image': '../media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg',
  'Product Price': 'Â£51.33',
  'Product Avail': 'In stock'},
 {'Product Name': "It's Only the Himalayas",
  'Product Image': '../media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg',
  'Product Price': 'Â£45.17',
  'Product Avail': 'In stock'}]

In [137]:
df =pd.DataFrame(dl)
df

,Product Name,Product Image,Product Price,Product Avail
0,A Light in the ...,../media/cache/2c/da/2cdad67c44b002e7ead0cc356...,Â£51.77,In stock
1,Tipping the Velvet,../media/cache/26/0c/260c6ae16bce31c8f8c95dadd...,Â£53.74,In stock
2,Soumission,../media/cache/3e/ef/3eef99c9d9adef34639f51066...,Â£50.10,In stock
3,Sharp Objects,../media/cache/32/51/3251cf3a3412f53f339e42cac...,Â£47.82,In stock
4,Sapiens: A Brief History ...,../media/cache/be/a5/bea5697f2534a2f86a3ef27b5...,Â£54.23,In stock
5,The Requiem Red,../media/cache/68/33/68339b4c9bc034267e1da611a...,Â£22.65,In stock
6,The Dirty Little Secrets ...,../media/cache/92/27/92274a95b7c251fea59a2b8a7...,Â£33.34,In stock
7,The Coming Woman: A ...,../media/cache/3d/54/3d54940e57e662c4dd1f3ff00...,Â£17.93,In stock
8,The Boys in the ...,../media/cache/66/88/66883b91f6804b2323c836933...,Â£22.60,In stock
9,The Black Maria,../media/cache/58/46/5846057e28022268153beff6d...,Â£52.15,In stock
10,Starving Hearts (Triangular Trade ...,../media/cache/be/f4/bef44da28c98f905a3ebec0b8...,Â£13.99,In stock
11,Shakespeare's Sonnets,../media/cache/10/48/1048f63d3b5061cd2f424d20b...,Â£20.66,In stock
12,Set Me Free,../media/cache/5b/88/5b88c52633f53cacf162c15f4...,Â£17.46,In stock
13,Scott Pilgrim's Precious Little ...,../media/cache/94/b1/94b1b8b244bce9677c2f29ccc...,Â£52.29,In stock
14,Rip it Up and ...,../media/cache/81/c4/81c4a973364e17d01f217e118...,Â£35.02,In stock
15,Our Band Could Be ...,../media/cache/54/60/54607fe8945897cdcced00441...,Â£57.25,In stock
16,Olio,../media/cache/55/33/553310a7162dfbc2c6d19a84d...,Â£23.88,In stock
17,Mesaerion: The Best Science ...,../media/cache/09/a3/09a3aef48557576e1a85ba7ef...,Â£37.59,In stock
18,Libertarianism for Beginners,../media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52...,Â£51.33,In stock
19,It's Only the Himalayas,../media/cache/27/a5/27a53d0bb95bdd88288eaf66c...,Â£45.17,In stock

In [138]:
df.to_csv("book_toscrape_q3.7.csv")

### 3.8 Extract all product details from second page & save into another csv file.

In [139]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r = requests.get("https://books.toscrape.com/catalogue/page-2.html")
r.status_code

200

In [140]:
soup = BeautifulSoup(r.text , "html.parser")
soup.prettify()

'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!-->\n<html class="no-js" lang="en-us">\n <!--<![endif]-->\n <head>\n  <title>\n   All products | Books to Scrape - Sandbox\n  </title>\n  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>\n  <meta content="24th Jun 2016 09:29" name="created"/>\n  <meta content="" name="description"/>\n  <meta content="width=device-width" name="viewport"/>\n  <meta content="NOARCHIVE,NOCACHE" name="robots"/>\n  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n  <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n  <link href="../static/oscar/favicon.ico" rel="shortcut icon"/>\n  <link href="../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>\n  <link href="../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>\n  <link href="../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>\n </head>\n <body class="default" id="default">\n  <header class="header container-fluid">\n   <div class="page_inner">\n    <div class="row">\n     <div class="col-sm-8 h1">\n      <a href="../index.html">\n       Books to Scrape\n      </a>\n      <small>\n       We love being scraped!\n      </small>\n     </div>\n    </div>\n   </div>\n  </header>\n  <div class="container-fluid page">\n   <div class="page_inner">\n    <ul class="breadcrumb">\n     <li>\n      <a href="../index.html">\n       Home\n      </a>\n     </li>\n     <li class="active">\n      All products\n     </li>\n    </ul>\n    <div class="row">\n     <aside class="sidebar col-sm-4 col-md-3">\n      <div id="promotions_left">\n      </div>\n      <div class="side_categories">\n       <ul class="nav nav-list">\n        <li>\n         <a href="category/books_1/index.html">\n          Books\n         </a>\n         <ul>\n          <li>\n           <a href="category/books/travel_2/index.html">\n            Travel\n           </a>\n          </li>\n          <li>\n           <a href="category/books/mystery_3/index.html">\n            Mystery\n           </a>\n          </li>\n          <li>\n           <a href="category/books/historical-fiction_4/index.html">\n            Historical Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/sequential-art_5/index.html">\n            Sequential Art\n           </a>\n          </li>\n          <li>\n           <a href="category/books/classics_6/index.html">\n            Classics\n           </a>\n          </li>\n          <li>\n           <a href="category/books/philosophy_7/index.html">\n            Philosophy\n           </a>\n          </li>\n          <li>\n           <a href="category/books/romance_8/index.html">\n            Romance\n           </a>\n          </li>\n          <li>\n           <a href="category/books/womens-fiction_9/index.html">\n            Womens Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/fiction_10/index.html">\n            Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/childrens_11/index.html">\n            Childrens\n           </a>\n          </li>\n          <li>\n           <a href="category/books/religion_12/index.html">\n            Religion\n           </a>\n          </li>\n          <li>\n           <a href="category/books/nonfiction_13/index.html">\n            Nonfiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/music_14/index.html">\n            Music\n           </a>\n          </li>\n          <li>\n           <a href="category/books/default_15/index.html">\n            Default\n           </a>\n          </li>\n          <li>\n           <a href="category/books/science-fiction_16/index.html">\n            Science Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/sports-and-games_17/index.html">\n            Sports and Games\n           </a>\n          </li>\n          <li>\n           <a href="category/books/add-a-comment_18/index.html">\n            Add a comment\n           </a>\n          </li>\n          <li>\n           <a href="category/books/fantasy_19/index.html">\n            Fantasy\n           </a>\n          </li>\n          <li>\n           <a href="category/books/new-adult_20/index.html">\n            New Adult\n           </a>\n          </li>\n          <li>\n           <a href="category/books/young-adult_21/index.html">\n            Young Adult\n           </a>\n          </li>\n          <li>\n           <a href="category/books/science_22/index.html">\n            Science\n           </a>\n          </li>\n          <li>\n           <a href="category/books/poetry_23/index.html">\n            Poetry\n           </a>\n          </li>\n          <li>\n           <a href="category/books/paranormal_24/index.html">\n            Paranormal\n           </a>\n          </li>\n          <li>\n           <a href="category/books/art_25/index.html">\n            Art\n           </a>\n          </li>\n          <li>\n           <a href="category/books/psychology_26/index.html">\n            Psychology\n           </a>\n          </li>\n          <li>\n           <a href="category/books/autobiography_27/index.html">\n            Autobiography\n           </a>\n          </li>\n          <li>\n           <a href="category/books/parenting_28/index.html">\n            Parenting\n           </a>\n          </li>\n          <li>\n           <a href="category/books/adult-fiction_29/index.html">\n            Adult Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/humor_30/index.html">\n            Humor\n           </a>\n          </li>\n          <li>\n           <a href="category/books/horror_31/index.html">\n            Horror\n           </a>\n          </li>\n          <li>\n           <a href="category/books/history_32/index.html">\n            History\n           </a>\n          </li>\n          <li>\n           <a href="category/books/food-and-drink_33/index.html">\n            Food and Drink\n           </a>\n          </li>\n          <li>\n           <a href="category/books/christian-fiction_34/index.html">\n            Christian Fiction\n           </a>\n          </li>\n          <li>\n           <a href="category/books/business_35/index.html">\n            Business\n           </a>\n          </li>\n          <li>\n           <a href="category/books/biography_36/index.html">\n            Biography\n           </a>\n          </li>\n          <li>\n           <a href="category/books/thriller_37/index.html">\n            Thriller\n           </a>\n          </li>\n          <li>\n           <a href="category/books/contemporary_38/index.html">\n            Contemporary\n           </a>\n          </li>\n          <li>\n           <a href="category/books/spirituality_39/index.html">\n            Spirituality\n           </a>\n          </li>\n          <li>\n           <a href="category/books/academic_40/index.html">\n            Academic\n           </a>\n          </li>\n          <li>\n           <a href="category/books/self-help_41/index.html">\n            Self Help\n           </a>\n          </li>\n          <li>\n           <a href="category/books/historical_42/index.html">\n            Historical\n           </a>\n          </li>\n          <li>\n           <a href="category/books/christian_43/index.html">\n            Christian\n           </a>\n          </li>\n          <li>\n           <a href="category/books/suspense_44/index.html">\n            Suspense\n           </a>\n          </li>\n          <li>\n           <a href="category/books/short-stories_45/index.html">\n            Short Stories\n           </a>\n          </li>\n          <li>\n           <a href="category/books/novels_46/index.html">\n            Novels\n           </a>\n          </li>\n          <li>\n           <a href="category/books/health_47/index.html">\n            Health\n           </a>\n          </li>\n          <li>\n           <a href="category/books/politics_48/index.html">\n            Politics\n           </a>\n          </li>\n          <li>\n           <a href="category/books/cultural_49/index.html">\n            Cultural\n           </a>\n          </li>\n          <li>\n           <a href="category/books/erotica_50/index.html">\n            Erotica\n           </a>\n          </li>\n          <li>\n           <a href="category/books/crime_51/index.html">\n            Crime\n           </a>\n          </li>\n         </ul>\n        </li>\n       </ul>\n      </div>\n     </aside>\n     <div class="col-sm-8 col-md-9">\n      <div class="page-header action">\n       <h1>\n        All products\n       </h1>\n      </div>\n      <div id="messages">\n      </div>\n      <div id="promotions">\n      </div>\n      <form class="form-horizontal" method="get">\n       <div style="display:none">\n       </div>\n       <strong>\n        1000\n       </strong>\n       results - showing\n       <strong>\n        21\n       </strong>\n       to\n       <strong>\n        40\n       </strong>\n       .\n      </form>\n      <section>\n       <div class="alert alert-warning" role="alert">\n        <strong>\n         Warning!\n        </strong>\n        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.\n       </div>\n       <div>\n        <ol class="row">\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="in-her-wake_980/index.html">\n             <img alt="In Her Wake" class="thumbnail" src="../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating One">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="in-her-wake_980/index.html" title="In Her Wake">\n             In Her Wake\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£12.84\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="how-music-works_979/index.html">\n             <img alt="How Music Works" class="thumbnail" src="../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Two">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="how-music-works_979/index.html" title="How Music Works">\n             How Music Works\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£37.32\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html">\n             <img alt="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More" class="thumbnail" src="../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html" title="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More">\n             Foolproof Preserving: A Guide ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£30.52\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="chase-me-paris-nights-2_977/index.html">\n             <img alt="Chase Me (Paris Nights #2)" class="thumbnail" src="../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="chase-me-paris-nights-2_977/index.html" title="Chase Me (Paris Nights #2)">\n             Chase Me (Paris Nights ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£25.27\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="black-dust_976/index.html">\n             <img alt="Black Dust" class="thumbnail" src="../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Five">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="black-dust_976/index.html" title="Black Dust">\n             Black Dust\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£34.53\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="birdsong-a-story-in-pictures_975/index.html">\n             <img alt="Birdsong: A Story in Pictures" class="thumbnail" src="../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="birdsong-a-story-in-pictures_975/index.html" title="Birdsong: A Story in Pictures">\n             Birdsong: A Story in ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£54.64\n            </p>\n            <p class="instock availability">\n             <i class="icon-ok">\n             </i>\n             In stock\n            </p>\n            <form>\n             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">\n              Add to basket\n             </button>\n            </form>\n           </div>\n          </article>\n         </li>\n         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n          <article class="product_pod">\n           <div class="image_container">\n            <a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html">\n             <img alt="America\'s Cradle of Quarterbacks: Western Pennsylvania\'s Football Factory from Johnny Unitas to Joe Montana" class="thumbnail" src="../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg"/>\n            </a>\n           </div>\n           <p class="star-rating Three">\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n            <i class="icon-star">\n            </i>\n           </p>\n           <h3>\n            <a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html" title="America\'s Cradle of Quarterbacks: Western Pennsylvania\'s Football Factory from Johnny Unitas to Joe Montana">\n             America\'s Cradle of Quarterbacks: ...\n            </a>\n           </h3>\n           <div class="product_price">\n            <p class="price_color">\n             Â£22.50\n            <

In [141]:
all_book = soup.find_all("li" , class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")
all_book

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="in-her-wake_980/index.html"><img alt="In Her Wake" class="thumbnail" src="../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="in-her-wake_980/index.html" title="In Her Wake">In Her Wake</a></h3>
 <div class="product_price">
 <p class="price_color">Â£12.84</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="how-music-works_979/index.html"><img alt="How Music Works" class="thumbnail" src="../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="how-music-works_979/index.html" title="How Music Works">How Music Works</a></h3>
 <div class="product_price">
 <p class="price_color">Â£37.32</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html"><img alt="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More" class="thumbnail" src="../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html" title="Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More">Foolproof Preserving: A Guide ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£30.52</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="chase-me-paris-nights-2_977/index.html"><img alt="Chase Me (Paris Nights #2)" class="thumbnail" src="../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="chase-me-paris-nights-2_977/index.html" title="Chase Me (Paris Nights #2)">Chase Me (Paris Nights ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£25.27</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="black-dust_976/index.html"><img alt="Black Dust" class="thumbnail" src="../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="black-dust_976/index.html" title="Black Dust">Black Dust</a></h3>
 <div class="product_price">
 <p class="price_color">Â£34.53</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="birdsong-a-story-in-pictures_975/index.html"><img alt="Birdsong: A Story in Pictures" class="thumbnail" src="../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="birdsong-a-story-in-pictures_975/index.html" title="Birdsong: A Story in Pictures">Birdsong: A Story in ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£54.64</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html"><img alt="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana" class="thumbnail" src="../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html" title="America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana">America's Cradle of Quarterbacks: ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.50</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="aladdin-and-his-wonderful-lamp_973/index.html"><img alt="Aladdin and His Wonderful Lamp" class="thumbnail" src="../media/cache/d6/da/d6da0371958068bbaf39ea9c174275cd.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="aladdin-and-his-wonderful-lamp_973/index.html" title="Aladdin and His Wonderful Lamp">Aladdin and His Wonderful ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.13</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html"><img alt="Worlds Elsewhere: Journeys Around Shakespeareâs Globe" class="thumbnail" src="../media/cache/2e/98/2e98c332bf8563b584784971541c4445.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="worlds-elsewhere-journeys-around-shakespeares-globe_972/index.html" title="Worlds Elsewhere: Journeys Around Shakespeareâs Globe">Worlds Elsewhere: Journeys Around ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£40.30</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="wall-and-piece_971/index.html"><img alt="Wall and Piece" class="thumbnail" src="../media/cache/a5/41/a5416b9646aaa7287baa287ec2590270.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="wall-and-piece_971/index.html" title="Wall and Piece">Wall and Piece</a></h3>
 <div class="product_price">
 <p class="price_color">Â£44.18</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html"><img alt="The Four Agreements: A Practical Guide to Personal Freedom" class="thumbnail" src="../media/cache/0f/7e/0f7ee69495c0df1d35723f012624a9f8.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html" title="The Four Agreements: A Practical Guide to Personal Freedom">The Four Agreements: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html"><img alt="The Five Love Languages: How to Express Heartfelt Commitment to Your Mate" class="thumbnail" src="../media/cache/38/c5/38c56fba316c07305643a8065269594e.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html" title="The Five Love Languages: How to Express Heartfelt Commitment to Your Mate">The Five Love Languages: ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£31.05</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-elephant-tree_968/index.html"><img alt="The Elephant Tree" class="thumbnail" src="../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe000744b.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-elephant-tree_968/index.html" title="The Elephant Tree">The Elephant Tree</a></h3>
 <div class="product_price">
 <p class="price_color">Â£23.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-bear-and-the-piano_967/index.html"><img alt="The Bear and the Piano" class="thumbnail" src="../media/cache/cf/bb/cfbb5e62715c6d888fd07794c9bab5d6.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-bear-and-the-piano_967/index.html" title="The Bear and the Piano">The Bear and the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£36.89</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="sophies-world_966/index.html"><img alt="Sophie's World" class="thumbnail" src="../media/cache/65/71/6571919836ec51ed54f0050c31d8a0cd.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="sophies-world_966/index.html" title="Sophie's World">Sophie's World</a></h3>
 <div class="product_price">
 <p class="price_color">Â£15.94</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="penny-maybe_965/index.html"><img alt="Penny Maybe" class="thumbnail" src="../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5fecee6a.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="penny-maybe_965/index.html" title="Penny Maybe">Penny Maybe</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="maude-1883-1993she-grew-up-with-the-country_964/index.html"><img alt="Maude (1883-1993):She Grew Up with the country" class="thumbnail" src="../media/cache/f5/88/f5889d038f5d8e949b494d147c2dcf54.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="maude-1883-1993she-grew-up-with-the-country_964/index.html" title="Maude (1883-1993):She Grew Up with the country">Maude (1883-1993):She Grew Up ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£18.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="in-a-dark-dark-wood_963/index.html"><img alt="In a Dark, Dark Wood" class="thumbnail" src="../media/cache/23/85/238570a1c284e730dbc737a7e631ae2b.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="in-a-dark-dark-wood_963/index.html" title="In a Dark, Dark Wood">In a Dark, Dark ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£19.63</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="behind-closed-doors_962/index.html"><img alt="Behind Closed Doors" class="thumbnail" src="../media/cache/e1/5c/e15c289ba58cea38519e1281e859f0c1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="behind-closed-doors_962/index.html" title="Behind Closed Doors">Behind Closed Doors</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.22</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="you-cant-bury-them-all-poems_961/index.html"><img alt="You can't bury them all: Poems" class="thumbnail" src="../media/cache/e9/20/e9203b733126c4a0832a1c7885dc27cf.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="you-cant-bury-them-all-poems_961/index.html" title="You can't bury them all: Poems">You can't bury them ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.63</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>]

In [142]:
dl = []
for sec in all_book:
    data = {
    "Product Name" : "",
    "Product Image" : "",
    "Product Price" : "",
    "Product Avail" : ""

}
    data["Product Name"] = sec.find("h3").text.strip()
    data["Product Image"] = sec.find("img")["src"]
    data["Product Price"] = sec.find("p" , class_ = "price_color").text.strip()
    data["Product Avail"] = sec.find("p" , class_ = "instock availability").text.strip()
    dl.append(data)
dl

[{'Product Name': 'In Her Wake',
  'Product Image': '../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg',
  'Product Price': 'Â£12.84',
  'Product Avail': 'In stock'},
 {'Product Name': 'How Music Works',
  'Product Image': '../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg',
  'Product Price': 'Â£37.32',
  'Product Avail': 'In stock'},
 {'Product Name': 'Foolproof Preserving: A Guide ...',
  'Product Image': '../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg',
  'Product Price': 'Â£30.52',
  'Product Avail': 'In stock'},
 {'Product Name': 'Chase Me (Paris Nights ...',
  'Product Image': '../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg',
  'Product Price': 'Â£25.27',
  'Product Avail': 'In stock'},
 {'Product Name': 'Black Dust',
  'Product Image': '../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg',
  'Product Price': 'Â£34.53',
  'Product Avail': 'In stock'},
 {'Product Name': 'Birdsong: A Story in ...',
  'Product Image': '../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg',
  'Product Price': 'Â£54.64',
  'Product Avail': 'In stock'},
 {'Product Name': "America's Cradle of Quarterbacks: ...",
  'Product Image': '../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg',
  'Product Price': 'Â£22.50',
  'Product Avail': 'In stock'},
 {'Product Name': 'Aladdin and His Wonderful ...',
  'Product Image': '../media/cache/d6/da/d6da0371958068bbaf39ea9c174275cd.jpg',
  'Product Price': 'Â£53.13',
  'Product Avail': 'In stock'},
 {'Product Name': 'Worlds Elsewhere: Journeys Around ...',
  'Product Image': '../media/cache/2e/98/2e98c332bf8563b584784971541c4445.jpg',
  'Product Price': 'Â£40.30',
  'Product Avail': 'In stock'},
 {'Product Name': 'Wall and Piece',
  'Product Image': '../media/cache/a5/41/a5416b9646aaa7287baa287ec2590270.jpg',
  'Product Price': 'Â£44.18',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Four Agreements: A ...',
  'Product Image': '../media/cache/0f/7e/0f7ee69495c0df1d35723f012624a9f8.jpg',
  'Product Price': 'Â£17.66',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Five Love Languages: ...',
  'Product Image': '../media/cache/38/c5/38c56fba316c07305643a8065269594e.jpg',
  'Product Price': 'Â£31.05',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Elephant Tree',
  'Product Image': '../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe000744b.jpg',
  'Product Price': 'Â£23.82',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Bear and the ...',
  'Product Image': '../media/cache/cf/bb/cfbb5e62715c6d888fd07794c9bab5d6.jpg',
  'Product Price': 'Â£36.89',
  'Product Avail': 'In stock'},
 {'Product Name': "Sophie's World",
  'Product Image': '../media/cache/65/71/6571919836ec51ed54f0050c31d8a0cd.jpg',
  'Product Price': 'Â£15.94',
  'Product Avail': 'In stock'},
 {'Product Name': 'Penny Maybe',
  'Product Image': '../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5fecee6a.jpg',
  'Product Price': 'Â£33.29',
  'Product Avail': 'In stock'},
 {'Product Name': 'Maude (1883-1993):She Grew Up ...',
  'Product Image': '../media/cache/f5/88/f5889d038f5d8e949b494d147c2dcf54.jpg',
  'Product Price': 'Â£18.02',
  'Product Avail': 'In stock'},
 {'Product Name': 'In a Dark, Dark ...',
  'Product Image': '../media/cache/23/85/238570a1c284e730dbc737a7e631ae2b.jpg',
  'Product Price': 'Â£19.63',
  'Product Avail': 'In stock'},
 {'Product Name': 'Behind Closed Doors',
  'Product Image': '../media/cache/e1/5c/e15c289ba58cea38519e1281e859f0c1.jpg',
  'Product Price': 'Â£52.22',
  'Product Avail': 'In stock'},
 {'Product Name': "You can't bury them ...",
  'Product Image': '../media/cache/e9/20/e9203b733126c4a0832a1c7885dc27cf.jpg',
  'Product Price': 'Â£33.63',
  'Product Avail': 'In stock'}]

In [143]:
df = pd.DataFrame(dl)
df

,Product Name,Product Image,Product Price,Product Avail
0,In Her Wake,../media/cache/5d/72/5d72709c6a7a9584a4d1cf076...,Â£12.84,In stock
1,How Music Works,../media/cache/5c/c8/5cc8e107246cb478960d4f0ab...,Â£37.32,In stock
2,Foolproof Preserving: A Guide ...,../media/cache/9f/59/9f59f01fa916a7bb8f0b28a40...,Â£30.52,In stock
3,Chase Me (Paris Nights ...,../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994f...,Â£25.27,In stock
4,Black Dust,../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4...,Â£34.53,In stock
5,Birdsong: A Story in ...,../media/cache/af/6e/af6e796160fe63e0cf19d4439...,Â£54.64,In stock
6,America's Cradle of Quarterbacks: ...,../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb...,Â£22.50,In stock
7,Aladdin and His Wonderful ...,../media/cache/d6/da/d6da0371958068bbaf39ea9c1...,Â£53.13,In stock
8,Worlds Elsewhere: Journeys Around ...,../media/cache/2e/98/2e98c332bf8563b5847849715...,Â£40.30,In stock
9,Wall and Piece,../media/cache/a5/41/a5416b9646aaa7287baa287ec...,Â£44.18,In stock
10,The Four Agreements: A ...,../media/cache/0f/7e/0f7ee69495c0df1d35723f012...,Â£17.66,In stock
11,The Five Love Languages: ...,../media/cache/38/c5/38c56fba316c07305643a8065...,Â£31.05,In stock
12,The Elephant Tree,../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe...,Â£23.82,In stock
13,The Bear and the ...,../media/cache/cf/bb/cfbb5e62715c6d888fd07794c...,Â£36.89,In stock
14,Sophie's World,../media/cache/65/71/6571919836ec51ed54f0050c3...,Â£15.94,In stock
15,Penny Maybe,../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5...,Â£33.29,In stock
16,Maude (1883-1993):She Grew Up ...,../media/cache/f5/88/f5889d038f5d8e949b494d147...,Â£18.02,In stock
17,"In a Dark, Dark ...",../media/cache/23/85/238570a1c284e730dbc737a7e...,Â£19.63,In stock
18,Behind Closed Doors,../media/cache/e1/5c/e15c289ba58cea38519e1281e...,Â£52.22,In stock
19,You can't bury them ...,../media/cache/e9/20/e9203b733126c4a0832a1c788...,Â£33.63,In stock

In [144]:
df.to_csv("book_toscrape_q3.8.csv")

### 3.9 Extract all product details from first page to fifth page & save into single csv file.

In [4]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
dl = []
for page in range(1,6):
    url=f"https://books.toscrape.com/catalogue/page-{page}.html"
    r = requests.get(url)
    soup = BeautifulSoup(r.text , "html.parser")
    all_book = soup.find_all("li" , class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")

    for sec in all_book:
        data = {
    "Product Name" : "",
    "Product Image" : "",
    "Product Price" : "",
    "Product Avail" : ""

    }
        data["Product Name"] = sec.find("h3").text.strip()
        data["Product Image"] = sec.find("img")["src"]
        data["Product Price"] = sec.find("p" , class_ = "price_color").text.strip()
        data["Product Avail"] = sec.find("p" , class_ = "instock availability").text.strip()
        dl.append(data)
dl

[{'Product Name': 'A Light in the ...',
  'Product Image': '../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg',
  'Product Price': 'Â£51.77',
  'Product Avail': 'In stock'},
 {'Product Name': 'Tipping the Velvet',
  'Product Image': '../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg',
  'Product Price': 'Â£53.74',
  'Product Avail': 'In stock'},
 {'Product Name': 'Soumission',
  'Product Image': '../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg',
  'Product Price': 'Â£50.10',
  'Product Avail': 'In stock'},
 {'Product Name': 'Sharp Objects',
  'Product Image': '../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg',
  'Product Price': 'Â£47.82',
  'Product Avail': 'In stock'},
 {'Product Name': 'Sapiens: A Brief History ...',
  'Product Image': '../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg',
  'Product Price': 'Â£54.23',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Requiem Red',
  'Product Image': '../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg',
  'Product Price': 'Â£22.65',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Dirty Little Secrets ...',
  'Product Image': '../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg',
  'Product Price': 'Â£33.34',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Coming Woman: A ...',
  'Product Image': '../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg',
  'Product Price': 'Â£17.93',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Boys in the ...',
  'Product Image': '../media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg',
  'Product Price': 'Â£22.60',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Black Maria',
  'Product Image': '../media/cache/58/46/5846057e28022268153beff6d352b06c.jpg',
  'Product Price': 'Â£52.15',
  'Product Avail': 'In stock'},
 {'Product Name': 'Starving Hearts (Triangular Trade ...',
  'Product Image': '../media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg',
  'Product Price': 'Â£13.99',
  'Product Avail': 'In stock'},
 {'Product Name': "Shakespeare's Sonnets",
  'Product Image': '../media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg',
  'Product Price': 'Â£20.66',
  'Product Avail': 'In stock'},
 {'Product Name': 'Set Me Free',
  'Product Image': '../media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg',
  'Product Price': 'Â£17.46',
  'Product Avail': 'In stock'},
 {'Product Name': "Scott Pilgrim's Precious Little ...",
  'Product Image': '../media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg',
  'Product Price': 'Â£52.29',
  'Product Avail': 'In stock'},
 {'Product Name': 'Rip it Up and ...',
  'Product Image': '../media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg',
  'Product Price': 'Â£35.02',
  'Product Avail': 'In stock'},
 {'Product Name': 'Our Band Could Be ...',
  'Product Image': '../media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg',
  'Product Price': 'Â£57.25',
  'Product Avail': 'In stock'},
 {'Product Name': 'Olio',
  'Product Image': '../media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg',
  'Product Price': 'Â£23.88',
  'Product Avail': 'In stock'},
 {'Product Name': 'Mesaerion: The Best Science ...',
  'Product Image': '../media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg',
  'Product Price': 'Â£37.59',
  'Product Avail': 'In stock'},
 {'Product Name': 'Libertarianism for Beginners',
  'Product Image': '../media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg',
  'Product Price': 'Â£51.33',
  'Product Avail': 'In stock'},
 {'Product Name': "It's Only the Himalayas",
  'Product Image': '../media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg',
  'Product Price': 'Â£45.17',
  'Product Avail': 'In stock'},
 {'Product Name': 'In Her Wake',
  'Product Image': '../media/cache/5d/72/5d72709c6a7a9584a4d1cf07648bfce1.jpg',
  'Product Price': 'Â£12.84',
  'Product Avail': 'In stock'},
 {'Product Name': 'How Music Works',
  'Product Image': '../media/cache/5c/c8/5cc8e107246cb478960d4f0aba1e1c8e.jpg',
  'Product Price': 'Â£37.32',
  'Product Avail': 'In stock'},
 {'Product Name': 'Foolproof Preserving: A Guide ...',
  'Product Image': '../media/cache/9f/59/9f59f01fa916a7bb8f0b28a4012179a4.jpg',
  'Product Price': 'Â£30.52',
  'Product Avail': 'In stock'},
 {'Product Name': 'Chase Me (Paris Nights ...',
  'Product Image': '../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994fd3d1c1a.jpg',
  'Product Price': 'Â£25.27',
  'Product Avail': 'In stock'},
 {'Product Name': 'Black Dust',
  'Product Image': '../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4ef25787.jpg',
  'Product Price': 'Â£34.53',
  'Product Avail': 'In stock'},
 {'Product Name': 'Birdsong: A Story in ...',
  'Product Image': '../media/cache/af/6e/af6e796160fe63e0cf19d44395c7ddf2.jpg',
  'Product Price': 'Â£54.64',
  'Product Avail': 'In stock'},
 {'Product Name': "America's Cradle of Quarterbacks: ...",
  'Product Image': '../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb98d9c36.jpg',
  'Product Price': 'Â£22.50',
  'Product Avail': 'In stock'},
 {'Product Name': 'Aladdin and His Wonderful ...',
  'Product Image': '../media/cache/d6/da/d6da0371958068bbaf39ea9c174275cd.jpg',
  'Product Price': 'Â£53.13',
  'Product Avail': 'In stock'},
 {'Product Name': 'Worlds Elsewhere: Journeys Around ...',
  'Product Image': '../media/cache/2e/98/2e98c332bf8563b584784971541c4445.jpg',
  'Product Price': 'Â£40.30',
  'Product Avail': 'In stock'},
 {'Product Name': 'Wall and Piece',
  'Product Image': '../media/cache/a5/41/a5416b9646aaa7287baa287ec2590270.jpg',
  'Product Price': 'Â£44.18',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Four Agreements: A ...',
  'Product Image': '../media/cache/0f/7e/0f7ee69495c0df1d35723f012624a9f8.jpg',
  'Product Price': 'Â£17.66',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Five Love Languages: ...',
  'Product Image': '../media/cache/38/c5/38c56fba316c07305643a8065269594e.jpg',
  'Product Price': 'Â£31.05',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Elephant Tree',
  'Product Image': '../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe000744b.jpg',
  'Product Price': 'Â£23.82',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Bear and the ...',
  'Product Image': '../media/cache/cf/bb/cfbb5e62715c6d888fd07794c9bab5d6.jpg',
  'Product Price': 'Â£36.89',
  'Product Avail': 'In stock'},
 {'Product Name': "Sophie's World",
  'Product Image': '../media/cache/65/71/6571919836ec51ed54f0050c31d8a0cd.jpg',
  'Product Price': 'Â£15.94',
  'Product Avail': 'In stock'},
 {'Product Name': 'Penny Maybe',
  'Product Image': '../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5fecee6a.jpg',
  'Product Price': 'Â£33.29',
  'Product Avail': 'In stock'},
 {'Product Name': 'Maude (1883-1993):She Grew Up ...',
  'Product Image': '../media/cache/f5/88/f5889d038f5d8e949b494d147c2dcf54.jpg',
  'Product Price': 'Â£18.02',
  'Product Avail': 'In stock'},
 {'Product Name': 'In a Dark, Dark ...',
  'Product Image': '../media/cache/23/85/238570a1c284e730dbc737a7e631ae2b.jpg',
  'Product Price': 'Â£19.63',
  'Product Avail': 'In stock'},
 {'Product Name': 'Behind Closed Doors',
  'Product Image': '../media/cache/e1/5c/e15c289ba58cea38519e1281e859f0c1.jpg',
  'Product Price': 'Â£52.22',
  'Product Avail': 'In stock'},
 {'Product Name': "You can't bury them ...",
  'Product Image': '../media/cache/e9/20/e9203b733126c4a0832a1c7885dc27cf.jpg',
  'Product Price': 'Â£33.63',
  'Product Avail': 'In stock'},
 {'Product Name': 'Slow States of Collapse: ...',
  'Product Image': '../media/cache/72/41/72417db983862010ef0c1a25de98c7d7.jpg',
  'Product Price': 'Â£57.31',
  'Product Avail': 'In stock'},
 {'Product Name': 'Reasons to Stay Alive',
  'Product Image': '../media/cache/cb/bd/cbbdb0222ee8a0f6ab61657412a15794.jpg',
  'Product Price': 'Â£26.41',
  'Product Avail': 'In stock'},
 {'Product Name': 'Private Paris (Private #10)',
  'Product Image': '../media/cache/9d/05/9d0533bae1578846d728a82913b95c26.jpg',
  'Product Price': 'Â£47.61',
  'Product Avail': 'In stock'},
 {'Product Name': '#HigherSelfie: Wake Up Your ...',
  'Product Image': '../media/cache/9c/46/9c463c7631c82401160fd3b554b8f0e1.jpg',
  'Product Price': 'Â£23.11',
  'Product Avail': 'In stock'},
 {'Product Name': 'Without Borders (Wanderlove #1)',
  'Product Image': '../media/cache/24/e2/24e2f5c9d325c4004d8190c054da86dd.jpg',
  'Product Price': 'Â£45.07',
  'Product Avail': 'In stock'},
 {'Product Name': 'When We Collided',
  'Product Image': '../media/cache/08/04/08044269fc197645268a6197c57e6173.jpg',
  'Product Price': 'Â£31.77',
  'Product Avail': 'In stock'},
 {'Product Name': 'We Love You, Charlie ...',
  'Product Image': '../media/cache/5f/15/5f152afdbc42356ecba02f61058a7e5b.jpg',
  'Product Price': 'Â£50.27',
  'Product Avail': 'In stock'},
 {'Product Name': 'Untitled Collection: Sabbath Poems ...',
  'Product Image': '../media/cache/f9/3b/f93b4a650f03a5d21f2436d7813f42c2.jpg',
  'Product Price': 'Â£14.27',
  'Product Avail': 'In stock'},
 {'Product Name': 'Unseen City: The Majesty ...',
  'Product Image': '../media/cache/41/a2/41a20f35adf0caea24f208dc01ad7681.jpg',
  'Product Price': 'Â£44.18',
  'Product Avail': 'In stock'},
 {'Product Name': 'Unicorn Tracks',
  'Product Image': '../media/cache/76/8e/768ea5924ac1ef6297c2be9959c796c2.jpg',
  'Product Price': 'Â£18.78',
  'Product Avail': 'In stock'},
 {'Product Name': 'Unbound: How Eight Technologies ...',
  'Product Image': '../media/cache/4a/3b/4a3b055f9e378a95fedbef55e7bab7ce.jpg',
  'Product Price': 'Â£25.52',
  'Product Avail': 'In stock'},
 {'Product Name': 'Tsubasa: WoRLD CHRoNiCLE 2 ...',
  'Product Image': '../media/cache/36/df/36df4caaf1420b1183a8235355d39e69.jpg',
  'Product Price': 'Â£16.28',
  'Product Avail': 'In stock'},
 {'Product Name': 'Throwing Rocks at the ...',
  'Product Image': '../media/cache/03/86/038650c9e7517b4baf2a423cd8eed38f.jpg',
  'Product Price': 'Â£31.12',
  'Product Avail': 'In stock'},
 {'Product Name': 'This One Summer',
  'Product Image': '../media/cache/c4/dd/c4ddd9ced89966b0602ec85e00cd5b61.jpg',
  'Product Price': 'Â£19.49',
  'Product Avail': 'In stock'},
 {'Product Name': 'Thirst',
  'Product Image': '../media/cache/c4/0a/c40a64f59e7487b1a80a049f6ceb2ba5.jpg',
  'Product Price': 'Â£17.27',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Torch Is Passed: ...',
  'Product Image': '../media/cache/33/e5/33e507172541628acfd421503196b578.jpg',
  'Product Price': 'Â£19.09',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Secret of Dreadwillow ...',
  'Product Image': '../media/cache/c4/a2/c4a2a1a026c67bcceb5a411c724d7d0c.jpg',
  'Product Price': 'Â£56.13',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Pioneer Woman Cooks: ...',
  'Product Image': '../media/cache/b7/f4/b7f4843dbe062d44be1ffcfa16b2faa4.jpg',
  'Product Price': 'Â£56.41',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Past Never Ends',
  'Product Image': '../media/cache/89/b8/89b850edb01851a91f64ba114b96acb6.jpg',
  'Product Price': 'Â£56.50',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Natural History of ...',
  'Product Image': '../media/cache/5d/7f/5d7f496cdf5e5962a73ecdcc1505c1d5.jpg',
  'Product Price': 'Â£45.22',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Nameless City (The ...',
  'Product Image': '../media/cache/f4/79/f479de5f305c2ac0512702cf7155bb74.jpg',
  'Product Price': 'Â£38.16',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Murder That Never ...',
  'Product Image': '../media/cache/dc/44/dc44f8e2aebac48ca8553814d9b021a8.jpg',
  'Product Price': 'Â£54.11',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Most Perfect Thing: ...',
  'Product Image': '../media/cache/d4/8d/d48d5122a15347e9fe2b15ad354d69bf.jpg',
  'Product Price': 'Â£42.96',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Mindfulness and Acceptance ...',
  'Product Image': '../media/cache/f8/6d/f86d08178e3788563ac17be5aefd29f0.jpg',
  'Product Price': 'Â£23.89',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Life-Changing Magic of ...',
  'Product Image': '../media/cache/95/64/95647d6a526bf54120b9445e124794e1.jpg',
  'Product Price': 'Â£16.77',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Inefficiency Assassin: Time ...',
  'Product Image': '../media/cache/75/dc/75dce2f5949b407161f37f0af249b018.jpg',
  'Product Price': 'Â£20.59',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Gutsy Girl: Escapades ...',
  'Product Image': '../media/cache/64/15/641570cd7e7aded53c7d33d78a9629f1.jpg',
  'Product Price': 'Â£37.13',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Electric Pencil: Drawings ...',
  'Product Image': '../media/cache/2e/23/2e236e23ad52aa74505f224f6552eda8.jpg',
  'Product Price': 'Â£56.06',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Death of Humanity: ...',
  'Product Image': '../media/cache/71/df/71df730cf38c232ee58a2e407135f055.jpg',
  'Product Price': 'Â£58.11',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Bulletproof Diet: Lose ...',
  'Product Image': '../media/cache/ee/3e/ee3e219d23e73ba71c79b700f183aaed.jpg',
  'Product Price': 'Â£49.05',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Art Forger',
  'Product Image': '../media/cache/70/fa/70fa6c0437d9c97dbeada6bd32bf9d2c.jpg',
  'Product Price': 'Â£40.76',
  'Product Avail': 'In stock'},
 {'Product Name': 'The Age of Genius: ...',
  'Product Image': '../media/cache/2d/4e/2d4e358712e6c9f1d3bdd78d1a16e5a8.jpg',
  'Product Price': 'Â£19.73',
  'Product Avail': 'In stock'},
 {'Product Name': "The Activist's Tao Te ...",
  'Product Image': '../media/cache/96/db/96db61bb53930c560fb4c1c62b583816.jpg',
  'Product Price': 'Â£32.24',
  'Product Avail': 'In stock'},
 {'Product Name': 'Spark Joy: An Illustrated ...',
  'Product Image': '../media/cache/f3/4f/f34ffb24cc21c9f9f52dad4fd8f3ac21.jpg',
  'Product Price': 'Â£41.83',
  'Product Avail': 'In stock'},
 {'Product Name': 'Soul Reader',
  'Product Image': '../media/cache/69/85/69852567cf97264a1442cbc882c84903.jpg',
  'Product Price': 'Â£39.58',
  'Product Avail': 'In stock'},
 {'Product Name': 'Security',
  'Product Image': '../media/cache/da/df/dadfac66a89774b46b10225362724c83.jpg',
  'Product Price': 'Â£39.25',
  'Product Avail': 'In stock'},
 {'Product Name': 'Saga, Volume 6 (Saga ...',
  'Product Image': '../media/cache/43/ae/43aee83ebb31e2122a7215e413770e5c.jpg',
  'Product Price': 'Â£25.02',
  'Product Avail': 'In stock'},
 {'Product Name': 'Saga, Volume 5 (Saga ...',
  'Product Image': '../media/cache/e1/ea/e1ea6cb36e62ae6dc7b805f68ab9a700.jpg',
  'Product Price': 'Â£51.04',
  'Product Avail': 'In stock'},
 {'Product Name': 'Reskilling America: Learning to ...',
  'Product Image': '../media/cache/97/f8/97f8debeeaaece9603267653076e760f.jpg',
  'Product Price': 'Â£19.83',
  'Product Avail': 'In stock'},
 {'Product Name': 'Rat Queens, Vol. 3: ...',
  'Product Image': '../media/cache/f3/ef/f3efd43ae0fa85d9b325d5e8783e7af5.jpg',
  'Product Price': 'Â£50.40',
  'Product Avail': 'In stock'},
 {'Product Name': 'Princess Jellyfish 2-in-1 Omnibus, ...',
  'Product Image': '../media/cache/78/0b/780b2c28122750c2c383846155815bf7.jpg',
  'Product Price': 'Â£13.61',
  'Product Avail': 'In stock'},
 {'Product Name': 'Princess Between Worlds (Wide-Awake ...',
  'Product Image': '../media/cache/b7/e8/b7e84b78be3d9bb79b71156a5e5d4e42.jpg',
  'Product Price': 'Â£13.34',
  'Product Avail': 'In stock'},
 {'Product Name': 'Pop Gun War, Volume ...',
  'Product Image': '../media/cache/c8/2f/c82f629a31b3f47bdb17ac14aa51076d.jpg',
  'Product Price': 'Â£18.97',
  'Product Avail': 'In stock'},
 {'Product Name': 'Political Suicide: Missteps, Peccadilloes, ...',
  'Product Image': '../media/cache/64/44/6444dacdcb9edaadbbd691524622aeb8.jpg',
  'Product Price': 'Â£36.28',
  'Product Avail': 'In stock'},
 {'Product Name': 'Patience',
  'Product Image': '../media/cache/01/72/01726c619a05114dca75bd840095016d.jpg',
  'Product Price': 'Â£10.16',
  'Product Avail': 'In stock'},
 {'Product Name': 'Outcast, Vol. 1: A ...',
  'Product Image': '../media/cache/cb/00/cb004189f548d75ad430d3ed19e6daa9.jpg',
  'Product Price': 'Â£15.44',
  'Product Avail': 'In stock'},
 {'Product Name': 'orange: The Complete Collection ...',
  'Product Image': '../media/cache/03/88/03886a8502ca54dbce0d91c2568ab69d.jpg',
  'Product Price': 'Â£48.41',
  'Product Avail': 'In stock'},
 {'Product Name': 'Online Marketing for Busy ...',
  'Product Image': '../media/cache/ea/9b/ea9b2cb8abbb317402e618445bade1e1.jpg',
  'Product Price': 'Â£46.35',
  'Product Avail': 'In stock'},
 {'Product Name': 'On a Midnight Clear',
  'Product Image': '../media/cache/a1/14/a114d70e7babf110ba42a389078e9a45.jpg',
  'Product Price': 'Â£14.07',
  'Product Avail': 'In stock'},
 {'Product Name': 'Obsidian (Lux #1)',
  'Product Image': '../media/cache/fc/72/fc72f158554b4b4164701e1dfa1153c7.jpg',
  'Product Price': 'Â£14.86',
  'Product Avail': 'In stock'},
 {'Product Name': 'My Paris Kitchen: Recipes ...',
  'Product Image': '../media/cache/f5/65/f565af3d9dd20a1ad72a1e7c4157387d.jpg',
  'Product Price': 'Â£33.37',
  'Product Avail': 'In stock'},
 {'Product Name': 'Masks and Shadows',
  'Product Image': '../media/cache/ff/e8/ffe81bf98f8386ef29e193abfb6f9c1e.jpg',
  'Product Price': 'Â£56.40',
  'Product Avail': 'In stock'},
 {'Product Name': 'Mama Tried: Traditional Italian ...',
  'Product Image': '../media/cache/10/c6/10c61093002db1fec4089d8076678624.jpg',
  'Product Price': 'Â£14.02',
  'Product Avail': 'In stock'},
 {'Product Name': 'Lumberjanes, Vol. 2: Friendship ...',
  'Product Image': '../media/cache/d3/15/d3158e8d3546fb90cced3c1d44a92a34.jpg',
  'Product Price': 'Â£46.91',
  'Product Avail': 'In stock'},
 {'Product Name': 'Lumberjanes, Vol. 1: Beware ...',
  'Product Image': '../media/cache/7e/a0/7ea062007ef00107e3c16d336b41fab2.jpg',
  'Product Price': 'Â£45.61',
  'Product Avail': 'In stock'},
 {'Product Name': 'Lumberjanes Vol. 3: A ...',
  'Product Image': '../media/cache/5f/b1/5fb1bf88dcfda795606745ce35be5975.jpg',
  'Product Price': 'Â£19.92',
  'Product Avail': 'In stock'},
 {'Product Name': 'Layered: Baking, Building, and ...',
  'Product Image': '../media/cache/98/d1/98d1c979c4bac9e147a6718946578b0f.jpg',
  'Product Price': 'Â£40.11',
  'Product Avail': 'In stock'},
 {'Product Name': 'Judo: Seven Steps to ...',
  'Product Image': '../media/cache/5f/52/5f52b1bc6d45daab2e330c744feb0359.jpg',
  'Product Price': 'Â£53.90',
  'Product Avail': 'In stock'},
 {'Product Name': 'Join',
  'Product Image': '../media/cache/93/63/9363f0065fbad5689f44fcf6e203eef3.jpg',
  'Product Price': 'Â£35.67',
  'Product Avail': 'In stock'},
 {'Product Name': 'In the Country We ...',
  'Product Image': '../media/cache/fe/ea/feeafd2ad7b3077f8e74cbb1da9e3c7d.jpg',
  'Product Price': 'Â£22.00',
  'Product Avail': 'In stock'}]

In [5]:
len(dl)

100

In [6]:
df = pd.DataFrame(dl)
df

,Product Name,Product Image,Product Price,Product Avail
0,A Light in the ...,../media/cache/2c/da/2cdad67c44b002e7ead0cc356...,Â£51.77,In stock
1,Tipping the Velvet,../media/cache/26/0c/260c6ae16bce31c8f8c95dadd...,Â£53.74,In stock
2,Soumission,../media/cache/3e/ef/3eef99c9d9adef34639f51066...,Â£50.10,In stock
3,Sharp Objects,../media/cache/32/51/3251cf3a3412f53f339e42cac...,Â£47.82,In stock
4,Sapiens: A Brief History ...,../media/cache/be/a5/bea5697f2534a2f86a3ef27b5...,Â£54.23,In stock
...,...,...,...,...
95,Lumberjanes Vol. 3: A ...,../media/cache/5f/b1/5fb1bf88dcfda795606745ce3...,Â£19.92,In stock
96,"Layered: Baking, Building, and ...",../media/cache/98/d1/98d1c979c4bac9e147a671894...,Â£40.11,In stock
97,Judo: Seven Steps to ...,../media/cache/5f/52/5f52b1bc6d45daab2e330c744...,Â£53.90,In stock
98,Join,../media/cache/93/63/9363f0065fbad5689f44fcf6e...,Â£35.67,In stock
99,In the Country We ...,../media/cache/fe/ea/feeafd2ad7b3077f8e74cbb1d...,Â£22.00,In stock

In [7]:
df.to_csv("book_toscrape_q3.9.csv")

### 8. https://books.toscrape.com/ (Product_name(full name click via clicking on product url),Product_Description, UPC, Product_Type, Price_excl_tax, Price_incl_tax, Tax, Availability_numbers, Number_of_reviews, product_img, product_reviews_star_no, product_price, product_availabililty)

### 8.1 Extract first product details save into csv file. e.g# A Light in the ...

In [29]:
dict_pro = {
    "Product_name":"",
    "product_url":"",

    "Product_Description":"",
    "UPC":"", 
    # "Product_Type":"",
    # "Price_excl_tax":"",
    # "Price_incl_tax":"",
    "Tax":"",
    # "Availability_numbers":"",
    # "Number_of_reviews":"",
    "product_img":"",
    "product_reviews_star_no":"",
    "product_price":"",
    "product_availabililty":""
}

In [30]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
main_url = "https://books.toscrape.com/"
r = requests.get(main_url)
r.status_code

200

In [31]:
soup = BeautifulSoup(r.text,"html")
products = soup.find_all("li",class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3") # finding all products div
print("total products are ",len(products))
products

total products are  20

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.74</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
 <div class="product_price">
 <p class="price_color">Â£50.10</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
 <div class="product_price">
 <p class="price_color">Â£47.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£54.23</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.65</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.34</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.93</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.60</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.15</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£13.99</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
 <div class="product_price">
 <p class="price_color">Â£20.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.46</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£35.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html"><img alt="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991" class="thumbnail" src="media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£57.25</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/olio_984/index.html"><img alt="Olio" class="thumbnail" src="media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
 <div class="product_price">
 <p class="price_color">Â£23.88</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£37.59</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.33</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>,
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
 <div class="product_price">
 <p class="price_color">Â£45.17</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>]

In [44]:
list = []

dict_pro = {
"Product_name":"",
"product_url":"",
"product_img":"",
"product_price":"",
"product_availabililty":""
}
dict_pro["Product_name"]= fst_pro.find("h3").text
dict_pro["product_price"]= fst_pro.find("p",class_ = "price_color").text
dict_pro["product_availabililty"]= fst_pro.find("p",class_ = "instock availability").text.strip()
dict_pro["product_img"]= fst_pro.find("img")["src"]
dict_pro["product_url"]= fst_pro.find("a")["href"]

In [45]:
fst_pro = products[0]

dict_pro["Product_name"]= fst_pro.find("h3").text
dict_pro["product_price"]= fst_pro.find("p",class_ = "price_color").text
dict_pro["product_availabililty"]= fst_pro.find("p",class_ = "instock availability").text.strip()
dict_pro["product_img"]= fst_pro.find("img")["src"]
dict_pro["product_url"]= fst_pro.find("a")["href"]
dict_pro

{'Product_name': 'A Light in the ...',
 'product_url': 'catalogue/a-light-in-the-attic_1000/index.html',
 'product_img': 'media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg',
 'product_price': 'Â£51.77',
 'product_availabililty': 'In stock'}

In [46]:
act_url = main_url + dict_pro["product_url"]

req = requests.get(act_url)

soup_nw = BeautifulSoup(req.text,"html")

dict_pro["Product_Description"] =  soup_nw.find("article",class_ = "product_page").find_all("p")[-1].text
# dict_pro["Product_Description"] =  soup_nw.find("div",id = "product_description").find_next_sibling().text.strip()


for i in soup_nw.find_all("tr"):
    dict_pro[i.find("th").text] = i.find("td").text

dict_pro["Product_name"] = soup_nw.find("h1").text
dict_pro["product_reviews_star_no"] =  soup_nw.find("p",class_ = "star-rating").attrs["class"][1]
dict_pro

{'Product_name': 'A Light in the Attic',
 'product_url': 'catalogue/a-light-in-the-attic_1000/index.html',
 'product_img': 'media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg',
 'product_price': 'Â£51.77',
 'product_availabililty': 'In stock',
 'Product_Description': "It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more",
 'UPC': 'a897fe39b1053632',
 'Product Type': 'Books',
 'Price (excl. tax)': 'Â£51.77',
 'Price (incl. tax)': 'Â£51.77',
 'Tax': 'Â£0.00',
 'Availability': 'In stock (22 available)',
 'Number of reviews': '0',
 'product_reviews_star_no': 'Three'}

In [47]:
list.append(dict_pro)

In [49]:
df = pd.DataFrame(list)
df

,Product_name,product_url,product_img,product_price,product_availabililty,Product_Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,product_reviews_star_no
0,A Light in the Attic,catalogue/a-light-in-the-attic_1000/index.html,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,Â£51.77,In stock,It's hard to imagine a world without A Light i...,a897fe39b1053632,Books,Â£51.77,Â£51.77,Â£0.00,In stock (22 available),0,Three

In [50]:
df.to_csv("books_toscrape_qm8.1.csv")

### m8.2 Extract product details from first row & save into csv file. e.g# A Light in the ..., Tipping the Velvet, Soumission

In [12]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

main_url = "https://books.toscrape.com/"

r = requests.get(main_url)
r.status_code

200

In [13]:
soup = BeautifulSoup(r.text, "html.parser")
products = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")[0:4]

In [22]:
all_products = []

for item in products:

    # step 2: detailed page crawl
    req = requests.get(base["product_url"])
    soup2 = BeautifulSoup(req.text, "html.parser")
    base["Product Name"] = soup2.find("h1").text
    base["Product_Description"] = soup2.find("div", id="product_description").find_next_sibling().text.strip()

    for tr in soup2.find_all("tr"):
        base[tr.find("th").text] = tr.find("td").text

    # basic data
    base = {
        "product_price": item.find("p", class_="price_color").text,
        "product_availability": item.find("p", class_="instock availability").text.strip(),
        "product_img": item.find("img")["src"],
        "product_url": main_url + item.find("a")["href"]
    }
    base["product_reviews_star_no"] = soup2.find("p", class_="star-rating")["class"][1]

    all_products.append(base)

df = pd.DataFrame(all_products)
df.to_csv("book_toscrape_qm8.2.csv", index=False)

df

,product_price,product_availability,product_img,product_url,product_reviews_star_no,Product Name,Product_Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews
0,Â£51.77,In stock,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,https://books.toscrape.com/catalogue/a-light-i...,One,A Light in the Attic,It's hard to imagine a world without A Light i...,a897fe39b1053632,Books,Â£51.77,Â£51.77,Â£0.00,In stock (22 available),0
1,Â£54.23,In stock,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...,https://books.toscrape.com/catalogue/sapiens-a...,Three,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,4165285e1663650f,Books,Â£54.23,Â£54.23,Â£0.00,In stock (20 available),0
2,Â£22.60,In stock,media/cache/66/88/66883b91f6804b2323c8369331cb...,https://books.toscrape.com/catalogue/the-boys-...,Five,The Boys in the Boat: Nine Americans and Their...,For readers of Laura Hillenbrand's Seabiscuit ...,e10e1e165dc8be4a,Books,Â£22.60,Â£22.60,Â£0.00,In stock (19 available),0
3,Â£17.46,In stock,media/cache/5b/88/5b88c52633f53cacf162c15f4f82...,https://books.toscrape.com/catalogue/set-me-fr...,Four,Set Me Free,Aaron Ledbetterâs future had been planned ou...,ce6396b0f23f6ecc,Books,Â£17.46,Â£17.46,Â£0.00,In stock (19 available),0
4,Â£23.88,In stock,media/cache/55/33/553310a7162dfbc2c6d19a84da0d...,https://books.toscrape.com/catalogue/olio_984/...,Five,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### m8.3 Extract all product details from page & save into csv file.

In [23]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

main_url = "https://books.toscrape.com/"

r = requests.get(main_url)
r.status_code

200

In [24]:
soup = BeautifulSoup(r.text, "html.parser")
products = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")

In [26]:
all_products = []

for item in products:

    # step 1: basic data
    base = {
       
        "product_price": item.find("p", class_="price_color").text,
        "product_availability": item.find("p", class_="instock availability").text.strip(),
        "product_img": item.find("img")["src"],
        "product_url": main_url + item.find("a")["href"]
    }

    # step 2: detailed page crawl
    req = requests.get(base["product_url"])
    soup2 = BeautifulSoup(req.text, "html.parser")

    base["Product Name"] = soup2.find("h1").text
    base["Product_Description"] = soup2.find("div", id="product_description").find_next_sibling().text.strip()

    for tr in soup2.find_all("tr"):
        base[tr.find("th").text] = tr.find("td").text

    base["product_reviews_star_no"] = soup2.find("p", class_="star-rating")["class"][1]

    all_products.append(base)

df = pd.DataFrame(all_products)
df.to_csv("book_toscrape_qm8.3.csv", index=False)

df

,product_price,product_availability,product_img,product_url,Product Name,Product_Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,product_reviews_star_no
0,Â£51.77,In stock,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,https://books.toscrape.com/catalogue/a-light-i...,A Light in the Attic,It's hard to imagine a world without A Light i...,a897fe39b1053632,Books,Â£51.77,Â£51.77,Â£0.00,In stock (22 available),0,Three
1,Â£53.74,In stock,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...,https://books.toscrape.com/catalogue/tipping-t...,Tipping the Velvet,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,Books,Â£53.74,Â£53.74,Â£0.00,In stock (20 available),0,One
2,Â£50.10,In stock,media/cache/3e/ef/3eef99c9d9adef34639f51066202...,https://books.toscrape.com/catalogue/soumissio...,Soumission,"Dans une France assez proche de la nÃ´tre, un ...",6957f44c3847a760,Books,Â£50.10,Â£50.10,Â£0.00,In stock (20 available),0,One
3,Â£47.82,In stock,media/cache/32/51/3251cf3a3412f53f339e42cac213...,https://books.toscrape.com/catalogue/sharp-obj...,Sharp Objects,"WICKED above her hipbone, GIRL across her hear...",e00eb4fd7b871a48,Books,Â£47.82,Â£47.82,Â£0.00,In stock (20 available),0,Four
4,Â£54.23,In stock,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...,https://books.toscrape.com/catalogue/sapiens-a...,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,4165285e1663650f,Books,Â£54.23,Â£54.23,Â£0.00,In stock (20 available),0,Five
5,Â£22.65,In stock,media/cache/68/33/68339b4c9bc034267e1da611ab3b...,https://books.toscrape.com/catalogue/the-requi...,The Requiem Red,Patient Twenty-nine.A monster roams the halls ...,f77dbf2323deb740,Books,Â£22.65,Â£22.65,Â£0.00,In stock (19 available),0,One
6,Â£33.34,In stock,media/cache/92/27/92274a95b7c251fea59a2b8a7827...,https://books.toscrape.com/catalogue/the-dirty...,The Dirty Little Secrets of Getting Your Dream...,Drawing on his extensive experience evaluating...,2597b5a345f45e1b,Books,Â£33.34,Â£33.34,Â£0.00,In stock (19 available),0,Four
7,Â£17.93,In stock,media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78...,https://books.toscrape.com/catalogue/the-comin...,The Coming Woman: A Novel Based on the Life of...,"""If you have a heart, if you have a soul, Kare...",e72a5dfc7e9267b2,Books,Â£17.93,Â£17.93,Â£0.00,In stock (19 available),0,Three
8,Â£22.60,In stock,media/cache/66/88/66883b91f6804b2323c8369331cb...,https://books.toscrape.com/catalogue/the-boys-...,The Boys in the Boat: Nine Americans and Their...,For readers of Laura Hillenbrand's Seabiscuit ...,e10e1e165dc8be4a,Books,Â£22.60,Â£22.60,Â£0.00,In stock (19 available),0,Four
9,Â£52.15,In stock,media/cache/58/46/5846057e28022268153beff6d352...,https://books.toscrape.com/catalogue/the-black...,The Black Maria,"Praise for Aracelis Girmay:""[Girmay's] every l...",1dfe412b8ac00530,Books,Â£52.15,Â£52.15,Â£0.00,In stock (19 available),0,One
10,Â£13.99,In stock,media/cache/be/f4/bef44da28c98f905a3ebec0b87be...,https://books.toscrape.com/catalogue/starving-...,"Starving Hearts (Triangular Trade Trilogy, #1)","Since her assault, Miss Annette Chetwynd has b...",0312262ecafa5a40,Books,Â£13.99,Â£13.99,Â£0.00,In stock (19 available),0,Two
11,Â£20.66,In stock,media/cache/10/48/1048f63d3b5061cd2f424d20b3f9...,https://books.toscrape.com/catalogue/shakespea...,Shakespeare's Sonnets,This book is an important and complete collect...,30a7f60cd76ca58c,Books,Â£20.66,Â£20.66,Â£0.00,In stock (19 available),0,Four
12,Â£17.46,In stock,media/cache/5b/88/5b88c52633f53cacf162c15f4f82...,https://books.toscrape.com/catalogue/set-me-fr...,Set Me Free,Aaron Ledbetterâs future had been planned ou...,ce6396b0f23f6ecc,Books,Â£17.46,Â£17.46,Â£0.00,In stock (19 available),0,Five
13,Â£52.29,In stock,media/cache/94/b1/94b1b8b244bce9677c2f29ccc890...,https://books.toscrape.com/catalogue/scott-pil...,Scott Pilgrim's Precious Little Life (Scott Pi...,Scott Pilgrim's life is totally sweet. He's 23...,3b1c02bac2a429e6,Books,Â£52.29,Â£52.29,Â£0.00,In stock (19 available),0,Five
14,Â£35.02,In stock,media/cache/81/c4/81c4a973364e17d01f217e118825...,https://books.toscrape.com/catalogue/rip-it-up...,Rip it Up and Start Again,"Punk's raw power rejuvenated rock, but by the ...",a34ba96d4081e6a4,Books,Â£35.02,Â£35.02,Â£0.00,In stock (19 available),0,Five
15,Â£57.25,In stock,media/cache/54/60/54607fe8945897cdcced0044103b...,https://books.toscrape.com/catalogue/our-band-...,Our Band Could Be Your Life: Scenes from the A...,This is the never-before-told story of the mus...,deda3e61b9514b83,Books,Â£57.25,Â£57.25,Â£0.00,In stock (19 available),0,Three
16,Â£23.88,In stock,media/cache/55/33/553310a7162dfbc2c6d19a84da0d...,https://books.toscrape.com/catalogue/olio_984/...,Olio,"Part fact, part fiction, Tyehimba Jess's much ...",feb7cc7701ecf901,Books,Â£23.88,Â£23.88,Â£0.00,In stock (19 available),0,One
17,Â£37.59,In stock,media/cache/09/a3/09a3aef48557576e1a85ba7efea8...,https://books.toscrape.com/catalogue/mesaerion...,Mesaerion: The Best Science Fiction Stories 18...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,Books,Â£37.59,Â£37.59,Â£0.00,In stock (19 available),0,One
18,Â£51.33,In stock,media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736...,https://books.toscrape.com/catalogue/libertari...,Libertarianism for Beginners,Libertarianism isn't about winning elections; ...,a18a4f574854aced,Books,Â£51.33,Â£51.33,Â£0.00,In stock (19 available),0,Two
19,Â£45.17,In stock,media/cache/27/a5/27a53d0bb95bdd88288eaf66c923...,https://books.toscrape.com/catalogue/its-only-...,It's Only the Himalayas,"âWherever you go, whatever you do, just . . ...",a22124811bfa8350,Books,Â£45.17,Â£45.17,Â£0.00,In stock (19 available),0,Two

### m8.4 Extract all product details of first column save into csv file.

In [27]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

main_url = "https://books.toscrape.com/"

r = requests.get(main_url)
r.status_code

200

In [28]:
soup = BeautifulSoup(r.text, "html.parser")
products = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")[0::4]

In [29]:
all_products = []

for item in products:

    # step 1: basic data
    base = {
        
        "product_price": item.find("p", class_="price_color").text,
        "product_availability": item.find("p", class_="instock availability").text.strip(),
        "product_img": item.find("img")["src"],
        "product_url": main_url + item.find("a")["href"]
    }

    # step 2: detailed page crawl
    req = requests.get(base["product_url"])
    soup2 = BeautifulSoup(req.text, "html.parser")

    base["Product Name"] = soup2.find("h1").text
    base["Product_Description"] = soup2.find("div", id="product_description").find_next_sibling().text.strip()

    for tr in soup2.find_all("tr"):
        base[tr.find("th").text] = tr.find("td").text

    base["product_reviews_star_no"] = soup2.find("p", class_="star-rating")["class"][1]

    all_products.append(base)

df = pd.DataFrame(all_products)
df.to_csv("book_toscrape_qm8.4.csv", index=False)

df

,product_price,product_availability,product_img,product_url,Product Name,Product_Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,product_reviews_star_no
0,Â£51.77,In stock,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,https://books.toscrape.com/catalogue/a-light-i...,A Light in the Attic,It's hard to imagine a world without A Light i...,a897fe39b1053632,Books,Â£51.77,Â£51.77,Â£0.00,In stock (22 available),0,Three
1,Â£54.23,In stock,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...,https://books.toscrape.com/catalogue/sapiens-a...,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,4165285e1663650f,Books,Â£54.23,Â£54.23,Â£0.00,In stock (20 available),0,Five
2,Â£22.60,In stock,media/cache/66/88/66883b91f6804b2323c8369331cb...,https://books.toscrape.com/catalogue/the-boys-...,The Boys in the Boat: Nine Americans and Their...,For readers of Laura Hillenbrand's Seabiscuit ...,e10e1e165dc8be4a,Books,Â£22.60,Â£22.60,Â£0.00,In stock (19 available),0,Four
3,Â£17.46,In stock,media/cache/5b/88/5b88c52633f53cacf162c15f4f82...,https://books.toscrape.com/catalogue/set-me-fr...,Set Me Free,Aaron Ledbetterâs future had been planned ou...,ce6396b0f23f6ecc,Books,Â£17.46,Â£17.46,Â£0.00,In stock (19 available),0,Five
4,Â£23.88,In stock,media/cache/55/33/553310a7162dfbc2c6d19a84da0d...,https://books.toscrape.com/catalogue/olio_984/...,Olio,"Part fact, part fiction, Tyehimba Jess's much ...",feb7cc7701ecf901,Books,Â£23.88,Â£23.88,Â£0.00,In stock (19 available),0,One

### m8.5 Extract all product details of Second column save into csv file.

In [30]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

main_url = "https://books.toscrape.com/"

r = requests.get(main_url)
r.status_code

200

In [31]:
soup = BeautifulSoup(r.text, "html.parser")
products = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")[1::4]

In [32]:
all_products = []

for item in products:

    # step 1: basic data
    base = {
        
        "product_price": item.find("p", class_="price_color").text,
        "product_availability": item.find("p", class_="instock availability").text.strip(),
        "product_img": item.find("img")["src"],
        "product_url": main_url + item.find("a")["href"]
    }

    # step 2: detailed page crawl
    req = requests.get(base["product_url"])
    soup2 = BeautifulSoup(req.text, "html.parser")

    base["Product Name"] = soup2.find("h1").text
    base["Product_Description"] = soup2.find("div", id="product_description").find_next_sibling().text.strip()

    for tr in soup2.find_all("tr"):
        base[tr.find("th").text] = tr.find("td").text

    base["product_reviews_star_no"] = soup2.find("p", class_="star-rating")["class"][1]

    all_products.append(base)

df = pd.DataFrame(all_products)
df.to_csv("book_toscrape_qm8.5.csv", index=False)

df

,product_price,product_availability,product_img,product_url,Product Name,Product_Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,product_reviews_star_no
0,Â£53.74,In stock,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...,https://books.toscrape.com/catalogue/tipping-t...,Tipping the Velvet,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,Books,Â£53.74,Â£53.74,Â£0.00,In stock (20 available),0,One
1,Â£22.65,In stock,media/cache/68/33/68339b4c9bc034267e1da611ab3b...,https://books.toscrape.com/catalogue/the-requi...,The Requiem Red,Patient Twenty-nine.A monster roams the halls ...,f77dbf2323deb740,Books,Â£22.65,Â£22.65,Â£0.00,In stock (19 available),0,One
2,Â£52.15,In stock,media/cache/58/46/5846057e28022268153beff6d352...,https://books.toscrape.com/catalogue/the-black...,The Black Maria,"Praise for Aracelis Girmay:""[Girmay's] every l...",1dfe412b8ac00530,Books,Â£52.15,Â£52.15,Â£0.00,In stock (19 available),0,One
3,Â£52.29,In stock,media/cache/94/b1/94b1b8b244bce9677c2f29ccc890...,https://books.toscrape.com/catalogue/scott-pil...,Scott Pilgrim's Precious Little Life (Scott Pi...,Scott Pilgrim's life is totally sweet. He's 23...,3b1c02bac2a429e6,Books,Â£52.29,Â£52.29,Â£0.00,In stock (19 available),0,Five
4,Â£37.59,In stock,media/cache/09/a3/09a3aef48557576e1a85ba7efea8...,https://books.toscrape.com/catalogue/mesaerion...,Mesaerion: The Best Science Fiction Stories 18...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,Books,Â£37.59,Â£37.59,Â£0.00,In stock (19 available),0,One

### m8.6 Extract all product details of thirst column save into csv file.

In [33]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

main_url = "https://books.toscrape.com/"

r = requests.get(main_url)
r.status_code

200

In [34]:
soup = BeautifulSoup(r.text, "html.parser")
products = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")[2::4]

In [35]:
all_products = []

for item in products:

    # step 1: basic data
    base = {
        
        "product_price": item.find("p", class_="price_color").text,
        "product_availability": item.find("p", class_="instock availability").text.strip(),
        "product_img": item.find("img")["src"],
        "product_url": main_url + item.find("a")["href"]
    }

    # step 2: detailed page crawl
    req = requests.get(base["product_url"])
    soup2 = BeautifulSoup(req.text, "html.parser")

    base["Product Name"] = soup2.find("h1").text
    base["Product_Description"] = soup2.find("div", id="product_description").find_next_sibling().text.strip()

    for tr in soup2.find_all("tr"):
        base[tr.find("th").text] = tr.find("td").text

    base["product_reviews_star_no"] = soup2.find("p", class_="star-rating")["class"][1]

    all_products.append(base)

df = pd.DataFrame(all_products)
df.to_csv("book_toscrape_qm8.6.csv", index=False)

df

,product_price,product_availability,product_img,product_url,Product Name,Product_Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,product_reviews_star_no
0,Â£50.10,In stock,media/cache/3e/ef/3eef99c9d9adef34639f51066202...,https://books.toscrape.com/catalogue/soumissio...,Soumission,"Dans une France assez proche de la nÃ´tre, un ...",6957f44c3847a760,Books,Â£50.10,Â£50.10,Â£0.00,In stock (20 available),0,One
1,Â£33.34,In stock,media/cache/92/27/92274a95b7c251fea59a2b8a7827...,https://books.toscrape.com/catalogue/the-dirty...,The Dirty Little Secrets of Getting Your Dream...,Drawing on his extensive experience evaluating...,2597b5a345f45e1b,Books,Â£33.34,Â£33.34,Â£0.00,In stock (19 available),0,Four
2,Â£13.99,In stock,media/cache/be/f4/bef44da28c98f905a3ebec0b87be...,https://books.toscrape.com/catalogue/starving-...,"Starving Hearts (Triangular Trade Trilogy, #1)","Since her assault, Miss Annette Chetwynd has b...",0312262ecafa5a40,Books,Â£13.99,Â£13.99,Â£0.00,In stock (19 available),0,Two
3,Â£35.02,In stock,media/cache/81/c4/81c4a973364e17d01f217e118825...,https://books.toscrape.com/catalogue/rip-it-up...,Rip it Up and Start Again,"Punk's raw power rejuvenated rock, but by the ...",a34ba96d4081e6a4,Books,Â£35.02,Â£35.02,Â£0.00,In stock (19 available),0,Five
4,Â£51.33,In stock,media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736...,https://books.toscrape.com/catalogue/libertari...,Libertarianism for Beginners,Libertarianism isn't about winning elections; ...,a18a4f574854aced,Books,Â£51.33,Â£51.33,Â£0.00,In stock (19 available),0,Two

### m8.7 Extract all product details from first page & save into csv file.

In [36]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

main_url = "https://books.toscrape.com/"

r = requests.get(main_url)
r.status_code

200

In [38]:
soup = BeautifulSoup(r.text, "html.parser")
products = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")

In [39]:
all_products = []

for item in products:

    # step 1: basic data
    base = {
        
        "product_price": item.find("p", class_="price_color").text,
        "product_availability": item.find("p", class_="instock availability").text.strip(),
        "product_img": item.find("img")["src"],
        "product_url": main_url + item.find("a")["href"]
    }

    # step 2: detailed page crawl
    req = requests.get(base["product_url"])
    soup2 = BeautifulSoup(req.text, "html.parser")

    base["Product Name"] = soup2.find("h1").text
    base["Product_Description"] = soup2.find("div", id="product_description").find_next_sibling().text.strip()

    for tr in soup2.find_all("tr"):
        base[tr.find("th").text] = tr.find("td").text

    base["product_reviews_star_no"] = soup2.find("p", class_="star-rating")["class"][1]

    all_products.append(base)

df = pd.DataFrame(all_products)
df.to_csv("book_toscrape_qm8.7.csv", index=False)

df

,product_price,product_availability,product_img,product_url,Product Name,Product_Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,product_reviews_star_no
0,Â£51.77,In stock,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...,https://books.toscrape.com/catalogue/a-light-i...,A Light in the Attic,It's hard to imagine a world without A Light i...,a897fe39b1053632,Books,Â£51.77,Â£51.77,Â£0.00,In stock (22 available),0,Three
1,Â£53.74,In stock,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...,https://books.toscrape.com/catalogue/tipping-t...,Tipping the Velvet,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,Books,Â£53.74,Â£53.74,Â£0.00,In stock (20 available),0,One
2,Â£50.10,In stock,media/cache/3e/ef/3eef99c9d9adef34639f51066202...,https://books.toscrape.com/catalogue/soumissio...,Soumission,"Dans une France assez proche de la nÃ´tre, un ...",6957f44c3847a760,Books,Â£50.10,Â£50.10,Â£0.00,In stock (20 available),0,One
3,Â£47.82,In stock,media/cache/32/51/3251cf3a3412f53f339e42cac213...,https://books.toscrape.com/catalogue/sharp-obj...,Sharp Objects,"WICKED above her hipbone, GIRL across her hear...",e00eb4fd7b871a48,Books,Â£47.82,Â£47.82,Â£0.00,In stock (20 available),0,Four
4,Â£54.23,In stock,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...,https://books.toscrape.com/catalogue/sapiens-a...,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,4165285e1663650f,Books,Â£54.23,Â£54.23,Â£0.00,In stock (20 available),0,Five
5,Â£22.65,In stock,media/cache/68/33/68339b4c9bc034267e1da611ab3b...,https://books.toscrape.com/catalogue/the-requi...,The Requiem Red,Patient Twenty-nine.A monster roams the halls ...,f77dbf2323deb740,Books,Â£22.65,Â£22.65,Â£0.00,In stock (19 available),0,One
6,Â£33.34,In stock,media/cache/92/27/92274a95b7c251fea59a2b8a7827...,https://books.toscrape.com/catalogue/the-dirty...,The Dirty Little Secrets of Getting Your Dream...,Drawing on his extensive experience evaluating...,2597b5a345f45e1b,Books,Â£33.34,Â£33.34,Â£0.00,In stock (19 available),0,Four
7,Â£17.93,In stock,media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78...,https://books.toscrape.com/catalogue/the-comin...,The Coming Woman: A Novel Based on the Life of...,"""If you have a heart, if you have a soul, Kare...",e72a5dfc7e9267b2,Books,Â£17.93,Â£17.93,Â£0.00,In stock (19 available),0,Three
8,Â£22.60,In stock,media/cache/66/88/66883b91f6804b2323c8369331cb...,https://books.toscrape.com/catalogue/the-boys-...,The Boys in the Boat: Nine Americans and Their...,For readers of Laura Hillenbrand's Seabiscuit ...,e10e1e165dc8be4a,Books,Â£22.60,Â£22.60,Â£0.00,In stock (19 available),0,Four
9,Â£52.15,In stock,media/cache/58/46/5846057e28022268153beff6d352...,https://books.toscrape.com/catalogue/the-black...,The Black Maria,"Praise for Aracelis Girmay:""[Girmay's] every l...",1dfe412b8ac00530,Books,Â£52.15,Â£52.15,Â£0.00,In stock (19 available),0,One
10,Â£13.99,In stock,media/cache/be/f4/bef44da28c98f905a3ebec0b87be...,https://books.toscrape.com/catalogue/starving-...,"Starving Hearts (Triangular Trade Trilogy, #1)","Since her assault, Miss Annette Chetwynd has b...",0312262ecafa5a40,Books,Â£13.99,Â£13.99,Â£0.00,In stock (19 available),0,Two
11,Â£20.66,In stock,media/cache/10/48/1048f63d3b5061cd2f424d20b3f9...,https://books.toscrape.com/catalogue/shakespea...,Shakespeare's Sonnets,This book is an important and complete collect...,30a7f60cd76ca58c,Books,Â£20.66,Â£20.66,Â£0.00,In stock (19 available),0,Four
12,Â£17.46,In stock,media/cache/5b/88/5b88c52633f53cacf162c15f4f82...,https://books.toscrape.com/catalogue/set-me-fr...,Set Me Free,Aaron Ledbetterâs future had been planned ou...,ce6396b0f23f6ecc,Books,Â£17.46,Â£17.46,Â£0.00,In stock (19 available),0,Five
13,Â£52.29,In stock,media/cache/94/b1/94b1b8b244bce9677c2f29ccc890...,https://books.toscrape.com/catalogue/scott-pil...,Scott Pilgrim's Precious Little Life (Scott Pi...,Scott Pilgrim's life is totally sweet. He's 23...,3b1c02bac2a429e6,Books,Â£52.29,Â£52.29,Â£0.00,In stock (19 available),0,Five
14,Â£35.02,In stock,media/cache/81/c4/81c4a973364e17d01f217e118825...,https://books.toscrape.com/catalogue/rip-it-up...,Rip it Up and Start Again,"Punk's raw power rejuvenated rock, but by the ...",a34ba96d4081e6a4,Books,Â£35.02,Â£35.02,Â£0.00,In stock (19 available),0,Five
15,Â£57.25,In stock,media/cache/54/60/54607fe8945897cdcced0044103b...,https://books.toscrape.com/catalogue/our-band-...,Our Band Could Be Your Life: Scenes from the A...,This is the never-before-told story of the mus...,deda3e61b9514b83,Books,Â£57.25,Â£57.25,Â£0.00,In stock (19 available),0,Three
16,Â£23.88,In stock,media/cache/55/33/553310a7162dfbc2c6d19a84da0d...,https://books.toscrape.com/catalogue/olio_984/...,Olio,"Part fact, part fiction, Tyehimba Jess's much ...",feb7cc7701ecf901,Books,Â£23.88,Â£23.88,Â£0.00,In stock (19 available),0,One
17,Â£37.59,In stock,media/cache/09/a3/09a3aef48557576e1a85ba7efea8...,https://books.toscrape.com/catalogue/mesaerion...,Mesaerion: The Best Science Fiction Stories 18...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,Books,Â£37.59,Â£37.59,Â£0.00,In stock (19 available),0,One
18,Â£51.33,In stock,media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736...,https://books.toscrape.com/catalogue/libertari...,Libertarianism for Beginners,Libertarianism isn't about winning elections; ...,a18a4f574854aced,Books,Â£51.33,Â£51.33,Â£0.00,In stock (19 available),0,Two
19,Â£45.17,In stock,media/cache/27/a5/27a53d0bb95bdd88288eaf66c923...,https://books.toscrape.com/catalogue/its-only-...,It's Only the Himalayas,"âWherever you go, whatever you do, just . . ...",a22124811bfa8350,Books,Â£45.17,Â£45.17,Â£0.00,In stock (19 available),0,Two

### m8.8 Extract all product details from second page & save into another csv file.

In [52]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

main_url = "https://books.toscrape.com/catalogue/page-2.html"
base_url = "https://books.toscrape.com/catalogue/"

r = requests.get(main_url)

In [53]:
soup = BeautifulSoup(r.text, "html.parser")

products = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")

In [54]:
all_products = []

for item in products:

    base = {
        "product_price": item.find("p", class_="price_color").text,
        "product_availability": item.find("p", class_="instock availability").text.strip(),
        "product_img": item.find("img")["src"],
        "product_url": base_url + item.find("a")["href"]
    }

    req = requests.get(base["product_url"])
    soup2 = BeautifulSoup(req.text, "html.parser")

    base["Product Name"] = soup2.find("h1").text

    base["Product_Description"] = soup2.find("div", id="product_description").find_next_sibling().text.strip()

    for tr in soup2.find_all("tr"):
        base[tr.find("th").text] = tr.find("td").text

    base["product_reviews_star_no"] = soup2.find("p", class_="star-rating")["class"][1]

    all_products.append(base)

df = pd.DataFrame(all_products)
df.to_csv("book_toscrape_qm8.8.csv", index=False)

df

,product_price,product_availability,product_img,product_url,Product Name,Product_Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,product_reviews_star_no
0,Â£12.84,In stock,../media/cache/5d/72/5d72709c6a7a9584a4d1cf076...,https://books.toscrape.com/catalogue/in-her-wa...,In Her Wake,A perfect life â¦ until she discovered it was...,23356462d1320d61,Books,Â£12.84,Â£12.84,Â£0.00,In stock (19 available),0,One
1,Â£37.32,In stock,../media/cache/5c/c8/5cc8e107246cb478960d4f0ab...,https://books.toscrape.com/catalogue/how-music...,How Music Works,How Music Works is David Byrneâs remarkable ...,327f68a59745c102,Books,Â£37.32,Â£37.32,Â£0.00,In stock (19 available),0,Two
2,Â£30.52,In stock,../media/cache/9f/59/9f59f01fa916a7bb8f0b28a40...,https://books.toscrape.com/catalogue/foolproof...,Foolproof Preserving: A Guide to Small Batch J...,Canning perfected the Americaâs Test Kitchen...,5674a18a29a43ced,Books,Â£30.52,Â£30.52,Â£0.00,In stock (19 available),0,Three
3,Â£25.27,In stock,../media/cache/9c/2e/9c2e0eb8866b8e3f3b768994f...,https://books.toscrape.com/catalogue/chase-me-...,Chase Me (Paris Nights #2),"A Michelin two-star chef at twenty-eight, Viol...",c2e46a2ee3b4a322,Books,Â£25.27,Â£25.27,Â£0.00,In stock (19 available),0,Five
4,Â£34.53,In stock,../media/cache/44/cc/44ccc99c8f82c33d4f9d2afa4...,https://books.toscrape.com/catalogue/black-dus...,Black Dust,"No matter how busy he keeps himself, successfu...",00bfed9e18bb36f3,Books,Â£34.53,Â£34.53,Â£0.00,In stock (19 available),0,Five
5,Â£54.64,In stock,../media/cache/af/6e/af6e796160fe63e0cf19d4439...,https://books.toscrape.com/catalogue/birdsong-...,Birdsong: A Story in Pictures,Bring the thrilling story of one red bird to l...,9528d0948525bf5f,Books,Â£54.64,Â£54.64,Â£0.00,In stock (19 available),0,Three
6,Â£22.50,In stock,../media/cache/ef/0b/ef0bed08de4e083dba5e20fdb...,https://books.toscrape.com/catalogue/americas-...,America's Cradle of Quarterbacks: Western Penn...,"Any fan of the Baltimore Colts of my era, any ...",c7d160c2c0de586f,Books,Â£22.50,Â£22.50,Â£0.00,In stock (19 available),0,Three
7,Â£53.13,In stock,../media/cache/d6/da/d6da0371958068bbaf39ea9c1...,https://books.toscrape.com/catalogue/aladdin-a...,Aladdin and His Wonderful Lamp,Planning on seeing Aladdin the Disney musical?...,904208d6aa64b655,Books,Â£53.13,Â£53.13,Â£0.00,In stock (19 available),0,Three
8,Â£40.30,In stock,../media/cache/2e/98/2e98c332bf8563b5847849715...,https://books.toscrape.com/catalogue/worlds-el...,Worlds Elsewhere: Journeys Around Shakespeareâ...,"Anti-apartheid activist, Bollywood screenwrite...",4c28def39d850cdf,Books,Â£40.30,Â£40.30,Â£0.00,In stock (18 available),0,Five
9,Â£44.18,In stock,../media/cache/a5/41/a5416b9646aaa7287baa287ec...,https://books.toscrape.com/catalogue/wall-and-...,Wall and Piece,"Banksy, Britain's now-legendary ""guerilla"" str...",ccd9ffa25efabdea,Books,Â£44.18,Â£44.18,Â£0.00,In stock (18 available),0,Four
10,Â£17.66,In stock,../media/cache/0f/7e/0f7ee69495c0df1d35723f012...,https://books.toscrape.com/catalogue/the-four-...,The Four Agreements: A Practical Guide to Pers...,"In The Four Agreements, don Miguel Ruiz reveal...",6258a1f6a6dcfe50,Books,Â£17.66,Â£17.66,Â£0.00,In stock (18 available),0,Five
11,Â£31.05,In stock,../media/cache/38/c5/38c56fba316c07305643a8065...,https://books.toscrape.com/catalogue/the-five-...,The Five Love Languages: How to Express Heartf...,Are you and your spouse speaking the same lang...,3c039985229453bf,Books,Â£31.05,Â£31.05,Â£0.00,In stock (18 available),0,Three
12,Â£23.82,In stock,../media/cache/5d/7e/5d7ecde8e81513eba8a64c9fe...,https://books.toscrape.com/catalogue/the-eleph...,The Elephant Tree,Mark Fallon is an overworked detective investi...,5dada2b7be26bd03,Books,Â£23.82,Â£23.82,Â£0.00,In stock (18 available),0,Five
13,Â£36.89,In stock,../media/cache/cf/bb/cfbb5e62715c6d888fd07794c...,https://books.toscrape.com/catalogue/the-bear-...,The Bear and the Piano,"One day, a young bear stumbles upon something ...",9f6568e9c95f60b0,Books,Â£36.89,Â£36.89,Â£0.00,In stock (18 available),0,One
14,Â£15.94,In stock,../media/cache/65/71/6571919836ec51ed54f0050c3...,https://books.toscrape.com/catalogue/sophies-w...,Sophie's World,A page-turning novel that is also an explorati...,6be3beb0793a53e7,Books,Â£15.94,Â£15.94,Â£0.00,In stock (18 available),0,Five
15,Â£33.29,In stock,../media/cache/12/53/1253c21c5ef3c6d075c5fa3f5...,https://books.toscrape.com/catalogue/penny-may...,Penny Maybe,"Sent to yet another foster family, Penny decid...",668fe56b17cfcd4f,Books,Â£33.29,Â£33.29,Â£0.00,In stock (18 available),0,Three
16,Â£18.02,In stock,../media/cache/f5/88/f5889d038f5d8e949b494d147...,https://books.toscrape.com/catalogue/maude-188...,Maude (1883-1993):She Grew Up with the country,This new edition of Maude (1883-1993) has been...,094b269567e1c300,Books,Â£18.02,Â£18.02,Â£0.00,In stock (18 available),0,Two
17,Â£19.63,In stock,../media/cache/23/85/238570a1c284e730dbc737a7e...,https://books.toscrape.com/catalogue/in-a-dark...,"In a Dark, Dark Wood","In a dark, dark wood Nora hasn't seen Clare fo...",19ed25f4641d5efd,Books,Â£19.63,Â£19.63,Â£0.00,In stock (18 available),0,One
18,Â£52.22,In stock,../media/cache/e1/5c/e15c289ba58cea38519e1281e...,https://books.toscrape.com/catalogue/behind-cl...,Behind Closed Doors,The 2016 debut bloggers can't stop raving abou...,be5cc846f45496fb,Books,Â£52.22,Â£52.22,Â£0.00,In stock (18 available),0,Four
19,Â£33.63,In stock,../media/cache/e9/20/e9203b733126c4a0832a1c788...,https://books.toscrape.com/catalogue/you-cant-...,You can't bury them all: Poems,"A poetry that is at once harrowing, angry, and...",55f9da0c5eea2e10,Books,Â£33.63,Â£33.63,Â£0.00,In stock (17 available),0,Two

### m8.9 Extract all product details from first page to fifth page & save into single csv file.

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

base_url = "https://books.toscrape.com/catalogue/"
all_products = []    # FIX: yeh loop ke bahar hona chahiye

In [2]:
for page in range(1, 6):

    m_url = f"https://books.toscrape.com/catalogue/page-{page}.html"
    r = requests.get(m_url)
    soup = BeautifulSoup(r.text, "html.parser")

    products = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")

    for item in products:

        base = {
            "product_price": item.find("p", class_="price_color").text,
            "product_availability": item.find("p", class_="instock availability").text.strip(),
            "product_img": item.find("img")["src"],
            "product_url": base_url + item.find("a")["href"]
        }

        req = requests.get(base["product_url"])
        soup2 = BeautifulSoup(req.text, "html.parser")

        base["Product Name"] = soup2.find("h1").text

        desc = soup2.find("div", id="product_description")
        if desc:
            base["Product_Description"] = desc.find_next_sibling().text.strip()
        else:
            base["Product_Description"] = ""

        for tr in soup2.find_all("tr"):
            base[tr.find("th").text] = tr.find("td").text

        base["product_reviews_star_no"] = soup2.find("p", class_="star-rating")["class"][1]

        all_products.append(base)

# Export
df = pd.DataFrame(all_products)
df.to_csv("book_toscrape_qm8.9.csv", index=False)

df

,product_price,product_availability,product_img,product_url,Product Name,Product_Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews,product_reviews_star_no
0,Â£51.77,In stock,../media/cache/2c/da/2cdad67c44b002e7ead0cc356...,https://books.toscrape.com/catalogue/a-light-i...,A Light in the Attic,It's hard to imagine a world without A Light i...,a897fe39b1053632,Books,Â£51.77,Â£51.77,Â£0.00,In stock (22 available),0,Three
1,Â£53.74,In stock,../media/cache/26/0c/260c6ae16bce31c8f8c95dadd...,https://books.toscrape.com/catalogue/tipping-t...,Tipping the Velvet,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,Books,Â£53.74,Â£53.74,Â£0.00,In stock (20 available),0,One
2,Â£50.10,In stock,../media/cache/3e/ef/3eef99c9d9adef34639f51066...,https://books.toscrape.com/catalogue/soumissio...,Soumission,"Dans une France assez proche de la nÃ´tre, un ...",6957f44c3847a760,Books,Â£50.10,Â£50.10,Â£0.00,In stock (20 available),0,One
3,Â£47.82,In stock,../media/cache/32/51/3251cf3a3412f53f339e42cac...,https://books.toscrape.com/catalogue/sharp-obj...,Sharp Objects,"WICKED above her hipbone, GIRL across her hear...",e00eb4fd7b871a48,Books,Â£47.82,Â£47.82,Â£0.00,In stock (20 available),0,Four
4,Â£54.23,In stock,../media/cache/be/a5/bea5697f2534a2f86a3ef27b5...,https://books.toscrape.com/catalogue/sapiens-a...,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,4165285e1663650f,Books,Â£54.23,Â£54.23,Â£0.00,In stock (20 available),0,Five
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Â£19.92,In stock,../media/cache/5f/b1/5fb1bf88dcfda795606745ce3...,https://books.toscrape.com/catalogue/lumberjan...,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,This New York Times Bestselling series continu...,57e5a4d515c8ce44,Books,Â£19.92,Â£19.92,Â£0.00,In stock (16 available),0,Two
96,Â£40.11,In stock,../media/cache/98/d1/98d1c979c4bac9e147a671894...,https://books.toscrape.com/catalogue/layered-b...,"Layered: Baking, Building, and Styling Spectac...",Itâs time to venture beyond vanilla and choc...,7b75cc7f223791f4,Books,Â£40.11,Â£40.11,Â£0.00,In stock (16 available),0,One
97,Â£53.90,In stock,../media/cache/5f/52/5f52b1bc6d45daab2e330c744...,https://books.toscrape.com/catalogue/judo-seve...,Judo: Seven Steps to Black Belt (an Introducto...,"Displaying the most impressive throws, compell...",228f74b74f3a08ae,Books,Â£53.90,Â£53.90,Â£0.00,In stock (16 available),0,Two
98,Â£35.67,In stock,../media/cache/93/63/9363f0065fbad5689f44fcf6e...,https://books.toscrape.com/catalogue/join_902/...,Join,What if you could live multiple lives simultan...,18ad3ed896c7ce05,Books,Â£35.67,Â£35.67,Â£0.00,In stock (16 available),0,Five
99,Â£22.00,In stock,../media/cache/fe/ea/feeafd2ad7b3077f8e74cbb1d...,https://books.toscrape.com/catalogue/in-the-co...,In the Country We Love: My Family Divided,The star of Orange is the New Black and Jane t...,b136b1b180ca753a,Books,Â£22.00,Â£22.00,Â£0.00,In stock (16 available),0,Four