In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url ="https://www.scrapethissite.com/pages/"

r = requests.get(url)

print(r.status_code)

soup = BeautifulSoup(r.text,"html")
# print(soup)

# divs = soup.find("div",class_="page") #it will give the first one
divs = soup.find_all("div",class_="page") #it will give all divs in list

dist = {
    "header":"",
    "para":"",
    "link":"",

}
list=[]

for div in divs:

    # print("(***********)")

    # print("h3 value: ",div.find("h3").text.strip())
    # print("p value: ",div.find("p").text.strip())
    # print("link value: ",div.find("a")["href"])
    
    dist["header"] = div.find("h3").text.strip()
    dist["para"] = div.find("p").text.strip()
    dist["link"] = div.find("a")["href"]

    list.append(dist.copy())

list

200
(***********)
(***********)
(***********)
(***********)
(***********)

[{'header': 'Countries of the World: A Simple Example',
  'para': 'A single page that lists information about all the countries in the world. Good for those just get started with web scraping.',
  'link': '/pages/simple/'},
 {'header': 'Hockey Teams: Forms, Searching and Pagination',
  'para': 'Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.',
  'link': '/pages/forms/'},
 {'header': 'Oscar Winning Films: AJAX and Javascript',
  'para': 'Click through a bunch of great films. Learn how content is added to the page asynchronously with Javascript and how you can scrape it.',
  'link': '/pages/ajax-javascript/'},
 {'header': 'Turtles All the Way Down: Frames & iFrames',
  'para': 'Some older sites might still use frames to break up thier pages. Modern ones might be using iFrames to expose data. Learn about turtles as you scrape content inside frames.',
  'link': '/pages/frames/'},
 {'header': "Advanced Topics: Real World Challenges You'll Encounter",
  'para': "Scraping real websites, you're likely run into a number of common gotchas. Get practice with spoofing headers, handling logins & session cookies, finding CSRF tokens, and other common network errors.",
  'link': '/pages/advanced/'}]

In [6]:
df = pd.DataFrame(list)
df

,header,para,link
0,Countries of the World: A Simple Example,A single page that lists information about all...,/pages/simple/
1,"Hockey Teams: Forms, Searching and Pagination",Browse through a database of NHL team stats si...,/pages/forms/
2,Oscar Winning Films: AJAX and Javascript,Click through a bunch of great films. Learn ho...,/pages/ajax-javascript/
3,Turtles All the Way Down: Frames & iFrames,Some older sites might still use frames to bre...,/pages/frames/
4,Advanced Topics: Real World Challenges You'll ...,"Scraping real websites, you're likely run into...",/pages/advanced/

In [8]:
df.to_csv("data of scrapethissite.csv",index=False)

# 3. https://www.scrapethissite.com/pages/forms/ (Team Name, Year, Wins, Losses, OT Losses, Win %, Goals For (GF), Goals Against (GA), + / -)

##	3.1 Extract Table of first page & save into csv file.

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url ="https://www.scrapethissite.com/pages/forms/"

r = requests.get(url)

print(r.status_code)

soup = BeautifulSoup(r.text,"html")

200

In [ ]:
tbl = soup.find('table',class_ = "table")
tbl

<table class="table">
<tr>
<th>
                            Team Name
                        </th>
<th>
                            Year
                        </th>
<th>
                            Wins
                        </th>
<th>
                            Losses
                        </th>
<th>
                            OT Losses
                        </th>
<th>
                            Win %
                        </th>
<th>
                            Goals For (GF)
                        </th>
<th>
                            Goals Against (GA)
                        </th>
<th>
                            + / -
                        </th>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            44
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.55
                        </td>
<td class="gf">
                            299
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            35
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            292
                        </td>
<td class="ga">
                            278
                        </td>
<td class="diff text-success">
                            14
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            26
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            344
                        </td>
<td class="ga">
                            263
                        </td>
<td class="diff text-success">
                            81
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            49
                        </td>
<td class="losses">
                            23
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.613
                        </td>
<td class="gf">
                            284
                        </td>
<td class="ga">
                            211
                        </td>
<td class="diff text-success">
                            73
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Detroit Red Wings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            34
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.425
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            298
                        </td>
<td class="diff text-danger">
                            -25
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Edmonton Oilers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            272
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Hartford Whalers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            38
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            238
                        </td>
<td class="ga">
                            276
                        </td>
<td class="diff text-danger">
                            -38
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Los Angeles Kings
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            46
                        </td>
<td class="losses">
                            24
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.575
                        </td>
<td class="gf">
                            340
                        </td>
<td class="ga">
                            254
                        </td>
<td class="diff text-success">
                            86
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Minnesota North Stars
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            27
                        </td>
<td class="losses">
                            39
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.338
                        </td>
<td class="gf">
                            256
                        </td>
<td class="ga">
                            266
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Montreal Canadiens
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            39
                        </td>
<td class="losses">
                            30
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.487
                        </td>
<td class="gf">
                            273
                        </td>
<td class="ga">
                            249
                        </td>
<td class="diff text-success">
                            24
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New Jersey Devils
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            32
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.4
                        </td>
<td class="gf">
                            272
                        </td>
<td class="ga">
                            264
                        </td>
<td class="diff text-success">
                            8
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Islanders
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            25
                        </td>
<td class="losses">
                            45
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.312
                        </td>
<td class="gf">
                            223
                        </td>
<td class="ga">
                            290
                        </td>
<td class="diff text-danger">
                            -67
                        </td>
</tr>
<tr class="team">
<td class="name">
                            New York Rangers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            31
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            297
                        </td>
<td class="ga">
                            265
                        </td>
<td class="diff text-success">
                            32
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Philadelphia Flyers
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            33
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.412
                        </td>
<td class="gf">
                            252
                        </td>
<td class="ga">
                            267
                        </td>
<td class="diff text-danger">
                            -15
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Pittsburgh Penguins
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            41
                        </td>
<td class="losses">
                            33
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.512
                        </td>
<td class="gf">
                            342
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-success">
                            37
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Quebec Nordiques
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            16
                        </td>
<td class="losses">
                            50
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.2
                        </td>
<td class="gf">
                            236
                        </td>
<td class="ga">
                            354
                        </td>
<td class="diff text-danger">
                            -118
                        </td>
</tr>
<tr class="team">
<td class="name">
                            St. Louis Blues
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            47
                        </td>
<td class="losses">
                            22
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-success">
                            0.588
                        </td>
<td class="gf">
                            310
                        </td>
<td class="ga">
                            250
                        </td>
<td class="diff text-success">
                            60
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Toronto Maple Leafs
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            23
                        </td>
<td class="losses">
                            46
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.287
                        </td>
<td class="gf">
                            241
                        </td>
<td class="ga">
                            318
                        </td>
<td class="diff text-danger">
                            -77
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Vancouver Canucks
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            28
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.35
                        </td>
<td class="gf">
                            243
                        </td>
<td class="ga">
                            315
                        </td>
<td class="diff text-danger">
                            -72
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Washington Capitals
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            37
                        </td>
<td class="losses">
                            36
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.463
                        </td>
<td class="gf">
                            258
                        </td>
<td class="ga">
                            258
                        </td>
<td class="diff text-success">
                            0
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Winnipeg Jets
                        </td>
<td class="year">
                            1990
                        </td>
<td class="wins">
                            26
                        </td>
<td class="losses">
                            43
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.325
                        </td>
<td class="gf">
                            260
                        </td>
<td class="ga">
                            288
                        </td>
<td class="diff text-danger">
                            -28
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Boston Bruins
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            32
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            270
                        </td>
<td class="ga">
                            275
                        </td>
<td class="diff text-danger">
                            -5
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Buffalo Sabres
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            289
                        </td>
<td class="ga">
                            299
                        </td>
<td class="diff text-danger">
                            -10
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Calgary Flames
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            31
                        </td>
<td class="losses">
                            37
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.388
                        </td>
<td class="gf">
                            296
                        </td>
<td class="ga">
                            305
                        </td>
<td class="diff text-danger">
                            -9
                        </td>
</tr>
<tr class="team">
<td class="name">
                            Chicago Blackhawks
                        </td>
<td class="year">
                            1991
                        </td>
<td class="wins">
                            36
                        </td>
<td class="losses">
                            29
                        </td>
<td class="ot-losses">
</td>
<td class="pct text-danger">
                            0.45
                        </td>
<td class="gf">
                            257
                        </td>
<td class="ga">
                            236
                        </td>
<td class="diff text-success">
                            21
                        </td>
</tr>
</table>

In [11]:
trs = tbl.find_all("tr")
len(trs)

26

### Method 1

In [34]:
list_df = []
list_row  = []
for th in trs[0].find_all("th"):
    # print(th.text.strip())
    list_row.append(th.text.strip())
list_row
list_df.append(list_row)

In [32]:
trs[1].find_all('td')

[<td class="name">
                             Boston Bruins
                         </td>,
 <td class="year">
                             1990
                         </td>,
 <td class="wins">
                             44
                         </td>,
 <td class="losses">
                             24
                         </td>,
 <td class="ot-losses">
 </td>,
 <td class="pct text-success">
                             0.55
                         </td>,
 <td class="gf">
                             299
                         </td>,
 <td class="ga">
                             264
                         </td>,
 <td class="diff text-success">
                             35
                         </td>]

In [38]:
for tr in trs[1:]:
    list_row= []
    for col in tr.find_all("td"):
        # print(col.text.strip(),end=" ")
        list_row.append(col.text.strip())
    # print()
    list_df.append(list_row)
df = pd.DataFrame(list_df[1:], columns=list_df[0])
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
...,...,...,...,...,...,...,...,...,...
70,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
71,Boston Bruins,1991,36,32,,0.45,270,275,-5
72,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
73,Calgary Flames,1991,31,37,,0.388,296,305,-9
74,Chicago Blackhawks,1991,36,29,,0.45,257,236,21

### method 2

In [55]:
dict = {
'Team Name' : "",
'Year' : "",
'Wins' : "",
'Losses' : "",
'OT Losses' : "",
'Win %' : "",
'Goals For (GF)' : "",
'Goals Against (GA)' : "",
'+ / -' : ""
}

In [56]:
list_df = []
for tr in trs[1:]:
    cols = tr.find_all("td")
    dict["Team Name"] = cols[0].text.strip()
    dict["Year"] = cols[1].text.strip()
    dict["Wins"] = cols[2].text.strip()
    dict["Losses"] = cols[3].text.strip()
    dict["OT Losses"] = cols[4].text.strip()
    dict["Win %"] = cols[5].text.strip()
    dict["Goals For (GF)"] = cols[6].text.strip()
    dict["Goals Against (GA)"] = cols[7].text.strip()
    dict["+ / -"] = cols[8].text.strip()
    list_df.append(dict.copy())
    
list_df

[{'Team Name': 'Boston Bruins',
  'Year': '1990',
  'Wins': '44',
  'Losses': '24',
  'OT Losses': '',
  'Win %': '0.55',
  'Goals For (GF)': '299',
  'Goals Against (GA)': '264',
  '+ / -': '35'},
 {'Team Name': 'Buffalo Sabres',
  'Year': '1990',
  'Wins': '31',
  'Losses': '30',
  'OT Losses': '',
  'Win %': '0.388',
  'Goals For (GF)': '292',
  'Goals Against (GA)': '278',
  '+ / -': '14'},
 {'Team Name': 'Calgary Flames',
  'Year': '1990',
  'Wins': '46',
  'Losses': '26',
  'OT Losses': '',
  'Win %': '0.575',
  'Goals For (GF)': '344',
  'Goals Against (GA)': '263',
  '+ / -': '81'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1990',
  'Wins': '49',
  'Losses': '23',
  'OT Losses': '',
  'Win %': '0.613',
  'Goals For (GF)': '284',
  'Goals Against (GA)': '211',
  '+ / -': '73'},
 {'Team Name': 'Detroit Red Wings',
  'Year': '1990',
  'Wins': '34',
  'Losses': '38',
  'OT Losses': '',
  'Win %': '0.425',
  'Goals For (GF)': '273',
  'Goals Against (GA)': '298',
  '+ / -': '-25'},
 {'Team Name': 'Edmonton Oilers',
  'Year': '1990',
  'Wins': '37',
  'Losses': '37',
  'OT Losses': '',
  'Win %': '0.463',
  'Goals For (GF)': '272',
  'Goals Against (GA)': '272',
  '+ / -': '0'},
 {'Team Name': 'Hartford Whalers',
  'Year': '1990',
  'Wins': '31',
  'Losses': '38',
  'OT Losses': '',
  'Win %': '0.388',
  'Goals For (GF)': '238',
  'Goals Against (GA)': '276',
  '+ / -': '-38'},
 {'Team Name': 'Los Angeles Kings',
  'Year': '1990',
  'Wins': '46',
  'Losses': '24',
  'OT Losses': '',
  'Win %': '0.575',
  'Goals For (GF)': '340',
  'Goals Against (GA)': '254',
  '+ / -': '86'},
 {'Team Name': 'Minnesota North Stars',
  'Year': '1990',
  'Wins': '27',
  'Losses': '39',
  'OT Losses': '',
  'Win %': '0.338',
  'Goals For (GF)': '256',
  'Goals Against (GA)': '266',
  '+ / -': '-10'},
 {'Team Name': 'Montreal Canadiens',
  'Year': '1990',
  'Wins': '39',
  'Losses': '30',
  'OT Losses': '',
  'Win %': '0.487',
  'Goals For (GF)': '273',
  'Goals Against (GA)': '249',
  '+ / -': '24'},
 {'Team Name': 'New Jersey Devils',
  'Year': '1990',
  'Wins': '32',
  'Losses': '33',
  'OT Losses': '',
  'Win %': '0.4',
  'Goals For (GF)': '272',
  'Goals Against (GA)': '264',
  '+ / -': '8'},
 {'Team Name': 'New York Islanders',
  'Year': '1990',
  'Wins': '25',
  'Losses': '45',
  'OT Losses': '',
  'Win %': '0.312',
  'Goals For (GF)': '223',
  'Goals Against (GA)': '290',
  '+ / -': '-67'},
 {'Team Name': 'New York Rangers',
  'Year': '1990',
  'Wins': '36',
  'Losses': '31',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '297',
  'Goals Against (GA)': '265',
  '+ / -': '32'},
 {'Team Name': 'Philadelphia Flyers',
  'Year': '1990',
  'Wins': '33',
  'Losses': '37',
  'OT Losses': '',
  'Win %': '0.412',
  'Goals For (GF)': '252',
  'Goals Against (GA)': '267',
  '+ / -': '-15'},
 {'Team Name': 'Pittsburgh Penguins',
  'Year': '1990',
  'Wins': '41',
  'Losses': '33',
  'OT Losses': '',
  'Win %': '0.512',
  'Goals For (GF)': '342',
  'Goals Against (GA)': '305',
  '+ / -': '37'},
 {'Team Name': 'Quebec Nordiques',
  'Year': '1990',
  'Wins': '16',
  'Losses': '50',
  'OT Losses': '',
  'Win %': '0.2',
  'Goals For (GF)': '236',
  'Goals Against (GA)': '354',
  '+ / -': '-118'},
 {'Team Name': 'St. Louis Blues',
  'Year': '1990',
  'Wins': '47',
  'Losses': '22',
  'OT Losses': '',
  'Win %': '0.588',
  'Goals For (GF)': '310',
  'Goals Against (GA)': '250',
  '+ / -': '60'},
 {'Team Name': 'Toronto Maple Leafs',
  'Year': '1990',
  'Wins': '23',
  'Losses': '46',
  'OT Losses': '',
  'Win %': '0.287',
  'Goals For (GF)': '241',
  'Goals Against (GA)': '318',
  '+ / -': '-77'},
 {'Team Name': 'Vancouver Canucks',
  'Year': '1990',
  'Wins': '28',
  'Losses': '43',
  'OT Losses': '',
  'Win %': '0.35',
  'Goals For (GF)': '243',
  'Goals Against (GA)': '315',
  '+ / -': '-72'},
 {'Team Name': 'Washington Capitals',
  'Year': '1990',
  'Wins': '37',
  'Losses': '36',
  'OT Losses': '',
  'Win %': '0.463',
  'Goals For (GF)': '258',
  'Goals Against (GA)': '258',
  '+ / -': '0'},
 {'Team Name': 'Winnipeg Jets',
  'Year': '1990',
  'Wins': '26',
  'Losses': '43',
  'OT Losses': '',
  'Win %': '0.325',
  'Goals For (GF)': '260',
  'Goals Against (GA)': '288',
  '+ / -': '-28'},
 {'Team Name': 'Boston Bruins',
  'Year': '1991',
  'Wins': '36',
  'Losses': '32',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '270',
  'Goals Against (GA)': '275',
  '+ / -': '-5'},
 {'Team Name': 'Buffalo Sabres',
  'Year': '1991',
  'Wins': '31',
  'Losses': '37',
  'OT Losses': '',
  'Win %': '0.388',
  'Goals For (GF)': '289',
  'Goals Against (GA)': '299',
  '+ / -': '-10'},
 {'Team Name': 'Calgary Flames',
  'Year': '1991',
  'Wins': '31',
  'Losses': '37',
  'OT Losses': '',
  'Win %': '0.388',
  'Goals For (GF)': '296',
  'Goals Against (GA)': '305',
  '+ / -': '-9'},
 {'Team Name': 'Chicago Blackhawks',
  'Year': '1991',
  'Wins': '36',
  'Losses': '29',
  'OT Losses': '',
  'Win %': '0.45',
  'Goals For (GF)': '257',
  'Goals Against (GA)': '236',
  '+ / -': '21'}]

In [57]:
df = pd.DataFrame(list_df)
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,,0.463,272,272,0
6,Hartford Whalers,1990,31,38,,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,,0.487,273,249,24
10,New Jersey Devils,1990,32,33,,0.4,272,264,8
11,New York Islanders,1990,25,45,,0.312,223,290,-67
12,New York Rangers,1990,36,31,,0.45,297,265,32
13,Philadelphia Flyers,1990,33,37,,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,,0.2,236,354,-118
16,St. Louis Blues,1990,47,22,,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,,0.35,243,315,-72
19,Washington Capitals,1990,37,36,,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
21,Boston Bruins,1991,36,32,,0.45,270,275,-5
22,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
23,Calgary Flames,1991,31,37,,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,,0.45,257,236,21

In [47]:
t_row = trs[1].find_all("td")
for i in range (len(dict)):
    # print()
    dict[list(dict.keys())[i]] = t_row[i].text.strip()

In [48]:
dict

{'Team Name': 'Boston Bruins',
 ' Year': '1990',
 ' Wins': '44',
 ' Losses': '24',
 ' OT Losses': '',
 ' Win %': '0.55',
 ' Goals For (GF)': '299',
 ' Goals Against (GA)': '264',
 ' + / -': '35'}

In [59]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
r=requests.get('https://www.scrapethissite.com/pages/forms/')
print(r.status_code)
soup=BeautifulSoup(r.text,'html.parser')

200

In [ ]:

web=soup.find_all('tr',class_='team')
list = [] 
for table in web[1:]:
    dic={
        'Team Name':'',
        'Year':'',
        'Wins':'',
        'Losses':'',
        'OT Losses':'Nill',
        'Win %':'',
        'Goals For (GF)':'',
        'Goals Against (GA)':'',
        '+ / -':'',
    }
    dic['Team Name']=table.find('td',class_='name').text.strip()
    dic['Year']=table.find('td',class_='year').text.strip()
    dic['Wins']=table.find('td',class_='wins').text.strip()
    dic['Losses']=table.find('td',class_='losses').text.strip()
    
    try:
        dic['Win %']=table.find('td',class_='pct text-success').text.strip()
    except:
        dic['Win %']=table.find('td',class_='pct text-danger').text.strip()

    dic['Goals For (GF)']=table.find('td',class_='gf').text.strip()
    dic['Goals Against (GA)']=table.find('td',class_='ga').text.strip()
    # dic['+ / -']=table.find('td',class_='diff text-success').text.strip()
    dic['+ / -']=table.find('td',class_='diff').text.strip()

    # print(dic)
    # list.append(dic.copy())
    list.append(dic)
print(list)

[{'Team Name': 'Buffalo Sabres', 'Year': '1990', 'Wins': '31', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '292', 'Goals Against (GA)': '278', '+ / -': '14'}, {'Team Name': 'Calgary Flames', 'Year': '1990', 'Wins': '46', 'Losses': '26', 'OT Losses': 'Nill', 'Win %': '0.575', 'Goals For (GF)': '344', 'Goals Against (GA)': '263', '+ / -': '81'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1990', 'Wins': '49', 'Losses': '23', 'OT Losses': 'Nill', 'Win %': '0.613', 'Goals For (GF)': '284', 'Goals Against (GA)': '211', '+ / -': '73'}, {'Team Name': 'Detroit Red Wings', 'Year': '1990', 'Wins': '34', 'Losses': '38', 'OT Losses': 'Nill', 'Win %': '0.425', 'Goals For (GF)': '273', 'Goals Against (GA)': '298', '+ / -': '-25'}, {'Team Name': 'Edmonton Oilers', 'Year': '1990', 'Wins': '37', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.463', 'Goals For (GF)': '272', 'Goals Against (GA)': '272', '+ / -': '0'}, {'Team Name': 'Hartford Whalers', 'Year': '1990', 'Wins': '31', 'Losses': '38', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '238', 'Goals Against (GA)': '276', '+ / -': '-38'}, {'Team Name': 'Los Angeles Kings', 'Year': '1990', 'Wins': '46', 'Losses': '24', 'OT Losses': 'Nill', 'Win %': '0.575', 'Goals For (GF)': '340', 'Goals Against (GA)': '254', '+ / -': '86'}, {'Team Name': 'Minnesota North Stars', 'Year': '1990', 'Wins': '27', 'Losses': '39', 'OT Losses': 'Nill', 'Win %': '0.338', 'Goals For (GF)': '256', 'Goals Against (GA)': '266', '+ / -': '-10'}, {'Team Name': 'Montreal Canadiens', 'Year': '1990', 'Wins': '39', 'Losses': '30', 'OT Losses': 'Nill', 'Win %': '0.487', 'Goals For (GF)': '273', 'Goals Against (GA)': '249', '+ / -': '24'}, {'Team Name': 'New Jersey Devils', 'Year': '1990', 'Wins': '32', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.4', 'Goals For (GF)': '272', 'Goals Against (GA)': '264', '+ / -': '8'}, {'Team Name': 'New York Islanders', 'Year': '1990', 'Wins': '25', 'Losses': '45', 'OT Losses': 'Nill', 'Win %': '0.312', 'Goals For (GF)': '223', 'Goals Against (GA)': '290', '+ / -': '-67'}, {'Team Name': 'New York Rangers', 'Year': '1990', 'Wins': '36', 'Losses': '31', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '297', 'Goals Against (GA)': '265', '+ / -': '32'}, {'Team Name': 'Philadelphia Flyers', 'Year': '1990', 'Wins': '33', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.412', 'Goals For (GF)': '252', 'Goals Against (GA)': '267', '+ / -': '-15'}, {'Team Name': 'Pittsburgh Penguins', 'Year': '1990', 'Wins': '41', 'Losses': '33', 'OT Losses': 'Nill', 'Win %': '0.512', 'Goals For (GF)': '342', 'Goals Against (GA)': '305', '+ / -': '37'}, {'Team Name': 'Quebec Nordiques', 'Year': '1990', 'Wins': '16', 'Losses': '50', 'OT Losses': 'Nill', 'Win %': '0.2', 'Goals For (GF)': '236', 'Goals Against (GA)': '354', '+ / -': '-118'}, {'Team Name': 'St. Louis Blues', 'Year': '1990', 'Wins': '47', 'Losses': '22', 'OT Losses': 'Nill', 'Win %': '0.588', 'Goals For (GF)': '310', 'Goals Against (GA)': '250', '+ / -': '60'}, {'Team Name': 'Toronto Maple Leafs', 'Year': '1990', 'Wins': '23', 'Losses': '46', 'OT Losses': 'Nill', 'Win %': '0.287', 'Goals For (GF)': '241', 'Goals Against (GA)': '318', '+ / -': '-77'}, {'Team Name': 'Vancouver Canucks', 'Year': '1990', 'Wins': '28', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.35', 'Goals For (GF)': '243', 'Goals Against (GA)': '315', '+ / -': '-72'}, {'Team Name': 'Washington Capitals', 'Year': '1990', 'Wins': '37', 'Losses': '36', 'OT Losses': 'Nill', 'Win %': '0.463', 'Goals For (GF)': '258', 'Goals Against (GA)': '258', '+ / -': '0'}, {'Team Name': 'Winnipeg Jets', 'Year': '1990', 'Wins': '26', 'Losses': '43', 'OT Losses': 'Nill', 'Win %': '0.325', 'Goals For (GF)': '260', 'Goals Against (GA)': '288', '+ / -': '-28'}, {'Team Name': 'Boston Bruins', 'Year': '1991', 'Wins': '36', 'Losses': '32', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '270', 'Goals Against (GA)': '275', '+ / -': '-5'}, {'Team Name': 'Buffalo Sabres', 'Year': '1991', 'Wins': '31', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '289', 'Goals Against (GA)': '299', '+ / -': '-10'}, {'Team Name': 'Calgary Flames', 'Year': '1991', 'Wins': '31', 'Losses': '37', 'OT Losses': 'Nill', 'Win %': '0.388', 'Goals For (GF)': '296', 'Goals Against (GA)': '305', '+ / -': '-9'}, {'Team Name': 'Chicago Blackhawks', 'Year': '1991', 'Wins': '36', 'Losses': '29', 'OT Losses': 'Nill', 'Win %': '0.45', 'Goals For (GF)': '257', 'Goals Against (GA)': '236', '+ / -': '21'}]

In [ ]:
df = pd.DataFrame(list)
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Buffalo Sabres,1990,31,30,Nill,0.388,292,278,14
1,Calgary Flames,1990,46,26,Nill,0.575,344,263,81
2,Chicago Blackhawks,1990,49,23,Nill,0.613,284,211,73
3,Detroit Red Wings,1990,34,38,Nill,0.425,273,298,-25
4,Edmonton Oilers,1990,37,37,Nill,0.463,272,272,0
5,Hartford Whalers,1990,31,38,Nill,0.388,238,276,-38
6,Los Angeles Kings,1990,46,24,Nill,0.575,340,254,86
7,Minnesota North Stars,1990,27,39,Nill,0.338,256,266,-10
8,Montreal Canadiens,1990,39,30,Nill,0.487,273,249,24
9,New Jersey Devils,1990,32,33,Nill,0.4,272,264,8
10,New York Islanders,1990,25,45,Nill,0.312,223,290,-67
11,New York Rangers,1990,36,31,Nill,0.45,297,265,32
12,Philadelphia Flyers,1990,33,37,Nill,0.412,252,267,-15
13,Pittsburgh Penguins,1990,41,33,Nill,0.512,342,305,37
14,Quebec Nordiques,1990,16,50,Nill,0.2,236,354,-118
15,St. Louis Blues,1990,47,22,Nill,0.588,310,250,60
16,Toronto Maple Leafs,1990,23,46,Nill,0.287,241,318,-77
17,Vancouver Canucks,1990,28,43,Nill,0.35,243,315,-72
18,Washington Capitals,1990,37,36,Nill,0.463,258,258,0
19,Winnipeg Jets,1990,26,43,Nill,0.325,260,288,-28
20,Boston Bruins,1991,36,32,Nill,0.45,270,275,-5
21,Buffalo Sabres,1991,31,37,Nill,0.388,289,299,-10
22,Calgary Flames,1991,31,37,Nill,0.388,296,305,-9
23,Chicago Blackhawks,1991,36,29,Nill,0.45,257,236,21

In [71]:
df.head(1)

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Buffalo Sabres,1990,31,30,Nill,0.388,292,278,14

In [70]:
df.to_csv("scrape_this_site_q_3_1.csv",index=False)