# 3.1 Extract Table of first page & save into csv file.

In [22]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://www.scrapethissite.com/pages/forms/')
response.status_code

soup = BeautifulSoup(response.text, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="hockey">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Hockey Teams: Forms, Searching and Pagination
        <small>
         25 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         8 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">
         http://www.opensourcesports.com/hockey/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row search-area">
      <div class="col-md-12 text-center">
       <form action="/pages/forms/" class="form form-inline" method="GET">
        <label for="q">
         Search for Teams:
        </label>
        <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
        <input class="btn btn-primary" type="submit" value="Search"/>
       </form>
       <hr/>
      </div>
     </div>
     <!--.row.search-area-->
     <table class="table">
      <tr>
       <th>
        Team Name
       </th>
       <th>
        Year
       </th>
       <th>
        Wins
       </th>
       <th>
        Losses
       </th>
       <th>
        OT Losses
       </th>
       <th>
        Win %
       </th>
       <th>
        Goals For (GF)
       </th>
       <th>
        Goals Against (GA)
       </th>
       <th>
        + / -
       </th>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        44
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.55
       </td>
       <td class="gf">
        299
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        35
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        292
       </td>
       <td class="ga">
        278
       </td>
       <td class="diff text-success">
        14
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        26
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        344
       </td>
       <td class="ga">
        263
       </td>
       <td class="diff text-success">
        81
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        49
       </td>
       <td class="losses">
        23
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.613
       </td>
       <td class="gf">
        284
       </td>
       <td class="ga">
        211
       </td>
       <td class="diff text-success">
        73
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        34
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.425
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        298
       </td>
       <td class="diff text-danger">
        -25
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Edmonton Oilers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        272
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Hartford Whalers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        238
       </td>
       <td class="ga">
        276
       </td>
       <td class="diff text-danger">
        -38
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Los Angeles Kings
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.575
       </td>
       <td class="gf">
        340
       </td>
       <td class="ga">
        254
       </td>
       <td class="diff text-success">
        86
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Minnesota North Stars
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        27
       </td>
       <td class="losses">
        39
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.338
       </td>
       <td class="gf">
        256
       </td>
       <td class="ga">
        266
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Montreal Canadiens
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.487
       </td>
       <td class="gf">
        273
       </td>
       <td class="ga">
        249
       </td>
       <td class="diff text-success">
        24
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New Jersey Devils
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        32
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.4
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        8
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Islanders
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        25
       </td>
       <td class="losses">
        45
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.312
       </td>
       <td class="gf">
        223
       </td>
       <td class="ga">
        290
       </td>
       <td class="diff text-danger">
        -67
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Rangers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        31
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        297
       </td>
       <td class="ga">
        265
       </td>
       <td class="diff text-success">
        32
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Philadelphia Flyers
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.412
       </td>
       <td class="gf">
        252
       </td>
       <td class="ga">
        267
       </td>
       <td class="diff text-danger">
        -15
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Pittsburgh Penguins
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        41
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        342
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-success">
        37
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Quebec Nordiques
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        16
       </td>
       <td class="losses">
        50
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.2
       </td>
       <td class="gf">
        236
       </td>
       <td class="ga">
        354
       </td>
       <td class="diff text-danger">
        -118
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        St. Louis Blues
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        22
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.588
       </td>
       <td class="gf">
        310
       </td>
       <td class="ga">
        250
       </td>
       <td class="diff text-success">
        60
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Toronto Maple Leafs
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        23
       </td>
       <td class="losses">
        46
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.287
       </td>
       <td class="gf">
        241
       </td>
       <td class="ga">
        318
       </td>
       <td class="diff text-danger">
        -77
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Vancouver Canucks
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        28
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.35
       </td>
       <td class="gf">
        243
       </td>
       <td class="ga">
        315
       </td>
       <td class="diff text-danger">
        -72
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Washington Capitals
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.463
       </td>
       <td class="gf">
        258
       </td>
       <td class="ga">
        258
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Winnipeg Jets
       </td>
       <td class="year">
        1990
       </td>
       <td class="wins">
        26
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.325
       </td>
       <td class="gf">
        260
       </td>
       <td class="ga">
        288
       </td>
       <td class="diff text-danger">
        -28
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        32
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        270
       </td>
       <td class="ga">
        275
       </td>
       <td class="diff text-danger">
        -5
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        289
       </td>
       <td class="ga">
        299
       </td>
       <td class="diff text-danger">
        -10
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        31
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.388
       </td>
       <td class="gf">
        296
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-danger">
        -9
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        257
       </td>
       <td class="ga">
        236
       </td>
       <td class="diff text-success">
        21
       </td>
      </tr>
     </table>
     <div class="row pagination-area">
      <div class="col-md-10 text-center">
       <ul class="pagination">
        <li>
         <a href="/pages/forms/?page_num=1">
          1
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=2">
          2
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=3">
          3
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=4">
          4
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=5">
          5
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=6">
          6
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=7">
          7
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=8">
          8
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=9">
          9
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=10">
          10
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=11">
          11
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=12">
          12
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=13">
          13
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=14">
          14
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=15">
          15
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=16">
          16
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=17">
          17
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=18">
          18
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=19">
          19
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=20">
          20
         </a>

In [23]:
var = soup.find('table',class_='table')

var1= soup.find_all('table',class_='table')
var1

[<table class="table">
 <tr>
 <th>
                             Team Name
                         </th>
 <th>
                             Year
                         </th>
 <th>
                             Wins
                         </th>
 <th>
                             Losses
                         </th>
 <th>
                             OT Losses
                         </th>
 <th>
                             Win %
                         </th>
 <th>
                             Goals For (GF)
                         </th>
 <th>
                             Goals Against (GA)
                         </th>
 <th>
                             + / -
                         </th>
 </tr>
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             44
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.55
                         </td>
 <td class="gf">
                             299
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             292
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-success">
                             14
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             344
                         </td>
 <td class="ga">
                             263
                         </td>
 <td class="diff text-success">
                             81
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             49
                         </td>
 <td class="losses">
                             23
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.613
                         </td>
 <td class="gf">
                             284
                         </td>
 <td class="ga">
                             211
                         </td>
 <td class="diff text-success">
                             73
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.425
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             298
                         </td>
 <td class="diff text-danger">
                             -25
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             272
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             238
                         </td>
 <td class="ga">
                             276
                         </td>
 <td class="diff text-danger">
                             -38
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.575
                         </td>
 <td class="gf">
                             340
                         </td>
 <td class="ga">
                             254
                         </td>
 <td class="diff text-success">
                             86
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             27
                         </td>
 <td class="losses">
                             39
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.338
                         </td>
 <td class="gf">
                             256
                         </td>
 <td class="ga">
                             266
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.487
                         </td>
 <td class="gf">
                             273
                         </td>
 <td class="ga">
                             249
                         </td>
 <td class="diff text-success">
                             24
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             8
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             25
                         </td>
 <td class="losses">
                             45
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.312
                         </td>
 <td class="gf">
                             223
                         </td>
 <td class="ga">
                             290
                         </td>
 <td class="diff text-danger">
                             -67
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             297
                         </td>
 <td class="ga">
                             265
                         </td>
 <td class="diff text-success">
                             32
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.412
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             267
                         </td>
 <td class="diff text-danger">
                             -15
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             342
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-success">
                             37
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             16
                         </td>
 <td class="losses">
                             50
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.2
                         </td>
 <td class="gf">
                             236
                         </td>
 <td class="ga">
                             354
                         </td>
 <td class="diff text-danger">
                             -118
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             22
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.588
                         </td>
 <td class="gf">
                             310
                         </td>
 <td class="ga">
                             250
                         </td>
 <td class="diff text-success">
                             60
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             23
                         </td>
 <td class="losses">
                             46
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.287
                         </td>
 <td class="gf">
                             241
                         </td>
 <td class="ga">
                             318
                         </td>
 <td class="diff text-danger">
                             -77
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             28
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.35
                         </td>
 <td class="gf">
                             243
                         </td>
 <td class="ga">
                             315
                         </td>
 <td class="diff text-danger">
                             -72
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.463
                         </td>
 <td class="gf">
                             258
                         </td>
 <td class="ga">
                             258
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1990
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.325
                         </td>
 <td class="gf">
                             260
                         </td>
 <td class="ga">
                             288
                         </td>
 <td class="diff text-danger">
                             -28
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             270
                         </td>
 <td class="ga">
                             275
                         </td>
 <td class="diff text-danger">
                             -5
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             289
                         </td>
 <td class="ga">
                             299
                         </td>
 <td class="diff text-danger">
                             -10
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             31
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.388
                         </td>
 <td class="gf">
                             296
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-danger">
                             -9
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             257
                         </td>
 <td class="ga">
                             236
                         </td>
 <td class="diff text-success">
                             21
                         </td>
 </tr>
 </table>]

In [27]:
len(var1)

1

In [29]:
len(tr)

NameError: name 'tr' is not defined

In [33]:
len(trs)

26

In [17]:
trs =var1[0].find_all('tr')

In [18]:
tr = trs[1]

In [ ]:
for tr

In [22]:
dict['name']= tr.find('td',class_='name').text.strip()
dict['year']=tr.find('td',class_='year').text.strip()
dict['wins']=tr.find('td',class_='wins').text.strip()
dict['losses']=tr.find('td',class_='losses').text.strip()
dict['ot-losses']=tr.find('td',class_='ot-losses').text.strip()
# dict['pct text-success']=tr.find('td',class_='pct text-success').text.strip()
dict['pct text-success']=tr.find('td',class_='pct').text.strip()

dict['gf']=tr.find('td',class_='gf').text.strip()
dict['ga']=tr.find('td',class_='ga').text.strip()
dict['diff text-success']=tr.find('td',class_='diff').text.strip()
# dict['diff text-success']=tr.find('td',class_='diff text-success').text.strip()

print(dict)

{'name': 'Los Angeles Kings', 'year': '1992', 'wins': '39', 'losses': '35', 'ot-losses': '', 'pct text-success': '0.464', 'gf': '338', 'ga': '340', 'diff text-success': '-2'}

In [23]:
list = []
for i in trs[1:]:
        dict={
            'name':'',
            'year':'',
            'wins':'',
            'losses':'',
            'ot-losses':'',
            'pct text-success':'',
            'gf':'',
            'ga':'',
            'diff text-success':''


        }
    # print(dict)
        dict['name']= i.find('td',class_='name').text.strip()
        dict['year']=i.find('td',class_='year').text.strip()
        dict['wins']=i.find('td',class_='wins').text.strip()
        dict['losses']=i.find('td',class_='losses').text.strip()
        dict['ot-losses']=i.find('td',class_='ot-losses').text.strip()
        # dict['pct text-success']=i.find('td',class_='pct text-success').text.strip() # 
        dict['pct text-success']=i.find('td',class_='pct').text.strip()

        dict['gf']=i.find('td',class_='gf').text.strip()
        dict['ga']=i.find('td',class_='ga').text.strip()
        # dict['diff text-success']=i.find('td',class_='diff text-success').text.strip()
        dict['diff text-success']=tr.find('td',class_='diff').text.strip()

        list.append(dict.copy())

In [24]:
import pandas as pd
# list = []
# list.append(dict)
df = pd.DataFrame(list)
df
df.to_csv('scrapethissite q3_3.csv',index=False)

# 3.2 Extract Table of second page & save into another csv file.

In [7]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://www.scrapethissite.com/pages/forms/?page_num=2')
response.status_code
soup = BeautifulSoup(response.text, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="hockey">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Hockey Teams: Forms, Searching and Pagination
        <small>
         25 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         8 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">
         http://www.opensourcesports.com/hockey/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row search-area">
      <div class="col-md-12 text-center">
       <form action="/pages/forms/" class="form form-inline" method="GET">
        <label for="q">
         Search for Teams:
        </label>
        <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
        <input class="btn btn-primary" type="submit" value="Search"/>
       </form>
       <hr/>
      </div>
     </div>
     <!--.row.search-area-->
     <table class="table">
      <tr>
       <th>
        Team Name
       </th>
       <th>
        Year
       </th>
       <th>
        Wins
       </th>
       <th>
        Losses
       </th>
       <th>
        OT Losses
       </th>
       <th>
        Win %
       </th>
       <th>
        Goals For (GF)
       </th>
       <th>
        Goals Against (GA)
       </th>
       <th>
        + / -
       </th>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        43
       </td>
       <td class="losses">
        25
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.537
       </td>
       <td class="gf">
        320
       </td>
       <td class="ga">
        256
       </td>
       <td class="diff text-success">
        64
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Edmonton Oilers
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        34
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        295
       </td>
       <td class="ga">
        297
       </td>
       <td class="diff text-danger">
        -2
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Hartford Whalers
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        26
       </td>
       <td class="losses">
        41
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.325
       </td>
       <td class="gf">
        247
       </td>
       <td class="ga">
        283
       </td>
       <td class="diff text-danger">
        -36
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Los Angeles Kings
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        35
       </td>
       <td class="losses">
        31
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.438
       </td>
       <td class="gf">
        287
       </td>
       <td class="ga">
        296
       </td>
       <td class="diff text-danger">
        -9
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Minnesota North Stars
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        32
       </td>
       <td class="losses">
        42
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.4
       </td>
       <td class="gf">
        246
       </td>
       <td class="ga">
        278
       </td>
       <td class="diff text-danger">
        -32
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Montreal Canadiens
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        41
       </td>
       <td class="losses">
        28
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        267
       </td>
       <td class="ga">
        207
       </td>
       <td class="diff text-success">
        60
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New Jersey Devils
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        38
       </td>
       <td class="losses">
        31
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.475
       </td>
       <td class="gf">
        289
       </td>
       <td class="ga">
        259
       </td>
       <td class="diff text-success">
        30
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Islanders
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        34
       </td>
       <td class="losses">
        35
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.425
       </td>
       <td class="gf">
        291
       </td>
       <td class="ga">
        299
       </td>
       <td class="diff text-danger">
        -8
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Rangers
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        50
       </td>
       <td class="losses">
        25
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.625
       </td>
       <td class="gf">
        321
       </td>
       <td class="ga">
        246
       </td>
       <td class="diff text-success">
        75
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Philadelphia Flyers
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        32
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.4
       </td>
       <td class="gf">
        252
       </td>
       <td class="ga">
        273
       </td>
       <td class="diff text-danger">
        -21
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Pittsburgh Penguins
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        32
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.487
       </td>
       <td class="gf">
        343
       </td>
       <td class="ga">
        308
       </td>
       <td class="diff text-success">
        35
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Quebec Nordiques
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        20
       </td>
       <td class="losses">
        48
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.25
       </td>
       <td class="gf">
        255
       </td>
       <td class="ga">
        318
       </td>
       <td class="diff text-danger">
        -63
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        San Jose Sharks
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        17
       </td>
       <td class="losses">
        58
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.212
       </td>
       <td class="gf">
        219
       </td>
       <td class="ga">
        359
       </td>
       <td class="diff text-danger">
        -140
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        St. Louis Blues
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.45
       </td>
       <td class="gf">
        279
       </td>
       <td class="ga">
        266
       </td>
       <td class="diff text-success">
        13
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Toronto Maple Leafs
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        30
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.375
       </td>
       <td class="gf">
        234
       </td>
       <td class="ga">
        294
       </td>
       <td class="diff text-danger">
        -60
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Vancouver Canucks
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        42
       </td>
       <td class="losses">
        26
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.525
       </td>
       <td class="gf">
        285
       </td>
       <td class="ga">
        250
       </td>
       <td class="diff text-success">
        35
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Washington Capitals
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        45
       </td>
       <td class="losses">
        27
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.562
       </td>
       <td class="gf">
        330
       </td>
       <td class="ga">
        275
       </td>
       <td class="diff text-success">
        55
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Winnipeg Jets
       </td>
       <td class="year">
        1991
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        32
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.412
       </td>
       <td class="gf">
        251
       </td>
       <td class="ga">
        244
       </td>
       <td class="diff text-success">
        7
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        51
       </td>
       <td class="losses">
        26
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.607
       </td>
       <td class="gf">
        332
       </td>
       <td class="ga">
        268
       </td>
       <td class="diff text-success">
        64
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        38
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.452
       </td>
       <td class="gf">
        335
       </td>
       <td class="ga">
        297
       </td>
       <td class="diff text-success">
        38
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        43
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        322
       </td>
       <td class="ga">
        282
       </td>
       <td class="diff text-success">
        40
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        25
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.56
       </td>
       <td class="gf">
        279
       </td>
       <td class="ga">
        230
       </td>
       <td class="diff text-success">
        49
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        28
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.56
       </td>
       <td class="gf">
        369
       </td>
       <td class="ga">
        280
       </td>
       <td class="diff text-success">
        89
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Edmonton Oilers
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        26
       </td>
       <td class="losses">
        50
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.31
       </td>
       <td class="gf">
        242
       </td>
       <td class="ga">
        337
       </td>
       <td class="diff text-danger">
        -95
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Hartford Whalers
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        26
       </td>
       <td class="losses">
        52
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.31
       </td>
       <td class="gf">
        284
       </td>
       <td class="ga">
        369
       </td>
       <td class="diff text-danger">
        -85
       </td>
      </tr>
     </table>
     <div class="row pagination-area">
      <div class="col-md-10 text-center">
       <ul class="pagination">
        <li>
         <a aria-label="Previous" href="/pages/forms/?page_num=1">
          <span aria-hidden="true">
           «
          </span>
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=1">
          1
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=2">
          <strong>
           2
          </strong>
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=3">
          3
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=4">
          4
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=5">
          5
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=6">
          6
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=7">
          7
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=8">
          8
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=9">
          9
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=10">
          10
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=11">
          11
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=12">
          12
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=13">
          13
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=14">
          14
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=15">
          15
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=16">
          16
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=17">
          17
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=18">

In [8]:
trs = soup.find_all('table',class_='table')
trs

[<table class="table">
 <tr>
 <th>
                             Team Name
                         </th>
 <th>
                             Year
                         </th>
 <th>
                             Wins
                         </th>
 <th>
                             Losses
                         </th>
 <th>
                             OT Losses
                         </th>
 <th>
                             Win %
                         </th>
 <th>
                             Goals For (GF)
                         </th>
 <th>
                             Goals Against (GA)
                         </th>
 <th>
                             + / -
                         </th>
 </tr>
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             43
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.537
                         </td>
 <td class="gf">
                             320
                         </td>
 <td class="ga">
                             256
                         </td>
 <td class="diff text-success">
                             64
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             34
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             295
                         </td>
 <td class="ga">
                             297
                         </td>
 <td class="diff text-danger">
                             -2
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             41
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.325
                         </td>
 <td class="gf">
                             247
                         </td>
 <td class="ga">
                             283
                         </td>
 <td class="diff text-danger">
                             -36
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             35
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.438
                         </td>
 <td class="gf">
                             287
                         </td>
 <td class="ga">
                             296
                         </td>
 <td class="diff text-danger">
                             -9
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             42
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             246
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-danger">
                             -32
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             28
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             267
                         </td>
 <td class="ga">
                             207
                         </td>
 <td class="diff text-success">
                             60
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             38
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.475
                         </td>
 <td class="gf">
                             289
                         </td>
 <td class="ga">
                             259
                         </td>
 <td class="diff text-success">
                             30
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             35
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.425
                         </td>
 <td class="gf">
                             291
                         </td>
 <td class="ga">
                             299
                         </td>
 <td class="diff text-danger">
                             -8
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             50
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.625
                         </td>
 <td class="gf">
                             321
                         </td>
 <td class="ga">
                             246
                         </td>
 <td class="diff text-success">
                             75
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             273
                         </td>
 <td class="diff text-danger">
                             -21
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.487
                         </td>
 <td class="gf">
                             343
                         </td>
 <td class="ga">
                             308
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             20
                         </td>
 <td class="losses">
                             48
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.25
                         </td>
 <td class="gf">
                             255
                         </td>
 <td class="ga">
                             318
                         </td>
 <td class="diff text-danger">
                             -63
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             San Jose Sharks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             17
                         </td>
 <td class="losses">
                             58
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.212
                         </td>
 <td class="gf">
                             219
                         </td>
 <td class="ga">
                             359
                         </td>
 <td class="diff text-danger">
                             -140
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             279
                         </td>
 <td class="ga">
                             266
                         </td>
 <td class="diff text-success">
                             13
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             30
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.375
                         </td>
 <td class="gf">
                             234
                         </td>
 <td class="ga">
                             294
                         </td>
 <td class="diff text-danger">
                             -60
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             42
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.525
                         </td>
 <td class="gf">
                             285
                         </td>
 <td class="ga">
                             250
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             45
                         </td>
 <td class="losses">
                             27
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.562
                         </td>
 <td class="gf">
                             330
                         </td>
 <td class="ga">
                             275
                         </td>
 <td class="diff text-success">
                             55
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.412
                         </td>
 <td class="gf">
                             251
                         </td>
 <td class="ga">
                             244
                         </td>
 <td class="diff text-success">
                             7
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             51
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.607
                         </td>
 <td class="gf">
                             332
                         </td>
 <td class="ga">
                             268
                         </td>
 <td class="diff text-success">
                             64
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             38
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.452
                         </td>
 <td class="gf">
                             335
                         </td>
 <td class="ga">
                             297
                         </td>
 <td class="diff text-success">
                             38
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             43
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             322
                         </td>
 <td class="ga">
                             282
                         </td>
 <td class="diff text-success">
                             40
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.56
                         </td>
 <td class="gf">
                             279
                         </td>
 <td class="ga">
                             230
                         </td>
 <td class="diff text-success">
                             49
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             28
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.56
                         </td>
 <td class="gf">
                             369
                         </td>
 <td class="ga">
                             280
                         </td>
 <td class="diff text-success">
                             89
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             50
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.31
                         </td>
 <td class="gf">
                             242
                         </td>
 <td class="ga">
                             337
                         </td>
 <td class="diff text-danger">
                             -95
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             52
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.31
                         </td>
 <td class="gf">
                             284
                         </td>
 <td class="ga">
                             369
                         </td>
 <td class="diff text-danger">
                             -85
                         </td>
 </tr>
 </table>]

In [9]:
trs.find_all('tr')

AttributeError: ResultSet object has no attribute "find_all". You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [48]:
len(trs)

26

In [11]:
va = trs[0].find_all('tr')

In [15]:
va= trs[0]

In [34]:
len(va)

53

In [46]:
len(va)

53

In [47]:
len(trs)

26

In [10]:
trs[0].find_all('tr')

[<tr>
 <th>
                             Team Name
                         </th>
 <th>
                             Year
                         </th>
 <th>
                             Wins
                         </th>
 <th>
                             Losses
                         </th>
 <th>
                             OT Losses
                         </th>
 <th>
                             Win %
                         </th>
 <th>
                             Goals For (GF)
                         </th>
 <th>
                             Goals Against (GA)
                         </th>
 <th>
                             + / -
                         </th>
 </tr>,
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             43
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.537
                         </td>
 <td class="gf">
                             320
                         </td>
 <td class="ga">
                             256
                         </td>
 <td class="diff text-success">
                             64
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             34
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             295
                         </td>
 <td class="ga">
                             297
                         </td>
 <td class="diff text-danger">
                             -2
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             41
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.325
                         </td>
 <td class="gf">
                             247
                         </td>
 <td class="ga">
                             283
                         </td>
 <td class="diff text-danger">
                             -36
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             35
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.438
                         </td>
 <td class="gf">
                             287
                         </td>
 <td class="ga">
                             296
                         </td>
 <td class="diff text-danger">
                             -9
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             42
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             246
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-danger">
                             -32
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             28
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             267
                         </td>
 <td class="ga">
                             207
                         </td>
 <td class="diff text-success">
                             60
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             38
                         </td>
 <td class="losses">
                             31
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.475
                         </td>
 <td class="gf">
                             289
                         </td>
 <td class="ga">
                             259
                         </td>
 <td class="diff text-success">
                             30
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             35
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.425
                         </td>
 <td class="gf">
                             291
                         </td>
 <td class="ga">
                             299
                         </td>
 <td class="diff text-danger">
                             -8
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             50
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.625
                         </td>
 <td class="gf">
                             321
                         </td>
 <td class="ga">
                             246
                         </td>
 <td class="diff text-success">
                             75
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             32
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.4
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             273
                         </td>
 <td class="diff text-danger">
                             -21
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.487
                         </td>
 <td class="gf">
                             343
                         </td>
 <td class="ga">
                             308
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             20
                         </td>
 <td class="losses">
                             48
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.25
                         </td>
 <td class="gf">
                             255
                         </td>
 <td class="ga">
                             318
                         </td>
 <td class="diff text-danger">
                             -63
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             San Jose Sharks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             17
                         </td>
 <td class="losses">
                             58
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.212
                         </td>
 <td class="gf">
                             219
                         </td>
 <td class="ga">
                             359
                         </td>
 <td class="diff text-danger">
                             -140
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.45
                         </td>
 <td class="gf">
                             279
                         </td>
 <td class="ga">
                             266
                         </td>
 <td class="diff text-success">
                             13
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             30
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.375
                         </td>
 <td class="gf">
                             234
                         </td>
 <td class="ga">
                             294
                         </td>
 <td class="diff text-danger">
                             -60
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             42
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.525
                         </td>
 <td class="gf">
                             285
                         </td>
 <td class="ga">
                             250
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             45
                         </td>
 <td class="losses">
                             27
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.562
                         </td>
 <td class="gf">
                             330
                         </td>
 <td class="ga">
                             275
                         </td>
 <td class="diff text-success">
                             55
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1991
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.412
                         </td>
 <td class="gf">
                             251
                         </td>
 <td class="ga">
                             244
                         </td>
 <td class="diff text-success">
                             7
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             51
                         </td>
 <td class="losses">
                             26
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.607
                         </td>
 <td class="gf">
                             332
                         </td>
 <td class="ga">
                             268
                         </td>
 <td class="diff text-success">
                             64
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             38
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.452
                         </td>
 <td class="gf">
                             335
                         </td>
 <td class="ga">
                             297
                         </td>
 <td class="diff text-success">
                             38
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             43
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             322
                         </td>
 <td class="ga">
                             282
                         </td>
 <td class="diff text-success">
                             40
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.56
                         </td>
 <td class="gf">
                             279
                         </td>
 <td class="ga">
                             230
                         </td>
 <td class="diff text-success">
                             49
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             28
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.56
                         </td>
 <td class="gf">
                             369
                         </td>
 <td class="ga">
                             280
                         </td>
 <td class="diff text-success">
                             89
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             50
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.31
                         </td>
 <td class="gf">
                             242
                         </td>
 <td class="ga">
                             337
                         </td>
 <td class="diff text-danger">
                             -95
                         </td>
 </tr>,
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             26
                         </td>
 <td class="losses">
                             52
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.31
                         </td>
 <td class="gf">
                             284
                         </td>
 <td class="ga">
                             369
                         </td>
 <td class="diff text-danger">
                             -85
                         </td>
 </tr>]

In [62]:
va[1].find_all('tr')

KeyError: 1

In [32]:
dict['name']= tr.find('td',class_='name').text.strip()
dict['year']=tr.find('td',class_='year').text.strip()
dict['wins']=tr.find('td',class_='wins').text.strip()
dict['losses']=tr.find('td',class_='losses').text.strip()
dict['ot-losses']=tr.find('td',class_='ot-losses').text.strip()
# dict['pct text-success']=tr.find('td',class_='pct text-success').text.strip()
dict['pct text-success']=tr.find('td',class_='pct').text.strip()

dict['gf']=tr.find('td',class_='gf').text.strip()
dict['ga']=tr.find('td',class_='ga').text.strip()
dict['diff text-success']=tr.find('td',class_='diff').text.strip()
# dict['diff text-success']=tr.find('td',class_='diff text-success').text.strip()

print(dict)

{'name': 'Los Angeles Kings', 'year': '1992', 'wins': '39', 'losses': '35', 'ot-losses': '', 'pct text-success': '0.464', 'gf': '338', 'ga': '340', 'diff text-success': '-2'}

In [12]:
list = []
for i in trs[1:]:
        dict={
            'name':'',
            'year':'',
            'wins':'',
            'losses':'',
            'ot-losses':'',
            'pct text-success':'',
            'gf':'',
            'ga':'',
            'diff text-success':''


        }
    # print(dict)
        dict['name']= i.find('td',class_='name').text.strip()
        dict['year']=i.find('td',class_='year').text.strip()
        dict['wins']=i.find('td',class_='wins').text.strip()
        dict['losses']=i.find('td',class_='losses').text.strip()
        dict['ot-losses']=i.find('td',class_='ot-losses').text.strip()
        # dict['pct text-success']=i.find('td',class_='pct text-success').text.strip() # 
        dict['pct text-success']=i.find('td',class_='pct').text.strip()

        dict['gf']=i.find('td',class_='gf').text.strip()
        dict['ga']=i.find('td',class_='ga').text.strip()
        # dict['diff text-success']=i.find('td',class_='diff text-success').text.strip()
        dict['diff text-success']=tr.find('td',class_='diff').text.strip()

        list.append(dict.copy())

In [34]:
import pandas as pd
df = pd.DataFrame(list)
df
df.to_csv('scrapethissite q3_2.csv',index=False)
df

,name,year,wins,losses,ot-losses,pct text-success,gf,ga,diff text-success
0,Los Angeles Kings,1992,39,35,,0.464,338,340,-2
1,Minnesota North Stars,1992,36,38,,0.429,272,293,-2
2,Montreal Canadiens,1992,48,30,,0.571,326,280,-2
3,New Jersey Devils,1992,40,37,,0.476,308,299,-2
4,New York Islanders,1992,40,37,,0.476,335,297,-2
5,New York Rangers,1992,34,39,,0.405,304,308,-2
6,Ottawa Senators,1992,10,70,,0.119,202,395,-2
7,Philadelphia Flyers,1992,36,37,,0.429,319,319,-2
8,Pittsburgh Penguins,1992,56,21,,0.667,367,268,-2
9,Quebec Nordiques,1992,47,27,,0.56,351,300,-2
10,San Jose Sharks,1992,11,71,,0.131,218,414,-2
11,St. Louis Blues,1992,37,36,,0.44,282,278,-2
12,Tampa Bay Lightning,1992,23,54,,0.274,245,332,-2
13,Toronto Maple Leafs,1992,44,29,,0.524,288,241,-2
14,Vancouver Canucks,1992,46,29,,0.548,346,278,-2
15,Washington Capitals,1992,43,34,,0.512,325,286,-2
16,Winnipeg Jets,1992,40,37,,0.476,322,320,-2
17,Mighty Ducks of Anaheim,1993,33,46,,0.393,229,251,-2
18,Boston Bruins,1993,42,29,,0.5,289,252,-2
19,Buffalo Sabres,1993,43,32,,0.512,282,218,-2
20,Calgary Flames,1993,42,29,,0.5,302,256,-2
21,Chicago Blackhawks,1993,39,36,,0.464,254,240,-2
22,Dallas Stars,1993,42,29,,0.5,286,265,-2
23,Detroit Red Wings,1993,46,30,,0.548,356,275,-2
24,Edmonton Oilers,1993,25,45,,0.298,261,305,-2

# 3.3 Extract Table of fist five pages & save into single csv file.

In [1]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://www.scrapethissite.com/pages/forms/?page_num=3')
response.status_code
soup = BeautifulSoup(response.text, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="hockey">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Hockey Teams: Forms, Searching and Pagination
        <small>
         25 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         8 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">
         http://www.opensourcesports.com/hockey/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row search-area">
      <div class="col-md-12 text-center">
       <form action="/pages/forms/" class="form form-inline" method="GET">
        <label for="q">
         Search for Teams:
        </label>
        <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
        <input class="btn btn-primary" type="submit" value="Search"/>
       </form>
       <hr/>
      </div>
     </div>
     <!--.row.search-area-->
     <table class="table">
      <tr>
       <th>
        Team Name
       </th>
       <th>
        Year
       </th>
       <th>
        Wins
       </th>
       <th>
        Losses
       </th>
       <th>
        OT Losses
       </th>
       <th>
        Win %
       </th>
       <th>
        Goals For (GF)
       </th>
       <th>
        Goals Against (GA)
       </th>
       <th>
        + / -
       </th>
      </tr>
      <tr class="team">
       <td class="name">
        Los Angeles Kings
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        35
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.464
       </td>
       <td class="gf">
        338
       </td>
       <td class="ga">
        340
       </td>
       <td class="diff text-danger">
        -2
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Minnesota North Stars
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        38
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.429
       </td>
       <td class="gf">
        272
       </td>
       <td class="ga">
        293
       </td>
       <td class="diff text-danger">
        -21
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Montreal Canadiens
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        48
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.571
       </td>
       <td class="gf">
        326
       </td>
       <td class="ga">
        280
       </td>
       <td class="diff text-success">
        46
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New Jersey Devils
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        40
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.476
       </td>
       <td class="gf">
        308
       </td>
       <td class="ga">
        299
       </td>
       <td class="diff text-success">
        9
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Islanders
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        40
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.476
       </td>
       <td class="gf">
        335
       </td>
       <td class="ga">
        297
       </td>
       <td class="diff text-success">
        38
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Rangers
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        34
       </td>
       <td class="losses">
        39
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.405
       </td>
       <td class="gf">
        304
       </td>
       <td class="ga">
        308
       </td>
       <td class="diff text-danger">
        -4
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Ottawa Senators
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        10
       </td>
       <td class="losses">
        70
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.119
       </td>
       <td class="gf">
        202
       </td>
       <td class="ga">
        395
       </td>
       <td class="diff text-danger">
        -193
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Philadelphia Flyers
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.429
       </td>
       <td class="gf">
        319
       </td>
       <td class="ga">
        319
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Pittsburgh Penguins
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        56
       </td>
       <td class="losses">
        21
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.667
       </td>
       <td class="gf">
        367
       </td>
       <td class="ga">
        268
       </td>
       <td class="diff text-success">
        99
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Quebec Nordiques
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        27
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.56
       </td>
       <td class="gf">
        351
       </td>
       <td class="ga">
        300
       </td>
       <td class="diff text-success">
        51
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        San Jose Sharks
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        11
       </td>
       <td class="losses">
        71
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.131
       </td>
       <td class="gf">
        218
       </td>
       <td class="ga">
        414
       </td>
       <td class="diff text-danger">
        -196
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        St. Louis Blues
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        37
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.44
       </td>
       <td class="gf">
        282
       </td>
       <td class="ga">
        278
       </td>
       <td class="diff text-success">
        4
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Tampa Bay Lightning
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        23
       </td>
       <td class="losses">
        54
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.274
       </td>
       <td class="gf">
        245
       </td>
       <td class="ga">
        332
       </td>
       <td class="diff text-danger">
        -87
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Toronto Maple Leafs
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        44
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.524
       </td>
       <td class="gf">
        288
       </td>
       <td class="ga">
        241
       </td>
       <td class="diff text-success">
        47
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Vancouver Canucks
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.548
       </td>
       <td class="gf">
        346
       </td>
       <td class="ga">
        278
       </td>
       <td class="diff text-success">
        68
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Washington Capitals
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        43
       </td>
       <td class="losses">
        34
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        325
       </td>
       <td class="ga">
        286
       </td>
       <td class="diff text-success">
        39
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Winnipeg Jets
       </td>
       <td class="year">
        1992
       </td>
       <td class="wins">
        40
       </td>
       <td class="losses">
        37
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.476
       </td>
       <td class="gf">
        322
       </td>
       <td class="ga">
        320
       </td>
       <td class="diff text-success">
        2
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Mighty Ducks of Anaheim
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        46
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.393
       </td>
       <td class="gf">
        229
       </td>
       <td class="ga">
        251
       </td>
       <td class="diff text-danger">
        -22
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        42
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.5
       </td>
       <td class="gf">
        289
       </td>
       <td class="ga">
        252
       </td>
       <td class="diff text-success">
        37
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        43
       </td>
       <td class="losses">
        32
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        282
       </td>
       <td class="ga">
        218
       </td>
       <td class="diff text-success">
        64
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        42
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.5
       </td>
       <td class="gf">
        302
       </td>
       <td class="ga">
        256
       </td>
       <td class="diff text-success">
        46
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.464
       </td>
       <td class="gf">
        254
       </td>
       <td class="ga">
        240
       </td>
       <td class="diff text-success">
        14
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Dallas Stars
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        42
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.5
       </td>
       <td class="gf">
        286
       </td>
       <td class="ga">
        265
       </td>
       <td class="diff text-success">
        21
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        46
       </td>
       <td class="losses">
        30
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.548
       </td>
       <td class="gf">
        356
       </td>
       <td class="ga">
        275
       </td>
       <td class="diff text-success">
        81
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Edmonton Oilers
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        25
       </td>
       <td class="losses">
        45
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.298
       </td>
       <td class="gf">
        261
       </td>
       <td class="ga">
        305
       </td>
       <td class="diff text-danger">
        -44
       </td>
      </tr>
     </table>
     <div class="row pagination-area">
      <div class="col-md-10 text-center">
       <ul class="pagination">
        <li>
         <a aria-label="Previous" href="/pages/forms/?page_num=2">
          <span aria-hidden="true">
           «
          </span>
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=1">
          1
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=2">
          2
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=3">
          <strong>
           3
          </strong>
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=4">
          4
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=5">
          5
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=6">
          6
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=7">
          7
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=8">
          8
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=9">
          9
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=10">
          10
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=11">
          11
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=12">
          12
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=13">
          13
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=14">
          14
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=15">
          15
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=16">
          16
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=17">
          17
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=18">

In [2]:
var1= soup.find_all('table',class_='table')
var1

[<table class="table">
 <tr>
 <th>
                             Team Name
                         </th>
 <th>
                             Year
                         </th>
 <th>
                             Wins
                         </th>
 <th>
                             Losses
                         </th>
 <th>
                             OT Losses
                         </th>
 <th>
                             Win %
                         </th>
 <th>
                             Goals For (GF)
                         </th>
 <th>
                             Goals Against (GA)
                         </th>
 <th>
                             + / -
                         </th>
 </tr>
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             35
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.464
                         </td>
 <td class="gf">
                             338
                         </td>
 <td class="ga">
                             340
                         </td>
 <td class="diff text-danger">
                             -2
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Minnesota North Stars
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             38
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.429
                         </td>
 <td class="gf">
                             272
                         </td>
 <td class="ga">
                             293
                         </td>
 <td class="diff text-danger">
                             -21
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             48
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.571
                         </td>
 <td class="gf">
                             326
                         </td>
 <td class="ga">
                             280
                         </td>
 <td class="diff text-success">
                             46
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             40
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.476
                         </td>
 <td class="gf">
                             308
                         </td>
 <td class="ga">
                             299
                         </td>
 <td class="diff text-success">
                             9
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             40
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.476
                         </td>
 <td class="gf">
                             335
                         </td>
 <td class="ga">
                             297
                         </td>
 <td class="diff text-success">
                             38
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             39
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.405
                         </td>
 <td class="gf">
                             304
                         </td>
 <td class="ga">
                             308
                         </td>
 <td class="diff text-danger">
                             -4
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Ottawa Senators
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             10
                         </td>
 <td class="losses">
                             70
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.119
                         </td>
 <td class="gf">
                             202
                         </td>
 <td class="ga">
                             395
                         </td>
 <td class="diff text-danger">
                             -193
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.429
                         </td>
 <td class="gf">
                             319
                         </td>
 <td class="ga">
                             319
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             56
                         </td>
 <td class="losses">
                             21
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.667
                         </td>
 <td class="gf">
                             367
                         </td>
 <td class="ga">
                             268
                         </td>
 <td class="diff text-success">
                             99
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             27
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.56
                         </td>
 <td class="gf">
                             351
                         </td>
 <td class="ga">
                             300
                         </td>
 <td class="diff text-success">
                             51
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             San Jose Sharks
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             11
                         </td>
 <td class="losses">
                             71
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.131
                         </td>
 <td class="gf">
                             218
                         </td>
 <td class="ga">
                             414
                         </td>
 <td class="diff text-danger">
                             -196
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             37
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.44
                         </td>
 <td class="gf">
                             282
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-success">
                             4
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Tampa Bay Lightning
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             23
                         </td>
 <td class="losses">
                             54
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.274
                         </td>
 <td class="gf">
                             245
                         </td>
 <td class="ga">
                             332
                         </td>
 <td class="diff text-danger">
                             -87
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             44
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.524
                         </td>
 <td class="gf">
                             288
                         </td>
 <td class="ga">
                             241
                         </td>
 <td class="diff text-success">
                             47
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.548
                         </td>
 <td class="gf">
                             346
                         </td>
 <td class="ga">
                             278
                         </td>
 <td class="diff text-success">
                             68
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             43
                         </td>
 <td class="losses">
                             34
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             325
                         </td>
 <td class="ga">
                             286
                         </td>
 <td class="diff text-success">
                             39
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1992
                         </td>
 <td class="wins">
                             40
                         </td>
 <td class="losses">
                             37
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.476
                         </td>
 <td class="gf">
                             322
                         </td>
 <td class="ga">
                             320
                         </td>
 <td class="diff text-success">
                             2
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Mighty Ducks of Anaheim
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             46
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.393
                         </td>
 <td class="gf">
                             229
                         </td>
 <td class="ga">
                             251
                         </td>
 <td class="diff text-danger">
                             -22
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             42
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.5
                         </td>
 <td class="gf">
                             289
                         </td>
 <td class="ga">
                             252
                         </td>
 <td class="diff text-success">
                             37
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             43
                         </td>
 <td class="losses">
                             32
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             282
                         </td>
 <td class="ga">
                             218
                         </td>
 <td class="diff text-success">
                             64
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             42
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.5
                         </td>
 <td class="gf">
                             302
                         </td>
 <td class="ga">
                             256
                         </td>
 <td class="diff text-success">
                             46
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.464
                         </td>
 <td class="gf">
                             254
                         </td>
 <td class="ga">
                             240
                         </td>
 <td class="diff text-success">
                             14
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Dallas Stars
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             42
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.5
                         </td>
 <td class="gf">
                             286
                         </td>
 <td class="ga">
                             265
                         </td>
 <td class="diff text-success">
                             21
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             46
                         </td>
 <td class="losses">
                             30
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.548
                         </td>
 <td class="gf">
                             356
                         </td>
 <td class="ga">
                             275
                         </td>
 <td class="diff text-success">
                             81
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Edmonton Oilers
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             25
                         </td>
 <td class="losses">
                             45
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.298
                         </td>
 <td class="gf">
                             261
                         </td>
 <td class="ga">
                             305
                         </td>
 <td class="diff text-danger">
                             -44
                         </td>
 </tr>
 </table>]

In [31]:
dict['name']= tr.find('td',class_='name').text.strip()
dict['year']=tr.find('td',class_='year').text.strip()
dict['wins']=tr.find('td',class_='wins').text.strip()
dict['losses']=tr.find('td',class_='losses').text.strip()
dict['ot-losses']=tr.find('td',class_='ot-losses').text.strip()
# dict['pct text-success']=tr.find('td',class_='pct text-success').text.strip()
dict['pct text-success']=tr.find('td',class_='pct').text.strip()

dict['gf']=tr.find('td',class_='gf').text.strip()
dict['ga']=tr.find('td',class_='ga').text.strip()
dict['diff text-success']=tr.find('td',class_='diff').text.strip()
# dict['diff text-success']=tr.find('td',class_='diff text-success').text.strip()

print(dict)

{'name': 'Los Angeles Kings', 'year': '1992', 'wins': '39', 'losses': '35', 'ot-losses': '', 'pct text-success': '0.464', 'gf': '338', 'ga': '340', 'diff text-success': '-2'}

In [ ]:
list = []
for i in trs[1:]:
        dict={
            'name':'',
            'year':'',
            'wins':'',
            'losses':'',
            'ot-losses':'',
            'pct text-success':'',
            'gf':'',
            'ga':'',
            'diff text-success':''


        }
    # print(dict)
        dict['name']= i.find('td',class_='name').text.strip()
        dict['year']=i.find('td',class_='year').text.strip()
        dict['wins']=i.find('td',class_='wins').text.strip()
        dict['losses']=i.find('td',class_='losses').text.strip()
        dict['ot-losses']=i.find('td',class_='ot-losses').text.strip()
        # dict['pct text-success']=i.find('td',class_='pct text-success').text.strip() # 
        dict['pct text-success']=i.find('td',class_='pct').text.strip()

        dict['gf']=i.find('td',class_='gf').text.strip()
        dict['ga']=i.find('td',class_='ga').text.strip()
        # dict['diff text-success']=i.find('td',class_='diff text-success').text.strip()
        dict['diff text-success']=tr.find('td',class_='diff').text.strip()

        list.append(dict.copy())

In [33]:
import pandas as pd
df = pd.DataFrame(list)
df
df.to_csv('scrapethissite q3_3.csv',index=False)
df

,name,year,wins,losses,ot-losses,pct text-success,gf,ga,diff text-success
0,Los Angeles Kings,1992,39,35,,0.464,338,340,-2
1,Minnesota North Stars,1992,36,38,,0.429,272,293,-2
2,Montreal Canadiens,1992,48,30,,0.571,326,280,-2
3,New Jersey Devils,1992,40,37,,0.476,308,299,-2
4,New York Islanders,1992,40,37,,0.476,335,297,-2
5,New York Rangers,1992,34,39,,0.405,304,308,-2
6,Ottawa Senators,1992,10,70,,0.119,202,395,-2
7,Philadelphia Flyers,1992,36,37,,0.429,319,319,-2
8,Pittsburgh Penguins,1992,56,21,,0.667,367,268,-2
9,Quebec Nordiques,1992,47,27,,0.56,351,300,-2
10,San Jose Sharks,1992,11,71,,0.131,218,414,-2
11,St. Louis Blues,1992,37,36,,0.44,282,278,-2
12,Tampa Bay Lightning,1992,23,54,,0.274,245,332,-2
13,Toronto Maple Leafs,1992,44,29,,0.524,288,241,-2
14,Vancouver Canucks,1992,46,29,,0.548,346,278,-2
15,Washington Capitals,1992,43,34,,0.512,325,286,-2
16,Winnipeg Jets,1992,40,37,,0.476,322,320,-2
17,Mighty Ducks of Anaheim,1993,33,46,,0.393,229,251,-2
18,Boston Bruins,1993,42,29,,0.5,289,252,-2
19,Buffalo Sabres,1993,43,32,,0.512,282,218,-2
20,Calgary Flames,1993,42,29,,0.5,302,256,-2
21,Chicago Blackhawks,1993,39,36,,0.464,254,240,-2
22,Dallas Stars,1993,42,29,,0.5,286,265,-2
23,Detroit Red Wings,1993,46,30,,0.548,356,275,-2
24,Edmonton Oilers,1993,25,45,,0.298,261,305,-2

In [1]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://www.scrapethissite.com/pages/forms/?page_num=4')
response.status_code
soup = BeautifulSoup(response.text, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="hockey">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Hockey Teams: Forms, Searching and Pagination
        <small>
         25 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         8 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://www.opensourcesports.com/hockey/" target="_blank">
         http://www.opensourcesports.com/hockey/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row search-area">
      <div class="col-md-12 text-center">
       <form action="/pages/forms/" class="form form-inline" method="GET">
        <label for="q">
         Search for Teams:
        </label>
        <input class="form-control" id="q" name="q" placeholder="Search for Teams" type="text"/>
        <input class="btn btn-primary" type="submit" value="Search"/>
       </form>
       <hr/>
      </div>
     </div>
     <!--.row.search-area-->
     <table class="table">
      <tr>
       <th>
        Team Name
       </th>
       <th>
        Year
       </th>
       <th>
        Wins
       </th>
       <th>
        Losses
       </th>
       <th>
        OT Losses
       </th>
       <th>
        Win %
       </th>
       <th>
        Goals For (GF)
       </th>
       <th>
        Goals Against (GA)
       </th>
       <th>
        + / -
       </th>
      </tr>
      <tr class="team">
       <td class="name">
        Florida Panthers
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        34
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.393
       </td>
       <td class="gf">
        233
       </td>
       <td class="ga">
        233
       </td>
       <td class="diff text-success">
        0
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Hartford Whalers
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        27
       </td>
       <td class="losses">
        48
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.321
       </td>
       <td class="gf">
        227
       </td>
       <td class="ga">
        288
       </td>
       <td class="diff text-danger">
        -61
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Los Angeles Kings
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        27
       </td>
       <td class="losses">
        45
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.321
       </td>
       <td class="gf">
        294
       </td>
       <td class="ga">
        322
       </td>
       <td class="diff text-danger">
        -28
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Montreal Canadiens
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        41
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.488
       </td>
       <td class="gf">
        283
       </td>
       <td class="ga">
        248
       </td>
       <td class="diff text-success">
        35
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New Jersey Devils
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        47
       </td>
       <td class="losses">
        25
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.56
       </td>
       <td class="gf">
        306
       </td>
       <td class="ga">
        220
       </td>
       <td class="diff text-success">
        86
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Islanders
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        36
       </td>
       <td class="losses">
        36
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.429
       </td>
       <td class="gf">
        282
       </td>
       <td class="ga">
        264
       </td>
       <td class="diff text-success">
        18
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        New York Rangers
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        52
       </td>
       <td class="losses">
        24
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.619
       </td>
       <td class="gf">
        299
       </td>
       <td class="ga">
        231
       </td>
       <td class="diff text-success">
        68
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Ottawa Senators
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        14
       </td>
       <td class="losses">
        61
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.167
       </td>
       <td class="gf">
        201
       </td>
       <td class="ga">
        397
       </td>
       <td class="diff text-danger">
        -196
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Philadelphia Flyers
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        35
       </td>
       <td class="losses">
        39
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.417
       </td>
       <td class="gf">
        294
       </td>
       <td class="ga">
        314
       </td>
       <td class="diff text-danger">
        -20
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Pittsburgh Penguins
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        44
       </td>
       <td class="losses">
        27
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.524
       </td>
       <td class="gf">
        299
       </td>
       <td class="ga">
        285
       </td>
       <td class="diff text-success">
        14
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Quebec Nordiques
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        34
       </td>
       <td class="losses">
        42
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.405
       </td>
       <td class="gf">
        277
       </td>
       <td class="ga">
        292
       </td>
       <td class="diff text-danger">
        -15
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        San Jose Sharks
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        35
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.393
       </td>
       <td class="gf">
        252
       </td>
       <td class="ga">
        265
       </td>
       <td class="diff text-danger">
        -13
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        St. Louis Blues
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        40
       </td>
       <td class="losses">
        33
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.476
       </td>
       <td class="gf">
        270
       </td>
       <td class="ga">
        283
       </td>
       <td class="diff text-danger">
        -13
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Tampa Bay Lightning
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        30
       </td>
       <td class="losses">
        43
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.357
       </td>
       <td class="gf">
        224
       </td>
       <td class="ga">
        251
       </td>
       <td class="diff text-danger">
        -27
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Toronto Maple Leafs
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        43
       </td>
       <td class="losses">
        29
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.512
       </td>
       <td class="gf">
        280
       </td>
       <td class="ga">
        243
       </td>
       <td class="diff text-success">
        37
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Vancouver Canucks
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        41
       </td>
       <td class="losses">
        40
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.488
       </td>
       <td class="gf">
        279
       </td>
       <td class="ga">
        276
       </td>
       <td class="diff text-success">
        3
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Washington Capitals
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        39
       </td>
       <td class="losses">
        35
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.464
       </td>
       <td class="gf">
        277
       </td>
       <td class="ga">
        263
       </td>
       <td class="diff text-success">
        14
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Winnipeg Jets
       </td>
       <td class="year">
        1993
       </td>
       <td class="wins">
        24
       </td>
       <td class="losses">
        51
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.286
       </td>
       <td class="gf">
        245
       </td>
       <td class="ga">
        344
       </td>
       <td class="diff text-danger">
        -99
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Mighty Ducks of Anaheim
       </td>
       <td class="year">
        1994
       </td>
       <td class="wins">
        16
       </td>
       <td class="losses">
        27
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.333
       </td>
       <td class="gf">
        125
       </td>
       <td class="ga">
        164
       </td>
       <td class="diff text-danger">
        -39
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Boston Bruins
       </td>
       <td class="year">
        1994
       </td>
       <td class="wins">
        27
       </td>
       <td class="losses">
        18
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.562
       </td>
       <td class="gf">
        150
       </td>
       <td class="ga">
        127
       </td>
       <td class="diff text-success">
        23
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Buffalo Sabres
       </td>
       <td class="year">
        1994
       </td>
       <td class="wins">
        22
       </td>
       <td class="losses">
        19
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.458
       </td>
       <td class="gf">
        130
       </td>
       <td class="ga">
        119
       </td>
       <td class="diff text-success">
        11
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Calgary Flames
       </td>
       <td class="year">
        1994
       </td>
       <td class="wins">
        24
       </td>
       <td class="losses">
        17
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.5
       </td>
       <td class="gf">
        163
       </td>
       <td class="ga">
        135
       </td>
       <td class="diff text-success">
        28
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Chicago Blackhawks
       </td>
       <td class="year">
        1994
       </td>
       <td class="wins">
        24
       </td>
       <td class="losses">
        19
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.5
       </td>
       <td class="gf">
        156
       </td>
       <td class="ga">
        115
       </td>
       <td class="diff text-success">
        41
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Dallas Stars
       </td>
       <td class="year">
        1994
       </td>
       <td class="wins">
        17
       </td>
       <td class="losses">
        23
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-danger">
        0.354
       </td>
       <td class="gf">
        136
       </td>
       <td class="ga">
        135
       </td>
       <td class="diff text-success">
        1
       </td>
      </tr>
      <tr class="team">
       <td class="name">
        Detroit Red Wings
       </td>
       <td class="year">
        1994
       </td>
       <td class="wins">
        33
       </td>
       <td class="losses">
        11
       </td>
       <td class="ot-losses">
       </td>
       <td class="pct text-success">
        0.688
       </td>
       <td class="gf">
        180
       </td>
       <td class="ga">
        117
       </td>
       <td class="diff text-success">
        63
       </td>
      </tr>
     </table>
     <div class="row pagination-area">
      <div class="col-md-10 text-center">
       <ul class="pagination">
        <li>
         <a aria-label="Previous" href="/pages/forms/?page_num=3">
          <span aria-hidden="true">
           «
          </span>
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=1">
          1
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=2">
          2
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=3">
          3
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=4">
          <strong>
           4
          </strong>
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=5">
          5
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=6">
          6
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=7">
          7
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=8">
          8
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=9">
          9
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=10">
          10
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=11">
          11
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=12">
          12
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=13">
          13
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=14">
          14
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=15">
          15
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=16">
          16
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=17">
          17
         </a>
        </li>
        <li>
         <a href="/pages/forms/?page_num=18">

In [2]:
trs = soup.find_all('table',class_='table')
trs

[<table class="table">
 <tr>
 <th>
                             Team Name
                         </th>
 <th>
                             Year
                         </th>
 <th>
                             Wins
                         </th>
 <th>
                             Losses
                         </th>
 <th>
                             OT Losses
                         </th>
 <th>
                             Win %
                         </th>
 <th>
                             Goals For (GF)
                         </th>
 <th>
                             Goals Against (GA)
                         </th>
 <th>
                             + / -
                         </th>
 </tr>
 <tr class="team">
 <td class="name">
                             Florida Panthers
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             34
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.393
                         </td>
 <td class="gf">
                             233
                         </td>
 <td class="ga">
                             233
                         </td>
 <td class="diff text-success">
                             0
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Hartford Whalers
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             27
                         </td>
 <td class="losses">
                             48
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.321
                         </td>
 <td class="gf">
                             227
                         </td>
 <td class="ga">
                             288
                         </td>
 <td class="diff text-danger">
                             -61
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Los Angeles Kings
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             27
                         </td>
 <td class="losses">
                             45
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.321
                         </td>
 <td class="gf">
                             294
                         </td>
 <td class="ga">
                             322
                         </td>
 <td class="diff text-danger">
                             -28
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Montreal Canadiens
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.488
                         </td>
 <td class="gf">
                             283
                         </td>
 <td class="ga">
                             248
                         </td>
 <td class="diff text-success">
                             35
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New Jersey Devils
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             47
                         </td>
 <td class="losses">
                             25
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.56
                         </td>
 <td class="gf">
                             306
                         </td>
 <td class="ga">
                             220
                         </td>
 <td class="diff text-success">
                             86
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Islanders
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             36
                         </td>
 <td class="losses">
                             36
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.429
                         </td>
 <td class="gf">
                             282
                         </td>
 <td class="ga">
                             264
                         </td>
 <td class="diff text-success">
                             18
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             New York Rangers
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             52
                         </td>
 <td class="losses">
                             24
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.619
                         </td>
 <td class="gf">
                             299
                         </td>
 <td class="ga">
                             231
                         </td>
 <td class="diff text-success">
                             68
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Ottawa Senators
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             14
                         </td>
 <td class="losses">
                             61
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.167
                         </td>
 <td class="gf">
                             201
                         </td>
 <td class="ga">
                             397
                         </td>
 <td class="diff text-danger">
                             -196
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Philadelphia Flyers
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             35
                         </td>
 <td class="losses">
                             39
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.417
                         </td>
 <td class="gf">
                             294
                         </td>
 <td class="ga">
                             314
                         </td>
 <td class="diff text-danger">
                             -20
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Pittsburgh Penguins
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             44
                         </td>
 <td class="losses">
                             27
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.524
                         </td>
 <td class="gf">
                             299
                         </td>
 <td class="ga">
                             285
                         </td>
 <td class="diff text-success">
                             14
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Quebec Nordiques
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             34
                         </td>
 <td class="losses">
                             42
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.405
                         </td>
 <td class="gf">
                             277
                         </td>
 <td class="ga">
                             292
                         </td>
 <td class="diff text-danger">
                             -15
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             San Jose Sharks
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             35
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.393
                         </td>
 <td class="gf">
                             252
                         </td>
 <td class="ga">
                             265
                         </td>
 <td class="diff text-danger">
                             -13
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             St. Louis Blues
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             40
                         </td>
 <td class="losses">
                             33
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.476
                         </td>
 <td class="gf">
                             270
                         </td>
 <td class="ga">
                             283
                         </td>
 <td class="diff text-danger">
                             -13
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Tampa Bay Lightning
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             30
                         </td>
 <td class="losses">
                             43
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.357
                         </td>
 <td class="gf">
                             224
                         </td>
 <td class="ga">
                             251
                         </td>
 <td class="diff text-danger">
                             -27
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Toronto Maple Leafs
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             43
                         </td>
 <td class="losses">
                             29
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.512
                         </td>
 <td class="gf">
                             280
                         </td>
 <td class="ga">
                             243
                         </td>
 <td class="diff text-success">
                             37
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Vancouver Canucks
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             41
                         </td>
 <td class="losses">
                             40
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.488
                         </td>
 <td class="gf">
                             279
                         </td>
 <td class="ga">
                             276
                         </td>
 <td class="diff text-success">
                             3
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Washington Capitals
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             39
                         </td>
 <td class="losses">
                             35
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.464
                         </td>
 <td class="gf">
                             277
                         </td>
 <td class="ga">
                             263
                         </td>
 <td class="diff text-success">
                             14
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Winnipeg Jets
                         </td>
 <td class="year">
                             1993
                         </td>
 <td class="wins">
                             24
                         </td>
 <td class="losses">
                             51
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.286
                         </td>
 <td class="gf">
                             245
                         </td>
 <td class="ga">
                             344
                         </td>
 <td class="diff text-danger">
                             -99
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Mighty Ducks of Anaheim
                         </td>
 <td class="year">
                             1994
                         </td>
 <td class="wins">
                             16
                         </td>
 <td class="losses">
                             27
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.333
                         </td>
 <td class="gf">
                             125
                         </td>
 <td class="ga">
                             164
                         </td>
 <td class="diff text-danger">
                             -39
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Boston Bruins
                         </td>
 <td class="year">
                             1994
                         </td>
 <td class="wins">
                             27
                         </td>
 <td class="losses">
                             18
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.562
                         </td>
 <td class="gf">
                             150
                         </td>
 <td class="ga">
                             127
                         </td>
 <td class="diff text-success">
                             23
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Buffalo Sabres
                         </td>
 <td class="year">
                             1994
                         </td>
 <td class="wins">
                             22
                         </td>
 <td class="losses">
                             19
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.458
                         </td>
 <td class="gf">
                             130
                         </td>
 <td class="ga">
                             119
                         </td>
 <td class="diff text-success">
                             11
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Calgary Flames
                         </td>
 <td class="year">
                             1994
                         </td>
 <td class="wins">
                             24
                         </td>
 <td class="losses">
                             17
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.5
                         </td>
 <td class="gf">
                             163
                         </td>
 <td class="ga">
                             135
                         </td>
 <td class="diff text-success">
                             28
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Chicago Blackhawks
                         </td>
 <td class="year">
                             1994
                         </td>
 <td class="wins">
                             24
                         </td>
 <td class="losses">
                             19
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.5
                         </td>
 <td class="gf">
                             156
                         </td>
 <td class="ga">
                             115
                         </td>
 <td class="diff text-success">
                             41
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Dallas Stars
                         </td>
 <td class="year">
                             1994
                         </td>
 <td class="wins">
                             17
                         </td>
 <td class="losses">
                             23
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-danger">
                             0.354
                         </td>
 <td class="gf">
                             136
                         </td>
 <td class="ga">
                             135
                         </td>
 <td class="diff text-success">
                             1
                         </td>
 </tr>
 <tr class="team">
 <td class="name">
                             Detroit Red Wings
                         </td>
 <td class="year">
                             1994
                         </td>
 <td class="wins">
                             33
                         </td>
 <td class="losses">
                             11
                         </td>
 <td class="ot-losses">
 </td>
 <td class="pct text-success">
                             0.688
                         </td>
 <td class="gf">
                             180
                         </td>
 <td class="ga">
                             117
                         </td>
 <td class="diff text-success">
                             63
                         </td>
 </tr>
 </table>]

In [3]:
dict['name']= tr.find('td',class_='name').text.strip()
dict['year']=tr.find('td',class_='year').text.strip()
dict['wins']=tr.find('td',class_='wins').text.strip()
dict['losses']=tr.find('td',class_='losses').text.strip()
dict['ot-losses']=tr.find('td',class_='ot-losses').text.strip()
# dict['pct text-success']=tr.find('td',class_='pct text-success').text.strip()
dict['pct text-success']=tr.find('td',class_='pct').text.strip()

dict['gf']=tr.find('td',class_='gf').text.strip()
dict['ga']=tr.find('td',class_='ga').text.strip()
dict['diff text-success']=tr.find('td',class_='diff').text.strip()
# dict['diff text-success']=tr.find('td',class_='diff text-success').text.strip()

print(dict)

NameError: name 'tr' is not defined