## 3.1 Extract Table of first page & save into csv file.

In [20]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.scrapethissite.com/pages/forms/"
r = requests.get(url); r.raise_for_status()
soup = BeautifulSoup(r.text, "html.parser")

table = soup.find("table")


headers = [th.get_text(strip=True) for th in table.find_all("th")]
rows = []
for tr in table.find_all("tr")[1:]:
    cols = [td.get_text(strip=True) for td in tr.find_all("td")]
    if cols:
        rows.append(cols)

df = pd.DataFrame(rows, columns=headers)
df.to_csv("scrapthisside q3__1.csv", index=False, encoding="utf-8")
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,,0.463,272,272,0
6,Hartford Whalers,1990,31,38,,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,,0.487,273,249,24
10,New Jersey Devils,1990,32,33,,0.4,272,264,8
11,New York Islanders,1990,25,45,,0.312,223,290,-67
12,New York Rangers,1990,36,31,,0.45,297,265,32
13,Philadelphia Flyers,1990,33,37,,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,,0.2,236,354,-118
16,St. Louis Blues,1990,47,22,,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,,0.35,243,315,-72
19,Washington Capitals,1990,37,36,,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
21,Boston Bruins,1991,36,32,,0.45,270,275,-5
22,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
23,Calgary Flames,1991,31,37,,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,,0.45,257,236,21

## 3.2 Extract Table of second page & save into another csv file.

In [21]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.scrapethissite.com/pages/forms/?page_num=2"
r = requests.get(url); r.raise_for_status()
soup = BeautifulSoup(r.text, "html.parser")

table = soup.find("table")


headers = [th.get_text(strip=True) for th in table.find_all("th")]
rows = []
for tr in table.find_all("tr")[1:]:
    cols = [td.get_text(strip=True) for td in tr.find_all("td")]
    if cols:
        rows.append(cols)

df = pd.DataFrame(rows, columns=headers)
df.to_csv("scrapthisside q3_2.csv",index=False, encoding="utf-8")
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Detroit Red Wings,1991,43,25,,0.537,320,256,64
1,Edmonton Oilers,1991,36,34,,0.45,295,297,-2
2,Hartford Whalers,1991,26,41,,0.325,247,283,-36
3,Los Angeles Kings,1991,35,31,,0.438,287,296,-9
4,Minnesota North Stars,1991,32,42,,0.4,246,278,-32
5,Montreal Canadiens,1991,41,28,,0.512,267,207,60
6,New Jersey Devils,1991,38,31,,0.475,289,259,30
7,New York Islanders,1991,34,35,,0.425,291,299,-8
8,New York Rangers,1991,50,25,,0.625,321,246,75
9,Philadelphia Flyers,1991,32,37,,0.4,252,273,-21
10,Pittsburgh Penguins,1991,39,32,,0.487,343,308,35
11,Quebec Nordiques,1991,20,48,,0.25,255,318,-63
12,San Jose Sharks,1991,17,58,,0.212,219,359,-140
13,St. Louis Blues,1991,36,33,,0.45,279,266,13
14,Toronto Maple Leafs,1991,30,43,,0.375,234,294,-60
15,Vancouver Canucks,1991,42,26,,0.525,285,250,35
16,Washington Capitals,1991,45,27,,0.562,330,275,55
17,Winnipeg Jets,1991,33,32,,0.412,251,244,7
18,Boston Bruins,1992,51,26,,0.607,332,268,64
19,Buffalo Sabres,1992,38,36,,0.452,335,297,38
20,Calgary Flames,1992,43,30,,0.512,322,282,40
21,Chicago Blackhawks,1992,47,25,,0.56,279,230,49
22,Detroit Red Wings,1992,47,28,,0.56,369,280,89
23,Edmonton Oilers,1992,26,50,,0.31,242,337,-95
24,Hartford Whalers,1992,26,52,,0.31,284,369,-85

In [16]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.scrapethissite.com/pages/forms/?page_num=2"
r = requests.get(url); r.raise_for_status()
soup = BeautifulSoup(r.text, "html.parser")

table = soup.find("table")


headers = [th.get_text(strip=True) for th in table.find_all("th")]
rows = []
for tr in table.find_all("tr")[1:]:
    cols = [td.get_text(strip=True) for td in tr.find_all("td")]
    if cols:
        rows.append(cols)

df = pd.DataFrame(rows, columns=headers)
df.to_csv("scrapthisside q3_1.csv",mode='a+',index=False, encoding="utf-8")
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Detroit Red Wings,1991,43,25,,0.537,320,256,64
1,Edmonton Oilers,1991,36,34,,0.45,295,297,-2
2,Hartford Whalers,1991,26,41,,0.325,247,283,-36
3,Los Angeles Kings,1991,35,31,,0.438,287,296,-9
4,Minnesota North Stars,1991,32,42,,0.4,246,278,-32
5,Montreal Canadiens,1991,41,28,,0.512,267,207,60
6,New Jersey Devils,1991,38,31,,0.475,289,259,30
7,New York Islanders,1991,34,35,,0.425,291,299,-8
8,New York Rangers,1991,50,25,,0.625,321,246,75
9,Philadelphia Flyers,1991,32,37,,0.4,252,273,-21
10,Pittsburgh Penguins,1991,39,32,,0.487,343,308,35
11,Quebec Nordiques,1991,20,48,,0.25,255,318,-63
12,San Jose Sharks,1991,17,58,,0.212,219,359,-140
13,St. Louis Blues,1991,36,33,,0.45,279,266,13
14,Toronto Maple Leafs,1991,30,43,,0.375,234,294,-60
15,Vancouver Canucks,1991,42,26,,0.525,285,250,35
16,Washington Capitals,1991,45,27,,0.562,330,275,55
17,Winnipeg Jets,1991,33,32,,0.412,251,244,7
18,Boston Bruins,1992,51,26,,0.607,332,268,64
19,Buffalo Sabres,1992,38,36,,0.452,335,297,38
20,Calgary Flames,1992,43,30,,0.512,322,282,40
21,Chicago Blackhawks,1992,47,25,,0.56,279,230,49
22,Detroit Red Wings,1992,47,28,,0.56,369,280,89
23,Edmonton Oilers,1992,26,50,,0.31,242,337,-95
24,Hartford Whalers,1992,26,52,,0.31,284,369,-85

In [17]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.scrapethissite.com/pages/forms/?page_num=3"
r = requests.get(url); r.raise_for_status()
soup = BeautifulSoup(r.text, "html.parser")

table = soup.find("table")


headers = [th.get_text(strip=True) for th in table.find_all("th")]
rows = []
for tr in table.find_all("tr")[1:]:
    cols = [td.get_text(strip=True) for td in tr.find_all("td")]
    if cols:
        rows.append(cols)

df = pd.DataFrame(rows, columns=headers)
df.to_csv("scrapthisside q3_1.csv",mode='a+', index=False, encoding="utf-8")
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Los Angeles Kings,1992,39,35,,0.464,338,340,-2
1,Minnesota North Stars,1992,36,38,,0.429,272,293,-21
2,Montreal Canadiens,1992,48,30,,0.571,326,280,46
3,New Jersey Devils,1992,40,37,,0.476,308,299,9
4,New York Islanders,1992,40,37,,0.476,335,297,38
5,New York Rangers,1992,34,39,,0.405,304,308,-4
6,Ottawa Senators,1992,10,70,,0.119,202,395,-193
7,Philadelphia Flyers,1992,36,37,,0.429,319,319,0
8,Pittsburgh Penguins,1992,56,21,,0.667,367,268,99
9,Quebec Nordiques,1992,47,27,,0.56,351,300,51
10,San Jose Sharks,1992,11,71,,0.131,218,414,-196
11,St. Louis Blues,1992,37,36,,0.44,282,278,4
12,Tampa Bay Lightning,1992,23,54,,0.274,245,332,-87
13,Toronto Maple Leafs,1992,44,29,,0.524,288,241,47
14,Vancouver Canucks,1992,46,29,,0.548,346,278,68
15,Washington Capitals,1992,43,34,,0.512,325,286,39
16,Winnipeg Jets,1992,40,37,,0.476,322,320,2
17,Mighty Ducks of Anaheim,1993,33,46,,0.393,229,251,-22
18,Boston Bruins,1993,42,29,,0.5,289,252,37
19,Buffalo Sabres,1993,43,32,,0.512,282,218,64
20,Calgary Flames,1993,42,29,,0.5,302,256,46
21,Chicago Blackhawks,1993,39,36,,0.464,254,240,14
22,Dallas Stars,1993,42,29,,0.5,286,265,21
23,Detroit Red Wings,1993,46,30,,0.548,356,275,81
24,Edmonton Oilers,1993,25,45,,0.298,261,305,-44

## 3.3 Extract Table of fist five pages & save into single csv file.

In [18]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.scrapethissite.com/pages/forms/?page_num=4"
r = requests.get(url); r.raise_for_status()
soup = BeautifulSoup(r.text, "html.parser")

table = soup.find("table")


headers = [th.get_text(strip=True) for th in table.find_all("th")]
rows = []
for tr in table.find_all("tr")[1:]:
    cols = [td.get_text(strip=True) for td in tr.find_all("td")]
    if cols:
        rows.append(cols)

df = pd.DataFrame(rows, columns=headers)
df.to_csv("scrapthisside q3_1.csv",mode='a+', index=False, encoding="utf-8")
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Florida Panthers,1993,33,34,,0.393,233,233,0
1,Hartford Whalers,1993,27,48,,0.321,227,288,-61
2,Los Angeles Kings,1993,27,45,,0.321,294,322,-28
3,Montreal Canadiens,1993,41,29,,0.488,283,248,35
4,New Jersey Devils,1993,47,25,,0.56,306,220,86
5,New York Islanders,1993,36,36,,0.429,282,264,18
6,New York Rangers,1993,52,24,,0.619,299,231,68
7,Ottawa Senators,1993,14,61,,0.167,201,397,-196
8,Philadelphia Flyers,1993,35,39,,0.417,294,314,-20
9,Pittsburgh Penguins,1993,44,27,,0.524,299,285,14
10,Quebec Nordiques,1993,34,42,,0.405,277,292,-15
11,San Jose Sharks,1993,33,35,,0.393,252,265,-13
12,St. Louis Blues,1993,40,33,,0.476,270,283,-13
13,Tampa Bay Lightning,1993,30,43,,0.357,224,251,-27
14,Toronto Maple Leafs,1993,43,29,,0.512,280,243,37
15,Vancouver Canucks,1993,41,40,,0.488,279,276,3
16,Washington Capitals,1993,39,35,,0.464,277,263,14
17,Winnipeg Jets,1993,24,51,,0.286,245,344,-99
18,Mighty Ducks of Anaheim,1994,16,27,,0.333,125,164,-39
19,Boston Bruins,1994,27,18,,0.562,150,127,23
20,Buffalo Sabres,1994,22,19,,0.458,130,119,11
21,Calgary Flames,1994,24,17,,0.5,163,135,28
22,Chicago Blackhawks,1994,24,19,,0.5,156,115,41
23,Dallas Stars,1994,17,23,,0.354,136,135,1
24,Detroit Red Wings,1994,33,11,,0.688,180,117,63

In [19]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.scrapethissite.com/pages/forms/?page_num=5"
r = requests.get(url); r.raise_for_status()
soup = BeautifulSoup(r.text, "html.parser")

table = soup.find("table")


headers = [th.get_text(strip=True) for th in table.find_all("th")]
rows = []
for tr in table.find_all("tr")[1:]:
    cols = [td.get_text(strip=True) for td in tr.find_all("td")]
    if cols:
        rows.append(cols)

df = pd.DataFrame(rows, columns=headers)
df.to_csv("scrapthisside q3_1.csv",mode='a+', index=False, encoding="utf-8")
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Edmonton Oilers,1994,17,27,,0.354,136,183,-47
1,Florida Panthers,1994,20,22,,0.417,115,127,-12
2,Hartford Whalers,1994,19,24,,0.396,127,141,-14
3,Los Angeles Kings,1994,16,23,,0.333,142,174,-32
4,Montreal Canadiens,1994,18,23,,0.375,125,148,-23
5,New Jersey Devils,1994,22,18,,0.458,136,121,15
6,New York Islanders,1994,15,28,,0.312,126,158,-32
7,New York Rangers,1994,22,23,,0.458,139,134,5
8,Ottawa Senators,1994,9,34,,0.188,117,174,-57
9,Philadelphia Flyers,1994,28,16,,0.583,150,132,18
10,Pittsburgh Penguins,1994,29,16,,0.604,181,158,23
11,Quebec Nordiques,1994,30,13,,0.625,185,134,51
12,San Jose Sharks,1994,19,25,,0.396,129,161,-32
13,St. Louis Blues,1994,28,15,,0.583,178,135,43
14,Tampa Bay Lightning,1994,17,28,,0.354,120,144,-24
15,Toronto Maple Leafs,1994,21,19,,0.438,135,146,-11
16,Vancouver Canucks,1994,18,18,,0.375,153,148,5
17,Washington Capitals,1994,22,18,,0.458,136,120,16
18,Winnipeg Jets,1994,16,25,,0.333,157,177,-20
19,Mighty Ducks of Anaheim,1995,35,39,,0.427,234,247,-13
20,Boston Bruins,1995,40,31,,0.488,282,269,13
21,Buffalo Sabres,1995,33,42,,0.402,247,262,-15
22,Calgary Flames,1995,34,37,,0.415,241,240,1
23,Chicago Blackhawks,1995,40,28,,0.488,273,220,53
24,Colorado Avalanche,1995,47,25,,0.573,326,240,86

## 3.4 Extract Table of first page of 100 records/rows & save into another csv file.

In [22]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.scrapethissite.com/pages/forms/?per_page=100"
r = requests.get(url); r.raise_for_status()
soup = BeautifulSoup(r.text, "html.parser")

table = soup.find("table")


headers = [th.get_text(strip=True) for th in table.find_all("th")]
rows = []
for tr in table.find_all("tr")[1:]:
    cols = [td.get_text(strip=True) for td in tr.find_all("td")]
    if cols:
        rows.append(cols)

df = pd.DataFrame(rows, columns=headers)
df.to_csv("scrapthisside q3_4.csv", index=False, encoding="utf-8")
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
...,...,...,...,...,...,...,...,...,...
95,Buffalo Sabres,1994,22,19,,0.458,130,119,11
96,Calgary Flames,1994,24,17,,0.5,163,135,28
97,Chicago Blackhawks,1994,24,19,,0.5,156,115,41
98,Dallas Stars,1994,17,23,,0.354,136,135,1
99,Detroit Red Wings,1994,33,11,,0.688,180,117,63

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd 
c_url = 'https://www.scrapethissite.com/pages/forms/?per_page='

In [ ]:
data = []
for i in range(1,6):
    url= c_url + str(i)
    r= requests.get(url)

## 5.1 Extract first country details of a page & save into csv file. e.g# Andorra
## https://www.scrapethissite.com/pages/simple/

In [1]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://www.scrapethissite.com/pages/simple/')
response.status_code
soup =  BeautifulSoup(response.text,'html')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
  <link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="countries">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Countries of the World: A Simple Example
        <small>
         250 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         4 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">
         http://peric.github.io/GetCountries/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ad">
        </i>
        Andorra
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Andorra la Vella
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         84000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         468.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ae">
        </i>
        United Arab Emirates
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Abu Dhabi
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         4975593
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         82880.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-af">
        </i>
        Afghanistan
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Kabul
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         29121286
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         647500.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ag">
        </i>
        Antigua and Barbuda
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         St. John's
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         86754
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         443.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ai">
        </i>
        Anguilla
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         The Valley
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         13254
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         102.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-al">
        </i>
        Albania
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Tirana
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         2986952
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         28748.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-am">
        </i>
        Armenia
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Yerevan
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         2968000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         29800.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ao">
        </i>
        Angola
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Luanda
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         13068161
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         1246700.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-aq">
        </i>
        Antarctica
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         None
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         0
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         1.4E7
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ar">
        </i>
        Argentina
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Buenos Aires
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         41343201
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         2766890.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-as">
        </i>
        American Samoa
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Pago Pago
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         57881
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         199.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-at">
        </i>
        Austria
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Vienna
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         8205000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         83858.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-au">
        </i>
        Australia
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Canberra
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         21515754
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         7686850.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-aw">
        </i>
        Aruba
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Oranjestad
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         71566
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         193.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ax">
        </i>
        Åland
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Mariehamn
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         26711
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         1580.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-az">
        </i>
        Azerbaijan
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Baku
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         8303512
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         86600.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ba">
        </i>
        Bosnia and Herzegovina
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Sarajevo
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         4590000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         51129.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-bb">
        </i>
        Barbados
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Bridgetown
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         285653
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         431.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-bd">
        </i>
        Bangladesh
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Dhaka
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         156118464
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         144000.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-be">
        </i>
        Belgium
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Brussels
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         10403000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         30510.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-bf">
        </i>
        Burkina Faso
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Ouagadougou
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         16241811
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         274200.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-bg">
        </i>
        Bulgaria
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Sofia
        </span>
        <br/>
        <strong>
         Population:

In [2]:
var = soup.find('div',class_='col-md-4 country')
var

<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div>

In [3]:
list = []
dictionary={
        'country name':'',
        'capital':'',
        'Population':'',
        'area':'',

    }

In [4]:
dictionary['country name']=var.find('h3').text.strip()
dictionary['capital']=var.find('span',class_='country-capital').text
dictionary['Population']=var.find('span',class_='country-population').text
dictionary['area']=var.find('span',class_='country-area').text
print(dictionary)
list.append(dictionary)

{'country name': 'Andorra', 'capital': 'Andorra la Vella', 'Population': '84000', 'area': '468.0'}

In [6]:
import pandas as pd 
df = pd.DataFrame(list)
df

  country name           capital Population   area
0      Andorra  Andorra la Vella      84000  468.0

In [7]:
df.to_csv('scrapthisside q5_1.csv',index=False)

## 5.2 Extract country details of a first row of a page & save into csv file. e.g# Andorra, United Arab Emirates, Afghanistan

In [10]:
var = soup.find_all('div',class_='col-md-4 country')
var

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">

In [11]:
list = []
for vars in var[0:3]:
    dictionary={
        'country name':'',
        'capital':'',
        'Population':'',
        'area':'',

    }
    # print(dictionary)
    dictionary['country name']=vars.find('h3').text.strip()
    dictionary['capital']=vars.find('span',class_='country-capital').text
    dictionary['Population']=vars.find('span',class_='country-population').text
    dictionary['area']=vars.find('span',class_='country-area').text
    list.append(dictionary)

In [12]:
import pandas as pd 
df = pd.DataFrame(list)
df

           country name           capital Population      area
0               Andorra  Andorra la Vella      84000     468.0
1  United Arab Emirates         Abu Dhabi    4975593   82880.0
2           Afghanistan             Kabul   29121286  647500.0

In [13]:
df.to_csv('scrapthisside q5_2.csv',index=False)

## 5.3 Extract all country details of a page & save into csv file.

In [14]:
var = soup.find_all('div',class_='col-md-4 country')
var

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">

In [15]:
list = []
for vars in var[0:250]:
    dictionary={
        'country name':'',
        'capital':'',
        'Population':'',
        'area':'',

    }
    # print(dictionary)
    dictionary['country name']=vars.find('h3').text.strip()
    dictionary['capital']=vars.find('span',class_='country-capital').text
    dictionary['Population']=vars.find('span',class_='country-population').text
    dictionary['area']=vars.find('span',class_='country-area').text
    list.append(dictionary)

In [84]:
list

[{'country name': 'Andorra',
  'capital': 'Andorra la Vella',
  'Population': '84000',
  'area': '468.0'},
 {'country name': 'United Arab Emirates',
  'capital': 'Abu Dhabi',
  'Population': '4975593',
  'area': '82880.0'},
 {'country name': 'Afghanistan',
  'capital': 'Kabul',
  'Population': '29121286',
  'area': '647500.0'},
 {'country name': 'Antigua and Barbuda',
  'capital': "St. John's",
  'Population': '86754',
  'area': '443.0'},
 {'country name': 'Anguilla',
  'capital': 'The Valley',
  'Population': '13254',
  'area': '102.0'},
 {'country name': 'Albania',
  'capital': 'Tirana',
  'Population': '2986952',
  'area': '28748.0'},
 {'country name': 'Armenia',
  'capital': 'Yerevan',
  'Population': '2968000',
  'area': '29800.0'},
 {'country name': 'Angola',
  'capital': 'Luanda',
  'Population': '13068161',
  'area': '1246700.0'},
 {'country name': 'Antarctica',
  'capital': 'None',
  'Population': '0',
  'area': '1.4E7'},
 {'country name': 'Argentina',
  'capital': 'Buenos Aires',
  'Population': '41343201',
  'area': '2766890.0'},
 {'country name': 'American Samoa',
  'capital': 'Pago Pago',
  'Population': '57881',
  'area': '199.0'},
 {'country name': 'Austria',
  'capital': 'Vienna',
  'Population': '8205000',
  'area': '83858.0'},
 {'country name': 'Australia',
  'capital': 'Canberra',
  'Population': '21515754',
  'area': '7686850.0'},
 {'country name': 'Aruba',
  'capital': 'Oranjestad',
  'Population': '71566',
  'area': '193.0'},
 {'country name': 'Åland',
  'capital': 'Mariehamn',
  'Population': '26711',
  'area': '1580.0'},
 {'country name': 'Azerbaijan',
  'capital': 'Baku',
  'Population': '8303512',
  'area': '86600.0'},
 {'country name': 'Bosnia and Herzegovina',
  'capital': 'Sarajevo',
  'Population': '4590000',
  'area': '51129.0'},
 {'country name': 'Barbados',
  'capital': 'Bridgetown',
  'Population': '285653',
  'area': '431.0'},
 {'country name': 'Bangladesh',
  'capital': 'Dhaka',
  'Population': '156118464',
  'area': '144000.0'},
 {'country name': 'Belgium',
  'capital': 'Brussels',
  'Population': '10403000',
  'area': '30510.0'},
 {'country name': 'Burkina Faso',
  'capital': 'Ouagadougou',
  'Population': '16241811',
  'area': '274200.0'},
 {'country name': 'Bulgaria',
  'capital': 'Sofia',
  'Population': '7148785',
  'area': '110910.0'},
 {'country name': 'Bahrain',
  'capital': 'Manama',
  'Population': '738004',
  'area': '665.0'},
 {'country name': 'Burundi',
  'capital': 'Bujumbura',
  'Population': '9863117',
  'area': '27830.0'},
 {'country name': 'Benin',
  'capital': 'Porto-Novo',
  'Population': '9056010',
  'area': '112620.0'},
 {'country name': 'Saint Barthélemy',
  'capital': 'Gustavia',
  'Population': '8450',
  'area': '21.0'},
 {'country name': 'Bermuda',
  'capital': 'Hamilton',
  'Population': '65365',
  'area': '53.0'},
 {'country name': 'Brunei',
  'capital': 'Bandar Seri Begawan',
  'Population': '395027',
  'area': '5770.0'},
 {'country name': 'Bolivia',
  'capital': 'Sucre',
  'Population': '9947418',
  'area': '1098580.0'},
 {'country name': 'Bonaire',
  'capital': 'Kralendijk',
  'Population': '18012',
  'area': '328.0'},
 {'country name': 'Brazil',
  'capital': 'Brasília',
  'Population': '201103330',
  'area': '8511965.0'},
 {'country name': 'Bahamas',
  'capital': 'Nassau',
  'Population': '301790',
  'area': '13940.0'},
 {'country name': 'Bhutan',
  'capital': 'Thimphu',
  'Population': '699847',
  'area': '47000.0'},
 {'country name': 'Bouvet Island',
  'capital': 'None',
  'Population': '0',
  'area': '49.0'},
 {'country name': 'Botswana',
  'capital': 'Gaborone',
  'Population': '2029307',
  'area': '600370.0'},
 {'country name': 'Belarus',
  'capital': 'Minsk',
  'Population': '9685000',
  'area': '207600.0'},
 {'country name': 'Belize',
  'capital': 'Belmopan',
  'Population': '314522',
  'area': '22966.0'},
 {'country name': 'Canada',
  'capital': 'Ottawa',
  'Population': '33679000',
  'area': '9984670.0'},
 {'country name': 'Cocos [Keeling] Islands',
  'capital': 'West Island',
  'Population': '628',
  'area': '14.0'},
 {'country name': 'Democratic Republic of the Congo',
  'capital': 'Kinshasa',
  'Population': '70916439',
  'area': '2345410.0'},
 {'country name': 'Central African Republic',
  'capital': 'Bangui',
  'Population': '4844927',
  'area': '622984.0'},
 {'country name': 'Republic of the Congo',
  'capital': 'Brazzaville',
  'Population': '3039126',
  'area': '342000.0'},
 {'country name': 'Switzerland',
  'capital': 'Bern',
  'Population': '7581000',
  'area': '41290.0'},
 {'country name': 'Ivory Coast',
  'capital': 'Yamoussoukro',
  'Population': '21058798',
  'area': '322460.0'},
 {'country name': 'Cook Islands',
  'capital': 'Avarua',
  'Population': '21388',
  'area': '240.0'},
 {'country name': 'Chile',
  'capital': 'Santiago',
  'Population': '16746491',
  'area': '756950.0'},
 {'country name': 'Cameroon',
  'capital': 'Yaoundé',
  'Population': '19294149',
  'area': '475440.0'},
 {'country name': 'China',
  'capital': 'Beijing',
  'Population': '1330044000',
  'area': '9596960.0'},
 {'country name': 'Colombia',
  'capital': 'Bogotá',
  'Population': '47790000',
  'area': '1138910.0'},
 {'country name': 'Costa Rica',
  'capital': 'San José',
  'Population': '4516220',
  'area': '51100.0'},
 {'country name': 'Cuba',
  'capital': 'Havana',
  'Population': '11423000',
  'area': '110860.0'},
 {'country name': 'Cape Verde',
  'capital': 'Praia',
  'Population': '508659',
  'area': '4033.0'},
 {'country name': 'Curacao',
  'capital': 'Willemstad',
  'Population': '141766',
  'area': '444.0'},
 {'country name': 'Christmas Island',
  'capital': 'Flying Fish Cove',
  'Population': '1500',
  'area': '135.0'},
 {'country name': 'Cyprus',
  'capital': 'Nicosia',
  'Population': '1102677',
  'area': '9250.0'},
 {'country name': 'Czech Republic',
  'capital': 'Prague',
  'Population': '10476000',
  'area': '78866.0'},
 {'country name': 'Germany',
  'capital': 'Berlin',
  'Population': '81802257',
  'area': '357021.0'},
 {'country name': 'Djibouti',
  'capital': 'Djibouti',
  'Population': '740528',
  'area': '23000.0'},
 {'country name': 'Denmark',
  'capital': 'Copenhagen',
  'Population': '5484000',
  'area': '43094.0'},
 {'country name': 'Dominica',
  'capital': 'Roseau',
  'Population': '72813',
  'area': '754.0'},
 {'country name': 'Dominican Republic',
  'capital': 'Santo Domingo',
  'Population': '9823821',
  'area': '48730.0'},
 {'country name': 'Algeria',
  'capital': 'Algiers',
  'Population': '34586184',
  'area': '2381740.0'},
 {'country name': 'Ecuador',
  'capital': 'Quito',
  'Population': '14790608',
  'area': '283560.0'},
 {'country name': 'Estonia',
  'capital': 'Tallinn',
  'Population': '1291170',
  'area': '45226.0'},
 {'country name': 'Egypt',
  'capital': 'Cairo',
  'Population': '80471869',
  'area': '1001450.0'},
 {'country name': 'Western Sahara',
  'capital': 'Laâyoune / El Aaiún',
  'Population': '273008',
  'area': '266000.0'},
 {'country name': 'Eritrea',
  'capital': 'Asmara',
  'Population': '5792984',
  'area': '121320.0'},
 {'country name': 'Spain',
  'capital': 'Madrid',
  'Population': '46505963',
  'area': '504782.0'},
 {'country name': 'Ethiopia',
  'capital': 'Addis Ababa',
  'Population': '88013491',
  'area': '1127127.0'},
 {'country name': 'Finland',
  'capital': 'Helsinki',
  'Population': '5244000',
  'area': '337030.0'},
 {'country name': 'Fiji',
  'capital': 'Suva',
  'Population': '875983',
  'area': '18270.0'},
 {'country name': 'Falkland Islands',
  'capital': 'Stanley',
  'Population': '2638',
  'area': '12173.0'},
 {'country name': 'Micronesia',
  'capital': 'Palikir',
  'Population': '107708',
  'area': '702.0'},
 {'country name': 'Faroe Islands',
  'capital': 'Tórshavn',
  'Population': '48228',
  'area': '1399.0'},
 {'country name': 'France',
  'capital': 'Paris',
  'Population': '64768389',
  'area': '547030.0'},
 {'country name': 'Gabon',
  'capital': 'Libreville',
  'Population': '1545255',
  'area': '267667.0'},
 {'country name': 'United Kingdom',
  'capital': 'London',
  'Population': '62348447',
  'area': '244820.0'},
 {'country name': 'Grenada',
  'capital': "St. George's",
  'Population': '107818',
  'area': '344.0'},
 {'country name': 'Georgia',
  'capital': 'Tbilisi',
  'Population': '4630000',
  'area': '69700.0'},
 {'country name': 'French Guiana',
  'capital': 'Cayenne',
  'Population': '195506',
  'area': '91000.0'},
 {'country name': 'Guernsey',
  'capital': 'St Peter Port',
  'Population': '65228',
  'area': '78.0'},
 {'country name': 'Ghana',
  'capital': 'Accra',
  'Population': '24339838',
  'area': '239460.0'},
 {'country name': 'Gibraltar',
  'capital': 'Gibraltar',
  'Population': '27884',
  'area': '6.5'},
 {'country name': 'Greenland',
  'capital': 'Nuuk',
  'Population': '56375',
  'area': '2166086.0'},
 {'country name': 'Gambia',
  'capital': 'Bathurst',
  'Population': '1593256',
  'area': '11300.0'},
 {'country name': 'Guinea',
  'capital': 'Conakry',
  'Population': '10324025',
  'area': '245857.0'},
 {'country name': 'Guadeloupe',
  'capital': 'Basse-Terre',
  'Population': '443000',
  'area': '1780.0'},
 {'country name': 'Equatorial Guinea',
  'capital': 'Malabo',
  'Population': '1014999',
  'area': '28051.0'},
 {'country name': 'Greece',
  'capital': 'Athens',
  'Population': '11000000',
  'area': '131940.0'},
 {'country name': 'South Georgia and the South Sandwich Islands',
  'capital': 'Grytviken',
  'Population': '30',
  'area': '3903.0'},
 {'country name': 'Guatemala',
  'capital': 'Guatemala City',
  'Population': '13550440',
  'area': '108890.0'},
 {'country name': 'Guam',
  'capital': 'Hagåtña',
  'Population': '159358',
  'area': '549.0'},
 {'country name': 'Guinea-Bissau',
  'capital': 'Bissau',
  'Population': '1565126',
  'area': '36120.0'},
 {'country name': 'Guyana',
  'capital': 'Georgetown',
  'Population': '748486',
  'area': '214970.0'},
 {'country name': 'Hong Kong',
  'capital': 'Hong Kong',
  'Population': '6898686',
  'area': '1092.0'},
 {'country name': 'Heard Island and McDonald Islands',
  'capital': 'None',
  'Population': '0',
  'area': '412.0'},
 {'country name': 'Honduras',
  'capital': 'Tegucigalpa',
  'Population': '7989415',
  'area': '112090.0'},
 {'country name': 'Croatia',
  'capital': 'Zagreb',
  'Population': '4491000',
  'area': '56542.0'},
 {'country name': 'Haiti',
  'capital': 'Port-au-Prince',
  'Population': '9648924',
  'area': '27750.0'},
 {'country name': 'Hungary',
  'capital': 'Budapest',
  'Population': '9982000',
  'area': '93030.0'},
 {'country name': 'Indonesia',
  'capital': 'Jakarta',
  'Population': '242968342',
  'area': '1919440.0'},
 {'country name': 'Ireland',
  'capital': 'Dublin',
  'Population': '4622917',
  'area': '70280.0'},
 {'country name': 'Israel',
  'capital': 'None',
  'Population': '7353985',
  'area': '20770.0'},
 {'country name': 'Isle of Man',
  'capital': 'Douglas',
  'Population': '75049',
  'area': '572.0'},
 {'country name': 'India',
  'capital': 'New Delhi',
  'Population': '1173108018',
  'area': '3287590.0'},
 {'country name': 'British Indian Ocean Territory',
  'capital': 'None',
  'Population': '4000',
  'area': '60.0'},
 {'country name': 'Iraq',
  'capital': 'Baghdad',
  'Population': '29671605',
  'area': '437072.0'},
 {'country name': 'Iran',
  'capital': 'Tehran',
  'Population': '76923300',
  'area': '1648000.0'},
 {'country name': 'Iceland',
  'capital': 'Reykjavik',
  'Population': '308910',
  'area': '103000.0'},
 {'country name': 'Italy',
  'capital': 'Rome',
  'Population': '60340328',
  'area': '301230.0'},
 {'country name': 'Jersey',
  'capital': 'Saint Helier',
  'Population': '90812',
  'area': '116.0'},
 {'country name': 'Jamaica',
  'capital': 'Kingston',
  'Population': '2847232',
  'area': '10991.0'},
 {'country name': 'Jordan',
  'capital': 'Amman',
  'Population': '6407085',
  'area': '92300.0'},
 {'country name': 'Japan',
  'capital': 'Tokyo',
  'Population': '127288000',
  'area': '377835.0'},
 {'country name': 'Kenya',
  'capital': 'Nairobi',
  'Population': '40046566',
  'area': '582650.0'},
 {'country name': 'Kyrgyzstan',
  'capital': 'Bishkek',
  'Population': '5776500',
  'area': '198500.0'},
 {'country name': 'Cambodia',
  'capital': 'Phnom Penh',
  'Population': '14453680',
  'area': '181040.0'},
 {'country name': 'Kiribati',
  'capital': 'Tarawa',
  'Population': '92533',
  'area': '811.0'},
 {'country name': 'Comoros',
  'capital': 'Moroni',
  'Population': '773407',
  'area': '2170.0'},
 {'country name': 'Saint Kitts and Nevis',
  'capital': 'Basseterre',
  'Population': '51134',
  'area': '261.0'},
 {'country name': 'North Korea',
  'capital': 'Pyongyang',
  'Population': '22912177',
  'area': '120540.0'},
 {'country name': 'South Korea',
  'capital': 'Seoul',
  'Population': '48422644',
  'area': '98480.0'},
 {'country name': 'Kuwait',
  'capital': 'Kuwait City',
  'Population': '2789132',
  'area': '17820.0'},
 {'country name': 'Cayman Islands',
  'capital': 'George Town',
  'Population': '44270',
  'area': '262.0'},
 {'country name': 'Kazakhstan',
  'capital': 'Astana',
  'Population': '15340000',
  'area': '2717300.0'},
 {'country name': 'Laos',
  'capital': 'Vientiane',
  'Population': '6368162',
  'area': '236800.0'},
 {'country name': 'Lebanon',
  'capital': 'Beirut',
  'Population': '4125247',
  'area': '10400.0'},
 {'country name': 'Saint Lucia',
  'capital': 'Castries',
  'Population': '160922',
  'area': '616.0'},
 {'country name': 'Liechtenstein',
  'capital': 'Vaduz',
  'Population': '35000',
  'area': '160.0'},
 {'country name': 'Sri Lanka',
  'capital': 'Colombo',
  'Population': '21513990',
  'area': '65610.0'},
 {'country name': 'Liberia',
  'capital': 'Monrovia',
  'Population': '3685076',
  'area': '111370.0'},
 {'country name': 'Lesotho',
  'capital': 'Maseru',
  'Population': '1919552',
  'area': '30355.0'},
 {'country name': 'Lithuania',
  'capital': 'Vilnius',
  'Population': '2944459',
  'area': '65200.0'},
 {'country name': 'Luxembourg',
  'capital': 'Luxembourg',
  'Population': '497538',
  'area': '2586.0'},
 {'country name': 'Latvia',
  'capital': 'Riga',
  'Population': '2217969',
  'area': '64589.0'},
 {'country name': 'Libya',
  'capital': 'Tripoli',
  'Population': '6461454',
  'area': '1759540.0'},
 {'country name': 'Morocco',
  'capital': 'Rabat',
  'Population': '31627428',
  'area': '446550.0'},
 {'country name': 'Monaco',
  'capital': 'Monaco',
  'Population': '32965',
  'area': '1.95'},
 {'country name': 'Moldova',
  'capital': 'Chişinău',
  'Population': '4324000',
  'area': '33843.0'},
 {'country name': 'Montenegro',
  'capital': 'Podgorica',
  'Population': '666730',
  'area': '14026.0'},
 {'country name': 'Saint Martin',
  'capital': 'Marigot',
  'Population': '35925',
  'area': '53.0'},
 {'country name': 'Madagascar',
  'capital': 'Antananarivo',
  'Population': '21281844',
  'area': '587040.0'},
 {'country name': 'Marshall Islands',
  'capital': 'Majuro',
  'Population': '65859',
  'area': '181.3'},
 {'country name': 'Macedonia',
  'capital': 'Skopje',
  'Population': '2062294',
  'area': '25333.0'},
 {'country name': 'Mali',
  'capital': 'Bamako',
  'Population': '13796354',
  'area': '1240000.0'},
 {'country name': 'Myanmar [Burma]',
  'capital': 'Naypyitaw',
  'Population': '53414374',
  'area': '678500.0'},
 {'country name': 'Mongolia',
  'capital': 'Ulan Bator',
  'Population': '3086918',
  'area': '1565000.0'},
 {'country name': 'Macao',
  'capital': 'Macao',
  'Population': '449198',
  'area': '254.0'},
 {'country name': 'Northern Mariana Islands',
  'capital': 'Saipan',
  'Population': '53883',
  'area': '477.0'},
 {'country name': 'Martinique',
  'capital': 'Fort-de-France',
  'Population': '432900',
  'area': '1100.0'},
 {'country name': 'Mauritania',
  'capital': 'Nouakchott',
  'Population': '3205060',
  'area': '1030700.0'},
 {'country name': 'Montserrat',
  'capital': 'Plymouth',
  'Population': '9341',
  'area': '102.0'},
 {'country name': 'Malta',
  'capital': 'Valletta',
  'Population': '403000',
  'area': '316.0'},
 {'country name': 'Mauritius',
  'capital': 'Port Louis',
  'Population': '1294104',
  'area': '2040.0'},
 {'country name': 'Maldives',
  'capital': 'Malé',
  'Population': '395650',
  'area': '300.0'},
 {'country name': 'Malawi',
  'capital': 'Lilongwe',
  'Population': '15447500',
  'area': '118480.0'},
 {'country name': 'Mexico',
  'capital': 'Mexico City',
  'Population': '112468855',
  'area': '1972550.0'},
 {'country name': 'Malaysia',
  'capital': 'Kuala Lumpur',
  'Population': '28274729',
  'area': '329750.0'},
 {'country name': 'Mozambique',
  'capital': 'Maputo',
  'Population': '22061451',
  'area': '801590.0'},
 {'country name': 'Namibia',
  'capital': 'Windhoek',
  'Population': '2128471',
  'area': '825418.0'},
 {'country name': 'New Caledonia',
  'capital': 'Noumea',
  'Population': '216494',
  'area': '19060.0'},
 {'country name': 'Niger',
  'capital': 'Niamey',
  'Population': '15878271',
  'area': '1267000.0'},
 {'country name': 'Norfolk Island',
  'capital': 'Kingston',
  'Population': '1828',
  'area': '34.6'},
 {'country name': 'Nigeria',
  'capital': 'Abuja',
  'Population': '154000000',
  'area': '923768.0'},
 {'country name': 'Nicaragua',
  'capital': 'Managua',
  'Population': '5995928',
  'area': '129494.0'},
 {'country name': 'Netherlands',
  'capital': 'Amsterdam',
  'Population': '16645000',
  'area': '41526.0'},
 {'country name': 'Norway',
  'capital': 'Oslo',
  'Population': '5009150',
  'area': '324220.0'},
 {'country name': 'Nepal',
  'capital': 'Kathmandu',
  'Population': '28951852',
  'area': '140800.0'},
 {'country name': 'Nauru',
  'capital': 'Yaren',
  'Population': '10065',
  'area': '21.0'},
 {'country name': 'Niue',
  'capital': 'Alofi',
  'Population': '2166',
  'area': '260.0'},
 {'country name': 'New Zealand',
  'capital': 'Wellington',
  'Population': '4252277',
  'area': '268680.0'},
 {'country name': 'Oman',
  'capital': 'Muscat',
  'Population': '2967717',
  'area': '212460.0'},
 {'country name': 'Panama',
  'capital': 'Panama City',
  'Population': '3410676',
  'area': '78200.0'},
 {'country name': 'Peru',
  'capital': 'Lima',
  'Population': '29907003',
  'area': '1285220.0'},
 {'country name': 'French Polynesia',
  'capital': 'Papeete',
  'Population': '270485',
  'area': '4167.0'},
 {'country name': 'Papua New Guinea',
  'capital': 'Port Moresby',
  'Population': '6064515',
  'area': '462840.0'},
 {'country name': 'Philippines',
  'capital': 'Manila',
  'Population': '99900177',
  'area': '300000.0'},
 {'country name': 'Pakistan',
  'capital': 'Islamabad',
  'Population': '184404791',
  'area': '803940.0'},
 {'country name': 'Poland',
  'capital': 'Warsaw',
  'Population': '38500000',
  'area': '312685.0'},
 {'country name': 'Saint Pierre and Miquelon',
  'capital': 'Saint-Pierre',
  'Population': '7012',
  'area': '242.0'},
 {'country name': 'Pitcairn Islands',
  'capital': 'Adamstown',
  'Population': '46',
  'area': '47.0'},
 {'country name': 'Puerto Rico',
  'capital': 'San Juan',
  'Population': '3916632',
  'area': '9104.0'},
 {'country name': 'Palestine',
  'capital': 'None',
  'Population': '3800000',
  'area': '5970.0'},
 {'country name': 'Portugal',
  'capital': 'Lisbon',
  'Population': '10676000',
  'area': '92391.0'},
 {'country name': 'Palau',
  'capital': 'Melekeok',
  'Population': '19907',
  'area': '458.0'},
 {'country name': 'Paraguay',
  'capital': 'Asunción',
  'Population': '6375830',
  'area': '406750.0'},
 {'country name': 'Qatar',
  'capital': 'Doha',
  'Population': '840926',
  'area': '11437.0'},
 {'country name': 'Réunion',
  'capital': 'Saint-Denis',
  'Population': '776948',
  'area': '2517.0'},
 {'country name': 'Romania',
  'capital': 'Bucharest',
  'Population': '21959278',
  'area': '237500.0'},
 {'country name': 'Serbia',
  'capital': 'Belgrade',
  'Population': '7344847',
  'area': '88361.0'},
 {'country name': 'Russia',
  'capital': 'Moscow',
  'Population': '140702000',

In [16]:
import pandas as pd 
df = pd.DataFrame(list)
df

             country name           capital Population       area
0                 Andorra  Andorra la Vella      84000      468.0
1    United Arab Emirates         Abu Dhabi    4975593    82880.0
2             Afghanistan             Kabul   29121286   647500.0
3     Antigua and Barbuda        St. John's      86754      443.0
4                Anguilla        The Valley      13254      102.0
..                    ...               ...        ...        ...
245                 Yemen             Sanaa   23495361   527970.0
246               Mayotte         Mamoudzou     159042      374.0
247          South Africa          Pretoria   49000000  1219912.0
248                Zambia            Lusaka   13460305   752614.0
249              Zimbabwe            Harare   11651858   390580.0

[250 rows x 4 columns]

In [17]:
df.to_csv('scrapthisside1 q5_3.csv',index=False)

## 	5.4 Extract country details of a first column of a page & save into csv file.

In [18]:
var = soup.find_all('div',class_='col-md-4 country')
var

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">

In [20]:
list = []
for vars in var[0:250:3]:
    dictionary={
        'country name':'',
        'capital':'',
        'Population':'',
        'area':'',

    }
    # print(dictionary)
    dictionary['country name']=vars.find('h3').text.strip()
    dictionary['capital']=vars.find('span',class_='country-capital').text
    dictionary['Population']=vars.find('span',class_='country-population').text
    dictionary['area']=vars.find('span',class_='country-area').text
    list.append(dictionary)

In [89]:
list

[{'country name': 'Andorra',
  'capital': 'Andorra la Vella',
  'Population': '84000',
  'area': '468.0'},
 {'country name': 'Antigua and Barbuda',
  'capital': "St. John's",
  'Population': '86754',
  'area': '443.0'},
 {'country name': 'Armenia',
  'capital': 'Yerevan',
  'Population': '2968000',
  'area': '29800.0'},
 {'country name': 'Argentina',
  'capital': 'Buenos Aires',
  'Population': '41343201',
  'area': '2766890.0'},
 {'country name': 'Australia',
  'capital': 'Canberra',
  'Population': '21515754',
  'area': '7686850.0'},
 {'country name': 'Azerbaijan',
  'capital': 'Baku',
  'Population': '8303512',
  'area': '86600.0'},
 {'country name': 'Bangladesh',
  'capital': 'Dhaka',
  'Population': '156118464',
  'area': '144000.0'},
 {'country name': 'Bulgaria',
  'capital': 'Sofia',
  'Population': '7148785',
  'area': '110910.0'},
 {'country name': 'Benin',
  'capital': 'Porto-Novo',
  'Population': '9056010',
  'area': '112620.0'},
 {'country name': 'Brunei',
  'capital': 'Bandar Seri Begawan',
  'Population': '395027',
  'area': '5770.0'},
 {'country name': 'Brazil',
  'capital': 'Brasília',
  'Population': '201103330',
  'area': '8511965.0'},
 {'country name': 'Bouvet Island',
  'capital': 'None',
  'Population': '0',
  'area': '49.0'},
 {'country name': 'Belize',
  'capital': 'Belmopan',
  'Population': '314522',
  'area': '22966.0'},
 {'country name': 'Democratic Republic of the Congo',
  'capital': 'Kinshasa',
  'Population': '70916439',
  'area': '2345410.0'},
 {'country name': 'Switzerland',
  'capital': 'Bern',
  'Population': '7581000',
  'area': '41290.0'},
 {'country name': 'Chile',
  'capital': 'Santiago',
  'Population': '16746491',
  'area': '756950.0'},
 {'country name': 'Colombia',
  'capital': 'Bogotá',
  'Population': '47790000',
  'area': '1138910.0'},
 {'country name': 'Cape Verde',
  'capital': 'Praia',
  'Population': '508659',
  'area': '4033.0'},
 {'country name': 'Cyprus',
  'capital': 'Nicosia',
  'Population': '1102677',
  'area': '9250.0'},
 {'country name': 'Djibouti',
  'capital': 'Djibouti',
  'Population': '740528',
  'area': '23000.0'},
 {'country name': 'Dominican Republic',
  'capital': 'Santo Domingo',
  'Population': '9823821',
  'area': '48730.0'},
 {'country name': 'Estonia',
  'capital': 'Tallinn',
  'Population': '1291170',
  'area': '45226.0'},
 {'country name': 'Eritrea',
  'capital': 'Asmara',
  'Population': '5792984',
  'area': '121320.0'},
 {'country name': 'Finland',
  'capital': 'Helsinki',
  'Population': '5244000',
  'area': '337030.0'},
 {'country name': 'Micronesia',
  'capital': 'Palikir',
  'Population': '107708',
  'area': '702.0'},
 {'country name': 'Gabon',
  'capital': 'Libreville',
  'Population': '1545255',
  'area': '267667.0'},
 {'country name': 'Georgia',
  'capital': 'Tbilisi',
  'Population': '4630000',
  'area': '69700.0'},
 {'country name': 'Ghana',
  'capital': 'Accra',
  'Population': '24339838',
  'area': '239460.0'},
 {'country name': 'Gambia',
  'capital': 'Bathurst',
  'Population': '1593256',
  'area': '11300.0'},
 {'country name': 'Equatorial Guinea',
  'capital': 'Malabo',
  'Population': '1014999',
  'area': '28051.0'},
 {'country name': 'Guatemala',
  'capital': 'Guatemala City',
  'Population': '13550440',
  'area': '108890.0'},
 {'country name': 'Guyana',
  'capital': 'Georgetown',
  'Population': '748486',
  'area': '214970.0'},
 {'country name': 'Honduras',
  'capital': 'Tegucigalpa',
  'Population': '7989415',
  'area': '112090.0'},
 {'country name': 'Hungary',
  'capital': 'Budapest',
  'Population': '9982000',
  'area': '93030.0'},
 {'country name': 'Israel',
  'capital': 'None',
  'Population': '7353985',
  'area': '20770.0'},
 {'country name': 'British Indian Ocean Territory',
  'capital': 'None',
  'Population': '4000',
  'area': '60.0'},
 {'country name': 'Iceland',
  'capital': 'Reykjavik',
  'Population': '308910',
  'area': '103000.0'},
 {'country name': 'Jamaica',
  'capital': 'Kingston',
  'Population': '2847232',
  'area': '10991.0'},
 {'country name': 'Kenya',
  'capital': 'Nairobi',
  'Population': '40046566',
  'area': '582650.0'},
 {'country name': 'Kiribati',
  'capital': 'Tarawa',
  'Population': '92533',
  'area': '811.0'},
 {'country name': 'North Korea',
  'capital': 'Pyongyang',
  'Population': '22912177',
  'area': '120540.0'},
 {'country name': 'Cayman Islands',
  'capital': 'George Town',
  'Population': '44270',
  'area': '262.0'},
 {'country name': 'Lebanon',
  'capital': 'Beirut',
  'Population': '4125247',
  'area': '10400.0'},
 {'country name': 'Sri Lanka',
  'capital': 'Colombo',
  'Population': '21513990',
  'area': '65610.0'},
 {'country name': 'Lithuania',
  'capital': 'Vilnius',
  'Population': '2944459',
  'area': '65200.0'},
 {'country name': 'Libya',
  'capital': 'Tripoli',
  'Population': '6461454',
  'area': '1759540.0'},
 {'country name': 'Moldova',
  'capital': 'Chişinău',
  'Population': '4324000',
  'area': '33843.0'},
 {'country name': 'Madagascar',
  'capital': 'Antananarivo',
  'Population': '21281844',
  'area': '587040.0'},
 {'country name': 'Mali',
  'capital': 'Bamako',
  'Population': '13796354',
  'area': '1240000.0'},
 {'country name': 'Macao',
  'capital': 'Macao',
  'Population': '449198',
  'area': '254.0'},
 {'country name': 'Mauritania',
  'capital': 'Nouakchott',
  'Population': '3205060',
  'area': '1030700.0'},
 {'country name': 'Mauritius',
  'capital': 'Port Louis',
  'Population': '1294104',
  'area': '2040.0'},
 {'country name': 'Mexico',
  'capital': 'Mexico City',
  'Population': '112468855',
  'area': '1972550.0'},
 {'country name': 'Namibia',
  'capital': 'Windhoek',
  'Population': '2128471',
  'area': '825418.0'},
 {'country name': 'Norfolk Island',
  'capital': 'Kingston',
  'Population': '1828',
  'area': '34.6'},
 {'country name': 'Netherlands',
  'capital': 'Amsterdam',
  'Population': '16645000',
  'area': '41526.0'},
 {'country name': 'Nauru',
  'capital': 'Yaren',
  'Population': '10065',
  'area': '21.0'},
 {'country name': 'Oman',
  'capital': 'Muscat',
  'Population': '2967717',
  'area': '212460.0'},
 {'country name': 'French Polynesia',
  'capital': 'Papeete',
  'Population': '270485',
  'area': '4167.0'},
 {'country name': 'Pakistan',
  'capital': 'Islamabad',
  'Population': '184404791',
  'area': '803940.0'},
 {'country name': 'Pitcairn Islands',
  'capital': 'Adamstown',
  'Population': '46',
  'area': '47.0'},
 {'country name': 'Portugal',
  'capital': 'Lisbon',
  'Population': '10676000',
  'area': '92391.0'},
 {'country name': 'Qatar',
  'capital': 'Doha',
  'Population': '840926',
  'area': '11437.0'},
 {'country name': 'Serbia',
  'capital': 'Belgrade',
  'Population': '7344847',
  'area': '88361.0'},
 {'country name': 'Saudi Arabia',
  'capital': 'Riyadh',
  'Population': '25731776',
  'area': '1960582.0'},
 {'country name': 'Sudan',
  'capital': 'Khartoum',
  'Population': '35000000',
  'area': '1861484.0'},
 {'country name': 'Saint Helena',
  'capital': 'Jamestown',
  'Population': '7460',
  'area': '410.0'},
 {'country name': 'Slovakia',
  'capital': 'Bratislava',
  'Population': '5455000',
  'area': '48845.0'},
 {'country name': 'Senegal',
  'capital': 'Dakar',
  'Population': '12323252',
  'area': '196190.0'},
 {'country name': 'South Sudan',
  'capital': 'Juba',
  'Population': '8260490',
  'area': '644329.0'},
 {'country name': 'Sint Maarten',
  'capital': 'Philipsburg',
  'Population': '37429',
  'area': '21.0'},
 {'country name': 'Turks and Caicos Islands',
  'capital': 'Cockburn Town',
  'Population': '20556',
  'area': '430.0'},
 {'country name': 'Togo',
  'capital': 'Lomé',
  'Population': '6587239',
  'area': '56785.0'},
 {'country name': 'Tokelau',
  'capital': 'None',
  'Population': '1466',
  'area': '10.0'},
 {'country name': 'Tunisia',
  'capital': 'Tunis',
  'Population': '10589025',
  'area': '163610.0'},
 {'country name': 'Trinidad and Tobago',
  'capital': 'Port of Spain',
  'Population': '1228691',
  'area': '5128.0'},
 {'country name': 'Tanzania',
  'capital': 'Dodoma',
  'Population': '41892895',
  'area': '945087.0'},
 {'country name': 'U.S. Minor Outlying Islands',
  'capital': 'None',
  'Population': '0',
  'area': '0.0'},
 {'country name': 'Uzbekistan',
  'capital': 'Tashkent',
  'Population': '27865738',
  'area': '447400.0'},
 {'country name': 'Venezuela',
  'capital': 'Caracas',
  'Population': '27223228',
  'area': '912050.0'},
 {'country name': 'Vietnam',
  'capital': 'Hanoi',
  'Population': '89571130',
  'area': '329560.0'},
 {'country name': 'Samoa',
  'capital': 'Apia',
  'Population': '192001',
  'area': '2944.0'},
 {'country name': 'Mayotte',
  'capital': 'Mamoudzou',
  'Population': '159042',
  'area': '374.0'},
 {'country name': 'Zimbabwe',
  'capital': 'Harare',
  'Population': '11651858',
  'area': '390580.0'}]

In [21]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('scrapthisside1 q5_4.csv',index=False)

## 5.5 Extract country details of a Second column of a page & save into csv file.

In [22]:
var = soup.find_all('div',class_='col-md-4 country')
var

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">

In [23]:
list = []
for vars in var[1:250:3]:
    dictionary={
        'country name':'',
        'capital':'',
        'Population':'',
        'area':'',

    }
    # print(dictionary)
    dictionary['country name']=vars.find('h3').text.strip()
    dictionary['capital']=vars.find('span',class_='country-capital').text
    dictionary['Population']=vars.find('span',class_='country-population').text
    dictionary['area']=vars.find('span',class_='country-area').text
    list.append(dictionary)

In [24]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('scrapthisside1 q5_5.csv',index=False)

## 5.6 Extract country details of a Third column of a page & save into csv file.

In [25]:
var = soup.find_all('div',class_='col-md-4 country')
var

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">

In [26]:
list = []
for vars in var[2:250:3]:
    dictionary={
        'country name':'',
        'capital':'',
        'Population':'',
        'area':'',

    }
    # print(dictionary)
    dictionary['country name']=vars.find('h3').text.strip()
    dictionary['capital']=vars.find('span',class_='country-capital').text
    dictionary['Population']=vars.find('span',class_='country-population').text
    dictionary['area']=vars.find('span',class_='country-area').text
    list.append(dictionary)

In [27]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('scrapthisside1 q5_6.csv',index=False)