In [1]:
import requests
from bs4 import BeautifulSoup
url = ('https://www.yello.ae/location/dubai')
response = requests.get(url)
# print(response.text)
response.status_code
soup = BeautifulSoup(response.text, 'html')
soup

<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"/><meta content="en" http-equiv="Content-Language"/><meta content="initial-scale=1, maximum-scale=5, minimum-scale=1, user-scalable=1, width=device-width" name="viewport"/><title>List of 130,993 Registered Companies in Dubai, UAE</title><meta content="Top verified registered companies in the Dubai, UAE. Companies near me, Businesses in Dubai, Business directory Dubai, Big companies in Dubai, Corporate companies in Dubai" name="description"/><link as="style" href="/css/main_v2.min.css?v=824" rel="preload"/><link href="/css/main_v2.min.css?v=824" rel="stylesheet" type="text/css"/><link href="https://www.yello.ae/favs/y-96.png" rel="shortcut icon" sizes="96x96" type="image/png"/><link href="/manifest/aemanifest.json" rel="manifest"/><link href="/favs/y-96.png" rel="apple-touch-icon"/><meta content="none" name="msapplication-config"/><meta content="#ffffff" name="theme-color"/><meta content="#ffffff" name="msapplication-navbutton-color"/><link href="https://ajax.googleapis.com" rel="preconnect"/><link href="https://maxcdn.bootstrapcdn.com" rel="preconnect"/><link href="https://googleads.g.doubleclick.net" rel="preconnect"/><link href="https://fundingchoicesmessages.google.com" rel="preconnect"/>
<link href="https://www.yello.ae/rss" rel="alternate" title="UAE Business Directory Feed" type="application/rss+xml"/>
<link href="https://www.yello.ae/location/dubai?amp=1" rel="amphtml"/><link href="https://www.yello.ae/location/dubai" rel="canonical"/><link href="https://www.yello.ae/location/dubai/2" rel="next"/><meta content="en_AE" property="og:locale"/><meta content="Yello UAE" property="og:site_name"/><meta content="website" property="og:type"/><meta content="List of 130,993 Registered Companies in Dubai, UAE" property="og:title"/><meta content="https://www.yello.ae/location/dubai" property="og:url"/><meta content="https://www.yello.ae/img/def/yello.webp" property="og:image"/><meta content="1200" property="og:image:width"/><meta content="630" property="og:image:height"/><meta content="Top verified registered companies in the Dubai, UAE. Companies near me, Businesses in Dubai, Business directory Dubai, Big companies in Dubai, Corporate companies in Dubai" property="og:description"/><meta content="https://www.facebook.com/yellouae" property="og:see_also"/><meta content="summary_large_image" name="twitter:card"/><meta content="summary_large_image" name="twitter:card"/><meta content="List of 130,993 Registered Companies in Dubai, UAE" name="twitter:title"/><meta content="Top verified registered companies in the Dubai, UAE. Companies near me, Businesses in Dubai, Business directory Dubai, Big companies in Dubai, Corporate companies in Dubai" name="twitter:description"/><meta content="https://www.yello.ae/img/def/yello.webp" name="twitter:image"/><meta content="1200" name="twitter:image:width"/><meta content="630" name="twitter:image:height"/><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-LCKN56H6MT"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-LCKN56H6MT');gtag("config", "G-KJZ6CRN0QB");</script><script async="" crossorigin="anonymous" data-ad-client="ca-pub-3351151485848212" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script async="" nonce="MK2FWOFYsAMP7kvNDFwNDw" src="https://fundingchoicesmessages.google.com/i/pub-3351151485848212?ers=1"></script><script nonce="MK2FWOFYsAMP7kvNDFwNDw">(function() {function signalGooglefcPresent() {if (!window.frames['googlefcPresent']) {if (document.body) {const iframe = document.createElement('iframe'); iframe.style = 'width: 0; height: 0; border: none; z-index: -1000; left: -1000px; top: -1000px;'; iframe.style.display = 'none'; iframe.name = 'googlefcPresent'; document.body.appendChild(iframe);} else {setTimeout(signalGooglefcPresent, 0);}}}signalGooglefcPresent();})();</script></head><body><a id="nav-top"></a>
<header><nav aria-label="Main Navigation" role="navigation"><a class="logo_link logo_yello" href="https://www.yello.ae" style="background-image: url(/img/logos/yello.png?v=26);" title="UAE Business Directory - Yello UAE">UAE Business Directory - Yello UAE</a><div class="round20 hidden" id="login"></div><div class="userbox userbox_en">
<div id="userbox_menu"><button aria-expanded="true" aria-label="Sign in" id="login_button" role="button">Sign in</button><a class="add_business" href="/create-business-listing">Get Listed</a></div>
<button aria-expanded="false" aria-label="Search" class="m_header_link m_search_link search_call" data-pos="top" role="button"><i aria-hidden="true" class="fa fa fa-search"></i></button>
<button aria-expanded="false" aria-label="Browse" class="m_header_link m_menu_link" data-ajaxload="1" role="button"><i aria-hidden="true" class="fa fa fa-bars"></i></button>
</div><div id="dm"><div id="dm_in"></div></div> </nav></header><main><section>
<div class="tp scroller"><ul itemscope="" itemtype="https://schema.org/BreadcrumbList"><li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem"><a href="/" itemprop="item"><span itemprop="name">UAE</span></a><meta content="1" itemprop="position"/></li><li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem"><a href="/browse-business-cities" itemprop="item"><span itemprop="name">Cities</span></a><meta content="2" itemprop="position"/></li><li>Dubai</li></ul></div><h1>List of 130,993 Registered Companies in Dubai, UAE</h1><div id="page_text">Top verified registered companies in the Dubai, near me Dec 2025</div><div class="ad336">
<ins class="adsbygoogle asas" data-ad-client="ca-pub-3351151485848212" data-ad-format="auto" data-ad-slot="3758602228" data-full-width-responsive="true" style="display:block"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({}); </script>
</div><div id="listings"><div class="pages_container_top"><h2 class="pages_h2">We found <strong>130,993</strong> companies registered in Dubai, UAE</h2></div><button aria-expanded="false" aria-label="Map" data-map-key="AIzaSyCJa7hHE89_JJ9LK4P_qfYD_o-Qc767Ii8" data-map-lng="55.307485" data-map-ltd="25.271139" data-map-zoom="15" id="m_map_link" role="button"><i aria-hidden="true" class="fa fa-map"></i>  Map</button><div class="flex-container"><div class="company with_img g_3" data-cmpid="344684" id="cmap_0"><i>Sponsored</i><div class="company_header"><h3><a href="/company/344684/al-khatri-interior-designfit-out" target="_blank">Khatri Interior Design and Fit-Out</a></h3><div class="address">Address: 133 Al Ittihad Rd - <b>Dubai</b>, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Innovative interior solutions for luxury spaces.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/l/_1690793386-18-khatri-interior-design-and-fit-out.jpg" href="/company/344684/al-khatri-interior-designfit-out" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+12</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 56 105 4946</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2007 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>21 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="0" data-lng="55.3480400003052" data-ltd="25.2731570120788"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>
<div class="company with_img g_3" data-cmpid="355527" id="cmap_1"><i>Sponsored</i><div class="company_header"><h3><a href="/company/355527/al-jazeerah-pest-controlcleaning-service" target="_blank">Al Jazeerah Pest Control &amp; Cleaning Service </a></h3><div class="address">Address: International City England , <b>Dubai</b>, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Comprehensive pest control and cleaning services.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/f/_1691503017-46-al-jazeerah-a-k-pest-control-cleaning-service.jpg" href="/company/355527/al-jazeerah-pest-controlcleaning-service" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+9</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 450 3654</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2011 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="1" data-lng="55.408061533746896" data-ltd="25.17305584973514"></div></div>
<div class="company with_img g_3" data-cmpid="350653" id="cmap_2"><i>Sponsored</i><div class="company_header"><h3><a href="/company/350653/hassan-elhais-professional-lawyer" target="_blank">Hassan Elhais - Professional Lawyer</a></h3><div class="address">Address: The H Hotel Office Tower 29th Floor, Sheikh Zayed Road, <b>Dubai</b>, United Arab Emirates, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Expert legal services in Dubai, UAE.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/j/_1450094837-31-hassan-elhais-professional-lawyer.jpg" href="/company/350653/hassan-elhais-professional-lawyer" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+10</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 355 8000</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2003 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="2" data-lng="55.2867636563965" data-ltd="25.2300844038061"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>
<div class="company with_img g_3" data-cmpid="346658" id="cmap_3"><i>Sponsored</i><div class="company_header"><h3><a href="/company/346658/axis-passenger-transport-bus-rentllc" target="_blank">Axis Passenger Transport Bus Rent LLC</a></h3><div class="address">Address: Office No 9 Home Shop Building,umm Ramool, <b>Dubai</b>, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Reliable bus rental services in Dubai.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/m/_1415476361-axis-passenger-transport-bus-rent-llc.jpg" href="/company/346658/axis-passenger-transport-bus-rentllc" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+11</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 285 5045</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2006 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>11 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="3" data-lng="55.374698638916" data-ltd="25.21988955008"></div></div>
<div class="company with_img g_3" data-cmpid="367668" id="cmap_4"><i>Sponsored</i><div class="company_header"><h3><a href="/company/367668/mena-research-partners" target="_blank">MENA Research Partners</a></h3><div class="address">Address: Emirates Towers, 41st floor Sheikh Zayed Road <b>Dubai</b>, Po Box 31303, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Insightful research and analysis in MENA.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/c/_1610010835-87-mena-research-partners.png" href="/company/367668/mena-research-partners" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+5</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 50 813 3520</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2013 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="4" data-lng="55.2827954292297" data-ltd="25.2176182886652"></div></div>
<div class="company company_ad"><ins class="adsbygoogle" data-ad-client="ca-pub-3351151485848212" data-ad-format="fluid" data-ad-layout-key="-ht+5+15-58+68" data-ad-slot="7479942841" style="display:block"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div><div class="company with_img g_3" data-cmpid="351780" id="cmap_5"><i>Sponsored</i><div class="company_header"><h3><a href="/company/351780/mas-transport" target="_blank">Mas Transport </a></h3><div class="address">Address: Ras Al Khor Industrial Area - Ras Al Khor Industrial Area 2, <b>Dubai</b>, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Reliable transportation solutions at competitive rates</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/z/_1531213472-45-mas-transport.png" href="/company/351780/mas-transport" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+10</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 336 6450</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2015 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>20 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="5" data-lng="55.2838897705078" data-ltd="25.1738736805988"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>
<div class="company with_img g_3" data-cmpid="317508" id="cmap_6"><i>Sponsored</i><div class="company_header"><h3><a href="/company/317508/infinity-innovations-general-trading-llc" target="_blank">INFINITY Innovations General Trading LLC</a></h3><div class="address">Address: Office 105, A.S.B. Tower, <b>Dubai</b> Silicon Oasis, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Innovative trading solutions in diverse sectors.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/r/_1690799070-52-infinity-innovations-general-trading-l-l-c.jpg" href="/company/317508/infinity-innovations-general-trading-llc" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+13</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 392 2994</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2011 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>8 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="6" data-lng="55.377391576767" data-ltd="25.1104812010902"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>

In [25]:
yall= soup.find_all('div',class_='company with_img g_3')
yall

[<div class="company with_img g_3" data-cmpid="344684" id="cmap_0"><i>Sponsored</i><div class="company_header"><h3><a href="/company/344684/al-khatri-interior-designfit-out" target="_blank">Khatri Interior Design and Fit-Out</a></h3><div class="address">Address: 133 Al Ittihad Rd - <b>Dubai</b>, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Innovative interior solutions for luxury spaces.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/l/_1690793386-18-khatri-interior-design-and-fit-out.jpg" href="/company/344684/al-khatri-interior-designfit-out" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+12</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 56 105 4946</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2007 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>21 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="0" data-lng="55.3480400003052" data-ltd="25.2731570120788"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>,
 <div class="company with_img g_3" data-cmpid="355527" id="cmap_1"><i>Sponsored</i><div class="company_header"><h3><a href="/company/355527/al-jazeerah-pest-controlcleaning-service" target="_blank">Al Jazeerah Pest Control &amp; Cleaning Service </a></h3><div class="address">Address: International City England , <b>Dubai</b>, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Comprehensive pest control and cleaning services.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/f/_1691503017-46-al-jazeerah-a-k-pest-control-cleaning-service.jpg" href="/company/355527/al-jazeerah-pest-controlcleaning-service" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+9</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 450 3654</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2011 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="1" data-lng="55.408061533746896" data-ltd="25.17305584973514"></div></div>,
 <div class="company with_img g_3" data-cmpid="350653" id="cmap_2"><i>Sponsored</i><div class="company_header"><h3><a href="/company/350653/hassan-elhais-professional-lawyer" target="_blank">Hassan Elhais - Professional Lawyer</a></h3><div class="address">Address: The H Hotel Office Tower 29th Floor, Sheikh Zayed Road, <b>Dubai</b>, United Arab Emirates, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Expert legal services in Dubai, UAE.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/j/_1450094837-31-hassan-elhais-professional-lawyer.jpg" href="/company/350653/hassan-elhais-professional-lawyer" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+10</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 355 8000</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2003 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="2" data-lng="55.2867636563965" data-ltd="25.2300844038061"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>,
 <div class="company with_img g_3" data-cmpid="346658" id="cmap_3"><i>Sponsored</i><div class="company_header"><h3><a href="/company/346658/axis-passenger-transport-bus-rentllc" target="_blank">Axis Passenger Transport Bus Rent LLC</a></h3><div class="address">Address: Office No 9 Home Shop Building,umm Ramool, <b>Dubai</b>, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Reliable bus rental services in Dubai.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/m/_1415476361-axis-passenger-transport-bus-rent-llc.jpg" href="/company/346658/axis-passenger-transport-bus-rentllc" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+11</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 285 5045</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2006 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>11 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="3" data-lng="55.374698638916" data-ltd="25.21988955008"></div></div>,
 <div class="company with_img g_3" data-cmpid="367668" id="cmap_4"><i>Sponsored</i><div class="company_header"><h3><a href="/company/367668/mena-research-partners" target="_blank">MENA Research Partners</a></h3><div class="address">Address: Emirates Towers, 41st floor Sheikh Zayed Road <b>Dubai</b>, Po Box 31303, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Insightful research and analysis in MENA.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/c/_1610010835-87-mena-research-partners.png" href="/company/367668/mena-research-partners" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+5</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 50 813 3520</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2013 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="4" data-lng="55.2827954292297" data-ltd="25.2176182886652"></div></div>,
 <div class="company with_img g_3" data-cmpid="351780" id="cmap_5"><i>Sponsored</i><div class="company_header"><h3><a href="/company/351780/mas-transport" target="_blank">Mas Transport </a></h3><div class="address">Address: Ras Al Khor Industrial Area - Ras Al Khor Industrial Area 2, <b>Dubai</b>, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Reliable transportation solutions at competitive rates</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/z/_1531213472-45-mas-transport.png" href="/company/351780/mas-transport" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+10</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 336 6450</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2015 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>20 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="5" data-lng="55.2838897705078" data-ltd="25.1738736805988"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>,
 <div class="company with_img g_3" data-cmpid="317508" id="cmap_6"><i>Sponsored</i><div class="company_header"><h3><a href="/company/317508/infinity-innovations-general-trading-llc" target="_blank">INFINITY Innovations General Trading LLC</a></h3><div class="address">Address: Office 105, A.S.B. Tower, <b>Dubai</b> Silicon Oasis, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Innovative trading solutions in diverse sectors.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/r/_1690799070-52-infinity-innovations-general-trading-l-l-c.jpg" href="/company/317508/infinity-innovations-general-trading-llc" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+13</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 392 2994</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2011 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>8 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="6" data-lng="55.377391576767" data-ltd="25.1104812010902"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>,
 <div class="company with_img g_3" data-cmpid="363959" id="cmap_7"><i>Sponsored</i><div class="company_header"><h3><a href="/company/363959/m-o-k-building-maintenance-llc" target="_blank">MOK Building Maintenance L.L.C</a></h3><div class="address">Address: <b>Dubai</b> Marina, <b>Dubai</b> U.A.E, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Reliable cleaning and maintenance services provider.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/c/_1547461057-26-m-o-k-building-maintenance-l-l-c.jpg" href="/company/363959/m-o-k-building-maintenance-llc" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+7</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 55 524 8568</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2014 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>19 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="7" data-lng="55.1317585423401" data-ltd="25.0737295648046"></div></div>,
 <div class="company with_img g_3" data-cmpid="375427" id="cmap_8"><i>Sponsored</i><div class="company_header"><h3><a href="/company/375427/hha-diving-services-llc" target="_blank">HHA Diving Services LLC</a></h3><div class="address">Address: <b>Dubai</b> International City, UAE</div></div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/f/_1753808187-41-hha-diving-services-llc.jpg" href="/company/375427/hha-diving-services-llc" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><i aria-hidden="true" aria-label="Updated" class="fa fa-bolt" role="img"></i>  Updated</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 56 162 4008</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2017 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>24 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="8" data-lng="55.41240812294842" data-ltd="25.166286174254992"></div></div>,
 <div class="company with_img g_3" data-cmpid="375417" id="cmap_9"><i>Sponsored</i><div class="company_header"><h3><a href="/company/375417/instylea" target="_blank">Instylea</a></h3><div class="address">Address: Instylea LLC-FZ Meydan Grandstand 6th, Floor Meydan Road, Nad Al Sheba, <b>Dubai</b>, UAE</div></div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/k/_1746427509-42-instylea.png" href="/company/375417/instylea" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><i aria-hidden="true" aria-label="Updated" class="fa fa-bolt" role="img"></i>  Updated</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971552172343</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2024 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>100 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="9" data-lng="55.258554" data-ltd="25.173763"></div></div>,
 <div class="company with_img g_3" data-cmpid="349348" id="cmap_10"><i>Sponsored</i><div class="company_header"><h3><a href="/company/349348/amidas-securitec-llc" target="_blank">Amidas Securitec LLC</a></h3><div class="address">Address: Plt. MO 543A St. 302N, Jebel Ali Free Zone, <b>Dubai</b>, UAE</div></div><div class="tagline"><i aria-hidden="true" aria-label="tagline" class="fa fa-quote-right" role="img"></i>Innovative security solutions for diverse needs.</div><a class="logo lazy-img lazy-bg" data-bg="/img/ae/f/_1690879475-54-amidas-securitec-l-l-c.jpg" href="/company/349348/amidas-securitec-llc" target="_blank"></a><div class="cont"><u class="v"><i aria-hidden="true" aria-label="Verified" class="fa fa-check-circle" role="img"></i>  Verified</u><u class="v v4"><b>+10</b>  Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i aria-hidden="true" aria-label="Phone" class="fa fa-phone" role="img"></i><span>+971 4 887 3291</span></div><div class="s"><i aria-hidden="true" aria-label="Calendar" class="fa fa-calendar" role="img"></i><span>2005 Established</span></div><div class="s"><i aria-hidden="true" aria-label="E-mail" class="fa fa-envelope" role="img"></i><span>E-mail</span></div><div class="s"><i aria-hidden="true" aria-label="Map" class="fa fa-map-marker" role="img"></i><span>Map</span></div><div class="s"><i aria-hidden="true" aria-label="Website" class="fa fa-globe" role="img"></i><span>Website</span></div><div class="s"><i aria-hidden="true" aria-label="Photos" class="fa fa-picture-o" role="img"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-key="10" data-lng="55.0885552167893" data-ltd="24.9779084267843"></div><div class="company_reviews"><div class="stars"></div><div class="rate">4.5</div>2 Reviews</div></div>,

In [26]:
len(yall)

20

In [29]:
list = []
for i in yall:
    dict={
    'company name':'',
    "Establishment year":'',
    'location':'',
    'main_link':'',
    "profile_link":'',
    'Contact number':''
 }

    dict['profile_link']=i.find('a')['href']
    dict['company name']=i.find('h3').text

    dict['Contact number']=i.find('div',class_='s').text
    dict['Establishment year']=i.find_all('div',class_='s')[1].text
    dict['location']=i.find('div',class_='address').text
    list.append(dict)

In [30]:
list

[{'company name': 'Khatri Interior Design and Fit-Out',
  'Establishment year': '2007 Established',
  'location': 'Address: 133 Al Ittihad Rd - Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/344684/al-khatri-interior-designfit-out',
  'Contact number': '+971 56 105 4946'},
 {'company name': 'Al Jazeerah Pest Control & Cleaning Service ',
  'Establishment year': '2011 Established',
  'location': 'Address: International City England , Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/355527/al-jazeerah-pest-controlcleaning-service',
  'Contact number': '+971 4 450 3654'},
 {'company name': 'Hassan Elhais - Professional Lawyer',
  'Establishment year': '2003 Established',
  'location': 'Address: The H Hotel Office Tower 29th Floor, Sheikh Zayed Road, Dubai, United Arab Emirates, UAE',
  'main_link': '',
  'profile_link': '/company/350653/hassan-elhais-professional-lawyer',
  'Contact number': '+971 4 355 8000'},
 {'company name': 'Axis Passenger Transport Bus Rent LLC',
  'Establishment year': '2006 Established',
  'location': 'Address: Office No 9 Home Shop Building,umm Ramool, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/346658/axis-passenger-transport-bus-rentllc',
  'Contact number': '+971 4 285 5045'},
 {'company name': 'MENA Research Partners',
  'Establishment year': '2013 Established',
  'location': 'Address: Emirates Towers, 41st floor Sheikh Zayed Road Dubai, Po Box 31303, UAE',
  'main_link': '',
  'profile_link': '/company/367668/mena-research-partners',
  'Contact number': '+971 50 813 3520'},
 {'company name': 'Mas Transport ',
  'Establishment year': '2015 Established',
  'location': 'Address: Ras Al Khor Industrial Area - Ras Al Khor Industrial Area 2, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/351780/mas-transport',
  'Contact number': '+971 4 336 6450'},
 {'company name': 'INFINITY Innovations General Trading LLC',
  'Establishment year': '2011 Established',
  'location': 'Address: Office 105, A.S.B. Tower, Dubai Silicon Oasis, UAE',
  'main_link': '',
  'profile_link': '/company/317508/infinity-innovations-general-trading-llc',
  'Contact number': '+971 4 392 2994'},
 {'company name': 'MOK Building Maintenance L.L.C',
  'Establishment year': '2014 Established',
  'location': 'Address: Dubai Marina, Dubai U.A.E, UAE',
  'main_link': '',
  'profile_link': '/company/363959/m-o-k-building-maintenance-llc',
  'Contact number': '+971 55 524 8568'},
 {'company name': 'HHA Diving Services LLC',
  'Establishment year': '2017 Established',
  'location': 'Address: Dubai International City, UAE',
  'main_link': '',
  'profile_link': '/company/375427/hha-diving-services-llc',
  'Contact number': '+971 56 162 4008'},
 {'company name': 'Instylea',
  'Establishment year': '2024 Established',
  'location': 'Address: Instylea LLC-FZ Meydan Grandstand 6th, Floor Meydan Road, Nad Al Sheba, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/375417/instylea',
  'Contact number': '+971552172343'},
 {'company name': 'Amidas Securitec LLC',
  'Establishment year': '2005 Established',
  'location': 'Address: Plt. MO 543A St. 302N, Jebel Ali Free Zone, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/349348/amidas-securitec-llc',
  'Contact number': '+971 4 887 3291'},
 {'company name': 'Ibrahim Khan Passenger Transport',
  'Establishment year': '2001 Established',
  'location': 'Address: Al Awir Road, Nadd Al Hamar, Al Mansuri Building, Office No. 03, Next to Bilasa Driving, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/344698/ibrahim-khan-passenger-transport',
  'Contact number': '+971 4 224 0945'},
 {'company name': 'Fast Repair Care Dubai',
  'Establishment year': '2002 Established',
  'location': 'Address: G7 Shop, G7 Building - Al Karama, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/367793/fast-repair-care-dubai',
  'Contact number': '+971 52 245 1145'},
 {'company name': 'Corporate Research & Investigations LLC ',
  'Establishment year': '1990 Established',
  'location': 'Address: Liberty House , Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/348518/corporate-researchinvestigations-llc',
  'Contact number': '+971 4 358 9884'},
 {'company name': 'Eyewa',
  'Establishment year': '2017 Established',
  'location': 'Address: Ground floor, Dubai Festival City - Crescent Dr - opposite to Zara - Dubai Festival City, UAE',
  'main_link': '',
  'profile_link': '/company/367820/eyewa',
  'Contact number': '+971 4 247 2979'},
 {'company name': 'English Way Language Training FZ LLC',
  'Establishment year': '2025 Established',
  'location': 'Address: Dubai Knowledge park, Block 3, Office 101, UAE',
  'main_link': '',
  'profile_link': '/company/375458/english-way-language-training-fz-llc',
  'Contact number': '97143200020'},
 {'company name': 'Gulf Got Talents - Modeling & Casting Agency Dubai',
  'Establishment year': '2024 Established',
  'location': 'Address: 607, M Square, Bur Dubai, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/375411/gulf-got-talents-modelingcasting-agency-dubai',
  'Contact number': '+97142999230'},
 {'company name': 'Cactix',
  'Establishment year': '2011 Established',
  'location': 'Address: Office 207, Wing B, Headquarters Building, Dubai Silicon Oasis, UAE',
  'main_link': '',
  'profile_link': '/company/353787/cactix',
  'Contact number': '+971 4 591 9665'},
 {'company name': 'Office One LLC',
  'Establishment year': '2007 Established',
  'location': 'Address: Al Quoz Industrial 1, Street 4B, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/347010/office-one-llc',
  'Contact number': '+971 4 380 4009'},
 {'company name': 'Car Park Shades Al Muzalaat Building Maintenance ',
  'Establishment year': '2002 Established',
  'location': 'Address: Al Quoz, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/355454/car-park-shades-al-muzalaat-building-maintenance',
  'Contact number': '+971 54 383 9003'}]

In [32]:
import pandas as pd 
df = pd.DataFrame(list)
df

,company name,Establishment year,location,main_link,profile_link,Contact number
0,Khatri Interior Design and Fit-Out,2007 Established,"Address: 133 Al Ittihad Rd - Dubai, UAE",,/company/344684/al-khatri-interior-designfit-out,+971 56 105 4946
1,Al Jazeerah Pest Control & Cleaning Service,2011 Established,"Address: International City England , Dubai, UAE",,/company/355527/al-jazeerah-pest-controlcleani...,+971 4 450 3654
2,Hassan Elhais - Professional Lawyer,2003 Established,"Address: The H Hotel Office Tower 29th Floor, ...",,/company/350653/hassan-elhais-professional-lawyer,+971 4 355 8000
3,Axis Passenger Transport Bus Rent LLC,2006 Established,"Address: Office No 9 Home Shop Building,umm Ra...",,/company/346658/axis-passenger-transport-bus-r...,+971 4 285 5045
4,MENA Research Partners,2013 Established,"Address: Emirates Towers, 41st floor Sheikh Za...",,/company/367668/mena-research-partners,+971 50 813 3520
5,Mas Transport,2015 Established,Address: Ras Al Khor Industrial Area - Ras Al ...,,/company/351780/mas-transport,+971 4 336 6450
6,INFINITY Innovations General Trading LLC,2011 Established,"Address: Office 105, A.S.B. Tower, Dubai Silic...",,/company/317508/infinity-innovations-general-t...,+971 4 392 2994
7,MOK Building Maintenance L.L.C,2014 Established,"Address: Dubai Marina, Dubai U.A.E, UAE",,/company/363959/m-o-k-building-maintenance-llc,+971 55 524 8568
8,HHA Diving Services LLC,2017 Established,"Address: Dubai International City, UAE",,/company/375427/hha-diving-services-llc,+971 56 162 4008
9,Instylea,2024 Established,Address: Instylea LLC-FZ Meydan Grandstand 6th...,,/company/375417/instylea,+971552172343
10,Amidas Securitec LLC,2005 Established,"Address: Plt. MO 543A St. 302N, Jebel Ali Free...",,/company/349348/amidas-securitec-llc,+971 4 887 3291
11,Ibrahim Khan Passenger Transport,2001 Established,"Address: Al Awir Road, Nadd Al Hamar, Al Mansu...",,/company/344698/ibrahim-khan-passenger-transport,+971 4 224 0945
12,Fast Repair Care Dubai,2002 Established,"Address: G7 Shop, G7 Building - Al Karama, Dub...",,/company/367793/fast-repair-care-dubai,+971 52 245 1145
13,Corporate Research & Investigations LLC,1990 Established,"Address: Liberty House , Dubai, UAE",,/company/348518/corporate-researchinvestigatio...,+971 4 358 9884
14,Eyewa,2017 Established,"Address: Ground floor, Dubai Festival City - C...",,/company/367820/eyewa,+971 4 247 2979
15,English Way Language Training FZ LLC,2025 Established,"Address: Dubai Knowledge park, Block 3, Office...",,/company/375458/english-way-language-training-...,97143200020
16,Gulf Got Talents - Modeling & Casting Agency D...,2024 Established,"Address: 607, M Square, Bur Dubai, Dubai, UAE",,/company/375411/gulf-got-talents-modelingcasti...,+97142999230
17,Cactix,2011 Established,"Address: Office 207, Wing B, Headquarters Buil...",,/company/353787/cactix,+971 4 591 9665
18,Office One LLC,2007 Established,"Address: Al Quoz Industrial 1, Street 4B, Duba...",,/company/347010/office-one-llc,+971 4 380 4009
19,Car Park Shades Al Muzalaat Building Maintenance,2002 Established,"Address: Al Quoz, Dubai, UAE",,/company/355454/car-park-shades-al-muzalaat-bu...,+971 54 383 9003

In [33]:
df.to_csv('assigment no1.csv',index=False)
df

,company name,Establishment year,location,main_link,profile_link,Contact number
0,Khatri Interior Design and Fit-Out,2007 Established,"Address: 133 Al Ittihad Rd - Dubai, UAE",,/company/344684/al-khatri-interior-designfit-out,+971 56 105 4946
1,Al Jazeerah Pest Control & Cleaning Service,2011 Established,"Address: International City England , Dubai, UAE",,/company/355527/al-jazeerah-pest-controlcleani...,+971 4 450 3654
2,Hassan Elhais - Professional Lawyer,2003 Established,"Address: The H Hotel Office Tower 29th Floor, ...",,/company/350653/hassan-elhais-professional-lawyer,+971 4 355 8000
3,Axis Passenger Transport Bus Rent LLC,2006 Established,"Address: Office No 9 Home Shop Building,umm Ra...",,/company/346658/axis-passenger-transport-bus-r...,+971 4 285 5045
4,MENA Research Partners,2013 Established,"Address: Emirates Towers, 41st floor Sheikh Za...",,/company/367668/mena-research-partners,+971 50 813 3520
5,Mas Transport,2015 Established,Address: Ras Al Khor Industrial Area - Ras Al ...,,/company/351780/mas-transport,+971 4 336 6450
6,INFINITY Innovations General Trading LLC,2011 Established,"Address: Office 105, A.S.B. Tower, Dubai Silic...",,/company/317508/infinity-innovations-general-t...,+971 4 392 2994
7,MOK Building Maintenance L.L.C,2014 Established,"Address: Dubai Marina, Dubai U.A.E, UAE",,/company/363959/m-o-k-building-maintenance-llc,+971 55 524 8568
8,HHA Diving Services LLC,2017 Established,"Address: Dubai International City, UAE",,/company/375427/hha-diving-services-llc,+971 56 162 4008
9,Instylea,2024 Established,Address: Instylea LLC-FZ Meydan Grandstand 6th...,,/company/375417/instylea,+971552172343
10,Amidas Securitec LLC,2005 Established,"Address: Plt. MO 543A St. 302N, Jebel Ali Free...",,/company/349348/amidas-securitec-llc,+971 4 887 3291
11,Ibrahim Khan Passenger Transport,2001 Established,"Address: Al Awir Road, Nadd Al Hamar, Al Mansu...",,/company/344698/ibrahim-khan-passenger-transport,+971 4 224 0945
12,Fast Repair Care Dubai,2002 Established,"Address: G7 Shop, G7 Building - Al Karama, Dub...",,/company/367793/fast-repair-care-dubai,+971 52 245 1145
13,Corporate Research & Investigations LLC,1990 Established,"Address: Liberty House , Dubai, UAE",,/company/348518/corporate-researchinvestigatio...,+971 4 358 9884
14,Eyewa,2017 Established,"Address: Ground floor, Dubai Festival City - C...",,/company/367820/eyewa,+971 4 247 2979
15,English Way Language Training FZ LLC,2025 Established,"Address: Dubai Knowledge park, Block 3, Office...",,/company/375458/english-way-language-training-...,97143200020
16,Gulf Got Talents - Modeling & Casting Agency D...,2024 Established,"Address: 607, M Square, Bur Dubai, Dubai, UAE",,/company/375411/gulf-got-talents-modelingcasti...,+97142999230
17,Cactix,2011 Established,"Address: Office 207, Wing B, Headquarters Buil...",,/company/353787/cactix,+971 4 591 9665
18,Office One LLC,2007 Established,"Address: Al Quoz Industrial 1, Street 4B, Duba...",,/company/347010/office-one-llc,+971 4 380 4009
19,Car Park Shades Al Muzalaat Building Maintenance,2002 Established,"Address: Al Quoz, Dubai, UAE",,/company/355454/car-park-shades-al-muzalaat-bu...,+971 54 383 9003

In [19]:
import requests
from bs4 import BeautifulSoup
url = ('https://www.yello.ae/location/dubai')
response = requests.get(url)
print(response.text)
response.status_code
soup = BeautifulSoup(response.text, 'html')
soup

yall= soup.find_all('div',class_='company with_img g_3')
yall
url_b = url+str(yall)+'html'
response = requests.get(url_b)
print(response.status_code)
soup = BeautifulSoup(response.text,('html'))
list = []
for i in yall:
    dict={
    'company name':'',
    "Establishment year":'',
    'location':'',
    'main_link':'',
    "profile_link":'',
    'Contact number':''
 }

    dict['profile_link']=i.find('a')['href']
    dict['company name']=i.find('h3').text

    dict['Contact number']=i.find('div',class_='s').text
    dict['Establishment year']=i.find_all('div',class_='s')[1].text
    dict['location']=i.find('div',class_='address').text
    list.append(dict)

<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8" /><meta http-equiv="Content-Language" content="en" /><meta name="viewport" content="initial-scale=1, maximum-scale=5, minimum-scale=1, user-scalable=1, width=device-width"><title>List of 130,994 Registered Companies in Dubai, UAE</title><meta name="description" content="Top verified registered companies in the Dubai, UAE. Companies near me, Businesses in Dubai, Business directory Dubai, Big companies in Dubai, Corporate companies in Dubai"/><link rel="preload" href="/css/main_v2.min.css?v=824" as="style" /><link rel="stylesheet" type="text/css" href="/css/main_v2.min.css?v=824" /><link rel="shortcut icon" href="https://www.yello.ae/favs/y-96.png" sizes="96x96" type="image/png" /><link rel="manifest" href="/manifest/aemanifest.json"><link rel="apple-touch-icon" href="/favs/y-96.png"><meta name="msapplication-config" content="none" /><meta name="theme-color" content="#ffffff"><meta name="msapplication-navbutton-color" content="#ffffff"><link rel="preconnect" href="https://ajax.googleapis.com"><link rel="preconnect" href="https://maxcdn.bootstrapcdn.com"><link rel="preconnect" href="https://googleads.g.doubleclick.net"><link rel="preconnect" href="https://fundingchoicesmessages.google.com">
<link rel="alternate" type="application/rss+xml" title="UAE Business Directory Feed" href="https://www.yello.ae/rss">
<link rel="amphtml" href="https://www.yello.ae/location/dubai?amp=1"><link rel="canonical" href="https://www.yello.ae/location/dubai" /><link rel="next" href="https://www.yello.ae/location/dubai/2" /><meta content="en_AE" property="og:locale"><meta property="og:site_name" content="Yello UAE" /><meta property="og:type" content="website" /><meta property="og:title" content="List of 130,994 Registered Companies in Dubai, UAE" /><meta property="og:url" content="https://www.yello.ae/location/dubai" /><meta property="og:image" content="https://www.yello.ae/img/def/yello.webp" /><meta property="og:image:width" content="1200" /><meta property="og:image:height" content="630" /><meta property="og:description" content="Top verified registered companies in the Dubai, UAE. Companies near me, Businesses in Dubai, Business directory Dubai, Big companies in Dubai, Corporate companies in Dubai" /><meta property="og:see_also" content="https://www.facebook.com/yellouae" /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content="List of 130,994 Registered Companies in Dubai, UAE" /><meta name="twitter:description" content="Top verified registered companies in the Dubai, UAE. Companies near me, Businesses in Dubai, Business directory Dubai, Big companies in Dubai, Corporate companies in Dubai" /><meta name="twitter:image" content="https://www.yello.ae/img/def/yello.webp" /><meta name="twitter:image:width" content="1200" /><meta name="twitter:image:height" content="630" /><script async src="https://www.googletagmanager.com/gtag/js?id=G-LCKN56H6MT"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-LCKN56H6MT');gtag("config", "G-KJZ6CRN0QB");</script><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" data-ad-client="ca-pub-3351151485848212" crossorigin="anonymous"></script><script async src="https://fundingchoicesmessages.google.com/i/pub-3351151485848212?ers=1" nonce="MK2FWOFYsAMP7kvNDFwNDw"></script><script nonce="MK2FWOFYsAMP7kvNDFwNDw">(function() {function signalGooglefcPresent() {if (!window.frames['googlefcPresent']) {if (document.body) {const iframe = document.createElement('iframe'); iframe.style = 'width: 0; height: 0; border: none; z-index: -1000; left: -1000px; top: -1000px;'; iframe.style.display = 'none'; iframe.name = 'googlefcPresent'; document.body.appendChild(iframe);} else {setTimeout(signalGooglefcPresent, 0);}}}signalGooglefcPresent();})();</script></head><body><a id="nav-top"></a>
<header><nav role="navigation" aria-label="Main Navigation"><a href="https://www.yello.ae" title="UAE Business Directory - Yello UAE" class="logo_link logo_yello" style="background-image: url(/img/logos/yello.png?v=26);">UAE Business Directory - Yello UAE</a><div id="login" class="round20 hidden"></div><div class="userbox userbox_en">
<div id="userbox_menu"><button id="login_button" aria-label="Sign in" role="button" aria-expanded="true">Sign in</button><a href="/create-business-listing" class="add_business">Get Listed</a></div>
<button class="m_header_link m_search_link search_call" data-pos="top" aria-label="Search" role="button" aria-expanded="false"><i class="fa fa fa-search" aria-hidden="true"></i></button>
<button class="m_header_link m_menu_link" aria-label="Browse" role="button" aria-expanded="false" data-ajaxload="1"><i class="fa fa fa-bars" aria-hidden="true"></i></button>
</div><div id="dm"><div id="dm_in"></div></div>	</nav></header><main><section>
<div class="tp scroller"><ul itemscope itemtype="https://schema.org/BreadcrumbList"><li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a href="/" itemprop="item"><span itemprop="name">UAE</span></a><meta itemprop="position" content="1" /></li><li itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a href="/browse-business-cities" itemprop="item"><span itemprop="name">Cities</span></a><meta itemprop="position" content="2" /></li><li>Dubai</li></ul></div><h1>List of 130,994 Registered Companies in Dubai, UAE</h1><div id="page_text">Top verified registered companies in the Dubai, near me Dec 2025</div><div class="ad336">
<ins class="adsbygoogle asas" style="display:block" data-ad-client="ca-pub-3351151485848212" data-ad-slot="3758602228" data-ad-format="auto" data-full-width-responsive="true"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({}); </script>
</div><div id="listings"><div class="pages_container_top"><h2 class="pages_h2">We found <strong>130,994</strong> companies registered in Dubai, UAE</h2></div><button aria-label="Map" role="button" aria-expanded="false" id="m_map_link" data-map-ltd="25.271139" data-map-lng="55.307485" data-map-key="AIzaSyCJa7hHE89_JJ9LK4P_qfYD_o-Qc767Ii8" data-map-zoom="15"><i class="fa fa-map" aria-hidden="true"></i>&nbsp;&nbsp;Map</button><div class="flex-container"><div class="company with_img g_3" id="cmap_0" data-cmpid="344684"><i>Sponsored</i><div class="company_header"><h3><a href="/company/344684/al-khatri-interior-designfit-out" target="_blank">Khatri Interior Design and Fit-Out</a></h3><div class="address">Address: 133 Al Ittihad Rd &#45; <b>Dubai</b>, UAE</div></div><div class="tagline"><i class="fa fa-quote-right" aria-hidden="true" role="img" aria-label="tagline"></i>Innovative interior solutions for luxury spaces.</div><a href="/company/344684/al-khatri-interior-designfit-out" class="logo lazy-img lazy-bg" target="_blank" data-bg="/img/ae/l/_1690793386-18-khatri-interior-design-and-fit-out.jpg"></a><div class="cont"><u class="v"><i class="fa fa-check-circle" role="img" aria-label="Verified" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+12</b> &nbsp;Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i class="fa fa-phone" role="img" aria-label="Phone" aria-hidden="true"></i><span>+971 56 105 4946</span></div><div class="s"><i class="fa fa-calendar" role="img" aria-label="Calendar" aria-hidden="true"></i><span>2007 Established</span></div><div class="s"><i class="fa fa-envelope" role="img" aria-label="E-mail" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" role="img" aria-label="Map" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" role="img" aria-label="Website" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" role="img" aria-label="Photos" aria-hidden="true"></i><span>21 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-ltd="25.2731570120788" data-lng="55.3480400003052" data-key="0"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>
<div class="company with_img g_3" id="cmap_1" data-cmpid="355527"><i>Sponsored</i><div class="company_header"><h3><a href="/company/355527/al-jazeerah-pest-controlcleaning-service" target="_blank">Al Jazeerah Pest Control &amp; Cleaning Service </a></h3><div class="address">Address: International City England , <b>Dubai</b>, UAE</div></div><div class="tagline"><i class="fa fa-quote-right" aria-hidden="true" role="img" aria-label="tagline"></i>Comprehensive pest control and cleaning services.</div><a href="/company/355527/al-jazeerah-pest-controlcleaning-service" class="logo lazy-img lazy-bg" target="_blank" data-bg="/img/ae/f/_1691503017-46-al-jazeerah-a-k-pest-control-cleaning-service.jpg"></a><div class="cont"><u class="v"><i class="fa fa-check-circle" role="img" aria-label="Verified" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+9</b> &nbsp;Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i class="fa fa-phone" role="img" aria-label="Phone" aria-hidden="true"></i><span>+971 4 450 3654</span></div><div class="s"><i class="fa fa-calendar" role="img" aria-label="Calendar" aria-hidden="true"></i><span>2011 Established</span></div><div class="s"><i class="fa fa-envelope" role="img" aria-label="E-mail" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" role="img" aria-label="Map" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" role="img" aria-label="Website" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" role="img" aria-label="Photos" aria-hidden="true"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-ltd="25.17305584973514" data-lng="55.408061533746896" data-key="1"></div></div>
<div class="company with_img g_3" id="cmap_2" data-cmpid="350653"><i>Sponsored</i><div class="company_header"><h3><a href="/company/350653/hassan-elhais-professional-lawyer" target="_blank">Hassan Elhais - Professional Lawyer</a></h3><div class="address">Address: The H Hotel Office Tower 29th Floor, Sheikh Zayed Road, <b>Dubai</b>, United Arab Emirates, UAE</div></div><div class="tagline"><i class="fa fa-quote-right" aria-hidden="true" role="img" aria-label="tagline"></i>Expert legal services in Dubai, UAE.</div><a href="/company/350653/hassan-elhais-professional-lawyer" class="logo lazy-img lazy-bg" target="_blank" data-bg="/img/ae/j/_1450094837-31-hassan-elhais-professional-lawyer.jpg"></a><div class="cont"><u class="v"><i class="fa fa-check-circle" role="img" aria-label="Verified" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+10</b> &nbsp;Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i class="fa fa-phone" role="img" aria-label="Phone" aria-hidden="true"></i><span>+971 4 355 8000</span></div><div class="s"><i class="fa fa-calendar" role="img" aria-label="Calendar" aria-hidden="true"></i><span>2003 Established</span></div><div class="s"><i class="fa fa-envelope" role="img" aria-label="E-mail" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" role="img" aria-label="Map" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" role="img" aria-label="Website" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" role="img" aria-label="Photos" aria-hidden="true"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-ltd="25.2300844038061" data-lng="55.2867636563965" data-key="2"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>
<div class="company with_img g_3" id="cmap_3" data-cmpid="346658"><i>Sponsored</i><div class="company_header"><h3><a href="/company/346658/axis-passenger-transport-bus-rentllc" target="_blank">Axis Passenger Transport Bus Rent LLC</a></h3><div class="address">Address: Office No 9 Home Shop Building,umm Ramool, <b>Dubai</b>, UAE</div></div><div class="tagline"><i class="fa fa-quote-right" aria-hidden="true" role="img" aria-label="tagline"></i>Reliable bus rental services in Dubai.</div><a href="/company/346658/axis-passenger-transport-bus-rentllc" class="logo lazy-img lazy-bg" target="_blank" data-bg="/img/ae/m/_1415476361-axis-passenger-transport-bus-rent-llc.jpg"></a><div class="cont"><u class="v"><i class="fa fa-check-circle" role="img" aria-label="Verified" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+11</b> &nbsp;Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i class="fa fa-phone" role="img" aria-label="Phone" aria-hidden="true"></i><span>+971 4 285 5045</span></div><div class="s"><i class="fa fa-calendar" role="img" aria-label="Calendar" aria-hidden="true"></i><span>2006 Established</span></div><div class="s"><i class="fa fa-envelope" role="img" aria-label="E-mail" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" role="img" aria-label="Map" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" role="img" aria-label="Website" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" role="img" aria-label="Photos" aria-hidden="true"></i><span>11 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-ltd="25.21988955008" data-lng="55.374698638916" data-key="3"></div></div>
<div class="company with_img g_3" id="cmap_4" data-cmpid="367668"><i>Sponsored</i><div class="company_header"><h3><a href="/company/367668/mena-research-partners" target="_blank">MENA Research Partners</a></h3><div class="address">Address: Emirates Towers, 41st floor Sheikh Zayed Road <b>Dubai</b>, Po Box 31303, UAE</div></div><div class="tagline"><i class="fa fa-quote-right" aria-hidden="true" role="img" aria-label="tagline"></i>Insightful research and analysis in MENA.</div><a href="/company/367668/mena-research-partners" class="logo lazy-img lazy-bg" target="_blank" data-bg="/img/ae/c/_1610010835-87-mena-research-partners.png"></a><div class="cont"><u class="v"><i class="fa fa-check-circle" role="img" aria-label="Verified" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+5</b> &nbsp;Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i class="fa fa-phone" role="img" aria-label="Phone" aria-hidden="true"></i><span>+971 50 813 3520</span></div><div class="s"><i class="fa fa-calendar" role="img" aria-label="Calendar" aria-hidden="true"></i><span>2013 Established</span></div><div class="s"><i class="fa fa-envelope" role="img" aria-label="E-mail" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" role="img" aria-label="Map" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" role="img" aria-label="Website" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" role="img" aria-label="Photos" aria-hidden="true"></i><span>1 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-ltd="25.2176182886652" data-lng="55.2827954292297" data-key="4"></div></div>
<div class="company company_ad"><ins class="adsbygoogle" style="display:block" data-ad-format="fluid" data-ad-layout-key="-ht+5+15-58+68" data-ad-client="ca-pub-3351151485848212" data-ad-slot="7479942841"></ins>
<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div><div class="company with_img g_3" id="cmap_5" data-cmpid="351780"><i>Sponsored</i><div class="company_header"><h3><a href="/company/351780/mas-transport" target="_blank">Mas Transport </a></h3><div class="address">Address: Ras Al Khor Industrial Area &#45; Ras Al Khor Industrial Area 2, <b>Dubai</b>, UAE</div></div><div class="tagline"><i class="fa fa-quote-right" aria-hidden="true" role="img" aria-label="tagline"></i>Reliable transportation solutions at competitive rates</div><a href="/company/351780/mas-transport" class="logo lazy-img lazy-bg" target="_blank" data-bg="/img/ae/z/_1531213472-45-mas-transport.png"></a><div class="cont"><u class="v"><i class="fa fa-check-circle" role="img" aria-label="Verified" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+10</b> &nbsp;Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i class="fa fa-phone" role="img" aria-label="Phone" aria-hidden="true"></i><span>+971 4 336 6450</span></div><div class="s"><i class="fa fa-calendar" role="img" aria-label="Calendar" aria-hidden="true"></i><span>2015 Established</span></div><div class="s"><i class="fa fa-envelope" role="img" aria-label="E-mail" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" role="img" aria-label="Map" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" role="img" aria-label="Website" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" role="img" aria-label="Photos" aria-hidden="true"></i><span>20 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-ltd="25.1738736805988" data-lng="55.2838897705078" data-key="5"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>
<div class="company with_img g_3" id="cmap_6" data-cmpid="317508"><i>Sponsored</i><div class="company_header"><h3><a href="/company/317508/infinity-innovations-general-trading-llc" target="_blank">INFINITY Innovations General Trading LLC</a></h3><div class="address">Address: Office 105, A.S.B. Tower, <b>Dubai</b> Silicon Oasis, UAE</div></div><div class="tagline"><i class="fa fa-quote-right" aria-hidden="true" role="img" aria-label="tagline"></i>Innovative trading solutions in diverse sectors.</div><a href="/company/317508/infinity-innovations-general-trading-llc" class="logo lazy-img lazy-bg" target="_blank" data-bg="/img/ae/r/_1690799070-52-infinity-innovations-general-trading-l-l-c.jpg"></a><div class="cont"><u class="v"><i class="fa fa-check-circle" role="img" aria-label="Verified" aria-hidden="true"></i> &nbsp;Verified</u><u class="v v4"><b>+13</b> &nbsp;Years with us</u></div><div class="clear"></div><div class="cont"><div class="s"><i class="fa fa-phone" role="img" aria-label="Phone" aria-hidden="true"></i><span>+971 4 392 2994</span></div><div class="s"><i class="fa fa-calendar" role="img" aria-label="Calendar" aria-hidden="true"></i><span>2011 Established</span></div><div class="s"><i class="fa fa-envelope" role="img" aria-label="E-mail" aria-hidden="true"></i><span>E-mail</span></div><div class="s"><i class="fa fa-map-marker" role="img" aria-label="Map" aria-hidden="true"></i><span>Map</span></div><div class="s"><i class="fa fa-globe" role="img" aria-label="Website" aria-hidden="true"></i><span>Website</span></div><div class="s"><i class="fa fa-picture-o" role="img" aria-label="Photos" aria-hidden="true"></i><span>8 Photos</span></div></div><div class="clear"></div><div class="mapmarker hidden" data-ltd="25.1104812010902" data-lng="55.377391576767" data-key="6"></div><div class="company_reviews"><div class="stars"></div><div class="rate">5.0</div>1 Review</div></div>

In [20]:
import pandas as pd
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://www.yello.ae/location/dubai')
time.sleep(5)
soup = BeautifulSoup(driver.page_source, 'html.parser')
yall= soup.find_all('div',class_='company with_img g_3')
list = []
for i in yall:
    dict={
    'company name':'',
    "Establishment year":'',
    'location':'',
    'main_link':'',
    "profile_link":'',
    'Contact number':''
 }

    dict['profile_link']=i.find('a')['href']
    dict['company name']=i.find('h3').text

    dict['Contact number']=i.find('div',class_='s').text
    dict['Establishment year']=i.find_all('div',class_='s')[1].text
    dict['location']=i.find('div',class_='address').text
    list.append(dict)

In [21]:
list

[{'company name': 'Khatri Interior Design and Fit-Out',
  'Establishment year': '2007 Established',
  'location': 'Address: 133 Al Ittihad Rd - Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/344684/al-khatri-interior-designfit-out',
  'Contact number': '+971 56 105 4946'},
 {'company name': 'Al Jazeerah Pest Control & Cleaning Service ',
  'Establishment year': '2011 Established',
  'location': 'Address: International City England , Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/355527/al-jazeerah-pest-controlcleaning-service',
  'Contact number': '+971 4 450 3654'},
 {'company name': 'Hassan Elhais - Professional Lawyer',
  'Establishment year': '2003 Established',
  'location': 'Address: The H Hotel Office Tower 29th Floor, Sheikh Zayed Road, Dubai, United Arab Emirates, UAE',
  'main_link': '',
  'profile_link': '/company/350653/hassan-elhais-professional-lawyer',
  'Contact number': '+971 4 355 8000'},
 {'company name': 'Axis Passenger Transport Bus Rent LLC',
  'Establishment year': '2006 Established',
  'location': 'Address: Office No 9 Home Shop Building,umm Ramool, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/346658/axis-passenger-transport-bus-rentllc',
  'Contact number': '+971 4 285 5045'},
 {'company name': 'MENA Research Partners',
  'Establishment year': '2013 Established',
  'location': 'Address: Emirates Towers, 41st floor Sheikh Zayed Road Dubai, Po Box 31303, UAE',
  'main_link': '',
  'profile_link': '/company/367668/mena-research-partners',
  'Contact number': '+971 50 813 3520'},
 {'company name': 'Mas Transport ',
  'Establishment year': '2015 Established',
  'location': 'Address: Ras Al Khor Industrial Area - Ras Al Khor Industrial Area 2, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/351780/mas-transport',
  'Contact number': '+971 4 336 6450'},
 {'company name': 'INFINITY Innovations General Trading LLC',
  'Establishment year': '2011 Established',
  'location': 'Address: Office 105, A.S.B. Tower, Dubai Silicon Oasis, UAE',
  'main_link': '',
  'profile_link': '/company/317508/infinity-innovations-general-trading-llc',
  'Contact number': '+971 4 392 2994'},
 {'company name': 'MOK Building Maintenance L.L.C',
  'Establishment year': '2014 Established',
  'location': 'Address: Dubai Marina, Dubai U.A.E, UAE',
  'main_link': '',
  'profile_link': '/company/363959/m-o-k-building-maintenance-llc',
  'Contact number': '+971 55 524 8568'},
 {'company name': 'HHA Diving Services LLC',
  'Establishment year': '2017 Established',
  'location': 'Address: Dubai International City, UAE',
  'main_link': '',
  'profile_link': '/company/375427/hha-diving-services-llc',
  'Contact number': '+971 56 162 4008'},
 {'company name': 'Instylea',
  'Establishment year': '2024 Established',
  'location': 'Address: Instylea LLC-FZ Meydan Grandstand 6th, Floor Meydan Road, Nad Al Sheba, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/375417/instylea',
  'Contact number': '+971552172343'},
 {'company name': 'Amidas Securitec LLC',
  'Establishment year': '2005 Established',
  'location': 'Address: Plt. MO 543A St. 302N, Jebel Ali Free Zone, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/349348/amidas-securitec-llc',
  'Contact number': '+971 4 887 3291'},
 {'company name': 'Ibrahim Khan Passenger Transport',
  'Establishment year': '2001 Established',
  'location': 'Address: Al Awir Road, Nadd Al Hamar, Al Mansuri Building, Office No. 03, Next to Bilasa Driving, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/344698/ibrahim-khan-passenger-transport',
  'Contact number': '+971 4 224 0945'},
 {'company name': 'Fast Repair Care Dubai',
  'Establishment year': '2002 Established',
  'location': 'Address: G7 Shop, G7 Building - Al Karama, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/367793/fast-repair-care-dubai',
  'Contact number': '+971 52 245 1145'},
 {'company name': 'Corporate Research & Investigations LLC ',
  'Establishment year': '1990 Established',
  'location': 'Address: Liberty House , Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/348518/corporate-researchinvestigations-llc',
  'Contact number': '+971 4 358 9884'},
 {'company name': 'Eyewa',
  'Establishment year': '2017 Established',
  'location': 'Address: Ground floor, Dubai Festival City - Crescent Dr - opposite to Zara - Dubai Festival City, UAE',
  'main_link': '',
  'profile_link': '/company/367820/eyewa',
  'Contact number': '+971 4 247 2979'},
 {'company name': 'English Way Language Training FZ LLC',
  'Establishment year': '2025 Established',
  'location': 'Address: Dubai Knowledge park, Block 3, Office 101, UAE',
  'main_link': '',
  'profile_link': '/company/375458/english-way-language-training-fz-llc',
  'Contact number': '97143200020'},
 {'company name': 'Gulf Got Talents - Modeling & Casting Agency Dubai',
  'Establishment year': '2024 Established',
  'location': 'Address: 607, M Square, Bur Dubai, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/375411/gulf-got-talents-modelingcasting-agency-dubai',
  'Contact number': '+97142999230'},
 {'company name': 'Cactix',
  'Establishment year': '2011 Established',
  'location': 'Address: Office 207, Wing B, Headquarters Building, Dubai Silicon Oasis, UAE',
  'main_link': '',
  'profile_link': '/company/353787/cactix',
  'Contact number': '+971 4 591 9665'},
 {'company name': 'Office One LLC',
  'Establishment year': '2007 Established',
  'location': 'Address: Al Quoz Industrial 1, Street 4B, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/347010/office-one-llc',
  'Contact number': '+971 4 380 4009'},
 {'company name': 'Car Park Shades Al Muzalaat Building Maintenance ',
  'Establishment year': '2002 Established',
  'location': 'Address: Al Quoz, Dubai, UAE',
  'main_link': '',
  'profile_link': '/company/355454/car-park-shades-al-muzalaat-building-maintenance',
  'Contact number': '+971 54 383 9003'}]

In [22]:
driver.execute_script('window.scrollTo(0,1087)')

In [28]:
driver.find_element('xpath',"//a[contains(text(),'→')]")