In [1]:
import pandas as pd
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver

driver  = webdriver.Chrome()
url   = "https://getlatka.com/saas-companies?page=1"
driver.get(url)
time.sleep(5)

tds_of_each_row = trs[0].find_all("td") # trs[0] matlb 1st row of data, next row k leye trs[1]

dic = {
    "name": ""
}

second_colum_of_row = tds_of_each_row[1] # q k second col me company data han

all_a_of_2nd_td = second_colum_of_row.find_all("a") # find all a tags

dic["name"] = all_a_of_2nd_td[0].text # fisrt a k tag k andar company name

for a in all_a_of_2nd_td[1:]: #baki sary links `a tag`` k andar han os k leye loop lagyga. k automatically key/column name with value pick kary 
    key  = a["aria-label"] # `a` tag k attribute `aria-label` mein key/column  name houwta
    value = a["href"] # `a` tag k attribute `href` mein url/link houwta
    # print(f"{key} = {value}")
    dic[key] = value # har row me jis social media links huengy wo automatically save hun jaengy. jaisy k 1st row me 2 links and last row me 5 links. toh humra code chal jayga dono situation py without any error

dic["company location"]  = tds_of_each_row[-2].text # company location sary tds me sy second last `td tag`` me han. jis k leye -2 lagaya
dic["company founder"]  =tds_of_each_row[-6].text.strip() # company founder sary tds me sy last 6th `td tag`` me han. jis k leye -6 lagaya
dic

NameError: name 'trs' is not defined

In [55]:
import pandas as pd
import time
from selenium import webdriver
from bs4 import BeautifulSoup

# WebDriver initialize karo
driver = webdriver.Chrome()

# URL jahan se data scrape karna hai
url = "https://getlatka.com/saas-companies?page=1"
driver.get(url)

# Page load hone ka intezaar karo
time.sleep(5)

# BeautifulSoup ke through page source ko parse karo
soup = BeautifulSoup(driver.page_source, "html.parser")

# Sabhi rows ko find karo (saare tr elements)
trs = soup.find_all("tr")

# Data store karne ke liye ek empty list
list_data = []

# Har row ko loop karke data extract karna
for tr in trs:
    # Har row mein saare td elements find karo
    tds = tr.find_all("td")
    
    # Agar row mein 2 se kam td elements hain, toh wo ya header ho sakta hai ya empty row ho sakti hai, skip karo
    if len(tds) < 2:
        continue

    dic = {}
    
    # Company name aur social media links ko extract karo
    links = tds[1].find_all("a")
    if links:
        dic["name"] = links[0].text  # Pehli link se company ka naam le lo
        for a in links[1:]:  # Baaki links ko loop karke extract karo
            key = a.get("aria-label", "")  # aria-label se key milti hai
            value = a.get("href", "")  # href se link milta hai
            if key and value:  # Agar key aur value dono hain, toh dictionary mein add karo
                dic[key] = value

    # Company location aur founder ki information extract karo
    dic["company location"] = tds[-2].text.strip()  # Last se second td mein location hoti hai
    dic["company founder"] = tds[-6].text.strip()  # Last se sixth td mein founder ka naam hota hai

    # Har company ka data list mein add karna
    list_data.append(dic)

# Data ko pandas DataFrame mein convert karo (optional)
df = pd.DataFrame(list_data)

# Data ko print karo
df

,name,Company linkedIn,website url,company location,company founder,Company Twitter,Company Crunchbase,Company facebook
0,Nue.io,http://www.linkedin.com/company/nue-io?ref=get...,//nue.io/?ref=getlatka.com,United States,Mark Walker,NaN,NaN,NaN
1,briq,https://www.linkedin.com/company/briqhq/?ref=g...,//briq.com/?ref=getlatka.com,(US),Ron Goldshmidt,NaN,NaN,NaN
2,Arcads,https://www.linkedin.com/company/arcads-ai/?re...,//arcads.ai/?ref=getlatka.com,France,,NaN,NaN,NaN
3,BetterPic,NaN,//betterpic.io/?ref=getlatka.com,Estonia,,NaN,NaN,NaN
4,SubMagic,https://www.linkedin.com/company/submagic?ref=...,//submagic.co/?ref=getlatka.com,France,David Zitoun,NaN,NaN,NaN
5,Zapmail,https://www.linkedin.com/company/zapmail-ai/?r...,//zapmail.ai/?ref=getlatka.com,(US),Alan D'Souza,NaN,NaN,NaN
6,MarsX.dev,https://www.linkedin.com/company/marsx?ref=get...,//marsx.dev/?ref=getlatka.com,(US),John Rush,https://twitter.com/marsxdev?ref=getlatka.com,NaN,NaN
7,Cal AI,https://www.linkedin.com/company/cal-ai-app/?r...,//calai.app/?ref=getlatka.com,(US),Jake Castillo,NaN,NaN,NaN
8,Capacity,https://www.linkedin.com/company/teamcapacity?...,//capacity.com/?ref=getlatka.com,(US),David Karandish,NaN,https://www.crunchbase.com/organization/capaci...,NaN
9,TripleDart,https://www.linkedin.com/company/tripledart-di...,//tripledart.com/?ref=getlatka.com,(US),Shiyam Sunder,https://twitter.com/Tripledart_?ref=getlatka.com,NaN,NaN
10,Voxpopme,https://www.linkedin.com/company/voxpopme?ref=...,//voxpopme.com/?ref=getlatka.com,(US),Andrew Barraclough,NaN,https://www.crunchbase.com/organization/voxpop...,NaN
11,Pendo,https://www.linkedin.com/company/pendo-io/?ref...,//pendo.io/?ref=getlatka.com,(US),Todd Olson,https://twitter.com/pendoio?ref=getlatka.com,https://www.crunchbase.com/organization/pendo-...,https://www.facebook.com/Pendoio/?ref=getlatka...
12,Issuu,https://www.linkedin.com/company/issuu/?ref=ge...,//issuu.com/?ref=getlatka.com,(US),,NaN,https://www.crunchbase.com/organization/issuu?...,NaN
13,Ninety.io,https://www.linkedin.com/company/ninety-io?ref...,//ninety.io/?ref=getlatka.com,(US),Tim Weerasiri,NaN,https://www.crunchbase.com/organization/ninety...,NaN
14,Reveleer,https://www.linkedin.com/company/reveleer/?ref...,//reveleer.com/?ref=getlatka.com,(US),,NaN,https://www.crunchbase.com/organization/revele...,NaN
15,Proposify,https://www.linkedin.com/company/proposify/?re...,//proposify.com/?ref=getlatka.com,(CA),Kyle Racki,NaN,https://www.crunchbase.com/organization/propos...,NaN
16,BrightEdge,https://www.linkedin.com/company/brightedge?re...,//brightedge.com/?ref=getlatka.com,(US),Jim Yu,http://twitter.com/brightedge?ref=getlatka.com,https://www.crunchbase.com/organization/bright...,https://www.facebook.com/seoplatform?ref=getla...
17,Celigo,https://www.linkedin.com/company/celigo-inc?re...,//celigo.com/?ref=getlatka.com,(US),Jan Arendtsz,https://twitter.com/celigoinc?ref=getlatka.com,https://www.crunchbase.com/organization/celigo...,https://www.facebook.com/CeligoInc/?ref=getlat...
18,Netcore Cloud,https://www.linkedin.com/company/netcore-cloud...,//netcorecloud.com/?ref=getlatka.com,(IN),Rajesh Jain,https://twitter.com/netcore_cloud?ref=getlatka...,https://www.crunchbase.com/organization/netcor...,https://www.facebook.com/NetcoreCloud/?ref=get...
19,Hootsuite,https://ca.linkedin.com/company/hootsuite?ref=...,//hootsuite.com/?ref=getlatka.com,(CA),Irina Novoselsky,https://twitter.com/hootsuite?ref=getlatka.com,https://www.crunchbase.com/organization/hootsu...,https://www.facebook.com/hootsuite?ref=getlatk...

In [54]:
df.to_csv('gelatka no1.csv',index=False)
df

,name,Company linkedIn,website url,company location,company founder,Company Twitter,Company Crunchbase,Company facebook
0,Nue.io,http://www.linkedin.com/company/nue-io?ref=get...,//nue.io/?ref=getlatka.com,United States,Mark Walker,NaN,NaN,NaN
1,briq,https://www.linkedin.com/company/briqhq/?ref=g...,//briq.com/?ref=getlatka.com,(US),Ron Goldshmidt,NaN,NaN,NaN
2,Arcads,https://www.linkedin.com/company/arcads-ai/?re...,//arcads.ai/?ref=getlatka.com,France,,NaN,NaN,NaN
3,BetterPic,NaN,//betterpic.io/?ref=getlatka.com,Estonia,,NaN,NaN,NaN
4,SubMagic,https://www.linkedin.com/company/submagic?ref=...,//submagic.co/?ref=getlatka.com,France,David Zitoun,NaN,NaN,NaN
5,Zapmail,https://www.linkedin.com/company/zapmail-ai/?r...,//zapmail.ai/?ref=getlatka.com,(US),Alan D'Souza,NaN,NaN,NaN
6,MarsX.dev,https://www.linkedin.com/company/marsx?ref=get...,//marsx.dev/?ref=getlatka.com,(US),John Rush,https://twitter.com/marsxdev?ref=getlatka.com,NaN,NaN
7,Cal AI,https://www.linkedin.com/company/cal-ai-app/?r...,//calai.app/?ref=getlatka.com,(US),Jake Castillo,NaN,NaN,NaN
8,Capacity,https://www.linkedin.com/company/teamcapacity?...,//capacity.com/?ref=getlatka.com,(US),David Karandish,NaN,https://www.crunchbase.com/organization/capaci...,NaN
9,TripleDart,https://www.linkedin.com/company/tripledart-di...,//tripledart.com/?ref=getlatka.com,(US),Shiyam Sunder,https://twitter.com/Tripledart_?ref=getlatka.com,NaN,NaN
10,Voxpopme,https://www.linkedin.com/company/voxpopme?ref=...,//voxpopme.com/?ref=getlatka.com,(US),Andrew Barraclough,NaN,https://www.crunchbase.com/organization/voxpop...,NaN
11,Pendo,https://www.linkedin.com/company/pendo-io/?ref...,//pendo.io/?ref=getlatka.com,(US),Todd Olson,https://twitter.com/pendoio?ref=getlatka.com,https://www.crunchbase.com/organization/pendo-...,https://www.facebook.com/Pendoio/?ref=getlatka...
12,Issuu,https://www.linkedin.com/company/issuu/?ref=ge...,//issuu.com/?ref=getlatka.com,(US),,NaN,https://www.crunchbase.com/organization/issuu?...,NaN
13,Ninety.io,https://www.linkedin.com/company/ninety-io?ref...,//ninety.io/?ref=getlatka.com,(US),Tim Weerasiri,NaN,https://www.crunchbase.com/organization/ninety...,NaN
14,Reveleer,https://www.linkedin.com/company/reveleer/?ref...,//reveleer.com/?ref=getlatka.com,(US),,NaN,https://www.crunchbase.com/organization/revele...,NaN
15,Proposify,https://www.linkedin.com/company/proposify/?re...,//proposify.com/?ref=getlatka.com,(CA),Kyle Racki,NaN,https://www.crunchbase.com/organization/propos...,NaN
16,BrightEdge,https://www.linkedin.com/company/brightedge?re...,//brightedge.com/?ref=getlatka.com,(US),Jim Yu,http://twitter.com/brightedge?ref=getlatka.com,https://www.crunchbase.com/organization/bright...,https://www.facebook.com/seoplatform?ref=getla...
17,Celigo,https://www.linkedin.com/company/celigo-inc?re...,//celigo.com/?ref=getlatka.com,(US),Jan Arendtsz,https://twitter.com/celigoinc?ref=getlatka.com,https://www.crunchbase.com/organization/celigo...,https://www.facebook.com/CeligoInc/?ref=getlat...
18,Netcore Cloud,https://www.linkedin.com/company/netcore-cloud...,//netcorecloud.com/?ref=getlatka.com,(IN),Rajesh Jain,https://twitter.com/netcore_cloud?ref=getlatka...,https://www.crunchbase.com/organization/netcor...,https://www.facebook.com/NetcoreCloud/?ref=get...
19,Hootsuite,https://ca.linkedin.com/company/hootsuite?ref=...,//hootsuite.com/?ref=getlatka.com,(CA),Irina Novoselsky,https://twitter.com/hootsuite?ref=getlatka.com,https://www.crunchbase.com/organization/hootsu...,https://www.facebook.com/hootsuite?ref=getlatk...

In [56]:
import pandas as pd
import time
from selenium import webdriver
from bs4 import BeautifulSoup

# WebDriver initialize karo
driver = webdriver.Chrome()

# URL jahan se data scrape karna hai
url = "https://getlatka.com/saas-companies?page=2"
driver.get(url)

# Page load hone ka intezaar karo
time.sleep(5)

# BeautifulSoup ke through page source ko parse karo
soup = BeautifulSoup(driver.page_source, "html.parser")

# Sabhi rows ko find karo (saare tr elements)
trs = soup.find_all("tr")

# Data store karne ke liye ek empty list
list_data = []

# Har row ko loop karke data extract karna
for tr in trs:
    # Har row mein saare td elements find karo
    tds = tr.find_all("td")
    
    # Agar row mein 2 se kam td elements hain, toh wo ya header ho sakta hai ya empty row ho sakti hai, skip karo
    if len(tds) < 2:
        continue

    dic = {}
    
    # Company name aur social media links ko extract karo
    links = tds[1].find_all("a")
    if links:
        dic["name"] = links[0].text  # Pehli link se company ka naam le lo
        for a in links[1:]:  # Baaki links ko loop karke extract karo
            key = a.get("aria-label", "")  # aria-label se key milti hai
            value = a.get("href", "")  # href se link milta hai
            if key and value:  # Agar key aur value dono hain, toh dictionary mein add karo
                dic[key] = value

    # Company location aur founder ki information extract karo
    dic["company location"] = tds[-2].text.strip()  # Last se second td mein location hoti hai
    dic["company founder"] = tds[-6].text.strip()  # Last se sixth td mein founder ka naam hota hai

    # Har company ka data list mein add karna
    list_data.append(dic)

# Data ko pandas DataFrame mein convert karo (optional)
df = pd.DataFrame(list_data)

# Data ko print karo
df

,name,Company linkedIn,Company Crunchbase,website url,company location,company founder,Company facebook,Company Twitter
0,Customer.io,https://www.linkedin.com/company/customer-io/?...,https://www.crunchbase.com/organization/custom...,//customer.io/?ref=getlatka.com,(US),Elizabeth Tse,NaN,NaN
1,Boomerang,https://www.linkedin.com/company/baydin?ref=ge...,NaN,//boomerangapp.com/?ref=getlatka.com,(US),Mike Chin,NaN,NaN
2,Retention.com,https://www.linkedin.com/company/retention-dot...,NaN,//retention.com/?ref=getlatka.com,(US),Keleigh Spinner,https://www.facebook.com/RetentionDotCom?ref=g...,https://twitter.com/Retentiondotcom?ref=getlat...
3,PAR Technology,https://www.linkedin.com/company/partechnology...,NaN,//partech.com/?ref=getlatka.com,(US),Savneet Singh,https://www.facebook.com/parpointofsale/?ref=g...,https://twitter.com/PAR_Tech?ref=getlatka.com
4,Craver,https://www.linkedin.com/company/craver-soluti...,NaN,//craverapp.com/?ref=getlatka.com,(CA),Amin Yazdani,https://www.facebook.com/craverapp/?ref=getlat...,https://x.com/craver_app_?ref=getlatka.com
5,GTMfund,https://www.linkedin.com/company/gtmfund/about...,NaN,//gtmfund.com/?ref=getlatka.com,(US),Sophie Buonassisi,NaN,NaN
6,Flowcase (formerly CV Partner),https://www.linkedin.com/company/cv-partner/?o...,NaN,//cvpartner.com/?ref=getlatka.com,(GB),Erling Linde,NaN,NaN
7,ActiveCampaign,https://www.linkedin.com/company/activecampaig...,https://www.crunchbase.com/organization/active...,//activecampaign.com/?ref=getlatka.com,(US),Jason VandeBoom,https://www.facebook.com/activecampaign?ref=ge...,https://twitter.com/ActiveCampaign?ref=getlatk...
8,GetDynasty,https://www.linkedin.com/company/getdynasty/?r...,NaN,//getdynasty.com/?ref=getlatka.com,(US),Alessandro Chesser,https://www.facebook.com/getdynastycom?ref=get...,https://twitter.com/getdynasty_com?ref=getlatk...
9,Beehiiv,https://www.linkedin.com/company/beehiiv/?ref=...,NaN,//beehiiv.com/?ref=getlatka.com,United States,Tyler Denk,NaN,https://twitter.com/beehiiv/?ref=getlatka.com
10,SaaS Group,https://www.linkedin.com/company/saas-group/?r...,NaN,//saas.group/?ref=getlatka.com,(US),Facundo Farias,NaN,https://twitter.com/SaaS_group?ref=getlatka.com
11,Flodesk,https://www.linkedin.com/company/flodesk?ref=g...,NaN,//flodesk.com/?ref=getlatka.com,(US),Rebecca Shostak,NaN,https://twitter.com/?ref=getlatka.com
12,Muck Rack,https://www.linkedin.com/company/muckrack/?ref...,https://www.crunchbase.com/organization/muckra...,//muckrack.com/?ref=getlatka.com,(US),Gregory Galant,NaN,NaN
13,Younium,https://www.linkedin.com/company/younium?ref=g...,https://www.crunchbase.com/organization/youniu...,//younium.com/?ref=getlatka.com,Sweden,Niclas Lilja,NaN,https://twitter.com/younium?ref=getlatka.com
14,LMS 365,https://www.linkedin.com/company/lms365/?ref=g...,NaN,//lms365.com/?ref=getlatka.com,Denmark,Maria Herrejon Skoglund,https://www.facebook.com/lms365?ref=getlatka.com,https://twitter.com/lms365?ref=getlatka.com
15,SEMrush,https://www.linkedin.com/company/semrush/?ref=...,https://www.crunchbase.com/organization/semrus...,//semrush.com/?ref=getlatka.com,(US),Eugene Levin,https://www.facebook.com/SEMrush?ref=getlatka.com,https://twitter.com/semrush?ref=getlatka.com
16,Crossbeam,https://www.linkedin.com/company/getcrossbeam?...,https://www.crunchbase.com/organization/crossb...,//crossbeam.com/?ref=getlatka.com,(US),Bob Moore,NaN,NaN
17,Typeform,https://www.linkedin.com/company/typeform-com?...,https://www.crunchbase.com/organization/typefo...,//typeform.com/?ref=getlatka.com,Spain,Joaquim Lecha,https://www.facebook.com/typeform/?ref=getlatk...,https://twitter.com/typeform/?ref=getlatka.com
18,Ahrefs,https://www.linkedin.com/company/ahrefs/?ref=g...,https://www.crunchbase.com/organization/ahrefs...,//ahrefs.com/?ref=getlatka.com,Singapore,Dmytro Gerasymenko,https://www.facebook.com/Ahrefs/?ref=getlatka.com,https://twitter.com/ahrefs?ref=getlatka.com
19,Goldcast,https://www.linkedin.com/company/goldcastevent...,https://www.crunchbase.com/organization/goldca...,//goldcast.io/?ref=getlatka.com,(US),Palash Soni,NaN,https://twitter.com/goldcast?ref=getlatka.com

In [57]:
df.to_csv('gelatka no2.csv',index=False)
df

,name,Company linkedIn,Company Crunchbase,website url,company location,company founder,Company facebook,Company Twitter
0,Customer.io,https://www.linkedin.com/company/customer-io/?...,https://www.crunchbase.com/organization/custom...,//customer.io/?ref=getlatka.com,(US),Elizabeth Tse,NaN,NaN
1,Boomerang,https://www.linkedin.com/company/baydin?ref=ge...,NaN,//boomerangapp.com/?ref=getlatka.com,(US),Mike Chin,NaN,NaN
2,Retention.com,https://www.linkedin.com/company/retention-dot...,NaN,//retention.com/?ref=getlatka.com,(US),Keleigh Spinner,https://www.facebook.com/RetentionDotCom?ref=g...,https://twitter.com/Retentiondotcom?ref=getlat...
3,PAR Technology,https://www.linkedin.com/company/partechnology...,NaN,//partech.com/?ref=getlatka.com,(US),Savneet Singh,https://www.facebook.com/parpointofsale/?ref=g...,https://twitter.com/PAR_Tech?ref=getlatka.com
4,Craver,https://www.linkedin.com/company/craver-soluti...,NaN,//craverapp.com/?ref=getlatka.com,(CA),Amin Yazdani,https://www.facebook.com/craverapp/?ref=getlat...,https://x.com/craver_app_?ref=getlatka.com
5,GTMfund,https://www.linkedin.com/company/gtmfund/about...,NaN,//gtmfund.com/?ref=getlatka.com,(US),Sophie Buonassisi,NaN,NaN
6,Flowcase (formerly CV Partner),https://www.linkedin.com/company/cv-partner/?o...,NaN,//cvpartner.com/?ref=getlatka.com,(GB),Erling Linde,NaN,NaN
7,ActiveCampaign,https://www.linkedin.com/company/activecampaig...,https://www.crunchbase.com/organization/active...,//activecampaign.com/?ref=getlatka.com,(US),Jason VandeBoom,https://www.facebook.com/activecampaign?ref=ge...,https://twitter.com/ActiveCampaign?ref=getlatk...
8,GetDynasty,https://www.linkedin.com/company/getdynasty/?r...,NaN,//getdynasty.com/?ref=getlatka.com,(US),Alessandro Chesser,https://www.facebook.com/getdynastycom?ref=get...,https://twitter.com/getdynasty_com?ref=getlatk...
9,Beehiiv,https://www.linkedin.com/company/beehiiv/?ref=...,NaN,//beehiiv.com/?ref=getlatka.com,United States,Tyler Denk,NaN,https://twitter.com/beehiiv/?ref=getlatka.com
10,SaaS Group,https://www.linkedin.com/company/saas-group/?r...,NaN,//saas.group/?ref=getlatka.com,(US),Facundo Farias,NaN,https://twitter.com/SaaS_group?ref=getlatka.com
11,Flodesk,https://www.linkedin.com/company/flodesk?ref=g...,NaN,//flodesk.com/?ref=getlatka.com,(US),Rebecca Shostak,NaN,https://twitter.com/?ref=getlatka.com
12,Muck Rack,https://www.linkedin.com/company/muckrack/?ref...,https://www.crunchbase.com/organization/muckra...,//muckrack.com/?ref=getlatka.com,(US),Gregory Galant,NaN,NaN
13,Younium,https://www.linkedin.com/company/younium?ref=g...,https://www.crunchbase.com/organization/youniu...,//younium.com/?ref=getlatka.com,Sweden,Niclas Lilja,NaN,https://twitter.com/younium?ref=getlatka.com
14,LMS 365,https://www.linkedin.com/company/lms365/?ref=g...,NaN,//lms365.com/?ref=getlatka.com,Denmark,Maria Herrejon Skoglund,https://www.facebook.com/lms365?ref=getlatka.com,https://twitter.com/lms365?ref=getlatka.com
15,SEMrush,https://www.linkedin.com/company/semrush/?ref=...,https://www.crunchbase.com/organization/semrus...,//semrush.com/?ref=getlatka.com,(US),Eugene Levin,https://www.facebook.com/SEMrush?ref=getlatka.com,https://twitter.com/semrush?ref=getlatka.com
16,Crossbeam,https://www.linkedin.com/company/getcrossbeam?...,https://www.crunchbase.com/organization/crossb...,//crossbeam.com/?ref=getlatka.com,(US),Bob Moore,NaN,NaN
17,Typeform,https://www.linkedin.com/company/typeform-com?...,https://www.crunchbase.com/organization/typefo...,//typeform.com/?ref=getlatka.com,Spain,Joaquim Lecha,https://www.facebook.com/typeform/?ref=getlatk...,https://twitter.com/typeform/?ref=getlatka.com
18,Ahrefs,https://www.linkedin.com/company/ahrefs/?ref=g...,https://www.crunchbase.com/organization/ahrefs...,//ahrefs.com/?ref=getlatka.com,Singapore,Dmytro Gerasymenko,https://www.facebook.com/Ahrefs/?ref=getlatka.com,https://twitter.com/ahrefs?ref=getlatka.com
19,Goldcast,https://www.linkedin.com/company/goldcastevent...,https://www.crunchbase.com/organization/goldca...,//goldcast.io/?ref=getlatka.com,(US),Palash Soni,NaN,https://twitter.com/goldcast?ref=getlatka.com

In [25]:
import pandas as pd
import time
from selenium import webdriver
from bs4 import BeautifulSoup

# WebDriver initialize karo
driver = webdriver.Edge()

# URL jahan se data scrape karna hai
url = "https://getlatka.com/saas-companies?page="

driver.get(url)
time.sleep(5)
try:
    checkbox = driver.find_element_by_xpath("//div[@class='recaptcha-checkbox-checkmark']")
    checkbox.click()
    time.sleep(2)
except Exception as e:
    print("No CAPTCHA checkbox found or could not be clicked:", e)




driver.find_element("xpath","//button[@class='newsletter-popup__close']").click()
time.sleep(7)

# Page load hone ka intezaar karo


# BeautifulSoup ke through page source ko parse karo
soup = BeautifulSoup(driver.page_source, "html.parser")

# Sabhi rows ko find karo (saare tr elements)
trs = soup.find_all("tr")
for i in range(1,6):
    # driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    # time.sleep(2)
    driver.find_element('xpath'"//div[@id='__next']/div[2]/div[6]/div/a/span").click()

    time.sleep(5)
    # driver.find_element("xpath","//button[@class='newsletter-popup__close']").click()
    # time.sleep(7)

try:
    checkbox = driver.find_element_by_xpath("//div[@class='recaptcha-checkbox-checkmark']")
    checkbox.click()
    time.sleep(2)
except Exception as e:
    print("No CAPTCHA checkbox found or could not be clicked:", e)

    # driver.find_element('xpath',"//div[@id='tgnx8']").click()
    # time.sleep(5)
    
    driver.find_element("xpath","//button[@class='newsletter-popup__close']").click()
    time.sleep(7)
    
    soup = BeautifulSoup(driver.page_source, "html.parser")

# Data store karne ke liye ek empty list
list_data = []

# Har row ko loop karke data extract karna
for tr in trs:
    # Har row mein saare td elements find karo
    tds = tr.find_all("td")
    
    # Agar row mein 2 se kam td elements hain, toh wo ya header ho sakta hai ya empty row ho sakti hai, skip karo
    if len(tds) < 2:
        continue

    dic = {}
    
    # Company name aur social media links ko extract karo
    links = tds[1].find_all("a")
    if links:
        dic["name"] = links[0].text  # Pehli link se company ka naam le lo
        for a in links[1:]:  # Baaki links ko loop karke extract karo
            key = a.get("aria-label", "")  # aria-label se key milti hai
            value = a.get("href", "")  # href se link milta hai
            if key and value:  # Agar key aur value dono hain, toh dictionary mein add karo
                dic[key] = value

    # Company location aur founder ki information extract karo
    dic["company location"] = tds[-2].text.strip()  # Last se second td mein location hoti hai
    dic["company founder"] = tds[-6].text.strip()  # Last se sixth td mein founder ka naam hota hai

    # Har company ka data list mein add karna
    list_data.append(dic)

# Data ko pandas DataFrame mein convert karo (optional)
df = pd.DataFrame(list_data)

# Data ko print karo
df

No CAPTCHA checkbox found or could not be clicked: 'WebDriver' object has no attribute 'find_element_by_xpath'

InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: MicrosoftEdge=143.0.3650.75)
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff717bb87c5
	0x7ff717b28e34
	0x7ff717f13222
	0x7ff717982497
	0x7ff717982ffb
	0x7ff7179be917
	0x7ff71797a2e5
	0x7ff7179bc8de
	0x7ff71797982a
	0x7ff717978b33
	0x7ff717979653
	0x7ff717a622e4
	0x7ff717a7109c
	0x7ff717a6ac7f
	0x7ff717c49b27
	0x7ff717b34696
	0x7ff717b2eaa4
	0x7ff717b2ebe9
	0x7ff717b22cad
	0x7ff9a4ad7374
	0x7ff9a6abcc91

In [9]:
driver.find_element("xpath","//button[@class='newsletter-popup__close']").click()