In [3]:
# Method 2: Saving data into list

import requests
from bs4 import BeautifulSoup
header={
    "User-Agent": "IsraBot"
}

r=requests.get("https://en.wikipedia.org/wiki/Python",headers=header)
soup=BeautifulSoup(r.text,'html.parser')

sub_headings=soup.find_all('div',class_='mw-heading mw-heading2')


var_list_of_dict = []

for i in sub_headings:
    var=i.find('h2')
    if var:
        
        
        ul=i.find_next_sibling('ul')
        if ul:
            for li in ul.find_all('li'):
                # text 
                text = li.get_text(strip=True)
                #url links 
                link_tag = li.find('a')["href"]
                # print(f"  - {text} ({link_tag})")

                var_list_of_dict.append(
                    {
                    "sub_header": var.text,
                    "data_point": text,
                    "url": link_tag
                    }
                )
                
                print(var_list_of_dict)

[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}, {'sub_header': 'Media', 'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh', 'url': '/wiki/Python_(film)'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}, {'sub_header': 'Media', 'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh', 'url': '/wiki/Python_(film)'}, {'sub_header': 'Media', 'data_point': "Monty Pythonor the Pythons, a British comedy groupPython (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Monty_Python'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}, {'sub_header': 'Media', 'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh', 'url': '/wiki/Python_(film)'}, {'sub_header': 'Media', 'data_point': "Monty Pythonor the Pythons, a British comedy groupPython (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Monty_Python'}, {'sub_header': 'Media', 'data_point': "Python (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Python_(Monty)_Pictures'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}, {'sub_header': 'Media', 'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh', 'url': '/wiki/Python_(film)'}, {'sub_header': 'Media', 'data_point': "Monty Pythonor the Pythons, a British comedy groupPython (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Monty_Python'}, {'sub_header': 'Media', 'data_point': "Python (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Python_(Monty)_Pictures'}, {'sub_header': 'Media', 'data_point': 'Python, a work written by philosopherTimon of Phlius', 'url': '/wiki/Timon_of_Phlius'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}, {'sub_header': 'Media', 'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh', 'url': '/wiki/Python_(film)'}, {'sub_header': 'Media', 'data_point': "Monty Pythonor the Pythons, a British comedy groupPython (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Monty_Python'}, {'sub_header': 'Media', 'data_point': "Python (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Python_(Monty)_Pictures'}, {'sub_header': 'Media', 'data_point': 'Python, a work written by philosopherTimon of Phlius', 'url': '/wiki/Timon_of_Phlius'}, {'sub_header': 'People', 'data_point': 'Python of Aenus(4th-century BCE), student of Plato', 'url': '/wiki/Python_of_Aenus'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}, {'sub_header': 'Media', 'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh', 'url': '/wiki/Python_(film)'}, {'sub_header': 'Media', 'data_point': "Monty Pythonor the Pythons, a British comedy groupPython (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Monty_Python'}, {'sub_header': 'Media', 'data_point': "Python (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Python_(Monty)_Pictures'}, {'sub_header': 'Media', 'data_point': 'Python, a work written by philosopherTimon of Phlius', 'url': '/wiki/Timon_of_Phlius'}, {'sub_header': 'People', 'data_point': 'Python of Aenus(4th-century BCE), student of Plato', 'url': '/wiki/Python_of_Aenus'}, {'sub_header': 'People', 'data_point': 'Python (painter)(ca. 360–320 BCE), vase painter in Poseidonia', 'url': '/wiki/Python_(painter)'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}, {'sub_header': 'Media', 'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh', 'url': '/wiki/Python_(film)'}, {'sub_header': 'Media', 'data_point': "Monty Pythonor the Pythons, a British comedy groupPython (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Monty_Python'}, {'sub_header': 'Media', 'data_point': "Python (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Python_(Monty)_Pictures'}, {'sub_header': 'Media', 'data_point': 'Python, a work written by philosopherTimon of Phlius', 'url': '/wiki/Timon_of_Phlius'}, {'sub_header': 'People', 'data_point': 'Python of Aenus(4th-century BCE), student of Plato', 'url': '/wiki/Python_of_Aenus'}, {'sub_header': 'People', 'data_point': 'Python (painter)(ca. 360–320 BCE), vase painter in Poseidonia', 'url': '/wiki/Python_(painter)'}, {'sub_header': 'People', 'data_point': 'Python of Byzantium(4th-century BCE), orator, diplomat of Philip II of Macedon', 'url': '/wiki/Python_of_Byzantium'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}, {'sub_header': 'Media', 'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh', 'url': '/wiki/Python_(film)'}, {'sub_header': 'Media', 'data_point': "Monty Pythonor the Pythons, a British comedy groupPython (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Monty_Python'}, {'sub_header': 'Media', 'data_point': "Python (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Python_(Monty)_Pictures'}, {'sub_header': 'Media', 'data_point': 'Python, a work written by philosopherTimon of Phlius', 'url': '/wiki/Timon_of_Phlius'}, {'sub_header': 'People', 'data_point': 'Python of Aenus(4th-century BCE), student of Plato', 'url': '/wiki/Python_of_Aenus'}, {'sub_header': 'People', 'data_point': 'Python (painter)(ca. 360–320 BCE), vase painter in Poseidonia', 'url': '/wiki/Python_(painter)'}, {'sub_header': 'People', 'data_point': 'Python of Byzantium(4th-century BCE), orator, diplomat of Philip II of Macedon', 'url': '/wiki/Python_of_Byzantium'}, {'sub_header': 'People', 'data_point': 'Python of Catana, poet who accompanied Alexander the Great', 'url': '/wiki/Python_of_Catana'}]
[{'sub_header': 'Snakes', 'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Pythonidae'}, {'sub_header': 'Snakes', 'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia', 'url': '/wiki/Python_(genus)'}, {'sub_header': 'Snakes', 'data_point': 'Python (mythology), a mythical serpent', 'url': '/wiki/Python_(mythology)'}, {'sub_header': 'Computing', 'data_point': 'Python (programming language), a widely used high-level programming language', 'url': '/wiki/Python_(programming_language)'}, {'sub_header': 'Computing', 'data_point': 'Python, a native code compiler forCMU Common Lisp', 'url': '/wiki/CMU_Common_Lisp'}, {'sub_header': 'Computing', 'data_point': 'Python, the internal project name for thePERQ 3computer workstation', 'url': '/wiki/PERQ#PERQ_3'}, {'sub_header': 'Media', 'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh', 'url': '/wiki/Python_(film)'}, {'sub_header': 'Media', 'data_point': "Monty Pythonor the Pythons, a British comedy groupPython (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Monty_Python'}, {'sub_header': 'Media', 'data_point': "Python (Monty) Pictures, a company owned by the troupe's surviving members", 'url': '/wiki/Python_(Monty)_Pictures'}, {'sub_header': 'Media', 'data_point': 'Python, a work written by philosopherTimon of Phlius', 'url': '/wiki/Timon_of_Phlius'}, {'sub_header': 'People', 'data_point': 'Python of Aenus(4th-century BCE), student of Plato', 'url': '/wiki/Python_of_Aenus'}, {'sub_header': 'People', 'data_point': 'Python (painter)(ca. 360–320 BCE), vase painter in Poseidonia', 'url': '/wiki/Python_(painter)'}, {'sub_header': 'People', 'data_point': 'Python of Byzantium(4th-century BCE), orator, diplomat of Philip II of Macedon', 'url': '/wiki/Python_of_Byzantium'}, {'sub_header': 'People', 'data_point': 'Python of Catana, poet who accompanied Alexander the Great', 'url': '/wiki/Python_of_Catana'}, {'sub_header': 'People', 'data_point': 'Python Anghelo(1954–2014), Romanian graphic artist', 'url': '/wiki/Python_Anghelo'}]

In [4]:
var_list_of_dict

[{'sub_header': 'Snakes',
  'data_point': 'Pythonidae, a family of nonvenomous snakes found in Africa, Asia, and AustraliaPython(genus), a genus of Pythonidae found in Africa and Asia',
  'url': '/wiki/Pythonidae'},
 {'sub_header': 'Snakes',
  'data_point': 'Python(genus), a genus of Pythonidae found in Africa and Asia',
  'url': '/wiki/Python_(genus)'},
 {'sub_header': 'Snakes',
  'data_point': 'Python (mythology), a mythical serpent',
  'url': '/wiki/Python_(mythology)'},
 {'sub_header': 'Computing',
  'data_point': 'Python (programming language), a widely used high-level programming language',
  'url': '/wiki/Python_(programming_language)'},
 {'sub_header': 'Computing',
  'data_point': 'Python, a native code compiler forCMU Common Lisp',
  'url': '/wiki/CMU_Common_Lisp'},
 {'sub_header': 'Computing',
  'data_point': 'Python, the internal project name for thePERQ 3computer workstation',
  'url': '/wiki/PERQ#PERQ_3'},
 {'sub_header': 'Media',
  'data_point': 'Python(film), a 2000 horror film by Richard Clabaugh',
  'url': '/wiki/Python_(film)'},
 {'sub_header': 'Media',
  'data_point': "Monty Pythonor the Pythons, a British comedy groupPython (Monty) Pictures, a company owned by the troupe's surviving members",
  'url': '/wiki/Monty_Python'},
 {'sub_header': 'Media',
  'data_point': "Python (Monty) Pictures, a company owned by the troupe's surviving members",
  'url': '/wiki/Python_(Monty)_Pictures'},
 {'sub_header': 'Media',
  'data_point': 'Python, a work written by philosopherTimon of Phlius',
  'url': '/wiki/Timon_of_Phlius'},
 {'sub_header': 'People',
  'data_point': 'Python of Aenus(4th-century BCE), student of Plato',
  'url': '/wiki/Python_of_Aenus'},
 {'sub_header': 'People',
  'data_point': 'Python (painter)(ca. 360–320 BCE), vase painter in Poseidonia',
  'url': '/wiki/Python_(painter)'},
 {'sub_header': 'People',
  'data_point': 'Python of Byzantium(4th-century BCE), orator, diplomat of Philip II of Macedon',
  'url': '/wiki/Python_of_Byzantium'},
 {'sub_header': 'People',
  'data_point': 'Python of Catana, poet who accompanied Alexander the Great',
  'url': '/wiki/Python_of_Catana'},
 {'sub_header': 'People',
  'data_point': 'Python Anghelo(1954–2014), Romanian graphic artist',
  'url': '/wiki/Python_Anghelo'},
 {'sub_header': 'Roller coasters',
  'data_point': 'Python (Efteling), a roller coaster in the Netherlands',
  'url': '/wiki/Python_(Efteling)'},
 {'sub_header': 'Roller coasters',
  'data_point': 'Python (Busch Gardens Tampa Bay), a defunct roller coaster',
  'url': '/wiki/Python_(Busch_Gardens_Tampa_Bay)'},
 {'sub_header': 'Roller coasters',
  'data_point': 'Python (Coney Island, Cincinnati, Ohio), a steel roller coaster',
  'url': '/wiki/Python_(Coney_Island,_Cincinnati,_Ohio)'},
 {'sub_header': 'Vehicles',
  'data_point': 'Python (automobile maker), an Australian car company',
  'url': '/wiki/Python_(automobile_maker)'},
 {'sub_header': 'Vehicles',
  'data_point': 'Python (Ford prototype), a Ford prototype sports car',
  'url': '/wiki/Python_(Ford_prototype)'},
 {'sub_header': 'Weaponry and war',
  'data_point': 'Python (missile), a series of Israeli air-to-air missiles',
  'url': '/wiki/Python_(missile)'},
 {'sub_header': 'Weaponry and war',
  'data_point': 'Python (nuclear primary), a gas-boosted fission primary used in thermonuclear weapons',
  'url': '/wiki/Python_(nuclear_primary)'},
 {'sub_header': 'Weaponry and war',
  'data_point': 'Colt Python, a revolver',
  'url': '/wiki/Colt_Python'},
 {'sub_header': 'Weaponry and war',
  'data_point': 'Python (codename), a British nuclear war contingency plan',
  'url': '/wiki/Python_(codename)'},
 {'sub_header': 'Weaponry and war',
  'data_point': 'Operation Python, Indian naval operation during the Indo-Pakistani War of 1971',
  'url': '/wiki/Operation_Python'},
 {'sub_header': 'See also',
  'data_point': 'All pages with titles beginning withPython',
  'url': '/wiki/Special:PrefixIndex/Python'},
 {'sub_header': 'See also',
  'data_point': 'All pages with titles containingPython',
  'url': '/wiki/Special:Search/intitle:%22Python%22'},
 {'sub_header': 'See also',
  'data_point': 'Pithon, a commune in northern France',
  'url': '/wiki/Pithon'},
 {'sub_header': 'See also',
  'data_point': 'Pyton, a Norwegian magazine',
  'url': '/wiki/Pyton'}]

In [ ]:
import pandas

,sub_header,data_point,url
0,Snakes,"Pythonidae, a family of nonvenomous snakes fou...",/wiki/Pythonidae
1,Snakes,"Python(genus), a genus of Pythonidae found in ...",/wiki/Python_(genus)
2,Snakes,"Python (mythology), a mythical serpent",/wiki/Python_(mythology)
3,Computing,"Python (programming language), a widely used h...",/wiki/Python_(programming_language)
4,Computing,"Python, a native code compiler forCMU Common Lisp",/wiki/CMU_Common_Lisp
5,Computing,"Python, the internal project name for thePERQ ...",/wiki/PERQ#PERQ_3
6,Media,"Python(film), a 2000 horror film by Richard Cl...",/wiki/Python_(film)
7,Media,"Monty Pythonor the Pythons, a British comedy g...",/wiki/Monty_Python
8,Media,"Python (Monty) Pictures, a company owned by th...",/wiki/Python_(Monty)_Pictures
9,Media,"Python, a work written by philosopherTimon of ...",/wiki/Timon_of_Phlius
10,People,"Python of Aenus(4th-century BCE), student of P...",/wiki/Python_of_Aenus
11,People,"Python (painter)(ca. 360–320 BCE), vase painte...",/wiki/Python_(painter)
12,People,"Python of Byzantium(4th-century BCE), orator, ...",/wiki/Python_of_Byzantium
13,People,"Python of Catana, poet who accompanied Alexand...",/wiki/Python_of_Catana
14,People,"Python Anghelo(1954–2014), Romanian graphic ar...",/wiki/Python_Anghelo
15,Roller coasters,"Python (Efteling), a roller coaster in the Net...",/wiki/Python_(Efteling)
16,Roller coasters,"Python (Busch Gardens Tampa Bay), a defunct ro...",/wiki/Python_(Busch_Gardens_Tampa_Bay)
17,Roller coasters,"Python (Coney Island, Cincinnati, Ohio), a ste...","/wiki/Python_(Coney_Island,_Cincinnati,_Ohio)"
18,Vehicles,"Python (automobile maker), an Australian car c...",/wiki/Python_(automobile_maker)
19,Vehicles,"Python (Ford prototype), a Ford prototype spor...",/wiki/Python_(Ford_prototype)
20,Weaponry and war,"Python (missile), a series of Israeli air-to-a...",/wiki/Python_(missile)
21,Weaponry and war,"Python (nuclear primary), a gas-boosted fissio...",/wiki/Python_(nuclear_primary)
22,Weaponry and war,"Colt Python, a revolver",/wiki/Colt_Python
23,Weaponry and war,"Python (codename), a British nuclear war conti...",/wiki/Python_(codename)
24,Weaponry and war,"Operation Python, Indian naval operation durin...",/wiki/Operation_Python
25,See also,All pages with titles beginning withPython,/wiki/Special:PrefixIndex/Python
26,See also,All pages with titles containingPython,/wiki/Special:Search/intitle:%22Python%22
27,See also,"Pithon, a commune in northern France",/wiki/Pithon
28,See also,"Pyton, a Norwegian magazine",/wiki/Pyton

In [ ]:



student_data = [
    {
        "Name": "sheraz",
        "Roll number": "xyz",
        "Father_name": "muhammad",
        "class": "python"
    },
    {
        "Name": "amjad",
        "Roll number": "124231",
        "Father_name": "ali",
        "class": "python"
    },
    {
        "Name": "shehroz",
        "Roll number": "890",
        "Father_name": "panda",
        "class": "python"
    },
    {
        "Name": "Rahil",
        "Roll number": "0001",
        "Father_name": "Rahul",
        "class": "python"
    },
    {
        "Name": "khitab",
        "Roll number": "0004",
        "Father_name": "khitab ali",
        "class": "python"
    },
    {
        "Name": "umar",
        "Roll number": "0003",
        "Father_name": "umar bin khatab",
        "class": "python"
    },
    {
        "Name": "asim",
        "Roll number": "0004",
        "Father_name": "owliver",
        "class": "python"
    },
    {
        "Name": "khani",
        "Roll number": "0005",
        "Father_name": "faroz khan",
        "class": "python"
    }
]

print(student_data)

[{'Name': 'sheraz', 'Roll number': 'xyz', 'Father_name': 'muhammad', 'class': 'python'}, {'Name': 'amjad', 'Roll number': '124231', 'Father_name': 'ali', 'class': 'python'}, {'Name': 'shehroz', 'Roll number': '890', 'Father_name': 'panda', 'class': 'python'}, {'Name': 'Rahil', 'Roll number': '0001', 'Father_name': 'Rahul', 'class': 'python'}, {'Name': 'khitab', 'Roll number': '0004', 'Father_name': 'khitab ali', 'class': 'python'}, {'Name': 'umar', 'Roll number': '0003', 'Father_name': 'umar bin khatab', 'class': 'python'}, {'Name': 'asim', 'Roll number': '0004', 'Father_name': 'owliver', 'class': 'python'}, {'Name': 'khani', 'Roll number': '0005', 'Father_name': 'faroz khan', 'class': 'python'}]

In [14]:
df = pd.DataFrame(student_data)
df

      Name Roll number      Father_name   class
0   sheraz         xyz         muhammad  python
1    amjad      124231              ali  python
2  shehroz         890            panda  python
3    Rahil        0001            Rahul  python
4   khitab        0004       khitab ali  python
5     umar        0003  umar bin khatab  python
6     asim        0004          owliver  python
7    khani        0005       faroz khan  python

In [15]:
df.to_csv("student_info.csv",index=False)

In [ ]:
student_data = [
    {
        "Name": "sheraz",
        "Roll number": "xyz",
        "Father_name": "muhammad",
        "class": "python"
    },
    {
        "Name": "amjad",
        "Roll number": "124231",
        "Father_name": "ali",
        "class": "python"
    },
    {
        "Name": "shehroz",
        "Roll number": "890",
        "Father_name": "panda",
        "class": "python"
    },
    {
        "Name": "Rahil",
        "Roll number": "0001",
        "Father_name": "Rahul",
        "class": "python"
    },
    {
        "Name": "khitab",
        "Roll number": "0004",
        "Father_name": "khitab ali",
        "class": "python"
    },
    {
        "Name": "umar",
        "Roll number": "0003",
        "Father_name": "umar bin khatab",
        "class": "python"
    },
    {
        "Name": "asim",
        "Roll number": "0004",
        "Father_name": "owliver",
        "class": "python"
    },
    {
        "Name": "khani",
        "Roll number": "0005",
        "Father_name": "faroz khan",
        "class": "python"
    }
]

# 🔹 Take user input
name = input("Enter student name: ")
roll = input("Enter roll number: ")
father = input("Enter father name: ")
student_class = input("Enter class: ")

AttributeError: 'DataFrame' object has no attribute 'append'

In [23]:
df = pd.DataFrame(student_data)
df

      Name Roll number      Father_name   class
0   sheraz         xyz         muhammad  python
1    amjad      124231              ali  python
2  shehroz         890            panda  python
3    Rahil        0001            Rahul  python
4   khitab        0004       khitab ali  python
5     umar        0003  umar bin khatab  python
6     asim        0004          owliver  python
7    khani        0005       faroz khan  python