# 5. https://www.scrapethissite.com/pages/simple/ (coutry_name, Capital, Population, Area)

In [4]:
# from urllib.request import urlopen
import requests
from bs4 import BeautifulSoup
import re


header={
    "User-Agent": "Baiduspider"
}

html = requests.get('https://www.scrapethissite.com/pages/simple/',headers=header)
# html = requests.get('https://www.imdb.com/chart/top/')

html.status_code

200

In [5]:
soup = BeautifulSoup(html.text, "html")
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping
  </title>
  <link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
  <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
  <link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
  <meta content="noindex" name="robots"/>
  <link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
 </head>
 <body>
  <nav id="site-nav">
   <div class="container">
    <div class="col-md-12">
     <ul class="nav nav-tabs">
      <li id="nav-homepage">
       <a class="nav-link hidden-sm hidden-xs" href="/">
        <img id="nav-logo" src="/static/images/scraper-icon.png"/>
        Scrape This Site
       </a>
      </li>
      <li id="nav-sandbox">
       <a class="nav-link" href="/pages/">
        <i class="glyphicon glyphicon-console hidden-sm hidden-xs">
        </i>
        Sandbox
       </a>
      </li>
      <li id="nav-lessons">
       <a class="nav-link" href="/lessons/">
        <i class="glyphicon glyphicon-education hidden-sm hidden-xs">
        </i>
        Lessons
       </a>
      </li>
      <li id="nav-faq">
       <a class="nav-link" href="/faq/">
        <i class="glyphicon glyphicon-flag hidden-sm hidden-xs">
        </i>
        FAQ
       </a>
      </li>
      <li class="pull-right" id="nav-login">
       <a class="nav-link" href="/login/">
        Login
       </a>
      </li>
     </ul>
    </div>
   </div>
  </nav>
  <script type="text/javascript">
   var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
  </script>
  <div id="page">
   <section id="countries">
    <div class="container">
     <div class="row">
      <div class="col-md-12">
       <h1>
        Countries of the World: A Simple Example
        <small>
         250 items
        </small>
       </h1>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-12">
       <p class="lead">
        A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-6">
       <p>
        <i class="glyphicon glyphicon-education">
        </i>
        There are
        <a href="/lessons/">
         4 video lessons
        </a>
        that show you how to scrape this page.
       </p>
       <hr/>
      </div>
      <div class="col-md-6 text-right">
       <p>
        Data via
        <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">
         http://peric.github.io/GetCountries/
        </a>
       </p>
       <hr/>
      </div>
     </div>
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ad">
        </i>
        Andorra
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Andorra la Vella
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         84000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         468.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ae">
        </i>
        United Arab Emirates
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Abu Dhabi
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         4975593
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         82880.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-af">
        </i>
        Afghanistan
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Kabul
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         29121286
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         647500.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ag">
        </i>
        Antigua and Barbuda
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         St. John's
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         86754
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         443.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ai">
        </i>
        Anguilla
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         The Valley
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         13254
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         102.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-al">
        </i>
        Albania
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Tirana
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         2986952
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         28748.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-am">
        </i>
        Armenia
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Yerevan
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         2968000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         29800.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ao">
        </i>
        Angola
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Luanda
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         13068161
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         1246700.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-aq">
        </i>
        Antarctica
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         None
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         0
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         1.4E7
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ar">
        </i>
        Argentina
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Buenos Aires
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         41343201
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         2766890.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-as">
        </i>
        American Samoa
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Pago Pago
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         57881
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         199.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-at">
        </i>
        Austria
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Vienna
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         8205000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         83858.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-au">
        </i>
        Australia
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Canberra
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         21515754
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         7686850.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-aw">
        </i>
        Aruba
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Oranjestad
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         71566
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         193.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ax">
        </i>
        Åland
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Mariehamn
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         26711
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         1580.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-az">
        </i>
        Azerbaijan
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Baku
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         8303512
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         86600.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-ba">
        </i>
        Bosnia and Herzegovina
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Sarajevo
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         4590000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         51129.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-bb">
        </i>
        Barbados
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Bridgetown
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         285653
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         431.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-bd">
        </i>
        Bangladesh
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Dhaka
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         156118464
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         144000.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-be">
        </i>
        Belgium
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Brussels
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         10403000
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         30510.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-bf">
        </i>
        Burkina Faso
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Ouagadougou
        </span>
        <br/>
        <strong>
         Population:
        </strong>
        <span class="country-population">
         16241811
        </span>
        <br/>
        <strong>
         Area (km
         <sup>
          2
         </sup>
         ):
        </strong>
        <span class="country-area">
         274200.0
        </span>
        <br/>
       </div>
      </div>
      <!--.col-->
     </div>
     <!--.row-->
     <div class="row">
      <div class="col-md-4 country">
       <h3 class="country-name">
        <i class="flag-icon flag-icon-bg">
        </i>
        Bulgaria
       </h3>
       <div class="country-info">
        <strong>
         Capital:
        </strong>
        <span class="country-capital">
         Sofia
        </span>
        <br/>
        <strong>
         Population:

# Andorra

In [56]:
divs = soup.find_all("div",class_="col-md-4 country")
print(divs)
len(divs)

[<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bw"></i>
                            Botswana
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
<strong>Population:</strong> <span class="country-population">2029307</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-by"></i>
                            Belarus
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
<strong>Population:</strong> <span class="country-population">9685000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bz"></i>
                            Belize
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
<strong>Population:</strong> <span class="country-population">314522</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ca"></i>
                            Canada
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
<strong>Population:</strong> <span class="country-population">33679000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-cc"></i>
                            Cocos [Keeling] Islands
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
<strong>Population:</strong> <span class="country-population">628</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-cd"></i>
                            Democratic Republic of the Congo
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
<strong>Population:</strong> <span class="country-population">70916439</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-cf"></i>
                            Central African Republic
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
<strong>Population:</strong> <span class="country-population">4844927</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-cg"></i>
                            Republic of the Congo
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
<strong>Population:</strong> <span class="country-population">3039126</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ch"></i>
                            Switzerland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
<strong>Population:</strong> <span class="country-population">7581000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ci"></i>
                            Ivory Coast
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yamoussoukro</span><br/>
<strong>Population:</strong> <span class="country-population">21058798</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">322460.0</span><br/>
</div>
</div>, <div class="col-md-4 country">
<h3 class="country-name">

250

In [43]:
country_info = {
    "country_name":"",
    "country_capital":"",
    "country_population":"",
    "country_area":""

}
country_info

{'country_name': '',
 'country_capital': '',
 'country_population': '',
 'country_area': ''}

In [67]:
list_1 = []

for div in divs[0:249]:
    country_info = {
    "country_name":"",
    "country_capital":"",
    "country_population":"",
    "country_area":""
    }
    

    country_info["country_name"] = div.find("h3").text.strip()
    country_info["country_capital"] = div.find("span",class_="country-capital").text.strip()
    country_info["country_population"] = div.find("span",class_="country-population").text.strip()
    country_info["country_area"] = div.find("span",class_="country-area").text.strip()



    list_1.append(country_info)
print(list_1)

[{'country_name': 'Andorra', 'country_capital': 'Andorra la Vella', 'country_population': '84000', 'country_area': '468.0'}, {'country_name': 'United Arab Emirates', 'country_capital': 'Abu Dhabi', 'country_population': '4975593', 'country_area': '82880.0'}, {'country_name': 'Afghanistan', 'country_capital': 'Kabul', 'country_population': '29121286', 'country_area': '647500.0'}, {'country_name': 'Antigua and Barbuda', 'country_capital': "St. John's", 'country_population': '86754', 'country_area': '443.0'}, {'country_name': 'Anguilla', 'country_capital': 'The Valley', 'country_population': '13254', 'country_area': '102.0'}, {'country_name': 'Albania', 'country_capital': 'Tirana', 'country_population': '2986952', 'country_area': '28748.0'}, {'country_name': 'Armenia', 'country_capital': 'Yerevan', 'country_population': '2968000', 'country_area': '29800.0'}, {'country_name': 'Angola', 'country_capital': 'Luanda', 'country_population': '13068161', 'country_area': '1246700.0'}, {'country_name': 'Antarctica', 'country_capital': 'None', 'country_population': '0', 'country_area': '1.4E7'}, {'country_name': 'Argentina', 'country_capital': 'Buenos Aires', 'country_population': '41343201', 'country_area': '2766890.0'}, {'country_name': 'American Samoa', 'country_capital': 'Pago Pago', 'country_population': '57881', 'country_area': '199.0'}, {'country_name': 'Austria', 'country_capital': 'Vienna', 'country_population': '8205000', 'country_area': '83858.0'}, {'country_name': 'Australia', 'country_capital': 'Canberra', 'country_population': '21515754', 'country_area': '7686850.0'}, {'country_name': 'Aruba', 'country_capital': 'Oranjestad', 'country_population': '71566', 'country_area': '193.0'}, {'country_name': 'Åland', 'country_capital': 'Mariehamn', 'country_population': '26711', 'country_area': '1580.0'}, {'country_name': 'Azerbaijan', 'country_capital': 'Baku', 'country_population': '8303512', 'country_area': '86600.0'}, {'country_name': 'Bosnia and Herzegovina', 'country_capital': 'Sarajevo', 'country_population': '4590000', 'country_area': '51129.0'}, {'country_name': 'Barbados', 'country_capital': 'Bridgetown', 'country_population': '285653', 'country_area': '431.0'}, {'country_name': 'Bangladesh', 'country_capital': 'Dhaka', 'country_population': '156118464', 'country_area': '144000.0'}, {'country_name': 'Belgium', 'country_capital': 'Brussels', 'country_population': '10403000', 'country_area': '30510.0'}, {'country_name': 'Burkina Faso', 'country_capital': 'Ouagadougou', 'country_population': '16241811', 'country_area': '274200.0'}, {'country_name': 'Bulgaria', 'country_capital': 'Sofia', 'country_population': '7148785', 'country_area': '110910.0'}, {'country_name': 'Bahrain', 'country_capital': 'Manama', 'country_population': '738004', 'country_area': '665.0'}, {'country_name': 'Burundi', 'country_capital': 'Bujumbura', 'country_population': '9863117', 'country_area': '27830.0'}, {'country_name': 'Benin', 'country_capital': 'Porto-Novo', 'country_population': '9056010', 'country_area': '112620.0'}, {'country_name': 'Saint Barthélemy', 'country_capital': 'Gustavia', 'country_population': '8450', 'country_area': '21.0'}, {'country_name': 'Bermuda', 'country_capital': 'Hamilton', 'country_population': '65365', 'country_area': '53.0'}, {'country_name': 'Brunei', 'country_capital': 'Bandar Seri Begawan', 'country_population': '395027', 'country_area': '5770.0'}, {'country_name': 'Bolivia', 'country_capital': 'Sucre', 'country_population': '9947418', 'country_area': '1098580.0'}, {'country_name': 'Bonaire', 'country_capital': 'Kralendijk', 'country_population': '18012', 'country_area': '328.0'}, {'country_name': 'Brazil', 'country_capital': 'Brasília', 'country_population': '201103330', 'country_area': '8511965.0'}, {'country_name': 'Bahamas', 'country_capital': 'Nassau', 'country_population': '301790', 'country_area': '13940.0'}, {'country_name': 'Bhutan', 'country_capital': 'Thimphu', 'country_population': '699847', 'country_area': '47000.0'}, {'country_name': 'Bouvet Island', 'country_capital': 'None', 'country_population': '0', 'country_area': '49.0'}, {'country_name': 'Botswana', 'country_capital': 'Gaborone', 'country_population': '2029307', 'country_area': '600370.0'}, {'country_name': 'Belarus', 'country_capital': 'Minsk', 'country_population': '9685000', 'country_area': '207600.0'}, {'country_name': 'Belize', 'country_capital': 'Belmopan', 'country_population': '314522', 'country_area': '22966.0'}, {'country_name': 'Canada', 'country_capital': 'Ottawa', 'country_population': '33679000', 'country_area': '9984670.0'}, {'country_name': 'Cocos [Keeling] Islands', 'country_capital': 'West Island', 'country_population': '628', 'country_area': '14.0'}, {'country_name': 'Democratic Republic of the Congo', 'country_capital': 'Kinshasa', 'country_population': '70916439', 'country_area': '2345410.0'}, {'country_name': 'Central African Republic', 'country_capital': 'Bangui', 'country_population': '4844927', 'country_area': '622984.0'}, {'country_name': 'Republic of the Congo', 'country_capital': 'Brazzaville', 'country_population': '3039126', 'country_area': '342000.0'}, {'country_name': 'Switzerland', 'country_capital': 'Bern', 'country_population': '7581000', 'country_area': '41290.0'}, {'country_name': 'Ivory Coast', 'country_capital': 'Yamoussoukro', 'country_population': '21058798', 'country_area': '322460.0'}, {'country_name': 'Cook Islands', 'country_capital': 'Avarua', 'country_population': '21388', 'country_area': '240.0'}, {'country_name': 'Chile', 'country_capital': 'Santiago', 'country_population': '16746491', 'country_area': '756950.0'}, {'country_name': 'Cameroon', 'country_capital': 'Yaoundé', 'country_population': '19294149', 'country_area': '475440.0'}, {'country_name': 'China', 'country_capital': 'Beijing', 'country_population': '1330044000', 'country_area': '9596960.0'}, {'country_name': 'Colombia', 'country_capital': 'Bogotá', 'country_population': '47790000', 'country_area': '1138910.0'}, {'country_name': 'Costa Rica', 'country_capital': 'San José', 'country_population': '4516220', 'country_area': '51100.0'}, {'country_name': 'Cuba', 'country_capital': 'Havana', 'country_population': '11423000', 'country_area': '110860.0'}, {'country_name': 'Cape Verde', 'country_capital': 'Praia', 'country_population': '508659', 'country_area': '4033.0'}, {'country_name': 'Curacao', 'country_capital': 'Willemstad', 'country_population': '141766', 'country_area': '444.0'}, {'country_name': 'Christmas Island', 'country_capital': 'Flying Fish Cove', 'country_population': '1500', 'country_area': '135.0'}, {'country_name': 'Cyprus', 'country_capital': 'Nicosia', 'country_population': '1102677', 'country_area': '9250.0'}, {'country_name': 'Czech Republic', 'country_capital': 'Prague', 'country_population': '10476000', 'country_area': '78866.0'}, {'country_name': 'Germany', 'country_capital': 'Berlin', 'country_population': '81802257', 'country_area': '357021.0'}, {'country_name': 'Djibouti', 'country_capital': 'Djibouti', 'country_population': '740528', 'country_area': '23000.0'}, {'country_name': 'Denmark', 'country_capital': 'Copenhagen', 'country_population': '5484000', 'country_area': '43094.0'}, {'country_name': 'Dominica', 'country_capital': 'Roseau', 'country_population': '72813', 'country_area': '754.0'}, {'country_name': 'Dominican Republic', 'country_capital': 'Santo Domingo', 'country_population': '9823821', 'country_area': '48730.0'}, {'country_name': 'Algeria', 'country_capital': 'Algiers', 'country_population': '34586184', 'country_area': '2381740.0'}, {'country_name': 'Ecuador', 'country_capital': 'Quito', 'country_population': '14790608', 'country_area': '283560.0'}, {'country_name': 'Estonia', 'country_capital': 'Tallinn', 'country_population': '1291170', 'country_area': '45226.0'}, {'country_name': 'Egypt', 'country_capital': 'Cairo', 'country_population': '80471869', 'country_area': '1001450.0'}, {'country_name': 'Western Sahara', 'country_capital': 'Laâyoune / El Aaiún', 'country_population': '273008', 'country_area': '266000.0'}, {'country_name': 'Eritrea', 'country_capital': 'Asmara', 'country_population': '5792984', 'country_area': '121320.0'}, {'country_name': 'Spain', 'country_capital': 'Madrid', 'country_population': '46505963', 'country_area': '504782.0'}, {'country_name': 'Ethiopia', 'country_capital': 'Addis Ababa', 'country_population': '88013491', 'country_area': '1127127.0'}, {'country_name': 'Finland', 'country_capital': 'Helsinki', 'country_population': '5244000', 'country_area': '337030.0'}, {'country_name': 'Fiji', 'country_capital': 'Suva', 'country_population': '875983', 'country_area': '18270.0'}, {'country_name': 'Falkland Islands', 'country_capital': 'Stanley', 'country_population': '2638', 'country_area': '12173.0'}, {'country_name': 'Micronesia', 'country_capital': 'Palikir', 'country_population': '107708', 'country_area': '702.0'}, {'country_name': 'Faroe Islands', 'country_capital': 'Tórshavn', 'country_population': '48228', 'country_area': '1399.0'}, {'country_name': 'France', 'country_capital': 'Paris', 'country_population': '64768389', 'country_area': '547030.0'}, {'country_name': 'Gabon', 'country_capital': 'Libreville', 'country_population': '1545255', 'country_area': '267667.0'}, {'country_name': 'United Kingdom', 'country_capital': 'London', 'country_population': '62348447', 'country_area': '244820.0'}, {'country_name': 'Grenada', 'country_capital': "St. George's", 'country_population': '107818', 'country_area': '344.0'}, {'country_name': 'Georgia', 'country_capital': 'Tbilisi', 'country_population': '4630000', 'country_area': '69700.0'}, {'country_name': 'French Guiana', 'country_capital': 'Cayenne', 'country_population': '195506', 'country_area': '91000.0'}, {'country_name': 'Guernsey', 'country_capital': 'St Peter Port', 'country_population': '65228', 'country_area': '78.0'}, {'country_name': 'Ghana', 'country_capital': 'Accra', 'country_population': '24339838', 'country_area': '239460.0'}, {'country_name': 'Gibraltar', 'country_capital': 'Gibraltar', 'country_population': '27884', 'country_area': '6.5'}, {'country_name': 'Greenland', 'country_capital': 'Nuuk', 'country_population': '56375', 'country_area': '2166086.0'}, {'country_name': 'Gambia', 'country_capital': 'Bathurst', 'country_population': '1593256', 'country_area': '11300.0'}, {'country_name': 'Guinea', 'country_capital': 'Conakry', 'country_population': '10324025', 'country_area': '245857.0'}, {'country_name': 'Guadeloupe', 'country_capital': 'Basse-Terre', 'country_population': '443000', 'country_area': '1780.0'}, {'country_name': 'Equatorial Guinea', 'country_capital': 'Malabo', 'country_population': '1014999', 'country_area': '28051.0'}, {'country_name': 'Greece', 'country_capital': 'Athens', 'country_population': '11000000', 'country_area': '131940.0'}, {'country_name': 'South Georgia and the South Sandwich Islands', 'country_capital': 'Grytviken', 'country_population': '30', 'country_area': '3903.0'}, {'country_name': 'Guatemala', 'country_capital': 'Guatemala City', 'country_population': '13550440', 'country_area': '108890.0'}, {'country_name': 'Guam', 'country_capital': 'Hagåtña', 'country_population': '159358', 'country_area': '549.0'}, {'country_name': 'Guinea-Bissau', 'country_capital': 'Bissau', 'country_population': '1565126', 'country_area': '36120.0'}, {'country_name': 'Guyana', 'country_capital': 'Georgetown', 'country_population': '748486', 'country_area': '214970.0'}, {'country_name': 'Hong Kong', 'country_capital': 'Hong Kong', 'country_population': '6898686', 'country_area': '1092.0'}, {'country_name': 'Heard Island and McDonald Islands', 'country_capital': 'None', 'country_population': '0', 'country_area': '412.0'}, {'country_name': 'Honduras', 'country_capital': 'Tegucigalpa', 'country_population': '7989415', 'country_area': '112090.0'}, {'country_name': 'Croatia', 'country_capital': 'Zagreb', 'country_population': '4491000', 'country_area': '56542.0'}, {'country_name': 'Haiti', 'country_capital': 'Port-au-Prince', 'country_population': '9648924', 'country_area': '27750.0'}, {'country_name': 'Hungary', 'country_capital': 'Budapest', 'country_population': '9982000', 'country_area': '93030.0'}, {'country_name': 'Indonesia', 'country_capital': 'Jakarta', 'country_population': '242968342', 'country_area': '1919440.0'}, {'country_name': 'Ireland', 'country_capital': 'Dublin', 'country_population': '4622917', 'country_area': '70280.0'}, {'country_name': 'Israel', 'country_capital': 'None', 'country_population': '7353985', 'country_area': '20770.0'}, {'country_name': 'Isle of Man', 'country_capital': 'Douglas', 'country_population': '75049', 'country_area': '572.0'}, {'country_name': 'India', 'country_capital': 'New Delhi', 'country_population': '1173108018', 'country_area': '3287590.0'}, {'country_name': 'British Indian Ocean Territory', 'country_capital': 'None', 'country_population': '4000', 'country_area': '60.0'}, {'country_name': 'Iraq', 'country_capital': 'Baghdad', 'country_population': '29671605', 'country_area': '437072.0'}, {'country_name': 'Iran', 'country_capital': 'Tehran', 'country_population': '76923300', 'country_area': '1648000.0'}, {'country_name': 'Iceland', 'country_capital': 'Reykjavik', 'country_population': '308910', 'country_area': '103000.0'}, {'country_name': 'Italy', 'country_capital': 'Rome', 'country_population': '60340328', 'country_area': '301230.0'}, {'country_name': 'Jersey', 'country_capital': 'Saint Helier', 'country_population': '90812', 'country_area': '116.0'}, {'country_name': 'Jamaica', 'country_capital': 'Kingston', 'country_population': '2847232', 'country_area': '10991.0'}, {'country_name': 'Jordan', 'country_capital': 'Amman', 'country_population': '6407085', 'country_area': '92300.0'}, {'country_name': 'Japan', 'country_capital': 'Tokyo', 'country_population': '127288000', 'country_area': '377835.0'}, {'country_name': 'Kenya', 'country_capital': 'Nairobi', 'country_population': '40046566', 'country_area': '582650.0'}, {'country_name': 'Kyrgyzstan', 'country_capital': 'Bishkek', 'country_population': '5776500', 'country_area': '198500.0'}, {'country_name': 'Cambodia', 'country_capital': 'Phnom Penh', 'country_population': '14453680', 'country_area': '181040.0'}, {'country_name': 'Kiribati', 'country_capital': 'Tarawa', 'country_population': '92533', 'country_area': '811.0'}, {'country_name': 'Comoros', 'country_capital': 'Moroni', 'country_population': '773407', 'country_area': '2170.0'}, {'country_name': 'Saint Kitts and Nevis', 'country_capital': 'Basseterre', 'country_population': '51134', 'country_area': '261.0'}, {'country_name': 'North Korea', 'country_capital': 'Pyongyang', 'country_population': '22912177', 'country_area': '120540.0'}, {'country_name': 'South Korea', 'country_capital': 'Seoul', 'country_population': '48422644', 'country_area': '98480.0'}, {'country_name': 'Kuwait', 'country_capital': 'Kuwait City', 'country_population': '2789132', 'country_area': '17820.0'}, {'country_name': 'Cayman Islands', 'country_capital': 'George Town', 'country_population': '44270', 'country_area': '262.0'}, {'country_name': 'Kazakhstan', 'country_capital': 'Astana', 'country_population': '15340000', 'country_area': '2717300.0'}, {'country_name': 'Laos', 'country_capital': 'Vientiane', 'country_population': '6368162', 'country_area': '236800.0'}, {'country_name': 'Lebanon', 'country_capital': 'Beirut', 'country_population': '4125247', 'country_area': '10400.0'}, {'country_name': 'Saint Lucia', 'country_capital': 'Castries', 'country_population': '160922', 'country_area': '616.0'}, {'country_name': 'Liechtenstein', 'country_capital': 'Vaduz', 'country_population': '35000', 'country_area': '160.0'}, {'country_name': 'Sri Lanka', 'country_capital': 'Colombo', 'country_population': '21513990', 'country_area': '65610.0'}, {'country_name': 'Liberia', 'country_capital': 'Monrovia', 'country_population': '3685076', 'country_area': '111370.0'}, {'country_name': 'Lesotho', 'country_capital': 'Maseru', 'country_population': '1919552', 'country_area': '30355.0'}, {'country_name': 'Lithuania', 'country_capital': 'Vilnius', 'country_population': '2944459', 'country_area': '65200.0'}, {'country_name': 'Luxembourg', 'country_capital': 'Luxembourg', 'country_population': '497538', 'country_area': '2586.0'}, {'country_name': 'Latvia', 'country_capital': 'Riga', 'country_population': '2217969', 'country_area': '64589.0'}, {'country_name': 'Libya', 'country_capital': 'Tripoli', 'country_population': '6461454', 'country_area': '1759540.0'}, {'country_name': 'Morocco', 'country_capital': 'Rabat', 'country_population': '31627428', 'country_area': '446550.0'}, {'country_name': 'Monaco', 'country_capital': 'Monaco', 'country_population': '32965', 'country_area': '1.95'}, {'country_name': 'Moldova', 'country_capital': 'Chişinău', 'country_population': '4324000', 'country_area': '33843.0'}, {'country_name': 'Montenegro', 'country_capital': 'Podgorica', 'country_population': '666730', 'country_area': '14026.0'}, {'country_name': 'Saint Martin', 'country_capital': 'Marigot', 'country_population': '35925', 'country_area': '53.0'}, {'country_name': 'Madagascar', 'country_capital': 'Antananarivo', 'country_population': '21281844', 'country_area': '587040.0'}, {'country_name': 'Marshall Islands', 'country_capital': 'Majuro', 'country_population': '65859', 'country_area': '181.3'}, {'country_name': 'Macedonia', 'country_capital': 'Skopje', 'country_population': '2062294', 'country_area': '25333.0'}, {'country_name': 'Mali', 'country_capital': 'Bamako', 'country_population': '13796354', 'country_area': '1240000.0'}, {'country_name': 'Myanmar [Burma]', 'country_capital': 'Naypyitaw', 'country_population': '53414374', 'country_area': '678500.0'}, {'country_name': 'Mongolia', 'country_capital': 'Ulan Bator', 'country_population': '3086918', 'country_area': '1565000.0'}, {'country_name': 'Macao', 'country_capital': 'Macao', 'country_population': '449198', 'country_area': '254.0'}, {'country_name': 'Northern Mariana Islands', 'country_capital': 'Saipan', 'country_population': '53883', 'country_area': '477.0'}, {'country_name': 'Martinique', 'country_capital': 'Fort-de-France', 'country_population': '432900', 'country_area': '1100.0'}, {'country_name': 'Mauritania', 'country_capital': 'Nouakchott', 'country_population': '3205060', 'country_area': '1030700.0'}, {'country_name': 'Montserrat', 'country_capital': 'Plymouth', 'country_population': '9341', 'country_area': '102.0'}, {'country_name': 'Malta', 'country_capital': 'Valletta', 'country_population': '403000', 'country_area': '316.0'}, {'country_name': 'Mauritius', 'country_capital': 'Port Louis', 'country_population': '1294104', 'country_area': '2040.0'}, {'country_name': 'Maldives', 'country_capital': 'Malé', 'country_population': '395650', 'country_area': '300.0'}, {'country_name': 'Malawi', 'country_capital': 'Lilongwe', 'country_population': '15447500', 'country_area': '118480.0'}, {'country_name': 'Mexico', 'country_capital': 'Mexico City', 'country_population': '112468855', 'country_area': '1972550.0'}, {'country_name': 'Malaysia', 'country_capital': 'Kuala Lumpur', 'country_population': '28274729', 'country_area': '329750.0'}, {'country_name': 'Mozambique', 'country_capital': 'Maputo', 'country_population': '22061451', 'country_area': '801590.0'}, {'country_name': 'Namibia', 'country_capital': 'Windhoek', 'country_population': '2128471', 'country_area': '825418.0'}, {'country_name': 'New Caledonia', 'country_capital': 'Noumea', 'country_population': '216494', 'country_area': '19060.0'}, {'country_name': 'Niger', 'country_capital': 'Niamey', 'country_population': '15878271', 'country_area': '1267000.0'}, {'country_name': 'Norfolk Island', 'country_capital': 'Kingston', 'country_population': '1828', 'country_area': '34.6'}, {'country_name': 'Nigeria', 'country_capital': 'Abuja', 'country_population': '154000000', 'country_area': '923768

In [68]:
import pandas as pd
list = []
list.append(country_info)
df = pd.DataFrame(list_1)
df

             country_name   country_capital country_population country_area
0                 Andorra  Andorra la Vella              84000        468.0
1    United Arab Emirates         Abu Dhabi            4975593      82880.0
2             Afghanistan             Kabul           29121286     647500.0
3     Antigua and Barbuda        St. John's              86754        443.0
4                Anguilla        The Valley              13254        102.0
..                    ...               ...                ...          ...
244                Kosovo          Pristina            1800000      10908.0
245                 Yemen             Sanaa           23495361     527970.0
246               Mayotte         Mamoudzou             159042        374.0
247          South Africa          Pretoria           49000000    1219912.0
248                Zambia            Lusaka           13460305     752614.0

[249 rows x 4 columns]

In [69]:
df.to_csv("countryoo_info.csv",index=False)

<!-- 5.4 Extract country details of a first column of a page & save into csv file.  -->

# 5.4 Extract country details of a first column of a page & save into csv file.

In [70]:
list_1 = []

for div in divs[0:249:3]:
    country_info = {
    "country_name":"",
    "country_capital":"",
    "country_population":"",
    "country_area":""
    }
    

    country_info["country_name"] = div.find("h3").text.strip()
    country_info["country_capital"] = div.find("span",class_="country-capital").text.strip()
    country_info["country_population"] = div.find("span",class_="country-population").text.strip()
    country_info["country_area"] = div.find("span",class_="country-area").text.strip()



    list_1.append(country_info)
print(list_1)

[{'country_name': 'Andorra', 'country_capital': 'Andorra la Vella', 'country_population': '84000', 'country_area': '468.0'}, {'country_name': 'Antigua and Barbuda', 'country_capital': "St. John's", 'country_population': '86754', 'country_area': '443.0'}, {'country_name': 'Armenia', 'country_capital': 'Yerevan', 'country_population': '2968000', 'country_area': '29800.0'}, {'country_name': 'Argentina', 'country_capital': 'Buenos Aires', 'country_population': '41343201', 'country_area': '2766890.0'}, {'country_name': 'Australia', 'country_capital': 'Canberra', 'country_population': '21515754', 'country_area': '7686850.0'}, {'country_name': 'Azerbaijan', 'country_capital': 'Baku', 'country_population': '8303512', 'country_area': '86600.0'}, {'country_name': 'Bangladesh', 'country_capital': 'Dhaka', 'country_population': '156118464', 'country_area': '144000.0'}, {'country_name': 'Bulgaria', 'country_capital': 'Sofia', 'country_population': '7148785', 'country_area': '110910.0'}, {'country_name': 'Benin', 'country_capital': 'Porto-Novo', 'country_population': '9056010', 'country_area': '112620.0'}, {'country_name': 'Brunei', 'country_capital': 'Bandar Seri Begawan', 'country_population': '395027', 'country_area': '5770.0'}, {'country_name': 'Brazil', 'country_capital': 'Brasília', 'country_population': '201103330', 'country_area': '8511965.0'}, {'country_name': 'Bouvet Island', 'country_capital': 'None', 'country_population': '0', 'country_area': '49.0'}, {'country_name': 'Belize', 'country_capital': 'Belmopan', 'country_population': '314522', 'country_area': '22966.0'}, {'country_name': 'Democratic Republic of the Congo', 'country_capital': 'Kinshasa', 'country_population': '70916439', 'country_area': '2345410.0'}, {'country_name': 'Switzerland', 'country_capital': 'Bern', 'country_population': '7581000', 'country_area': '41290.0'}, {'country_name': 'Chile', 'country_capital': 'Santiago', 'country_population': '16746491', 'country_area': '756950.0'}, {'country_name': 'Colombia', 'country_capital': 'Bogotá', 'country_population': '47790000', 'country_area': '1138910.0'}, {'country_name': 'Cape Verde', 'country_capital': 'Praia', 'country_population': '508659', 'country_area': '4033.0'}, {'country_name': 'Cyprus', 'country_capital': 'Nicosia', 'country_population': '1102677', 'country_area': '9250.0'}, {'country_name': 'Djibouti', 'country_capital': 'Djibouti', 'country_population': '740528', 'country_area': '23000.0'}, {'country_name': 'Dominican Republic', 'country_capital': 'Santo Domingo', 'country_population': '9823821', 'country_area': '48730.0'}, {'country_name': 'Estonia', 'country_capital': 'Tallinn', 'country_population': '1291170', 'country_area': '45226.0'}, {'country_name': 'Eritrea', 'country_capital': 'Asmara', 'country_population': '5792984', 'country_area': '121320.0'}, {'country_name': 'Finland', 'country_capital': 'Helsinki', 'country_population': '5244000', 'country_area': '337030.0'}, {'country_name': 'Micronesia', 'country_capital': 'Palikir', 'country_population': '107708', 'country_area': '702.0'}, {'country_name': 'Gabon', 'country_capital': 'Libreville', 'country_population': '1545255', 'country_area': '267667.0'}, {'country_name': 'Georgia', 'country_capital': 'Tbilisi', 'country_population': '4630000', 'country_area': '69700.0'}, {'country_name': 'Ghana', 'country_capital': 'Accra', 'country_population': '24339838', 'country_area': '239460.0'}, {'country_name': 'Gambia', 'country_capital': 'Bathurst', 'country_population': '1593256', 'country_area': '11300.0'}, {'country_name': 'Equatorial Guinea', 'country_capital': 'Malabo', 'country_population': '1014999', 'country_area': '28051.0'}, {'country_name': 'Guatemala', 'country_capital': 'Guatemala City', 'country_population': '13550440', 'country_area': '108890.0'}, {'country_name': 'Guyana', 'country_capital': 'Georgetown', 'country_population': '748486', 'country_area': '214970.0'}, {'country_name': 'Honduras', 'country_capital': 'Tegucigalpa', 'country_population': '7989415', 'country_area': '112090.0'}, {'country_name': 'Hungary', 'country_capital': 'Budapest', 'country_population': '9982000', 'country_area': '93030.0'}, {'country_name': 'Israel', 'country_capital': 'None', 'country_population': '7353985', 'country_area': '20770.0'}, {'country_name': 'British Indian Ocean Territory', 'country_capital': 'None', 'country_population': '4000', 'country_area': '60.0'}, {'country_name': 'Iceland', 'country_capital': 'Reykjavik', 'country_population': '308910', 'country_area': '103000.0'}, {'country_name': 'Jamaica', 'country_capital': 'Kingston', 'country_population': '2847232', 'country_area': '10991.0'}, {'country_name': 'Kenya', 'country_capital': 'Nairobi', 'country_population': '40046566', 'country_area': '582650.0'}, {'country_name': 'Kiribati', 'country_capital': 'Tarawa', 'country_population': '92533', 'country_area': '811.0'}, {'country_name': 'North Korea', 'country_capital': 'Pyongyang', 'country_population': '22912177', 'country_area': '120540.0'}, {'country_name': 'Cayman Islands', 'country_capital': 'George Town', 'country_population': '44270', 'country_area': '262.0'}, {'country_name': 'Lebanon', 'country_capital': 'Beirut', 'country_population': '4125247', 'country_area': '10400.0'}, {'country_name': 'Sri Lanka', 'country_capital': 'Colombo', 'country_population': '21513990', 'country_area': '65610.0'}, {'country_name': 'Lithuania', 'country_capital': 'Vilnius', 'country_population': '2944459', 'country_area': '65200.0'}, {'country_name': 'Libya', 'country_capital': 'Tripoli', 'country_population': '6461454', 'country_area': '1759540.0'}, {'country_name': 'Moldova', 'country_capital': 'Chişinău', 'country_population': '4324000', 'country_area': '33843.0'}, {'country_name': 'Madagascar', 'country_capital': 'Antananarivo', 'country_population': '21281844', 'country_area': '587040.0'}, {'country_name': 'Mali', 'country_capital': 'Bamako', 'country_population': '13796354', 'country_area': '1240000.0'}, {'country_name': 'Macao', 'country_capital': 'Macao', 'country_population': '449198', 'country_area': '254.0'}, {'country_name': 'Mauritania', 'country_capital': 'Nouakchott', 'country_population': '3205060', 'country_area': '1030700.0'}, {'country_name': 'Mauritius', 'country_capital': 'Port Louis', 'country_population': '1294104', 'country_area': '2040.0'}, {'country_name': 'Mexico', 'country_capital': 'Mexico City', 'country_population': '112468855', 'country_area': '1972550.0'}, {'country_name': 'Namibia', 'country_capital': 'Windhoek', 'country_population': '2128471', 'country_area': '825418.0'}, {'country_name': 'Norfolk Island', 'country_capital': 'Kingston', 'country_population': '1828', 'country_area': '34.6'}, {'country_name': 'Netherlands', 'country_capital': 'Amsterdam', 'country_population': '16645000', 'country_area': '41526.0'}, {'country_name': 'Nauru', 'country_capital': 'Yaren', 'country_population': '10065', 'country_area': '21.0'}, {'country_name': 'Oman', 'country_capital': 'Muscat', 'country_population': '2967717', 'country_area': '212460.0'}, {'country_name': 'French Polynesia', 'country_capital': 'Papeete', 'country_population': '270485', 'country_area': '4167.0'}, {'country_name': 'Pakistan', 'country_capital': 'Islamabad', 'country_population': '184404791', 'country_area': '803940.0'}, {'country_name': 'Pitcairn Islands', 'country_capital': 'Adamstown', 'country_population': '46', 'country_area': '47.0'}, {'country_name': 'Portugal', 'country_capital': 'Lisbon', 'country_population': '10676000', 'country_area': '92391.0'}, {'country_name': 'Qatar', 'country_capital': 'Doha', 'country_population': '840926', 'country_area': '11437.0'}, {'country_name': 'Serbia', 'country_capital': 'Belgrade', 'country_population': '7344847', 'country_area': '88361.0'}, {'country_name': 'Saudi Arabia', 'country_capital': 'Riyadh', 'country_population': '25731776', 'country_area': '1960582.0'}, {'country_name': 'Sudan', 'country_capital': 'Khartoum', 'country_population': '35000000', 'country_area': '1861484.0'}, {'country_name': 'Saint Helena', 'country_capital': 'Jamestown', 'country_population': '7460', 'country_area': '410.0'}, {'country_name': 'Slovakia', 'country_capital': 'Bratislava', 'country_population': '5455000', 'country_area': '48845.0'}, {'country_name': 'Senegal', 'country_capital': 'Dakar', 'country_population': '12323252', 'country_area': '196190.0'}, {'country_name': 'South Sudan', 'country_capital': 'Juba', 'country_population': '8260490', 'country_area': '644329.0'}, {'country_name': 'Sint Maarten', 'country_capital': 'Philipsburg', 'country_population': '37429', 'country_area': '21.0'}, {'country_name': 'Turks and Caicos Islands', 'country_capital': 'Cockburn Town', 'country_population': '20556', 'country_area': '430.0'}, {'country_name': 'Togo', 'country_capital': 'Lomé', 'country_population': '6587239', 'country_area': '56785.0'}, {'country_name': 'Tokelau', 'country_capital': 'None', 'country_population': '1466', 'country_area': '10.0'}, {'country_name': 'Tunisia', 'country_capital': 'Tunis', 'country_population': '10589025', 'country_area': '163610.0'}, {'country_name': 'Trinidad and Tobago', 'country_capital': 'Port of Spain', 'country_population': '1228691', 'country_area': '5128.0'}, {'country_name': 'Tanzania', 'country_capital': 'Dodoma', 'country_population': '41892895', 'country_area': '945087.0'}, {'country_name': 'U.S. Minor Outlying Islands', 'country_capital': 'None', 'country_population': '0', 'country_area': '0.0'}, {'country_name': 'Uzbekistan', 'country_capital': 'Tashkent', 'country_population': '27865738', 'country_area': '447400.0'}, {'country_name': 'Venezuela', 'country_capital': 'Caracas', 'country_population': '27223228', 'country_area': '912050.0'}, {'country_name': 'Vietnam', 'country_capital': 'Hanoi', 'country_population': '89571130', 'country_area': '329560.0'}, {'country_name': 'Samoa', 'country_capital': 'Apia', 'country_population': '192001', 'country_area': '2944.0'}, {'country_name': 'Mayotte', 'country_capital': 'Mamoudzou', 'country_population': '159042', 'country_area': '374.0'}]

In [71]:
import pandas as pd
list = []
list.append(country_info)
df = pd.DataFrame(list_1)
df

           country_name   country_capital country_population country_area
0               Andorra  Andorra la Vella              84000        468.0
1   Antigua and Barbuda        St. John's              86754        443.0
2               Armenia           Yerevan            2968000      29800.0
3             Argentina      Buenos Aires           41343201    2766890.0
4             Australia          Canberra           21515754    7686850.0
..                  ...               ...                ...          ...
78           Uzbekistan          Tashkent           27865738     447400.0
79            Venezuela           Caracas           27223228     912050.0
80              Vietnam             Hanoi           89571130     329560.0
81                Samoa              Apia             192001       2944.0
82              Mayotte         Mamoudzou             159042        374.0

[83 rows x 4 columns]

In [72]:
df.to_csv("country3_info.csv",index=False)

In [73]:
list_1 = []

for div in divs[1:249:3]:
    country_info = {
    "country_name":"",
    "country_capital":"",
    "country_population":"",
    "country_area":""
    }
    

    country_info["country_name"] = div.find("h3").text.strip()
    country_info["country_capital"] = div.find("span",class_="country-capital").text.strip()
    country_info["country_population"] = div.find("span",class_="country-population").text.strip()
    country_info["country_area"] = div.find("span",class_="country-area").text.strip()



    list_1.append(country_info)
print(list_1)

[{'country_name': 'United Arab Emirates', 'country_capital': 'Abu Dhabi', 'country_population': '4975593', 'country_area': '82880.0'}, {'country_name': 'Anguilla', 'country_capital': 'The Valley', 'country_population': '13254', 'country_area': '102.0'}, {'country_name': 'Angola', 'country_capital': 'Luanda', 'country_population': '13068161', 'country_area': '1246700.0'}, {'country_name': 'American Samoa', 'country_capital': 'Pago Pago', 'country_population': '57881', 'country_area': '199.0'}, {'country_name': 'Aruba', 'country_capital': 'Oranjestad', 'country_population': '71566', 'country_area': '193.0'}, {'country_name': 'Bosnia and Herzegovina', 'country_capital': 'Sarajevo', 'country_population': '4590000', 'country_area': '51129.0'}, {'country_name': 'Belgium', 'country_capital': 'Brussels', 'country_population': '10403000', 'country_area': '30510.0'}, {'country_name': 'Bahrain', 'country_capital': 'Manama', 'country_population': '738004', 'country_area': '665.0'}, {'country_name': 'Saint Barthélemy', 'country_capital': 'Gustavia', 'country_population': '8450', 'country_area': '21.0'}, {'country_name': 'Bolivia', 'country_capital': 'Sucre', 'country_population': '9947418', 'country_area': '1098580.0'}, {'country_name': 'Bahamas', 'country_capital': 'Nassau', 'country_population': '301790', 'country_area': '13940.0'}, {'country_name': 'Botswana', 'country_capital': 'Gaborone', 'country_population': '2029307', 'country_area': '600370.0'}, {'country_name': 'Canada', 'country_capital': 'Ottawa', 'country_population': '33679000', 'country_area': '9984670.0'}, {'country_name': 'Central African Republic', 'country_capital': 'Bangui', 'country_population': '4844927', 'country_area': '622984.0'}, {'country_name': 'Ivory Coast', 'country_capital': 'Yamoussoukro', 'country_population': '21058798', 'country_area': '322460.0'}, {'country_name': 'Cameroon', 'country_capital': 'Yaoundé', 'country_population': '19294149', 'country_area': '475440.0'}, {'country_name': 'Costa Rica', 'country_capital': 'San José', 'country_population': '4516220', 'country_area': '51100.0'}, {'country_name': 'Curacao', 'country_capital': 'Willemstad', 'country_population': '141766', 'country_area': '444.0'}, {'country_name': 'Czech Republic', 'country_capital': 'Prague', 'country_population': '10476000', 'country_area': '78866.0'}, {'country_name': 'Denmark', 'country_capital': 'Copenhagen', 'country_population': '5484000', 'country_area': '43094.0'}, {'country_name': 'Algeria', 'country_capital': 'Algiers', 'country_population': '34586184', 'country_area': '2381740.0'}, {'country_name': 'Egypt', 'country_capital': 'Cairo', 'country_population': '80471869', 'country_area': '1001450.0'}, {'country_name': 'Spain', 'country_capital': 'Madrid', 'country_population': '46505963', 'country_area': '504782.0'}, {'country_name': 'Fiji', 'country_capital': 'Suva', 'country_population': '875983', 'country_area': '18270.0'}, {'country_name': 'Faroe Islands', 'country_capital': 'Tórshavn', 'country_population': '48228', 'country_area': '1399.0'}, {'country_name': 'United Kingdom', 'country_capital': 'London', 'country_population': '62348447', 'country_area': '244820.0'}, {'country_name': 'French Guiana', 'country_capital': 'Cayenne', 'country_population': '195506', 'country_area': '91000.0'}, {'country_name': 'Gibraltar', 'country_capital': 'Gibraltar', 'country_population': '27884', 'country_area': '6.5'}, {'country_name': 'Guinea', 'country_capital': 'Conakry', 'country_population': '10324025', 'country_area': '245857.0'}, {'country_name': 'Greece', 'country_capital': 'Athens', 'country_population': '11000000', 'country_area': '131940.0'}, {'country_name': 'Guam', 'country_capital': 'Hagåtña', 'country_population': '159358', 'country_area': '549.0'}, {'country_name': 'Hong Kong', 'country_capital': 'Hong Kong', 'country_population': '6898686', 'country_area': '1092.0'}, {'country_name': 'Croatia', 'country_capital': 'Zagreb', 'country_population': '4491000', 'country_area': '56542.0'}, {'country_name': 'Indonesia', 'country_capital': 'Jakarta', 'country_population': '242968342', 'country_area': '1919440.0'}, {'country_name': 'Isle of Man', 'country_capital': 'Douglas', 'country_population': '75049', 'country_area': '572.0'}, {'country_name': 'Iraq', 'country_capital': 'Baghdad', 'country_population': '29671605', 'country_area': '437072.0'}, {'country_name': 'Italy', 'country_capital': 'Rome', 'country_population': '60340328', 'country_area': '301230.0'}, {'country_name': 'Jordan', 'country_capital': 'Amman', 'country_population': '6407085', 'country_area': '92300.0'}, {'country_name': 'Kyrgyzstan', 'country_capital': 'Bishkek', 'country_population': '5776500', 'country_area': '198500.0'}, {'country_name': 'Comoros', 'country_capital': 'Moroni', 'country_population': '773407', 'country_area': '2170.0'}, {'country_name': 'South Korea', 'country_capital': 'Seoul', 'country_population': '48422644', 'country_area': '98480.0'}, {'country_name': 'Kazakhstan', 'country_capital': 'Astana', 'country_population': '15340000', 'country_area': '2717300.0'}, {'country_name': 'Saint Lucia', 'country_capital': 'Castries', 'country_population': '160922', 'country_area': '616.0'}, {'country_name': 'Liberia', 'country_capital': 'Monrovia', 'country_population': '3685076', 'country_area': '111370.0'}, {'country_name': 'Luxembourg', 'country_capital': 'Luxembourg', 'country_population': '497538', 'country_area': '2586.0'}, {'country_name': 'Morocco', 'country_capital': 'Rabat', 'country_population': '31627428', 'country_area': '446550.0'}, {'country_name': 'Montenegro', 'country_capital': 'Podgorica', 'country_population': '666730', 'country_area': '14026.0'}, {'country_name': 'Marshall Islands', 'country_capital': 'Majuro', 'country_population': '65859', 'country_area': '181.3'}, {'country_name': 'Myanmar [Burma]', 'country_capital': 'Naypyitaw', 'country_population': '53414374', 'country_area': '678500.0'}, {'country_name': 'Northern Mariana Islands', 'country_capital': 'Saipan', 'country_population': '53883', 'country_area': '477.0'}, {'country_name': 'Montserrat', 'country_capital': 'Plymouth', 'country_population': '9341', 'country_area': '102.0'}, {'country_name': 'Maldives', 'country_capital': 'Malé', 'country_population': '395650', 'country_area': '300.0'}, {'country_name': 'Malaysia', 'country_capital': 'Kuala Lumpur', 'country_population': '28274729', 'country_area': '329750.0'}, {'country_name': 'New Caledonia', 'country_capital': 'Noumea', 'country_population': '216494', 'country_area': '19060.0'}, {'country_name': 'Nigeria', 'country_capital': 'Abuja', 'country_population': '154000000', 'country_area': '923768.0'}, {'country_name': 'Norway', 'country_capital': 'Oslo', 'country_population': '5009150', 'country_area': '324220.0'}, {'country_name': 'Niue', 'country_capital': 'Alofi', 'country_population': '2166', 'country_area': '260.0'}, {'country_name': 'Panama', 'country_capital': 'Panama City', 'country_population': '3410676', 'country_area': '78200.0'}, {'country_name': 'Papua New Guinea', 'country_capital': 'Port Moresby', 'country_population': '6064515', 'country_area': '462840.0'}, {'country_name': 'Poland', 'country_capital': 'Warsaw', 'country_population': '38500000', 'country_area': '312685.0'}, {'country_name': 'Puerto Rico', 'country_capital': 'San Juan', 'country_population': '3916632', 'country_area': '9104.0'}, {'country_name': 'Palau', 'country_capital': 'Melekeok', 'country_population': '19907', 'country_area': '458.0'}, {'country_name': 'Réunion', 'country_capital': 'Saint-Denis', 'country_population': '776948', 'country_area': '2517.0'}, {'country_name': 'Russia', 'country_capital': 'Moscow', 'country_population': '140702000', 'country_area': '1.71E7'}, {'country_name': 'Solomon Islands', 'country_capital': 'Honiara', 'country_population': '559198', 'country_area': '28450.0'}, {'country_name': 'Sweden', 'country_capital': 'Stockholm', 'country_population': '9828655', 'country_area': '449964.0'}, {'country_name': 'Slovenia', 'country_capital': 'Ljubljana', 'country_population': '2007000', 'country_area': '20273.0'}, {'country_name': 'Sierra Leone', 'country_capital': 'Freetown', 'country_population': '5245695', 'country_area': '71740.0'}, {'country_name': 'Somalia', 'country_capital': 'Mogadishu', 'country_population': '10112453', 'country_area': '637657.0'}, {'country_name': 'São Tomé and Príncipe', 'country_capital': 'São Tomé', 'country_population': '175808', 'country_area': '1001.0'}, {'country_name': 'Syria', 'country_capital': 'Damascus', 'country_population': '22198110', 'country_area': '185180.0'}, {'country_name': 'Chad', 'country_capital': "N'Djamena", 'country_population': '10543464', 'country_area': '1284000.0'}, {'country_name': 'Thailand', 'country_capital': 'Bangkok', 'country_population': '67089500', 'country_area': '514000.0'}, {'country_name': 'East Timor', 'country_capital': 'Dili', 'country_population': '1154625', 'country_area': '15007.0'}, {'country_name': 'Tonga', 'country_capital': "Nuku'alofa", 'country_population': '122580', 'country_area': '748.0'}, {'country_name': 'Tuvalu', 'country_capital': 'Funafuti', 'country_population': '10472', 'country_area': '26.0'}, {'country_name': 'Ukraine', 'country_capital': 'Kiev', 'country_population': '45415596', 'country_area': '603700.0'}, {'country_name': 'United States', 'country_capital': 'Washington', 'country_population': '310232863', 'country_area': '9629091.0'}, {'country_name': 'Vatican City', 'country_capital': 'Vatican City', 'country_population': '921', 'country_area': '0.44'}, {'country_name': 'British Virgin Islands', 'country_capital': 'Road Town', 'country_population': '21730', 'country_area': '153.0'}, {'country_name': 'Vanuatu', 'country_capital': 'Port Vila', 'country_population': '221552', 'country_area': '12200.0'}, {'country_name': 'Kosovo', 'country_capital': 'Pristina', 'country_population': '1800000', 'country_area': '10908.0'}, {'country_name': 'South Africa', 'country_capital': 'Pretoria', 'country_population': '49000000', 'country_area': '1219912.0'}]

In [74]:
import pandas as pd
list = []
list.append(country_info)
df = pd.DataFrame(list_1)
df

              country_name country_capital country_population country_area
0     United Arab Emirates       Abu Dhabi            4975593      82880.0
1                 Anguilla      The Valley              13254        102.0
2                   Angola          Luanda           13068161    1246700.0
3           American Samoa       Pago Pago              57881        199.0
4                    Aruba      Oranjestad              71566        193.0
..                     ...             ...                ...          ...
78            Vatican City    Vatican City                921         0.44
79  British Virgin Islands       Road Town              21730        153.0
80                 Vanuatu       Port Vila             221552      12200.0
81                  Kosovo        Pristina            1800000      10908.0
82            South Africa        Pretoria           49000000    1219912.0

[83 rows x 4 columns]

In [75]:
df.to_csv("country2_info.csv",index=False)

In [76]:
list_1 = []

for div in divs[2:249:3]:
    country_info = {
    "country_name":"",
    "country_capital":"",
    "country_population":"",
    "country_area":""
    }
    

    country_info["country_name"] = div.find("h3").text.strip()
    country_info["country_capital"] = div.find("span",class_="country-capital").text.strip()
    country_info["country_population"] = div.find("span",class_="country-population").text.strip()
    country_info["country_area"] = div.find("span",class_="country-area").text.strip()



    list_1.append(country_info)
print(list_1)

[{'country_name': 'Afghanistan', 'country_capital': 'Kabul', 'country_population': '29121286', 'country_area': '647500.0'}, {'country_name': 'Albania', 'country_capital': 'Tirana', 'country_population': '2986952', 'country_area': '28748.0'}, {'country_name': 'Antarctica', 'country_capital': 'None', 'country_population': '0', 'country_area': '1.4E7'}, {'country_name': 'Austria', 'country_capital': 'Vienna', 'country_population': '8205000', 'country_area': '83858.0'}, {'country_name': 'Åland', 'country_capital': 'Mariehamn', 'country_population': '26711', 'country_area': '1580.0'}, {'country_name': 'Barbados', 'country_capital': 'Bridgetown', 'country_population': '285653', 'country_area': '431.0'}, {'country_name': 'Burkina Faso', 'country_capital': 'Ouagadougou', 'country_population': '16241811', 'country_area': '274200.0'}, {'country_name': 'Burundi', 'country_capital': 'Bujumbura', 'country_population': '9863117', 'country_area': '27830.0'}, {'country_name': 'Bermuda', 'country_capital': 'Hamilton', 'country_population': '65365', 'country_area': '53.0'}, {'country_name': 'Bonaire', 'country_capital': 'Kralendijk', 'country_population': '18012', 'country_area': '328.0'}, {'country_name': 'Bhutan', 'country_capital': 'Thimphu', 'country_population': '699847', 'country_area': '47000.0'}, {'country_name': 'Belarus', 'country_capital': 'Minsk', 'country_population': '9685000', 'country_area': '207600.0'}, {'country_name': 'Cocos [Keeling] Islands', 'country_capital': 'West Island', 'country_population': '628', 'country_area': '14.0'}, {'country_name': 'Republic of the Congo', 'country_capital': 'Brazzaville', 'country_population': '3039126', 'country_area': '342000.0'}, {'country_name': 'Cook Islands', 'country_capital': 'Avarua', 'country_population': '21388', 'country_area': '240.0'}, {'country_name': 'China', 'country_capital': 'Beijing', 'country_population': '1330044000', 'country_area': '9596960.0'}, {'country_name': 'Cuba', 'country_capital': 'Havana', 'country_population': '11423000', 'country_area': '110860.0'}, {'country_name': 'Christmas Island', 'country_capital': 'Flying Fish Cove', 'country_population': '1500', 'country_area': '135.0'}, {'country_name': 'Germany', 'country_capital': 'Berlin', 'country_population': '81802257', 'country_area': '357021.0'}, {'country_name': 'Dominica', 'country_capital': 'Roseau', 'country_population': '72813', 'country_area': '754.0'}, {'country_name': 'Ecuador', 'country_capital': 'Quito', 'country_population': '14790608', 'country_area': '283560.0'}, {'country_name': 'Western Sahara', 'country_capital': 'Laâyoune / El Aaiún', 'country_population': '273008', 'country_area': '266000.0'}, {'country_name': 'Ethiopia', 'country_capital': 'Addis Ababa', 'country_population': '88013491', 'country_area': '1127127.0'}, {'country_name': 'Falkland Islands', 'country_capital': 'Stanley', 'country_population': '2638', 'country_area': '12173.0'}, {'country_name': 'France', 'country_capital': 'Paris', 'country_population': '64768389', 'country_area': '547030.0'}, {'country_name': 'Grenada', 'country_capital': "St. George's", 'country_population': '107818', 'country_area': '344.0'}, {'country_name': 'Guernsey', 'country_capital': 'St Peter Port', 'country_population': '65228', 'country_area': '78.0'}, {'country_name': 'Greenland', 'country_capital': 'Nuuk', 'country_population': '56375', 'country_area': '2166086.0'}, {'country_name': 'Guadeloupe', 'country_capital': 'Basse-Terre', 'country_population': '443000', 'country_area': '1780.0'}, {'country_name': 'South Georgia and the South Sandwich Islands', 'country_capital': 'Grytviken', 'country_population': '30', 'country_area': '3903.0'}, {'country_name': 'Guinea-Bissau', 'country_capital': 'Bissau', 'country_population': '1565126', 'country_area': '36120.0'}, {'country_name': 'Heard Island and McDonald Islands', 'country_capital': 'None', 'country_population': '0', 'country_area': '412.0'}, {'country_name': 'Haiti', 'country_capital': 'Port-au-Prince', 'country_population': '9648924', 'country_area': '27750.0'}, {'country_name': 'Ireland', 'country_capital': 'Dublin', 'country_population': '4622917', 'country_area': '70280.0'}, {'country_name': 'India', 'country_capital': 'New Delhi', 'country_population': '1173108018', 'country_area': '3287590.0'}, {'country_name': 'Iran', 'country_capital': 'Tehran', 'country_population': '76923300', 'country_area': '1648000.0'}, {'country_name': 'Jersey', 'country_capital': 'Saint Helier', 'country_population': '90812', 'country_area': '116.0'}, {'country_name': 'Japan', 'country_capital': 'Tokyo', 'country_population': '127288000', 'country_area': '377835.0'}, {'country_name': 'Cambodia', 'country_capital': 'Phnom Penh', 'country_population': '14453680', 'country_area': '181040.0'}, {'country_name': 'Saint Kitts and Nevis', 'country_capital': 'Basseterre', 'country_population': '51134', 'country_area': '261.0'}, {'country_name': 'Kuwait', 'country_capital': 'Kuwait City', 'country_population': '2789132', 'country_area': '17820.0'}, {'country_name': 'Laos', 'country_capital': 'Vientiane', 'country_population': '6368162', 'country_area': '236800.0'}, {'country_name': 'Liechtenstein', 'country_capital': 'Vaduz', 'country_population': '35000', 'country_area': '160.0'}, {'country_name': 'Lesotho', 'country_capital': 'Maseru', 'country_population': '1919552', 'country_area': '30355.0'}, {'country_name': 'Latvia', 'country_capital': 'Riga', 'country_population': '2217969', 'country_area': '64589.0'}, {'country_name': 'Monaco', 'country_capital': 'Monaco', 'country_population': '32965', 'country_area': '1.95'}, {'country_name': 'Saint Martin', 'country_capital': 'Marigot', 'country_population': '35925', 'country_area': '53.0'}, {'country_name': 'Macedonia', 'country_capital': 'Skopje', 'country_population': '2062294', 'country_area': '25333.0'}, {'country_name': 'Mongolia', 'country_capital': 'Ulan Bator', 'country_population': '3086918', 'country_area': '1565000.0'}, {'country_name': 'Martinique', 'country_capital': 'Fort-de-France', 'country_population': '432900', 'country_area': '1100.0'}, {'country_name': 'Malta', 'country_capital': 'Valletta', 'country_population': '403000', 'country_area': '316.0'}, {'country_name': 'Malawi', 'country_capital': 'Lilongwe', 'country_population': '15447500', 'country_area': '118480.0'}, {'country_name': 'Mozambique', 'country_capital': 'Maputo', 'country_population': '22061451', 'country_area': '801590.0'}, {'country_name': 'Niger', 'country_capital': 'Niamey', 'country_population': '15878271', 'country_area': '1267000.0'}, {'country_name': 'Nicaragua', 'country_capital': 'Managua', 'country_population': '5995928', 'country_area': '129494.0'}, {'country_name': 'Nepal', 'country_capital': 'Kathmandu', 'country_population': '28951852', 'country_area': '140800.0'}, {'country_name': 'New Zealand', 'country_capital': 'Wellington', 'country_population': '4252277', 'country_area': '268680.0'}, {'country_name': 'Peru', 'country_capital': 'Lima', 'country_population': '29907003', 'country_area': '1285220.0'}, {'country_name': 'Philippines', 'country_capital': 'Manila', 'country_population': '99900177', 'country_area': '300000.0'}, {'country_name': 'Saint Pierre and Miquelon', 'country_capital': 'Saint-Pierre', 'country_population': '7012', 'country_area': '242.0'}, {'country_name': 'Palestine', 'country_capital': 'None', 'country_population': '3800000', 'country_area': '5970.0'}, {'country_name': 'Paraguay', 'country_capital': 'Asunción', 'country_population': '6375830', 'country_area': '406750.0'}, {'country_name': 'Romania', 'country_capital': 'Bucharest', 'country_population': '21959278', 'country_area': '237500.0'}, {'country_name': 'Rwanda', 'country_capital': 'Kigali', 'country_population': '11055976', 'country_area': '26338.0'}, {'country_name': 'Seychelles', 'country_capital': 'Victoria', 'country_population': '88340', 'country_area': '455.0'}, {'country_name': 'Singapore', 'country_capital': 'Singapore', 'country_population': '4701069', 'country_area': '692.7'}, {'country_name': 'Svalbard and Jan Mayen', 'country_capital': 'Longyearbyen', 'country_population': '2550', 'country_area': '62049.0'}, {'country_name': 'San Marino', 'country_capital': 'San Marino', 'country_population': '31477', 'country_area': '61.2'}, {'country_name': 'Suriname', 'country_capital': 'Paramaribo', 'country_population': '492829', 'country_area': '163270.0'}, {'country_name': 'El Salvador', 'country_capital': 'San Salvador', 'country_population': '6052064', 'country_area': '21040.0'}, {'country_name': 'Swaziland', 'country_capital': 'Mbabane', 'country_population': '1354051', 'country_area': '17363.0'}, {'country_name': 'French Southern Territories', 'country_capital': 'Port-aux-Français', 'country_population': '140', 'country_area': '7829.0'}, {'country_name': 'Tajikistan', 'country_capital': 'Dushanbe', 'country_population': '7487489', 'country_area': '143100.0'}, {'country_name': 'Turkmenistan', 'country_capital': 'Ashgabat', 'country_population': '4940916', 'country_area': '488100.0'}, {'country_name': 'Turkey', 'country_capital': 'Ankara', 'country_population': '77804122', 'country_area': '780580.0'}, {'country_name': 'Taiwan', 'country_capital': 'Taipei', 'country_population': '22894384', 'country_area': '35980.0'}, {'country_name': 'Uganda', 'country_capital': 'Kampala', 'country_population': '33398682', 'country_area': '236040.0'}, {'country_name': 'Uruguay', 'country_capital': 'Montevideo', 'country_population': '3477000', 'country_area': '176220.0'}, {'country_name': 'Saint Vincent and the Grenadines', 'country_capital': 'Kingstown', 'country_population': '104217', 'country_area': '389.0'}, {'country_name': 'U.S. Virgin Islands', 'country_capital': 'Charlotte Amalie', 'country_population': '108708', 'country_area': '352.0'}, {'country_name': 'Wallis and Futuna', 'country_capital': 'Mata-Utu', 'country_population': '16025', 'country_area': '274.0'}, {'country_name': 'Yemen', 'country_capital': 'Sanaa', 'country_population': '23495361', 'country_area': '527970.0'}, {'country_name': 'Zambia', 'country_capital': 'Lusaka', 'country_population': '13460305', 'country_area': '752614.0'}]

In [77]:
import pandas as pd
list = []
list.append(country_info)
df = pd.DataFrame(list_1)
df

,country_name,country_capital,country_population,country_area
0,Afghanistan,Kabul,29121286,647500.0
1,Albania,Tirana,2986952,28748.0
2,Antarctica,None,0,1.4E7
3,Austria,Vienna,8205000,83858.0
4,Åland,Mariehamn,26711,1580.0
...,...,...,...,...
78,Saint Vincent and the Grenadines,Kingstown,104217,389.0
79,U.S. Virgin Islands,Charlotte Amalie,108708,352.0
80,Wallis and Futuna,Mata-Utu,16025,274.0
81,Yemen,Sanaa,23495361,527970.0
82,Zambia,Lusaka,13460305,752614.0

In [78]:
df.to_csv("country1_info.csv",index=False)