## 1.1 Extract Table of year 2015 & save into csv file.(Title, Nominations, Awards, Best Picture)

In [2]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/ajax-javascript/#2015')

soup=BeautifulSoup(driver.page_source,'html')
table=soup.find_all('tr',class_='film')
list=[]
for i in table:
    dic={
        'Tittle':'',
        'Nomination':'',
        'Awards':'',
        'Best_pictures':'',
    }
    dic['Tittle']=i.find('td',class_='film-title').text.strip()
    dic['Nomination']=i.find('td',class_='film-nominations').text.strip()
    dic['Awards']=i.find('td',class_='film-awards')
    #dic['Best_pictures']=i.find
    list.append(dic)
list
df=pd.DataFrame(list)
df
df.to_csv('scrapthissite q1.csv',index=False)

## 1.2 Extract Table of year 2014 & save into another csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/ajax-javascript/#2014')

soup=BeautifulSoup(driver.page_source,'html')
table=soup.find_all('tr',class_='film')
list=[]
for i in table:
    dic={
        'Tittle':'',
        'Nomination':'',
        'Awards':'',
        'Best_pictures':'',
    }
    dic['Tittle']=i.find('td',class_='film-title').text.strip()
    dic['Nomination']=i.find('td',class_='film-nominations').text.strip()
    dic['Awards']=i.find('td',class_='film-awards')
    #dic['Best_pictures']=i.find
    list.append(dic)
list
df=pd.DataFrame(list)
df
#df.to_csv('scrapthissite q1.csv',index=False)

                              Tittle Nomination Awards Best_pictures
0                            Birdman          9    [4]
1           The Grand Budapest Hotel          9    [4]
2                           Whiplash          5    [3]
3                 The Imitation Game          8    [1]
4                    American Sniper          6    [1]
5                            Boyhood          6    [1]
6                       Interstellar          5    [1]
7           The Theory of Everything          5    [1]
8                                Ida          2    [1]
9                              Selma          2    [1]
10                       Citizenfour          1    [1]
11                        Big Hero 6          1    [1]
12  Crisis Hotline: Veterans Press 1          1    [1]
13                    The Phone Call          1    [1]
14                       Still Alice          1    [1]
15                             Feast          1    [1]

## 1.3 Extract Table of year 2013 & save into another csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/ajax-javascript/#2013')

In [11]:
soup=BeautifulSoup(driver.page_source,'html')
table=soup.find_all('tr',class_='film')
list=[]
for i in table:
    dic={
        'Tittle':'',
        'Nomination':'',
        'Awards':'',
        'Best_pictures':'',
    }
    dic['Tittle']=i.find('td',class_='film-title').text.strip()
    dic['Nomination']=i.find('td',class_='film-nominations').text.strip()
    dic['Awards']=i.find('td',class_='film-awards')
    #dic['Best_pictures']=i.find
    list.append(dic)
list
df=pd.DataFrame(list)
df
#df.to_csv('scrapthissite q1.csv',index=False)

                                       Tittle Nomination Awards Best_pictures
0                            12 Years a Slave          9    [3]
1                                     Gravity         10    [7]
2                          Dallas Buyers Club          6    [3]
3                                      Frozen          2    [2]
4                            The Great Gatsby          2    [2]
5                                         Her          5    [1]
6                                Blue Jasmine          3    [1]
7                                   Mr Hublot          1    [1]
8   The Lady in Number 6: Music Saved My Life          1    [1]
9                                      Helium          1    [1]
10                           The Great Beauty          1    [1]
11                       20 Feet from Stardom          1    [1]

In [ ]:
##

In [14]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

driver=webdriver.Chrome()
r='https://www.scrapethissite.com/pages/ajax-javascript/'
driver.get(r)

for yr in range(2015,2009,-1):

    driver.find_element('xpath',f"//a[@id='{yr}']").click()
    time.sleep(5)
    
    soup=BeautifulSoup(driver.page_source,'html.parser')
    table=soup.find_all('tr',class_='film')

    list=[]
    for i in table:
        dic={
            'Tittle':'',
            'Nomination':'',
            'Awards':'',
            'Best_pictures':'',
        }
        dic['Tittle']=i.find('td',class_='film-title').text.strip()
        dic['Nomination']=i.find('td',class_='film-nominations').text.strip()
        dic['Awards']=i.find('td',class_='film-awards').text.strip()
        #dic['Best_pictures']=i.find
        list.append(dic)


        df=pd.DataFrame(list)
    df=pd.DataFrame(list)
    df.to_csv(f'scrapthissite {yr}.csv',index=False)
    df
#df.to_csv('scrapthissite q1.csv',index=False)

In [ ]:
#---- ye sab libraries he---
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

#---har kisam ke browser hote he ye chrome se chalega---
driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/ajax-javascript/"
driver.get(url)

#---csv me lane ke lia ham list banainge---
all_list = []

#--- loof chale ga one by bone 2015 se 2010 tak chale ga---
for year in range(2015, 2009, -1):
    
    #---is se har element ko jake hit karega
    driver.find_element('xpath',f"//a[@id='{year}']").click()

    #---time is lia use howa he ke jab loading hota he tho us time quch nahi hota empty print hota he thora sa wait karne ke lia ye use karte hen
    

    #---sourse code lane ke lia---
    soup = BeautifulSoup(driver.page_source, "html.parser")

    #---saray tr mind karenge is se---
    table = soup.find_all("tr", class_="film")

    #---saray trs ke andar jo data he matlab tds wo saray one by one ainge---
    for row in table:

        #---har ak ko dictionary me ad karne ke lia---
        dic = {
            'Title': row.find('td', class_='film-title').text.strip(),
            'Nominations': row.find('td', class_='film-nominations').text.strip(),
            'Awards': row.find('td', class_='film-awards').text.strip(),
        }

        #---dictionary ko list me append karne ke lia---
        all_list.append(dic)

#---jab driver ka kaam khatam hojai tho wo khudhi band hojata he---
driver.quit()

#---poray list ko dataframe me lane ke lia---
df = pd.DataFrame(all_list)

#---csv file create karne ke lia---
df.to_csv("scrap_2015_to_2010.csv", index=False)
df

                 Title Nominations Awards
0            Spotlight           6      2
1   Mad Max: Fury Road          10      6
2         The Revenant          12      3
3      Bridge of Spies           6      1
4        The Big Short           5      1
..                 ...         ...    ...
82      The Lost Thing           1      1
83         God of Love           1      1
84         The Wolfman           1      1
85   Strangers No More           1      1
86          Inside Job           1      1

[87 rows x 3 columns]

## 1.8 Extract Tables from year 2015 to 2010 & save into single csv file with year column.

In [11]:
#---- ye sab libraries he---
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

#---har kisam ke browser hote he ye chrome se chalega---
driver = webdriver.Chrome()
url = "https://www.scrapethissite.com/pages/ajax-javascript/"
driver.get(url)

#---csv me lane ke lia ham list banainge---
all_list = []

#--- loof chale ga one by bone 2015 se 2010 tak chale ga---
for year in range(2015, 2009, -1):
    
    #---is se har element ko jake hit karega
    driver.find_element('xpath',f"//a[@id='{year}']").click()

    #---time is lia use howa he ke jab loading hota he tho us time quch nahi hota empty print hota he thora sa wait karne ke lia ye use karte hen
    time.sleep(3)

    #---sourse code lane ke lia---
    soup = BeautifulSoup(driver.page_source, "html.parser")

    #---saray tr mind karenge is se---
    table = soup.find_all("tr", class_="film")

    #---saray trs ke andar jo data he matlab tds wo saray one by one ainge---
    for row in table:

        #---har ak ko dictionary me ad karne ke lia---
        dic = {
            'years':year,
            'Title': row.find('td', class_='film-title').text.strip(),
            'Nominations': row.find('td', class_='film-nominations').text.strip(),
            'Awards': row.find('td', class_='film-awards').text.strip(),
        }

        #---dictionary ko list me append karne ke lia---
        all_list.append(dic)

#---jab driver ka kaam khatam hojai tho wo khudhi band hojata he---
driver.quit()

#---poray list ko dataframe me lane ke lia---
df = pd.DataFrame(all_list)

#---csv file create karne ke lia---
df.to_csv("scrap_2015_to_2010.csv", index=False)
df

    years               Title Nominations Awards
0    2015           Spotlight           6      2
1    2015  Mad Max: Fury Road          10      6
2    2015        The Revenant          12      3
3    2015     Bridge of Spies           6      1
4    2015       The Big Short           5      1
..    ...                 ...         ...    ...
82   2010      The Lost Thing           1      1
83   2010         God of Love           1      1
84   2010         The Wolfman           1      1
85   2010   Strangers No More           1      1
86   2010          Inside Job           1      1

[87 rows x 4 columns]

## 2.1 Extract first Testudines details save into csv file. e.g# Carettochelyidae (Testudines_name, url,img_url)

In [27]:
from  selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
div=soup.find('div',class_='col-md-4 turtle-family-card')
list=[]
dic={
    'turtle_name':'',
    'url':'',
    'img_url':'',
}
base_url='https://www.scrapethissite.com/'
dic['turtle_name']=div.find('h3').text.strip()
dic['url']=base_url+div.find('a')['href']
dic['img_url']=div.find('img')['src']
list.append(dic)
driver.quit()
df1=pd.DataFrame(list)
df1

,turtle_name,url,img_url
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

In [ ]:
df1.to_csv('scrapthissite q2.1.csv',index=False)

## 2.2 Extract Testudines family details save into csv file. e.g# Carettochelyidae, Cheloniidae, Chelydridae

In [22]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
firs_row=soup.find_all('div',class_='col-md-4 turtle-family-card')
list1=[]
for i in firs_row[:3]:
    dictionary={
        'turtle_name':'',
        'url':'',
        'img_url':'',  
    }
    base_url='https://www.scrapethissite.com/'
    dictionary['turtle_name']=i.find('h3').text.strip()
    dictionary['url']=base_url+i.find('a')['href']
    dictionary['img_url']=i.find('img')['src']
    list1.append(dictionary)
driver.quit()
df=pd.DataFrame(list1)
df

,turtle_name,url,img_url
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

In [23]:
df.to_csv('scrapthissite q2.csv',index=False)

## 2.3 Extract all Testudines family details save into csv file.

In [29]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
firs_row=soup.find_all('div',class_='col-md-4 turtle-family-card')
list1=[]
for i in firs_row:
    dictionary={
        'turtle_name':'',
        'url':'',
        'img_url':'',  
    }
    base_url='https://www.scrapethissite.com/'
    dictionary['turtle_name']=i.find('h3').text.strip()
    dictionary['url']=base_url+i.find('a')['href']
    dictionary['img_url']=i.find('img')['src']
    list1.append(dictionary)
driver.quit()
df2=pd.DataFrame(list1)
df2

,turtle_name,url,img_url
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
3,Dermatemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
4,Dermochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
5,Emydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
6,Geoemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
7,Kinosternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
8,Platysternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
9,Testudinidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
10,Trionychidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
11,Chelidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
12,Pelomedusidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...
13,Podocnemididae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...

In [30]:
df2.to_csv('scrapthissite q3.csv',index=False)

## 3.1 Extract first Testudines details save into csv file. e.g# Carettochelyidae

In [ ]:
from  selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
import requests
driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
div=soup.find('div',class_='col-md-4 turtle-family-card')
list=[]
dic={
    'turtle_name':'',
    'url':'',
    'img_url':'',
    'detail':'',
}
base_url='https://www.scrapethissite.com/'
dic['turtle_name']=div.find('h3').text.strip()
dic['url']=base_url+div.find('a')['href']
dic['img_url']=div.find('img')['src']
## method 1 for inner static websites
actural_url=dic['url']
r=requests.get(actural_url)
soup=BeautifulSoup(r.text,'html.parser')
dic['detail']=soup.find('p',class_='lead').text.strip()
## method 2 for inner dynamic websites
# actural_url=dic['url']
# driver.get(actural_url)
# time.sleep(3)
# dic['detail']=driver.find_element('xpath',"//p[@class='lead']").text.strip()
list.append(dic)
driver.quit()
df1=pd.DataFrame(list)
df1

,turtle_name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...

In [4]:
df1.to_csv('scrapthissite q3.1.csv',index=False)

## 3.2 Extract Testudines family details from first row & save into csv file. e.g# Carettochelyidae, Cheloniidae, Chelydridae

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
firs_row=soup.find_all('div',class_='col-md-4 turtle-family-card')
list1=[]
for i in firs_row[:3]:
    dictionary={
        'turtle_name':'',
        'url':'',
        'img_url':'',
        'detail':'',  
    }
    base_url='https://www.scrapethissite.com/'
    dictionary['turtle_name']=i.find('h3').text.strip()
    dictionary['url']=base_url+i.find('a')['href']
    dictionary['img_url']=i.find('img')['src']
    ## method 1 for inner static websites scraping
    main_url=dictionary['url']
    r=requests.get(main_url)
    soup=BeautifulSoup(r.text,'html.parser')
    dictionary['detail']=soup.find('p',class_='lead').text.strip()
    list1.append(dictionary)
driver.quit()
df=pd.DataFrame(list1)
df

,turtle_name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Cheloniidae family of turtles — more commo...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Chelydridae family of turtles — more commo...

In [6]:
df.to_csv('scrapthissite_q3.2.csv',index=False)

In [7]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
firs_row=soup.find_all('div',class_='col-md-4 turtle-family-card')
list1=[]
for i in firs_row[:3]:
    dictionary={
        'turtle_name':'',
        'url':'',
        'img_url':'',
        'detail':'',  
    }
    base_url='https://www.scrapethissite.com/'
    dictionary['turtle_name']=i.find('h3').text.strip()
    dictionary['url']=base_url+i.find('a')['href']
    dictionary['img_url']=i.find('img')['src']
    ## method 2 for inner dynamic websites scraping
    main_url=dictionary['url']
    driver.get(main_url)
    dictionary['detail']=driver.find_element('xpath',"//p[@class='lead']").text.strip()
    list1.append(dictionary)
driver.quit()
df=pd.DataFrame(list1)
df

,turtle_name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Cheloniidae family of turtles — more commo...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Chelydridae family of turtles — more commo...

## 3.3 Extract all Testudines family details save into csv file.

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
import requests

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
firs_row=soup.find_all('div',class_='col-md-4 turtle-family-card')
list1=[]
for i in firs_row:
    dictionary={
        'turtle_name':'',
        'url':'',
        'img_url':'',
        'detail':'',  
    }
    base_url='https://www.scrapethissite.com/'
    dictionary['turtle_name']=i.find('h3').text.strip()
    dictionary['url']=base_url+i.find('a')['href']
    dictionary['img_url']=i.find('img')['src']
    ## method 1 for inner static websites scraping
    main_url=dictionary['url']
    r=requests.get(main_url)
    soup=BeautifulSoup(r.text,'html.parser')
    dictionary['detail']=soup.find('p',class_='lead').text.strip()
    ## method 2 for inner dynamic websites scraping
    # main_url=dictionary['url']
    # driver.get(main_url)
    # dictionary['detail']=driver.find_element('xpath',"//p[@class='lead']").text.strip()
    list1.append(dictionary)
driver.quit()
df=pd.DataFrame(list1)
df

,turtle_name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...
1,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Cheloniidae family of turtles — more commo...
2,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Chelydridae family of turtles — more commo...
3,Dermatemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Dermatemydidae family of turtles — more co...
4,Dermochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Dermochelyidae family of turtles — more co...
5,Emydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Emydidae family of turtles — more commonly...
6,Geoemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Geoemydidae family of turtles — more commo...
7,Kinosternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Kinosternidae family of turtles — more com...
8,Platysternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Platysternidae family of turtles — more co...
9,Testudinidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Testudinidae family of turtles — more comm...
10,Trionychidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Trionychidae family of turtles — more comm...
11,Chelidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Chelidae family of turtles — more commonly...
12,Pelomedusidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Pelomedusidae family of turtles — more com...
13,Podocnemididae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Podocnemididae family of turtles — more co...

In [9]:
df.to_csv('scrapthissite_q_3.3.csv',index=False)

## 3.4 Extract all Testudines family details of first column save into csv file.

In [12]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
import requests

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
firs_row=soup.find_all('div',class_='col-md-4 turtle-family-card')
list1=[]
for i in firs_row[0:14:3]:
    dictionary={
        'turtle_name':'',
        'url':'',
        'img_url':'',
        'detail':'',  
    }
    base_url='https://www.scrapethissite.com/'
    dictionary['turtle_name']=i.find('h3').text.strip()
    dictionary['url']=base_url+i.find('a')['href']
    dictionary['img_url']=i.find('img')['src']
    ## method 1 for inner static websites scraping
    main_url=dictionary['url']
    r=requests.get(main_url)
    soup=BeautifulSoup(r.text,'html.parser')
    dictionary['detail']=soup.find('p',class_='lead').text.strip()
    ## method 2 for inner dynamic websites scraping
    # main_url=dictionary['url']
    # driver.get(main_url)
    # dictionary['detail']=driver.find_element('xpath',"//p[@class='lead']").text.strip()
    list1.append(dictionary)
driver.quit()
df=pd.DataFrame(list1)
df

,turtle_name,url,img_url,detail
0,Carettochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Carettochelyidae family of turtles — more ...
1,Dermatemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Dermatemydidae family of turtles — more co...
2,Geoemydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Geoemydidae family of turtles — more commo...
3,Testudinidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Testudinidae family of turtles — more comm...
4,Pelomedusidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Pelomedusidae family of turtles — more com...

## 3.5 Extract all Testudines family details of Second column save into csv file.

In [13]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
import requests

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
firs_row=soup.find_all('div',class_='col-md-4 turtle-family-card')
list1=[]
for i in firs_row[1:15:3]:
    dictionary={
        'turtle_name':'',
        'url':'',
        'img_url':'',
        'detail':'',  
    }
    base_url='https://www.scrapethissite.com/'
    dictionary['turtle_name']=i.find('h3').text.strip()
    dictionary['url']=base_url+i.find('a')['href']
    dictionary['img_url']=i.find('img')['src']
    ## method 1 for inner static websites scraping
    main_url=dictionary['url']
    r=requests.get(main_url)
    soup=BeautifulSoup(r.text,'html.parser')
    dictionary['detail']=soup.find('p',class_='lead').text.strip()
    ## method 2 for inner dynamic websites scraping
    # main_url=dictionary['url']
    # driver.get(main_url)
    # dictionary['detail']=driver.find_element('xpath',"//p[@class='lead']").text.strip()
    list1.append(dictionary)
driver.quit()
df=pd.DataFrame(list1)
df

,turtle_name,url,img_url,detail
0,Cheloniidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Cheloniidae family of turtles — more commo...
1,Dermochelyidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Dermochelyidae family of turtles — more co...
2,Kinosternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Kinosternidae family of turtles — more com...
3,Trionychidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Trionychidae family of turtles — more comm...
4,Podocnemididae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Podocnemididae family of turtles — more co...

## 3.6 Extract all Testudines family details of thirst column save into csv file.

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import time
import requests

driver=webdriver.Chrome()
driver.get('https://www.scrapethissite.com/pages/frames/')
time.sleep(5)
driver.switch_to.frame(0)
soup=BeautifulSoup(driver.page_source,'html')
firs_row=soup.find_all('div',class_='col-md-4 turtle-family-card')
list1=[]
for i in firs_row[2:16:3]:
    dictionary={
        'turtle_name':'',
        'url':'',
        'img_url':'',
        'detail':'',  
    }
    base_url='https://www.scrapethissite.com/'
    dictionary['turtle_name']=i.find('h3').text.strip()
    dictionary['url']=base_url+i.find('a')['href']
    dictionary['img_url']=i.find('img')['src']
    ## method 1 for inner static websites scraping
    main_url=dictionary['url']
    r=requests.get(main_url)
    soup=BeautifulSoup(r.text,'html.parser')
    dictionary['detail']=soup.find('p',class_='lead').text.strip()
    ## method 2 for inner dynamic websites scraping
    # main_url=dictionary['url']
    # driver.get(main_url)
    # dictionary['detail']=driver.find_element('xpath',"//p[@class='lead']").text.strip()
    list1.append(dictionary)
driver.quit()
df=pd.DataFrame(list1)
df

,turtle_name,url,img_url,detail
0,Chelydridae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Chelydridae family of turtles — more commo...
1,Emydidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Emydidae family of turtles — more commonly...
2,Platysternidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Platysternidae family of turtles — more co...
3,Chelidae,https://www.scrapethissite.com//pages/frames/?...,https://upload.wikimedia.org/wikipedia/commons...,The Chelidae family of turtles — more commonly...