
##	1.1 extract first product of a page. (product_name,product_index,product_desc,product_url,img_url)

##  1 https://webscraper.io/test-sites

In [16]:
import requests
from bs4 import BeautifulSoup

respose = requests.get("https://webscraper.io/test-sites")
respose.status_code
soup = BeautifulSoup (respose.text,('html.parser'))
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="2ch1dDVxKD3FUIMBGonJyquN6vi423Fl">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Test Sites | Web Scraper
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
   <meta content="Test Web Scraper's features and performance with our dedicated test sites. Experiment with different configurations, extract data, and evaluate the tool's capabilities in real-world scenarios" name="description">
    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <link href="https://fonts.googleapis.com" rel="preconnect"/>
    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
    <link href="https://webscraper.io/test-sites" rel="canonical"/>
    <meta content="Test Sites | Web Scraper" property="og:title"/>
    <meta content="Test Web Scraper's features and performance with our dedicated test sites. Experiment with different configurations, extract data, and evaluate the tool's capabilities in real-world scenarios" property="og:description"/>
    <meta content="website" property="og:type"/>
    <meta content="https://webscraper.io/test-sites" property="og:url"/>
    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
    </script>
   </meta>
  </meta>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-sites">
    <p style="font-size:21px;">
     Here are some sites that you can use for training while learning how to
			use the Web Scraper.
    </p>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/allinone">
        E-commerce site
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					All items are loaded in one page.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/static">
        E-commerce site with pagination links
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					Standard links are used for pagination.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-static.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/ajax">
        E-commerce site with AJAX pagination links
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					Dynamic links that use data without reloading the page for
					pagination.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-ajax.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/more">
        E-commerce site with "Load more" buttons
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					Instead of using pagination this site uses a "Load more"
					button to load more items.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-more.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/scroll">
        E-commerce site that loads items while scrolling
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					Instead of using pagination this site loads items when user
					scrolls the page down.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/tables">
        Table playground
       </a>
      </h2>
      <p class="lead">
       This page contains multiple tables. You can train using Table
					selector here.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="table playground" src="/images/test-sites/screens/test-sites-tables.png"/>
     </div>
    </div>
   </div>
   <div class="clearfix">
   </div>
   <div class="push">
   </div>
  </div>
  <div class="container-fluid footer" id="layout-footer">
   <div class="container">
    <div class="row">
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Products
        </p>
       </li>
       <li>
        <a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         Web Scraper browser extension
        </a>
       </li>
       <li>
        <a href="/cloud-scraper">
         Web Scraper Cloud
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Company
        </p>
       </li>
       <li>
        <a href="/about-us">
         About us
        </a>
       </li>
       <li>
        <a href="/contact">
         Contact
        </a>
       </li>
       <li>
        <a href="/privacy-policy">
         Website Privacy Policy
        </a>
       </li>
       <li>
        <a href="/extension-privacy-policy">
         Browser Extension Privacy Policy
        </a>
       </li>
       <li>
        <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">
         Media kit
        </a>
       </li>
       <li>
        <a href="/jobs">
         Jobs
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Resources
        </p>
       </li>
       <li>
        <a href="/blog">
         Blog
        </a>
       </li>
       <li>
        <a href="/documentation">
         Documentation
        </a>
       </li>
       <li>
        <a href="/tutorials">
         Video Tutorials
        </a>
       </li>
       <li>
        <a href="/screenshots">
         Screenshots
        </a>
       </li>
       <li>
        <a href="/test-sites">
         Test Sites
        </a>
       </li>
       <li>
        <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">
         Forum
        </a>
       </li>
       <li>
        <a href="https://status.webscraper.io/" rel="noopener" target="_blank">
         Status
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         CONTACT US
        </p>
       </li>
       <li>
        <a href="mailto:info@webscraper.io">
         info@webscraper.io
        </a>
       </li>
       <li>
        Ubelu 5-71,
        <br/>
        Adazi, Latvia, LV-2164
       </li>
      </ul>
      <ul class="smedia">
       <li>
        <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-facebook-f">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-linkedin">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-youtube">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i class="browser-icon ws-icon ws-icon-chrome-dark">
         </i>
        </a>
       </li>
      </ul>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-12">
      <p class="copyright">
       Copyright © 2025
       <b>
        Web Scraper
       </b>
       | All rights reserved
      </p>
     </div>
    </div>
   </div>
  </div>
 </body>
</html>

In [17]:
link = soup.find_all('a')
# link
for l in link:
    print(l,['href'])

<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a> ['href']
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a> ['href']
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a> ['href']
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a> ['href']
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a> ['href']
<a class="dropdown-item" href="/documentation">Documentation</a> ['href']
<a class="dropdown-item" href="/tutorials">Video Tutorials</a> ['href']
<a class="dropdown-item" href="/test-sites">Test Sites</a> ['href']
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a> ['href']
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a> ['href']
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a> ['href']
<a href="/test-sites/e-commerce/allinone">
						E-commerce site
					</a> ['href']
<a href="/test-sites/e-commerce/static">
						E-commerce site with pagination links
					</a> ['href']
<a href="/test-sites/e-commerce/ajax">
						E-commerce site with AJAX pagination links
					</a> ['href']
<a href="/test-sites/e-commerce/more">
						E-commerce site with "Load more" buttons
					</a> ['href']
<a href="/test-sites/e-commerce/scroll">
						E-commerce site that loads items while scrolling
					</a> ['href']
<a href="/test-sites/tables">Table playground
					</a> ['href']
<a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
							Web Scraper browser extension
						</a> ['href']
<a href="/cloud-scraper">Web Scraper Cloud</a> ['href']
<a href="/about-us">About us</a> ['href']
<a href="/contact">Contact</a> ['href']
<a href="/privacy-policy">Website Privacy Policy</a> ['href']
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a> ['href']
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a> ['href']
<a href="/jobs">Jobs</a> ['href']
<a href="/blog">Blog</a> ['href']
<a href="/documentation">Documentation</a> ['href']
<a href="/tutorials">Video Tutorials</a> ['href']
<a href="/screenshots">Screenshots</a> ['href']
<a href="/test-sites">Test Sites</a> ['href']
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a> ['href']
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a> ['href']
<a href="mailto:info@webscraper.io">info@webscraper.io</a> ['href']
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a> ['href']
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a> ['href']
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a> ['href']
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="browser-icon ws-icon ws-icon-chrome-dark"></i>
</a> ['href']

In [3]:
header = soup.find_all(['h1','h2','h3','h4','h5','h6','h7'])
header

[<h1>Test Sites</h1>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/allinone">
 						E-commerce site
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/static">
 						E-commerce site with pagination links
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/ajax">
 						E-commerce site with AJAX pagination links
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/more">
 						E-commerce site with "Load more" buttons
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/scroll">
 						E-commerce site that loads items while scrolling
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/tables">Table playground
 					</a>
 </h2>]

In [6]:
products = {
     'product name': '',
     'product description': '',
     'product-link': '',
     'image url': ''

}
products

{'product name': '',
 'product description': '',
 'product-link': '',
 'image url': ''}

In [18]:
products['product name'] = soup.find('h2').text.strip()

In [19]:
div = soup.find("div",class_="row test-site")

In [20]:
products['product name'] = div.find('h2').text.strip()
products['product description'] = div.find('p').text.strip().replace('\n',' ').replace('\t','')

products['product-link'] = div.find('a')['href']
products['image url'] = div.find('img')['src']
products

{'product name': 'E-commerce site',
 'product description': 'E-commerce site with multiple categories, subcategories. All items are loaded in one page.',
 'product-link': '/test-sites/e-commerce/allinone',
 'image url': '/images/test-sites/screens/test-sites-ecommerce-allinone.png'}

In [31]:
import pandas as pd
list =[]
products = {
     'product name': '',
     'product description': '',
     'product-link': '',
     'image url': ''

}
products['product name'] = div.find('h2').text.strip()
products['product description'] = div.find('p').text.strip().replace('\n',' ').replace('\t','')

products['product-link'] = div.find('a')['href']
products['image url'] = div.find('img')['src']
products
list.append(products)
# df = pd.DataFrame(products)
# df
# df.to_csv('webscraper.csv',index=False)
df = pd.DataFrame(list)
df
df.to_csv('webscraper.csv',index=False)

# 	1.2 extract first product of a page. (product_name,product_index,product_desc,product_url,img_url)

In [7]:
import requests
from bs4 import BeautifulSoup
respose = requests.get("https://webscraper.io/test-sites")
respose.status_code
soup = BeautifulSoup (respose.text,('html.parser'))

In [ ]:
products = {
     'product name': '',
     'product description': '',
     'product-link': '',
     'image url': ''

}
print(products)

{'product name': '', 'product description': '', 'product-link': '', 'image url': ''}

In [8]:
var2 = soup.find_all("div",class_="row test-site")
type(var2)

bs4.element.ResultSet

In [9]:
var2[1]

<div class="row test-site">
<div class="col-lg-7 order-lg-2">
<h2 class="site-heading">
<a href="/test-sites/e-commerce/static">
						E-commerce site with pagination links
					</a>
</h2>
<p class="lead">
					E-commerce site with multiple categories, subcategories.
					Standard links are used for pagination.
				</p>
</div>
<div class="col-lg-5 order-lg-1">
<img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-static.png"/>
</div>
</div>

In [10]:
var2[1].find('h2').text.strip()

var2[1].find('p').text.strip().replace('\n',' ').replace('\t','')
var2[1].find('img')['src']
var2[1].find('a')['href']
var2

[<div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/allinone">
 						E-commerce site
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					All items are loaded in one page.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/static">
 						E-commerce site with pagination links
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					Standard links are used for pagination.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-static.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/ajax">
 						E-commerce site with AJAX pagination links
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					Dynamic links that use data without reloading the page for
 					pagination.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-ajax.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/more">
 						E-commerce site with "Load more" buttons
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					Instead of using pagination this site uses a "Load more"
 					button to load more items.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-more.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/scroll">
 						E-commerce site that loads items while scrolling
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					Instead of using pagination this site loads items when user
 					scrolls the page down.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/tables">Table playground
 					</a>
 </h2>
 <p class="lead">
 					This page contains multiple tables. You can train using Table
 					selector here.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="table playground" src="/images/test-sites/screens/test-sites-tables.png"/>
 </div>
 </div>]

In [32]:
import pandas as pd
list =[]

products['product name'] = var2[1].find('h2').text.strip()
products['product description'] = var2[1].find('p').text.strip().replace('\n',' ').replace('\t','')
products['product-link'] = var2[1].find('a')['href']
products['image url'] = var2[1].find('img')['src']
# var1
list.append(products)

df = pd.DataFrame(list)
df
df.to_csv('webscraper.csv',mode='a+',index=False)

# 	1.1  all extract first product of a page. (product_name,product_index,product_desc,product_url,img_url)

In [34]:
import requests
from bs4 import BeautifulSoup

url = 'https://webscraper.io/test-sites'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

In [ ]:
data_list = []  

var_all = soup.find_all("div", class_="row test-site")
for div in var_all:
    var_dec = {
         'product name': '',
         'product description': '',
         'product-link': '',
         'image url': ''
    }
    var_dec['product name'] = div.find('h2').text.strip()
    var_dec['product description'] = div.find('p').text.strip().replace('\n',' ').replace('\t','')
    var_dec['product-link'] = div.find('a')['href']
    var_dec['image url'] = div.find('img')['src']
    data_list.append(var_dec)
df = pd.DataFrame(data_list)
df

,product name,product description,product-link,image url
0,E-commerce site,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/allinone,/images/test-sites/screens/test-sites-ecommerc...
1,E-commerce site with pagination links,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/static,/images/test-sites/screens/test-sites-ecommerc...
2,E-commerce site with AJAX pagination links,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/ajax,/images/test-sites/screens/test-sites-ecommerc...
3,"E-commerce site with ""Load more"" buttons","E-commerce site with multiple categories, subc...",/test-sites/e-commerce/more,/images/test-sites/screens/test-sites-ecommerc...
4,E-commerce site that loads items while scrolling,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/scroll,/images/test-sites/screens/test-sites-ecommerc...
5,Table playground,This page contains multiple tables. You can tr...,/test-sites/tables,/images/test-sites/screens/test-sites-tables.png

In [53]:
import pandas as pd

df = pd.DataFrame(data_list)
df.to_csv('webscraper.csv',mode='a+',index=False)

# 4.1 Extract first Table of a page & save into csv file.
# https://webscraper.io/test-sites/tables

In [10]:
import requests 
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/tables')
response.status_code
soup = BeautifulSoup(response.text,('html.parser'))
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="zbKBiZamIF0pOgQl4g2EnKTE9TNQRSLV">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Table Playground | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
   <meta content="Test Web Scraper's features on basic table layouts. Practice extracting structured table data." name="description">
    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <link href="https://fonts.googleapis.com" rel="preconnect"/>
    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
    <link href="https://webscraper.io/test-sites/tables" rel="canonical"/>
    <meta content="Table Playground | Web Scraper Test Sites" property="og:title"/>
    <meta content="Test Web Scraper's features on basic table layouts. Practice extracting structured table data." property="og:description"/>
    <meta content="website" property="og:type"/>
    <meta content="https://webscraper.io/test-sites/tables" property="og:url"/>
    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
    </script>
   </meta>
  </meta>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container">
    <div class="test-site">
     <div class="row">
      <div class="col-lg-3 sidebar">
       <div class="navbar-light sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
         <ul class="nav flex-column tables-nav" id="side-menu">
          <li class="nav-item">
           <a class="table-nav-button semantically-correct-button nav-link active" href="/test-sites/tables/tables-semantically-correct">
            Semantically correct tables
           </a>
          </li>
          <li class="nav-item">
           <a class="table-nav-button button-without-thead nav-link" href="/test-sites/tables/tables-without-thead">
            Tables without the thead tag
           </a>
          </li>
          <li class="nav-item">
           <a class="table-nav-button button-multiple-headers nav-link" href="/test-sites/tables/tables-multiple-header-rows">
            Tables with multiple header rows
           </a>
          </li>
         </ul>
        </div>
       </div>
      </div>
      <div class="col-lg-9">
       <div class="tables-all">
        <div class="jumbotron tables-initial-text">
         <h2>
          Table playground
         </h2>
         <p class="lead">
          You can train using Table selector here.
         </p>
        </div>
        <div class="tables-semantically-correct">
         <h2>
          Semantically correct table with thead and tbody
         </h2>
         <p>
          Table selector automatically detects header and data rows.
         </p>
         <table class="table table-bordered">
          <thead>
           <tr>
            <th>
             #
            </th>
            <th>
             First Name
            </th>
            <th>
             Last Name
            </th>
            <th>
             Username
            </th>
           </tr>
          </thead>
          <tbody>
           <tr>
            <td>
             1
            </td>
            <td>
             Mark
            </td>
            <td>
             Otto
            </td>
            <td>
             @mdo
            </td>
           </tr>
           <tr>
            <td>
             2
            </td>
            <td>
             Jacob
            </td>
            <td>
             Thornton
            </td>
            <td>
             @fat
            </td>
           </tr>
           <tr>
            <td>
             3
            </td>
            <td>
             Larry
            </td>
            <td>
             the Bird
            </td>
            <td>
             @twitter
            </td>
           </tr>
          </tbody>
         </table>
         <table class="table table-bordered table-bordered2">
          <thead>
           <tr>
            <th>
             #
            </th>
            <th>
             First Name
            </th>
            <th>
             Last Name
            </th>
            <th>
             Username
            </th>
           </tr>
          </thead>
          <tbody>
           <tr>
            <td>
             4
            </td>
            <td>
             Harry
            </td>
            <td>
             Potter
            </td>
            <td>
             @hp
            </td>
           </tr>
           <tr>
            <td>
             5
            </td>
            <td>
             John
            </td>
            <td>
             Snow
            </td>
            <td>
             @dunno
            </td>
           </tr>
           <tr>
            <td>
             6
            </td>
            <td>
             Tim
            </td>
            <td>
             Bean
            </td>
            <td>
             @timbean
            </td>
           </tr>
          </tbody>
         </table>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
   <div class="clearfix">
   </div>
   <div class="push">
   </div>
  </div>
  <div class="container-fluid footer" id="layout-footer">
   <div class="container">
    <div class="row">
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Products
        </p>
       </li>
       <li>
        <a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         Web Scraper browser extension
        </a>
       </li>
       <li>
        <a href="/cloud-scraper">
         Web Scraper Cloud
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Company
        </p>
       </li>
       <li>
        <a href="/about-us">
         About us
        </a>
       </li>
       <li>
        <a href="/contact">
         Contact
        </a>
       </li>
       <li>
        <a href="/privacy-policy">
         Website Privacy Policy
        </a>
       </li>
       <li>
        <a href="/extension-privacy-policy">
         Browser Extension Privacy Policy
        </a>
       </li>
       <li>
        <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">
         Media kit
        </a>
       </li>
       <li>
        <a href="/jobs">
         Jobs
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Resources
        </p>
       </li>
       <li>
        <a href="/blog">
         Blog
        </a>
       </li>
       <li>
        <a href="/documentation">
         Documentation
        </a>
       </li>
       <li>
        <a href="/tutorials">
         Video Tutorials
        </a>
       </li>
       <li>
        <a href="/screenshots">
         Screenshots
        </a>
       </li>
       <li>
        <a href="/test-sites">
         Test Sites
        </a>
       </li>
       <li>
        <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">
         Forum
        </a>
       </li>
       <li>
        <a href="https://status.webscraper.io/" rel="noopener" target="_blank">
         Status
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         CONTACT US
        </p>
       </li>
       <li>
        <a href="mailto:info@webscraper.io">
         info@webscraper.io
        </a>
       </li>
       <li>
        Ubelu 5-71,
        <br/>
        Adazi, Latvia, LV-2164
       </li>
      </ul>
      <ul class="smedia">
       <li>
        <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-facebook-f">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-linkedin">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-youtube">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i class="browser-icon ws-icon ws-icon-chrome-dark">
         </i>
        </a>
       </li>
      </ul>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-12">
      <p class="copyright">
       Copyright © 2025
       <b>
        Web Scraper
       </b>
       | All rights reserved
      </p>
     </div>
    </div>
   </div>
  </div>
 </body>
</html>

In [11]:
var = soup.find_all('table','table table-bordered')
var

[<table class="table table-bordered">
 <thead>
 <tr>
 <th>#</th>
 <th>First Name</th>
 <th>Last Name</th>
 <th>Username</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td>1</td>
 <td>Mark</td>
 <td>Otto</td>
 <td>@mdo</td>
 </tr>
 <tr>
 <td>2</td>
 <td>Jacob</td>
 <td>Thornton</td>
 <td>@fat</td>
 </tr>
 <tr>
 <td>3</td>
 <td>Larry</td>
 <td>the Bird</td>
 <td>@twitter</td>
 </tr>
 </tbody>
 </table>]

In [12]:
row = var[0].find_all('tr')[1]
cells = row.find_all('td')

number = cells[0].text.strip()      # '1'
first_name = cells[1].text.strip()  # 'Mark'
last_name = cells[2].text.strip()   # 'Otto'
username = cells[3].text.strip()    # '@mdo'

print(f"{number} {first_name} {last_name} {username}")

1 Mark Otto @mdo

In [13]:
from bs4 import BeautifulSoup

# row = var[0].find_all('tr')[1]   # tumhara row object
row = var[0].find_all('tr')[1]

# agar table cells <td> mein hain:
cols = [td.get_text(strip=True) for td in row.find_all('td')]
print(cols)   # e.g. ['1', 'Mark Otto', '@mdo']

rank = cols[0]
name = cols[1]
handle = cols[2].lstrip('@')   # agar @ hataana ho
print(rank, name, handle)

['1', 'Mark', 'Otto', '@mdo']
1 Mark Otto

In [37]:
row = var[0].find_all('th')[1].text
row = var[0].find_all('th')[2].text
row = var[0].find_all('th')[3].text
row

'Username'

In [34]:
row = var[0].find_all('th')[2].text
row

'Last Name'

In [61]:
dict ['index']= row = var[0].find_all('tr')[0].text.strip().replace('\n',' ')
dict ['frist name']=row = var[0].find_all('tr')[1].text.strip().replace('\n',' ')
dict ['last name']=row = var[0].find_all('tr')[2].text.strip().replace('\n',' ')
dict ['user name']=row = var[0].find_all('tr')[3].text.strip().replace('\n',' ')

print(dict)

{'index': '# First Name Last Name Username', 'frist name': '1 Mark Otto @mdo', 'last name': '2 Jacob Thornton @fat', 'user name': '3 Larry the Bird @twitter'}

In [35]:
row = var[0].find_all('th')[3].text
row

'Username'

In [2]:
rows = table.find_all('tr')

In [59]:
# Extract data
data = []
for row in rows[0:4]:  # Skip header row
    cells = row.find_all('td')
    dict={
    'index':'',
    'frist name':'',
    'last name':'',
    'user name':'',
    }
    if cells:
        row_data = [cell.text.strip() for cell in cells]
        data.append(row_data)

In [29]:
import pandas as pd 

df = pd.DataFrame(data)
df
df.to_csv('table q4_1.csv',index=False)
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
dict={
    'index':'',
    'name':'',
    'last name':'',
    'user name':'',
}

In [8]:
table=soup.find_all('table',class_='table table-bordered table-bordered2')
table

[<table class="table table-bordered table-bordered2">
 <thead>
 <tr>
 <th>#</th>
 <th>First Name</th>
 <th>Last Name</th>
 <th>Username</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td>4</td>
 <td>Harry</td>
 <td>Potter</td>
 <td>@hp</td>
 </tr>
 <tr>
 <td>5</td>
 <td>John</td>
 <td>Snow</td>
 <td>@dunno</td>
 </tr>
 <tr>
 <td>6</td>
 <td>Tim</td>
 <td>Bean</td>
 <td>@timbean</td>
 </tr>
 </tbody>
 </table>]

In [24]:
data = []
for row in rows[0:4]:  # Skip header row
    table = row.find_all('tr')
    dict={
    'index':'',
    'name':'',
    'last name':'',
    'user name':'',
    }
    if table:
        row_data = [cell.text.strip() for cell in table]
        data.append(row_data)

Empty DataFrame
Columns: []
Index: []