
##	1.1 extract first product of a page. (product_name,product_index,product_desc,product_url,img_url)

##  1 https://webscraper.io/test-sites

In [16]:
import requests
from bs4 import BeautifulSoup

respose = requests.get("https://webscraper.io/test-sites")
respose.status_code
soup = BeautifulSoup (respose.text,('html.parser'))
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="2ch1dDVxKD3FUIMBGonJyquN6vi423Fl">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Test Sites | Web Scraper
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
   <meta content="Test Web Scraper's features and performance with our dedicated test sites. Experiment with different configurations, extract data, and evaluate the tool's capabilities in real-world scenarios" name="description">
    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <link href="https://fonts.googleapis.com" rel="preconnect"/>
    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
    <link href="https://webscraper.io/test-sites" rel="canonical"/>
    <meta content="Test Sites | Web Scraper" property="og:title"/>
    <meta content="Test Web Scraper's features and performance with our dedicated test sites. Experiment with different configurations, extract data, and evaluate the tool's capabilities in real-world scenarios" property="og:description"/>
    <meta content="website" property="og:type"/>
    <meta content="https://webscraper.io/test-sites" property="og:url"/>
    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
    </script>
   </meta>
  </meta>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-sites">
    <p style="font-size:21px;">
     Here are some sites that you can use for training while learning how to
			use the Web Scraper.
    </p>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/allinone">
        E-commerce site
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					All items are loaded in one page.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/static">
        E-commerce site with pagination links
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					Standard links are used for pagination.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-static.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/ajax">
        E-commerce site with AJAX pagination links
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					Dynamic links that use data without reloading the page for
					pagination.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-ajax.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/more">
        E-commerce site with "Load more" buttons
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					Instead of using pagination this site uses a "Load more"
					button to load more items.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-more.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/e-commerce/scroll">
        E-commerce site that loads items while scrolling
       </a>
      </h2>
      <p class="lead">
       E-commerce site with multiple categories, subcategories.
					Instead of using pagination this site loads items when user
					scrolls the page down.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
     </div>
    </div>
    <hr class="test-site-divider"/>
    <div class="row test-site">
     <div class="col-lg-7 order-lg-2">
      <h2 class="site-heading">
       <a href="/test-sites/tables">
        Table playground
       </a>
      </h2>
      <p class="lead">
       This page contains multiple tables. You can train using Table
					selector here.
      </p>
     </div>
     <div class="col-lg-5 order-lg-1">
      <img alt="table playground" src="/images/test-sites/screens/test-sites-tables.png"/>
     </div>
    </div>
   </div>
   <div class="clearfix">
   </div>
   <div class="push">
   </div>
  </div>
  <div class="container-fluid footer" id="layout-footer">
   <div class="container">
    <div class="row">
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Products
        </p>
       </li>
       <li>
        <a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         Web Scraper browser extension
        </a>
       </li>
       <li>
        <a href="/cloud-scraper">
         Web Scraper Cloud
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Company
        </p>
       </li>
       <li>
        <a href="/about-us">
         About us
        </a>
       </li>
       <li>
        <a href="/contact">
         Contact
        </a>
       </li>
       <li>
        <a href="/privacy-policy">
         Website Privacy Policy
        </a>
       </li>
       <li>
        <a href="/extension-privacy-policy">
         Browser Extension Privacy Policy
        </a>
       </li>
       <li>
        <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">
         Media kit
        </a>
       </li>
       <li>
        <a href="/jobs">
         Jobs
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Resources
        </p>
       </li>
       <li>
        <a href="/blog">
         Blog
        </a>
       </li>
       <li>
        <a href="/documentation">
         Documentation
        </a>
       </li>
       <li>
        <a href="/tutorials">
         Video Tutorials
        </a>
       </li>
       <li>
        <a href="/screenshots">
         Screenshots
        </a>
       </li>
       <li>
        <a href="/test-sites">
         Test Sites
        </a>
       </li>
       <li>
        <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">
         Forum
        </a>
       </li>
       <li>
        <a href="https://status.webscraper.io/" rel="noopener" target="_blank">
         Status
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         CONTACT US
        </p>
       </li>
       <li>
        <a href="mailto:info@webscraper.io">
         info@webscraper.io
        </a>
       </li>
       <li>
        Ubelu 5-71,
        <br/>
        Adazi, Latvia, LV-2164
       </li>
      </ul>
      <ul class="smedia">
       <li>
        <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-facebook-f">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-linkedin">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-youtube">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i class="browser-icon ws-icon ws-icon-chrome-dark">
         </i>
        </a>
       </li>
      </ul>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-12">
      <p class="copyright">
       Copyright © 2025
       <b>
        Web Scraper
       </b>
       | All rights reserved
      </p>
     </div>
    </div>
   </div>
  </div>
 </body>
</html>

In [17]:
link = soup.find_all('a')
# link
for l in link:
    print(l,['href'])

<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a> ['href']
<a href="/"><img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/></a> ['href']
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a> ['href']
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a> ['href']
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a> ['href']
<a class="dropdown-item" href="/documentation">Documentation</a> ['href']
<a class="dropdown-item" href="/tutorials">Video Tutorials</a> ['href']
<a class="dropdown-item" href="/test-sites">Test Sites</a> ['href']
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a> ['href']
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500"></i>
							Install
						</a> ['href']
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a> ['href']
<a href="/test-sites/e-commerce/allinone">
						E-commerce site
					</a> ['href']
<a href="/test-sites/e-commerce/static">
						E-commerce site with pagination links
					</a> ['href']
<a href="/test-sites/e-commerce/ajax">
						E-commerce site with AJAX pagination links
					</a> ['href']
<a href="/test-sites/e-commerce/more">
						E-commerce site with "Load more" buttons
					</a> ['href']
<a href="/test-sites/e-commerce/scroll">
						E-commerce site that loads items while scrolling
					</a> ['href']
<a href="/test-sites/tables">Table playground
					</a> ['href']
<a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
							Web Scraper browser extension
						</a> ['href']
<a href="/cloud-scraper">Web Scraper Cloud</a> ['href']
<a href="/about-us">About us</a> ['href']
<a href="/contact">Contact</a> ['href']
<a href="/privacy-policy">Website Privacy Policy</a> ['href']
<a href="/extension-privacy-policy">Browser Extension Privacy Policy</a> ['href']
<a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">Media kit</a> ['href']
<a href="/jobs">Jobs</a> ['href']
<a href="/blog">Blog</a> ['href']
<a href="/documentation">Documentation</a> ['href']
<a href="/tutorials">Video Tutorials</a> ['href']
<a href="/screenshots">Screenshots</a> ['href']
<a href="/test-sites">Test Sites</a> ['href']
<a href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a> ['href']
<a href="https://status.webscraper.io/" rel="noopener" target="_blank">Status</a> ['href']
<a href="mailto:info@webscraper.io">info@webscraper.io</a> ['href']
<a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-facebook-f"></i>
</a> ['href']
<a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-linkedin"></i>
</a> ['href']
<a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
<i class="ws-icon ws-icon-youtube"></i>
</a> ['href']
<a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
<i class="browser-icon ws-icon ws-icon-chrome-dark"></i>
</a> ['href']

In [3]:
header = soup.find_all(['h1','h2','h3','h4','h5','h6','h7'])
header

[<h1>Test Sites</h1>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/allinone">
 						E-commerce site
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/static">
 						E-commerce site with pagination links
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/ajax">
 						E-commerce site with AJAX pagination links
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/more">
 						E-commerce site with "Load more" buttons
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/scroll">
 						E-commerce site that loads items while scrolling
 					</a>
 </h2>,
 <h2 class="site-heading">
 <a href="/test-sites/tables">Table playground
 					</a>
 </h2>]

In [6]:
products = {
     'product name': '',
     'product description': '',
     'product-link': '',
     'image url': ''

}
products

{'product name': '',
 'product description': '',
 'product-link': '',
 'image url': ''}

In [18]:
products['product name'] = soup.find('h2').text.strip()

In [19]:
div = soup.find("div",class_="row test-site")

In [20]:
products['product name'] = div.find('h2').text.strip()
products['product description'] = div.find('p').text.strip().replace('\n',' ').replace('\t','')

products['product-link'] = div.find('a')['href']
products['image url'] = div.find('img')['src']
products

{'product name': 'E-commerce site',
 'product description': 'E-commerce site with multiple categories, subcategories. All items are loaded in one page.',
 'product-link': '/test-sites/e-commerce/allinone',
 'image url': '/images/test-sites/screens/test-sites-ecommerce-allinone.png'}

In [31]:
import pandas as pd
list =[]
products = {
     'product name': '',
     'product description': '',
     'product-link': '',
     'image url': ''

}
products['product name'] = div.find('h2').text.strip()
products['product description'] = div.find('p').text.strip().replace('\n',' ').replace('\t','')

products['product-link'] = div.find('a')['href']
products['image url'] = div.find('img')['src']
products
list.append(products)
# df = pd.DataFrame(products)
# df
# df.to_csv('webscraper.csv',index=False)
df = pd.DataFrame(list)
df
df.to_csv('webscraper.csv',index=False)

# 	1.2 extract first product of a page. (product_name,product_index,product_desc,product_url,img_url)

In [7]:
import requests
from bs4 import BeautifulSoup
respose = requests.get("https://webscraper.io/test-sites")
respose.status_code
soup = BeautifulSoup (respose.text,('html.parser'))

In [ ]:
products = {
     'product name': '',
     'product description': '',
     'product-link': '',
     'image url': ''

}
print(products)

{'product name': '', 'product description': '', 'product-link': '', 'image url': ''}

In [8]:
var2 = soup.find_all("div",class_="row test-site")
type(var2)

bs4.element.ResultSet

In [9]:
var2[1]

<div class="row test-site">
<div class="col-lg-7 order-lg-2">
<h2 class="site-heading">
<a href="/test-sites/e-commerce/static">
						E-commerce site with pagination links
					</a>
</h2>
<p class="lead">
					E-commerce site with multiple categories, subcategories.
					Standard links are used for pagination.
				</p>
</div>
<div class="col-lg-5 order-lg-1">
<img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-static.png"/>
</div>
</div>

In [10]:
var2[1].find('h2').text.strip()

var2[1].find('p').text.strip().replace('\n',' ').replace('\t','')
var2[1].find('img')['src']
var2[1].find('a')['href']
var2

[<div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/allinone">
 						E-commerce site
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					All items are loaded in one page.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/static">
 						E-commerce site with pagination links
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					Standard links are used for pagination.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-static.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/ajax">
 						E-commerce site with AJAX pagination links
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					Dynamic links that use data without reloading the page for
 					pagination.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-ajax.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/more">
 						E-commerce site with "Load more" buttons
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					Instead of using pagination this site uses a "Load more"
 					button to load more items.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-more.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/e-commerce/scroll">
 						E-commerce site that loads items while scrolling
 					</a>
 </h2>
 <p class="lead">
 					E-commerce site with multiple categories, subcategories.
 					Instead of using pagination this site loads items when user
 					scrolls the page down.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="E-commerce site" src="/images/test-sites/screens/test-sites-ecommerce-allinone.png"/>
 </div>
 </div>,
 <div class="row test-site">
 <div class="col-lg-7 order-lg-2">
 <h2 class="site-heading">
 <a href="/test-sites/tables">Table playground
 					</a>
 </h2>
 <p class="lead">
 					This page contains multiple tables. You can train using Table
 					selector here.
 				</p>
 </div>
 <div class="col-lg-5 order-lg-1">
 <img alt="table playground" src="/images/test-sites/screens/test-sites-tables.png"/>
 </div>
 </div>]

In [32]:
import pandas as pd
list =[]

products['product name'] = var2[1].find('h2').text.strip()
products['product description'] = var2[1].find('p').text.strip().replace('\n',' ').replace('\t','')
products['product-link'] = var2[1].find('a')['href']
products['image url'] = var2[1].find('img')['src']
# var1
list.append(products)

df = pd.DataFrame(list)
df
df.to_csv('webscraper.csv',mode='a+',index=False)

# 	1.1  all extract first product of a page. (product_name,product_index,product_desc,product_url,img_url)

In [34]:
import requests
from bs4 import BeautifulSoup

url = 'https://webscraper.io/test-sites'
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

In [ ]:
data_list = []  

var_all = soup.find_all("div", class_="row test-site")
for div in var_all:
    var_dec = {
         'product name': '',
         'product description': '',
         'product-link': '',
         'image url': ''
    }
    var_dec['product name'] = div.find('h2').text.strip()
    var_dec['product description'] = div.find('p').text.strip().replace('\n',' ').replace('\t','')
    var_dec['product-link'] = div.find('a')['href']
    var_dec['image url'] = div.find('img')['src']
    data_list.append(var_dec)
df = pd.DataFrame(data_list)
df

,product name,product description,product-link,image url
0,E-commerce site,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/allinone,/images/test-sites/screens/test-sites-ecommerc...
1,E-commerce site with pagination links,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/static,/images/test-sites/screens/test-sites-ecommerc...
2,E-commerce site with AJAX pagination links,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/ajax,/images/test-sites/screens/test-sites-ecommerc...
3,"E-commerce site with ""Load more"" buttons","E-commerce site with multiple categories, subc...",/test-sites/e-commerce/more,/images/test-sites/screens/test-sites-ecommerc...
4,E-commerce site that loads items while scrolling,"E-commerce site with multiple categories, subc...",/test-sites/e-commerce/scroll,/images/test-sites/screens/test-sites-ecommerc...
5,Table playground,This page contains multiple tables. You can tr...,/test-sites/tables,/images/test-sites/screens/test-sites-tables.png

In [53]:
import pandas as pd

df = pd.DataFrame(data_list)
df.to_csv('webscraper.csv',mode='a+',index=False)

# 4.1 Extract first Table of a page & save into csv file.
# https://webscraper.io/test-sites/tables

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://webscraper.io/test-sites/tables"
resp = requests.get(url)
soup = BeautifulSoup(resp.text, "html.parser")

table = soup.find("table")

headers = [th.get_text(strip=True) for th in table.find_all("th")]
print("Headers:", headers)
row= []

for tr in table.find_all("tr")[1:]:
    cells = [td.get_text(strip=True) for td in tr.find_all(["td","th"])]
    print(cells)
    row.append(cells)
    
df = pd.DataFrame(row)
df.to_csv("webscraper q4_1.csv", index=False, encoding="utf-8")
df

Headers: ['#', 'First Name', 'Last Name', 'Username']
['1', 'Mark', 'Otto', '@mdo']
['2', 'Jacob', 'Thornton', '@fat']
['3', 'Larry', 'the Bird', '@twitter']

   0      1         2         3
0  1   Mark      Otto      @mdo
1  2  Jacob  Thornton      @fat
2  3  Larry  the Bird  @twitter

In [10]:
import requests 
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/tables')
response.status_code
soup = BeautifulSoup(response.text,('html.parser'))
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="zbKBiZamIF0pOgQl4g2EnKTE9TNQRSLV">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Table Playground | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords">
   <meta content="Test Web Scraper's features on basic table layouts. Practice extracting structured table data." name="description">
    <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
    <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
    <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
    <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <link href="https://fonts.googleapis.com" rel="preconnect"/>
    <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
    <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
    <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
    <link href="https://webscraper.io/test-sites/tables" rel="canonical"/>
    <meta content="Table Playground | Web Scraper Test Sites" property="og:title"/>
    <meta content="Test Web Scraper's features on basic table layouts. Practice extracting structured table data." property="og:description"/>
    <meta content="website" property="og:type"/>
    <meta content="https://webscraper.io/test-sites/tables" property="og:url"/>
    <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
    <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
    </script>
   </meta>
  </meta>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container">
    <div class="test-site">
     <div class="row">
      <div class="col-lg-3 sidebar">
       <div class="navbar-light sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
         <ul class="nav flex-column tables-nav" id="side-menu">
          <li class="nav-item">
           <a class="table-nav-button semantically-correct-button nav-link active" href="/test-sites/tables/tables-semantically-correct">
            Semantically correct tables
           </a>
          </li>
          <li class="nav-item">
           <a class="table-nav-button button-without-thead nav-link" href="/test-sites/tables/tables-without-thead">
            Tables without the thead tag
           </a>
          </li>
          <li class="nav-item">
           <a class="table-nav-button button-multiple-headers nav-link" href="/test-sites/tables/tables-multiple-header-rows">
            Tables with multiple header rows
           </a>
          </li>
         </ul>
        </div>
       </div>
      </div>
      <div class="col-lg-9">
       <div class="tables-all">
        <div class="jumbotron tables-initial-text">
         <h2>
          Table playground
         </h2>
         <p class="lead">
          You can train using Table selector here.
         </p>
        </div>
        <div class="tables-semantically-correct">
         <h2>
          Semantically correct table with thead and tbody
         </h2>
         <p>
          Table selector automatically detects header and data rows.
         </p>
         <table class="table table-bordered">
          <thead>
           <tr>
            <th>
             #
            </th>
            <th>
             First Name
            </th>
            <th>
             Last Name
            </th>
            <th>
             Username
            </th>
           </tr>
          </thead>
          <tbody>
           <tr>
            <td>
             1
            </td>
            <td>
             Mark
            </td>
            <td>
             Otto
            </td>
            <td>
             @mdo
            </td>
           </tr>
           <tr>
            <td>
             2
            </td>
            <td>
             Jacob
            </td>
            <td>
             Thornton
            </td>
            <td>
             @fat
            </td>
           </tr>
           <tr>
            <td>
             3
            </td>
            <td>
             Larry
            </td>
            <td>
             the Bird
            </td>
            <td>
             @twitter
            </td>
           </tr>
          </tbody>
         </table>
         <table class="table table-bordered table-bordered2">
          <thead>
           <tr>
            <th>
             #
            </th>
            <th>
             First Name
            </th>
            <th>
             Last Name
            </th>
            <th>
             Username
            </th>
           </tr>
          </thead>
          <tbody>
           <tr>
            <td>
             4
            </td>
            <td>
             Harry
            </td>
            <td>
             Potter
            </td>
            <td>
             @hp
            </td>
           </tr>
           <tr>
            <td>
             5
            </td>
            <td>
             John
            </td>
            <td>
             Snow
            </td>
            <td>
             @dunno
            </td>
           </tr>
           <tr>
            <td>
             6
            </td>
            <td>
             Tim
            </td>
            <td>
             Bean
            </td>
            <td>
             @timbean
            </td>
           </tr>
          </tbody>
         </table>
        </div>
       </div>
      </div>
     </div>
    </div>
   </div>
   <div class="clearfix">
   </div>
   <div class="push">
   </div>
  </div>
  <div class="container-fluid footer" id="layout-footer">
   <div class="container">
    <div class="row">
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Products
        </p>
       </li>
       <li>
        <a class="install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         Web Scraper browser extension
        </a>
       </li>
       <li>
        <a href="/cloud-scraper">
         Web Scraper Cloud
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Company
        </p>
       </li>
       <li>
        <a href="/about-us">
         About us
        </a>
       </li>
       <li>
        <a href="/contact">
         Contact
        </a>
       </li>
       <li>
        <a href="/privacy-policy">
         Website Privacy Policy
        </a>
       </li>
       <li>
        <a href="/extension-privacy-policy">
         Browser Extension Privacy Policy
        </a>
       </li>
       <li>
        <a href="https://webscraper.io/downloads/Web_Scraper_Media_Kit.zip">
         Media kit
        </a>
       </li>
       <li>
        <a href="/jobs">
         Jobs
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         Resources
        </p>
       </li>
       <li>
        <a href="/blog">
         Blog
        </a>
       </li>
       <li>
        <a href="/documentation">
         Documentation
        </a>
       </li>
       <li>
        <a href="/tutorials">
         Video Tutorials
        </a>
       </li>
       <li>
        <a href="/screenshots">
         Screenshots
        </a>
       </li>
       <li>
        <a href="/test-sites">
         Test Sites
        </a>
       </li>
       <li>
        <a href="https://forum.webscraper.io/" rel="noopener" target="_blank">
         Forum
        </a>
       </li>
       <li>
        <a href="https://status.webscraper.io/" rel="noopener" target="_blank">
         Status
        </a>
       </li>
      </ul>
     </div>
     <div class="col-lg-3">
      <ul>
       <li>
        <p>
         CONTACT US
        </p>
       </li>
       <li>
        <a href="mailto:info@webscraper.io">
         info@webscraper.io
        </a>
       </li>
       <li>
        Ubelu 5-71,
        <br/>
        Adazi, Latvia, LV-2164
       </li>
      </ul>
      <ul class="smedia">
       <li>
        <a aria-label="Web Scraper on Facebook" href="https://www.facebook.com/webscraperio/" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-facebook-f">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on LinkedIn" href="https://lv.linkedin.com/company/web-scraper" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-linkedin">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Web Scraper on Youtube" href="https://youtube.com/@WebScraper/videos" rel="noopener" target="_blank">
         <i class="ws-icon ws-icon-youtube">
         </i>
        </a>
       </li>
       <li>
        <a aria-label="Download the Web Scraper extension" class="install-extension browser-icon-dark" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i class="browser-icon ws-icon ws-icon-chrome-dark">
         </i>
        </a>
       </li>
      </ul>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-12">
      <p class="copyright">
       Copyright © 2025
       <b>
        Web Scraper
       </b>
       | All rights reserved
      </p>
     </div>
    </div>
   </div>
  </div>
 </body>
</html>

In [11]:
var = soup.find_all('table','table table-bordered')
var

[<table class="table table-bordered">
 <thead>
 <tr>
 <th>#</th>
 <th>First Name</th>
 <th>Last Name</th>
 <th>Username</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td>1</td>
 <td>Mark</td>
 <td>Otto</td>
 <td>@mdo</td>
 </tr>
 <tr>
 <td>2</td>
 <td>Jacob</td>
 <td>Thornton</td>
 <td>@fat</td>
 </tr>
 <tr>
 <td>3</td>
 <td>Larry</td>
 <td>the Bird</td>
 <td>@twitter</td>
 </tr>
 </tbody>
 </table>]

In [12]:
row = var[0].find_all('tr')[1]
cells = row.find_all('td')

number = cells[0].text.strip()      # '1'
first_name = cells[1].text.strip()  # 'Mark'
last_name = cells[2].text.strip()   # 'Otto'
username = cells[3].text.strip()    # '@mdo'

print(f"{number} {first_name} {last_name} {username}")

1 Mark Otto @mdo

In [13]:
from bs4 import BeautifulSoup

# row = var[0].find_all('tr')[1]   # tumhara row object
row = var[0].find_all('tr')[1]

# agar table cells <td> mein hain:
cols = [td.get_text(strip=True) for td in row.find_all('td')]
print(cols)   # e.g. ['1', 'Mark Otto', '@mdo']

rank = cols[0]
name = cols[1]
handle = cols[2].lstrip('@')   # agar @ hataana ho
print(rank, name, handle)

['1', 'Mark', 'Otto', '@mdo']
1 Mark Otto

In [37]:
row = var[0].find_all('th')[1].text
row = var[0].find_all('th')[2].text
row = var[0].find_all('th')[3].text
row

'Username'

In [34]:
row = var[0].find_all('th')[2].text
row

'Last Name'

In [61]:
dict ['index']= row = var[0].find_all('tr')[0].text.strip().replace('\n',' ')
dict ['frist name']=row = var[0].find_all('tr')[1].text.strip().replace('\n',' ')
dict ['last name']=row = var[0].find_all('tr')[2].text.strip().replace('\n',' ')
dict ['user name']=row = var[0].find_all('tr')[3].text.strip().replace('\n',' ')

print(dict)

{'index': '# First Name Last Name Username', 'frist name': '1 Mark Otto @mdo', 'last name': '2 Jacob Thornton @fat', 'user name': '3 Larry the Bird @twitter'}

In [35]:
row = var[0].find_all('th')[3].text
row

'Username'

In [2]:
rows = table.find_all('tr')

In [59]:
# Extract data
data = []
for row in rows[0:4]:  # Skip header row
    cells = row.find_all('td')
    dict={
    'index':'',
    'frist name':'',
    'last name':'',
    'user name':'',
    }
    if cells:
        row_data = [cell.text.strip() for cell in cells]
        data.append(row_data)

In [29]:
import pandas as pd 

df = pd.DataFrame(data)
df
df.to_csv('table q4_1.csv',index=False)
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
dict={
    'index':'',
    'name':'',
    'last name':'',
    'user name':'',
}

In [8]:
table=soup.find_all('table',class_='table table-bordered table-bordered2')
table

[<table class="table table-bordered table-bordered2">
 <thead>
 <tr>
 <th>#</th>
 <th>First Name</th>
 <th>Last Name</th>
 <th>Username</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td>4</td>
 <td>Harry</td>
 <td>Potter</td>
 <td>@hp</td>
 </tr>
 <tr>
 <td>5</td>
 <td>John</td>
 <td>Snow</td>
 <td>@dunno</td>
 </tr>
 <tr>
 <td>6</td>
 <td>Tim</td>
 <td>Bean</td>
 <td>@timbean</td>
 </tr>
 </tbody>
 </table>]

In [24]:
data = []
for row in rows[0:4]:  # Skip header row
    table = row.find_all('tr')
    dict={
    'index':'',
    'name':'',
    'last name':'',
    'user name':'',
    }
    if table:
        row_data = [cell.text.strip() for cell in table]
        data.append(row_data)

## 6.1 Extract first product details save into csv file. e.g# Asus VivoBook...
## https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops

In [4]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="20Uu5iaai4c5tIT44tE3kPKNoVML6zr1">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Allinone | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
  <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
  <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
  <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
  <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
  <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
  <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
  <link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>
  <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
  <meta content="website" property="og:type"/>
  <meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>
  <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
  <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
  </script>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-site">
    <div class="row">
     <div class="col-lg-3 sidebar">
      <div class="navbar-light sidebar" role="navigation">
       <div class="sidebar-nav navbar-collapse">
        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
         <li class="nav-item">
          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">
           <span itemprop="name">
            Home
           </span>
          </a>
         </li>
         <li class="nav-item active">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
           <span itemprop="name">
            Computers
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
             <span itemprop="name">
              Laptops
             </span>
            </a>
           </li>
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
             <span itemprop="name">
              Tablets
             </span>
            </a>
           </li>
          </ul>
         </li>
         <li class="nav-item">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
           <span itemprop="name">
            Phones
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
         </li>
        </ul>
       </div>
      </div>
     </div>
     <div class="col-lg-9">
      <h1 class="page-header">
       Computers / Laptops
      </h1>
      <div class="row">
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $295.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
             Asus VivoBook...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             14
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $299
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
             Prestigio Smar...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             8
            </span>
            reviews
           </p>
           <p data-rating="2">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $299
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
             Prestigio Smar...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             12
            </span>
            reviews
           </p>
           <p data-rating="4">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $306.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
             Aspire E1-510
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             2
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $321.94
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
             Lenovo V110-15...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             5
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $356.49
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
             Lenovo V110-15...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             6
            </span>
            reviews
           </p>
           <p data-rating="2">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $364.46
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
             Hewlett Packar...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             12
            </span>

In [7]:
product = soup.find('div',class_='product-wrapper card-body')
product

<div class="product-wrapper card-body">
<img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
<div class="caption">
<h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
<span itemprop="price">$295.99</span>
<meta content="USD" itemprop="priceCurrency"/>
</h4>
<h4>
<a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
						Asus VivoBook...
					</a>
</h4>
<p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
</div>
<div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
<p class="review-count float-end">
<span itemprop="reviewCount">14</span> reviews
				</p>
<p data-rating="3">
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
<span class="ws-icon ws-icon-star"></span>
</p>
</div>
</div>

In [15]:
list = []
prod_dictionary = {
    'product_name': '',
    'product_link': '',
    'product_img': '',
    'product_price': '',
    'product_details': '',
    'product_reviews_number': '',
    'product_reviews_star_number': '',
}

In [16]:
prod_dictionary['product_name']= product.find('a').text.strip()
prod_dictionary['product_details']=product.find('p').text
prod_dictionary['product_img']=product.find('img')['src']
prod_dictionary['product_link']=product.find('a')['href']
prod_dictionary['product_reviews_number']=product.find('div',class_='ratings').text.strip()
prod_dictionary['product_reviews_star_number']
prod_dictionary['product_price']=product.find('h4').text.strip()
list.append(prod_dictionary)

In [14]:
prod_dictionary

{'product_name': 'Asus VivoBook...',
 'product_link': '/test-sites/e-commerce/allinone/product/60',
 'product_img': '/images/test-sites/e-commerce/items/cart2.png',
 'product_price': '$295.99',
 'product_details': 'Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd',
 'product_reviews_number': '14 reviews',
 'product_reviews_star_number': ''}

In [50]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q6_1.csv',index=False)

In [29]:
len(product)

5

## 6.2 Extract product details from first row & save into csv file. e.g# Asus VivoBook..., Prestigio Smar...,Prestigio Smar...

In [52]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="sRLmsOcgqwQoEH6FB3yWUCVlw9IZ1hTM">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Allinone | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
  <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
  <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
  <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
  <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
  <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
  <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
  <link href="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" rel="canonical"/>
  <meta content="Allinone | Web Scraper Test Sites" property="og:title"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
  <meta content="website" property="og:type"/>
  <meta content="https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops" property="og:url"/>
  <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
  <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
  </script>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-site">
    <div class="row">
     <div class="col-lg-3 sidebar">
      <div class="navbar-light sidebar" role="navigation">
       <div class="sidebar-nav navbar-collapse">
        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
         <li class="nav-item">
          <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url">
           <span itemprop="name">
            Home
           </span>
          </a>
         </li>
         <li class="nav-item active">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
           <span itemprop="name">
            Computers
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
             <span itemprop="name">
              Laptops
             </span>
            </a>
           </li>
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
             <span itemprop="name">
              Tablets
             </span>
            </a>
           </li>
          </ul>
         </li>
         <li class="nav-item">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
           <span itemprop="name">
            Phones
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
         </li>
        </ul>
       </div>
      </div>
     </div>
     <div class="col-lg-9">
      <h1 class="page-header">
       Computers / Laptops
      </h1>
      <div class="row">
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $295.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
             Asus VivoBook...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             14
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $299
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
             Prestigio Smar...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             8
            </span>
            reviews
           </p>
           <p data-rating="2">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $299
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
             Prestigio Smar...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             12
            </span>
            reviews
           </p>
           <p data-rating="4">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $306.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
             Aspire E1-510
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             2
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $321.94
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
             Lenovo V110-15...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             5
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $356.49
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
             Lenovo V110-15...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             6
            </span>
            reviews
           </p>
           <p data-rating="2">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $364.46
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
             Hewlett Packar...
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             12
            </span>

In [5]:
products = soup.find_all('div',class_='row')
products

[<div class="row">
 <div class="col-lg-12">
 <h1>Test Sites</h1>
 </div>
 </div>,
 <div class="row">
 <div class="col-lg-3 sidebar">
 <div class="navbar-light sidebar" role="navigation">
 <div class="sidebar-nav navbar-collapse">
 <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
 <li class="nav-item">
 <a class="nav-link" href="/test-sites/e-commerce/allinone" itemprop="url"><span itemprop="name">Home</span></a>
 </li>
 <li class="nav-item active">
 <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/computers" itemprop="url">
 <span itemprop="name">Computers</span>
 <i aria-hidden="true" class="ws-icon ws-icon-right"></i>
 </a>
 <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
 <li class="nav-item">
 <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/allinone/computers/laptops" itemprop="url">
 <span itemprop="name">Laptops</span>
 </a>
 </li>
 <li class="nav-item">
 <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/allinone/computers/tablets" itemprop="url">
 <span itemprop="name">Tablets</span>
 </a>
 </li>
 </ul>
 </li>
 <li class="nav-item">
 <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/allinone/phones" itemprop="url">
 <span itemprop="name">Phones</span>
 <i aria-hidden="true" class="ws-icon ws-icon-right"></i>
 </a>
 </li>
 </ul>
 </div>
 </div>
 </div>
 <div class="col-lg-9">
 <h1 class="page-header">Computers / Laptops</h1>
 <div class="row">
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$321.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$356.49</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$364.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
 						Hewlett Packar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$372.7</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$391.48</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$393.88</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/70" itemprop="name" title="Acer Aspire 3 A315-21">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/45" itemprop="name" title="Asus VivoBook Max">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/71" itemprop="name" title="Asus VivoBook E502NA-GO022T Dark Blue">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">3</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$404.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/72" itemprop="name" title="Lenovo ThinkPad E31-80">
 						Lenovo ThinkPa...
 					</a>
 </h4>

In [32]:
len(products)

5

In [24]:
len(prod_dictionary)

7

In [26]:
main_div = products[2]

all_products = main_div.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
len(all_products)

117

In [25]:
products = soup.find_all('div',class_='row')
len(products)

5

In [34]:
list = []
for i in all_products[0:3]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [49]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q6_2.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Prestigio Smar...,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews,
1,Lenovo V110-15...,/test-sites/e-commerce/allinone/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,6 reviews,
2,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",0 reviews,
3,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",9 reviews,
4,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/72,/images/test-sites/e-commerce/items/cart2.png,$404.23,"Lenovo ThinkPad E31-80, 13.3"" HD, Celeron 3855...",12 reviews,
5,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/75,/images/test-sites/e-commerce/items/cart2.png,$410.46,"Acer Aspire ES1-732 Black, 17.3"" HD+, Celeron,...",14 reviews,
6,Asus EeeBook R...,/test-sites/e-commerce/allinone/product/77,/images/test-sites/e-commerce/items/cart2.png,$433.3,"Asus EeeBook R416NA-FA014T, 14"" FHD, Pentium N...",1 reviews,
7,Acer Extensa 1...,/test-sites/e-commerce/allinone/product/80,/images/test-sites/e-commerce/items/cart2.png,$439.73,"Acer Extensa 15 (2540) Black, 15.6"" HD, Core i...",6 reviews,
8,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/83,/images/test-sites/e-commerce/items/cart2.png,$457.38,"Acer Aspire A315-51-33TG, Black 15.6"" HD, Core...",9 reviews,
9,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/86,/images/test-sites/e-commerce/items/cart2.png,$469.1,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",5 reviews,
10,Lenovo V510 Bl...,/test-sites/e-commerce/allinone/product/89,/images/test-sites/e-commerce/items/cart2.png,$487.8,"Lenovo V510 Black, 15.6"" HD, Core i3-6006U, 4G...",9 reviews,
11,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/91,/images/test-sites/e-commerce/items/cart2.png,$494.71,"Acer Aspire 3 A315-51 Black, 15.6"" FHD, Core i...",2 reviews,
12,HP 250 G3,/test-sites/e-commerce/allinone/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews,
13,Aspire E1-572G,/test-sites/e-commerce/allinone/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews,
14,Dell Inspiron...,/test-sites/e-commerce/allinone/product/49,/images/test-sites/e-commerce/items/cart2.png,$679,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",7 reviews,
15,Inspiron 15,/test-sites/e-commerce/allinone/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews,
16,Asus ROG STRIX...,/test-sites/e-commerce/allinone/product/53,/images/test-sites/e-commerce/items/cart2.png,$899,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews,
17,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/94,/images/test-sites/e-commerce/items/cart2.png,$1096.02,"Lenovo ThinkPad L460, 14"" FHD IPS, Core i7-660...",14 reviews,
18,MSI GL72M 7RDX,/test-sites/e-commerce/allinone/product/97,/images/test-sites/e-commerce/items/cart2.png,$1099,"Asus ROG Strix GL553VD-DM535T, 15.6"" FHD, Core...",9 reviews,
19,Dell Latitude...,/test-sites/e-commerce/allinone/product/100,/images/test-sites/e-commerce/items/cart2.png,$1110.14,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",4 reviews,
20,Acer Predator...,/test-sites/e-commerce/allinone/product/103,/images/test-sites/e-commerce/items/cart2.png,$1123.87,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",1 reviews,
21,Dell Latitude...,/test-sites/e-commerce/allinone/product/106,/images/test-sites/e-commerce/items/cart2.png,$1133.82,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",14 reviews,
22,Acer Nitro 5 A...,/test-sites/e-commerce/allinone/product/109,/images/test-sites/e-commerce/items/cart2.png,$1140.62,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i7-...",14 reviews,
23,Dell Latitude...,/test-sites/e-commerce/allinone/product/112,/images/test-sites/e-commerce/items/cart2.png,$1144.4,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",10 reviews,
24,Lenovo Yoga 72...,/test-sites/e-commerce/allinone/product/114,/images/test-sites/e-commerce/items/cart2.png,$1149.73,"Lenovo Yoga 720 Grey, 15.6"" FHD IPS, Core i5-7...",12 reviews,
25,Dell Latitude...,/test-sites/e-commerce/allinone/product/117,/images/test-sites/e-commerce/items/cart2.png,$1178.19,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",6 reviews,
26,Dell Latitude...,/test-sites/e-commerce/allinone/product/119,/images/test-sites/e-commerce/items/cart2.png,$1187.88,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",5 reviews,
27,MSI GL62M 7REX...,/test-sites/e-commerce/allinone/product/122,/images/test-sites/e-commerce/items/cart2.png,$1199,"MSI GL62M 7REX2, 15.6"" FHD, Core i7-7700HQ, 8G...",12 reviews,
28,Lenovo IdeaPad...,/test-sites/e-commerce/allinone/product/125,/images/test-sites/e-commerce/items/cart2.png,$1212.16,"Lenovo IdeaPad Miix 510 Platinum Silver, 12.2""...",0 reviews,
29,Asus VivoBook...,/test-sites/e-commerce/allinone/product/127,/images/test-sites/e-commerce/items/cart2.png,$1235.49,"Asus VivoBook Pro 15 N580VN-FI006T Gold Metal,...",10 reviews,
30,ThinkPad X230,/test-sites/e-commerce/allinone/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews,
31,Dell Latitude...,/test-sites/e-commerce/allinone/product/132,/images/test-sites/e-commerce/items/cart2.png,$1271.06,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",13 reviews,
32,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/134,/images/test-sites/e-commerce/items/cart2.png,$1294.74,"Toshiba Portege Z30-C-16K Grey, 13.3"" FHD, Cor...",6 reviews,
33,ThinkPad X240,/test-sites/e-commerce/allinone/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews,
34,Dell Latitude...,/test-sites/e-commerce/allinone/product/139,/images/test-sites/e-commerce/items/cart2.png,$1337.28,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",6 reviews,
35,Apple MacBook...,/test-sites/e-commerce/allinone/product/142,/images/test-sites/e-commerce/items/cart2.png,$1347.78,"Apple MacBook Air 13"", Intel Core i5 1.8GHz, 8...",11 reviews,
36,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/145,/images/test-sites/e-commerce/items/cart2.png,$1366.32,"Toshiba Portege X20W-D-10V Black/Blue, 12.5"" F...",11 reviews,
37,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/147,/images/test-sites/e-commerce/items/cart2.png,$1399,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",10 reviews,
38,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews,

## 6.3 Extract all product details from page & save into csv file.

In [ ]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

In [29]:
all_products = main_div.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products
# len(all_products)

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$321.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$356.49</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$364.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
 						Hewlett Packar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$372.7</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$391.48</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$393.88</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/70" itemprop="name" title="Acer Aspire 3 A315-21">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/45" itemprop="name" title="Asus VivoBook Max">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/71" itemprop="name" title="Asus VivoBook E502NA-GO022T Dark Blue">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">3</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$404.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/72" itemprop="name" title="Lenovo ThinkPad E31-80">
 						Lenovo ThinkPa...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$408.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/73" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,

In [30]:
list = []
for i in all_products[0:117]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [48]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q6_3.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Prestigio Smar...,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews,
1,Lenovo V110-15...,/test-sites/e-commerce/allinone/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,6 reviews,
2,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",0 reviews,
3,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",9 reviews,
4,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/72,/images/test-sites/e-commerce/items/cart2.png,$404.23,"Lenovo ThinkPad E31-80, 13.3"" HD, Celeron 3855...",12 reviews,
5,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/75,/images/test-sites/e-commerce/items/cart2.png,$410.46,"Acer Aspire ES1-732 Black, 17.3"" HD+, Celeron,...",14 reviews,
6,Asus EeeBook R...,/test-sites/e-commerce/allinone/product/77,/images/test-sites/e-commerce/items/cart2.png,$433.3,"Asus EeeBook R416NA-FA014T, 14"" FHD, Pentium N...",1 reviews,
7,Acer Extensa 1...,/test-sites/e-commerce/allinone/product/80,/images/test-sites/e-commerce/items/cart2.png,$439.73,"Acer Extensa 15 (2540) Black, 15.6"" HD, Core i...",6 reviews,
8,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/83,/images/test-sites/e-commerce/items/cart2.png,$457.38,"Acer Aspire A315-51-33TG, Black 15.6"" HD, Core...",9 reviews,
9,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/86,/images/test-sites/e-commerce/items/cart2.png,$469.1,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",5 reviews,
10,Lenovo V510 Bl...,/test-sites/e-commerce/allinone/product/89,/images/test-sites/e-commerce/items/cart2.png,$487.8,"Lenovo V510 Black, 15.6"" HD, Core i3-6006U, 4G...",9 reviews,
11,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/91,/images/test-sites/e-commerce/items/cart2.png,$494.71,"Acer Aspire 3 A315-51 Black, 15.6"" FHD, Core i...",2 reviews,
12,HP 250 G3,/test-sites/e-commerce/allinone/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews,
13,Aspire E1-572G,/test-sites/e-commerce/allinone/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews,
14,Dell Inspiron...,/test-sites/e-commerce/allinone/product/49,/images/test-sites/e-commerce/items/cart2.png,$679,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",7 reviews,
15,Inspiron 15,/test-sites/e-commerce/allinone/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews,
16,Asus ROG STRIX...,/test-sites/e-commerce/allinone/product/53,/images/test-sites/e-commerce/items/cart2.png,$899,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews,
17,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/94,/images/test-sites/e-commerce/items/cart2.png,$1096.02,"Lenovo ThinkPad L460, 14"" FHD IPS, Core i7-660...",14 reviews,
18,MSI GL72M 7RDX,/test-sites/e-commerce/allinone/product/97,/images/test-sites/e-commerce/items/cart2.png,$1099,"Asus ROG Strix GL553VD-DM535T, 15.6"" FHD, Core...",9 reviews,
19,Dell Latitude...,/test-sites/e-commerce/allinone/product/100,/images/test-sites/e-commerce/items/cart2.png,$1110.14,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",4 reviews,
20,Acer Predator...,/test-sites/e-commerce/allinone/product/103,/images/test-sites/e-commerce/items/cart2.png,$1123.87,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",1 reviews,
21,Dell Latitude...,/test-sites/e-commerce/allinone/product/106,/images/test-sites/e-commerce/items/cart2.png,$1133.82,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",14 reviews,
22,Acer Nitro 5 A...,/test-sites/e-commerce/allinone/product/109,/images/test-sites/e-commerce/items/cart2.png,$1140.62,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i7-...",14 reviews,
23,Dell Latitude...,/test-sites/e-commerce/allinone/product/112,/images/test-sites/e-commerce/items/cart2.png,$1144.4,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",10 reviews,
24,Lenovo Yoga 72...,/test-sites/e-commerce/allinone/product/114,/images/test-sites/e-commerce/items/cart2.png,$1149.73,"Lenovo Yoga 720 Grey, 15.6"" FHD IPS, Core i5-7...",12 reviews,
25,Dell Latitude...,/test-sites/e-commerce/allinone/product/117,/images/test-sites/e-commerce/items/cart2.png,$1178.19,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",6 reviews,
26,Dell Latitude...,/test-sites/e-commerce/allinone/product/119,/images/test-sites/e-commerce/items/cart2.png,$1187.88,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",5 reviews,
27,MSI GL62M 7REX...,/test-sites/e-commerce/allinone/product/122,/images/test-sites/e-commerce/items/cart2.png,$1199,"MSI GL62M 7REX2, 15.6"" FHD, Core i7-7700HQ, 8G...",12 reviews,
28,Lenovo IdeaPad...,/test-sites/e-commerce/allinone/product/125,/images/test-sites/e-commerce/items/cart2.png,$1212.16,"Lenovo IdeaPad Miix 510 Platinum Silver, 12.2""...",0 reviews,
29,Asus VivoBook...,/test-sites/e-commerce/allinone/product/127,/images/test-sites/e-commerce/items/cart2.png,$1235.49,"Asus VivoBook Pro 15 N580VN-FI006T Gold Metal,...",10 reviews,
30,ThinkPad X230,/test-sites/e-commerce/allinone/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews,
31,Dell Latitude...,/test-sites/e-commerce/allinone/product/132,/images/test-sites/e-commerce/items/cart2.png,$1271.06,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",13 reviews,
32,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/134,/images/test-sites/e-commerce/items/cart2.png,$1294.74,"Toshiba Portege Z30-C-16K Grey, 13.3"" FHD, Cor...",6 reviews,
33,ThinkPad X240,/test-sites/e-commerce/allinone/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews,
34,Dell Latitude...,/test-sites/e-commerce/allinone/product/139,/images/test-sites/e-commerce/items/cart2.png,$1337.28,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",6 reviews,
35,Apple MacBook...,/test-sites/e-commerce/allinone/product/142,/images/test-sites/e-commerce/items/cart2.png,$1347.78,"Apple MacBook Air 13"", Intel Core i5 1.8GHz, 8...",11 reviews,
36,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/145,/images/test-sites/e-commerce/items/cart2.png,$1366.32,"Toshiba Portege X20W-D-10V Black/Blue, 12.5"" F...",11 reviews,
37,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/147,/images/test-sites/e-commerce/items/cart2.png,$1399,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",10 reviews,
38,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews,

## 6.4 Extract all product details of first column save into csv file.

In [ ]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

In [36]:
all_products = main_div.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$321.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$356.49</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$364.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
 						Hewlett Packar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$372.7</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$391.48</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$393.88</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/70" itemprop="name" title="Acer Aspire 3 A315-21">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/45" itemprop="name" title="Asus VivoBook Max">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/71" itemprop="name" title="Asus VivoBook E502NA-GO022T Dark Blue">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">3</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$404.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/72" itemprop="name" title="Lenovo ThinkPad E31-80">
 						Lenovo ThinkPa...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$408.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/73" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,

In [37]:
list = []
for i in all_products[0:117:3]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [51]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q6_4.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Prestigio Smar...,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews,
1,Lenovo V110-15...,/test-sites/e-commerce/allinone/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,6 reviews,
2,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",0 reviews,
3,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",9 reviews,
4,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/72,/images/test-sites/e-commerce/items/cart2.png,$404.23,"Lenovo ThinkPad E31-80, 13.3"" HD, Celeron 3855...",12 reviews,
5,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/75,/images/test-sites/e-commerce/items/cart2.png,$410.46,"Acer Aspire ES1-732 Black, 17.3"" HD+, Celeron,...",14 reviews,
6,Asus EeeBook R...,/test-sites/e-commerce/allinone/product/77,/images/test-sites/e-commerce/items/cart2.png,$433.3,"Asus EeeBook R416NA-FA014T, 14"" FHD, Pentium N...",1 reviews,
7,Acer Extensa 1...,/test-sites/e-commerce/allinone/product/80,/images/test-sites/e-commerce/items/cart2.png,$439.73,"Acer Extensa 15 (2540) Black, 15.6"" HD, Core i...",6 reviews,
8,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/83,/images/test-sites/e-commerce/items/cart2.png,$457.38,"Acer Aspire A315-51-33TG, Black 15.6"" HD, Core...",9 reviews,
9,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/86,/images/test-sites/e-commerce/items/cart2.png,$469.1,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",5 reviews,
10,Lenovo V510 Bl...,/test-sites/e-commerce/allinone/product/89,/images/test-sites/e-commerce/items/cart2.png,$487.8,"Lenovo V510 Black, 15.6"" HD, Core i3-6006U, 4G...",9 reviews,
11,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/91,/images/test-sites/e-commerce/items/cart2.png,$494.71,"Acer Aspire 3 A315-51 Black, 15.6"" FHD, Core i...",2 reviews,
12,HP 250 G3,/test-sites/e-commerce/allinone/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews,
13,Aspire E1-572G,/test-sites/e-commerce/allinone/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews,
14,Dell Inspiron...,/test-sites/e-commerce/allinone/product/49,/images/test-sites/e-commerce/items/cart2.png,$679,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",7 reviews,
15,Inspiron 15,/test-sites/e-commerce/allinone/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews,
16,Asus ROG STRIX...,/test-sites/e-commerce/allinone/product/53,/images/test-sites/e-commerce/items/cart2.png,$899,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews,
17,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/94,/images/test-sites/e-commerce/items/cart2.png,$1096.02,"Lenovo ThinkPad L460, 14"" FHD IPS, Core i7-660...",14 reviews,
18,MSI GL72M 7RDX,/test-sites/e-commerce/allinone/product/97,/images/test-sites/e-commerce/items/cart2.png,$1099,"Asus ROG Strix GL553VD-DM535T, 15.6"" FHD, Core...",9 reviews,
19,Dell Latitude...,/test-sites/e-commerce/allinone/product/100,/images/test-sites/e-commerce/items/cart2.png,$1110.14,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",4 reviews,
20,Acer Predator...,/test-sites/e-commerce/allinone/product/103,/images/test-sites/e-commerce/items/cart2.png,$1123.87,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",1 reviews,
21,Dell Latitude...,/test-sites/e-commerce/allinone/product/106,/images/test-sites/e-commerce/items/cart2.png,$1133.82,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",14 reviews,
22,Acer Nitro 5 A...,/test-sites/e-commerce/allinone/product/109,/images/test-sites/e-commerce/items/cart2.png,$1140.62,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i7-...",14 reviews,
23,Dell Latitude...,/test-sites/e-commerce/allinone/product/112,/images/test-sites/e-commerce/items/cart2.png,$1144.4,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",10 reviews,
24,Lenovo Yoga 72...,/test-sites/e-commerce/allinone/product/114,/images/test-sites/e-commerce/items/cart2.png,$1149.73,"Lenovo Yoga 720 Grey, 15.6"" FHD IPS, Core i5-7...",12 reviews,
25,Dell Latitude...,/test-sites/e-commerce/allinone/product/117,/images/test-sites/e-commerce/items/cart2.png,$1178.19,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",6 reviews,
26,Dell Latitude...,/test-sites/e-commerce/allinone/product/119,/images/test-sites/e-commerce/items/cart2.png,$1187.88,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",5 reviews,
27,MSI GL62M 7REX...,/test-sites/e-commerce/allinone/product/122,/images/test-sites/e-commerce/items/cart2.png,$1199,"MSI GL62M 7REX2, 15.6"" FHD, Core i7-7700HQ, 8G...",12 reviews,
28,Lenovo IdeaPad...,/test-sites/e-commerce/allinone/product/125,/images/test-sites/e-commerce/items/cart2.png,$1212.16,"Lenovo IdeaPad Miix 510 Platinum Silver, 12.2""...",0 reviews,
29,Asus VivoBook...,/test-sites/e-commerce/allinone/product/127,/images/test-sites/e-commerce/items/cart2.png,$1235.49,"Asus VivoBook Pro 15 N580VN-FI006T Gold Metal,...",10 reviews,
30,ThinkPad X230,/test-sites/e-commerce/allinone/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews,
31,Dell Latitude...,/test-sites/e-commerce/allinone/product/132,/images/test-sites/e-commerce/items/cart2.png,$1271.06,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",13 reviews,
32,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/134,/images/test-sites/e-commerce/items/cart2.png,$1294.74,"Toshiba Portege Z30-C-16K Grey, 13.3"" FHD, Cor...",6 reviews,
33,ThinkPad X240,/test-sites/e-commerce/allinone/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews,
34,Dell Latitude...,/test-sites/e-commerce/allinone/product/139,/images/test-sites/e-commerce/items/cart2.png,$1337.28,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",6 reviews,
35,Apple MacBook...,/test-sites/e-commerce/allinone/product/142,/images/test-sites/e-commerce/items/cart2.png,$1347.78,"Apple MacBook Air 13"", Intel Core i5 1.8GHz, 8...",11 reviews,
36,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/145,/images/test-sites/e-commerce/items/cart2.png,$1366.32,"Toshiba Portege X20W-D-10V Black/Blue, 12.5"" F...",11 reviews,
37,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/147,/images/test-sites/e-commerce/items/cart2.png,$1399,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",10 reviews,
38,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews,

## 6.5 Extract all product details of Second column save into csv file.

In [ ]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

In [39]:
all_products = main_div.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$321.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$356.49</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$364.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
 						Hewlett Packar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$372.7</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$391.48</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$393.88</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/70" itemprop="name" title="Acer Aspire 3 A315-21">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/45" itemprop="name" title="Asus VivoBook Max">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/71" itemprop="name" title="Asus VivoBook E502NA-GO022T Dark Blue">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">3</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$404.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/72" itemprop="name" title="Lenovo ThinkPad E31-80">
 						Lenovo ThinkPa...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$408.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/73" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,

In [40]:
list = []
for i in all_products[1:117:3]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [45]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q6_5.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Prestigio Smar...,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews,
1,Lenovo V110-15...,/test-sites/e-commerce/allinone/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,6 reviews,
2,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",0 reviews,
3,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",9 reviews,
4,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/72,/images/test-sites/e-commerce/items/cart2.png,$404.23,"Lenovo ThinkPad E31-80, 13.3"" HD, Celeron 3855...",12 reviews,
5,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/75,/images/test-sites/e-commerce/items/cart2.png,$410.46,"Acer Aspire ES1-732 Black, 17.3"" HD+, Celeron,...",14 reviews,
6,Asus EeeBook R...,/test-sites/e-commerce/allinone/product/77,/images/test-sites/e-commerce/items/cart2.png,$433.3,"Asus EeeBook R416NA-FA014T, 14"" FHD, Pentium N...",1 reviews,
7,Acer Extensa 1...,/test-sites/e-commerce/allinone/product/80,/images/test-sites/e-commerce/items/cart2.png,$439.73,"Acer Extensa 15 (2540) Black, 15.6"" HD, Core i...",6 reviews,
8,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/83,/images/test-sites/e-commerce/items/cart2.png,$457.38,"Acer Aspire A315-51-33TG, Black 15.6"" HD, Core...",9 reviews,
9,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/86,/images/test-sites/e-commerce/items/cart2.png,$469.1,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",5 reviews,
10,Lenovo V510 Bl...,/test-sites/e-commerce/allinone/product/89,/images/test-sites/e-commerce/items/cart2.png,$487.8,"Lenovo V510 Black, 15.6"" HD, Core i3-6006U, 4G...",9 reviews,
11,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/91,/images/test-sites/e-commerce/items/cart2.png,$494.71,"Acer Aspire 3 A315-51 Black, 15.6"" FHD, Core i...",2 reviews,
12,HP 250 G3,/test-sites/e-commerce/allinone/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews,
13,Aspire E1-572G,/test-sites/e-commerce/allinone/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews,
14,Dell Inspiron...,/test-sites/e-commerce/allinone/product/49,/images/test-sites/e-commerce/items/cart2.png,$679,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",7 reviews,
15,Inspiron 15,/test-sites/e-commerce/allinone/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews,
16,Asus ROG STRIX...,/test-sites/e-commerce/allinone/product/53,/images/test-sites/e-commerce/items/cart2.png,$899,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews,
17,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/94,/images/test-sites/e-commerce/items/cart2.png,$1096.02,"Lenovo ThinkPad L460, 14"" FHD IPS, Core i7-660...",14 reviews,
18,MSI GL72M 7RDX,/test-sites/e-commerce/allinone/product/97,/images/test-sites/e-commerce/items/cart2.png,$1099,"Asus ROG Strix GL553VD-DM535T, 15.6"" FHD, Core...",9 reviews,
19,Dell Latitude...,/test-sites/e-commerce/allinone/product/100,/images/test-sites/e-commerce/items/cart2.png,$1110.14,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",4 reviews,
20,Acer Predator...,/test-sites/e-commerce/allinone/product/103,/images/test-sites/e-commerce/items/cart2.png,$1123.87,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",1 reviews,
21,Dell Latitude...,/test-sites/e-commerce/allinone/product/106,/images/test-sites/e-commerce/items/cart2.png,$1133.82,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",14 reviews,
22,Acer Nitro 5 A...,/test-sites/e-commerce/allinone/product/109,/images/test-sites/e-commerce/items/cart2.png,$1140.62,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i7-...",14 reviews,
23,Dell Latitude...,/test-sites/e-commerce/allinone/product/112,/images/test-sites/e-commerce/items/cart2.png,$1144.4,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",10 reviews,
24,Lenovo Yoga 72...,/test-sites/e-commerce/allinone/product/114,/images/test-sites/e-commerce/items/cart2.png,$1149.73,"Lenovo Yoga 720 Grey, 15.6"" FHD IPS, Core i5-7...",12 reviews,
25,Dell Latitude...,/test-sites/e-commerce/allinone/product/117,/images/test-sites/e-commerce/items/cart2.png,$1178.19,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",6 reviews,
26,Dell Latitude...,/test-sites/e-commerce/allinone/product/119,/images/test-sites/e-commerce/items/cart2.png,$1187.88,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",5 reviews,
27,MSI GL62M 7REX...,/test-sites/e-commerce/allinone/product/122,/images/test-sites/e-commerce/items/cart2.png,$1199,"MSI GL62M 7REX2, 15.6"" FHD, Core i7-7700HQ, 8G...",12 reviews,
28,Lenovo IdeaPad...,/test-sites/e-commerce/allinone/product/125,/images/test-sites/e-commerce/items/cart2.png,$1212.16,"Lenovo IdeaPad Miix 510 Platinum Silver, 12.2""...",0 reviews,
29,Asus VivoBook...,/test-sites/e-commerce/allinone/product/127,/images/test-sites/e-commerce/items/cart2.png,$1235.49,"Asus VivoBook Pro 15 N580VN-FI006T Gold Metal,...",10 reviews,
30,ThinkPad X230,/test-sites/e-commerce/allinone/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews,
31,Dell Latitude...,/test-sites/e-commerce/allinone/product/132,/images/test-sites/e-commerce/items/cart2.png,$1271.06,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",13 reviews,
32,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/134,/images/test-sites/e-commerce/items/cart2.png,$1294.74,"Toshiba Portege Z30-C-16K Grey, 13.3"" FHD, Cor...",6 reviews,
33,ThinkPad X240,/test-sites/e-commerce/allinone/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews,
34,Dell Latitude...,/test-sites/e-commerce/allinone/product/139,/images/test-sites/e-commerce/items/cart2.png,$1337.28,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",6 reviews,
35,Apple MacBook...,/test-sites/e-commerce/allinone/product/142,/images/test-sites/e-commerce/items/cart2.png,$1347.78,"Apple MacBook Air 13"", Intel Core i5 1.8GHz, 8...",11 reviews,
36,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/145,/images/test-sites/e-commerce/items/cart2.png,$1366.32,"Toshiba Portege X20W-D-10V Black/Blue, 12.5"" F...",11 reviews,
37,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/147,/images/test-sites/e-commerce/items/cart2.png,$1399,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",10 reviews,
38,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews,

## 6.6 Extract all product details of thirst column save into csv file.

In [ ]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

In [42]:
all_products = main_div.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$295.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/60" itemprop="name" title="Asus VivoBook X441NA-GA190">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook X441NA-GA190 Chocolate Black, 14", Celeron N3450, 4GB, 128GB SSD, Endless OS, ENG kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">14</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/61" itemprop="name" title="Prestigio SmartBook 133S Dark Grey">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Dark Grey, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$299</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/62" itemprop="name" title="Prestigio SmartBook 133S Gold">
 						Prestigio Smar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Prestigio SmartBook 133S Gold, 13.3" FHD IPS, Celeron N3350 1.1GHz, 4GB, 32GB, Windows 10 Pro + Office 365 1 gadam</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$321.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/63" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo V110-15IAP, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">5</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$356.49</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/64" itemprop="name" title="Lenovo V110-15IAP">
 						Lenovo V110-15...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook 15 X540NA-GQ008T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 500GB, Windows 10 Home, En kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">6</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$364.46</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/65" itemprop="name" title="Hewlett Packard 250 G6 Dark Ash Silver">
 						Hewlett Packar...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Hewlett Packard 250 G6 Dark Ash Silver, 15.6" HD, Celeron N3060 1.6GHz, 4GB, 128GB SSD, DOS</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$372.7</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/66" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Celeron N3350 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.94</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/67" itemprop="name" title="Acer Aspire A315-31-C33J">
 						Acer Aspire A3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire A315-31-C33J Black 15.6", HD, Celeron N3350, 4GB DDR3L, 128GB, Windows 10 Home, ENG</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">0</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$379.95</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/68" itemprop="name" title="Acer Aspire ES1-572 Black">
 						Acer Aspire ES...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire ES1-572 Black, 15.6" HD, Core i3-6006U, 4GB, 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$391.48</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/69" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$393.88</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/70" itemprop="name" title="Acer Aspire 3 A315-21">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-21, 15.6", AMD A4-9120. 4GB. 128GB SSD, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">9</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/45" itemprop="name" title="Asus VivoBook Max">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook Max X541NA-GQ041 Black Chocolate, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 500GB, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$399.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/71" itemprop="name" title="Asus VivoBook E502NA-GO022T Dark Blue">
 						Asus VivoBook...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Asus VivoBook E502NA-GO022T Dark Blue, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">3</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$404.23</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/72" itemprop="name" title="Lenovo ThinkPad E31-80">
 						Lenovo ThinkPa...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Lenovo ThinkPad E31-80, 13.3" HD, Celeron 3855U 1.6GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$408.98</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/allinone/product/73" itemprop="name" title="Acer Aspire 3 A315-31 Black">
 						Acer Aspire 3...
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Acer Aspire 3 A315-31 Black, 15.6" HD, Pentium N4200 1.1GHz, 4GB, 128GB SSD, Windows 10 Home</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,

In [43]:
list = []
for i in all_products[2:117:3]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [46]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q6_6.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Prestigio Smar...,/test-sites/e-commerce/allinone/product/62,/images/test-sites/e-commerce/items/cart2.png,$299,"Prestigio SmartBook 133S Gold, 13.3"" FHD IPS, ...",12 reviews,
1,Lenovo V110-15...,/test-sites/e-commerce/allinone/product/64,/images/test-sites/e-commerce/items/cart2.png,$356.49,Asus VivoBook 15 X540NA-GQ008T Chocolate Black...,6 reviews,
2,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/67,/images/test-sites/e-commerce/items/cart2.png,$379.94,"Acer Aspire A315-31-C33J Black 15.6"", HD, Cele...",0 reviews,
3,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/70,/images/test-sites/e-commerce/items/cart2.png,$393.88,"Acer Aspire 3 A315-21, 15.6"", AMD A4-9120. 4GB...",9 reviews,
4,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/72,/images/test-sites/e-commerce/items/cart2.png,$404.23,"Lenovo ThinkPad E31-80, 13.3"" HD, Celeron 3855...",12 reviews,
5,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/75,/images/test-sites/e-commerce/items/cart2.png,$410.46,"Acer Aspire ES1-732 Black, 17.3"" HD+, Celeron,...",14 reviews,
6,Asus EeeBook R...,/test-sites/e-commerce/allinone/product/77,/images/test-sites/e-commerce/items/cart2.png,$433.3,"Asus EeeBook R416NA-FA014T, 14"" FHD, Pentium N...",1 reviews,
7,Acer Extensa 1...,/test-sites/e-commerce/allinone/product/80,/images/test-sites/e-commerce/items/cart2.png,$439.73,"Acer Extensa 15 (2540) Black, 15.6"" HD, Core i...",6 reviews,
8,Acer Aspire A3...,/test-sites/e-commerce/allinone/product/83,/images/test-sites/e-commerce/items/cart2.png,$457.38,"Acer Aspire A315-51-33TG, Black 15.6"" HD, Core...",9 reviews,
9,Acer Aspire ES...,/test-sites/e-commerce/allinone/product/86,/images/test-sites/e-commerce/items/cart2.png,$469.1,"Acer Aspire ES1-572 Black, 15.6"" HD, Core i3-6...",5 reviews,
10,Lenovo V510 Bl...,/test-sites/e-commerce/allinone/product/89,/images/test-sites/e-commerce/items/cart2.png,$487.8,"Lenovo V510 Black, 15.6"" HD, Core i3-6006U, 4G...",9 reviews,
11,Acer Aspire 3...,/test-sites/e-commerce/allinone/product/91,/images/test-sites/e-commerce/items/cart2.png,$494.71,"Acer Aspire 3 A315-51 Black, 15.6"" FHD, Core i...",2 reviews,
12,HP 250 G3,/test-sites/e-commerce/allinone/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews,
13,Aspire E1-572G,/test-sites/e-commerce/allinone/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews,
14,Dell Inspiron...,/test-sites/e-commerce/allinone/product/49,/images/test-sites/e-commerce/items/cart2.png,$679,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",7 reviews,
15,Inspiron 15,/test-sites/e-commerce/allinone/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews,
16,Asus ROG STRIX...,/test-sites/e-commerce/allinone/product/53,/images/test-sites/e-commerce/items/cart2.png,$899,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews,
17,Lenovo ThinkPa...,/test-sites/e-commerce/allinone/product/94,/images/test-sites/e-commerce/items/cart2.png,$1096.02,"Lenovo ThinkPad L460, 14"" FHD IPS, Core i7-660...",14 reviews,
18,MSI GL72M 7RDX,/test-sites/e-commerce/allinone/product/97,/images/test-sites/e-commerce/items/cart2.png,$1099,"Asus ROG Strix GL553VD-DM535T, 15.6"" FHD, Core...",9 reviews,
19,Dell Latitude...,/test-sites/e-commerce/allinone/product/100,/images/test-sites/e-commerce/items/cart2.png,$1110.14,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",4 reviews,
20,Acer Predator...,/test-sites/e-commerce/allinone/product/103,/images/test-sites/e-commerce/items/cart2.png,$1123.87,"Acer Predator Helios 300 (PH317-51), 17.3"" FHD...",1 reviews,
21,Dell Latitude...,/test-sites/e-commerce/allinone/product/106,/images/test-sites/e-commerce/items/cart2.png,$1133.82,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",14 reviews,
22,Acer Nitro 5 A...,/test-sites/e-commerce/allinone/product/109,/images/test-sites/e-commerce/items/cart2.png,$1140.62,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i7-...",14 reviews,
23,Dell Latitude...,/test-sites/e-commerce/allinone/product/112,/images/test-sites/e-commerce/items/cart2.png,$1144.4,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",10 reviews,
24,Lenovo Yoga 72...,/test-sites/e-commerce/allinone/product/114,/images/test-sites/e-commerce/items/cart2.png,$1149.73,"Lenovo Yoga 720 Grey, 15.6"" FHD IPS, Core i5-7...",12 reviews,
25,Dell Latitude...,/test-sites/e-commerce/allinone/product/117,/images/test-sites/e-commerce/items/cart2.png,$1178.19,"Dell Latitude 5580, 15.6"" FHD, Core i5-7300U, ...",6 reviews,
26,Dell Latitude...,/test-sites/e-commerce/allinone/product/119,/images/test-sites/e-commerce/items/cart2.png,$1187.88,"Dell Latitude 5480, 14"" FHD, Core i5-7300U, 8G...",5 reviews,
27,MSI GL62M 7REX...,/test-sites/e-commerce/allinone/product/122,/images/test-sites/e-commerce/items/cart2.png,$1199,"MSI GL62M 7REX2, 15.6"" FHD, Core i7-7700HQ, 8G...",12 reviews,
28,Lenovo IdeaPad...,/test-sites/e-commerce/allinone/product/125,/images/test-sites/e-commerce/items/cart2.png,$1212.16,"Lenovo IdeaPad Miix 510 Platinum Silver, 12.2""...",0 reviews,
29,Asus VivoBook...,/test-sites/e-commerce/allinone/product/127,/images/test-sites/e-commerce/items/cart2.png,$1235.49,"Asus VivoBook Pro 15 N580VN-FI006T Gold Metal,...",10 reviews,
30,ThinkPad X230,/test-sites/e-commerce/allinone/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews,
31,Dell Latitude...,/test-sites/e-commerce/allinone/product/132,/images/test-sites/e-commerce/items/cart2.png,$1271.06,"Dell Latitude 5480, 14"" FHD, Core i7-7600U, 8G...",13 reviews,
32,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/134,/images/test-sites/e-commerce/items/cart2.png,$1294.74,"Toshiba Portege Z30-C-16K Grey, 13.3"" FHD, Cor...",6 reviews,
33,ThinkPad X240,/test-sites/e-commerce/allinone/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews,
34,Dell Latitude...,/test-sites/e-commerce/allinone/product/139,/images/test-sites/e-commerce/items/cart2.png,$1337.28,"Dell Latitude 5580, 15.6"" FHD, Core i7-7600U, ...",6 reviews,
35,Apple MacBook...,/test-sites/e-commerce/allinone/product/142,/images/test-sites/e-commerce/items/cart2.png,$1347.78,"Apple MacBook Air 13"", Intel Core i5 1.8GHz, 8...",11 reviews,
36,Toshiba Porteg...,/test-sites/e-commerce/allinone/product/145,/images/test-sites/e-commerce/items/cart2.png,$1366.32,"Toshiba Portege X20W-D-10V Black/Blue, 12.5"" F...",11 reviews,
37,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/147,/images/test-sites/e-commerce/items/cart2.png,$1399,"Asus ROG Strix GL702VM-GC146T, 17.3"" FHD, Core...",10 reviews,
38,Asus ROG Strix...,/test-sites/e-commerce/allinone/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews,

## 7.1 Extract first product details save into csv file. e.g# Packard 255 G2
## https://webscraper.io/test-sites/e-commerce/static/computers/laptops

In [67]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/static/computers/laptops')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="W4PkJV7B9LgvBOdMNw8b7ZQsQluIcU0e">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Static | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
  <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
  <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
  <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
  <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
  <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
  <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
  <link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" rel="canonical"/>
  <meta content="Static | Web Scraper Test Sites" property="og:title"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
  <meta content="website" property="og:type"/>
  <meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops" property="og:url"/>
  <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
  <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
  </script>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-site">
    <div class="row">
     <div class="col-lg-3 sidebar">
      <div class="navbar-light sidebar" role="navigation">
       <div class="sidebar-nav navbar-collapse">
        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
         <li class="nav-item">
          <a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url">
           <span itemprop="name">
            Home
           </span>
          </a>
         </li>
         <li class="nav-item active">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">
           <span itemprop="name">
            Computers
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">
             <span itemprop="name">
              Laptops
             </span>
            </a>
           </li>
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">
             <span itemprop="name">
              Tablets
             </span>
            </a>
           </li>
          </ul>
         </li>
         <li class="nav-item">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">
           <span itemprop="name">
            Phones
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
         </li>
        </ul>
       </div>
      </div>
     </div>
     <div class="col-lg-9">
      <h1 class="page-header">
       Computers / Laptops
      </h1>
      <div class="row">
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $416.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
             Packard 255 G2
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             2
            </span>
            reviews
           </p>
           <p data-rating="2">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $306.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">
             Aspire E1-510
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             2
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $1178.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">
             ThinkPad T540p
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             2
            </span>
            reviews
           </p>
           <p data-rating="1">
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $739.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">
             ProBook
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             8
            </span>
            reviews
           </p>
           <p data-rating="4">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $1311.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">
             ThinkPad X240
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             12
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $581.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">
             Aspire E1-572G
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             2
            </span>
            reviews
           </p>
           <p data-rating="1">
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
      </div>
      <div id="static-pagination">
       <nav>
        <ul class="pagination">
         <li aria-disabled="true" aria-label="« Previous" class="page-item disabled">
          <span aria-hidden="true" class="page-link">
           ‹
          </span>
         </li>
         <li aria-current="page" class="page-item active">
          <span class="page-link">
           1
          </span>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=2">
           2
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">
           3
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">
           4
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">
           5
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">
           6
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=7">
           7
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=8">
           8
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=9">
           9
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=10">

In [70]:
all_products = soup.find("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products.text

'\n\n\n\n\n\n$416.99\n\n\n\n\n\t\t\t\t\t\tPackard 255 G2\n\t\t\t\t\t\n\n15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1\n\n\n\n2 reviews\n\t\t\t\t\n\n\n\n\n\n\n\n'

In [ ]:
all_products

In [71]:
list = []
prod_dictionary = {
    'product_name': '',
    'product_link': '',
    'product_img': '',
    'product_price': '',
    'product_details': '',
    'product_reviews_number': '',
    'product_reviews_star_number': '',
}

In [72]:
prod_dictionary['product_name']= all_products.find('a').text.strip()
prod_dictionary['product_details']=all_products.find('p').text
prod_dictionary['product_img']=all_products.find('img')['src']
prod_dictionary['product_link']=all_products.find('a')['href']
prod_dictionary['product_reviews_number']=all_products.find('div',class_='ratings').text.strip()
prod_dictionary['product_reviews_star_number']
prod_dictionary['product_price']=all_products.find('h4').text.strip()
list.append(prod_dictionary)

In [73]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q7_1.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,/images/test-sites/e-commerce/items/cart2.png,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2 reviews,

## 7.2 Extract product details from first row & save into csv file. e.g# Packard 255 G2, Aspire E1-510, ThinkPad T540p

In [ ]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/static/computers/laptops')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

In [75]:
all_products = soup.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$416.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
 						Packard 255 G2
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1178.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">
 						ThinkPad T540p
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$739.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">
 						ProBook
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1311.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">
 						ThinkPad X240
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$581.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">
 						Aspire E1-572G
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>]

In [76]:
list = []
for i in all_products[0:3]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [77]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q7_2.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,/images/test-sites/e-commerce/items/cart2.png,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2 reviews,
1,Aspire E1-510,/test-sites/e-commerce/static/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews,
2,ThinkPad T540p,/test-sites/e-commerce/static/product/33,/images/test-sites/e-commerce/items/cart2.png,$1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",2 reviews,

## 7.3 Extract all product details from first page & save into csv file.

In [ ]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/static/computers/laptops')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

In [80]:
all_products = soup.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$416.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
 						Packard 255 G2
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$306.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">
 						Aspire E1-510
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Pentium N3520 2.16GHz, 4GB, 500GB, Linux</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1178.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">
 						ThinkPad T540p
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$739.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">
 						ProBook
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">14", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">8</span> reviews
 				</p>
 <p data-rating="4">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1311.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">
 						ThinkPad X240
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">12.5", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$581.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">
 						Aspire E1-572G
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 8GB, 1TB, Radeon R7 M265, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>]

In [81]:
list = []
for i in all_products[0:6]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [82]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q7_3.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,/images/test-sites/e-commerce/items/cart2.png,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2 reviews,
1,Aspire E1-510,/test-sites/e-commerce/static/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews,
2,ThinkPad T540p,/test-sites/e-commerce/static/product/33,/images/test-sites/e-commerce/items/cart2.png,$1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",2 reviews,
3,ProBook,/test-sites/e-commerce/static/product/34,/images/test-sites/e-commerce/items/cart2.png,$739.99,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",8 reviews,
4,ThinkPad X240,/test-sites/e-commerce/static/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews,
5,Aspire E1-572G,/test-sites/e-commerce/static/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews,

## 7.4 Extract all product details from second page & save into another csv file.

In [83]:
import requests
from bs4 import BeautifulSoup
response = requests.get('https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page=2')
response.status_code
soup = BeautifulSoup(response.text,('html'))
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- Google Tag Manager -->
  <script nonce="H8kFcMCfLmymRuwlD681mM1LGdb0OoOJ">
   (function (w, d, s, l, i) {
		w[l] = w[l] || [];
		w[l].push({
			'gtm.start':
				new Date().getTime(), event: 'gtm.js'
		});
		var f = d.getElementsByTagName(s)[0],
			j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
		j.async = true;
		j.src =
			'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
		f.parentNode.insertBefore(j, f);
	})(window, document, 'script', 'dataLayer', 'GTM-NVFPDWB');
  </script>
  <!-- End Google Tag Manager -->
  <title>
   Static | Web Scraper Test Sites
  </title>
  <meta charset="utf-8"/>
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
  <meta content="web scraping,Web Scraper,Chrome extension,Crawling,Cross platform scraper" name="keywords"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." name="description"/>
  <link href="/favicon.png" rel="icon" sizes="128x128" type="image/png"/>
  <link href="/favicon.ico" rel="icon" sizes="16x16 32x32" type="image/x-icon"/>
  <link href="/logo-icon.png" rel="apple-touch-icon" type="image/png"/>
  <link href="/icon.svg" rel="icon" type="image/svg+xml"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <link href="https://fonts.googleapis.com" rel="preconnect"/>
  <link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet"/>
  <link href="/css/app.css?id=37e354cd0cf06349d7ad09f2f5065e98" rel="stylesheet"/>
  <link href="/css/ws-icons.font.css?id=d8505f3d910cc64df752f712c8032fdb" rel="stylesheet"/>
  <link href="https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page=2" rel="canonical"/>
  <meta content="Static | Web Scraper Test Sites" property="og:title"/>
  <meta content="Test Web Scraper's features and performance on mock e-commerce sites. Extract product data, prices, and categories in a controlled environment." property="og:description"/>
  <meta content="website" property="og:type"/>
  <meta content="https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page=2" property="og:url"/>
  <meta content="https://webscraper.io/webscraper-logo-header.png" property="og:image"/>
  <script defer="" src="/js/app.js?id=08b634a892b70c890a9c8f6190db952b">
  </script>
 </head>
 <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-NVFPDWB" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <header class="navbar fixed-top navbar-expand-lg navbar-dark navbar-static svg-background" id="navbar-top" role="banner">
   <div class="container">
    <div class="navbar-header">
     <a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
      <button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
       <span class="visually-hidden">
        Toggle navigation
       </span>
       <span class="icon-bar top-bar">
       </span>
       <span class="icon-bar middle-bar">
       </span>
       <span class="icon-bar bottom-bar">
       </span>
       <span class="icon-bar extra-bottom-bar">
       </span>
      </button>
     </a>
     <div class="navbar-brand">
      <a href="/">
       <img alt="Web Scraper" height="50px" src="/img/logo_white.svg" width="150px"/>
      </a>
     </div>
    </div>
    <div class="side-collapse in">
     <nav class="navbar-collapse collapse" id="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-right">
       <li class="nav-item">
        <a class="nav-link menuitm" href="/">
         <p>
          Web Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
         <p>
          Cloud Scraper
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
         <p>
          Pricing
         </p>
         <div class="crta">
         </div>
        </a>
       </li>
       <li class="nav-item dropdown">
        <button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
         <p>
          Learn
          <i class="ws-icon ws-icon-down">
          </i>
         </p>
         <span class="crta">
         </span>
        </button>
        <ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
         <li>
          <a class="dropdown-item" href="/documentation">
           Documentation
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/tutorials">
           Video Tutorials
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="/test-sites">
           Test Sites
          </a>
         </li>
         <li>
          <a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">
           Forum
          </a>
         </li>
        </ul>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" rel="noopener" target="_blank">
         <i aria-hidden="true" class="browser-icon ws-icon ws-icon-chrome-500">
         </i>
         Install
        </a>
       </li>
       <li class="nav-item">
        <a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">
         Cloud Login
        </a>
       </li>
      </ul>
     </nav>
    </div>
   </div>
  </header>
  <div class="wrapper">
   <div class="formenu-here container-fluid">
   </div>
   <div class="container-fluid blog-hero">
    <div class="container">
     <div class="row">
      <div class="col-lg-12">
       <h1>
        Test Sites
       </h1>
      </div>
     </div>
    </div>
   </div>
   <div class="container test-site">
    <div class="row">
     <div class="col-lg-3 sidebar">
      <div class="navbar-light sidebar" role="navigation">
       <div class="sidebar-nav navbar-collapse">
        <ul class="nav flex-column" id="side-menu" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
         <li class="nav-item">
          <a class="nav-link" href="/test-sites/e-commerce/static" itemprop="url">
           <span itemprop="name">
            Home
           </span>
          </a>
         </li>
         <li class="nav-item active">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/computers" itemprop="url">
           <span itemprop="name">
            Computers
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
          <ul class="nav nav-second-level" itemscope="" itemtype="https://schema.org/SiteNavigationElement">
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link active" href="/test-sites/e-commerce/static/computers/laptops" itemprop="url">
             <span itemprop="name">
              Laptops
             </span>
            </a>
           </li>
           <li class="nav-item">
            <a aria-label="Navigation subcategory" class="nav-link subcategory-link" href="/test-sites/e-commerce/static/computers/tablets" itemprop="url">
             <span itemprop="name">
              Tablets
             </span>
            </a>
           </li>
          </ul>
         </li>
         <li class="nav-item">
          <a aria-label="Navigation category" class="category-link nav-link" href="/test-sites/e-commerce/static/phones" itemprop="url">
           <span itemprop="name">
            Phones
           </span>
           <i aria-hidden="true" class="ws-icon ws-icon-right">
           </i>
          </a>
         </li>
        </ul>
       </div>
      </div>
     </div>
     <div class="col-lg-9">
      <h1 class="page-header">
       Computers / Laptops
      </h1>
      <div class="row">
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $1033.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/37" itemprop="name" title="ThinkPad Yoga">
             ThinkPad Yoga
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             13
            </span>
            reviews
           </p>
           <p data-rating="2">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $609.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/38" itemprop="name" title="Pavilion">
             Pavilion
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             4
            </span>
            reviews
           </p>
           <p data-rating="1">
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $745.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/39" itemprop="name" title="Inspiron 15">
             Inspiron 15
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             12
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $1281.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/40" itemprop="name" title="Dell XPS 13">
             Dell XPS 13
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             4
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $1244.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/41" itemprop="name" title="ThinkPad X230">
             ThinkPad X230
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             10
            </span>
            reviews
           </p>
           <p data-rating="3">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
       <div class="col-md-4 col-xl-4 col-lg-4">
        <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
         <div class="product-wrapper card-body">
          <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
          <div class="caption">
           <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
            <span itemprop="price">
             $520.99
            </span>
            <meta content="USD" itemprop="priceCurrency"/>
           </h4>
           <h4>
            <a class="title" href="/test-sites/e-commerce/static/product/42" itemprop="name" title="HP 250 G3">
             HP 250 G3
            </a>
           </h4>
           <p class="description card-text" itemprop="description">
            15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1
           </p>
          </div>
          <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
           <p class="review-count float-end">
            <span itemprop="reviewCount">
             13
            </span>
            reviews
           </p>
           <p data-rating="2">
            <span class="ws-icon ws-icon-star">
            </span>
            <span class="ws-icon ws-icon-star">
            </span>
           </p>
          </div>
         </div>
        </div>
       </div>
      </div>
      <div id="static-pagination">
       <nav>
        <ul class="pagination">
         <li class="page-item">
          <a aria-label="« Previous" class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=1" rel="prev">
           ‹
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=1">
           1
          </a>
         </li>
         <li aria-current="page" class="page-item active">
          <span class="page-link">
           2
          </span>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=3">
           3
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=4">
           4
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=5">
           5
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=6">
           6
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=7">
           7
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=8">
           8
          </a>
         </li>
         <li class="page-item">
          <a class="page-link" href="/test-sites/e-commerce/static/computers/laptops?page=9">
           9
          </a>
         </li>
         <li class="page-item">

In [84]:
all_products = soup.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")
all_products

[<div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1033.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/37" itemprop="name" title="ThinkPad Yoga">
 						ThinkPad Yoga
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">12.5" Touch, Core i3-4010U, 4GB, 500GB + 16GB SSD Cache,</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">13</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$609.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/38" itemprop="name" title="Pavilion">
 						Pavilion
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4200U, 6GB, 750GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="1">
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$745.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/39" itemprop="name" title="Inspiron 15">
 						Inspiron 15
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">Moon Silver, 15.6", Core i7-4510U, 8GB, 1TB, Radeon HD R7 M265 2GB,</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">12</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1281.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/40" itemprop="name" title="Dell XPS 13">
 						Dell XPS 13
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">13.3" Touch, Core i5-4210U, 8GB, 128GB SSD, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">4</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$1244.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/41" itemprop="name" title="ThinkPad X230">
 						ThinkPad X230
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">12.5", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pro 64bit</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">10</span> reviews
 				</p>
 <p data-rating="3">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>,
 <div class="col-md-4 col-xl-4 col-lg-4">
 <div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$520.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/42" itemprop="name" title="HP 250 G3">
 						HP 250 G3
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", Core i5-4210U, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">13</span> reviews
 				</p>
 <p data-rating="2">
 <span class="ws-icon ws-icon-star"></span>
 <span class="ws-icon ws-icon-star"></span>
 </p>
 </div>
 </div>
 </div>
 </div>]

In [85]:
list = []
for i in all_products[0:6]:
    prod_dictionary = {
        'product_name': '',
        'product_link': '',
        'product_img': '',
        'product_price': '',
        'product_details': '',
        'product_reviews_number': '',
        'product_reviews_star_number': '',
    }
    prod_dictionary['product_name']= i.find('a').text.strip()
    prod_dictionary['product_details']=i.find('p').text
    prod_dictionary['product_img']=i.find('img')['src']
    prod_dictionary['product_link']=i.find('a')['href']
    prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
    prod_dictionary['product_reviews_star_number']
    prod_dictionary['product_price']=i.find('h4').text.strip()
    list.append(prod_dictionary)

In [86]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q7_4.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,ThinkPad Yoga,/test-sites/e-commerce/static/product/37,/images/test-sites/e-commerce/items/cart2.png,$1033.99,"12.5"" Touch, Core i3-4010U, 4GB, 500GB + 16GB ...",13 reviews,
1,Pavilion,/test-sites/e-commerce/static/product/38,/images/test-sites/e-commerce/items/cart2.png,$609.99,"15.6"", Core i5-4200U, 6GB, 750GB, Windows 8.1",4 reviews,
2,Inspiron 15,/test-sites/e-commerce/static/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews,
3,Dell XPS 13,/test-sites/e-commerce/static/product/40,/images/test-sites/e-commerce/items/cart2.png,$1281.99,"13.3"" Touch, Core i5-4210U, 8GB, 128GB SSD, Wi...",4 reviews,
4,ThinkPad X230,/test-sites/e-commerce/static/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews,
5,HP 250 G3,/test-sites/e-commerce/static/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews,

## 7.5 Extract all product details from first page to fifth page & save into single csv file.

In [87]:
import requests
from bs4 import BeautifulSoup
# url = 'https://webscraper.io/test-sites/e-commerce/static/computers/laptops='
url = "https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page="

In [88]:
list = []
for i in range(1,6):
    url_b = url+str(i)
    response = requests.get(url_b)
    print(response.status_code)
    soup = BeautifulSoup(response.text,('html'))
    all_products = soup.find_all("div",class_="col-md-4 col-xl-4 col-lg-4")


    # print(soup.prettify())
    
    for i in all_products:
        prod_dictionary = {
            'product_name': '',
            'product_link': '',
            'product_img': '',
            'product_price': '',
            'product_details': '',
            'product_reviews_number': '',
            'product_reviews_star_number': '',
        }
        prod_dictionary['product_name']= i.find('a').text.strip()
        prod_dictionary['product_details']=i.find('p').text
        prod_dictionary['product_img']=i.find('img')['src']
        prod_dictionary['product_link']=i.find('a')['href']
        prod_dictionary['product_reviews_number']=i.find('div',class_='ratings').text.strip()
        prod_dictionary['product_reviews_star_number']
        prod_dictionary['product_price']=i.find('h4').text.strip()
        list.append(prod_dictionary)

200
200
200
200
200

In [90]:
import pandas as pd 
df = pd.DataFrame(list)
df
df.to_csv('webscraper q7_5.csv',index=False)
df

,product_name,product_link,product_img,product_price,product_details,product_reviews_number,product_reviews_star_number
0,Packard 255 G2,/test-sites/e-commerce/static/product/31,/images/test-sites/e-commerce/items/cart2.png,$416.99,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",2 reviews,
1,Aspire E1-510,/test-sites/e-commerce/static/product/32,/images/test-sites/e-commerce/items/cart2.png,$306.99,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",2 reviews,
2,ThinkPad T540p,/test-sites/e-commerce/static/product/33,/images/test-sites/e-commerce/items/cart2.png,$1178.99,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",2 reviews,
3,ProBook,/test-sites/e-commerce/static/product/34,/images/test-sites/e-commerce/items/cart2.png,$739.99,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",8 reviews,
4,ThinkPad X240,/test-sites/e-commerce/static/product/35,/images/test-sites/e-commerce/items/cart2.png,$1311.99,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",12 reviews,
5,Aspire E1-572G,/test-sites/e-commerce/static/product/36,/images/test-sites/e-commerce/items/cart2.png,$581.99,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",2 reviews,
6,ThinkPad Yoga,/test-sites/e-commerce/static/product/37,/images/test-sites/e-commerce/items/cart2.png,$1033.99,"12.5"" Touch, Core i3-4010U, 4GB, 500GB + 16GB ...",13 reviews,
7,Pavilion,/test-sites/e-commerce/static/product/38,/images/test-sites/e-commerce/items/cart2.png,$609.99,"15.6"", Core i5-4200U, 6GB, 750GB, Windows 8.1",4 reviews,
8,Inspiron 15,/test-sites/e-commerce/static/product/39,/images/test-sites/e-commerce/items/cart2.png,$745.99,"Moon Silver, 15.6"", Core i7-4510U, 8GB, 1TB, R...",12 reviews,
9,Dell XPS 13,/test-sites/e-commerce/static/product/40,/images/test-sites/e-commerce/items/cart2.png,$1281.99,"13.3"" Touch, Core i5-4210U, 8GB, 128GB SSD, Wi...",4 reviews,
10,ThinkPad X230,/test-sites/e-commerce/static/product/41,/images/test-sites/e-commerce/items/cart2.png,$1244.99,"12.5"", Core i5 2.6GHz, 8GB, 180GB SSD, Win7 Pr...",10 reviews,
11,HP 250 G3,/test-sites/e-commerce/static/product/42,/images/test-sites/e-commerce/items/cart2.png,$520.99,"15.6"", Core i5-4210U, 4GB, 500GB, Windows 8.1",13 reviews,
12,ThinkPad Yoga,/test-sites/e-commerce/static/product/43,/images/test-sites/e-commerce/items/cart2.png,$1223.99,"12.5"" Touch, Core i5 4200U, 8GB, 500GB + 16GB ...",2 reviews,
13,HP 350 G1,/test-sites/e-commerce/static/product/44,/images/test-sites/e-commerce/items/cart2.png,$577.99,"15.6"", Core i5-4200U, 4GB, 750GB, Radeon HD867...",10 reviews,
14,Asus VivoBook...,/test-sites/e-commerce/static/product/45,/images/test-sites/e-commerce/items/cart2.png,$399,Asus VivoBook Max X541NA-GQ041 Black Chocolate...,4 reviews,
15,Dell Vostro 15,/test-sites/e-commerce/static/product/46,/images/test-sites/e-commerce/items/cart2.png,$488.78,"Dell Vostro 15 (3568) Black, 15.6"" FHD, Core i...",14 reviews,
16,Acer Spin 5,/test-sites/e-commerce/static/product/47,/images/test-sites/e-commerce/items/cart2.png,$564.98,"Acer Spin 5 SP513-51 Black, 13.3"" FHD Touch, C...",0 reviews,
17,Acer Aspire A5...,/test-sites/e-commerce/static/product/48,/images/test-sites/e-commerce/items/cart2.png,$679,"Acer Aspire A515-51-5654, Black, 15.6"", FHD, C...",9 reviews,
18,Dell Inspiron...,/test-sites/e-commerce/static/product/49,/images/test-sites/e-commerce/items/cart2.png,$679,"Dell Inspiron 15 (5567) Fog Gray, 15.6"" FHD, C...",7 reviews,
19,Asus VivoBook...,/test-sites/e-commerce/static/product/50,/images/test-sites/e-commerce/items/cart2.png,$729,"Asus VivoBook S14 (S406UA-BV041T) Starry Grey,...",2 reviews,
20,Asus ROG STRIX...,/test-sites/e-commerce/static/product/51,/images/test-sites/e-commerce/items/cart2.png,$799,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews,
21,Acer Nitro 5 A...,/test-sites/e-commerce/static/product/52,/images/test-sites/e-commerce/items/cart2.png,$809,"Acer Nitro 5 AN515-51, 15.6"" FHD IPS, Core i5-...",0 reviews,
22,Asus ROG STRIX...,/test-sites/e-commerce/static/product/53,/images/test-sites/e-commerce/items/cart2.png,$899,"Asus ROG STRIX GL553VD-DM256, 15.6"" FHD, Core ...",7 reviews,
23,Lenovo ThinkPa...,/test-sites/e-commerce/static/product/54,/images/test-sites/e-commerce/items/cart2.png,$999,"Lenovo ThinkPad L570, 15.6"" FHD, Core i7-7500U...",11 reviews,
24,Lenovo Legion...,/test-sites/e-commerce/static/product/55,/images/test-sites/e-commerce/items/cart2.png,$1149,"Lenovo Legion Y520-15IKBM, 15.6"" FHD IPS, Core...",11 reviews,
25,Lenovo Legion...,/test-sites/e-commerce/static/product/56,/images/test-sites/e-commerce/items/cart2.png,$1399,"Lenovo Legion Y720, 15.6"" FHD IPS, Core i7-770...",8 reviews,
26,Asus ROG Strix...,/test-sites/e-commerce/static/product/57,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC154T, 17.3"" FHD, Ryze...",7 reviews,
27,Asus ROG Strix...,/test-sites/e-commerce/static/product/58,/images/test-sites/e-commerce/items/cart2.png,$1769,"Asus ROG Strix GL702ZC-GC209T, 17.3"" FHD IPS, ...",8 reviews,
28,Asus ROG Strix...,/test-sites/e-commerce/static/product/59,/images/test-sites/e-commerce/items/cart2.png,$1799,"Asus ROG Strix SCAR Edition GL503VM-ED115T, 15...",8 reviews,
29,Asus VivoBook...,/test-sites/e-commerce/static/product/60,/images/test-sites/e-commerce/items/cart2.png,$295.99,"Asus VivoBook X441NA-GA190 Chocolate Black, 14...",14 reviews,